WIP - (DOCSP-14573): set data type
mongodb/docs-realm pull request #1079
Opened 2021-05-13 06:57 UTC by mongomoe

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-14573

### Staged Changes (Requires MongoDB Corp SSO)

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-05-14 16:50 UTC, MongoCaleb requested changes
Overall comment: I have no idea WHY I would use a set over an array. Perhaps JS developers already know that? Also, there is no section on how to retrieve a value from a set, and I assume that's because you can't -- you have to iterate? Is it worth any additional info about that?

2021-05-14 16:50 UTC, MongoCaleb commented on source/sdk/node/data-types/sets.txt
> +A {+service-short+} set is a special object that allows you to store a
"special object" sounds weird and doesn't really tel us anything. Since everyone is familiar with Arrays, perhaps a start like this?

> A {+service-short+} set is an object that stores a collection of values. A Set is similar to an Array, except:
 - Each value in a Set must be unique,
 - Arrays are ordered by index, while sets are iterable and unordered (this isn't quite right...)

2021-05-14 16:50 UTC, MongoCaleb commented on source/sdk/node/data-types/sets.txt
> +collection of unique values. {+service-short+} sets work similarly to JavaScript
> sets work similarly to JavaScript
to 
> sets are based on JavaScript Sets, but are limited to a single value type and can only be modified...

2021-05-14 16:50 UTC, MongoCaleb commented on source/sdk/node/data-types/sets.txt
> +   through a loop, {+service-short+} sets may be in a different order than
> through a loop,
to 
> through a set,

2021-05-14 16:50 UTC, MongoCaleb commented on source/sdk/node/data-types/sets.txt
> +   the set's values in the insertion order.
The last sentence here is confusing. Are you saying the user should create an Array that gets updated every time the set is updated, and insert into the array in the order I want?

2021-05-14 16:50 UTC, MongoCaleb commented on source/sdk/node/data-types/sets.txt
> +To define a property's values as a {+service-short+} set, specify the data type
Can this be shortened to:

> To define a property type as a Set,  specify the data type you want in the set, followed by ``<>``

2021-05-14 16:50 UTC, MongoCaleb commented on source/sdk/node/data-types/sets.txt
> +To create an object with a property that value is of the set data type, create a
The wording here is confusing me. 
Does this work?
> To create an object that has one or more set properties, you must create the object within a write transaction. You then initialize the set-type properties as you would an array, by passing the initial values  in brackets (``[]``)

2021-05-14 16:50 UTC, MongoCaleb commented on source/sdk/node/data-types/sets.txt
> +To find out if a set has a particular value, pass the value to the ``set.has()`` method. The
consider changing "To find out" to "To determine"

2021-05-14 16:56 UTC, ccho-mongodb approved these changes
There are some changes I think you should make and some nitpicks, but I'll approve since Caleb is also reviewing this.

2021-05-14 16:56 UTC, ccho-mongodb commented on source/sdk/node/data-types/sets.txt
> +A {+service-short+} set is a special object that allows you to store a
I wonder if we should make it conspicuous that "Realm Set" is a term, either through capitalization similar to Javascript "Set" or using a bold format. 
After reading the first couple of paragraphs, I'm also curious as to whether you can use Javascript Sets instead, or if I can only use Realm Sets since the title of the page is Sets.

2021-05-14 16:56 UTC, ccho-mongodb commented on source/sdk/node/data-types/sets.txt
> +type and can only be modified within a write-transaction.
1) I think Sets contain types since Set is a type itself, so I would suggest "they must contain a single type".
2) I think it's "write transaction" rather than "write-transaction", unless the latter is terminology specific to Realm. You also use "write transaction" on line 49 of this PR.

2021-05-14 16:56 UTC, ccho-mongodb commented on source/sdk/node/data-types/sets.txt
> +   through a loop, {+service-short+} sets may be in a different order than
Nitpick:
You probably don't iterate through a loop, so maybe you meant to say something like "to access the contents of the set in a loop" or "to traverse the Set in a loop".
Also, I think it's the contents of the sets that are in a different order rather than "sets may be in a different order".

2021-05-14 16:56 UTC, ccho-mongodb commented on source/sdk/node/data-types/sets.txt
> +   must implement that order yourself. You can do this by creating an array of
Nitpick:
I don't think you can "implement that order", so maybe you meant "implement that ordering".

2021-05-14 16:56 UTC, ccho-mongodb commented on source/sdk/node/data-types/sets.txt
> +   the set's values in the insertion order.
I think it could be helpful to show a short example if this is something users need to do often enough.

2021-05-14 16:56 UTC, ccho-mongodb commented on source/sdk/node/data-types/sets.txt
> +followed by a less than and equal sign. For instance, for a set made of integer
"less than and equal sign" doesn't match your example. I expected to see "<=", but in the example, I see "<>"

2021-05-14 16:56 UTC, ccho-mongodb commented on source/sdk/node/data-types/sets.txt
> +To add items to a set, pass the new value to the ``set.add()`` method within a write transaction.
Nitpick:
The plural "items" doesn't match with singular "new value". Instead, consider "To add an item to a set, pass the new value..."

2021-05-14 16:56 UTC, ccho-mongodb commented on source/sdk/node/data-types/sets.txt
> +To find out if a set has a particular value, pass the value to the ``set.has()`` method. The
Nitpick: could be more specific "has" -> "contains"

2021-05-14 16:56 UTC, ccho-mongodb commented on source/sdk/node/data-types/sets.txt
> +    :language: javascript
Is the indentation correct? I think the colon should match with the "l" in "literalinclude" above. I know snooty won't error, but occasionally it's updated to be more strict so this could potentially  cause some issues in the future. Applies to all instances.

2021-05-14 16:56 UTC, ccho-mongodb commented on source/sdk/node/data-types/sets.txt
> +``set.has()`` method will return true if the set contains the value specified.
Nitpick: personal preference, but the notation "set.has()" is a little confusing as to whether "set" is the class or a variable. Maybe "has()" or "mySet.has()" would be more clear. Applies to all instances.

2021-05-14 16:56 UTC, ccho-mongodb commented on examples/node/Examples/data-types.js
> +    let link, hunter;
Nitpick: this variable name could potentially be difficult for some to follow, especially if they are not familiar with Zelda and/or English is not their first language, since it is similar to the technical term "link".

2021-05-17 09:58 UTC, kneth commented on source/sdk/node/data-types/sets.txt
> +A {+service-short+} set is a special object that allows you to store a
I agree: A Realm Set is not a 1:1 mapping of a JavaScript Set (but heavily inspired by it).

2021-05-17 20:14 UTC, mongomoe commented on examples/node/Examples/data-types.js
> +    let link, hunter;
Fair point, about link the name vs the technical term. I've altered to 'playerOne' and 'playerTwo' (for consistency)

2021-05-17 20:21 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +A {+service-short+} set is a special object that allows you to store a
Fair point, I've altered it to be "``Realm Set``" consistently throughout the doc to indicate it is a term. 

As for indicating that it is not a 1:1 mapping, I've included the line: "Realm sets work similarly to JavaScript Sets, except they must be a single type and can only be modified within a write-transaction"

2021-05-17 20:26 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +type and can only be modified within a write-transaction.
Thanks, fixed both 👍

2021-05-17 20:31 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +   must implement that order yourself. You can do this by creating an array of
Fixed 👍

2021-05-17 20:35 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +   the set's values in the insertion order.
That's a good idea, I've added it to a jira ticket that contains a list of proposed updates to this doc

2021-05-17 20:35 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +To add items to a set, pass the new value to the ``set.add()`` method within a write transaction.
Fixed 👍

2021-05-17 20:36 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +To find out if a set has a particular value, pass the value to the ``set.has()`` method. The
Fixed 👍

2021-05-17 20:37 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +``set.has()`` method will return true if the set contains the value specified.
Good point, I've altered it and similar methods to "<Set>.methodName()"

2021-05-17 20:40 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +    :language: javascript
Good point, fixed 👍

2021-05-17 20:41 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +followed by a less than and equal sign. For instance, for a set made of integer
Good catch, that's a typo that is supposed to be "less than and greater than sign". Fixed now 👍

2021-05-17 20:44 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +   through a loop, {+service-short+} sets may be in a different order than
Thanks 👍 , I've fixed it to 'to traverse the loop' and 'the contents of the Realm Set  may be in a different order'

2021-05-17 21:53 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +To find out if a set has a particular value, pass the value to the ``set.has()`` method. The
👍

2021-05-17 21:55 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +To define a property's values as a {+service-short+} set, specify the data type
That works, fixed now 👍

2021-05-18 15:23 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +   the set's values in the insertion order.
Essentially, that's it. I've altered it to be a bit clearer:

"You can do this by creating an array from the set, using Array.from(mySet), and updating that array when the set has been modified through a change listener."

2021-05-18 15:24 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +   through a loop, {+service-short+} sets may be in a different order than
Changed the sentence to: "When using a forEach() loop or other iteration method to traverse the set in a loop, the content of the Realm Set may be in a different order than originally written to."

2021-05-18 15:27 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +collection of unique values. {+service-short+} sets work similarly to JavaScript
took this suggestion almost verbatim

2021-05-18 16:19 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +A {+service-short+} set is a special object that allows you to store a
I'm down for being a bit clearer on the advantages of Set. I do want to keep it a bit more subtle and not necessarily bring up array for the following reasons:
- JavaScript developers should probably know the differences between set and array. Explaining the differences between the two would be explaining JS, not explaining how to use Realm with JS. For those that aren't familiar with the differences, I've linked out to the mdn docs on set.

As for showing when to use set, I've added some info in the intro, the new intro reads:
```
"A Realm Set is a special object that allows you to store a collection of unique values. Realm Sets are based on JavaScript Sets, but can only contain values of a single type and can only be modified within a write transaction. Sets allow you to perform math operations such as finding the union, intersection, or difference between two sets. To learn more about performing these operations, see the MDN docs for Implementing basic set operations."
```

2021-05-18 16:33 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +To create an object with a property that value is of the set data type, create a
How about a combo of the two phrasings:

"To create an object with a ``{+service-short+} Set`` property, you must create the object within a write transaction. When defining your Realm object, initialize the set by passing an empty array or an array with your initial values."

2021-05-18 17:40 UTC, mongomoe commented
@MongoCaleb per your top level comment: "Overall comment: I have no idea WHY I would use a set over an array. Perhaps JS developers already know that? Also, there is no section on how to retrieve a value from a set, and I assume that's because you can't -- you have to iterate? Is it worth any additional info about that?"

- Added some info about the benefits of using a Set, but I'm opposed to directly mentioning Arrays in this doc since I think it may confuse readers. Fundamentally they are two different data types with unique use cases, see more about my reasoning for not directly mentioning Arrays here: https://github.com/mongodb/docs-realm/pull/1079#discussion_r634546906
- About retrieving a value from a set, you would check if a set has a value (shown in [Node.js > Sets # Check if a Set has Specific Items](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14573-Set-Data-Type/sdk/node/data-types/sets/#check-if-a-set-has-specific-items) since sets are not retrievable via any index like arrays. Alternatively, you can iterate through the values in a set with a forEach loop, but I don't think we should show a snippet of that since iteration of a set using a forEach loop might confuse readers and imply that a set is similar to an array and since we don't guarantee traversal order.

2021-05-19 07:48 UTC, kneth approved these changes

2021-05-19 07:48 UTC, kneth commented on source/examples/generated/node/data-types.codeblock.remove-all-items-from-set.js
> +  // clear all data from the inventory slot of the characterTwo by calling `set.clear()` in a write transaction
```suggestion
  // clear all data from the inventory slot of the characterTwo by calling `Realm.Set.clear()` in a write transaction
```

2021-05-19 07:48 UTC, kneth commented on source/examples/generated/node/data-types.codeblock.remove-specific-item-from-set.js
> +  // remove the compass from characterOne's inventory by calling `set.delete()` within a write transaction
```suggestion
  // remove the compass from characterOne's inventory by calling `Realm.Set.delete()` within a write transaction
```

2021-05-19 07:48 UTC, kneth commented on source/sdk/node/data-types/sets.txt
> +   of your set, you must implement that ordering yourself.If you require an
```suggestion
   of your set, you must implement that ordering yourself. If you require an
```

2021-05-19 07:48 UTC, kneth commented on source/sdk/node/data-types/sets.txt
> +   do this by creating an array from the set, using :mdn:`Array.from(mySet)
The spread operator (`...`) will also work.

2021-05-19 13:01 UTC, mongomoe commented on source/sdk/node/data-types/sets.txt
> +   do this by creating an array from the set, using :mdn:`Array.from(mySet)
Fixed 👍

2021-05-19 13:13 UTC, merged

2021-06-04 07:50 UTC, fronck commented on source/sdk/node/data-types/sets.txt
> +A {+service-short+} set is a special object that allows you to store a
The JS Set does not currently support the math operations.  Its implementation has been kept as close as possible to JS's own set type.

2021-06-04 07:55 UTC, fronck commented on source/sdk/node/data-types/sets.txt
> +A {+service-short+} set is a special object that allows you to store a
Maybe it's worth specifying here that Realm Set, unlike JS's own set, does not guarantee iteration in insertion order.