(DOCSP-14877): Add more information about migration of embedded objects
mongodb/docs-realm pull request #1129
Opened 2021-06-09 18:07 UTC by cbush

## Pull Request Info

### Jira

https://jira.mongodb.org/browse/DOCSP-14877

### Staged Changes (Requires MongoDB Corp SSO)

- [EmbeddedObjects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/schema-migrations-embedded/sdk/ios/data-types/embedded-objects/)
- [Modify an Object Schema](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/schema-migrations-embedded/sdk/ios/examples/modify-an-object-schema/#convert-from-object-to-embeddedobject)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-06-09 18:25 UTC, mongomoe approved these changes
LGTM 👍

2021-06-10 09:45 UTC, DominicFrei commented on source/sdk/ios/data-types/embedded-objects.txt
> +primary key.
Another limitation: They cannot be queried. In case that's not mentioned anywhere else, this might be a good spot. The query limitation as thrown users off guard in the past.

2021-06-10 09:47 UTC, DominicFrei commented on source/sdk/ios/examples/modify-an-object-schema.txt
> +   At least one object does not have a backlink (data would get lost).
This is the exception for multiple backlinks (https://github.com/realm/realm-core/blob/master/src/realm/table.cpp#L1063).

The one for no backlinks is different:
https://github.com/realm/realm-core/blob/master/src/realm/table.cpp#L1060

2021-06-10 09:49 UTC, DominicFrei requested changes
I only had two minor comments. The one for exceptions should be added though since it's incorrect in it's current state.

Overall looks great to me though. 👍

2021-06-10 18:12 UTC, merged