WIP - (DOCSP-11954) modify schema properties of a synced realm
mongodb/docs-realm pull request #1132
Opened 2021-06-10 11:51 UTC by mongomoe

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-11954

### Staged Changes (Requires MongoDB Corp SSO)

- [Modify Schema Properties of a Synced Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-11954-Modify-Schema-Properties-Synced-Realm/sync/modify-schema-properties-synced-realm/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-06-10 20:37 UTC, nlarew requested changes
A few comments, several revolving around how to do transforms between the collections

2021-06-10 20:37 UTC, nlarew commented on source/includes/note-modify-schema-properties-of-synced-realms.rst
> +   </sync/modify-schema-properties-synced-realm>`.
Looks like a comma splice here, these should be two separate sentences.

Also, thoughts on phrasing the second sentence a little more like "If you want to modify the schema of a synced realm, see..."?

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> + Modify Schema Properties of a Synced Realm
```suggestion
Modify Schema Properties of a Synced Realm
```
Extra space at the front here - need to also update the `=`

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> + Modify Schema Properties of a Synced Realm
I think the title could be a little more specific - it's properties of a realm object, not the synced realm. Maybe: "Modify a Synced Object Schema"?

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> +your schema at some point. Realm Database offers an intuitive API for making
nit: is it really intuitive? 🙃

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> +   field's value set to null. Realm sets fields that are non-nullable to an
```suggestion
   field's value to ``null``. Realm sets fields that are non-nullable to an
```

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> +   appropriate empty value, such as a 0 for integer values and an empty string
```suggestion
   appropriate empty value, such as a 0 for integer values or an empty string
```

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> +like the following:
nit: "Attempting to..." => "If you attempt to perform..., you will encounter an error like the following:"

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> +that when one collection is written to, the other should be as well.
Seems like we're trying to use the term "Partner Collection" to describe this pattern. Can we explicitly define it as a term somewhere up front here?

e.g. A partner collection is a second collection that contains the same data as another collection but with a different schema. Partner collections use database triggers that you define to sync changes between each collection.

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> +with the :manual:`Mongo shell <mongo>`.
The copied data needs to conform to the modified schema, right? Let's be clear that you need to copy _and transform_ the data before you insert it into the second collection (i.e. why aggregate is the most useful).

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> +      collection.aggregate([{ $match: {} }, { $out: "TaskV2" }]);
I don't think this works in `mongo` or `mongosh` so it's not mongo shell code. Looks like node driver/sdk or Realm function JS.

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> +   The developer then navigates to his {+app+}'s :guilabel:`Schema` tab and views his new JSON schemas:
Let's remove the mention of the UI (i.e. schema tab) so that this is agnostic to what interface they use

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> +          "difficulty"
thoughts on adding an emphasize-line on the field that we're gonna remove?

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> +   modification.
My intuition is that folks miss small bits of text at the end of a section when they're after a sizable code block or note. Any way we could move this up before the schemas?

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> +      collection.aggregate([{ $match: {} }, { $out: "TaskV2" }]);
I don't think this works in `mongo` or `mongosh` so it's not mongo shell code. Looks like node driver/sdk or Realm function JS.

2021-06-10 20:37 UTC, nlarew commented on source/examples/Triggers/copy-data-from-initial-collection.js
> +    await taskV2Collection.insertOne(changedItem); // insert the changed or inserted document into its partnet collection
```suggestion
    await taskV2Collection.insertOne(changedItem); // insert the changed or inserted document into its partner collection
```

2021-06-10 20:37 UTC, nlarew commented on source/examples/Triggers/copy-data-from-initial-collection.js
> +    await taskV2Collection.insertOne(changedItem); // insert the changed or inserted document into its partnet collection
Don't I need to actually do something other than just directly copy from one collection to the other? I assume the Task -> TaskV2 trigger needs to do some kind of transformation, otherwise why have two collections?

2021-06-10 20:37 UTC, nlarew commented on source/examples/Triggers/copy-data-from-second-version-collection.js
> +    await taskCollection.insertOne(changedItem); // insert the changed or inserted document into its partnet collection
```suggestion
    await taskCollection.insertOne(changedItem); // insert the changed or inserted document into its partner collection
```

2021-06-10 20:37 UTC, nlarew commented on source/examples/Triggers/copy-data-from-second-version-collection.js
> +    await taskCollection.insertOne(changedItem); // insert the changed or inserted document into its partnet collection
Same comment as the other trigger - shouldn't this do some transformation to match the other collection's schema?

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> +   .. tabs-realm-sdks::
nit: thoughts on removing the tabs and making this a bulleted list w/ the SDK clearly identified for each link? The whole "tabs for a single link" pattern feels a bit silly IMO.

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> +collection.
This should reflect the same transform we do in the initial aggregation

2021-06-10 20:37 UTC, nlarew commented on source/sync/modify-schema-properties-synced-realm.txt
> +      collection.aggregate([{ $match: {} }, { $out: "TaskV2" }]);
The aggregation should also transform the Task documents somehow to conform to TaskV2. The example we chose doesn't actually need to change anything, so maybe we should revisit to have a slightly more complex change.

e.g. a V1 model has `userId` as a `number` but the V2 model changes it to `string`

2021-06-11 15:44 UTC, mongomoe commented on source/sync/modify-schema-properties-synced-realm.txt
> + Modify Schema Properties of a Synced Realm
Good catch, fixed locally rather than through the 'Commit suggestion' button. 👍

2021-06-11 15:46 UTC, mongomoe commented on source/includes/note-modify-schema-properties-of-synced-realms.rst
> +   </sync/modify-schema-properties-synced-realm>`.
Fixed the comma issue 👍  

I originally thought about phrasing it that way, but "If you want to modify the schema of a synced realm, see the documentation{link} for modifying schema properties of a synced realm" is so redundant. Alternatively, "If you want to modify the schema of a synced realm, see the documentation{link}" is vaguer and worse for SEO.

2021-06-11 15:56 UTC, mongomoe commented on source/sync/modify-schema-properties-synced-realm.txt
> +your schema at some point. Realm Database offers an intuitive API for making
Haha arguably it's intuitive in that we don't even technically let you do destructive changes. But fair enough, "Realm offers an API for making backward-compatible schema changes to synced realms, allowing old clients to sync with newer ones." it is 👍

2021-06-11 19:12 UTC, mongomoe commented on source/sync/modify-schema-properties-synced-realm.txt
> + Modify Schema Properties of a Synced Realm
Good idea, changed it to that now 👍

2021-06-11 19:13 UTC, mongomoe commented on source/sync/modify-schema-properties-synced-realm.txt
> +   appropriate empty value, such as a 0 for integer values and an empty string
Fixed locally 👍

2021-06-11 19:14 UTC, mongomoe commented on source/sync/modify-schema-properties-synced-realm.txt
> +like the following:
Going to keep the current wording since it conveys the same message

2021-06-11 19:45 UTC, mongomoe commented on source/sync/modify-schema-properties-synced-realm.txt
> +that when one collection is written to, the other should be as well.
That's a great idea, I've altered this part. Let me know what you think of the new phrasing. 

Also, would love to use the phrase " to sync changes between each collection." but Ian recommended not to as users might confuse the product sync (which implies sync between clients, or sync between clients and a server) with sync between collections. Instead I used "data flows in both direction"

2021-06-11 19:46 UTC, mongomoe commented on source/sync/modify-schema-properties-synced-realm.txt
> +      collection.aggregate([{ $match: {} }, { $out: "TaskV2" }]);
Whoops sorry about that, I originally used the atlas UI to perform the aggregation. I've altered it to use mongo shell commands (and I've tested the commands to ensure that they work)

2021-06-11 19:49 UTC, mongomoe commented on source/sync/modify-schema-properties-synced-realm.txt
> +with the :manual:`Mongo shell <mongo>`.
Nope, the copied data does not need to conform to the modified schema. The new collection needs to contain the existing data, so that newer clients still have access to the old data. 

So to be clear, data does not need to be "transformed" before inserting into the second collection, it should be copied as is. You could also do a mongodump/mongorestore (or various other methods of copying a collection).

2021-06-11 19:50 UTC, mongomoe commented on source/sync/modify-schema-properties-synced-realm.txt
> +   The developer then navigates to his {+app+}'s :guilabel:`Schema` tab and views his new JSON schemas:
Do you have any suggestions for alternative phrasing?

2021-06-11 19:51 UTC, mongomoe commented on source/sync/modify-schema-properties-synced-realm.txt
> +          "difficulty"
Sounds like a good idea, added line emphasize on the "difficulty" field now

2021-06-11 19:54 UTC, mongomoe commented on source/sync/modify-schema-properties-synced-realm.txt
> +   modification.
Sure, moved it above the json schema now 👍

2021-06-11 19:56 UTC, mongomoe commented on source/sync/modify-schema-properties-synced-realm.txt
> +   .. tabs-realm-sdks::
Going to keep it as is, personally I think the tabs look cleaner than a list (especially since its a long-ish page anyway)

2021-06-17 19:04 UTC, nlarew commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  trigger fires, alter your trigger function's code. This time, transforming the
nit: not really "alter" since it's a separate function entirely and the backward transform may not be identical to the forward transform.

i.e. instead of "alter your trigger function's code..." maybe try "write a function similar to the first trigger...."

2021-06-17 19:04 UTC, nlarew commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  trigger fires, alter your trigger function's code. This time, transforming the
nit: here we lose the separation between generic advice and example. Can we rework the "This time..." sentence to make it clear that it's in our example?

2021-06-17 19:04 UTC, nlarew commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  the :guilabel:`Operation Type` column.
Can we make this less UI-centric? i.e. remove "checkmarked", guilabels, etc

"The trigger should fire for all operation types."

2021-06-21 13:24 UTC, mongomoe commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  To do this, set up a :ref:`database trigger <create-a-database-trigger>` for
Fixed verbatim 👍

2021-06-21 13:27 UTC, mongomoe commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +title: Set Up a Partner Collection
Changed instead to "Initialize Your Partner Collection", let me know what your think.

2021-06-21 13:37 UTC, mongomoe commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  collection named ``TaskV2``.
Right now there's no official documentation on copying data from one collection to another collection, outside of this staging link and the deprecated 'copyTo' method (there are other ways such as Mongodump+Mongorestore, looping through data + manually insertOne, Mongoexport + Mongoimport, etc). So since we don't have anywhere to point users to directly, I think vaguely telling them you can use these other ways might lead to more confusion than not. 

For the $addFields, I'll add a line that says you might need to use an alternate operator for your usecase.

2021-06-21 13:46 UTC, mongomoe commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  integer.
This step is dense because it outlines chronologically the steps to create the trigger function. Moving `parseInt` down a bit, would ruin the order of the steps and might be more confusing. There's also other methods that suffer from this same problem (such as deleteOne).

2021-06-21 13:48 UTC, mongomoe commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  collection named ``TaskV2``.
changed the $addFields paragraph to:

"Modify the desired fields of the initial collection by using an aggregation pipeline operator. In the following example, the data is transformed using the $addFields operator. The``_id`` field is transformed to a string type with the $toString operator."

2021-06-21 13:49 UTC, mongomoe commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  collection named ``TaskV2``.
Let me know what you think ^

2021-06-21 14:03 UTC, mongomoe commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  ``TaskV2`` collection.
Any specific wording that you would suggest? 

Also, personally I'm not against prescribing a specific way of doing something even if there are alternatives. For this example, using aggregations seems simpler (esp since we just did aggregations earlier and aggregations allow you to not have to do conditional checking on operation type, except delete, to determine what write method to perform)

2021-06-21 14:08 UTC, mongomoe commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  the :guilabel:`Operation Type` column.
Fixed 👍

2021-06-21 14:11 UTC, mongomoe commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  trigger fires, alter your trigger function's code. This time, transforming the
Good ideas, fixed now 👍 

"To copy data from TaskV2 collection to the Task collection when the trigger fires, write a function similar to the first trigger's function. In this example, we transform the data of TaskV2 before inserting it into the Task collection by changing the _id from a string to an integer value."

2021-06-22 14:52 UTC, nlarew commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  collection named ``TaskV2``.
Sounds good, already a lot of info so probably okay for now if we don't add more

2021-06-22 14:54 UTC, nlarew commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  ``TaskV2`` collection.
Per my other comment probably okay to leave it out

2021-06-22 15:08 UTC, nlarew commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  integer.
It goes a bit beyond density IMO. We specifically say "In the following example, we call `parseInt()` on the `_id` field since the `TaskV2` collection stores the `_id` field as an integer."

(Side note - this is incorrect because TaskV2 stores `_id` as a string not an integer)

This doesn't feel right because:
- We don't use `parseInt()` in the following code block (it's in the code block _after_ the following)
- We have another sentence after this one that _does_ describe the following code block, i.e. "In the following example, the initial data's `_id` field is transformed to a string type using the `$toString` operator."

I think the issue arising with `deleteOne()` gives us even more reason to evaluate this step critically - there's probably some (relatively small) underlying organizational change we can make to avoid or diminish the problem.

A couple of ideas:
- Be a bit more explicit up front that we're describing the three phases of ETL and then discuss how the trigger will **Extract** from one collection, **Transform** to match the other collection's schema, and then **Load** into the other collection.
- Remove the mention of `parseInt()` from the paragraph and add a code comment about it instead
- Or, move the mention of `parseInt()` to the paragraph after the first trigger code block. If we go this route, we probably also want to mention in a similar way that the first trigger uses `toString()`
- Maybe split the two triggers into separate steps? e.g. **Write a Forward Migration Trigger** followed by **Write a Reverse Migration Trigger**

2021-06-23 14:06 UTC, mongomoe commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  integer.
This was a really in-depth and helpful comment! I restructured this bit on trigger functions into two steps and followed a lot of your advice, let me know what you think.

2021-06-23 21:49 UTC, nlarew approved these changes
A few small wording comments but otherwise looking really good!

2021-06-23 21:49 UTC, nlarew commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  ``TaskV2`` collection to the ``Task`` collection.
nit: probably not a blocker but the timeline of the steps is a little off here if you're using the UI since you define the trigger function when you create it. Thoughts?

2021-06-23 21:49 UTC, nlarew commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  To copy any new changes to the initial collection to the partner collection,
nit: At first I read this as "copy changes [that were made somewhere] to the initial collection".

Also not sure if "initial collection" is super clear, especially in contrast to "partner collection". My read was that both V1 and V2 are "partners" with eachother and initial could mean "V1 since it is the earlier version" or (in the second trigger) "V2 since it is the collection I'm exporting from'

Maybe we can clear up the wording? (I use "old" and "new" here but there's probably a better choice) e.g.

"A forward migration trigger listens for inserts, updates, and deletes in the old collection, modifies them to reflect the newer collection's schema, and then applies them to the new collection"

2021-06-23 21:49 UTC, nlarew commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  To copy any new changes to the second collection to the initial collection,
Same thoughts here as in my previous comment re "copy...to" and "initial collection"

2021-06-24 15:10 UTC, mongomoe commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  ``TaskV2`` collection to the ``Task`` collection.
You actually don't need to define the content of the trigger function immediately, you can just create & name the function and leave it blank - which is what the step is saying.

2021-06-24 15:16 UTC, mongomoe commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  To copy any new changes to the initial collection to the partner collection,
Personally I don't like 'old' because it makes me think the Task collection is deprecated or unusable compared to the TaskV2 collection. But actually both collections are used simultaneously, Task is used by clients before the schema change, and TaskV2 after the schema change.

I did take your advice on the 'copy changes' and almost verbatimly applied your updated wording:
"A forward migration trigger listens for inserts, updates, and deletes in the initial collection, modifies them to reflect the partner collection's schema, and then applies them to the partner collection."

2021-06-24 15:16 UTC, mongomoe commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  To copy any new changes to the initial collection to the partner collection,
Personally I don't like 'old' because it makes me think the Task collection is deprecated or unusable compared to the TaskV2 collection. But actually both collections are used simultaneously, Task is used by clients before the schema change, and TaskV2 after the schema change.

I did take your advice on the 'copy changes' and almost verbatim applied your updated wording:
"A forward migration trigger listens for inserts, updates, and deletes in the initial collection, modifies them to reflect the partner collection's schema, and then applies them to the partner collection."

2021-06-24 15:18 UTC, mongomoe commented on source/includes/steps-perform-destructive-changes-synced-schema.yaml
> +  To copy any new changes to the second collection to the initial collection,
Altered to: "To listen for changes to the second collection and apply them to the initial collection, write a reverse migration function"

2021-06-24 15:35 UTC, merged