Fix for deprecated ListItem title
mongodb/docs-realm pull request #1159
Opened 2021-06-19 00:49 UTC by marklchaves

Fix for deprecated ListItem title in the RN tutorial.

Reference: https://reactnativeelements.com/blog/2020/08/10/2.3-upgrade-guide/#listitem

## Pull Request Info

Running the RN tutorial throws the following warning.

`[Sat Jun 19 2021 05:03:22.951]  WARN     'ListItem.title' prop has been deprecated and will be removed in the next version. `

This PR updates the `ListItem` code according to the following React Native Elements upgrade guide.

https://reactnativeelements.com/blog/2020/08/10/2.3-upgrade-guide/#listitem

### Jira

N/A

### Staged Changes (Requires MongoDB Corp SSO)

N/A

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-07-01 22:40 UTC, nathan-contino-mongo commented
@mongomoe @nlarew can one of you take a look at this? Unfortunately my RN skills aren't quite up to snuff for a change of this size.

2021-07-01 22:44 UTC, nathan-contino-mongo commented
@marklchaves can you agree to our CLA? https://docs.google.com/forms/d/e/1FAIpQLSeQ9ROFaTu9pyrmPhXc-dEnLD84DbLuT_-tPNZDOL9J10tOKQ/viewform

2021-07-01 23:27 UTC, marklchaves commented
Hello @nathan-contino-mongo,

I've signed the CLA.

Thanks so much :-)

2021-07-02 19:30 UTC, mongomoe commented
@marklchaves Thanks for contributing with this pull request. This PR uses an updated version of 'react-native-elements' but you didn't push any changes to the package.json. Can you add those changes?

Also, it looks like some of the styling on the list items is not matching the original styling. For instance, when you click a task in your branch the actions spacing and font do not match the original.

Original:
<img width="430" alt="Screen Shot 2021-07-02 at 3 24 46 PM" src="https://user-images.githubusercontent.com/52428905/124320518-0bfb1800-db4a-11eb-9b0f-f5c80c31ed43.png">

marklchaves:listitem-ttile-attribute-fix:
<img width="428" alt="Screen Shot 2021-07-02 at 3 19 03 PM" src="https://user-images.githubusercontent.com/52428905/124320557-19b09d80-db4a-11eb-97e8-f38e10efcd69.png">


In addition, it appears as if the ListItem is not showing when items are marked "In Progress" or "Complete" in your version.

So required fixes before giving this an approval is:
- UI fixes
- package.json change to upgrade 'react-native-elements'

2021-07-02 19:36 UTC, mongomoe commented on tutorial/rn/components/TaskItem.js
> +            checkmark={
Looks like ListItem.Title does not have a checkmark prop in later versions of react-native-elements. See: https://reactnativeelements.com/docs/listitem/

2021-07-02 19:37 UTC, mongomoe commented on tutorial/rn/components/TaskItem.js
> +            checkmark={
I believe you have to move this logic to a ListItem.Checkbox. See: https://reactnativeelements.com/docs/listitem/#listitemcheckbox

2021-07-02 19:38 UTC, mongomoe requested changes
Thanks again for submitting a PR and contributing. Some UI bugs in this (left comments explaining) + needs an updated package.json file

2021-07-14 13:17 UTC, marklchaves commented
Hello @mongomoe,

Thanks so much for the code review. I'll try to work on your suggestions over the next few days or so.

Cheers! :-)

2021-07-29 20:44 UTC, nathan-contino-mongo commented
> Hello @mongomoe,
> 
> Thanks so much for the code review. I'll try to work on your suggestions over the next few days or so.
> 
> Cheers! :-)

Hi Mark,

Any progress on this? We'd like to update the docs to follow this convention, but I also want to make sure you get credit. If you can finish this up in the next couple of days we can avoid having to reimplement it ourselves 😄

2021-07-30 14:17 UTC, marklchaves commented
Hey @nathan-contino-mongo,

Thanks for checking in. I'll try to make time to work on this over the weekend! Sorry, I couldn't get to it earlier like I said I would.

Have a great weekend :smile:

2021-07-31 07:08 UTC, marklchaves commented on tutorial/rn/components/TaskItem.js
> +            checkmark={
Hi @mongomoe,

I pushed my fixes:

1. Fixed the line spacing in the task action sheet.
2. Fixed the missing task item status in the task list.
3. Updated `react-native-elements` version in package.json.

I didn't use `ListItem.Checkbox`. I kept the [original logic](https://github.com/marklchaves/docs-realm/blob/651c40d0f9d5ded42f66713e1733d37a5c5261f5/tutorial/rn/components/TaskItem.js#L75) that displays the check _icon_ or **In Progress** depending on the status of the task.

Give me a yell if I missed anything 😄

2021-08-10 20:55 UTC, mongomoe commented on tutorial/rn/components/ManageTeam.js
> -  // :code-block-start: get-team
The "// :code-block-start", "// :state-start:", ":state-uncomment-end:", "// :state-end:", etc are statements used by our bluehawk markup parser and required for this tutorial. Can you add them back to this PR?

See: https://www.npmjs.com/package/bluehawk

2021-08-10 20:58 UTC, mongomoe commented on tutorial/rn/components/TaskItem.js
> +            checkmark={
@marklchaves thanks for upgrading the version + fixing the UI issue

2021-08-10 20:59 UTC, mongomoe requested changes
Close to LGTM, the UI looks good. But you just need to bring back the bluehawk comments (see: https://github.com/mongodb/docs-realm/pull/1159/files#r686315829). 

Thanks again for your work on this.

2021-08-25 13:43 UTC, mongomoe approved these changes
LGTM, thanks for all your work on this! Merging this now ✅

2021-08-25 13:44 UTC, merged