(DOCSP-16511): Update Sync -> Development Mode documentation
mongodb/docs-realm pull request #1175
Opened 2021-06-25 21:50 UTC by dacharyc

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-16511

### Staged Changes (Requires MongoDB Corp SSO)

- [Concepts: Development Mode](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16511/sync/concepts/development-mode/): Largely novel content
- [Guides: Enable/Disable Development Mode](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16511/sync/guides/enable-development-mode/#std-label-enable-disable-development-mode): New procedures to disable development mode

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-07-06 21:09 UTC, nlarew requested changes
Really good stuff, a few comments across the pages and some ideas on how to streamline the concept page. Lemme know your thoughts!

2021-07-06 21:09 UTC, nlarew commented on source/sync/concepts/development-mode.txt
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The idea of separate apps for each env seems like a production workflow best practice more than it is specific to dev mode. Especially given that app environments are also a feature that you can use independent of dev mode - a "development" app won't necessarily always have "development mode" turned on.

Barring that, it seems like the major point here is similar to the following section, i.e. don't enable dev mode for a production app

2021-07-06 21:09 UTC, nlarew commented on source/sync/concepts/development-mode.txt
> +mode would leave that data vulnerable to inadvertent or malicious access.
Also, dev mode in production would let anybody with your app id modify your schemas and break stuff, which is obviously no bueno

2021-07-06 21:09 UTC, nlarew commented on source/sync/concepts/development-mode.txt
> +<appconfig-sync>` by setting ``development_mode_enabled`` to ``false``.
I think this would be more relevant in the upcoming CI/CD workflow guide since it's advice specific to the CI/CD use case instead of a more general explanation.

2021-07-06 21:09 UTC, nlarew commented on source/sync/concepts/development-mode.txt
> +-----------------------------
This section has really good info - I'm wondering if it makes sense on this high level concept page in its current form though. We may be able to eliminate this section and shorten the page if we move some of it around. Check out my other comments on the subsections for more info.

2021-07-06 21:09 UTC, nlarew commented on source/sync/concepts/development-mode.txt
> +For example, you specify a Development Mode database of ``myapp``. Your
Can we put this in a `.. example::` and move it to the bottom of the subsection?

Right now it splits up the general definition into two halves and it isn't totally clear where the example ends and the general definition comes back in.

2021-07-06 21:09 UTC, nlarew commented on source/sync/concepts/development-mode.txt
> +or user data.
Maybe we could cover the "don't enable dev mode for a production app" point here since we mention it again anyway? Could be inline text or a note.

2021-07-08 13:56 UTC, dacharyc commented on source/sync/guides/enable-development-mode.txt
> +This page contains the procedures to enable or disable development mode.
I put that there after discovering that directives, if they're the first thing on the page, are the content that shows up in the search results under the page title. I'd rather see a line describing the page contents than a seealso or a warning when I discover the page in the search results. I agree that it's a bit redundant, though - if we could specify this in metadata, that would be ideal. Meanwhile, if you have a suggestion for something else to put here, or if you think we should scrap it anyway and not worry about how the page displays in search results, I'll remove it. Thoughts @nlarew ?

2021-07-08 14:03 UTC, dacharyc commented on source/sync/concepts/development-mode.txt
> +tools to define and work with these objects.
I like it. Added!

2021-07-08 15:21 UTC, dacharyc commented on source/sync/concepts/development-mode.txt
> +-> :guilabel:`Schema`.
That's fair. Linking to a guide makes sense, I think. I wanted to close the loop - i.e. it's good to know from a concept standpoint that once you've created a schema, you can view it and know that it was created correctly, etc. 

We should probably also create a guide for, er, what do we call it - translate your data model to SDKs? I've seen people get excited about the fact that they can generate data models for other languages once they have a schema defined in Sync - i.e. I write a client for my app in Swift, sync it to my Realm app, and then go to Build -> SDKs and copy the data models for JS/TS/Java/Kotlin without having to manually recreate them for cross-platform development. I don't know off the top of my head what the best name for that guide would be.

Should there be new tickets for these guides in the Sync Update epic, or should I put them together for this since it's all sort of related?

2021-07-08 15:33 UTC, dacharyc commented on source/sync/concepts/development-mode.txt
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Yes, that's fair. This section of recommendations was really to set the stage for the following sections, and I was specifically thinking about the case for CI/CD where you're using different apps for different stages in the SDLC, and you use automation to turn off development mode (i.e. have a step to set `development_mode_enabled` to `false` every time someone pushes to a non-development app). So it wasn't necessarily that a development app would always have "development mode" turned on, but more that a non-development app would always have "development mode" turned _off_.

If you think it's too much set up for not enough payout in the context of this page, I'm happy to remove the content.

2021-07-08 15:35 UTC, dacharyc commented on source/sync/concepts/development-mode.txt
> +mode would leave that data vulnerable to inadvertent or malicious access.
Fair, but this was more about development mode in the context of potentially exposing data that you're using in a development environment, not dev mode in production. I've worked for companies that have used production data in development, so they have "real" representation of what the data looks like... and that seems like a security vulnerability in this context.

2021-07-08 15:37 UTC, dacharyc commented on source/sync/concepts/development-mode.txt
> +<appconfig-sync>` by setting ``development_mode_enabled`` to ``false``.
That's fair, and if the CI/CD workflow guide had been available, I'd have been happy to link to that with a recommendation to use CI/CD to automate turning off dev mode. Because that content doesn't yet exist, I wanted to provide some more recommendations here relevant to this context. I do think it's worth including _some_ recommendations about this on this page, even if it's not in this level of detail, because users should be thinking about this in this context. It also speaks a bit to the "best practices" conversation we keep having with Ian.

2021-07-08 15:39 UTC, dacharyc commented on source/sync/concepts/development-mode.txt
> +-----------------------------
I do think it's relevant to include some guidance around this in this "development mode" context. I'm happy to shorten the section and link out to other content when it exists, or make a separate ticket to add something like this to this section once that other content does exist, but I do think it should be here in some form.

2021-07-08 15:42 UTC, dacharyc commented on source/sync/concepts/development-mode.txt
> +or user data.
Does that really belong in this section? Since this is specifically about the development database, I wonder if that warning really belongs here again. I'm mostly trying to address the case like I've seen in some of my former companies where the org uses production data in development databases.

2021-07-09 01:57 UTC, nlarew commented on source/sync/guides/enable-development-mode.txt
> +This page contains the procedures to enable or disable development mode.
SGTM would definitely be nice to configure this in metadata down the road

2021-07-09 01:58 UTC, nlarew commented on source/sync/concepts/development-mode.txt
> +-> :guilabel:`Schema`.
Already have one! https://jira.mongodb.org/browse/DOCSP-16519

2021-07-09 02:00 UTC, nlarew commented on source/sync/concepts/development-mode.txt
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Definitely good advice - I think it'd make sense here but even more sense in a specific CI/CD guide section. I maybe can integrate it into the upcoming CI/CD page but not sure.

2021-07-29 16:20 UTC, nlarew approved these changes
LGTM! We can revisit the concept/guides hierarchy once everything fits neatly into it.

2021-07-29 16:21 UTC, merged