(DOCSP-13905): Pass configurations in iOS Tutorial for offline usage
mongodb/docs-realm pull request #1208
Opened 2021-07-06 21:01 UTC by cbush

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-13905

### Staged Changes (Requires MongoDB Corp SSO)

- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ios-tut/tutorial/ios-swift/

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-07-06 21:50 UTC, cbush commented
Reminder to check that arty-fact works correctly after merge as https://github.com/mongodb/docs-realm/pull/1205 was recently merged and this will test it.

2021-07-07 17:16 UTC, dacharyc requested changes
LGTM overall. I did find one typo where there were some missing words, and a couple of places where things are worded awkwardly or seemed unclear to me.

I only read the text and code snippets - I didn't actually try cloning and running the tutorial. Would you like me to go through and run the tutorial, too, or is this level of review sufficient?

2021-07-07 17:16 UTC, dacharyc commented on source/includes/steps-tutorial-ios-swift-sync.yaml
> +  ``User`` object in the user {+realm+}. Because your backend app creates
Do we say anywhere what a `user {+realm+}` is in this context? We're saying "User" a lot in this section and I'm having trouble keeping the state of all of the "user" references consistent in my head. Is it the realm file that this specific user should have access to - i.e. the user's realm? I see that we also say "user Realm" in [the `signIn()` section above](https://github.com/mongodb/docs-realm/pull/1208/files#diff-c1c95ac8e5cb095f67019814e4f391c73274ea6f2ebaebc9ee7790590d402efbR92) - I wonder if we can clarify our meaning in both places.

2021-07-07 17:16 UTC, dacharyc commented on source/includes/steps-tutorial-ios-swift-sync.yaml
> +  Next, we'll to add menu to manage members of a project that you can open with
```suggestion
  Next, we'll need to add a menu to manage members of a project that you can open with
```
Seems like we're missing some words. But this is also awkwardly worded - perhaps we could say instead something like "Add a button that enables the user to open a menu to manage project members"?

2021-07-07 17:16 UTC, dacharyc commented on source/includes/steps-tutorial-ios-swift-sync.yaml
> +  that checks if a project is owned by the current user, which controls whether
Nit: we could simplify this by making a full stop and new sentence here. i.e. "checks if a project is owned by the current user. This controls whether or not..."

2021-07-07 17:16 UTC, dacharyc commented on source/includes/steps-tutorial-ios-swift-sync.yaml
> +  .. note::
Should this be a warning, instead?

2021-07-08 00:04 UTC, cbush commented on source/includes/steps-tutorial-ios-swift-sync.yaml
> +  ``User`` object in the user {+realm+}. Because your backend app creates
Added a note and also pasted it around to the other tutorials.

2021-07-08 00:09 UTC, cbush commented on source/includes/steps-tutorial-ios-swift-local.yaml
> +  Finally, implement the ``signIn()`` method. Create a {+realm+} configuration
Happy to change, but having trouble here - it feels self-explanatory, so I'm not sure what to say.

2021-07-08 00:09 UTC, cbush commented
@dacharyc Thanks for the review! Comments addressed, let me know if you have more thoughts.

2021-07-08 13:36 UTC, dacharyc commented on source/includes/steps-tutorial-ios-swift-local.yaml
> +  Finally, implement the ``signIn()`` method. Create a {+realm+} configuration
Fair. I'm thinking bigger picture about how we talk about configuration relative to opening realms, so I'll make a mental note for myself to put in a link here if we do a "configuration" concept at some point.

2021-07-08 13:49 UTC, dacharyc approved these changes
Nice, looks great! I found one little thing in the new note, which I've made a suggestion about, but otherwise LGTM.

2021-07-08 13:49 UTC, dacharyc commented on source/includes/note-tutorial-custom-user-data-permissions.txt
> +   access to project, which we will use later when we add the Manage Team
```suggestion
   access to projects, which we will use later when we add the Manage Team
```

2021-07-08 13:49 UTC, dacharyc commented on source/includes/note-tutorial-custom-user-data-permissions.txt
> +.. note:: How Do We Know Which Projects a User Can Access?
Awesome, this is a really helpful piece of context. Thank you for adding this!

2021-07-08 13:49 UTC, dacharyc commented on source/includes/steps-tutorial-ios-swift-sync.yaml
> +  ``User`` object in the user {+realm+}. Because your backend app creates
That note is excellent - provides such good context. Thank you for adding it!

2021-07-08 16:55 UTC, merged