Docsp 16518
mongodb/docs-realm pull request #1238
Opened 2021-07-19 23:37 UTC by MongoCaleb

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-16518

### Staged Changes (Requires MongoDB Corp SSO)

- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16518/sync/local-to-sync/

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-07-20 19:18 UTC, dacharyc approved these changes
Overall, this is excellent. I spotted a couple of nits, but feel free to take or leave any of the suggestions. (Although I think one of those things was actually a typo in line 170.)

Big-picture, I think this page does a good job of hitting the notes described in the Jira ticket. I do think the title isn't quite right. When I think of "convert a local Realm to a synced Realm" I think of the process our users have to go through to copy data from a local Realm file on disk to a new Realm that is a synced Realm. (Which is another thing I want to provide guidance around.)

I know this wasn't in the Jira ticket, but we should probably cover what to do if the app has end users who already have local Realms that contain data - i.e. how they then get that data to sync. I know we don't have code examples for that at the SDK level, but maybe it's worth adding a step at the end of each SDK's writeup mentioning that's an additional piece of logic they'll have to implement for that case.

2021-07-20 19:18 UTC, dacharyc commented on source/sync/local-to-sync.txt
> +      5. Once you have :ref:`enabled {+sync+} <enable-sync>` and authenticated a
I liked how you called out specifically what was different about the opening a synced Realm code examples in the other SDKs (i.e. passing in a config/partition/user object). I was bummed not to see it in the RN or Node.js examples. Perhaps we could add that? I think it helps the reader focus on what's different here vs. in the standard "open a Realm" example.

2021-07-20 19:21 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +- Configure a User Authentication provider, and
```suggestion
- Configure at least one User Authentication provider, and
```

2021-07-20 19:23 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +Convert a Local Realm to a Synced Realm
I wonder if we should instead name this "Add Sync to an Application that Already Uses Realm Database"... or something like that

2021-07-20 19:24 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +         selected when creating the backend, you'll need to add that property.
The partition key isn't actually necessary in the Android SDK, so we can remove this step entirely.

2021-07-20 19:25 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +         object to specify of how your application synchronizes data with
```suggestion
         object to control how your application synchronizes data with 
```

2021-07-20 19:25 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +your client app. Since each SDk is different, choose the tab below for your
```suggestion
your client app. Since each SDK is different, choose the tab below for your 
```

2021-07-20 19:27 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +      1. To use {+backend+} features such as authentication and sync, you must
With the Android SDK, before a user can use any sync functionality (such as the `App` class), they have to [enable sync](https://docs.mongodb.com/realm/sdk/android/install/#add-realm-to-the-application-level-build-gradle-file) in their gradle config. (described in the linked step, but i'm breaking that out into a linkable example in a PR soon)

2021-07-20 19:28 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +         {+backend+}. The following example includes a partition name and the user
```suggestion
         {+backend+}. The following example includes a partition and the user 
```
It might be better to use either "partition value" or just "partition" here so we don't introduce a new term in a step guide.

2021-07-20 19:29 UTC, nathan-contino-mongo requested changes
I think we should reconsider the page name and trim the "partition keys in models" bits from the android sdk -- see my comments for more info!

2021-07-25 22:51 UTC, MongoCaleb commented on source/sync/local-to-sync.txt
> +Once you determine your
Much better.

2021-07-26 18:05 UTC, nathan-contino-mongo commented on source/examples/generated/android/local/OpenARealmTest.codeblock.configure-a-realm-local.kt
> -    .inMemory()
Can you rebase or merge in the latest from master so we can avoid seeing all of these unrelated changes?

2021-07-26 18:06 UTC, nathan-contino-mongo requested changes
Holding off on reviewing for now because there are too many unrelated changes in this diff and it's very hard to see what's changed in the PR.

2021-07-26 18:48 UTC, nathan-contino-mongo approved these changes
Noticed a few places where source constants weren't being used for source constant-ified concepts, but otherwise LGTM

2021-07-26 18:48 UTC, nathan-contino-mongo commented on source/sdk/android/quick-start-sync.txt
> -         :language: java
This codeblock should not be removed, I think? Both models are required for the quick start.

2021-07-26 18:48 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +None of the data in your local realm will be automatically transferred to your
```suggestion
None of the data in your local {+realm+} will be automatically transferred to your 
```

2021-07-26 18:48 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +copied to the new realm. How you go about doing this depends, in part, on your
```suggestion
copied to the new {+realm+}. How you go about doing this depends, in part, on your 
```

2021-07-26 18:48 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +new synced realm; it is up to you to ensure the data you want to preserve is
```suggestion
new synced {+realm+}; it is up to you to ensure the data you want to preserve is 
```

2021-07-26 18:48 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +copying all of the data from the local realm to the synced realm. If done
```suggestion
copying all of the data from the local {+realm+} to the synced {+realm+}. If done 
```

2021-07-26 18:48 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +1. Check if a synced realm already exists.
```suggestion
1. Check if a synced {+realm+} already exists.
```

2021-07-26 18:48 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +2. If not, create one. Open a connection to it and to the local realm.
```suggestion
2. If not, create one. Open a connection to it and to the local {+realm+}.
```

2021-07-26 18:48 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +3. Read each record from the local realm and modify it to meet the needs of the
```suggestion
3. Read each record from the local {+realm+} and modify it to meet the needs of the 
```

2021-07-26 18:48 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +4. Copy the modified record to the new synced realm. Sync will automatically
```suggestion
4. Copy the modified record to the new synced {+realm+}. Sync will automatically 
```

2021-07-26 18:48 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +5. Confirm that all records you want to preserve are in the new realm.
```suggestion
5. Confirm that all records you want to preserve are in the new {+realm+}.
```

2021-07-26 18:48 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +7. On each subsequent app load, simply check if the local realm has been deleted.
```suggestion
7. On each subsequent app load, simply check if the local {+realm+} has been deleted.
```

2021-07-26 18:48 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +6. Delete the local realm file.
```suggestion
6. Delete the local {+realm+} file.
```

2021-07-26 18:48 UTC, nathan-contino-mongo commented on source/sync/local-to-sync.txt
> +:ref:`Create a Realm App (Realm UI) <create-a-realm-app>`.
```suggestion
:ref:`Create a {+app+} (Realm UI) <create-a-realm-app>`.
```

2021-07-26 21:08 UTC, MongoCaleb commented on source/sdk/android/quick-start-sync.txt
> -         :language: java
Not sure what happened here!

2021-07-26 21:16 UTC, merged