Expand Open a Realm page
mongodb/docs-realm pull request #1272
Opened 2021-08-04 19:28 UTC by MongoCaleb

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-17708

### Staged Changes (Requires MongoDB Corp SSO)

- main work: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-17708/sdk/dotnet/examples/open-a-realm/
- small change: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-17708/sdk/dotnet/examples/sync-changes-between-devices/

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-08-06 17:07 UTC, nathan-contino-mongo requested changes
A few nitpicks and questions!

2021-08-06 17:07 UTC, nathan-contino-mongo commented on source/sdk/dotnet/examples/open-a-realm.txt
> +method:
I know that iOS never returns a realm for an async open when offline. Android, on the other hand, is happy to return an empty realm, even if you've never opened it before (unless you specify a waitForInitialData option in the sync configuration, and even that has a timeout). Does .NET have any limitations like this? Could be worth mentioning here or in the next section.

2021-08-06 17:07 UTC, nathan-contino-mongo commented on source/sdk/dotnet/examples/open-a-realm.txt
> +Once a user authenticates on a device, the User object is persisted until the
I wonder if we should put User in monospace here since we're talking about the programmatic object. Also, passive voice/moving "on that device" to demonstrate the persistence occurring on the device as opposed to in da cloud:
```suggestion
Once a user authenticates, the ``User`` object persists on that device until the 
```

2021-08-06 17:07 UTC, nathan-contino-mongo commented on source/sdk/dotnet/examples/open-a-realm.txt
> +User logs off. This allows your app to
```suggestion
user logs off. This allows your app to 
```
And here I'd say we're referring to the physical (probably human) user of the app, who we can just use the pronoun for. I think.

2021-08-06 17:07 UTC, nathan-contino-mongo commented on source/sdk/dotnet/examples/open-a-realm.txt
> +synced realm in an offline state. Changes that occur while offline will be
I'll never stop nitpicking the source constant omissions :) 

```suggestion
synced {+realm+} in an offline state. Changes that occur while offline will be 
```

2021-08-06 17:07 UTC, nathan-contino-mongo commented on source/sdk/dotnet/examples/open-a-realm.txt
> +   The first time a user logs on to your realm app, you should open the realm
```suggestion
   The first time a user logs on to your app, you should open the {+realm+}
```
I think we can just use "app" here since the user doesn't have to be aware of realm and we normally reserve the "realm app" term for the backend, even though that's also technically correct here. And a source constant.

2021-08-06 17:07 UTC, nathan-contino-mongo commented on source/sdk/dotnet/examples/open-a-realm.txt
> +   *asynchronously* to sync data from the server to the device. After that initial
I think we should pull this information directly in to the opening paragraph of "open a synced realm while offline", and possibly justify it more. Will opening a realm asynchronously while offline cause the realm to never open or crash the app? What happens if I open the realm synchronously when I first open it -- just a chuggy, slow app while it downloads changes, or does it fail or cause issues? I think this note is easy to ignore and the opening paragraph of this section would provide a better place to explain these tradeoffs.

2021-08-11 16:49 UTC, dacharyc approved these changes
The "Open a Synced Realm" updates look good, mod one small grammar nit.

I am seeing a lot of warnings from GitHub actions, and there are a lot of code changes that don't seem related to this content update - I am guessing all of that is related to the CI fixes. But just want to call out here that those things are present, and verify this PR contains only the changes you intend. If that's the case, then go for merge after fixing that teensy grammar thing!

2021-08-11 16:49 UTC, dacharyc commented on source/sdk/dotnet/examples/open-a-realm.txt
> +device already have a ``user``, it opens the synced {+realm+} with that user:
```suggestion
device already has a ``user``, it opens the synced {+realm+} with that user:
```

2021-08-11 17:10 UTC, cbush approved these changes

2021-08-11 17:29 UTC, merged