(DOCSP-16245): [iOS] SwiftUI AsyncOpen and AutoOpen docs
mongodb/docs-realm pull request #1278
Opened 2021-08-06 21:45 UTC by dacharyc

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-16245

### Staged Changes (Requires MongoDB Corp SSO)

- [Sync Changes Between Devices](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-16245/sdk/ios/examples/sync-changes-between-devices/#open-a-synced-realm-with-swiftui): New section: "Open a Synced Realm with SwiftUI"

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-08-06 22:30 UTC, terakilobyte requested changes
A few nits/comments, questions, and suggestions.

2021-08-06 22:30 UTC, terakilobyte commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +populate views. These property wrappers provide a syntax that integrates nicely
suggestion: remove editorial flavor
```suggestion
populate views. These property wrappers provide a syntax that integrates
```

2021-08-06 22:30 UTC, terakilobyte commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +  the cost of potentially working with stale data.
Note: This reads more like a flowchart at the moment than describing the provided wrappers. As is, the flow I interpret is
```
    if exists(networkConnection) {
      updateFromRemote()
    } else {
      useLocalRealm()
    }
```

2021-08-06 22:30 UTC, terakilobyte commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +{+app+}s that need to always have up-to-date information from the server, such
suggestion: simplify

```suggestion
{+app+}s that require up-to-date information from the server, such
```

2021-08-06 22:30 UTC, terakilobyte commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +for the user to work with potentially stale data, should use ``@AutoOpen`` to
note: the phrasing for this is different than the "online-first" strategy presented above. Maybe reword to not use jargon initially (offline-first), an then use jargon.

> Apps that are tolerant of potentially stale data ...

2021-08-06 22:30 UTC, terakilobyte commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +should use ``@AsyncOpen`` to open a {+realm+}. This only works if the user has
question: would linking AsyncOpen to the header below be useful here for users that identify this as their desired use-case?

2021-08-06 22:30 UTC, terakilobyte commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +for the user to work with potentially stale data, should use ``@AutoOpen`` to
same question as the other method, should there be a link here for users to jump directly to their desired use-case?

2021-08-09 13:39 UTC, dacharyc commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +  the cost of potentially working with stale data.
Fair point. I omitted the bullets entirely and rewrote this intro section to be clearer, and more consistent with language used elsewhere on the page.

2021-08-09 14:31 UTC, terakilobyte approved these changes
LGTM. One suggestion, but it's probably more personal preference than anything and isn't a blocker to landing this.

2021-08-09 14:31 UTC, terakilobyte commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +should :ref:`use @AutoOpen to open the {+realm+}<swiftui-auto-open-synced-realm>`.
suggestion: This still feels a bit odd/unwieldy. I think it's because there are two clauses here but the previous use-case only has one. Maybe further reword this to introduce it like you did the previous use-case?

2021-08-09 18:22 UTC, dianaafanador3 commented
I think we should mention our new enviromnent value partitionValue
 AsyncOpenPartitionView()
                        .environment(\.partitionValue, <partitionValue>)
which can be used to dynamically inject a partitionValue into @AsyncOpen and @AutoOpen, for example in cases where this value is retrieved from the user id
`AsyncOpenPartitionView()
            .environment(\.partitionValue, user.id)`,
where we get the user id only after loggin in

2021-08-09 20:59 UTC, dacharyc commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +should :ref:`use @AutoOpen to open the {+realm+}<swiftui-auto-open-synced-realm>`.
Hmm, fair point. I've updated it again based on this feedback. Thank you!

2021-08-09 21:01 UTC, dacharyc commented
Hey, @dianaafanador3 , thank you for pointing this out!

> I think we should mention our new enviromnent value partitionValue

I had missed this completely, but have now added it to the documentation here.

2021-08-09 21:53 UTC, cbush reviewed
I find the environment-passing examples to be a bit more confusing than if they were perhaps not there. What about making one section or note that lets users know they can use [the environment(_:_:) view modifier](https://developer.apple.com/documentation/swiftui/view/environment(_:_:)) to pass the partitionValue down?

Commenting for now, will review again upon discussion.

2021-08-09 21:53 UTC, cbush commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +{+app+}s where it's not a problem for the user to work with potentially stale
I don't think this is the correct use of {+app+}? Aren't you referring to apps in general?
```suggestion
Apps where it's not a problem for the user to work with potentially stale 
```

2021-08-09 21:53 UTC, cbush commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +         ...view code...
It's always nice to try to keep it at least syntactically correct:
```suggestion
         // ...view code...
```

2021-08-09 21:53 UTC, cbush commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +   }
This block doesn't look right... where's the @AsyncOpen?

2021-08-09 21:53 UTC, cbush commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +From the LoginView, you can inject the ``.partitionvalue`` environment value
```suggestion
From the LoginView, you can inject the ``.partitionValue`` environment value 
```

2021-08-09 21:53 UTC, cbush commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +From the LoginView, you can inject the ``.partitionvalue`` environment value
```suggestion
From the LoginView, you can inject the ``.partitionValue`` environment value 
```

2021-08-09 21:53 UTC, cbush commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +From the LoginView, you can inject the ``.partitionvalue`` environment value
It doesn't necessarily have to come from the LoginView. Partition values may also not always be based on the user id (though probably). So, it seems a bit specific to refer to "the LoginView" in this doc context.

2021-08-09 21:53 UTC, cbush commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +   }
Scratch that. Self-addressed in the overall review comment.

2021-08-10 14:40 UTC, dacharyc commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +{+app+}s where it's not a problem for the user to work with potentially stale
I used {+app+} here since we were talking about synced realms, but after thinking about this more, yeah, I think you're right and it should be general "Apps". Changing.

2021-08-10 17:11 UTC, cbush approved these changes
Ok, looks clearer now.

What if the examples came before the "pass environment values" sections? It still feels like it could be confusing if you don't know a more complete context is still coming.

And what if the "Pass environment values" section were shared between both auto-open and async open? (as a subheading of "Open ... with SwiftUI" I guess).

Up to you.

2021-08-10 17:11 UTC, cbush commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +changesets before opening {+realm+}s, or open {+realm+}s with data on the
(No comma when not changing the subject)
```suggestion
changesets before opening {+realm+}s or open {+realm+}s with data on the 
```

2021-08-10 18:10 UTC, merged