Add page about copying & bundling a realm in .NET
mongodb/docs-realm pull request #1310
Opened 2021-08-24 16:51 UTC by MongoCaleb

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-17940

### Staged Changes (Requires MongoDB Corp SSO)

- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/writeCopy/sdk/dotnet/advanced-guides/bundle-a-realm/

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-08-24 21:08 UTC, mongomoe commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +(with only the data you want bundled) and then use Visual Studio to bundle the
```suggestion
(with only the data you want to be bundled) and then use Visual Studio to bundle the 
```

2021-08-24 21:10 UTC, mongomoe commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +   #. When promoted, choose :guilabel:`Copy the file to the directory`.
```suggestion
   #. When prompted, choose :guilabel:`Copy the file to the directory`.
```

necessary change: promoted -> prompted

2021-08-24 21:10 UTC, mongomoe commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +to users on first launch. To do this, you can make a copy of an existing realm
```suggestion
to users on the first launch. To do this, you can make a copy of an existing realm 
```

2021-08-24 21:12 UTC, mongomoe commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +   .. literalinclude:: /examples/generated/dotnet/WriteCopy.codeblock.copy_a_realm.cs
C# Syntax highlighting isn't working in this example snippet. Can you add `:language: csharp` below line 33?

2021-08-24 21:17 UTC, mongomoe commented on examples/dotnet/Examples/WriteCopy.cs
> +            realm.WriteCopy(config);
Found this remark in the WriteCopy API link: https://docs.mongodb.com/realm-sdks/dotnet/latest/reference/Realms.Realm.html#Realms_Realm_WriteCopy_Realms_RealmConfigurationBase_

"The destination file cannot already exist." 

Should we do a check to see if the destination file exists ? if (File.Exists(myRealm_copy.realm)) then encrypt + writeCopy

2021-08-24 21:18 UTC, mongomoe reviewed
Close to LGTM just 1 typo fix and a couple other suggestions + 1 question

2021-08-24 21:23 UTC, nirinchev requested changes
Please don't merge this yet - there are technical changes that need to be addressed on several levels.

1. @papafe can you work with Caleb to outline the procedure for bundling a Realm file with a Xamarin application.
2. Typically a bundled resource will need to be copied to the data directory so we'd ideally include a code snippet to determine whether to copy the file from app resources or use the one that was copied previously.
3. @DominicFrei can you look into and help provide a summary for how to bundle resources in a Unity application? Even though we don't have a dedicated Unity page, we should make sure to produce all new content with Unity in mind so that whenever we split the docs, we don't have to rewrite everything.
4. Finally, this doesn't cover bundling synchronized Realms which is fairly key. @DominicFrei can you work with Caleb to outline the differences compared to local ones.

2021-08-24 21:23 UTC, nirinchev commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +   Realm files are cross-platform compatible, which is why you can bundle the
This is not the case for encrypted Realms, so we should make it clear that when bundling files with the app, the Realm should be unencrypted.

2021-08-24 21:23 UTC, nirinchev commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +      :guilabel:`Build Action`, and then choose :guilabel:`EmbeddedResource`.
The database should never be added as an embedded resource as that would significantly increase loading times of the app.

2021-08-25 14:35 UTC, DominicFrei commented
Sounds good, @nirinchev.
@MongoCaleb Let's have a chat or Zoom and talk this through. 👍

2021-08-30 09:59 UTC, DominicFrei commented
> 
> 
> @nirinchev @DominicFrei @papafe
> Out of curiosity, wouldn't it work just as easily to do this:
> 
>     1. Make a copy of the Realm we want bundled.
> 
>     2. Upload the copy to an S3 bucket (or elsewhere, obv.)
> 
>     3. On app load, if the realm file doesn't exist, download it from the bucket.

If I understand correctly this will basically mimick downloading (syncing) the Realm initially so I don't really see an advantage in that.
The idea behind bundling a Realm with the app is that on app start there is no data that needs to be downloaded at all and the app can be used right away (apart from any new data that needs to be synced).

2021-08-31 09:57 UTC, DominicFrei commented on examples/dotnet/Examples/WriteCopy.cs
> +            realm.WriteCopy(config);
You can either check or delete it as I've done in the example that I pushed to the Unity examples repo:
https://github.com/realm/unity-examples-3d-chess/blob/temp/bundled-sync-realm/Bundled%20Realms/Assets/Cube.cs#L47-L48

2021-08-31 09:58 UTC, DominicFrei commented on examples/dotnet/Examples/WriteCopy.cs
> +            realm.WriteCopy(config);
Regarding encryption please also refer to @nirinchev's comment in https://github.com/mongodb/docs-realm/pull/1310#discussion_r695221963

2021-08-31 20:53 UTC, MongoCaleb commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +      :guilabel:`Build Action`, and then choose :guilabel:`EmbeddedResource`.
@nirinchev I believe, based on word from @papafe, that bundling it this way is, in fact, the correct thing to do. Just want to confirm before going further with the remaining updates.

2021-08-31 21:14 UTC, nirinchev commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +      :guilabel:`Build Action`, and then choose :guilabel:`EmbeddedResource`.
Yes, I was mistaken. Ferdinando did test it out and confirmed that embedded resources don't cause excessive memory usage, so this should be just fine.

2021-09-01 21:06 UTC, nirinchev reviewed
Looks good to me. @DominicFrei, @papafe do you think we should show the `using` statements for the code snippets? Or do you think `Path`, `Stream`, `File`, and so on are popular enough API that most people will figure it out?

2021-09-02 07:17 UTC, papafe commented on source/examples/generated/dotnet/Unity.codeblock.read_a_realm_unity.cs
> +// we can access it in Applicatoin.dataPath:
typo in Application

2021-09-02 07:20 UTC, papafe commented
> Looks good to me. @DominicFrei, @papafe do you think we should show the `using` statements for the code snippets? Or do you think `Path`, `Stream`, `File`, and so on are popular enough API that most people will figure it out?

I think it makes sense to use them, so we're always on the safe side. And from what I can see about the staged changed, it seems we already have using in all the possible locations.

2021-09-02 07:21 UTC, papafe commented
Apart from those few notes from Nikola that still need to be addressed and the typo, the rest looks fine for me.

2021-09-02 10:16 UTC, DominicFrei requested changes
Just some small details.

2021-09-02 10:16 UTC, DominicFrei commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +      2. Copy the new {+realm+} file to the project folder of the app. It will
There is not really a `project` folder, rather a `project` tab which shows the `Assets` folder and the `Packages` folder.
The bundled Realm File should be copied into the `Assets` folder.

2021-09-02 10:16 UTC, DominicFrei commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +      2. Copy the new {+realm+} file to the project folder of the app. It will
Especially since we use `Application.dataPath` later in the example, which is specifically the path to the `Assets` folder.

2021-09-02 10:16 UTC, DominicFrei commented on source/examples/generated/dotnet/Unity.codeblock.read_a_realm_unity.cs
> +var realmPath = Application.dataPath + "/copy.realm";
The Realm that we copied is called `bundled.realm`, here we look for `copy.realm`. I'd suggest having the same name to avoid renaming the file to make it work.

2021-09-02 10:16 UTC, DominicFrei commented on examples/dotnet/Examples/Unity.cs
> +        var syncConfiguration = new SyncConfiguration("partition_key", user, "");
```suggestion
        var syncConfiguration = new SyncConfiguration("partition_key", user);
```

If you leave the path empty you can just ignore all together, it's the same result.

2021-09-03 08:34 UTC, DominicFrei approved these changes
LGTM 👍

2021-09-03 09:53 UTC, nirinchev reviewed
A couple final nits from me.

2021-09-03 09:53 UTC, nirinchev commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +         .. note:: Cross-Platform Compatibility
That note applies to Unity as well since most games are cross-platform.

2021-09-03 09:53 UTC, nirinchev commented on examples/dotnet/Examples/Unity.cs
> +        //Realm realm = await Realm.GetInstanceAsync(realmPath);
```suggestion
        //var realm = Realm.GetInstance(realmPath);
```

2021-09-03 09:53 UTC, nirinchev commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +      be sure to call ``WaitForUploadAsync()`` and ``WaitForDownloadAsync()``.
This is not necessary - it might be a good idea depending on the application, but for most use cases, users can probably just start using the data that is already in the file.

2021-09-10 17:17 UTC, MongoCaleb commented
@nirinchev et al - I've updated the page to reflect the fact that we can't bundle Synced realms (for now). Is this enough to cover the issue?

2021-09-10 19:07 UTC, nirinchev approved these changes

2021-09-10 21:12 UTC, merged