(DOCSP-18224): Code for Unity SDK Tutorial Project - readme
mongodb/docs-realm pull request #1331
Opened 2021-09-09 12:17 UTC by mongomoe

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-18224

### Staged Changes (Requires MongoDB Corp SSO)

N/A

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-09-13 21:36 UTC, MongoCaleb commented on tutorial/unity/UnityProjectScripts/RealmScripts/LeaderboardManager.cs
> +        realm = await GetRealm();
Compile error: await in a function that isn't async

2021-09-13 21:36 UTC, MongoCaleb commented on tutorial/unity/UnityProjectScripts/RealmScripts/LeaderboardManager.cs
> +    // public static async Task<Realm> GetRealm()
Because this line is commented out, we get compile errors that GetRealm() doesn't exist.

2021-09-13 21:36 UTC, MongoCaleb commented on tutorial/unity/README.md
> +- Through the Unity Package Manager, install [com.unity.ui.builder](https://docs.unity3d.com/Packages/com.unity.ui.builder@1.0/manual/index.html) and [com.unity.ui.builder](https://docs.unity3d.com/P
Should add to this step about adding from the git repo com.unity.com

2021-09-13 21:36 UTC, MongoCaleb commented on tutorial/unity/README.md
> +- In your project's [hierarchy window](https://docs.unity3d.com/Manual/Hierarchy.html), right click and create a UI Canvas named "Canvas".
Might want to say UI/Canvas so people ca find it a bit easier. Or Canvas within the UI folder

2021-09-13 21:36 UTC, MongoCaleb commented on tutorial/unity/README.md
> +
What should I see that's different from the default game? How do I test it, in other words? More details here would be good.

2021-09-13 21:36 UTC, MongoCaleb commented on tutorial/unity/README.md
> +- Replace the following files with the matching files in this codebase: Scripts/Gameplay/PlayerDeath.cs, Scripts/Gameplay/PlayerEnemyCollision, Scripts/Gameplay/PlayerEnteredVictoryZone.cs, Scripts/G
Might be easier to read as 2 bulleted lists (the following files in /Gameplay and this file in Mechanics)

2021-09-13 21:36 UTC, MongoCaleb commented on tutorial/unity/README.md
> +- Replace the following files with the matching files in this codebase: Scripts/Gameplay/PlayerDeath.cs, Scripts/Gameplay/PlayerEnemyCollision, Scripts/Gameplay/PlayerEnteredVictoryZone.cs, Scripts/G
Also, you list PlayEnteredVictoryZone twice

2021-09-20 21:11 UTC, cbush reviewed
Some bluehawk comments. You can update the workflow file to add the non-Bluehawked file extensions to the list (`-i "*.md" -i "*.properties" -i "*.lock"`...)

2021-09-20 21:11 UTC, cbush commented on tutorial/unity/UnityProjectScripts/RealmScripts/Constants.cs
> +        public const string AppId = "unity-tutorial-3-kgzvn";
Why not use `:replace:` instead to swap "unity-tutorial-3-kgzvn" with "<your-realm-app-ID-here>"? Then you won't have to fiddle with states. See examples/ios for an example.

2021-09-20 21:11 UTC, cbush commented on tutorial/unity/UnityProjectScripts/RealmScripts/LeaderboardManager.cs
> +    // :code-block-start: listen-for-stat-changes
Duplicate id. This is probably supposed to be something else?

2021-09-21 15:33 UTC, cbush commented on tutorial/unity/UnityProjectScripts/RealmScripts/RealmController.cs
> +        // TODO: within a write transaction, delete the current Stat object, and it's reference in the current Player object
```suggestion
        // TODO: within a write transaction, delete the current Stat object, and its reference in the current Player object
```

2021-09-21 15:33 UTC, cbush commented on tutorial/unity/UnityProjectScripts/RealmScripts/RealmController.cs
> +        if (runTime <= 30) // if the game is beat in in less than or equal to 30 seconds, +80 bonus points
beat in in -> beaten in ?

2021-09-22 19:40 UTC, mongomoe commented on tutorial/unity/README.md
> +- Through the Unity Package Manager, install [com.unity.ui.builder](https://docs.unity3d.com/Packages/com.unity.ui.builder@1.0/manual/index.html) and [com.unity.ui.builder](https://docs.unity3d.com/P
Resolving this convo as we figured it out through slack. Also for anyone reading this comment, this step is simplified in: 

[step 2: Update Your Project Manifest](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18225-Unity-Tutorial-Docs/tutorial/unity/#update-your-project-manifest)

2021-09-22 19:41 UTC, mongomoe commented on tutorial/unity/README.md
> +- Replace the following files with the matching files in this codebase: Scripts/Gameplay/PlayerDeath.cs, Scripts/Gameplay/PlayerEnemyCollision, Scripts/Gameplay/PlayerEnteredVictoryZone.cs, Scripts/G
Resolving this convo as those two files have been removed from this pr

2021-09-22 20:34 UTC, mongomoe commented on tutorial/unity/UnityProjectScripts/RealmScripts/LeaderboardManager.cs
> +        realm = await GetRealm();
Fixed now 👍: https://github.com/mongodb/docs-realm/blob/dac393210a7438a514dd606734426d006052c961/tutorial/unity/UnityProjectScripts/RealmScripts/LeaderboardManager.cs#L44

2021-09-22 20:39 UTC, mongomoe commented on tutorial/unity/README.md
> +- In your project's [hierarchy window](https://docs.unity3d.com/Manual/Hierarchy.html), right click and create a UI Canvas named "Canvas".
The word 'canvas' here refers to the UI element within the Unity Editor's [hierarchy window ](https://docs.unity3d.com/Manual/Hierarchy.html) rather than within your project folder. For instance, there is no file or folder called canvas in this repository.

2021-09-23 14:42 UTC, DominicFrei requested changes
Here is my first run through. I do have some more suggestions in the work, but will probably only get to it tomorrow.

2021-09-23 15:18 UTC, DominicFrei commented
I compared the `local` branch of the code snippets repo with the result after working through the tutorial.
I did not end up adjusting `private int getRealmPlayerTopStat()` and `private void createLeaderboardUI()` during the tutorial and I can't find them there. Can you point to what my misunderstanding is? :)

2021-09-27 16:46 UTC, DominicFrei commented
I have added a PR for my code change suggestions: https://github.com/mongomoe/bluehawked-unity-code/pull/3

2021-09-28 12:38 UTC, mongomoe commented on tutorial/unity/README.md
> +- In your project's [hierarchy window](https://docs.unity3d.com/Manual/Hierarchy.html), right click and create a UI Canvas named "Canvas".
Resolving all these README instruction comments because I've removed these instructions from the README since we (deved or anyone looking to contribute) can follow the steps in the actual documentation.

2021-09-28 12:38 UTC, mongomoe commented on tutorial/unity/README.md
> +
Resolving all these README instruction comments because I've removed these instructions from the README since we (deved or anyone looking to contribute) can follow the steps in the actual documentation.

2021-09-28 12:50 UTC, mongomoe commented on tutorial/unity/UnityProjectScripts/RealmScripts/RealmController.cs
> +        if (runTime <= 30) // if the game is beat in in less than or equal to 30 seconds, +80 bonus points
Fixed 👍

2021-09-28 12:52 UTC, mongomoe commented on tutorial/unity/UnityProjectScripts/RealmScripts/LeaderboardManager.cs
> +    // :code-block-start: listen-for-stat-changes
Fixed

2021-09-28 12:58 UTC, mongomoe commented on tutorial/unity/UnityProjectScripts/RealmScripts/Constants.cs
> +        public const string AppId = "unity-tutorial-3-kgzvn";
Good idea, fixed now 👍

2021-09-28 13:13 UTC, mongomoe commented on tutorial/unity/UnityProjectScripts/RealmScripts/RealmController.cs
> +        // TODO: open a realm and return it
I chose the wording "Open a realm" rather than "Create a realm" to match the .NET documentation on it https://docs.mongodb.com/realm/sdk/dotnet/examples/open-a-realm/ 

It also imo sounds more accurate given the method name is "GetInstance()" rather than "CreateInstance()"

2021-09-28 17:59 UTC, mongomoe commented on tutorial/unity/UnityProjectScripts/RealmScripts/StatModel.cs
> +    public Player StatOwner { get; set; }
Resolving this conversation, since we discussed this via zoom. 

Fyi, to anyone else reading this conversation - we ended up going with two realm objects rather than Stat being an embedded object, so that developers could query Stat directly (for example in ScoreCardManager.cs).

2021-09-29 00:01 UTC, mongomoe commented on tutorial/unity/UnityProjectScripts/RealmScripts/StatModel.cs
> +    public ObjectId Id { get; private set; } = ObjectId.GenerateNewId();
Resolving this conversation since we discussed via zoom. 

Fyi to anyone reading this:
- We decided to go with a string _id for PlayerModel because the MongoDB Realm User._id is returned as a string, and since the MongoDB Realm User correlates to the Player they are kept consistent.
- Fixed order of MapTo/PrimaryKey to be consistent

2021-09-29 00:04 UTC, mongomoe commented on tutorial/unity/UnityProjectScripts/RealmScripts/PlayerModel.cs
> +    [Required]
We actually do that for the StatModel, but for the PlayerModel we assign the Id value in RealmController. This is because, for the synced version of the game, we get the id from the MongoDB Realm User. So we need to get that specific user.id for sync, rather than a random one. 

 For the local version of the game we generate a random one in RealmController, rather than PlayerModel. This is done so that readers do not have to change the PlayerModel file when adding sync to their game.

2021-09-30 14:52 UTC, DominicFrei approved these changes
Don't see any open comments. 👍

2021-09-30 18:02 UTC, MongoCaleb approved these changes
LGTM with one check about code comments.

2021-09-30 18:02 UTC, MongoCaleb commented on tutorial/unity/UnityProjectScripts/RealmScripts/AuthenticationManager.cs
> +    // // OnPressLogin() is an asynchronous method that calls RealmController.SetLoggedInUser to login with the values from the userInput and passInput
Make sure the comments don't wrap beyond the standard width (throughout the code examples).

2021-09-30 18:02 UTC, MongoCaleb commented on tutorial/unity/UnityProjectScripts/RealmScripts/AuthenticationManager.cs
> +    #region UnityLifecycleMethods
Nice use of #region...I never think to do this, and it surely helps learners.

2021-09-30 18:22 UTC, cbush reviewed
I think you're overusing `state-uncomment`. Could you consider finding ways to reduce the number of commented blocks?

2021-09-30 18:22 UTC, cbush commented on tutorial/unity/UnityProjectScripts/RealmScripts/AuthenticationManager.cs
> +    // }
Why do these large blocks of code need to be commented out? Maybe it would be better to abstract out these functions (loginWithBackend vs. loginWithoutBackend or something) so that at least both versions can be compiled.

2021-09-30 18:22 UTC, cbush commented on tutorial/unity/UnityProjectScripts/RealmScripts/AuthenticationManager.cs
> +    // //  when the start button is clicked, toggle between registration modes
This line won't be formatted correctly when the comments are removed.

2021-09-30 18:22 UTC, cbush commented on tutorial/unity/UnityProjectScripts/RealmScripts/AuthenticationManager.cs
> +    //     passInput.isPasswordField = true;
If all this stuff is repeated from above, why not nest the state block within the Start() method so you don't have to a) repeat yourself and b) have large swaths of commented code?

2021-10-04 03:34 UTC, mongomoe commented on tutorial/unity/UnityProjectScripts/RealmScripts/AuthenticationManager.cs
> +    // //  when the start button is clicked, toggle between registration modes
Fixed 👍

2021-10-04 03:35 UTC, mongomoe commented on tutorial/unity/UnityProjectScripts/RealmScripts/AuthenticationManager.cs
> +    //     passInput.isPasswordField = true;
Good idea, fixed now

2021-10-04 15:42 UTC, mongomoe commented on tutorial/unity/UnityProjectScripts/RealmScripts/AuthenticationManager.cs
> +    // }
Abstracted a few functions to names like: {funcName} and {funcNameWithBackend} now 👍  Originally had it as the same function name so that the user experience was a bit smoother and users wouldn't have to change function calls when adding sync to their app. 

The only area where your suggestion is not utilized yet right now is the "SetLoggedInUser" methods which might take a larger amount of fiddling/moving things around around with, so I'll keep them as is for at least this iteration of this PR.

2021-10-04 15:48 UTC, mongomoe commented
@cbush per your top level comment:
```
"I think you're overusing state-uncomment. Could you consider finding ways to reduce the number of commented blocks?"
```
 removed a few instances of the 'state-uncomment-start' in the latest commit, but checked out the other tutorial folders and they're also using around the same amount (if not more), so I think to some degree these are necessary for the tutorials. But I did try to remove some instances where I could. Lmk if this is okay.

2021-10-04 15:49 UTC, mongomoe commented on tutorial/unity/UnityProjectScripts/RealmScripts/AuthenticationManager.cs
> +    #region UnityLifecycleMethods
Thanks! Can't take credit for this one, it was a suggestion from Dominic

2021-10-04 15:49 UTC, mongomoe commented on tutorial/unity/UnityProjectScripts/RealmScripts/AuthenticationManager.cs
> +    // // OnPressLogin() is an asynchronous method that calls RealmController.SetLoggedInUser to login with the values from the userInput and passInput
Fixed 👍

2021-10-04 15:50 UTC, cbush commented
Which tutorial did you check? They are not really needed, I think the amount could be reduced there too.

2021-10-04 18:33 UTC, cbush approved these changes

2021-10-04 18:42 UTC, mongomoe commented
@cbush per the top level comment:
```
"Which tutorial did you check? They are not really needed, I think the amount could be reduced there too."
```
Answer: 
Looks like the clients have the following instances of "state-uncomment-start"s:
kotlin-android: 26
swift-ios:  56
dotnet: 22
web: 32 
Unity: 9

So Unity actually has the least instances of it.

I definitely think the 9 instances in this Unity PR are somewhat necessary. We could theoretically replace them w/ "state-start" but that might be a user experience tradeoff, wherein there would have to be two versions of each method that required sync (for instance GetRealm and GetRealmSynced). In addition, some of the uses of "state-uncomment" are done inside functions such as "Start()" that are unity specific and can't have a "StartSynced()" because it is called by Unity internally.

At the very least I think some instances of "state-uncomment-start" are worth it, even though it may be ugly to look at commented code.

2021-10-04 19:03 UTC, cbush commented
Ok, but the problem isn't state-uncomment. The problem is commenting out large swathes of code in the source repo when you don't have to.

2021-10-04 19:07 UTC, cbush commented
Commented code is unchecked code. That decreases our confidence that the tutorial actually compiles. It's also harder to work with, as the IDE will know it's commented and not bother formatting it etc. We should be validating that everything works by running Bluehawk and testing the different state outputs, but we can also make our lives easier by catching compile errors at source as well.

2021-10-04 20:05 UTC, mongomoe commented
@cbush Fair point on the formatting + the code compiling. In the recent commit, other than SetLoggedInUser, my uses of "state-uncomment-start" are pretty small code blocks. I've updated my [JIRA Ticket](https://jira.mongodb.org/browse/DOCSP-18846) containing v2 improvements to include the refactoring of SetLoggedInUser.

2021-10-05 17:56 UTC, merged