(DOCSP-18707): [iOS] Add async/await methods for App.login and asyncOpen
mongodb/docs-realm pull request #1353
Opened 2021-09-21 14:00 UTC by dacharyc

## Pull Request Info

This PR documents the changes that were introduced in [10.15.0](https://github.com/realm/realm-cocoa/releases/tag/v10.15.0) - new async support for `App.login` and `asyncOpen`, and the introduction of `OpenBehavior` and the `downloadBeforeOpen` param. There will be a separate PR for the rest of the async/await changes when they are released.

### Jira

- https://jira.mongodb.org/browse/DOCSP-18707

### Staged Changes (Requires MongoDB Corp SSO)

- [Authenticate Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18707/sdk/ios/examples/authenticate-users/#async-await-login): New section for Async/Await Login
- [Sync Changes Between Devices](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18707/sdk/ios/examples/sync-changes-between-devices)
  - New Swift text and code example: [Open a Synced Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18707/sdk/ios/examples/sync-changes-between-devices/#open-a-synced-realm)
  - New section and code example: [Download Changes Before Open](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18707/sdk/ios/examples/sync-changes-between-devices/#download-changes-before-open)
  - [Overview](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18707/sdk/ios/examples/sync-changes-between-devices/#overview): Tweaked this section a little and the "Synced Realms vs Local Realms" verbiage that is a sub-section here to reflect the new download behavior functionality
- [Legacy Realm Sync Open Methods](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18707/sdk/ios/examples/sync-realm-open-legacy/): This page splits off the old open methods which we still need to retain for users who are building for older iOS targets and with older versions of Swift. `asyncOpen` behavior is different enough that it warrants keeping around all the verbiage, etc. The only new content on this page is the `Overview`.

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-09-22 23:26 UTC, terakilobyte requested changes
Looks good overall. I noticed a lot of future tense throughout that I didn't highlight, and some inconsistencies in naming.

2021-09-22 23:26 UTC, terakilobyte commented on source/sdk/ios/examples/sync-realm-open-legacy.txt
> +      user, and pass the  user's :swift-sdk:`Configuration <Structs/Realm/Configuration.html>`
question: "log in the user" or "log the user in"?

2021-09-24 01:42 UTC, dacharyc commented on source/sdk/ios/examples/sync-realm-open-legacy.txt
> +The examples on this page describe how to work with synced {+realms+} in
Generally we use the term "synced" when referring to realms in the SDK docs. 260 results across the SDK docs, vs 6 instances of "synchronized." Good question, though!

2021-09-24 01:50 UTC, dacharyc commented on source/sdk/ios/examples/sync-realm-open-legacy.txt
> +for iOS targets prior to 15.0, with Swift versions older than 5.5, or with
We generally don't pair "Realm" with "iOS SDK." The Swift library is RealmSwift, the Obj-C library is Realm, and the repo is realm-cocoa - we haven't really paired the "Realm" with "iOS" anywhere else. Nate did say today in standup that there will be a naming conversation soon, as the Realm SDKs tend to conflate platform and language in inconsistent ways, so hopefully we'll have more alignment within the org soon around how to refer to the SDKs, and we'll have a naming cleanup project.

2021-09-24 02:05 UTC, dacharyc commented on source/sdk/ios/examples/sync-realm-open-legacy.txt
> +   If you're using Swift SDK 10.15.0 or newer, see the :ref:`Sync Changes
Yeah, the iOS SDK is how we generally refer to this SDK, but these enhancements are specifically around the new Swift language features. So I was trying to get that "Swift" keyword front-and-center. There are definitely naming contortions when we have a single SDK "name" to refer to multiple languages, and only one of them gets the new stuff. Hopefully the upcoming naming conversation will provide clearer guidance around this.

2021-09-24 02:16 UTC, dacharyc commented on source/sdk/ios/examples/sync-realm-open-legacy.txt
> +you'll use ``asyncOpen`` to open the {+realm+}, but that requires a user
That's a fair question. The legacy `asyncOpen` method has caused some confusion for developers. It is a method that always downloads changes before opening the realm. Unfortunately, that's not obvious in the name - async doesn't necessarily imply that it requires an active internet connection. We've also given guidance previously that users should use `asyncOpen` as the default method for opening a realm, as it ensures their data is always fresh. However, we've had developers push back on those recommendations because it requires an active internet connection. 

This paragraph is an attempt to say "you _can_ open a synced realm offline, and here's how to do it, but if you want to use the `asyncOpen` method, that does _not_ work offline." This page has gone through so many revisions to try to clear this up for developers, and as a result, it has crept into almost all sections of the page.

2021-09-24 02:22 UTC, dacharyc commented on source/sdk/ios/examples/sync-realm-open-legacy.txt
> +      user, and pass the  user's :swift-sdk:`Configuration <Structs/Realm/Configuration.html>`
Rewrote this line to remove the future tense and move the preposition.

2021-09-24 02:35 UTC, dacharyc commented
> Looks good overall. I noticed a lot of future tense throughout that I didn't highlight, and some inconsistencies in naming.

Thanks, @terakilobyte ! I think I stripped all the future tense in these edits. I did leave responses to your comments; the naming is tricky, but hopefully we'll have more formal guidance around that soon. I'd love if you could take another look.

2021-09-24 04:47 UTC, terakilobyte commented on source/sdk/ios/examples/sync-realm-open-legacy.txt
> +   If you're using Swift SDK 10.15.0 or newer, see the :ref:`Sync Changes
Hmm, I'm not sure that justifies using two identifiers within 16 lines to refer to the same thing. I bring this up again because it was confusing during the review. Two identifiers made me check to ensure there weren't two different things.

2021-09-24 05:00 UTC, terakilobyte approved these changes
The changes lgtm. I'd still consider sticking to a single name for an entity to avoid confusion.

2021-09-24 13:33 UTC, dacharyc commented on source/sdk/ios/examples/sync-realm-open-legacy.txt
> +   If you're using Swift SDK 10.15.0 or newer, see the :ref:`Sync Changes
Fair point - I reworked this a little to:
>Swift 5.5 with iOS SDK 10.15.0 or newer

Because that's really what the new stuff applies to, for the moment. Thanks for the feedback!

2021-09-24 21:26 UTC, merged

2021-10-04 12:10 UTC, jsflax commented on source/examples/generated/code/start/Authenticate.codeblock.async-await.swift
> +    return loggedInUser
I know I'm a bit late on this, but these functions wrapping the Realm functions are kind of awkward. Is there any way to eliminate these wrapping methods?