(DOCSP-18598): Create Guides for Deleting Realm Apps
mongodb/docs-realm pull request #1382
Opened 2021-10-04 15:27 UTC by nspektor

## Pull Request Info

- Create new section under the Manage Realm Apps section for deleting apps and add 3 guides for the 3 methods of deleting an app (UI, CLI, API)

### Jira

- https://jira.mongodb.org/browse/DOCSP-18598

### Staged Changes (Requires MongoDB Corp SSO)

- [Delete with Realm UI](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18598/manage-apps/delete/delete-with-realm-ui/)
- [Delete with CLI](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18598/manage-apps/delete/delete-with-cli/)
- [Delete with API](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-18598/manage-apps/delete/delete-with-api/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-10-04 18:10 UTC, dacharyc requested changes
Awesome - great job adding the new section and all the novel procedures. I like the swapping stuff to includes here, too. Suggested fixes for a few nits and potential additions to consider.

2021-10-04 18:10 UTC, dacharyc commented on source/includes/steps-cli-delete.yaml
> +title: Run the App Delete Command
Hmm, here we go right from authenticate to delete. In the API instructions, we tell the users how to get a list of their apps so they'll have the right app ID.

We might add a similar step here - maybe telling users they can use `realm-cli apps list` to get a list of apps by name, and potentially drill in with `realm-cli apps describe` to verify which app they want to delete.

One could argue that the prompt to select an app to delete from a list of apps makes this redundant, but choosing to list the apps ahead of delete gives users an opportunity to verify more details about an app and be sure they're deleting the right one. Maybe it would be an optional step, since they can get that prompt by using `delete` without specifying an ID? I can't decide if that would be helpful, or if it's just redundant since list functionality is built into `delete`. Feel free to take this suggestion or leave it!

2021-10-04 18:16 UTC, nspektor commented on source/includes/steps-api-delete.yaml
> +  If creation succeeds the {+backend+} returns a ``204`` response.
oops! copy paste  :( thanks for noticing!

2021-10-05 15:35 UTC, nspektor commented on source/includes/steps-ui-delete.yaml
> +  Select the :guilabel:`Realm` tab at the top.
hmm, everywhere I see :guilabel:Realm tab there doesnt seem to be an associated screenshot, I can add one but Im not sure if it adds enough value to justify having to maintain it, especially since for the screenshot to be useful it has to have the whole page i think (to show location in relation to everything the user sees) @dacharyc

2021-10-05 15:49 UTC, nspektor commented on source/manage-apps/delete/delete-with-api.txt
> +- A `{+atlas+}
should the section still be titled Prerequisites? or just Prerequisite

2021-10-05 22:12 UTC, merged