(DOCSP-19450): Bundle a realm -- Android SDK
mongodb/docs-realm pull request #1485
Opened 2021-11-20 09:04 UTC by nathan-contino-mongo

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-19450

### Staged Changes (Requires MongoDB Corp SSO)

- [Android SDK - Bundle a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19450/sdk/android/advanced-guides/bundle-a-realm/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-11-20 15:35 UTC, nathan-contino-mongo commented on examples/android/sync/build.gradle
> +        classpath "io.realm:realm-gradle-plugin:10.9.0-SNAPSHOT"
Once 10.9.0 comes out, we'll want to change this library reference to point to the production release. It's OK to leave the other snapshot release stuff in here because we'll need it sporadically in the future for testing new releases anyway.

```suggestion
        classpath "io.realm:realm-gradle-plugin:10.9.0"
```

2021-11-22 17:29 UTC, MongoCaleb reviewed
I think this page would benefit from a bit of restructuring and a little more continuity between the sections. See my thoughts below.

2021-11-22 17:29 UTC, MongoCaleb commented on source/sdk/android/examples/bundle-a-realm.txt
> +Copy a Realm File
Is this something different from the steps in the Overview? How does it relate? Is it an alternative? In other words, we need a bit of continuity glue here.

2021-11-22 17:29 UTC, MongoCaleb commented on source/sdk/android/examples/bundle-a-realm.txt
> +Using the Copied Realm File
I think this page would benefit from 2 sections, so the two Copy-related sections are together (as subsections).

2021-11-22 23:52 UTC, nathan-contino-mongo commented on source/sdk/android/examples/bundle-a-realm.txt
> +.. warning:: Synced Realm Bundling and Client Maximum Offline Time
IMO I think this warning is really important to understand *before* you choose to bundle a realm. I understand that it's a lot up front, but if your app doesn't release on the right cadence, this outright eliminates the ability to bundle a realm, so I think it's important to raise early for readers.

2021-11-22 23:54 UTC, nathan-contino-mongo commented on source/sdk/android/examples/bundle-a-realm.txt
> +Copy a Realm File
This section does share common steps with the overview, but contains additional information (concrete API reference links to relevant methods) and a code sample. I'll add an extra sentence explaining the connection at the end of the overview to make this clearer.

2021-11-22 23:55 UTC, nathan-contino-mongo commented on source/sdk/android/examples/bundle-a-realm.txt
> +Using the Copied Realm File
I don't understand this request. This section layout is partially based off of the [.NET equivalent](https://docs.mongodb.com/realm/sdk/dotnet/advanced-guides/bundle-a-realm/), and the second "include" section chronologically occurs *between* the two copy sections.

2021-11-23 00:07 UTC, MongoCaleb commented on source/sdk/android/examples/bundle-a-realm.txt
> +Copy a Realm File
Sounds good....though I don't see any new sentence added. In fact, I don't see a commit newer than 3 days ago. ¯\_(ツ)_/¯

2021-11-23 00:10 UTC, MongoCaleb approved these changes
LGTM

2021-12-01 15:39 UTC, cmelchior requested changes

2021-12-01 15:39 UTC, cmelchior commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/BundleTest.java
> +            App app = new App(new AppConfiguration.Builder(appID)
For simple cases like this it is easier to use `App app = new App(appId);`

2021-12-01 15:39 UTC, cmelchior commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/BundleTest.java
> +                        Realm.getInstanceAsync(config, new Realm.Callback() {
Since you are using a manul handler thread here. There is no need to call `getInstanceAsync` here, you are already on a background thread, so you can just use blocking `Realm.getInstance()`...that will also simplify the remaining code.

2021-12-01 15:39 UTC, cmelchior commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/BundleTest.java
> +                                Realm.compactRealm(config); // :emphasize:
This is done automatically as part of writing a copy

2021-12-01 15:39 UTC, cmelchior commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/BundleTest.java
> +public class BundleTest extends RealmTest {
You might want to hint to people that doing this in a node script using the Realm JS API might be easier depending on their setup. Especially on CI, where it can be automated much easier. But obviously also requires that JS has shipped support for this.

2021-12-01 15:39 UTC, cmelchior commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/BundleTest.kt
> +            val app = App(AppConfiguration.Builder(appID).build())
Same with `App(appId)` being easier here.

2021-12-01 15:39 UTC, cmelchior commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/BundleTest.kt
> +                        Realm.getInstanceAsync(config, object : Realm.Callback() {
Consider making this blocking similar to Java

2021-12-01 15:39 UTC, cmelchior commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/BundleTest.kt
> +                                Realm.compactRealm(config) // :emphasize:
This is done automatically, so I would just remove it.

2021-12-01 17:43 UTC, cmelchior approved these changes

2021-12-08 16:05 UTC, merged