(DOCSP-14806): Rename iOS SDK -> Swift SDK
mongodb/docs-realm pull request #1490
Opened 2021-11-22 20:31 UTC by cbush

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-14806

### Staged Changes (Requires MongoDB Corp SSO)

- https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ios-to-swift/sdk/swift/

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-11-22 21:04 UTC, dacharyc approved these changes
Overall, this looks great! Just a couple of questions.

Thank you for making this PR!

2021-11-22 21:04 UTC, dacharyc commented on source/studio/modify-schema.txt
>        :tabid: ios
So this is part of tabs-realm-sdks per ln 120 above. This renders as "iOS SDK" on [the page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/ios-to-swift/studio/modify-schema/). Where do we update that?

2021-12-01 16:18 UTC, jsflax approved these changes

2021-12-01 16:18 UTC, jsflax commented on source/stitch.txt
> +   (Legacy) Stitch Swift/Swift SDK <http://stitch-sdks.s3-website-us-east-1.amazonaws.com/stitch-sdks/swift/6/>
We called it the iOS SDK.

2021-12-01 20:58 UTC, dacharyc approved these changes
Overall, looks great! I did spot what looks to me like a duplicate redirect, and I also still have that outstanding question about how we rename iOS to Swift in the tabs-realm-sdks - is that a snooty thing that needs to happen outside of our repo? Or is it defined somewhere in the repo?

2021-12-01 20:58 UTC, dacharyc commented on config/redirects
> +raw: realm/sdk/ios/integrations -> ${base}/realm/sdk/swift/integrations/
Looks like this one is in here twice - here and ln 317 above.

2021-12-01 20:59 UTC, dacharyc requested changes
Oh, looks like I missed a bunch of Snooty build errors - the title underlines are now too short with the longer "Swift" vs. "iOS".

2021-12-02 16:42 UTC, dacharyc approved these changes

2021-12-06 21:10 UTC, merged