(DOCSP-19629): Configure Prettier and ESLint for Web SDK tutorial
mongodb/docs-realm pull request #1492
Opened 2021-11-23 16:56 UTC by mongodben

## Pull Request Info

Added Prettier and ESLint configuration to the Web SDK tutorial to normalize code formatting across the project and enforce standard practices. 

Note that this expands the scope of the initial ticket request, which was just to run prettier on the repo. Based on the changes in this PR, coding practices should be enforced, so it's no longer necessary to manually run prettier. 

### Jira

- https://jira.mongodb.org/browse/DOCSP-19629

### Staged Changes (Requires MongoDB Corp SSO)

- N/A

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-11-23 17:00 UTC, cbush requested changes
Why did you make a specific prettierrc when we can just use the standard? The whole point is avoiding arguments about personal preferences.

2021-11-23 17:04 UTC, mongodben commented on tutorial/web/.prettierrc.json
> +  "trailingComma": "none",
personal preference 🤷. i can change to make it with commas

2021-11-23 17:09 UTC, mongodben commented on tutorial/web/.prettierrc.json
> +  "trailingComma": "none",
changes to make `"trailingComma": "all",`

2021-11-23 17:48 UTC, cbush commented on tutorial/web/.prettierrc.json
> +  "trailingComma": "none",
Why not just remove the prettierrc though?

2021-11-23 18:26 UTC, mongodben commented on tutorial/web/.prettierrc.json
> +  "trailingComma": "none",
yep looks like we can do that. i believe i put like this b.c i was following along w some tutorial. 

upon reading through the [prettier default options docs](https://prettier.io/docs/en/options.html), the only difference btwn what's here currently and the default is the default is `"trailingComma": "es5"`. there'd be no practical difference btwn them here b.c the [only difference for these settings relates to typescript](https://prettier.io/docs/en/options.html#trailing-commas).

will remove this file and validate that everything still works as expected.

2021-11-23 18:58 UTC, mongodben commented on tutorial/web/.prettierrc.json
> +  "trailingComma": "none",
removed the `.prettierrc` file and associated changes.

2021-11-24 15:33 UTC, cbush approved these changes

2021-11-24 15:33 UTC, cbush commented on tutorial/web/.eslintrc.json
> +    "comma-dangle": ["always-multiline"]
Is this needed?

2021-11-24 16:32 UTC, mongodben commented on tutorial/web/.eslintrc.json
> +    "comma-dangle": ["always-multiline"]
yep was needed b/c prettier was conflicting w the eslint config. this fixed.

2021-11-24 16:32 UTC, merged

2021-11-24 16:42 UTC, cbush commented on tutorial/web/.eslintrc.json
> +    "comma-dangle": ["always-multiline"]
This shouldn't be needed. Could you retry without it now that the prettierrc is gone?

2021-11-24 17:18 UTC, mongodben commented on tutorial/web/.eslintrc.json
> +    "comma-dangle": ["always-multiline"]
sure thing. i think i already did. but maybe this is exposing a deeper issue with the setup that was patched overby adding these rules

2021-11-24 20:29 UTC, mongodben commented
since this PR and associated ticket are already closed, creating new ticket to track - https://jira.mongodb.org/browse/DOCSP-19864