(DOCS-14138): Add SDK-agnostic Realm Query Language reference
mongodb/docs-realm pull request #1504
Opened 2021-11-30 19:25 UTC by dacharyc

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCS-14138

### Staged Changes (Requires MongoDB Corp SSO)

- [Realm Query Language](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-14138/reference/realm-query-language/): New page, based on iOS NSPredicate page, updated to remove SDK-specific references/examples, provide JSON (BSON) schema, and add SORT/DISTINCT/LIMIT

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-12-01 04:36 UTC, cbush approved these changes

2021-12-01 04:36 UTC, cbush commented on source/reference/realm-query-language.txt
> +for every :term:`object <Realm object>` in the collection being
The section is about operators but this paragraph really explains filters, which were already explained above. Can we clarify?

2021-12-01 04:36 UTC, cbush commented on source/reference/realm-query-language.txt
> +       specify ascending (``ASC``) or descending (``DSC``) order.
Is it definitely "DSC" and not "DESC"?

2021-12-01 14:25 UTC, dacharyc commented on source/reference/realm-query-language.txt
> +for a fetch or for in-memory filtering. Queries evaluate an operator
I don't actually _know_ - that came from the Node.js page, I think. What about:

> constrain searches when retrieving objects.

2021-12-01 17:56 UTC, tgoyne commented
The aggregates section is missing an example of aggregates on a primitive collection (i.e. `values.@sum > 10` on a `List<Int>` property). Otherwise looks good to me.

2021-12-02 14:43 UTC, nirinchev requested changes
Looks good so far. Some notable things that are missing are:

1. Information about how queries on dictionary properties behave.
2. Information about how data is serialized in a query. Obviously you can use value substitution and pass $0, $1, and so on, but sometimes people want to go the hard route and stringify the date/objectId/uuid themselves.
3. Information about backlink queries.
4. Information about comparing two properties. E.g. `SUBQUERY(tasks, $t, $t.isCompleted).@count > minQuota` where `minQuota` and `tasks` are properties on the same object.

It seems like you may have tested this using the iOS SDK which is precisely the SDK that doesn't use RQL, so it might be a good idea to re-run your tests with the JS SDK or even better - create actual unit tests like the ones the docs team maintains for the SDK-specific docs. That way it will be easier to add and test new queries.

2021-12-02 14:43 UTC, nirinchev commented on source/reference/realm-query-language.txt
> +searches when retreiving objects. Queries evaluate a predicate for every
```suggestion
searches when retrieving objects. Queries evaluate a predicate for every 
```

2021-12-02 14:43 UTC, nirinchev commented on source/reference/realm-query-language.txt
> +You can use Realm Query Language in every SDK with your SDK's filter method.
I don't think the iOS SDK exposes this - they only expose the NSPredicate query API, which while similar, are different from RQL.

2021-12-02 14:43 UTC, nirinchev commented on source/reference/realm-query-language.txt
> +- An operator and up to two argument expression(s).
I'm not sure I understand this - what are the argument expressions?

2021-12-02 14:43 UTC, nirinchev commented on source/reference/realm-query-language.txt
> +You can iterate through a collection property with another query using the
Is there an expectation that the subquery is followed by an aggregation operator, such as `@count`, `@avg`, and so on to be used in the query? I think we should provide more examples as this is a fairly complex concept and we should be explicit about what's possible and what isn't.

2021-12-02 14:43 UTC, nirinchev commented on source/reference/realm-query-language.txt
> +   .. code-block:: json
I think using json schema to explain the data structure is going to be foreign for the majority of Realm users. We can instead use a C-based pseudocode language to convey the types without the complexities and verbosity of json schema. Like:

```
class Task {
    ObjectId id;
    string name;
    bool isComplete;
    string? assignee;
    int priority;
    int progressMinutes;
}

class Project {
    ObjectId id;
    string name;
    Task[] tasks;
}
```

2021-12-02 14:43 UTC, nirinchev commented on source/reference/realm-query-language.txt
> +      "assignee IN {'Ali', 'Jamie'}"
Is this really supported?

2021-12-02 14:43 UTC, nirinchev commented on source/reference/realm-query-language.txt
> +     - Evaluates to ``true`` if the left-hand string expression is found anywhere in the right-hand string expression.
I don't think this is correct. `CONTAINS` will return `true` if the left hand expression contains the right-hand one, while I would expect `IN` to be the opposite.

2021-12-02 14:43 UTC, nirinchev commented on source/reference/realm-query-language.txt
> +A **set operator** uses specific rules to determine whether
Is "set" a common terminology for these operators? Initially I thought those only applied to collections that are of type Set, but they apply to any collection - i.e. set, list, backlinks. Additionally, this should explain how these operators interact with dictionaries which have both a key and a value.

2021-12-02 14:43 UTC, nirinchev commented on source/reference/realm-query-language.txt
> +   "progressMinutes > 1 AND name == %@", "Ali"
I don't think %@ is valid value substitution here.

2021-12-03 14:04 UTC, cmelchior commented on source/reference/realm-query-language.txt
> +Filters consist of **expressions** in a predicate. An expression consists of
This sentence makes sense to me, but the following details, don't sound right, how can just "42" be a valid expression  or "myFieldName"?

2021-12-03 14:42 UTC, cmelchior commented on source/reference/realm-query-language.txt
> +   "progressMinutes > 1 AND name == %@", "Ali"
Yes, that looks like the iOS syntax. `$1` is used in RQL.

2021-12-03 14:42 UTC, cmelchior commented on source/reference/realm-query-language.txt
> +Realm Query Language
I might be missing it, but I don't see any examples using `@LinkingObjects`?

2021-12-03 14:42 UTC, cmelchior commented on source/reference/realm-query-language.txt
> +   You can compare any numeric type with any other numeric type.
Maybe specifically spell out if this is true for decimal, float and Decimal128 as well?

2021-12-03 14:42 UTC, cmelchior commented on source/reference/realm-query-language.txt
> +   * - | ``and``
Also add the upper case `AND` here and elsewhere since that is what we are using in all our examples?

2021-12-03 14:42 UTC, cmelchior commented on source/reference/realm-query-language.txt
> +     - Evaluates to the average value of a given numerical property across a collection.
We need to describe semantics if there is `null` values in here. I do not recall if it ignore `null` values in the count or include them.

2021-12-03 14:42 UTC, cmelchior commented on source/reference/realm-query-language.txt
> +   * - ``SORT``
We can also add multiple SORT fields, which will be used in case of same values, e.g `SORT (name, age)` will first sort by name and for equal names use age.

2021-12-03 14:42 UTC, cmelchior commented on source/reference/realm-query-language.txt
> +   * - ``DISTINCT``
Same for DISTINCT, it allow multiple values.

2021-12-16 23:30 UTC, dacharyc commented on source/reference/realm-query-language.txt
> +      "assignee IN {'Ali', 'Jamie'}"
Nope, I think you're right, @nirinchev - when I converted these to JS-tested code examples, I realized this does not work in JS, so I've removed it from the examples.

2021-12-16 23:49 UTC, dacharyc commented on source/reference/realm-query-language.txt
> +- An operator and up to two argument expression(s).
Added some language to clarify - let me know if this resolves the confusion, @nirinchev :

> An operator and up to two argument expression(s). For example, in the 
  expression ``A + B``, the entirety of ``A + B`` is an expression, but ``A``
  and ``B`` are also argument expressions to the operator ``+``.

2021-12-16 23:52 UTC, dacharyc commented on source/reference/realm-query-language.txt
> +You can iterate through a collection property with another query using the
Added some more details to clarify (these come from academy.realm.io - can't take credit for it!)

> A subquery takes a collection, then iterates through each object (as 
variableName) checking the predicate against that object. Subqueries work well 
when you have a collection (A) objects, and each object has a collection (B) 
other objects. Use a subquery if you're trying to filter A based on 2 or more 
varying attributes of B.

And then in the example itself:
> SUBQUERY(...) returns an array. We need to check if its count > 0 to return the true or false value predicate expects.

2021-12-17 13:59 UTC, cbush commented on source/reference/realm-query-language.txt
> +A **set operator** uses specific rules to determine whether
I was thinking of "set" in the mathematical sense, set_intersection etc.

2021-12-17 14:00 UTC, cbush commented on source/reference/realm-query-language.txt
> +     - Evaluates to ``true`` if the left-hand string expression is found anywhere in the right-hand string expression.
Yes I think this is backwards.

2021-12-17 14:04 UTC, cbush commented on source/reference/realm-query-language.txt
> +- An operator and up to two argument expression(s).
Not to throw a new term out there but we could also say "and two operands"

2021-12-17 14:17 UTC, cbush commented on source/reference/realm-query-language.txt
> +Filters consist of **expressions** in a predicate. An expression consists of
`42` or `"myFieldName"` may not be a valid _predicate_ on their own but they are still expressions in the general sense (expression of a value)

2021-12-17 14:17 UTC, cbush commented on source/reference/realm-query-language.txt
> +A **set operator** uses specific rules to determine whether
We could say "collection operators" instead.

2022-01-03 12:21 UTC, nirinchev commented on source/reference/realm-query-language.txt
> +You can iterate through a collection property with another query using the
Looks better, but I think we should be explicit about the operators one can use in combination with a subquery. I guess that's all the aggregation operators as those will convert the collection to a single value that can then be compared to something else to return a boolean. Still, since I'm kind of uncertain about it, my guess is that users will be even more so.

2022-01-04 21:02 UTC, cbush commented on source/reference/realm-query-language.txt
> +Realm Query Language
We have many examples using collections and nested object. I'm open to it if so, but do we need an explicit `@LinkingObjects` example?

2022-01-05 13:16 UTC, dacharyc commented on source/reference/realm-query-language.txt
> +<rql-aggregate-operator>` on this result. This allows you to count how
@cbush Looks like the snooty build log CI is failing because this ref is missing an `s` at the end - the anchor is `rql-aggregate-operators` in line 310.
```suggestion
<rql-aggregate-operators>` on this result. This allows you to count how
```

2022-01-05 15:23 UTC, cbush commented
@nirinchev, could you clarify point 3, "information on backlink properties"? Added your point 4. I don't think we want to cover your point 2 unless people frequently ask for it. Looking into point 1.

2022-01-05 15:30 UTC, cbush commented
@nirinchev never mind, I just discovered `@links` https://github.com/realm/realm-core/blob/master/test/test_parser.cpp#L256

2022-01-05 15:34 UTC, cbush commented
Dictionary-specific operators will be done in this ticket: https://jira.mongodb.org/browse/DOCSP-20137

2022-01-05 15:38 UTC, merged