Bundledsyncrealm
mongodb/docs-realm pull request #1509
Opened 2021-12-01 19:25 UTC by MongoCaleb

## Pull Request Info

This change adds feedback from Nikola and Nate about other concerns with bundling a synced realm.
### Jira

- https://jira.mongodb.org/browse/DOCSP-19909

### Staged Changes (Requires MongoDB Corp SSO)

- [[PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/bundledsyncrealm/sdk/dotnet/advanced-guides/bundle-a-realm/)

2021-12-01 19:28 UTC, nathan-contino-mongo commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +{+realm+} from the application {+backend+}. This negates the
```suggestion
{+realm+} from the application backend. This negates the
```
The "backend" source constant expands to "MongoDB Realm", so we actually just want the word "backend" here.

2021-12-01 19:29 UTC, nathan-contino-mongo commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +   **client maximum offline time** number of days.
```suggestion
- Avoid using a client maximum offline time in applications that
  bundle a synchronized {+realm+}.

- If your application does use a client maximum offline time, ensure
  that your application download always includes a recently synced
  {+realm+} file. Generate a new file each application version,
  and ensure that no version ever stays current for more than
  **client maximum offline time** number of days.
```

Looks like an extra space snuck in here, causing snooty to interpret these bullet points as definitions in a glossary.

2021-12-01 19:31 UTC, nathan-contino-mongo commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +Synced Realm Considerations
Personally I think this buries the lede a little bit -- most readers will likely never bother reading the "Synced Realm Considerations" section because it sounds like dry reference information. I feel like this issue is worthy of a warning right up front in the documentation, but use your best judgement.

2021-12-01 23:21 UTC, nirinchev requested changes

2021-12-01 23:23 UTC, nirinchev commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +Synced Realm Considerations
I think it's fine to leave it toward the end as we should optimize for the majority of our users, who are not sync users. Might want to link to it from the `Synced Realm` tab of the `Copy a Realm File` section.

2021-12-02 00:19 UTC, MongoCaleb commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
> +Synced Realm Considerations
@nirinchev @nathan-contino-mongo LMK what you think of the change -- I tried to meet both considerations.

2021-12-02 00:23 UTC, MongoCaleb commented on examples/dotnet/Examples/BundleARealmExamples.cs
> +            // var syncConfig = new SyncConfiguration("myPartition", user);
Not sure about this; it doesn't make sense to connect to a realm file that you haven't yet extracted and copied.

2021-12-02 11:12 UTC, nirinchev commented on examples/dotnet/Examples/BundleARealmExamples.cs
> +            // var syncConfig = new SyncConfiguration("myPartition", user);
You're not connecting to the Realm before you call `Realm.GetInstance`. The code snippet as it is doesn't apply for the synced Realm case because the extraction part shows how to extract the file to a location that doesn't match the location of the synced Realm. The final snippet should be something like:

```csharp
// if using a local Realm
var config = RealmConfiguration.DefaultConfiguration;

// ...or...
// If the realm is synced realm:
var app = App.Create(appConfig);
var user = await app.LogInAsync(Credentials.Anonymous());
var config = new SyncConfiguration("myPartition", user);

// Extract and copy the realm
if (!File.Exists(config.DatabasePath))
{
    using var bundledDbStream = Assembly.GetExecutingAssembly()
        .GetManifestResourceStream("bundled.realm");
    using var databaseFile = File.Create(config.DatabasePath);
    bundledDbStream.CopyTo(databaseFile);
}
 
// Then, open the realm
var realm = Realm.GetInstance(config);
```

Note how in both cases, we're just creating a config object, then extracting the file to whatever location the config points to, and then calling `Realm.GetInstance` with whatever config we had. Note that we don't need to call `GetInstanceAsync` in the synchronized realm case because there's some data already in the file and we don't need to wait for the server bootstrap before we can let the user interact with the app.

2021-12-02 17:48 UTC, nirinchev reviewed
Just noticed the Unity snippet in "Using the Copied Realm File" needs updating to also describe how to use it with synced realms. On my phone, but can prepare something later today if you need help with it.

2021-12-02 18:08 UTC, nathan-contino-mongo commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
>        you can do this during start-up of the app; note that it will only run when no
With two notes here, should we consider a "note that: (bullet points)" construction instead of inline thoughts?

2021-12-02 19:34 UTC, MongoCaleb commented on source/sdk/dotnet/advanced-guides/bundle-a-realm.txt
>        you can do this during start-up of the app; note that it will only run when no
Good idea

2021-12-16 17:58 UTC, nathan-contino-mongo approved these changes
LGTM!

2021-12-16 18:25 UTC, merged