(DOCSP-19356): Update Google Auth for Web SDK
mongodb/docs-realm pull request #1523
Opened 2021-12-13 19:09 UTC by mongodben

## Pull Request Info

* update examples for Google Auth for Web SDK
* moved the set up `Set Up a Project in the Google API Console` section b/c it's the first action you should do when setting up google auth for project

### Jira

- https://jira.mongodb.org/browse/DOCSP-19356

### Staged Changes (Requires MongoDB Corp SSO)

- [Authentication, Google Authentication section (Web SDK)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19356/web/authenticate/#google-authentication)
- [Google Authentication](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-19356/authentication/google/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-12-13 20:13 UTC, terakilobyte requested changes
A few questions before I can lgtm.

2021-12-13 20:13 UTC, terakilobyte commented on source/web/authenticate.txt
> +      .. example:: Basic Google One Tap Flow
question: should the html content be common between the two tabs?

2021-12-13 20:22 UTC, terakilobyte commented on source/authentication/google.txt
> +
I see what it's doing now. It sets the tabs for the rest of the page since they also have the same id

2021-12-13 20:24 UTC, mongodben commented on source/web/authenticate.txt
> +      .. example:: Basic Google One Tap Flow
not necessarily. if this were a typescript project, it'd be inherently npm based, meaning the structure and html would be different here. 

removing all the typescript documentation from the JS SDK docs has been discussed b/c it doesn't provide much value to users and can lead to potentially funky situations like this (esp for web SDK).

2021-12-13 20:31 UTC, mongodben commented on source/web/authenticate.txt
> +      .. example:: Basic Web Login Flow
ditto previous response abt removing typescript from JS SDK examples. 

and regarding jarring experience abt tab switching i see what you mean, but i think that's a docs platform issue. 

i think lowest hanging solution here is just to remove all the TS examples from this page. if we proceed w that, i'd advocate doing it in a separate ticket and PR since it's a pretty separate unit of work

2021-12-13 20:36 UTC, terakilobyte approved these changes
LGTM. Justification makes sense and I hope the TS content is extracted as our users may suffer.

2021-12-13 20:39 UTC, mongodben commented
thx nathan! will run the removal of TS stuff by other members of Realm Docs team before proceeding.

2021-12-13 20:53 UTC, mongodben commented
going to hold off on merge here til we complete https://jira.mongodb.org/browse/DOCSP-20055

this is the ticket to remove the unnecessary TS. will be easier to get DOCSP-20055 done first and rebase this PR on top of those changes.

2021-12-14 15:49 UTC, mongodben commented
note that the 2 failing tests above seem to have been snooty platform bugs.

2021-12-14 15:49 UTC, merged