(DOCSP-20326): January 14 2022 Release Notes
mongodb/docs-realm pull request #1558
Opened 2022-01-14 04:58 UTC by nathan-contino-mongo

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-20326

### Staged Changes (Requires MongoDB Corp SSO)

- [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-20326/release-notes/backend/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2022-01-14 23:20 UTC, MongoCaleb approved these changes
lgtm

2022-01-18 21:53 UTC, sumedhamehta requested changes

2022-01-18 21:53 UTC, sumedhamehta commented on source/release-notes/changelogs/backend/changelog-backend-2022.rst
> +- Refreshed the Sync Schema UI.
```suggestion
```

Let's remove this it will not be ready in time

2022-01-18 23:56 UTC, nathan-contino-mongo commented
@sumedhamehta is this out?

2022-01-20 07:04 UTC, nathan-contino-mongo commented on source/release-notes/changelogs/backend/changelog-backend-2022.rst
> +14 January 2022 Release
```suggestion
19 January 2022 Release
```

2022-01-20 07:04 UTC, nathan-contino-mongo commented on source/release-notes/changelogs/backend/changelog-backend-2022.rst
> +.. _backend_20220114:
```suggestion
.. _backend_20220119:
```

2022-01-24 16:32 UTC, merged