docsp-19410 (not ready for review/do not merge)
mongodb/docs-realm pull request #1578
Opened 2022-01-21 15:34 UTC by mongomoe

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-NNNNN

### Staged Changes (Requires MongoDB Corp SSO)

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2022-01-26 19:08 UTC, MongoCaleb reviewed
General comment (made specifically in 2 places below): update all text referring to methods, properties, etc. to point to the appropriate pages in the SDK docs.

2022-01-26 19:08 UTC, MongoCaleb commented on source/sdk/dotnet/examples/flexible-sync.txt
> +You can use this snapshot to add queries to this list of subscriptions and
I don't think we previously define a snapshot; is that even the correct term? It implies a static collection (to me, at least)

2022-01-26 19:08 UTC, MongoCaleb commented on source/sdk/dotnet/examples/flexible-sync.txt
> +When using a flexible synced realm, you can access a ``SubscriptionSet``, a collection of subscriptions, through the
"When using flexible sync..."

2022-01-26 19:08 UTC, MongoCaleb commented on source/sdk/dotnet/examples/flexible-sync.txt
> +Writing an update to the subscription set locally is only one part
"After updating the subscription locally, Realm Sync resolves data changes with the updates, which may result in Realm adding or removing data from the synced realm"

2022-01-27 13:51 UTC, nirinchev requested changes
Apart from the comments, there is some information missing:
1. Examples iterating the subscriptions collection.
2. Examples of using `realm.Subscriptions.Find` to look up a subscription by query or name. This can be used in combination with update - e.g.:
    ```csharp
    if (realm.Subscriptions.Find("teams") == null)
    {
        // We don't have the teams data yet, subscribe and wait for the server to send it
        realm.Subscriptions.Update(() =>
        {
             realm.Subscriptions.Add(realm.All<Team>(), new() { Name = "teams" });
        });
        await realm.Subscriptions.WaitForSynchronizationAsync();
    }

    // At this point we have teams locally - either because the server had previously
    // sent the data, or because we just subscribed and waited for it.
    ```
3. Examples of error handling - rejected subscription are going to be fairly common early on, so we should show users how to handle the exceptions from `WaitForSynchronizationAsync` or access the subscription state and error properties.
4. Explanation of the different states the subscription set can be in.

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/open-a-realm.txt
> +   :language: swift
```suggestion
   :language: csharp
```

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +To use Flexible Sync in a .NET client:
Maybe this?

```suggestion
To use Flexible Sync in a .NET application:
```

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +You can use this snapshot to add queries to this list of subscriptions and
Agreed - while the collection is indeed static in some sense, it's also dynamic - i.e. if the subscriptions changed on a bg thread, when you access the property again, you'll get the updated collection.

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +Add a Query to the List Of Subscriptions
We prefer to use `Set` instead of `List` terminology here to convey the fact that subscriptions will be deduplicated on insertion. I.e. if you add the same query multiple times, only one element will end up in the collection.

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +Within a Flexible Sync ``transaction`` you can add queries to your list of
What does a flexible sync transaction mean here? I don't think we should bring in additional terminology that does not match directly the API. How about we call out that all mutations on the collection must happen within an update block?

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +subscription options object. The subscription options include:
We should call out that providing subscription options is optional and subscriptions will be unnamed if you leave it as default.

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +You can add a single query, or batch multiple queries within a ``SubscriptionSet.Update``
We should clearly state that batching queries is by far the preferred way of doing as every update is quite expensive on the server.

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +If ``UpdateExisting`` is true, adding a subscription with an
We should call out the set semantics of the subscriptions collection - namely, that adding multiple unnamed subscriptions with the same query will de-duplicate them, as well as adding multiple identical named subscriptions, regardless of whether `UpdateExisting` is true or false, will be a no-op.

2022-01-27 13:51 UTC, nirinchev commented on examples/dotnet/Examples/FlexibleSyncExamples.cs
> +                var longRunningTasksSubscription = subscriptions.Add(longRunningTasksQuery, longRunningTasksSubscriptionOptions);
This can be simplified with the C# 10 syntax to:

```suggestion
               subscriptions.Add(longRunningTasksQuery, new() { Name = "longRunningTasks" });
```

There's no need to include `subscription` in the name, as it's fairly obvious that everything in the subscriptions collection is a subscription. There's also no need to assign the return value of `.Add()` if you're not going to use it.

2022-01-27 13:51 UTC, nirinchev commented on examples/dotnet/Examples/FlexibleSyncExamples.cs
> +                var teamsSubscription = subscriptions.Add(realm.All<Team>(), teamsSubscriptionOptions);
```suggestion
                var teamsSubscriptionOptions = new SubscriptionOptions() { Name = "teamsSubscription", UpdateExisting = false };
                subscriptions.Add(realm.All<Team>(), new() { Name = "teams", UpdateExisting = false }); 
```

2022-01-27 13:51 UTC, nirinchev commented on examples/dotnet/Examples/FlexibleSyncExamples.cs
> +                var bensTasks = subscriptions.Add(realm.All<MyTask>().Where(t => t.Owner == "Ben"));
```suggestion
               subscriptions.Add(realm.All<MyTask>().Where(t => t.Owner == "Ben"));
```

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +Wait for Subscription Changes to Sync
Can we group these sections logically - I'd prefer to have Add, Update, Remove one after another and then Wait to wrap them up.

2022-01-27 13:51 UTC, nirinchev commented on examples/dotnet/Examples/FlexibleSyncExamples.cs
> +            // Wait for the server to acknowledge the subscription and return all objects
```suggestion
            // Wait for the server to acknowledge the subscription change and return all objects
```

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +Use the ``SubscriptionSet.WaitForSynchronizationAsync()`` method to wait for the server to
This section should also explain that an exception will be thrown if the server rejects the change.

2022-01-27 13:51 UTC, nirinchev commented on examples/dotnet/Examples/FlexibleSyncExamples.cs
> +                var longRunningTasksSubscription = subscriptions.Add(updatedLongRunningTasksQuery, longRunningTasksSubscriptionOptions);
```suggestion
                var updatedLongRunningTasksQuery = realm.All<MyTask>().Where(t => t.Status == "completed" && t.ProgressMinutes > 130);
                subscriptions.Add(updatedLongRunningTasksQuery, new() { Name = "longRunningTasks" });
```

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +You can update a named subscription with a new query. To update a subscriptions
We should probably explicitly state that updating unnamed subscriptions is not possible and the only way to do it is to remove the previous one and add the new one.

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +Subscribe to Queryable Fields
The wording of this sections is odd - you don't subscribe to fields, you subscribe to queries.

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +- Remove a single subscription with the given query
You can also remove a specific subscription if you have a reference to it - either by storing the returned value from `.Add` or by looking it up in the collection.

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +the subscriptions set. Pass the query to the ``remove()`` method on the mutable
```suggestion
the subscriptions set. Pass the query to the ``Remove()`` method on the mutable
```

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +the subscriptions set. Pass the query to the ``remove()`` method on the mutable
There's no mutable subscription instance in .NET.

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +``removeByName()`` method on the mutable subscriptions instance.
Need to update the method name and again, no mutable subs in .NET.

2022-01-27 13:51 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +Remove All Subscriptions of an Object Type
We should note that `RemoveAll` have an optional `removeNamed` argument which controls whether named subscriptions will be removed or only the anonymous ones.

2022-01-31 13:58 UTC, mongomoe commented on examples/dotnet/Examples/FlexibleSyncExamples.cs
> +            subscriptions.Update(() =>
Makes sense, I've replaced the uses of `subscriptions.{someAPI}()` with `realm.Subscriptions.{someAPI}()` everywhere

2022-01-31 15:10 UTC, mongomoe commented on examples/dotnet/Examples/FlexibleSyncExamples.cs
> +    class MyTask : RealmObject
👍

2022-01-31 15:15 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +.. note:: Realm .NET SDK Version Requirement
Yeah the 3 warnings is a bit ugly for me as well, but the 3 separate warnings are used in different places, so changing 1 would have ramifications on multiple pages.

2022-01-31 15:21 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +Subscribe to Queryable Fields
On the backend, you select up to 10 queryable fields (which is what the following sentences indicate: `"When configuring Flexible Sync on the backend, you specify which fields your client application can query. In the client application, use the subscriptions API to manage a set of subscriptions to specific queries on queryable fields."`)  

I've taken this format from the other SDKs as well: 
- https://docs.mongodb.com/realm/sdk/swift/examples/flexible-sync/#subscribe-to-queryable-fields
- https://docs.mongodb.com/realm/sdk/node/examples/flexible-sync/#subscribe-to-queryable-fields
- https://docs.mongodb.com/realm/sdk/android/examples/flexible-sync/#subscribe-to-queryable-fields 

which all use "Subscribe to Queryable Fields". Let me know if you still want me to change this (if that's the case we should also consider changing those other pages)

2022-01-31 19:27 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +Subscribe to Queryable Fields
Yeah, I think we should change the title here because it's ambiguous - it implies an API where you subscribe to a field rather than subscribe to a query on that field. The last sentence of that quote is actually fairly precise - you "manage a set of subscriptions to [...] queries".

2022-01-31 20:00 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +A Realm subscription in .NET has:
No, you don't necessarily need to provide the following fields, this is just a description of the Subscription Class. Although you can set the name & query field through the subscriptions.add method. I'd be happy to remove this though if you want, I'm not in love w/ this bit of the page.

2022-01-31 20:00 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +- A created and updated date
Exactly, when the subscription was created and updated

2022-01-31 20:03 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +A Realm subscription in .NET has:
Update: I just removed this bit altogether. Originally, I had it to parity the swift version, but it looks like Dachary's removed it from hers as well, so it makes sense here to not have it as well.

2022-01-31 20:04 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +- A created and updated date
Resolving, see: https://github.com/mongodb/docs-realm/pull/1578/files#r796021477

2022-01-31 20:16 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +object type.
In the "Add a Query to the List Of Subscriptions" subsection below, there's an example of subscription to 2 different object types (task & team) & several queries on a single object type.

2022-01-31 20:17 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +.. literalinclude:: /examples/generated/dotnet-flexible-sync/FlexibleSyncExamples.codeblock.get-subscriptions.cs
Can you try hard refreshing it? It should be there. Cmd+shift+r

<img width="767" alt="Screen Shot 2022-01-31 at 3 13 36 PM" src="https://user-images.githubusercontent.com/52428905/151866331-f6952c00-4da8-4878-829e-cc456c98f65d.png">

2022-01-31 20:18 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +You can use this snapshot to add queries to this list of subscriptions and
Sorry, that's leftover from when I copied the JS content. I've changed it now to "You can use the subscription set to  ..."

2022-01-31 20:46 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +Within a Flexible Sync ``transaction`` you can add queries to your list of
I've removed the word 'transaction' now. The new sentence reads: `"You must perform all mutations on the subscriptions set within an update block.To create an update block, call the SubscriptionSet.Update() method"`

2022-01-31 20:51 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +You can add a single query, or batch multiple queries within a ``SubscriptionSet.Update``
Sure, how would you recommend saying that? Maybe: "We recommend batching queries together to decrease server cost"?

2022-01-31 21:07 UTC, nirinchev commented on source/sdk/dotnet/examples/flexible-sync.txt
> +You can add a single query, or batch multiple queries within a ``SubscriptionSet.Update``
We can be even more forceful here. "Performing query updates is an expensive operation on the server, so it is strongly advised that you design your app in a way that minimizes updates - for example by creating all subscriptions in a single `Update` block the first time the user launches the app and batching any follow-up changes to the subscription set."

2022-01-31 21:17 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +Writing an update to the subscription set locally is only one part
I'm going to roughly keep it as is, but change "writing an update to the subscription set" to "mutating the subscription set". The version I had is taken from the swift/node versions + is a bit more accurate than your suggestion (for instance, in the fragment: 'Realm Sync resolves data changes' , there's actually no changes to the data in the realm, but rather what data is being synchronized due to the mutated subscription).

2022-01-31 21:47 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +You can update a named subscription with a new query. To update a subscriptions
Added a note explicitly stating that 👍

2022-01-31 23:55 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +Subscribe to Queryable Fields
How about as a title: "Manage Your Subscriptions"? Which is broad enough that it encompasses all of the examples

2022-02-01 00:03 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +If ``UpdateExisting`` is true, adding a subscription with an
Added the following note, let me know if the wording is okay for you:

```

.. note:: {+service-short+} Automatically Removes Duplicate Subscriptions 

   {+service-short+} will automatically remove duplicate unnamed subscriptions
   with the same query. Also, adding multiple identical named subscriptions,
   regardless of the value of ``UpdateExisting``, is a :wikipedia:`no-op <NOP_(code)>`.
   
 ```

2022-02-01 00:07 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +You can add a single query, or batch multiple queries within a ``SubscriptionSet.Update``
Thanks! I've took that suggestion, but just altered the wording slightly to be a bit more readable:

"You can add a single query, or batch multiple queries within a ``SubscriptionSet.Update``
block. Performing query updates is an expensive operation on the server. We
strongly advise designing your application to minimize updates. You can do this
by creating all subscriptions in a single update block the first time the user
launches the app and batching any follow-up changes to the subscription set."

2022-02-01 00:14 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +Use the ``SubscriptionSet.WaitForSynchronizationAsync()`` method to wait for the server to
Added the sentence: "If the server rejects the change, the ``SubscriptionSetState`` will be an error state, and
an exception will be thrown."

2022-02-01 00:15 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +on the mutable subscriptions instance within the transaction
Sorry for all these wrong name + mutable subs, a copy & paste error from when I ported over the JS SDK content. It should be fixed now, everywhere.

2022-02-01 00:18 UTC, mongomoe commented on source/sdk/dotnet/examples/flexible-sync.txt
> +subscription options object. The subscription options include:
Changed the sentence to "The ``Add()`` method takes a ``query``, and an optional subscription options object" 

The sentence "If you do not give your subscription a name, the name is set to null." is already in the beginning of the page (under the section currently titled "Subscribe to Queryable Fields")

2022-02-04 11:49 UTC, nirinchev approved these changes
I think we can merge this (after updating the `Subscribe to Queryable Fields` section wording) and file tickets for the follow-up work, some of which probably needs to be done across all SDK pages. Off the top of my head, here is what's missing:
1. Explanation of the fields in the `Subscription` class. Those do have API docs, but it would still be a good idea to highlight the key ones.
2. Looking up a subscription by name/query.
3. Removing a subscription directly (i.e. after looking it up).
4. Explanation of the subscription set states.
5. Replace the obsoleted `SyncConfiguration` with `PartitionSyncConfiguration` across the docs.

Thanks for moving this forward and I'm sorry I've been a PITA during the review. We'll try to figure out a process in engineering where a more thorough eng review will be done for major new features for all SDKs to avoid ending up in a situation where copy-pasting some already approved content results in tens of comments and a week of back-and-forth.

2022-02-07 16:42 UTC, MongoCaleb approved these changes
LGMT % my comment about using a term like no-op.

2022-02-07 16:42 UTC, MongoCaleb commented on source/sdk/dotnet/examples/flexible-sync.txt
> +If ``UpdateExisting`` is true, adding a subscription with an
I'd avoid using any term that requires a link to Wikipedia -- suggests that many/most of our users won't understand. 
Isn't this really saying "If you add a named subscription with the same name, {+service-short+} will ignore it"?

2022-02-07 16:57 UTC, merged