(DOCSP-19911): Realm Hooks docs
mongodb/docs-realm pull request #1638
Opened 2022-02-11 17:47 UTC by mongomoe

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-19911

### Staged Changes (Requires MongoDB Corp SSO)

- [Use Realm Hooks](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-19911-realm-hooks-docs/sdk/react-native/integrations/realm-hooks/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2022-03-18 15:41 UTC, takameyer requested changes
Before I go into the weekend, I want to submit my review so far.  I guess generally, I would prefer that we provide the code samples as valid React components that can easily be copied and pasted.  Also we should make sure it conforms to TypeScript.

2022-03-18 15:41 UTC, takameyer commented on source/examples/generated/expo/App.codeblock.example-usequery-hook-usage.tsx
> +const tasks = useQuery("Task");
I think it would be good to display code examples as functional components.  For example:
```
const TestComponent = ({ queryType }: { queryType: QueryType }) => {
  const tasks = useQuery("Task");
  const sortedTasks = useMemo(() => tasks.sorted("createdAt"), [tasks]);

  const renderItem = useCallback(({ item }) => <Text>{item.name}</Text>, []);

  const keyExtractor = useCallback((item) => item._id, []);

  return <FlatList testID={"list"} data={result} keyExtractor={keyExtractor} renderItem={renderItem} />;
};
}
```

Also we should probably show that you can use `React.Memo` in order to avoid unnecessary re-renders:
```
const ItemComponent = React.memo(({ item }) => {
...
}
```

2022-03-18 15:41 UTC, takameyer commented on source/examples/generated/expo/App.codeblock.wrap-app-within-realm-provider.tsx
> +    <RealmProvider>
I added a `fallback` prop that we should highlight.  At the moment it looks something like:
```
<RealmProvider fallback={<LoadingSpinner/>}/>
```

2022-03-18 15:41 UTC, takameyer commented on source/examples/generated/expo/App.codeblock.example-useobject-hook-usage.tsx
> +const myTask = useObject("Task", id);
This is a pretty sparse example.  I would show this as a small React component.
Also both `useQuery` and `useObject` are good opportunities to show TypeScript support.  With these current examples, users would get a TypeScript compile error when they access any `Task` paramenters.  This can be avoided using the following syntax:
```
//This infers the types from the Task class
const myTask = useObject(Task, id); 

//Without a class, a Task interface/type can be provided
const myTask = useObject<Task>("Task", id); 
```

2022-03-18 15:41 UTC, takameyer commented on source/examples/generated/expo/App.codeblock.example-userealm-hook-usage.tsx
> +const handleAddTask = (description: string) => {
I would again show this in a React component (Perhaps a simple button).
Also handleAddTask should be wrapped in `useCallback`.  Otherwise the function will be created again on every re-render.
```
const handleAddTask = useCallback(() => {
...
}, [realm])
```

2022-03-18 15:41 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +hook and then the tasks are set as a prop of a ``TaskList`` component.
We should highlight that this can be used with `FlatList` and `React.Memo` (see my comments in the codeblocks)
Also how `filtered` and `sorted` can also be applied, and should be wrapped in `useMemo`

2022-03-18 15:41 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +- A ``RealmProvider`` passes data and hooks to the component it wraps around, and any children of that component.
```suggestion
- A ``RealmProvider`` provides access to the configured Realm using hooks, which can be used to display and modify data.
```

2022-03-18 15:41 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +- A ``RealmProvider`` passes data and hooks to the component it wraps around, and any children of that component.
Also the hooks automatically subscribe to updates to the data and will re-render components on any changes.

2022-03-18 15:41 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +``useObject()`` hook, and it's description is logged to the console.
```suggestion
``useObject()`` hook, and its description is logged to the console.
```

2022-03-18 15:41 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +- A :reactjs:`Context Provider <docs/context.html#contextprovider>` component that wraps around a component, and provides any of it's child components with access to the hooks.
```suggestion
- A :reactjs:`Context Provider <docs/context.html#contextprovider>` component that wraps around a component, and provides any of its child components with access to the hooks.
```

2022-03-18 15:41 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +- A :reactjs:`Context Provider <docs/context.html#contextprovider>` component that wraps around a component, and provides any of it's child components with access to the hooks.
Sorry for being a bit of a grammar nut, but `it's` is only used as a contraction `it is` and the possessive form is `its`.  I see this in many places of the document, so please fix that 🙂

2022-03-21 08:00 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +- A schema
A static schema property that defines the ``Task`` Realm model.

2022-03-21 08:05 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +``createRealmContext()`` so you can use it's ``Context`` in other files.
```suggestion
Finally, create a ``Realm.Configuration`` object and set its ``schema`` property
to the any classes you have created. Pass the configuration object to the
``createRealmContext()`` method. Export the return value of
``createRealmContext()`` so you can use the ``Context`` object in other files.
```

2022-03-21 08:14 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +to the {+service-short+} and the Realm Hooks.
```suggestion
Wrap the component needing access to {+service-short+}, typically the top layer of your application, with the ``RealmProvider`` component included in the Context object which was returned from `createRealmContext`.  The ``RealmProvider`` provides any child components access
to the configured {+service-short+} through the Hooks included in the Context object.
```

2022-03-21 08:14 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +the Task. :mdn:`Destructure
```suggestion
the Task. You can :mdn:`Destructure
```

2022-03-21 08:18 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +the ``App`` component which renders the application.
```suggestion
Wrap the ``RealmProvider`` around the component that you want
to give access to the configured Realm. In the example below, we give the entire
app access to the Realm by wrapping the ``RealmProvider`` around
the ``App`` component which renders the application.
```

Just want to clear this language up.  We are providing access to a configured Realm through the Hooks.  Also removed "Finally" since there wasn't a "First".  Also just ``RealmProvider`` instead of ``RealmsProvider`` component.  It being a Provider already denotes that it is a component.

2022-03-21 08:20 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +:js-sdk:`sync configuration <Realm.App.Sync.html#~SyncConfiguration>`:
This example appears to be broken.  The code block is not visible in the docs page.

2022-03-21 08:21 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +Use Realm Hooks In Child Components
```suggestion
Using Realm Hooks
```
I think we can drop "In Child Components".  By now it should be clear how this is being setup.

2022-03-21 08:23 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +``useObject()``, and ``useQuery()`` hooks.
```suggestion
Once you have wrapped your application with the ``RealmProvider``, all child components will have access to Realm with the ``useRealm()``,
``useObject()``, and ``useQuery()`` hooks.
```

2022-03-21 08:24 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +``useObject()``, and ``useQuery()`` hooks.
I think we should just assume the user is going to wrap their entire application with this.  It is theoretically possible to wrap some arbitrary component with the ``RealmProvider``, but would not be a common use case.  This will also make this document read easier.

2022-03-21 08:32 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +the TaskContext object to get it's Realm Hooks.
This language seems to be copied from the RealmProvider usage above.  Let's change it up a bit:
```suggestion
As with the above ``RealmProvider`` (link to the usage above), the Hooks can be destructured directly from the `Context` object returned from `createRealmContext`.  
```

2022-03-21 08:34 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +The ``useRealm()`` hook returns the opened {+realm+} instance. In the following
```suggestion
The ``useRealm()`` Hook returns the opened {+realm+} instance. In the following
```
Lets keep `Hook` capitalised

2022-03-21 08:37 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +
This would be a good spot to also showcase the `fallback` property (probably just add to the above paragraph).  This is shown until the Realm is opened, which can take some time if using sync for a large Realm.

```
return (
  <RealmProvider fallback={<LoadingSpinner/>}>
    <App/>
  </RealmProvider>
);
```

2022-03-21 08:38 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +
This also lets the reader know that Realm is not opened until the provider is rendered.

2022-03-21 08:40 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +``createdAt`` properties.
```suggestion
The :js-sdk:`Realm.create() <Realm.html#create>` call invokes the ``Task.generate()`` method defined in the ``Task`` class.  This method is used to instantiate
a JavaScript object with default values for the ``_id``, ``isComplete``, and
``createdAt`` properties.
```

2022-03-21 08:43 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +``createdAt`` properties.
The above code example should also be using the `useCallback` Hook (https://reactjs.org/docs/hooks-reference.html#usecallback)
We should recommend using this, so that the handleAddTask method is not reinstantiated after every re-rerender.  If the developer were to provide `handAddTask` to a child component through props, then it would trigger that child to unintentionally re-render .

2022-03-21 08:48 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +deleted.
```suggestion
The ``useObject()`` Hook returns a {+realm+} object for a given primary key.  It is invoked with either the class model definition (this will add types to the returned object in TypeScript) or the class name as a string and the primary key.
``useObject()`` will return null if the object doesn't exist or has been
deleted.  The Hook will automatically subscribe to updates and re-render the component using the Hook on any change to the object.
```

The example should be passing the class, and not the string.

2022-03-21 08:52 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +the class name as a string) to the ``useQuery()`` hook.
```suggestion
The ``useQuery()`` Hook, returns a collection of realm objects of a given type.  Just like `useObject` it is either invoked with either the Realm model class or the model name as a string.  It will also subscribe to updates to any of the objects in the collection and re-render the component using it on any change.
```

2022-03-21 08:53 UTC, takameyer commented on source/sdk/react-native/use-realm-hooks.txt
> +In the following example, the ``Task`` class is passed to the ``useQuery()``
Update the example to use the class.

2022-03-22 16:19 UTC, mongomoe commented on source/sdk/react-native/use-realm-hooks.txt
> +<docs/context.html>` object that opens a realm with a given :js-sdk:`Realm.Configuration
* Got it, sorry I thought createRealmContext opened the realm itself. I've updated the wording now, let me know if that works. 
* I added an example of how to dynamically update the realm config via the `<RealmProvider />` component props in the [Using The Realm Provider](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-19911-realm-hooks-docs/sdk/react-native/use-realm-hooks/#using-the-realm-provider) section.

2022-03-24 15:24 UTC, mongomoe commented on source/examples/generated/expo/App.codeblock.example-usequery-hook-usage.tsx
> +const tasks = useQuery("Task");
1. Switched to a functional component. Also, all the code examples on this page are using your Expo Template (https://github.com/expo/examples/tree/master/with-realm) with a few small tweaks. So in this example, I used your `<TaskList />` component with slight variation. We should avoid too many changes to it though, since a reader may be coming to this page from the [Expo QuickStart](https://github.com/mongodb/docs-realm/pull/1697) to learn more about the code in the template. In that case, we want the code in this page to explain the template and so it needs to not be too different from it.
2. I'm a little torn on including `React.Memo`, because (like with all documentation) we want to focus on teaching the concept of the page and any additional APIs/technologies might distract or confuse the user, even if they offer better performance. So it's always a tradeoff, and we don't want to include something that the user may not understand out of the box & would have to do additional research & leave the page. Would it be fine to not include `React.Memo` or is this a 'must-have' for you?

2022-03-24 15:53 UTC, mongomoe commented on source/sdk/react-native/use-realm-hooks.txt
> +To set up realm hooks, you can either start from scratch with a new application
Yup, switched to Realm React & capitalized now. There should be no more instances of "Realm Hooks" but there's still some of hooks (just to describe the actual hook methods, not as the name of the library)

2022-03-24 15:55 UTC, mongomoe commented on source/sdk/react-native/use-realm-hooks.txt
> +
Added a fallback just a little below this in the [Dynamically Update the Realm Configuration](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-19911-realm-hooks-docs/sdk/react-native/use-realm-react/#dynamically-update-the-realm-configuration) subsection

2022-03-24 15:58 UTC, mongomoe commented on source/sdk/react-native/use-realm-hooks.txt
> +First, create a file where you will define a Realm object type, a Realm
Update, sorry for the back & forth but I reread it and didn't love the wording. Changed it again to: 
"To begin, we recommend creating a file where you will define a Realm object type, a Realm configuration, and create a Realm Context. At the top of the file, import Realm and the createRealmContext() method." 
Let me know what you think

2022-03-24 16:04 UTC, mongomoe commented on source/sdk/react-native/use-realm-hooks.txt
> +:js-sdk:`sync configuration <Realm.App.Sync.html#~SyncConfiguration>`:
Fixed

2022-03-25 15:11 UTC, mongomoe commented on source/examples/generated/expo/App.codeblock.example-useobject-hook-usage.tsx
> +const myTask = useObject("Task", id);
Swapped this to a functional component using the recommended syntax, let me know if this works:
```
const SampleTask = ({ _id}) => {
  const myTask = useObject<Task>("Task", _id);
  return (<View><Text>Task: {myTask?.description} </Text></View>)
}
```

2022-03-25 15:12 UTC, mongomoe commented on source/examples/generated/expo/App.codeblock.example-userealm-hook-usage.tsx
> +const handleAddTask = (description: string) => {
For this one, I don't want to use a react component since this is directly from the Expo Template. I'd like to keep this doc fairly close to the template at least, so users of the template can refer to this guide to understand the template more.

2022-03-25 15:18 UTC, takameyer commented on source/examples/generated/expo/App.codeblock.example-useobject-hook-usage.tsx
> +const myTask = useObject("Task", id);
Sorry for the confusion, but the recommended syntax is actually:
```
const myTask = useObject(Task, _id);
```

2022-03-25 15:20 UTC, takameyer commented on source/examples/generated/expo/App.codeblock.example-userealm-hook-usage.tsx
> +const handleAddTask = (description: string) => {
The Expo template is using `useCallback` though.

2022-03-25 15:53 UTC, mongomoe commented on source/sdk/react-native/use-realm-hooks.txt
> +hook and then the tasks are set as a prop of a ``TaskList`` component.
* Added a mention to FlatList
* Added a tip admonition w/ links on to how to use filtered and sorted. 
* See: https://github.com/mongodb/docs-realm/pull/1638#discussion_r834434202 for question related to memoization

2022-03-28 07:19 UTC, takameyer commented on source/examples/generated/expo/App.codeblock.example-usequery-hook-usage.tsx
> +const tasks = useQuery("Task");
1. I think the example should probably be changed to use not abstract `FlatList` into `TaskList`.  If that happens I'll notify you and we can update the examples.
2. Yeah, I see the logic there.  We did put in a lot of work to get that working, but the developers will figure that out on their own if they want to do performance tweaks on their application.  Perhaps that is something better suited for a small blog post.

2022-03-28 07:22 UTC, takameyer commented on source/examples/generated/expo/App.codeblock.example-userealm-hook-usage.tsx
> +const handleAddTask = (description: string) => {
I'm confused.  This sample is different than the expo template.
https://github.com/realm/realm-js/blob/master/templates/react-native-template-realm-ts/template/app/App.tsx#L18-L36
So by that logic, it should be included.

2022-03-29 16:17 UTC, mongomoe commented on source/examples/generated/expo/App.codeblock.example-useobject-hook-usage.tsx
> +const myTask = useObject("Task", id);
Fixed 👍

2022-03-29 16:46 UTC, mongomoe commented on source/examples/generated/expo/App.codeblock.example-userealm-hook-usage.tsx
> +const handleAddTask = (description: string) => {
Whoops, not sure why my above comment was commented twice. You're right sorry I must've changed it at some point locally & then forgotten that the original template used `useCallback` (extra silly of me considering the examples below also use `useCallback`). 

I've fixed it now to use `useCallback`.

2022-03-29 16:48 UTC, mongomoe commented on source/examples/generated/expo/App.codeblock.example-usequery-hook-usage.tsx
> +const tasks = useQuery("Task");
Cool, so I'll leave it as is for now, and whenever you update it on your end, I'm happy to update these examples.

2022-03-30 06:05 UTC, takameyer requested changes
This is much better.  Just a few more questions and suggestions.  Then I am happy to get this published. 🙂

2022-03-30 06:05 UTC, takameyer commented on source/sdk/react-native/use-realm-react.txt
> +   :ref:`write to a realm <react-native-write-operations>`
Maybe expand on this tip, something like.

Read the `Realm Write Operations` to learn more about modifying Realm data.

2022-03-30 14:51 UTC, mongomoe commented on examples/node/expo-app/App.tsx
> +  if (!RealmProvider) {
Fixed, you may want to change this on the template as well: https://github.com/expo/examples/blob/master/with-realm/App.tsx#L101

2022-03-30 14:57 UTC, mongomoe commented on source/sdk/react-native/use-realm-react.txt
> +- A schema
Fixed 👍  took your suggestion.

2022-03-30 15:01 UTC, mongomoe commented on source/sdk/react-native/use-realm-react.txt
> +``createRealmContext()`` method. Export the return value of
`createRealmContext` is already described at the top of this section. See: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-19911-realm-hooks-docs/sdk/react-native/use-realm-react/#create-a-realm-context

2022-03-30 15:04 UTC, mongomoe commented on source/sdk/react-native/use-realm-react.txt
> +Context object, which was returned from ``createRealmContext``.  The
Fixed locally 👍  + all other occurrences of the word 'Context'

2022-03-30 15:05 UTC, mongomoe commented on examples/node/expo-app/App.tsx
>    if (!RealmProvider) {
Took your suggestion from: https://github.com/mongodb/docs-realm/pull/1638#discussion_r838132806

2022-03-31 07:21 UTC, takameyer commented on source/sdk/react-native/use-realm-react.txt
> +``useObject()``, and ``useQuery()`` hooks.
Ok cool, then I'm fine with it.  As long as we are consistent I am happy :)

2022-03-31 07:27 UTC, takameyer commented on examples/node/expo-app/App.tsx
> +  if (!RealmProvider) {
We have some changes in review for the templates that also show how to implement sync.  This will be updated there as well, but first in https://github.com/realm/realm-js/tree/master/templates/expo-template-ts

2022-03-31 07:36 UTC, takameyer approved these changes
I have some minor suggestions.  Also I noticed that the capitalisation of Realm is a bit inconsistent throughout the document.  Please check that.

Thanks so much for the work you've done here!  I'm happy to see this published as soon as the changes are made.

2022-03-31 07:36 UTC, takameyer commented on source/examples/generated/expo/App.codeblock.dynamically-update-realm-config.tsx
> +  if (!RealmProvider) {
```suggestion
  if (!app.currentUser) {
```
Fix here as well

2022-03-31 07:36 UTC, takameyer commented on source/sdk/react-native/use-realm-react.txt
> +property that is used to render a temporary LoadingSpinner component while
```suggestion
property that is used to render a temporary ``LoadingSpinner`` component while
```

2022-03-31 07:36 UTC, takameyer commented on source/sdk/react-native/use-realm-react.txt
> +waiting for {+sync+} to respond:
```suggestion
waiting for {+sync+} to open:
```
Technically we are waiting for realm to open, and in the case of Sync, to download and apply sync changes.

2022-03-31 15:39 UTC, merged