(DOCSP-21141): Flutter SDK supported data types
mongodb/docs-realm pull request #1766
Opened 2022-03-17 19:48 UTC by mongodben

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-21141

### Staged Changes (Requires MongoDB Corp SSO)

- [Data Types (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-21141/sdk/flutter/data-types/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2022-03-18 06:54 UTC, blagoev requested changes
suggest some changes

2022-03-18 06:54 UTC, blagoev commented on examples/dart/test/data_types_test.dart
> +  late final int id; // Flutter SDK does not yet support ObjectId
```suggestion
  late final int id;
```

2022-03-18 06:54 UTC, blagoev commented on examples/dart/test/data_types_test.dart
> +  late final int id; // Flutter SDK does not yet support ObjectId
ObjectId is just one type that can be a primary key. I think we should not steer people of using objectIds primary keys by default. In my experience developers start doing what the examples are using and always use the example code as the default. So its perfectly fine to have an int primary key here.

2022-03-18 06:54 UTC, blagoev commented on examples/dart/test/data_types_test.dart
> +  late final int id; // Flutter SDK does not yet support ObjectId
```suggestion
  late final int id;
```

2022-03-18 06:54 UTC, blagoev commented on source/examples/generated/flutter/data_types_test.codeblock.data-types-example-model.dart
> +  late final int id; // Flutter SDK does not yet support ObjectId
```suggestion
  late final int id;
```

2022-03-18 06:54 UTC, blagoev commented on source/examples/generated/flutter/data_types_test.codeblock.data-types-example-model.dart
> +  late final int id; // Flutter SDK does not yet support ObjectId
```suggestion
  late final int id;
```

2022-03-18 06:54 UTC, blagoev commented on source/sdk/flutter/data-types.txt
> +- ``null``
I see we list `null` here. I suggest we remove it. It is not a type in the database, its more like a value for nullable properties in the data model.

2022-03-18 06:54 UTC, blagoev commented on source/sdk/flutter/data-types.txt
> +- ``List<T>``, where T is any of the supported data types
```suggestion
- ``List<T>``, where T is any of the supported data types or a RealmObject type
```

2022-03-18 06:54 UTC, blagoev commented on source/sdk/flutter/data-types.txt
> +Embed RealmObjects
We don't support embedded objects right now. If you mean we support object references we should reword this to be object references
so something like 
`You can also reference a RealmObject in another RealmObject`

2022-03-18 06:54 UTC, blagoev commented on examples/dart/test/data_types_test.dart
> +  late final List<String> attributes = [];
```suggestion
  late final List<String> attributes;
```

2022-03-18 06:54 UTC, blagoev commented on examples/dart/test/data_types_test.dart
> +  final bool isElectric = false;
```suggestion
  bool isElectric = false;
```

2022-03-22 14:36 UTC, blagoev approved these changes

2022-03-22 15:41 UTC, cbush approved these changes

2022-03-22 15:41 UTC, cbush commented on source/sdk/flutter/define-realm-object-schema.txt
> +      You must include the annotation `RealmModel <{+flutter-sdk-common+}/realm_common/RealmModel-class.html>`_
Why not create a `:flutter-sdk-common:` role for these links? Using source constants in a URL is not a pattern I've seen before.

2022-03-22 18:34 UTC, mongodben commented on source/sdk/flutter/define-realm-object-schema.txt
> +      You must include the annotation `RealmModel <{+flutter-sdk-common+}/realm_common/RealmModel-class.html>`_
mainly b/c it's not a very common path to link to. as it's a different package from the main flutter package, which there is an inline role for `:flutter-sdk:`. 

i used the source constant instead following the pattern of the drivers team.

2022-03-22 18:36 UTC, mongodben commented on source/sdk/flutter/data-types.txt
> +at the moment.
not currently scheduled in the sense that i couldn't find a ticket for it. 

but functionality exists for the more mature SDKs, so i assume it's coming to the Flutter SDK as well.

2022-03-22 19:54 UTC, mongodben commented on source/sdk/flutter/define-realm-object-schema.txt
> +      You must include the annotation `RealmModel <{+flutter-sdk-common+}/realm_common/RealmModel-class.html>`_
per slack convo, updating to be just links with `__`

2022-03-22 21:01 UTC, merged