(DOCSP-22738): Flutter Quick Start with Sync
mongodb/docs-realm pull request #2061
Opened 2022-07-28 17:03 UTC by mongodben

## Pull Request Info

New page: Flutter Quick Start with Sync

### Jira

- https://jira.mongodb.org/browse/DOCSP-22738

### Staged Changes (Requires MongoDB Corp SSO)

- [Quick Start with Sync - Flutter SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-22738/sdk/flutter/quick-start-sync/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2022-08-04 17:07 UTC, MongoCaleb commented
General thoughts:
1. Looks great overall!
2. I would remove the section about the template app. As Dachary mentioned, it *seems* like this page is about the template app rather than "rolling your own". Instead, considering putting in a short note there: "For a complete end-to-end solution that shows all of this foo, check out the <link>Flutter Quick Start</link>." This leads me to #3...
3. I think the Quick Starts should not show a complete solution, because we have the complete solution in the template app and the tutorials based on it, and having it here just adds to the code maintenance / tech debt.

2022-08-29 21:12 UTC, dacharyc requested changes
I think this is a good step toward what we discussed in lobby a few weeks ago, but I still think it leans more toward tutorial than quick start. I think we can make it leaner in text and styling to make it feel more "quick start"-ey.

2022-08-29 21:12 UTC, dacharyc commented on source/sdk/flutter/quick-start.txt
> +   .. step:: Configure App Services Backend
I think this makes more sense as a prerequisite than a step 1. The rest of the quick start steps are about using Realm/Device Sync in a client, and this is a whole bunch of backend stuff that you have to do before you can use Realm/Device Sync in a client. Maybe this could be moved into a callout box as a prerequisite similar to how Moe did the Kotlin quick start?

2022-08-29 21:12 UTC, dacharyc commented on source/sdk/flutter/quick-start.txt
> +      App ID in the App Services UI.
This might be a good place to link to the App Services page on finding your App ID.

2022-08-29 21:12 UTC, dacharyc commented on source/sdk/flutter/quick-start.txt
> +.. procedure::
This is totally subjective, but seeing this as a procedure - especially with all the "See also" callout boxes - makes this section feel really chonky and like it takes up a lot of space relative to the rest of the page. I think we should probably restructure it to a section with subheadings, because I think the procedure styling makes this look, well, more procedural than like a "quick start." It "feels" more like a tutorial than just "here's what you need to do to quickly get going."

Also, I think the see also callouts here are probably overkill. We're not using them consistently in every section in the page above, and I think with the new docs styling it would feel pretty overwhelming if we did. I'd probably just use a line instead of the callout box in each section to connect users to the related docs.

2022-08-31 18:06 UTC, dacharyc approved these changes
Nice work - LGTM! 👍

2022-09-07 20:22 UTC, merged