Xamarin Tutorial Redux
mongodb/docs-realm pull request #2072
Opened 2022-08-03 16:50 UTC by MongoCaleb

## Pull Request Info

This first of the new tutorials (based on the template apps). 

### Jira
https://jira.mongodb.org/browse/DOCSP-23972

### Staged Changes (Requires MongoDB Corp SSO)

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/phase1/tutorial/dotnet/

2022-08-04 09:43 UTC, papafe requested changes
I think that the tutorial overall looks good and makes sense. 
My concerns are mostly for not using the Enum that we defined. We could kill two birds with one stone and also show how to use enums with realm too. 
Otherwise we can remove the enum completely, even though this means that we can't constrain it.

2022-08-04 14:06 UTC, dacharyc approved these changes
This looks awesome! I had a bunch of questions and nits, but I don't think any of it is necessarily blocking except for the source constant stuff that is not rendering since we got rid of source constants in this repo.

I think you mentioned having a separate PR for the backend app page but just wanted to verify since it looks like you started to edit that page in this PR.

I do wonder if we should be using Bluehawked code blocks here, and if we should have a "working" version of this code for folks who mess up the copy and paste, similar to the Final branch of the existing tutorials. Presumably we should have that internally, at the very least, to make maintenance easier so we can simply run and test the app to make sure it's still working versus having to recreate the app w/copy-and-paste code snippets every time we want to test it. Thoughts?

2022-08-04 14:06 UTC, dacharyc commented on source/tutorial/backend-app.txt
> +like authentication and :syc:. To make this easier and faster, we've
FWIW, Sync isn't a source constant here anymore - Nate did a big project to remove source constants from this repo since there were many places where we didn't use them correctly. Plus this seems to be malformed, so it's rendering as-is on the page.

2022-08-04 15:59 UTC, dacharyc commented on source/tutorial/dotnet.txt
> +      a value of 3. This makes it straight-forward to compare and filter on the
I agree with that in principle, and ordinarily I would never suggest it, but I think in this case we don't mean "simple" as in "easy" - we mean "simple" as in "non-complex." I think the nuance is tough.

Maybe "basic" would work better?

2022-08-04 17:55 UTC, MongoCaleb commented on source/tutorial/dotnet.txt
> +           - Provides shared resources, including the ``Navigation Elements`` (the
'twas a nasty hangover from the original tutorial. Removed accordingly.

2022-08-04 17:57 UTC, MongoCaleb commented on source/tutorial/dotnet.txt
> +.NET flexible sync Template App, named "xamarin.todo.flex", which illustrates
Agreed. I didn't give enough attention to the pre-existing intro text. I know better...

2022-08-04 18:02 UTC, MongoCaleb commented on source/tutorial/dotnet.txt
> +to the existing ``Item`` model and update the Flexible Sync subscription to
Was trying to avoid inline links, but also adding a "For More information..." felt disruptive. Decided on the former.

2022-08-04 18:24 UTC, MongoCaleb commented on source/tutorial/dotnet.txt
> +   .. step:: Open the Solution
it's pretty widely accepted within the .NET community...but I also see no harm in changing it.

2022-08-04 18:27 UTC, MongoCaleb commented on source/tutorial/dotnet.txt
> +            public enum Priority
Realm .NET doesn't support persisting an enum (yet) -- see Ferdinando's comments -- but I've modified the code to show how to get around that limitation.

2022-08-05 15:43 UTC, MongoCaleb commented on source/tutorial/dotnet.txt
> +            public enum Priority
After a long discussion in Slack, it turns out that the Realm support for enums complicates this scenario too much to be of use in a tutorial.

2022-08-05 17:15 UTC, papafe approved these changes
Looks good 👍

2022-08-05 18:01 UTC, dacharyc reviewed
I simultaneously think this looks great, but also I seem to have left even more comments than I did last time! I think it's pretty fabulous, though, and most of my comments are just nits to make things clearer or avoid potential misunderstandings.

2022-08-05 18:01 UTC, dacharyc commented on source/tutorial/dotnet.txt
> +If you already have the latest Realm CLI installed, you can run the
Just realized we say "If you already have the latest Realm CLI installed" but we don't give instructions or a link to the install steps for users who _don't_ already have Realm CLI installed. Presumably that should be in the prerequisites.

2022-08-05 21:44 UTC, merged