Rn tut
mongodb/docs-realm pull request #2105
Opened 2022-08-17 15:04 UTC by nlarew

## Pull Request Info

### Jira

- (DOCSP-23975) Update React Native Tutorial to Flexible Sync

### Staged Changes (Requires MongoDB Corp SSO)

- [React Native Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/phase1/tutorial/react-native/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2022-08-18 18:40 UTC, mongomoe commented on docs-release-notes.md
> +# August 12, 2022
Why are there release notes in this PR?

2022-08-18 18:42 UTC, mongomoe commented on examples/java/local/README.md
> +#### Test via Android Studio
you may have pulled from a different branch so you have all these changes that are unrelated to the tutorial. Or maybe your branch (rn-tut) is ahead of 'upstream:tutorial-phase1' and then we need to pull from 'upstream:master' into 'upstream:tutorial-phase1'

2022-08-22 14:37 UTC, nlarew commented on examples/java/local/README.md
> +#### Test via Android Studio
Yeah switching branches pulled in extra commits from master. I updated the commit history so this should be fixed.

2022-08-22 14:38 UTC, nlarew commented
@mongomoe Fixed the git history

2022-08-23 15:24 UTC, mongomoe commented on source/tutorial/react-native.txt
> +You can use the Realm JavaScript SDK and the official Realm React hooks
```suggestion
You can use the Realm JavaScript SDK and the official Realm React
```

I know we call it Realm Hooks sometimes internally, but iirc we're supposed to just refer to it as either the "Realm React" or "@realm/react" library.

2022-08-23 15:27 UTC, mongomoe commented on source/tutorial/react-native.txt
> +For this tutorial, we'll start with a pre-built template application to
Suggestion (not required for LGTM): I think the other SDKs had a slightly more descriptive variation of a sentence that explains the tutorial:
```
This tutorial adds functionality to the Template App. You will add a new Priority field to the existing Item model and update the Flexible Sync Subscription to only show items within a range of priorities.
```

2022-08-23 15:31 UTC, mongomoe commented on source/tutorial/react-native.txt
> +  represent individual to-do tasks.
```suggestion
  represent individual items to do.
```

2022-08-23 15:39 UTC, mongomoe commented on source/tutorial/react-native.txt
> +     - This is where we define the ``Item`` class, including its object
Suggestion/Not required for LGTM: For this table, I don't think it's necessary to start each description sentence with "This is", it gets repetitive and doesn't add value to the sentence. 

For example, the first description (ItemSchema.js), the following might be a bit more concise and avoid the fragment 'this is':

```
The Item class, including its object schema. We import the class in RealmContext.js
to include it in the app's Realm schema.
```

2022-08-23 15:43 UTC, mongomoe commented on source/tutorial/react-native.txt
> +      want to easily be able sort the levels. In TypeScript, you could
Question: Do we really need to describe what to do in TS if the template app doesn't use typescript?

2022-08-23 15:44 UTC, mongomoe commented on source/tutorial/react-native.txt
> +         least, ``Priority[3]``. This means that a "higher" priority
```suggestion
         least important, ``Priority[3]``. This means that a "higher" priority
```

2022-08-23 15:52 UTC, mongomoe commented on source/tutorial/react-native.txt
> +         At this point your React Native ``Item`` model and its
The other tutorials have a similar statement about why this doesn't break sync, do you just want to remove this paragraph and include that note, it reads:

```
Why Didn't This Break Sync?
Adding a property to a Realm object is not a breaking change and therefore does not 
require a client reset. The template app has Development Mode enabled, so changes
to the client Realm object are reflected in the server-side schema. For more information,
 see Enable or Disable Development Mode and Update Your Schema.

```

2022-08-23 15:59 UTC, mongomoe commented on source/tutorial/react-native.txt
> +                 style={{width: '80%'}}
Suggestion/not required for LGTM: This maybe a personal pet-peave of mine, but can we change the inline-styling to a styles.pickerWidth or something?

2022-08-23 16:30 UTC, mongomoe commented on source/tutorial/react-native.txt
> +                 // More important Items have lower priority values
```suggestion
                 // Filter 'Severe' or 'High' priority level items
```
The sentence "More important Items have lower priority values" seems very clunky and is hard to understand (especially if the reader skimmed the explanation that priority value is inversely correlated to importance)

2022-08-23 16:45 UTC, mongomoe commented on source/tutorial/react-native.txt
> +               priority: 'int' // Store the index value of the Priority enum rather than the name
Should this be?: 

```
priority: {type: 'int', default: Priority.High},
```

2022-08-23 16:50 UTC, mongomoe commented on source/tutorial/react-native.txt
> +             priority = Priority.High, // Default to High priority if none is specified
```suggestion
             priority = Priority["High"], // Default to High priority if none is specified
```

If it's Priority.High you will get the error: undefined is not an object 
![Uploading Screen Shot 2022-08-23 at 12.49.40 PM.png…]()

2022-08-23 16:53 UTC, mongomoe commented on source/tutorial/react-native.txt
> +           const [priority, setPriority] = useState(Priority.High);
```suggestion
           const [priority, setPriority] = useState(Priority["High"]);
```
Priority.High will lead to an undefined is not an object error. See: https://github.com/mongodb/docs-realm/pull/2105/files#r952881610

2022-08-23 17:23 UTC, mongomoe commented on source/tutorial/react-native.txt
> +         npm install @react-native-picker/picker
Needed fix: The user needs to pod install after installing @react-native-picker/picker, otherwise they'll get the following error:

![Uploading picker-not-found.png…]()

2022-08-23 17:25 UTC, mongomoe commented on source/tutorial/react-native.txt
> +         const Priority = createEnum([
Needed fix: You need to export 'Priority' in order to import it into `CreateToDoPrompt.js` as shown in the step [3.Add a Priority Picker](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rn-tut/tutorial/react-native/#add-a-priority-picker)

2022-08-23 17:25 UTC, mongomoe commented on source/tutorial/react-native.txt
> +         const Priority = createEnum([
```suggestion
         export const Priority = createEnum([
```

2022-08-23 17:26 UTC, mongomoe commented on source/tutorial/react-native.txt
> +         const Priority = createEnum([
Needed fix: You need to export 'Priority' in order to import it into `CreateToDoPrompt.js` as shown in the step [3.Add a Priority Picker](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/rn-tut/tutorial/react-native/#add-a-priority-picker)

2022-08-23 17:44 UTC, mongomoe commented on source/tutorial/react-native.txt
> +           onPress={() => setShowImportantOnly(b => !b)}
Suggestion/not required for lgtm (but strongly suggest): Can you change it from 'b' to something more descriptive, maybe: ``` onPress={() => setShowImportantOnly(buttonType => !buttonType)}```

2022-08-23 17:49 UTC, mongomoe commented on source/tutorial/react-native.txt
> +                 ))}
Suggestion/not required for LGTM (but strongly suggested): Can we choose something more descriptive than 'p', maybe:
```
                 {Priority.map((priorityValue, i) => (
                   <Picker.Item key={`picker-${priorityValue}-${i}`} label={priorityValue} value={Priority[priorityValue]} />
                 ))}
```

Note: I chose "`picker-${priorityValue}-${i}`" above because keys should be unique

2022-08-23 17:57 UTC, mongomoe commented on source/tutorial/react-native.txt
> +     - This is a re-usable button that logs out an authenticated user.
Needed fix:
```suggestion
     - This is a reusable button that logs out an authenticated user.
```

2022-08-23 17:59 UTC, mongomoe commented on source/tutorial/react-native.txt
> +      We want to allow a small number of named priority levels and we
```suggestion
      We want to allow a small number of named priority levels, and we
```

2022-08-23 18:01 UTC, mongomoe commented on source/tutorial/react-native.txt
> +      Your apps data model now includes a ``priority`` for each ``Item``
```suggestion
      Your app's data model now includes a ``priority`` for each ``Item``
```

2022-08-23 18:03 UTC, mongomoe commented on source/tutorial/react-native.txt
> +      "important only" mode, you'll see that the list doesn't change and
```suggestion
      "important only" mode, you'll see that the list doesn't change, and
```

2022-08-23 18:04 UTC, mongomoe commented on source/tutorial/react-native.txt
> +      be able create, complete, and delete to-do items as well as switch
```suggestion
      be able to create, complete, and delete to-do items as well as switch
```

2022-08-23 18:06 UTC, mongomoe reviewed
Great job on this so far! There are a few fixes needed to get this to LGTM which I've labelled as required fix, and there's also various grammar/wording fixes needed. Most of the other comments are suggestions which you can choose whether or not to incorporate into the PR.

2022-08-23 20:41 UTC, nlarew commented on source/tutorial/react-native.txt
> +      want to easily be able sort the levels. In TypeScript, you could
I mainly wanted a handy reference to say "doing it this way gives you the TS enum behavior" - I'll update to focus less on TS while still keeping the pointer.

2022-08-23 20:53 UTC, nlarew commented on source/tutorial/react-native.txt
> +         At this point your React Native ``Item`` model and its
Good point, updated

2022-08-23 20:54 UTC, nlarew commented on source/tutorial/react-native.txt
> +                 style={{width: '80%'}}
I thought about doing this but it's an extra step for something that's not the point of the tutorial and is still a one-liner here. Not sure it justifies the extra step but if you think it's worth it we can change.

2022-08-23 20:56 UTC, nlarew commented on source/tutorial/react-native.txt
> +         npm install @react-native-picker/picker
Oops good catch! I forgot I did this 😅

2022-08-24 04:47 UTC, nlarew commented on source/tutorial/react-native.txt
> +                 ))}
+1 for a more descriptive name. Keys only need to be unique within the map and the enum guarantees that each priority value is unique in the enum, so in this case just `priorityValue` will work.

2022-08-24 09:31 UTC, takameyer reviewed
Since there are descrepencies between the source code snippets in this tutorial and the template that was downloaded, I am going to pause this review. 
I will continue reviewing when I have a template where the code matches the tutorial, so I don't have to pull my hair out fixing errors.

2022-08-24 09:31 UTC, takameyer commented on source/tutorial/react-native.txt
> +         ])
The `createEnum` function is a bit overkill.  I would just define this as an object in descending order:
```
export const Priority = {
  Low: 0,
  Medium: 1,
  High: 2,
  Severe: 3
}
```
Then one can reference the priority as `Priority.Medium` which makes the code clearer when doing logic comparisons or assignments:
```
if( item.priority > Priority.High ) 
//...

realm.write(() => {
  item.priority = Priority.Low
})
```

2022-08-24 09:31 UTC, takameyer commented on source/tutorial/react-native.txt
> +         In a TypeScript app, you could define an `enum
We should also have a TypeScript version of this template and tutorial.  When doing so, one should consult us about how to correctly do class based models (there are changes coming to this in v11)

2022-08-24 15:20 UTC, takameyer requested changes
Really nice work here.  I was about to comment on the queryable field error, as I had tried to apply the filter right away and noticed it didn't work.  Fixed it myself and realized the next session was addressing said issue 😂 What was cool though is that the app updated without restarting as soon as I added the queryable field in the atlas ui.  Nice wow effect.

Feel free to get back to me when my feedback has been applied or if there are any questions on anything i've commented on.

2022-08-24 15:20 UTC, takameyer commented on source/tutorial/react-native.txt
> +         pod install --repo-update
This is only for `ios`.  It should be clear that they will have to rerun `npm run ios` or `npm run android` in order for the picker ot be useable.  They also might have to restart their realm bundler

2022-08-24 17:15 UTC, nlarew commented on source/tutorial/react-native.txt
Neat! Good suggestion thanks

2022-08-24 17:27 UTC, nlarew commented on source/tutorial/react-native.txt
> +               npx react-native run-android
Good catch, added

2022-08-24 17:29 UTC, nlarew commented on source/tutorial/react-native.txt
> +      - Add a few to-do items to the list.
Ah yeah I actually already installed the package just never added the import 😅

2022-08-24 17:30 UTC, nlarew commented on source/tutorial/react-native.txt
> +``backend`` directory. It has a unique ``app_id`` value in
Yeah this is a side-effect of how we organize the template apps so not a simple change unfortunately. I can bring it up with the team.

2022-08-24 17:33 UTC, nlarew commented on source/tutorial/react-native.txt
> +         ])
The code samples you have will work with the enum too. I chose to use the enum approach because it gives a two-way mapping between the level name and value. That way I can use the `Priority.High` syntax and _also_ map through the Priority enum to get the name and value together in the Picker component.

2022-08-24 17:34 UTC, nlarew commented on source/tutorial/react-native.txt
> +         In a TypeScript app, you could define an `enum
Yeah agreed - I think we've held off on going full force into TS until the models stuff is fully baked but we're all about it.

2022-08-24 17:58 UTC, nlarew commented
@takameyer Thanks for the comments! Update the page, lemme know what you think.

2022-08-25 06:55 UTC, takameyer commented on source/tutorial/react-native.txt
> +         ])
Ah, sure.  Makes sense that the Picker component needs an array instead of an object.

2022-08-25 07:29 UTC, takameyer approved these changes
Just a couple more requests.  Otherwise LGTM :shipit:

2022-08-25 07:29 UTC, takameyer commented on source/tutorial/react-native.txt
> +docs.
We should add a note here about Node 17.  And perhaps guide the user to [`nvm`](https://github.com/nvm-sh/nvm) if they need to downgrade Node.

2022-08-25 07:29 UTC, takameyer commented on source/tutorial/react-native.txt
> +         You may need to restart your project bundler after installing.
They will also need to rebuild the app with `npm run ios` and `npm run android`.  I would recommend running these commands first, this way they can see the changes as they update their code and there won't be any errors.

2022-08-25 20:33 UTC, nlarew commented on source/tutorial/react-native.txt
> -            # Enables Flipper.
Updated RN!

2022-08-25 20:35 UTC, nlarew commented on source/tutorial/react-native.txt
> +docs.
Node 17 is supported now since we're on the latest version of RN

2022-08-29 19:53 UTC, mongomoe commented on source/tutorial/react-native.txt
> +                 style={{width: '80%'}}
Good decision then :)

2022-08-29 19:56 UTC, mongomoe approved these changes
LGTM, fantastic job 👍

2022-08-30 15:05 UTC, merged