Data binding in Xamarin & MAUI
mongodb/docs-realm pull request #2115
Opened 2022-08-24 17:29 UTC by MongoCaleb

## Pull Request Info

### Jira

https://jira.mongodb.org/browse/DOCSP-24750

### Staged Changes (Requires MongoDB Corp SSO)

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/data_binding/sdk/dotnet/fundamentals/data-binding/

2022-08-25 07:38 UTC, papafe requested changes

2022-08-25 07:38 UTC, papafe commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +object changes, and vice versa.
I would say "allows updating the UI...". It's not strictly the data binding doing it. 
Also it should be "when an underlying object or collection changes"

2022-08-25 07:38 UTC, papafe commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +Realm objects are :ref:`live objects <dotnet-live-object>` that update automatically
This is maybe nitpicking, but maybe we should say "Realm objects and collections are live, and so update automatically to ...", so that we continue speaking about both objects and collections throughout.

2022-08-25 07:38 UTC, papafe commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +`INotifyCollectionChanged <https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.inotifycollectionchanged>`__.
Maybe "Implement INotifyCollectionChanged underneath so all changes can be automatically reflected in the UI, without the need to do additional work"? Too much repetition?

2022-08-25 07:54 UTC, papafe commented
I would say that this page should contain snippets to show most of what people want to do with Realm and Xamarin/MAUI. I'm not sure if we need to have the code snippet coming necessarily from the template app, but I think we should show:

Let's say that we have a model like this:
```csharp
public class Person : RealmObject
{
    public string Name { get; set; }

    public int Age { get; set; }

    public IList<string> ChildNames { get; }

	public IList<Dog> Dogs { get; }
}

public class Dog : RealmObject
{
    public string Name { get; set; }

    public string Breed { get; set; }

   public int DogYears { get; set; }
}
```

--- Binding to an object ----
In code :
```csharp
public Person Person {get;}

...
Person = realm.All<Person>().First() //For example
```
In XAML then we can do:
```
            <Label Text="{Binding Person.Name}" />
            <Label Text="{Binding Person.Age}" />
```
Changing Name or Age in Person will update the UI. (if those were Editor/Entry or another input form, then changes in the UI are also saved in Realm, so the value of Age and Name will change)

--- Binding to a collection ---
You can bind to a query (this is what you've shown)

You can also bind to any collection (like Dogs or ChildNames in Person). For example:
In code :
```csharp
public IEnumerable<Dog> Dogs {get;}

...
...
Dogs = person.Dogs;
```
In XAML then we can do (using the same UI you have in the example with the list):
```
<ListView x:Name="listItems" ItemsSource="{Binding Dogs}">

...
... 


<Label Text="{Binding Breed}"/>


```

Finally, you can also filter collections of objects like it's done with queries by using AsRealmQueryable().
For example:
```csharp
OldDogs = person.Dogs.AsRealmQueryable().Where( d => d.DogYears > 55);
```

I understand it's a lot of different things, but those are probably the most common use cases that we get asked about, so it would be a good idea to have them shown somewhere

2022-08-25 13:13 UTC, papafe requested changes

2022-08-25 13:13 UTC, papafe commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +   Because Realm objects are live objects, you should not cast a Realm collection
Maybe "Because Realm collections are live"

2022-08-25 13:13 UTC, papafe commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +   using ``ToList()``. Casting the collection to a list makes the collection no
Calling toList() it's not exactly casting. You could say "This forces loading the collection objects from memory, and the resulting collection is also no more live."

2022-08-25 14:09 UTC, dacharyc approved these changes
Overall LGTM, just a couple of nits.

Also, a note about the page name. In the recent App Services & Realm renaming document, there's a note that says:

> When referring to the Realm SDKs avoid using terms like 'binding' or 'wrapper' that may add confusion or imply that the SDKs offer fewer features/power than they actually do

I wonder if there's another name we could use for this page that isn't so general - maybe something like "Bind Realm Collections to the UI"? I know that's a mouthful, but "Data Binding" is such a general term I would think using it as a page title falls within the spirit of this marketing note.

2022-08-25 14:09 UTC, dacharyc commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +to reflect data changes, making data binding the UI simple and straight-forward.
Nit: "simple" and "straight-forward" are value judgements that we should try to avoid, as not all developers may agree. We should probably reword to avoid using these terms. Building on papafe's note above, maybe something like:

> Realm objects and collections are live, and so update automatically to reflect data changes. When you bind these to your UI, your UI always reflects the latest data.

Or something more directly about the benefit, rather than a subjective value judgement.

2022-08-25 14:09 UTC, dacharyc commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +In the following code example, we're creating a public ``IEnumerable`` of
Nit: indirect sentence structure is a bit less readable. Consider rewording to something like:

> In the following code example, we create a public...

2022-08-26 08:57 UTC, papafe commented
@MongoCaleb Another thing I think it's definitely worth mentioning (probably in one of those warning boxes) is that, at the moment, Realm does not work with compiled bindings for writes.
This means that if you use Realm objects just to take values to show in the UI, then it's fine. But if you need to have a value of a Realm object to change when a UI field changes (like with an Editor/Entry, for instance), then this will give a runtime exception complaining that there is no transaction open. 
This limitation is something we're trying to solve, at least for MAUI

2022-08-26 23:15 UTC, MongoCaleb commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +`INotifyCollectionChanged <https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.inotifycollectionchanged>`__.
> Too much repetition == true

2022-08-26 23:24 UTC, MongoCaleb commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +In the following code example, we're creating a public ``IEnumerable`` of
@papafe , this confuses me: 
> But if you need to have a value of a Realm object to change when a UI field changes (like with an Editor/Entry, for instance), then this will give a runtime exception complaining that there is no transaction open. 

Our current template app & tutorial work to update just fine. UI changes are reflected in the realm object. I must be missing a nuance in your comment.

2022-08-26 23:25 UTC, MongoCaleb commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +                                    Source="trash.png" AutomationId="{Binding Id}">
dunno why they were in there. Removed.

2022-08-26 23:31 UTC, MongoCaleb commented
> I understand it's a lot of different things, but those are probably the most common use cases that we get asked about, so it would be a good idea to have them shown somewhere

I'm not sure we're actually showing anything very different in these 3 examples. In each, we're binding the UI to a live object/collection. Showing an object and 2 different live collections doesn't make much sense to me, since it's the same binding technique in all 3, no? We show the filtering of a collection in other examples in the docs already. If you can help me understand how these 3 examples differ enough to help our users, that would be great.

2022-08-29 07:32 UTC, papafe commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +In the following code example, we're creating a public ``IEnumerable`` of
The problem is if compiled bindings are used. By default Xamarin does not use compiled bindings (while MAUI does it I think).

2022-08-29 07:38 UTC, papafe commented
> > I understand it's a lot of different things, but those are probably the most common use cases that we get asked about, so it would be a good idea to have them shown somewhere
> 
> I'm not sure we're actually showing anything very different in these 3 examples. In each, we're binding the UI to a live object/collection. Showing an object and 2 different live collections doesn't make much sense to me, since it's the same binding technique in all 3, no? We show the filtering of a collection in other examples in the docs already. If you can help me understand how these 3 examples differ enough to help our users, that would be great.

I would say this is more to be sure to cover the ground for all the most common cases that people encounter. A lot of new developers are confused about how data binding works, so having everything shown to them could help setting everything quicker. 
Binding to an object is definitely basic, but it shows that it's auto updating. The extra example about collection (person.Dogs) is to show that it's possible to bind also to collections inside objects, not only to queries (because it's not necessarily clear). Regarding the filtering, I understand it's shown in other parts, but maybe it's not evident that it's particularly useful in this case. 
We get a lot of questions/doubts/bug requests around bindings, and it would be nice to be able to just send a link to the docs with examples. Also, hopefully, this would reduce the number of such posts 😁

2022-08-30 23:14 UTC, MongoCaleb commented
Bluehawk error will exist until https://github.com/mongodb-university/Bluehawk/pull/129 is merged.

2022-08-31 08:16 UTC, papafe requested changes
We also need a warning box that says something like:
" Please note that Realm is not yet compatible with compiled bindings"

2022-08-31 08:16 UTC, papafe commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +.. literalinclude:: /examples/generated/dotnet/MainPage.xaml.snippet.bind-embedded-cs.cs
This example shows the wrong property to bind to.

2022-08-31 08:16 UTC, papafe commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +In the associated XAML file, we bind a ``ListView`` to the **Items** ``IEnumerable``
It's not the listItems enumerable anymore that is being shown

2022-08-31 08:16 UTC, papafe commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +.. literalinclude:: /examples/generated/dotnet/MainPage.snippet.bind-list-xaml.xaml
The name of the ListView is "listItems", but this is a list of employees

2022-08-31 08:16 UTC, papafe commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +Binding to a Single Realm Object
Probably Single shouldn't be capitalized? (also object probably)

2022-08-31 08:16 UTC, papafe commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +Binding to an Embedded Collection
Maybe "embedded" collections isn't the right term here, it makes it sounds like it's related to embedded object. 
Either we call it "Binding to a Collection property", or this could also be part of the previous section (Binding to a Realm Collection), and we say something like "Please note that you can also bind to collection properties, like in the following example"). If we go this way then there are 2 cases and not 3 😁

2022-08-31 08:16 UTC, papafe commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +.. literalinclude:: /examples/generated/dotnet/MainPage.xaml.snippet.bind-embedded-cs.cs
It also needs to use "AsRealmQueryable", otherwise it does not work. I would also add a note that we are using "AsRealmQueryable" because we're filtering the list, otherwise we can bind to the list directly, without the need to call it.

2022-08-31 18:28 UTC, MongoCaleb commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +Binding to a Single Realm Object
No, but removed anyway. :)

2022-08-31 19:14 UTC, papafe approved these changes
Apart from those two small things it looks good! I've just looked at the staged page, and not at all the files that are in the PR. Not sure if that's necessary?

2022-08-31 19:14 UTC, papafe commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +   Because Realm collections are live, you should not call ``ToList()`` when
Not sure what's happening, but this looks a little strange in the page

2022-08-31 19:14 UTC, papafe commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +.. literalinclude:: /examples/generated/dotnet/MainPage.xaml.snippet.bind-embedded-cs.cs
This example still shows the wrong property `public Employee Employee123 { get; }`, instead of `public IEnumerabel<Items> IncompleteItems { get; }`

2022-08-31 20:51 UTC, dacharyc approved these changes
Found some grammar nits and a couple of style things. Mod those, the page LGTM.

2022-08-31 20:51 UTC, dacharyc commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +binding use cases. They all use the following Realm objects:
Nit: compound modifier here should be hyphenated.
```suggestion
The following code snippets show both the C# and XAML for 3 typical data-binding 
use cases. They all use the following Realm objects:
```

2022-08-31 20:51 UTC, dacharyc commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +The following code snippets show both the C# and XAML for 3 typical data
Our [style guide](https://www.mongodb.com/docs/meta/style-guide/style/numbers/) indicates we should spell out numbers from zero through nine:
```suggestion
The following code snippets show both the C# and XAML for three typical data 
```

2022-08-31 20:51 UTC, dacharyc commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +   Because Realm collections are live, you should not call ``ToList()`` when
Agreed, looks like the indentation below isn't at the right level, but I wonder if there's also an issue with the `()` in the note title?

2022-08-31 20:51 UTC, dacharyc commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +Binding to a Single Realm Object
The docs [style guide](https://www.mongodb.com/docs/meta/style-guide/style/titles-and-headings/) indicates we should use title case in section headings, but I think we're inconsistent about doing this.

2022-08-31 20:51 UTC, dacharyc commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +In the following example, we create a public property of type Employee. Elsewhere
This is a bit inconsistent in how we use monospace. I might expect `Employee` to be monospace, and I would definitely expect `EmployeeId` to be monospace since you do monospace `Name` in ln 56. In the next section, you bold `Employee`, and then further down the page you use monospace for ``Employee`` in ln 81.

I don't have a strong opinion about what styling you should use where, and the style guide doesn't provide a lot of guidance about when to use monospace, but I'd say we should be consistent across the page. If we fall back to the Microsoft Manual of Style, I see that class names should be bold and code samples, including keywords and variables within text and as separate paragraphs, should be monospace.

2022-08-31 20:51 UTC, dacharyc commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +we bind to the ``Items`` property of a specific Employee``. The ``Items``
```suggestion
we bind to the ``Items`` property of a specific ``Employee``. The ``Items`` 
```

2022-08-31 20:51 UTC, dacharyc commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +collection with all of the documents in the Employees collection:
From context, I believe I am reading about a Realm collection here, but then you refer to documents in ln 67, which makes me wonder if we have switched context to a MongoDB collection.

I think, for clarity, we should stick with the term objects when discussing Realm collections and documents when discussing accessing MongoDB collections.

2022-08-31 20:51 UTC, dacharyc commented on source/sdk/dotnet/fundamentals/data-binding.txt
> +	Note that we are calling the :dotnet-sdk:`AsRealmQueryable()
I'm just noting here that the `()` in the note title isn't an issue on the staged page, so I think it's the indent in the first line of the note above at ln 43 that's causing the weird bold styling in the staged page.

2022-09-01 16:19 UTC, merged