Convert Nosync and sync realms
mongodb/docs-realm pull request #2120
Opened 2022-08-24 21:50 UTC by MongoCaleb

## Pull Request Info

### Jira
https://jira.mongodb.org/browse/DOCSP-20724

### Staged Changes (Requires MongoDB Corp SSO)
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/nosync-to-sync/sdk/dotnet/advanced-guides/convert-realm/

2022-08-25 13:29 UTC, papafe commented on examples/dotnet/Examples/Convert.cs
> +            var nonsyncConfig = new RealmConfiguration("my.realm");
better call it nonSyncConfig

2022-08-25 13:32 UTC, papafe requested changes

2022-08-25 13:32 UTC, papafe commented on source/sdk/dotnet/advanced-guides/convert-realm.txt
> +   Converting between non-synced and synced realms only works with Flexible Sync
Actually it works also with Partition Sync. The only non working case is when converting a Partition based sync realm to another partition based sync realm with a different partition key

2022-08-25 14:29 UTC, dacharyc approved these changes
LGTM - just a couple of Qs about whether we should be more explicit about some potential gotchas.

2022-08-25 14:29 UTC, dacharyc commented on source/sdk/dotnet/advanced-guides/convert-realm.txt
> +   Converting between non-synced and synced realms only works with Flexible Sync
I was surprised to see this! In the other SDKs, this seems to only work with Partition-Based Sync. Way to go .NET team :)

2022-08-25 14:29 UTC, dacharyc commented on source/sdk/dotnet/advanced-guides/convert-realm.txt
> +in both directions. We do this by calling
I had to stop and think about the implications of this, which makes me wonder if we should add some more explicit details around what this entails.

i.e. if we're awaiting an async upload/download, presumably we should block new writes to the realm? Otherwise, there could be new pending operations by the time these awaitable async calls complete and we try to copy the realm. 

I also wondered if it's worth explicitly calling out that this requires the user to be online. I know it's implied by the waiting for network activity, but it sort of breaks our "Realm is offline-first" marketing message, so I wonder if it's just worth making a note about it.

2022-08-26 23:07 UTC, MongoCaleb commented on source/sdk/dotnet/advanced-guides/convert-realm.txt
> +in both directions. We do this by calling
Ultimately it shouldn't matter -- we're explicitly saying we not longer want shared, fresh data. So...the code shows getting the "latest", which might not include something being written concurrently from another device. I think that's fine, and have added a note to the end. LMK what you think!

2022-08-29 07:27 UTC, papafe requested changes

2022-08-29 12:55 UTC, dacharyc approved these changes
One tiny nit, but LGTM 👍

2022-08-29 12:55 UTC, dacharyc commented on source/sdk/dotnet/advanced-guides/convert-realm.txt
> +With this method, you can easily duplicate a realm's data, which you can then
Nit: "easily" sounds dangerously close to "simple." Maybe remove the subjective difficulty modifier and just say "you can duplicate a realm's data"?

2022-08-29 17:23 UTC, merged