(DOCSP-24627): Flutter tutorial
mongodb/docs-realm pull request #2123
Opened 2022-08-25 21:15 UTC by mongodben

## Pull Request Info

Flutter tutorial w flexible sync

### Jira

- https://jira.mongodb.org/browse/DOCSP-24627

### Staged Changes (Requires MongoDB Corp SSO)

- [Flutter Tutorial](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24627/tutorial/flutter/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2022-08-26 21:29 UTC, dacharyc approved these changes
Just a couple of small comments and a broken link - otherwise, this looks really good, and even managed to guide me - a dev completely new to Flutter stuff - through the tutorial (mostly) successfully. Nice work!

2022-08-29 14:11 UTC, mongodben commented on source/tutorial/flutter.txt
> +      In your code editor, take a few minutes to explore how the solution is
nice catch! you're absolutely right. will change.

2022-08-29 14:11 UTC, mongodben commented on source/tutorial/flutter.txt
> +         * - ``main.dart``
makes sense to me as well. will update.

2022-08-29 14:12 UTC, mongodben commented on source/tutorial/flutter.txt
> +         * - ``main.dart``
```suggestion
         * - ``lib/main.dart``
```

2022-08-30 14:03 UTC, nielsenko commented on source/examples/generated/flutter/tutorial/item_card.snippet.item-card.dart
> +          child: Slidable(
Don't you want to hook up some action on people actually sliding this?

2022-08-30 14:03 UTC, nielsenko commented on source/examples/generated/flutter/tutorial/init_realm.snippet.post-update.dart
> +            'priority <= \$0 OR priority == nil', [PriorityLevel.high]),
This surprised me. You are fetching everything with a priority **lower** than or equal to `PriorityLevel.high` or that has no priority at all. I know this is just a sample, but it sounds a bit odd in my ears.

2022-08-30 14:03 UTC, nielsenko commented on source/examples/generated/flutter/tutorial/init_realm.snippet.updated-sub.dart
> +          'priority <= \$0 OR priority == nil',
Same..

2022-08-30 14:09 UTC, nielsenko approved these changes
LGTM, I have a few observations

2022-08-30 14:39 UTC, mongodben commented on source/examples/generated/flutter/tutorial/item_card.snippet.item-card.dart
> +          child: Slidable(
not sure? this was part of the rendering of the cards, i thought

2022-08-30 14:41 UTC, mongodben commented on source/examples/generated/flutter/tutorial/init_realm.snippet.post-update.dart
> +            'priority <= \$0 OR priority == nil', [PriorityLevel.high]),
i get what you're saying. however this is the query that gets the relevant data b/c: 

- highest priority is `0`
- and we're looking for cards w no priority specified

and this is actually outside my hands directly, b/c this is the format that all the tutorials take, per docs team decision

2022-08-31 20:07 UTC, dacharyc requested changes
Still some things that I think need to be tweaked, but it mostly worked this time so good progress!

2022-08-31 20:07 UTC, dacharyc commented on source/tutorial/flutter.txt
> +   .. step:: Test the changes
Testing after updating the subscription did not work as expected. The item that I initially created doesn't have a `null` priority - there is no priority property. It does still appear on the device.

When I add a new low-priority item, there is no issue - it appears on the device and I don't see a compensating write error in the console or the App Services logs. 

I did eventually stop the app and delete it from the device before running it again, and _then_ I saw the expected behavior - only the high-priority item was in the list, and creating a new item of low priority triggered a compensating write. Seems we may need to advise users to delete the app again before testing this? I would assume that isn't desired, though, because people should be able to change the subscription and see the synced objects update, so I'm not sure what we need to do to trigger the subscription update.

2022-08-31 20:18 UTC, mongodben commented on source/examples/generated/flutter/tutorial/create_item.snippet.create-item.dart
> +                            final summary = taskEditingController.text;
yes i think so to both of those

2022-08-31 20:18 UTC, mongodben commented on source/tutorial/flutter.txt
> +         in ``lib/components/item.dart``. Create a new widget ``_PriorityIndicator`` that gives
yep, nice catch. was just `item.dart` in a prev iteration. must have slipped into the guide.

2022-08-31 20:19 UTC, mongodben commented on source/examples/generated/flutter/tutorial/init_realm.snippet.updated-sub.dart.modified.rst
> +       realm.subscriptions.findByName('getUserItemsWithPriority');
i'd say no b/c this is just the dart linter at work doing what it does when it hits a line length limit. now it hits the limit b/c longer subscription name.

2022-08-31 20:22 UTC, mongodben commented on source/tutorial/flutter.txt
> +   .. step:: Test the changes
hmm interesting. will need to investigate this one.

2022-09-01 13:32 UTC, mongodben commented on source/tutorial/flutter.txt
> +         Make the file ``lib/components/select_priority.dart``.
did some tweaks on your suggestion, but adjusted to remove 'make the file'

2022-09-01 13:42 UTC, mongodben commented on source/tutorial/flutter.txt
> +   .. step:: Test the changes
maybe call to `await realm.subscriptions.waitForSynchronization()` after changing subscriptions? will see if i can duplicate the behavior you're describing and then try to add this. 

https://pub.dev/documentation/realm/latest/realm/SubscriptionSet/waitForSynchronization.html

2022-09-06 19:20 UTC, mongodben commented on source/tutorial/flutter.txt
> +      #. Now add a visual indicator for priority in the ``Item`` widget
```suggestion
      #. Now add a visual indicator for priority in the ``ItemCard`` widget
```

2022-09-06 19:20 UTC, mongodben commented on source/tutorial/flutter.txt
> +         widget.
```suggestion
         Add a ``_PriorityIndicator`` widget you just created to the ``ItemCard``
         widget.
```

2022-09-07 17:07 UTC, dacharyc approved these changes
Still a few tweaks to make, I think. But it's very close. I'm going to LGTM it because I don't think these changes necessarily need another review.

2022-09-07 17:07 UTC, dacharyc commented on source/tutorial/flutter.txt
> +      Update the subscription to the delete the old subscription and add
```suggestion
      Update the subscription to delete the old subscription and add
```

2022-09-07 17:07 UTC, dacharyc commented on source/tutorial/flutter.txt
> +      since it has a priority of "High" (1). But it is not in the list. If you
This was not quite my experience. When I ran the app again, I see the item of "High" priority in the list _and_ I got the priority is not a queryable field error.

2022-09-07 17:07 UTC, dacharyc commented on source/tutorial/flutter.txt
> +      .. code-block::
When I did this, I did not get this error. Instead, the non-high-priority item just went away.

2022-09-07 17:22 UTC, mongodben commented on source/tutorial/flutter.txt
> +         .. include:: /examples/generated/flutter/tutorial/item_viewmodel.snippet.item-viewmodel.dart.modified.rst
fixed

2022-09-07 17:23 UTC, mongodben commented on source/tutorial/flutter.txt
> +      .. code-block::
i was getting this consistently. updating this documentation to reflect that user *might see*

2022-09-07 17:28 UTC, mongodben commented on source/tutorial/flutter.txt
> +      since it has a priority of "High" (1). But it is not in the list. If you
fixed to reflect current state

2022-09-07 17:47 UTC, merged