(DOCSP-23489): Swift client reset with recovery docs
mongodb/docs-realm pull request #2201
Opened 2022-10-07 19:43 UTC by dacharyc

## Pull Request Info

Note for reviewer: there are a couple of :ref:s that won't work until the App Services Client Reset PR is merged ([#165](https://github.com/mongodb/docs-app-services/pull/165)).

### Jira

- https://jira.mongodb.org/browse/DOCSP-23489

### Staged Changes (Requires MongoDB Corp SSO)

- [Handle Sync Errors](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/): Revised Client Reset section

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2022-10-18 14:51 UTC, mongomoe commented on source/sdk/swift/sync/handle-sync-errors.txt
> +client reset occurs, and falls through to discard unsynced changes when
```suggestion
client reset occurs, and discards unsynced changes when 
```

2022-10-18 14:57 UTC, ericjordanmossman requested changes

2022-10-18 14:57 UTC, ericjordanmossman commented on source/sdk/swift/sync/handle-sync-errors.txt
> +Choose ``.recoverOrDiscardUnsyncedChanges`` to handle most client reset
I think @ianpward would want us to steer users to .recoverUnsyncedChanges. That's also our default.

2022-10-18 14:57 UTC, ericjordanmossman commented on source/sdk/swift/sync/handle-sync-errors.txt
> +You can specify a before and after block to execute during the automatic client
Maybe put quotes or back tick around "before" and "after" since it's not a technical term and just a proper noun I chose.

2022-10-18 14:57 UTC, ericjordanmossman commented on examples/ios/Examples/ClientReset.swift
>              // This block could be used to back-up a realm file, send reporting, etc.
Recommended addition:
```let beforeClientResetBlock: (Realm) -> Void = { before in
    var recoveryConfig = Realm.Configuration()
    recoveryConfig.fileURL = myRecoveryPath
    do {
       before.writeCopy(configuration: recoveryConfig)
        // The copied realm could be used later for recovery, debugging, reporting, etc.
     } catch {
            // handle error
     }
}```

This way the developer might see some of the things they could do.

2022-10-18 14:57 UTC, ericjordanmossman commented on examples/ios/Examples/ClientReset.swift
>              // This block could be used to add custom recovery logic, send reporting, etc.
Potential recommended:
```
let afterClientResetBlock: (Realm, Realm) -> Void = { before, after in
    /// // This block could be used to add custom recovery logic, back-up a realm file, send reporting, etc.
    /// for object in before.objects(myClass.self) {
    ///     let res = after.objects(myClass.self)
    ///     if (res.filter("primaryKey == %@", object.primaryKey).first != nil) {
    ///         // ...custom recovery logic...
    ///     } else {
    ///         // ...custom recovery logic...
    ///     }
    /// }
```

This block isn't something a developer would want to do exactly, but hopefully demonstrates that `before` and `after` are realm references and they could normal realm things to them.

2022-10-18 14:57 UTC, ericjordanmossman commented on source/sdk/swift/sync/handle-sync-errors.txt
> +- ``.recoverUnsyncedChanges``: choose this mode when you do not want to fall
I'd put this sentence last, and lead with the second sentence.
"choose this mode when you do not want to fall through to discard unsynced changes."
This may be more style, but I'd put the edge case later.

2022-10-18 14:57 UTC, ericjordanmossman commented on source/sdk/swift/sync/handle-sync-errors.txt
> +- ``.recoverOrDiscardUnsyncedChanges``: choose this mode when you want to
Same here. Lead with second sentence.

2022-10-18 14:57 UTC, ericjordanmossman commented on source/sdk/swift/sync/handle-sync-errors.txt
> +- ``.recoverOrDiscardUnsyncedChanges``: choose this mode when you want to
Same as above, lead with second sentence.

2022-10-18 15:26 UTC, mongodben commented on examples/ios/Examples/ClientReset.swift
> +            var configuration = user.flexibleSyncConfiguration(clientResetMode: .recoverOrDiscardUnsyncedChanges(beforeReset: beforeClientResetBlock, afterReset: afterClientResetBlock))
not sure swift conventions here, but could this code be split over a couple of lines? 

currently makes the code example have a lot of horizontal wrap

2022-10-18 15:29 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +work for your app.
are you here talking about, do `.manual` mode if automatic fails? is this a property of the `.recoverUnsyncedChanges` method? 

i think this paragraph could be a little clearer, and a code example could help as well.

2022-10-18 15:31 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +  when there are no schema changes, or non-breaking schema changes.
this doesn't seem like a limitation, but a good feature. yet its in the list of limitations. i think something needs rephrasing.

2022-10-18 17:08 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +as in when there are breaking schema changes, the client reset process falls
```suggestion
like when there are breaking schema changes, the client reset process falls 
```

2022-10-18 17:08 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +through to ``.manual`` mode. You can set an error handler for this fall
```suggestion
as in when there are breaking schema changes, the client reset process falls 
back to ``.manual`` mode. You can set an error handler for this fall
```

2022-10-18 17:09 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +through case via the :swift-sdk:`SyncManager
```suggestion
back case via the :swift-sdk:`SyncManager 
```

2022-10-18 17:11 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +users to update the app or perform some other action.
```suggestion
automatic client recovery modes when possible, and treating the manual
handler as a tool for fatal error recovery situations where you advise
users to update the app or perform some other action. 
```

2022-10-18 17:14 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
in the below bullet point, it says "Realm server crash". what is meant by Realm server? 
maybe rephrase to 'Device Sync server crash'?

2022-10-18 17:15 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
>  situation:
```suggestion
situations:
```

2022-10-18 17:16 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
>  version on the client.
this intro doesn't talk about the notion of breaking schema changes. should it?

2022-10-18 17:24 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +cases. When you make schema changes, Client Recovery has these limitations:
what do you mean by "Client Recovery" here? it's title cased in this paragraph like a feature, but hasn't been introduced as such yet

2022-10-18 17:26 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +  reset handler <ios-manual-client-reset-handler>`. Automatic client recovery
can it automatically *discard* changes if breaking? or must you always do manual recovery if breaking changes, even if you're ok discarding changes?

2022-10-18 17:31 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +  to automatically perform the client reset.
per below example, looks like `.manual` is a secondary fallback if cannot discard. is this a correct understanding? 

if so, would be good for docs to reflect this.

2022-10-18 17:39 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +~~~~~~~~~~~~~~~~~~~~~
should this section be subsection of "Recover unsynced changes" section? 

based on my understanding of this, the content in "Handle Schema Changes" is only applicable when you're doing a client reset w recovery.

2022-10-18 17:50 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +.. versionchanged:: 10.32.0: .discardLocal changed to .discardUnsyncedChanges
in the rendered docs, there's a double colon here (`::`). not sure why. can you make it just 1?

2022-10-18 17:51 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +breaking schema changes, you should implement a manual client reset handler.
```suggestion
breaking schema changes and you're using another client reset handler, you should implement a manual client reset handler.
```

2022-10-18 17:51 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +is not an available property on the SyncConfiguration.
```suggestion
is not an available property on the `SyncConfiguration`.
```

2022-10-18 17:54 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +automatic client recovery modes when possible, and treating the manual
maybe ref "automatic client recovery modes" to the above section about the topic?

2022-10-18 17:54 UTC, mongodben reviewed
nice work documenting a very complex set of features. some comments throughout.

2022-10-18 20:32 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
> +work for your app.
No, this is meant to communicate that you can manually handle a client reset if our automatic client reset logic is not compatible with the app's design or needs. We don't want to recommend developers handle it themselves, but it _is_ an option that developers should know about if they don't want to use our client recovery rules or have specific logic they need to add during a client reset.

2022-10-18 20:33 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
> +<https://www.mongodb.com/docs/realm-sdks/swift/latest/Typealiases.html#/s:10RealmSwift11SyncManagera>`:
Good catch, thank you!

2022-10-18 20:44 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
I don't actually know. This bullet predates my touching this page. I'm just going to remove that "For example" since I'm not really sure what it means, and if it _does_ mean Device Sync server crash, we maybe don't want to highlight that possibility in docs.

2022-10-18 20:45 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
>  situation:
This isn't actually two separate situations; it's when A *and* B.

2022-10-18 20:48 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
>  version on the client.
I don't think it should, necessarily, as there are apparently a bunch of reasons a client reset could occur - not just breaking schema changes. But it's a good note that this intro doesn't really provide details about why this could happen. I'll add a link to the client reset page in App Services that goes into more detail about why client resets could occur.

2022-10-18 20:54 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
> +requires specific client reset logic that can't be handled automatically.
I specifically wanted to add some information about what we mean when we talk about an "automatic client reset". This is meant to be conceptual information about what is an automatic client reset and which client reset modes use it. I do introduce the paragraph with a sentence introducing the client reset modes here: 

> The Realm SDKs provide :ref:`client reset modes <ios-specify-client-reset-mode>` that automatically handle most client reset errors.

The "Specify a Client Reset Mode" section is supposed to be more of a "how to do the thing" section.

2022-10-18 20:58 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
> +cases. When you make schema changes, Client Recovery has these limitations:
Ah, good point. I had recently written a lot about this on the App Services side and completely spaced that I hadn't introduced it as such in the SDK. Added a few lines and links to App Services docs.

2022-10-18 21:05 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
> +  to automatically perform the client reset.
Added the line from above bullet point here also.

2022-10-18 21:07 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
> +~~~~~~~~~~~~~~~~~~~~~
Breaking changes must be handled through a manual client reset. So I think this section generally applies to the entire client reset process.

2022-10-18 21:10 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
> +.. versionchanged:: 10.32.0: .discardLocal changed to .discardUnsyncedChanges
Huh, interesting. I'll try changing the punctuation and see what happens?

2022-10-18 21:11 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
> +breaking schema changes, you should implement a manual client reset handler.
I don't think this actually makes sense, as you have to implement a manual client reset handler full stop if you make breaking changes.

2022-10-19 14:38 UTC, ericjordanmossman commented on examples/ios/Examples/ClientReset.swift
>              // This block could be used to back-up a realm file, send reporting, etc.
Looking at this in staged format,  I realized that a developer might think this is the _only_ way to use a `beforeClientResetBlock`. So how about adding something like: 
```
// A block called after a client reset error is detected, but before the client reset process is executed.
// This block could be used for custom logic, reporting, debugging, testing, etc. Below is one example use.
let beforeClientResetBlock: (Realm) -> Void = { before in
    var recoveryConfig = Realm.Configuration()
    recoveryConfig.fileURL = myRecoveryPath
    do {
       before.writeCopy(configuration: recoveryConfig)
        // The copied realm could be used later for recovery, debugging, reporting, etc.
     } catch {
            // handle error
     }
}
```

2022-10-19 14:45 UTC, ericjordanmossman commented on examples/ios/Examples/ClientReset.swift
>              // This block could be used to add custom recovery logic, send reporting, etc.
Sorry, added triple forward slash by mistake (took them from the sdk docs).

```
// A block called after the client recovery process has executed.
// This block could be used for custom recovery, reporting, debugging etc. 
// Below is just one example use.
let afterClientResetBlock: (Realm, Realm) -> Void = { before, after in
      for object in before.objects(myClass.self) {
          let res = after.objects(myClass.self)
         if (res.filter("primaryKey == %@", object.primaryKey).first != nil) {
             // ...custom recovery logic...
         } else {
             // ...custom recovery logic...
         }
     }
```

For the final product, please check the bracket indentation. It's hard to format in the github comment section.

2022-10-19 15:09 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
>  situation:
```suggestion
error recovery task that your client app must perform when both of the following occur:
```

2022-10-19 15:10 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
>  situation:
ah ok, see new suggestion below clarifying that

2022-10-19 15:11 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +:ref:`client-resets`.
```suggestion
For more information about what might cause a client reset to occur, see
:ref:`client-resets`.
```

2022-10-19 15:15 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +For information on breaking vs. non-breaking schema changes, see:
```suggestion
For information on breaking vs. non-breaking schema changes, see 
```

i notice this is 2nd time on this page w `see: <page link>`. for the sdks i've worked on, we don't do this. is this a convention in the swift sdk docs?

2022-10-19 15:22 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +  reset handler <ios-manual-client-reset-handler>`. Automatic client recovery
ok, i think i better understand now. 

pardon me if my understanding is still wrong, i think in this bullet point it's worth noting that the 3 non manual client reset handlers (.recoverUnsyncedChanges, .recoverOrDiscardUnsyncedChanges, .discardUnsyncedChanges) still fall back to manual client reset if there's a breaking change.

2022-10-19 17:35 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +If the client reset operation cannot complete in recover unsynced changes mode,
i think it could be worthwhile to break this into its own section, titled something like "Manual Fallback" with a ref like `ios-client-reset-manual-fallback`.

this'd make sense cuz the code example here is relevant to `.recoverUnsyncedChanges`, `.recoverOrDiscardUnsyncedChanges`, and `.discardUnsyncedChanges`.

and then you could reference this section in the explanations of all those sync handlers

2022-10-19 17:37 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +  through to ``.manual``. Choose this mode when you do not want to fall
i find it confusing how this refers to the method `.manual` when it's not actually invoking `.manual()` like it would in a [non-fallback manual client reset](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23489/sdk/swift/sync/handle-sync-errors/#manual-client-reset). 

rather, you just set `app.syncManager.errorHandler` here. per [below suggestion](https://github.com/mongodb/docs-realm/pull/2201/files#r999758994), if you make a dedicated section for "Manual Fallback", you could ref to it here rather than refer to `.manual`.

2022-10-19 17:42 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +   :language: swift
per [above suggestion](https://github.com/mongodb/docs-realm/pull/2201/files#r999758994), i think it'd make sense to break this out into it's own section to reference here.

2022-10-19 17:46 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +some other action.
maybe i'm misunderstanding something, but this seems to conflate `.manual` mode with the  manual fallback for the more automated modes. 

is my understanding correct?

2022-10-19 20:42 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
> +For information on breaking vs. non-breaking schema changes, see:
Ah! I saw this comment come in through email and missed the suggested change - that gives me the context that you're talking about the colon.

This is a "me" convention, but I couldn't remember where I picked it up. I went looking in various style guides and can't find any guidance related to this specifically. I think it is probably a holdover from my long-ago web writing days when we used to introduce links at the end of sentences with colons. That does not appear to be the convention in any of my current style guides, so I'm happy to change it.

2022-10-19 20:44 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
>  situation:
Maybe I've been looking at this too long now, but this part feels unnecessarily wordy to me. Rewording slightly.

2022-10-19 21:31 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
> +If the client reset operation cannot complete in recover unsynced changes mode,
Fair point. I've refactored this a bit to break "manual fallback" out into its own section, and clean up the `.manual` mode verbiage so it's not trying to do double duty. I think this should handle the next several comments. Let me know if you think it still needs clarifying after these changes.

2022-10-19 21:36 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
> +  reset handler <ios-manual-client-reset-handler>`. Automatic client recovery
I _think_ I've clarified this sufficiently with restructuring and verbiage tweaks based on your comments below. If you think it still needs tweaking, let me know!

2022-10-20 14:02 UTC, ericjordanmossman commented on examples/ios/Examples/ClientReset.swift
> +            // }
Are commenting lines necessary for the snippet building and testing? If we can do without them, I'd remove them. Just a personal style choice.

2022-10-20 14:06 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +  fall back to discard unsynced changes.
don't this was the case before, but now this client reset method is mentioned in both this section and below in the "Discard Unsynced Changes" section.

2022-10-20 14:12 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +----------------------------
should this be an H3?

2022-10-20 14:18 UTC, mongodben reviewed
looking a lot better! a couple of significant questions still. if my questions are still not clear, would you like to schedule 30 min to chat so that we can get to alignment here?

2022-10-20 14:22 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
>  situation:
i think some explicit call out in the text that there's an "AND" here is important. 

doesn't need to be the wordy "error recovery task that your client app must perform when both of the following occur:", but i think something more than what's there now would help clarify this "AND"

2022-10-20 18:27 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
> +  through to ``.manual``. Choose this mode when you do not want to fall
Sorry, I meant to remove these lines after adding the new section. Totally missed removing these. Thank you for catching!

2022-10-20 18:30 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
> +  fall back to discard unsynced changes.
I think it's relevant in both places, because it attempts both to recover and then discard unsynced changes. That's why I've put it in both places.

2022-10-20 18:31 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
> +----------------------------
Updated!

2022-10-20 18:38 UTC, dacharyc commented on examples/ios/Examples/ClientReset.swift
> +            // }
Yeah, I commented these lines because otherwise I'll need to actually add the class/object to get the code to compile, and I also want to make it very clear that this is just an example and is not intended to be real, runnable code. We generally try to avoid including code that we don't actually want users to run in our examples, because inevitably someone tries to copy and run it and then is unhappy it doesn't work. 

If you think it's important to show a working example to illustrate this, I'll add what is needed to get the code to compile, but my preference in this instance would be to leave it commented to make it clear we don't intend folks to actually run this.

2022-10-20 18:47 UTC, dacharyc commented on source/sdk/swift/sync/handle-sync-errors.txt
>  situation:
Hrm. I'm not super thrilled with this verbiage anyway, so I've made a pass at rewriting this section to more clearly describe the error and potential consequences. What do you think of the updates?

2022-10-20 19:41 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +:ref:`client-resets`.
```suggestion
For more information about what might cause a client reset to occur, go to
:ref:`client-resets`.
```

might also be worth mentioning that this is in the App Services docs

2022-10-20 19:42 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
>  situation:
great improvement!

2022-10-20 19:46 UTC, mongodben commented on source/sdk/swift/sync/handle-sync-errors.txt
> +Device Sync configuration. To handle this case, your app can implement a
```suggestion
Device Sync backend configuration. To handle this case, your app can implement a
```

i think worth specifying talking abt server-side for clarity.

2022-10-20 19:56 UTC, mongodben approved these changes
L.G.T.M!!!!

a couple of nitty suggestions and one broader suggestion about the duplicated docs for `. recoverOrDiscardUnsyncedChanges`, but nothing blocking. 

nice work here!

2022-10-21 16:20 UTC, ericjordanmossman commented on examples/ios/Examples/ClientReset.swift
> +            // }
Nope. I see what you mean. Leave as is.

2022-10-21 16:24 UTC, ericjordanmossman approved these changes

2022-10-21 18:36 UTC, merged