(DOCSP-25565): Update to React Native Landing Page
mongodb/docs-realm pull request #2207
Opened 2022-10-10 20:26 UTC by lindseymoore

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-25565

### Staged Changes (Requires MongoDB Corp SSO)

- [React Native SDK (landing page)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-25565-rn-land/sdk/react-native/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2022-10-11 13:11 UTC, mongodben commented on source/sdk/react-native.txt
> +      create your own working Realm app.
```suggestion
      create your own working app with Realm Database and Device Sync.
```

2022-10-11 13:11 UTC, mongodben commented on source/sdk/react-native.txt
> +      create your own working Realm app.
we don't use the term 'Realm app' anymore

2022-10-11 13:12 UTC, mongodben commented on source/sdk/react-native.txt
> +Use free open-source Realm Database as a local object store on a device.
```suggestion
Use open-source Realm Database as a local object store on a device.
```

2022-10-11 13:15 UTC, mongodben commented on source/sdk/react-native.txt
> +            Use CocoaPods to :ref:`react-native-install` in your
```suggestion
            :ref:`Install React Native <react-native-install>` in your
```

RN doesn't use Cocoapods. 'Use npm' would be more equivalent, but i don't think you need to specify this implementation detail since every JS project uses npm.

2022-10-11 13:16 UTC, mongodben commented on source/sdk/react-native.txt
> +            <react-native-define-a-realm-object-schema>`.
this reads weird. you're not defining the schema using anything react native-specific. 

how about instead: 

```suggestion
            Use JavaScript to :ref:`define an object schema 
            <react-native-define-a-realm-object-schema>`. 
```

2022-10-11 13:18 UTC, mongodben commented on source/sdk/react-native.txt
> +            or you can open an in-memory realm which does not create a file.
i think realm files and in-memory realms are more implementation details than we need here on the landing page

2022-10-11 13:18 UTC, mongodben commented on source/sdk/react-native.txt
> +            Realm Query Language.
```suggestion
            :ref:`Realm Query Language <realm-query-language>`. 
```

2022-10-11 13:19 UTC, mongodben commented on source/sdk/react-native.txt
> +            to watch for changes and perform some logic, such as updating
```suggestion
            to watch for changes and perform logic like updating 
```

2022-10-11 13:20 UTC, mongodben commented on source/sdk/react-native.txt
> +      fully working Realm Expo template application.
```suggestion
      fully-functional Realm Expo template application.
```

nit

2022-10-11 13:22 UTC, mongodben commented on source/sdk/react-native.txt
> +            Development Mode to infer your schema from your data model.
```suggestion
            <realm-sync-get-started>`. Define data access rules or use 
            Development Mode to infer a schema from your client's data model.
```

2022-10-11 13:23 UTC, mongodben commented on source/sdk/react-native.txt
> +            provides access without requiring a login or persisting user data.
i think you can slim this down. lotta info for a landing page. see the flutter page as an example - https://www.mongodb.com/docs/realm/sdk/flutter/

2022-10-11 13:24 UTC, mongodben commented on source/sdk/react-native.txt
> +            synced Realm <react-native-open-close-realm>`.
```suggestion
            :ref:`Configure and open a synced Realm <react-native-open-close-realm>`. 
```

2022-10-11 13:26 UTC, mongodben commented on source/sdk/react-native.txt
> +            to determine what data the synced realm can read and write.
```suggestion
            To determine what data the synced realm can read and write,
            :ref:`subscribe to a query <react-native-sync-subscribe-to-queryable-fields>`.
```

nit: separating the links from being right next to each other. also, generally it's better to have link end of line so reader has full context of sentence by time to click link.

2022-10-11 13:27 UTC, mongodben commented on source/sdk/react-native.txt
> +            deterministically sync changes whenever a network connection is
```suggestion
           sync changes whenever a network connection is 
```

2022-10-11 13:29 UTC, mongodben commented on source/sdk/react-native.txt
> +            const queryFilter = animals.filtered("name == cheetah");
this is not an example of querying mongodb atlas with React Native SDK. this is an example of querying local Realm DB.

for examples of querying MongoDB Atlas, refer to https://www.mongodb.com/docs/realm/sdk/react-native/examples/query-mongodb/

2022-10-11 13:33 UTC, mongodben requested changes
great start! 

some little changes noted in comments.

one very important section that you should add is another tab for [Realm React](https://www.mongodb.com/docs/realm/sdk/react-native/use-realm-react/). for reference on how to structure, checkout the SwiftUI tab on the [Swift SDK landing page](https://www.mongodb.com/docs/realm/sdk/swift/).

2022-10-13 17:54 UTC, mongodben commented on source/sdk/react-native.txt
> +            :ref:`Realm Query Language <realm-query-language>`.
this is a lot of links and i think is more detail than necessary here. how bout smthn like: 

```suggestion
            You can create, read, update, and delete objects from the realm.
            
            For more information, see :ref:`Read & Write Data
            <react-native-read-and-write-data>` and :ref:`Query Data <react-native-query-data>.
```

2022-10-13 17:56 UTC, mongodben commented on source/sdk/react-native.txt
> +            const credentials = Realm.Credentials.jwt(jwt);
```suggestion
            const credentials = Realm.Credentials.jwt(jwt);
            const user = await app.logIn(credentials);
```

2022-10-13 17:57 UTC, mongodben commented on source/sdk/react-native.txt
> +         Learn more about :ref:`Realm React here <react-native-use-realm-react>`.
```suggestion
         For more information, see :ref:`Realm React <react-native-use-realm-react>`.
```

2022-10-13 17:57 UTC, mongodben commented on source/sdk/react-native.txt
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
```

2022-10-13 18:03 UTC, mongodben commented on source/sdk/react-native.txt
> +         manange the state of wrapped components.
i think as it was, it was providing too much implementation detail which wouldn't mean much to the reader who's learning from this landing page. tried to slim the content down here; 

```suggestion
         Realm React is an npm package that provides an easy-to-use API to
         perform common Realm operations in your React Native app,
         such as querying or writing to  a realm and listening to realm objects.

         Realm React includes React context, providers, hooks, for working with Realm.
         Use Realm React to manage a Realm Database, Atlas App Services,
         and Atlas Device Sync.
```

2022-10-13 18:04 UTC, mongodben commented on source/sdk/react-native.txt
> +      Explore generated reference docs for the React Native APIs.
```suggestion
      Explore generated reference docs for the React Native SDK.
```

2022-10-13 18:05 UTC, mongodben commented on source/sdk/react-native.txt
> +      fully functional Realm Expo template application.
```suggestion
      Expo template application with Realm.
```

2022-10-13 18:05 UTC, mongodben commented on source/sdk/react-native.txt
> +
pls only 1 blank line at EOF

2022-10-13 18:06 UTC, mongodben commented on source/sdk/react-native.txt
> +      :icon: /images/icons/react_native_sdk.svg
can you add the icon for Expo here, not React Native? https://expo.dev/

2022-10-13 18:08 UTC, mongodben commented on source/sdk/react-native.txt
> +   :columns: 3
can you either add a third card or make this only 2 column? 

i don't have any particular idea what the third card would be, so unless you have something, making just 2 columns is prob the easiest/best move.

2022-10-13 18:10 UTC, mongodben reviewed
nice improvements, back to you! 

one higher level thing that i think this could do differently is reduce the number of in-line links. they can be quite overwhelming ot a reader, especially someone who's new to the product. 

see the web sdk landing page for example of putting links at the end  section - https://www.mongodb.com/docs/realm/web/

2022-10-18 14:07 UTC, mongomoe commented on source/sdk/react-native.txt
> +      Expo template application with Realm.
Can we also mention that the Expo QuickStart uses Realm React?

2022-10-18 14:08 UTC, mongomoe commented on source/sdk/react-native.txt
> +      Build and deploy a React Native application quickly using a
```suggestion
      Build and deploy a React Native application quickly using an
```
Typo

2022-10-18 14:13 UTC, mongomoe reviewed
A few suggestions, but this is close to LGTM

2022-10-18 14:20 UTC, mongodben commented on source/sdk/react-native.txt
> +            The APIs to read and write data from a realm are the same
yes, but `APIs` is plural.

2022-10-18 15:40 UTC, mongomoe commented on source/sdk/react-native.txt
> +            Queryable Fields <react-native-sync-subscribe-to-queryable-fields>`.
I'll LGTM it, so I'm not holding this up - but I still have the suggestion to have that queryable fields link in the sentence itself. I think you can do something similar for the Open & Close link too. Maybe:

```
:ref:`Opening a Synced Realm <react-native-open-close-realm>` allows you to access data across devices. To determine what data a synced realm can read and write, :ref:`subscribe to a query <react-native-sync-subscribe-to-queryable-fields>`.
```

To clarify, you don't have to make the ref inline for the sake of being inline, I just think it looks better to have the ref inline if you're using the title phrase verbatim/almost verbatim (like in the case of "To determine what data a synced realm can read and write, subscribe to a query. For more information, see ... Queryable Fields."

2022-10-18 16:59 UTC, mongodben approved these changes

2022-10-18 16:59 UTC, merged