(DOCSP-24570): Flutter Client Reset docs
mongodb/docs-realm pull request #2266
Opened 2022-11-04 21:18 UTC by mongodben

## Pull Request Info

Document client reset for Realm Flutter SDK

### Jira

- https://jira.mongodb.org/browse/DOCSP-24570

### Staged Changes (Requires MongoDB Corp SSO)

- [Handle Sync Errors (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-24570/sdk/flutter/sync/handle-sync-errors/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2022-11-08 20:35 UTC, dacharyc requested changes
Great start! This is looking really good. I've got a handful of questions and nits, but only a couple of typo spots that are must-fix.

2022-11-08 20:35 UTC, dacharyc commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +:ref:`Client Recovery <enable-or-disable-recovery-mode>` in the App Services documentation.
You may already have this planned, but I just followed this link and noticed just above this section in the App Services docs is a tabbed list of client reset docs across the SDKs. Presumably you'll be putting up an App Services PR to add the Flutter SDK docs to those tabs after this PR is merged.

2022-11-08 20:35 UTC, dacharyc commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +Recover or Discard Unsynced Changes Mode
This is purely a styling nit, but I noticed on the staged page that this H size & styling looks a bit weird above the bolded text in the opening line below. I might suggest we remove the bolding below since it's just duplicating this heading and it makes the heading look - odd.

2022-11-08 20:35 UTC, dacharyc commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +**Recover unsyced changes mode** attempts to recover all unsynced local changes automatically
Same note as above - if you're so inclined, I think removing the bold styling here would make this H level look less odd on the page.

```suggestion
Recover unsyced changes mode attempts to recover all unsynced local changes automatically
```

2022-11-08 20:35 UTC, dacharyc commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +it is used if you do not specify an alternative client reset mode.
Do we need to say "it is used if you do not specify an alternative" here? Isn't that what default means?

2022-11-08 20:35 UTC, dacharyc commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +Instead, it  falls back to manually recovery changes.
```suggestion
Instead, it  falls back to manually recover changes.
```

2022-11-08 20:35 UTC, dacharyc commented on source/examples/generated/flutter/client_reset_test.snippet.manual-fallback.dart
> +  onManualResetFallback: (clientResetError) {
Spacing looks a bit weird here.

2022-11-08 20:39 UTC, mongodben commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +:ref:`Client Recovery <enable-or-disable-recovery-mode>` in the App Services documentation.
thanks for spotting this. i didn't have anything planned for that. will add an app services PR!

2022-11-08 20:59 UTC, mongodben commented on source/examples/generated/flutter/client_reset_test.snippet.manual-fallback.dart
> +  onManualResetFallback: (clientResetError) {
yeah, but that's the dart linter 🤷

2022-11-08 21:01 UTC, mongodben commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +Recover or Discard Unsynced Changes Mode
sure. that's a new snooty styling thing. but the bold doesn't add much value here so let's drop.

2022-11-08 21:05 UTC, mongodben commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +it is used if you do not specify an alternative client reset mode.
i wanted to underscore that's it's automatically applied. adding word 'automatically' to sentence to clarify this.

want to make clear that even if you don't specify a handler, this is used

2022-11-08 22:15 UTC, dacharyc commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +it is used if you do not specify an alternative client reset mode.
Ok, that makes sense. This is totally a nit and is subjective, but this reads a bit awkwardly to me. I wonder if we can wordsmith a little? Maybe something like:

> If you do not specify a client reset mode, client reset behavior defaults to recover or discard unsynced changes.

2022-11-08 22:16 UTC, dacharyc approved these changes
The only thing left is a subjective nit, so feel free to address or ignore as you wish. Nice work!

2022-11-09 14:31 UTC, mongodben commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +it is used if you do not specify an alternative client reset mode.
i like the change, adding!

2022-11-09 14:35 UTC, mongodben commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +it is used if you do not specify an alternative client reset mode.
moved stuff around a bit for clarity and flow

2022-11-09 15:03 UTC, merged

2022-11-09 18:36 UTC, desistefanova reviewed
Looks good, just a few comments.

2022-11-09 18:36 UTC, desistefanova commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +Do not use recover or discard unsynced changes mode if your application
```suggestion
Do not use discard unsynced changes mode if your application
```

2022-11-09 18:36 UTC, desistefanova commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +  recovery and the discard strategy have failed. You implement this callback to
```suggestion
 the discard strategy have failed. You implement this callback to
```

2022-11-09 18:36 UTC, desistefanova commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +  which the SDK invokes if *and only if* the automatic reset completes successfully.
```suggestion
which the SDK invokes if *and only if* the automatic recovery completes successfully.
```
Maybe it will be better to be more specific here. What do you think? I will not put the same comment on the rest of the places (onAfterDiscard of RecoverOrDiscardUnsynced, onAfterReset of RecoverUnsynced, onAfterReset of DiscardUnsynced). If you @mongodben  decide that it is valuable to say recover or respectively discard instead of just reset, you can do it also at the other places.

2022-11-09 18:36 UTC, desistefanova commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +and downloading relevant data from the server.
I'm not exactly sure if the user is not required to restart the app or reopen the realm in order to download the data. Maybe @nirinchev can share more details here.

2022-11-09 18:36 UTC, desistefanova commented on source/examples/generated/flutter/client_reset_test.snippet.manual-fallback.dart
> +        // the Realm and reinitialize the current page.
```suggestion
        // Navigate the user back to the main page or reopen the
        // the Realm and reinitialize the current page.
```

2022-11-09 18:36 UTC, desistefanova commented on source/sdk/flutter/sync/handle-sync-errors.txt
> +and downloading relevant data from the server.
I saw that you have explained that in the comment in the sample. Maybe it has to be something similar here.