JS Models
mongodb/docs-realm pull request #2281
Opened 2022-11-09 14:08 UTC by mongomoe

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-22493 
- https://jira.mongodb.org/browse/DOCSP-22494

### Staged Changes (Requires MongoDB Corp SSO)

- [Define a Realm Object Schema - Node.js SDK # Define Realm Object Types with JavaScript Classes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/models-js-docs/sdk/node/examples/define-a-realm-object-model/#define-realm-object-types-with-javascript-classes)
- [Define a Realm Object Schema - React Native SDK # Define Realm Object Types with JavaScript Classes](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/models-js-docs/sdk/node/examples/define-a-realm-object-model/#define-realm-object-types-with-javascript-classes)
- [Use Realm React # Setup](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/models-js-docs/sdk/react-native/use-realm-react/#setup)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2022-11-09 14:46 UTC, mongomoe commented on examples/node/Examples/authenticate.js
> +  test.skip("server api key login", async () => {
Fyi, ignore this test.skip. I've actually fixed this test in this PR: https://github.com/mongodb/docs-realm/pull/2264

2022-11-09 14:46 UTC, mongomoe commented on examples/node/Examples/authenticate.ts
> +  test.skip("server api key login", async () => {
Fyi, ignore this test.skip. I've actually fixed this test in this PR: https://github.com/mongodb/docs-realm/pull/2264

2022-11-21 21:09 UTC, kneth reviewed
LGTM

I will suggest that you include an example where you use a function as default value. It can be a date property, and the value is set to the current time (`timestamp = new Date()`).

2022-11-22 12:08 UTC, takameyer requested changes
As similar as the documents are between `node` and React Native, I think it's important to document how they are different, by showing the React Native examples in the `@realm/react` context.

Also the TypeScript based models are the future of the `realm-js` project.  This should be the first document someone sees when setting up their models, and the non-typescript should be a sub-section/document.  I think the TypeScript based models document should have all the sections from the other document, but with the examples using the TS-model based syntax.

2022-11-22 12:08 UTC, takameyer commented on source/sdk/react-native/examples/define-a-realm-object-model.txt
>     .. literalinclude:: /examples/generated/node/open-and-close-a-local-realm.snippet.open-local-realm-with-car-schema.js
It's more useful in a React Native context, to show that one uses the model to perform the following operations:
* `createRealmContext`
* `useQuery(Item)` and `useObject(Item, primaryKey)`
* `realm.write(() => return new Item(realm, {prop1, prop2})`

I do not recommend anyone call `realm.open` when using `@realm/react` as we handle that logic in the `RealmProvider` returned from `createRealmContext`

2022-11-22 16:23 UTC, mongomoe commented on source/examples/generated/node/define-a-realm-object-schema.snippet.define-a-realm-object-schema-define-js-classes.ts
> +  _id!: Realm.BSON.ObjectId;
Rewrote this like the example you sent me:
```
  _id: Realm.BSON.ObjectId = new Realm.BSON.ObjectId();
```

2022-11-22 16:26 UTC, mongomoe commented on source/examples/generated/node/define-a-realm-object-schema.snippet.map-field-using-ts-first-model.ts
> +      make!: string;
Resolving this per our discussion. These examples will be added as part of: https://jira.mongodb.org/browse/DOCSP-23395

2022-11-22 16:27 UTC, mongomoe commented on source/sdk/node/examples/define-a-realm-object-model-using-ts.txt
> +Decorators
Added to the Install page based on our discussion: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/models-js-docs/sdk/react-native/install/

2022-11-22 16:28 UTC, mongomoe commented on source/sdk/react-native/examples/define-a-realm-object-model.txt
>     .. literalinclude:: /examples/generated/node/open-and-close-a-local-realm.snippet.open-local-realm-with-car-schema.js
Resolving this as part of our discussion. Realm React examples will be added as part of: https://jira.mongodb.org/browse/DOCSP-23395

2022-11-22 22:09 UTC, mongomoe commented on source/sdk/react-native/examples.txt
> +   Define a Realm Object Model Using TypeScript </sdk/react-native/examples/define-a-realm-object-model-using-ts>
```suggestion
```

2022-11-22 22:09 UTC, mongomoe commented on source/sdk/node/examples.txt
> +- :doc:`Define a Realm Object Model Using TypeScript </sdk/node/examples/define-a-realm-object-model-using-ts>`
```suggestion
```

2022-11-22 22:09 UTC, mongomoe commented on source/sdk/node/examples.txt
> +   Define a Realm Object Model Using TypeScript </sdk/node/examples/define-a-realm-object-model-using-ts>
```suggestion
```

2022-11-23 17:59 UTC, krollins-mdb reviewed
Nice work, @mongomoe! I have some suggestions, mostly small things. Adding this TS info will be great for readers.

2022-11-23 17:59 UTC, krollins-mdb commented on source/sdk/node/examples/define-a-realm-object-model.txt
> +This plugin supports standard TypeScript types wherever possible to make
"This plugin" is a bit vague. Unless readers are already familiar with it, they won't know that we support TypeScript Types only through the Realm Babel Plugin. It's mentioned in the note above, but that's easily missed. I recommend spelling it out here again.

```suggestion
The Realm Babel Plugin supports standard TypeScript types wherever possible to make
```

2022-11-23 17:59 UTC, krollins-mdb commented on source/sdk/node/examples/define-a-realm-object-model.txt
> +and ``float`` are all represented by ``number`` in TypeScript). In these cases,
Typo: standalone closing parenthesis.
```suggestion
and ``float`` are all represented by ``number`` in TypeScript. In these cases,
```

2022-11-23 17:59 UTC, krollins-mdb commented on source/sdk/node/examples/define-a-realm-object-model.txt
> +The top-level Realm namespace and ``Realm.Types`` exports various types, such as
Count and verb disagreement: Realm namespace and ``Realm.Types`` are two things, so the verb should agree with a plural noun form.
```suggestion
The top-level Realm namespace and ``Realm.Types`` export various types, such as
```

2022-11-23 17:59 UTC, krollins-mdb commented on source/sdk/node/examples/define-a-realm-object-model.txt
> +      You can declare a Realm Object Model using TypeScript property types
Are "Realm Object Model" and "Realm Object Schema" the same thing? We seem to use "schema" far more frequently in the Node and React Native SDK docs. If they're equivalent, I suggest rewriting all instances of "object model" to "object schema".

This page in particular has a Car schema with "model" as a property, so that could be a bit confusing - readers could conflate the two things.

2022-11-23 17:59 UTC, krollins-mdb commented on source/sdk/node/install.txt
> +You can declare a Realm Object Model using TypeScript property types
As noted on the realm object model page, we should consider using "schema" instead of "model". If the two are equivalent.

2022-11-23 17:59 UTC, krollins-mdb commented on source/sdk/node/examples/define-a-realm-object-model.txt
> +      You can declare a Realm Object Model using TypeScript property types
Ha! I just noticed in other files you purposefully changed from "Schema" to "Model". Disregard this suggestion and the following ones about model -> schema if we're in fact moving the other direction.

2022-11-23 17:59 UTC, krollins-mdb commented on source/sdk/react-native/install.txt
> +TypeScript property types declarations on classes. The Realm JS SDK will derive
I asked this in the Node.js SDK content, and I think it's valuable here too. Do we refer to the "Realm JS SDK" elsewhere? In this instance, shouldn't we say "React Native SDK"? I know Node and React Native use the same source, but we present them as two different SDKs.
```suggestion
TypeScript property types declarations on classes. The Realm React Native SDK will derive
```

2022-11-23 17:59 UTC, krollins-mdb commented on source/sdk/react-native/install.txt
> +the schema at runtime from the types declared in your TS source files. This
We haven't abbreviated TypeScript to TS before this. I recommend spelling it out or using `.ts` here.
```suggestion
the schema at runtime from the types declared in your `.ts` source files. This
```

2022-11-23 17:59 UTC, krollins-mdb commented on source/sdk/react-native/install.txt
> +-  the :npm:`@babel/plugin-proposal-decorators <package/@babel/plugin-proposal-decorators>`
We generally don't use sentence fragments in lists to complete an introductory sentence. It's harder to read than being more explicit.
```suggestion
To implicitly declare a Realm Object Model, follow the steps below to install and configure the :npm:`Realm Babel Plugin <package/@realm/babel-plugin>` and the :npm:`@babel/plugin-proposal-decorators <package/@babel/plugin-proposal-decorators>`.
```
"Realm Object Model" should be "Realm Object Schema" if we're going with the model -> schema suggestion.

2022-11-23 17:59 UTC, krollins-mdb commented on source/sdk/react-native/install.txt
> +      Add the following to your ``babel.config.js`` file to apply the `plugins <https://babeljs.io/docs/en/plugins>`_
```suggestion
      Add the following to your ``babel.config.js`` file to apply the `plugins <https://babeljs.io/docs/en/plugins>`_:
```

2022-11-23 17:59 UTC, krollins-mdb commented on source/sdk/react-native/install.txt
> +      Enable experimental decorators in your `tsconfig.json <https://www.typescriptlang.org/docs/handbook/tsconfig-json.html>`_ within your ``compilerOptions``:
```suggestion
      Enable experimental decorators in your `tsconfig.json <https://www.typescriptlang.org/docs/handbook/tsconfig-json.html>`_ within your ``compilerOptions`` file:
```

2022-11-23 17:59 UTC, krollins-mdb commented on source/sdk/react-native/install.txt
> +      If you're using TypeScript, you must restart the package cache to work with the newly applied plugin in your app. For most React Native applications, you can run the command:
```suggestion
      If you're using TypeScript, you must restart the package cache to work with the newly-applied plugin in your app. For most React Native applications, you can run the command:
```

2023-01-03 15:53 UTC, closed without merging