Minor C++ example readme updates
mongodb/docs-realm pull request #2357
Opened 2022-12-02 20:48 UTC by krollins-mdb

## Pull Request Info

This PR doesn't have its own Jira, as I was working through the example repo to learn. I noticed some minor ways we can improve the readme, so this is kind of a follow-up.

### Jira

- https://jira.mongodb.org/browse/DOCSP-26490

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2022-12-02 20:50 UTC, krollins-mdb commented on examples/cpp/README.md
> +To verify your new test file works, [build the project](https://github.com/mongodb/docs-realm/tree/master/examples/cpp#build-the-project) again and then [run the tests](https://github.com/mongodb/doc
Note for reviewer: I know we tend to avoid "wiki" style links, but the process for this is exactly the same as what we've already defined. I think it makes sense to link back to those sections if readers need a reminder of what to do.

2022-12-02 20:58 UTC, krollins-mdb commented on examples/cpp/README.md
> +If you have previously run `CMake` for this project, you may see this error:
I removed the "Note:" here because lines 166-175 are related content. Because GitHub doesn't have a good way of handling admonitions, it may not be clear that this content is related but 177 and further on isn't. (You can have a successful build and not see the error.)

2022-12-02 21:34 UTC, dacharyc requested changes
Nice improvements - thanks! Back to you with a couple of Qs and requests.

2022-12-02 21:34 UTC, dacharyc commented on examples/cpp/README.md
> +To change the version of the SDK your build, change the value
Not sure if this was a typo of "To change the version of the SDK you build" or if it's "in your build" so I picked one.

```suggestion
To change the version of the SDK in your build, change the value
```

I do think it's worth noting, though, that if you commit these changes, it changes the Realm SDK version for anyone using this project. That's why I went with "we use in the build" here. I'm fine with not using first person here if you want to otherwise indicate that changing this and committing it means the project builds with the new version.

2022-12-02 21:34 UTC, dacharyc commented on examples/cpp/README.md
> +To verify your new test file works, [build the project](https://github.com/mongodb/docs-realm/tree/master/examples/cpp#build-the-project) again and then [run the tests](https://github.com/mongodb/doc
Could we wrap this line, please? It's pretty long.

2022-12-02 21:34 UTC, dacharyc commented on examples/cpp/README.md
> +You can either run `cmake ../ -G Xcode` from a clean build directory, or remove the
Bush pointed out another option here, which is to just make another directory in the `build` directory for the Xcode build. i.e. `/build/xcode`. Curious if you think it's worth adding. If you do, we might want to remove the specific `/build` in ln 177 below, and just say "build directory."

2022-12-05 14:55 UTC, krollins-mdb commented on examples/cpp/README.md
> +To change the version of the SDK your build, change the value
Ooh, I wasn't aware that the Realm SDK version would change for people using this project. The original makes more sense now. Thanks for clarifying. I'll change this back to the original.

2022-12-05 14:59 UTC, krollins-mdb commented on examples/cpp/README.md
> +You can either run `cmake ../ -G Xcode` from a clean build directory, or remove the
I think that's worth adding. Seems like a better approach.

2022-12-05 15:30 UTC, dacharyc approved these changes
Nice, looks good! Good improvements 👍

2022-12-05 15:52 UTC, merged