Adding maui and links
mongodb/docs-realm pull request #2367
Opened 2022-12-05 19:47 UTC by MongoCaleb

## Pull Request Info

### Jira

https://jira.mongodb.org/browse/DOCSP-23233

### Staged Changes

- [Encrypting Files](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/maui/sdk/dotnet/realm-files/encrypt-a-realm)
- [Compatability](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/maui/sdk/dotnet/compatibility/) 
- [Install](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/maui/sdk/dotnet/install/)

2022-12-05 21:21 UTC, dacharyc approved these changes
LGTM 👍

2022-12-07 08:59 UTC, papafe requested changes
I think it looks good apart from some small details!

2022-12-07 08:59 UTC, papafe commented on source/sdk/dotnet/compatibility.txt
> +       | MAUI Blazor apps require iOS 14 or later.
We actually don't support Blazor, so we'd better remove it from compatibility list from all the platforms

2022-12-07 08:59 UTC, papafe commented on source/sdk/dotnet/model-data/define-object-model.txt
> +When building a .NET app using the
I think I would spell out "MAUI/Xamarin"  instead of generic .NET here, because the considerations for MVVM are valid for those two frameworks in the end.

2022-12-07 08:59 UTC, papafe commented on examples/dotnet/README.md
> +   **NOTE:** You might need to update XCode -- the .NET code requires a specific version of the
I would also spell MAUI/Xamarin here as noted under

2022-12-07 18:36 UTC, merged