(DOCSP-26982): Dictionary Unit Tests + Bluehawked Snippets
mongodb/docs-realm pull request #2401
Opened 2022-12-14 08:54 UTC by mongomoe

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-26982

### Staged Changes

- [Dictionaries - React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [ ] Create Jira ticket for corresponding docs-app-services update(s), if any
- [ ] Checked/updated Admin API
- [ ] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2022-12-16 16:08 UTC, mongodben commented on examples/react-native/__tests__/ts/Models/HomeOwner.ts
> +}
can you add bit of explanation about why you're extending `Realm.Dictionary` here? 

since only relevant for the TS example, maybe this could be a comment.

2022-12-16 16:09 UTC, mongodben commented on source/sdk/react-native/realm-database/schemas/dictionaries.txt
> +<Web/JavaScript/Reference/Operators/new>` operator within a :ref:`write
i don't think this link is necessary

2022-12-16 16:12 UTC, mongodben commented on examples/react-native/__tests__/js/realm-database/schemas/dictionary-test.jsx
> +      const SubmitHomeOwner = () => {
not sure about RN conventions, but usual JS convention is to lowercase the first letter of a function. if there's not different RN i'd recommend doing that here.

2022-12-16 16:13 UTC, mongodben commented on examples/react-native/__tests__/js/realm-database/schemas/dictionary-test.jsx
> +      const SubmitHomeOwner = () => {
```suggestion
      const submitHomeOwner = () => {
```

2022-12-16 16:14 UTC, mongodben commented on examples/react-native/__tests__/js/realm-database/schemas/dictionary-test.jsx
> +          <Button title='Submit Home Owner' testID='submitHomeOwnerBtn' onPress={SubmitHomeOwner} />
```suggestion
          <Button title='Submit Home Owner' testID='submitHomeOwnerBtn' onPress={submitHomeOwner} />
```

alignment w prev comment

2022-12-16 16:16 UTC, mongodben commented on source/sdk/react-native/realm-database/schemas/dictionaries.txt
> +         :emphasize-lines: 2, 4, 8, 12, 16
i think the emphasize lines are off. ditto JS example

<img width="894" alt="Screen Shot 2022-12-16 at 11 16 01 AM" src="https://user-images.githubusercontent.com/90647379/208141874-b8255009-6377-4584-930b-49772b1f4eb1.png">

2022-12-16 16:21 UTC, mongodben commented on examples/react-native/__tests__/js/realm-database/schemas/dictionary-test.jsx
> +    };
suggestion: i find this example difficult to track b/c there's the 3 filtered methods and the 3 usages of it below. 

could you create different components for each query/JSX pairing?

2022-12-16 16:24 UTC, mongodben commented on source/sdk/react-native/realm-database/schemas/dictionaries.txt
> +- Add an `onPress <https://reactnative.dev/docs/handling-touches>`__ event on the submit button that calls ``SubmitHomeOwner()``
on a higher level, i wonder if these descriptions of the component are necessary.

personally, i think the examples are clear and self contained enough that what's happening is evident.

if there's anything in the explanation that requires additional explanation, i think it can be a comment.

curious your perspective here.

2022-12-16 16:26 UTC, mongodben reviewed
back to you! nice work. couple small fixes.

and then some larger, more open non-blocking questions.

2023-01-03 20:34 UTC, mongomoe commented on examples/react-native/__tests__/js/realm-database/schemas/dictionary-test.jsx
> +      const SubmitHomeOwner = () => {
React Components should be capitalized. See: https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized

2023-01-03 20:42 UTC, mongomoe commented on examples/react-native/__tests__/js/realm-database/schemas/dictionary-test.jsx
> +      const SubmitHomeOwner = () => {
Fixed locally 👍

2023-01-03 20:42 UTC, mongomoe commented on examples/react-native/__tests__/js/realm-database/schemas/dictionary-test.jsx
> +          <Button title='Submit Home Owner' testID='submitHomeOwnerBtn' onPress={SubmitHomeOwner} />
Fixed locally 👍

2023-01-03 20:50 UTC, mongomoe commented on source/sdk/react-native/realm-database/schemas/dictionaries.txt
> +         :emphasize-lines: 2, 4, 8, 12, 16
Fixed 👍

2023-01-03 20:50 UTC, mongomoe commented on examples/react-native/__tests__/js/realm-database/schemas/dictionary-test.jsx
> +    };
Decided not to take this suggestion because:
1. That would cause overhead/additional work
2. It breaks the standard in all the examples of one example per subsection
3. I fixed the line emphasis problem that [you pointed out](https://github.com/mongodb/docs-realm/pull/2401#discussion_r1050926677), so hopefully that makes it clearer which lines are doing the filtering.

2023-01-03 20:55 UTC, mongomoe commented on source/sdk/react-native/realm-database/schemas/dictionaries.txt
> +- Add an `onPress <https://reactnative.dev/docs/handling-touches>`__ event on the submit button that calls ``SubmitHomeOwner()``
Personally, I like the explanation of the components. They all roughly follow the same structure (throughout the entirety of the new React Native/@realm/react docs:

```
<Subsection Title>
--------------------
<How to perform the subsection's objective with realm-js, what method to use, etc>

Example
~~~~~~~
In the following ``<Component>`` example, we perform <subsection objective>
* <Bullet points outlining how the component is structured, how it uses @realm/react hooks, and what is rendered>
* // ....
```

I like the consistency across pages, and I like that we explain the Realm-JS fundamental part of the subsection objective, before diving into the specific React Native component example and how it uses @realm/react to accomplish the subsection objective.

2023-01-03 21:25 UTC, mongodben commented on examples/react-native/__tests__/ts/Models/HomeOwner.ts
> +}
this was not addressed

2023-01-03 21:27 UTC, mongodben commented on source/sdk/react-native/realm-database/schemas/dictionaries.txt
> +- Add an `onPress <https://reactnative.dev/docs/handling-touches>`__ event on the submit button that calls ``SubmitHomeOwner()``
ok, ty for explaining

2023-01-03 21:30 UTC, mongodben approved these changes
lgtm.

1 small comment not addressed that would be good to address before merge. but don't think it needs to block the lgtm.

2023-01-03 22:12 UTC, merged

2023-02-09 08:20 UTC, takameyer requested changes
@mongodben @krollins-mdb Have some suggestions.

2023-02-09 08:20 UTC, takameyer commented on source/sdk/react-native/realm-database/schemas/dictionaries.txt
>  --------
It could be useful to show an example of what a dictionary structure looks like in the overview section.  Then the reader can decide if they want to read further.

2023-02-09 08:20 UTC, takameyer commented on source/sdk/react-native/realm-database/schemas/dictionaries.txt
> +To create an object with a dictionary value, use the :mdn:`new
I think this sentence is a little unclear.  Perhaps just going to an example would be less confusing.

2023-02-09 08:20 UTC, takameyer commented on source/sdk/react-native/realm-database/schemas/dictionaries.txt
> +.. tabs-realm-languages::
These tabs are identical.  May be better to just show one example in this case

2023-02-09 08:20 UTC, takameyer commented on examples/react-native/__tests__/ts/realm-database/schemas/dictionary-test.tsx
> +        home: {address: '2 jefferson lane', yearRenovated: 1994, color: 'blue'},
I really like seeing the structure of how a dictionary looks here.  Unfortunately, this is not in the documentation.  The docs explain a lot of "how" to do things, but not for what it's good for.  Just my two cents.  Perhaps logging the dictionary in the examples to show what the results of those operations would be.