wip - mixed tests
mongodb/docs-realm pull request #2411
Opened 2022-12-15 18:12 UTC by mongomoe

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-NNNNN

### Staged Changes

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [ ] Create Jira ticket for corresponding docs-app-services update(s), if any
- [ ] Checked/updated Admin API
- [ ] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2022-12-16 15:33 UTC, mongodben commented on examples/react-native/__tests__/js/realm-database/schemas/mixed-tests.jsx
> +      useEffect(() => {
do you think it's worth adding a note about what the useEffect hook is doing? 

like i (and i imagine most react devs) would understand that you're adding the cats to the realm when the component mounts, but wonder if it might be adding a comment before the line with smthn like:

```suggestion
      // Add data to the Realm when CreateCatsInput component mounts
      useEffect(() => {
```

2022-12-16 15:38 UTC, mongodben commented on examples/react-native/__tests__/js/realm-database/schemas/mixed-tests.jsx
> +    // Test that 5 Cat Items have been added to the UI, and 5 matching Cat objects have been created in the assertionRealm (since there was already 1 cat object 'clover' created in the beforeEach) +
nit

```suggestion
    // Test that 5 Cat Items have been added to the UI,
    // and 5 matching Cat objects have been created in the assertionRealm
    // (since there was already 1 cat object 'clover' created in the beforeEach)
    // + the 4 new Cats
```

2022-12-16 15:42 UTC, mongodben commented on examples/react-native/__tests__/ts/realm-database/schemas/mixed-test.tsx
> +import React, {useEffect} from 'react';
all comments/suggestions on `examples/react-native/__tests__/js/realm-database/schemas/mixed-tests.jsx` also apply to this file

2022-12-16 15:43 UTC, mongodben commented on examples/react-native/testSetup.js
> +  // log: jest.fn(),
can you just remove, or leave a comment abt why commented out?

2022-12-16 15:53 UTC, mongodben commented on source/sdk/react-native/realm-database/schemas/mixed.txt
> +collection. Properties using the mixed data type can also hold null values.
i think outside of scope of this PR, but would be good to have example of using mixed type with a collection.

2022-12-16 15:59 UTC, mongodben reviewed
nice work! i like the way you handled the @realm/react-ification of the examples. 

couple small suggestions/nits throughout.

and then some larger comments about how the data type is described that fall outside of the scope of this PR, but should probably be addressed. could be good work for @krollins-mdb to learn more about the SDK.

2023-01-03 21:25 UTC, mongomoe commented on examples/react-native/__tests__/js/realm-database/schemas/mixed-tests.jsx
> +      const cats = useQuery(Cat);
1. Technically since the 'assertionRealm' is using the same config and we write to it in the 'beforeEach' block the 'useQuery(Cat)' has 1 cat in it when the component first mounts. 
2. Yes and the component would re-render, displaying the new cats (without having to listen for changes) 

I thought about including more info about this, but I think since so many examples throughout these docs will show writing to data in a realm, and the component re-rendering automatically, it would be repeated too many times. Instead, I'm going to describe this in depth in (maybe) the 'Write Transactions' (or alternatively an explainer page of @realm/react) page in a future PR.

2023-01-03 21:30 UTC, mongomoe commented on examples/react-native/__tests__/js/realm-database/schemas/mixed-tests.jsx
> +    // Test that 5 Cat Items have been added to the UI, and 5 matching Cat objects have been created in the assertionRealm (since there was already 1 cat object 'clover' created in the beforeEach) +
Fixed locally

2023-01-03 21:31 UTC, mongomoe commented on examples/react-native/testSetup.js
> +  // log: jest.fn(),
Accident

2023-01-03 21:35 UTC, mongomoe commented on source/sdk/react-native/realm-database/schemas/mixed.txt
> +collection. Properties using the mixed data type can also hold null values.
Interesting idea, I'm not opposed to it, but don't necessarily want to bulk up this page. Maybe a note saying for additional examples, see <link to repo with these examples>?

2023-01-03 21:38 UTC, mongomoe commented on source/sdk/react-native/realm-database/schemas/mixed.txt
I don't think this is necessarily out of scope of this PR. 

* I've made this part of the description rather than as a note
* The mixed type cannot be optional and must always have a value (even if that value is just null). Does that make sense to you?

2023-01-03 21:40 UTC, mongomoe commented on source/sdk/react-native/realm-database/schemas/mixed.txt
Actually, I've updated the text to:

```
The mixed data type is indexable, but you can't use it as a primary key.

Properties using the mixed data type can also hold null values. You can't
declare a Mixed property as optional.

```

Let me know if that works.

2023-01-04 15:03 UTC, mongodben commented on examples/react-native/__tests__/js/realm-database/schemas/mixed-tests.jsx
> +        // Add data to the Realm when the component mounts
```suggestion
      // Add data to the Realm when the component mounts
      useEffect(() => {
```

nit: think it'd be clearer if this comment before the hook.

2023-01-04 15:07 UTC, mongodben commented on examples/react-native/__tests__/ts/realm-database/schemas/mixed-test.tsx
> +import React, {useEffect} from 'react';
still applies for remaining nit https://github.com/mongodb/docs-realm/pull/2411/files#r1061575928

2023-01-04 15:09 UTC, mongodben commented on source/sdk/react-native/realm-database/schemas/mixed.txt
> +collection. Properties using the mixed data type can also hold null values.
what would that note point to?

2023-01-04 15:11 UTC, mongodben commented on source/sdk/react-native/realm-database/schemas/mixed.txt
> +- Within the anonymous function, we create four different ``Cat`` objects by using the new operator to create a new realm object within a write transaction. Each of the ``Cat`` objects uses a differe
```suggestion
- Within the anonymous function, we create four different ``Cat`` objects by using the ``new`` operator to create a new realm object within a write transaction. Each of the ``Cat`` objects uses a different data type for the ``birthDate`` property. 
```

2023-01-04 15:12 UTC, mongodben commented on source/sdk/react-native/realm-database/schemas/mixed.txt
> +- Within the anonymous function, we create four different ``Cat`` objects by using the new operator to create a new realm object within a write transaction. Each of the ``Cat`` objects uses a differe
alternatively, on a different page, i recall you linking to the MDN page for the `new` operator.

i said didn't think it was necessary there, but you might want to do it here as well for consistency.

2023-01-04 15:13 UTC, mongodben approved these changes
lgtm. 

couple little things to fix and 1 open question, but nothing blocking.

2023-01-04 16:41 UTC, mongomoe commented on source/sdk/react-native/realm-database/schemas/mixed.txt
> +collection. Properties using the mixed data type can also hold null values.
Possibly an "Additional Examples" page like we used to have for C#?

2023-01-04 16:48 UTC, merged

2023-02-26 16:49 UTC, takameyer requested changes
What we are missing here is a nice method called `Realm.Object.getPropertyType(propertyName:string)`.  This will return the underlying property type as a string.  This is useful when trying to do some type checking on a `mixed` property.
The cat example could use this to logically depict how it should interpret the given `birthday` type.