(DOCSP-26985): UUID object
mongodb/docs-realm pull request #2443
Opened 2022-12-28 00:01 UTC by mongomoe

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-26985

### Staged Changes

- [UUID - React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [N/A] Create Jira ticket for corresponding docs-app-services update(s), if any
- [N/A] Checked/updated Admin API
- [N/A] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2022-12-29 14:41 UTC, krollins-mdb reviewed
@mongomoe, this looks great! I did notice one thing that should be addressed: one of the list items seems to be incomplete. Could be a simple fix, but it currently leaves readers hanging.

2022-12-29 14:41 UTC, krollins-mdb commented on source/sdk/react-native/realm-database/schemas/uuid.txt
>  -----
[minor] I know you didn't change line 38 in this PR, but we may want to remove "the string". I think readers will understand its a string, and mentioning it here may confuse some readers - make them think that the object type is a string.

2022-12-29 14:41 UTC, krollins-mdb commented on source/sdk/react-native/realm-database/schemas/uuid.txt
> +- Create a name `state variable <https://reactjs.org/docs/hooks-state.html>`__ called "name" that.
[blocker] Incomplete sentence. Was there supposed to be more after "that"?

2022-12-29 14:41 UTC, krollins-mdb commented on source/sdk/react-native/realm-database/schemas/uuid.txt
> +- Get access to the opened realm instance by calling the ``useRealm()`` hook.
[grammar] Because all of these list items share the same subject (the component), their starting verbs should agree with the singular subject.

For example, "The `CreateProfileInput` component ... _Gets_ access to ...."

2022-12-29 14:41 UTC, krollins-mdb commented on source/sdk/react-native/realm-database/schemas/uuid.txt
> +- Renders a ``TextInput`` component that allows the user to enter a name for the profile. When the user presses the "Create Profile" button, the ``createProfile`` method is called and creates the ``P
[minor] The way this is worded, it could be read that the `createProfile` method creates a `Profile` called `Realm.Object`.

I suggest re-writing to avoid this ambiguity. Also, moving the link up to when we first mention realm object on line 47 could help. Something like this could work:
```suggestion
- Renders a ``TextInput`` component that allows the user to enter a name for the profile. When the user presses the "Create Profile" button, the ``createProfile`` method is called and creates a ``Profile`` Realm object.
```

2022-12-29 14:41 UTC, krollins-mdb commented on source/sdk/react-native/realm-database/schemas/uuid.txt
> +In the following ``CreateProfileInput`` example, we create a ``Profile`` realm
[capitalization] Realm object should have a capital R.
```suggestion
In the following ``CreateProfileInput`` example, we create a ``Profile`` Realm
```

2023-01-03 21:56 UTC, mongomoe commented on source/sdk/react-native/realm-database/schemas/uuid.txt
> +- Create a name `state variable <https://reactjs.org/docs/hooks-state.html>`__ called "name" that.
Fixed 👍 
```
Create a name `state variable <https://reactjs.org/docs/hooks-state.html>`__ called "name" that represents the name of the profile.
```

2023-01-03 22:00 UTC, mongomoe commented on source/sdk/react-native/realm-database/schemas/uuid.txt
> +- Renders a ``TextInput`` component that allows the user to enter a name for the profile. When the user presses the "Create Profile" button, the ``createProfile`` method is called and creates the ``P
Moved the link up, but reworded the sentence slightly different than your suggestion:

```
- Renders a ``TextInput`` component that allows the user to enter a name for the profile. When the user presses the "Create Profile" button, the ``createProfile`` method is called and creates a ``Profile`` object.
```

2023-01-03 22:00 UTC, mongomoe commented on source/sdk/react-native/realm-database/schemas/uuid.txt
> +In the following ``CreateProfileInput`` example, we create a ``Profile`` realm
Fixed locally

2023-01-04 14:07 UTC, krollins-mdb approved these changes
Thanks for making changes, @mongomoe! This looks great. 🚢

2023-01-04 17:36 UTC, merged

2023-02-27 07:16 UTC, takameyer requested changes
It wasn't clear right away where `UUID` lives until I read the example (`Realm.BSON.UUID`).  I think it would be good to indicate this somehow.  

Other than that, LGTM