(DOCSP-26983): @realm/react-ify "Sets - React Native SDK"
mongodb/docs-realm pull request #2477
Opened 2023-01-10 15:39 UTC by mongomoe

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-26983

### Staged Changes

- [Sets - React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26983-realmset/sdk/react-native/realm-database/schemas/sets/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [N/A] Create Jira ticket for corresponding docs-app-services update(s), if any
- [N/A] Checked/updated Admin API
- [N/A] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-01-17 13:56 UTC, cbullinger approved these changes
A couple small things but overall lgtm

2023-01-17 13:56 UTC, cbullinger commented on source/sdk/react-native/realm-database/schemas/sets.txt
> +- Uses React's `useEffect <https://reactjs.org/docs/hooks-effect.html>`__ hook to call an anonymous function only once by passing ``useEffect`` an `empty dependency array <https://reactjs.org/docs/ho
```suggestion
- Uses React's `useEffect <https://reactjs.org/docs/hooks-effect.html>`__ hook to call an anonymous function only once by passing ``useEffect``, an `empty dependency array <https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects>`__, as a second argument. Within the anonymous function, we create two different ``Character`` objects by using the :mdn:`new <Web/JavaScript/Reference/Operators/new>` operator to create new realm objects within a write transaction. We set each character's ``inventory`` and ``levelsCompleted`` sets as an array with initial values.
```
could also put the last 2 sentences as sub-bullets

2023-01-17 13:56 UTC, cbullinger commented on source/sdk/react-native/realm-database/schemas/sets.txt
> +In the following example of a ``CreateInitialCharacters`` component we create
```suggestion
In the following example of a ``CreateInitialCharacters`` component, we create
```

2023-01-17 13:56 UTC, cbullinger commented on source/sdk/react-native/realm-database/schemas/sets.txt
>  values, specify ``"int<>"``.
```suggestion
values, specify ``'int<>'``. 
```

2023-01-17 13:56 UTC, cbullinger commented on source/sdk/react-native/realm-database/schemas/sets.txt
> +In the following example of a ``AddInventoryToCharacter`` component we add new ``Set`` elements to the character's inventory.
```suggestion
In the following example of a ``AddInventoryToCharacter`` component, we add new ``Set`` elements to the character's inventory.
```

2023-01-17 13:56 UTC, cbullinger commented on source/sdk/react-native/realm-database/schemas/sets.txt
> +In the following example of a ``QueryCharacterInventory`` component we check the character's inventory size and if it has a specific item.
```suggestion
In the following example of a ``QueryCharacterInventory`` component, we check the character's inventory size and if it has a specific item.
```

2023-01-17 13:56 UTC, cbullinger commented on source/sdk/react-native/realm-database/schemas/sets.txt
> +- Renders a ``TextInput`` that changes the ``inventoryItem`` state variable, and a ``Button`` that calls the ``addInventoryItem()`` method.
```suggestion
- Renders a ``TextInput`` that changes the ``inventoryItem`` state variable, and renders a ``Button`` that calls the ``addInventoryItem()`` method.
```
or remove the comma or "Renders a ``TextInput``... as well as a ``Button``..."

2023-01-17 13:56 UTC, cbullinger commented on source/sdk/react-native/realm-database/schemas/sets.txt
> +- Renders the character's name, and renders the inventory size using the ``size`` property of the character's inventory. It also renders a ``TextInput`` that changes the ``inventoryItem`` state varia
```suggestion
- Renders the character's name, and renders the inventory size using the ``size`` property of the character's inventory. It also renders a ``TextInput`` that changes the ``inventoryItem`` state variable, and renders a ``Button`` that calls the ``queryCharacterInventory`` method.
```
(same as earlier - could also remove the comma or "It also renders a ``TextInput``... as well as a ``Button``...")

2023-01-17 13:56 UTC, cbullinger commented on source/sdk/react-native/realm-database/schemas/sets.txt
> +In the following example of a ``RemoveInventoryFromCharacter`` component we remove a specific item from the set and clear the set of all items.
```suggestion
In the following example of a ``RemoveInventoryFromCharacter`` component, we remove a specific item from the set and clear the set of all items.
```

2023-01-17 13:56 UTC, cbullinger commented on source/sdk/react-native/realm-database/schemas/sets.txt
> +- Renders a ``TextInput`` that changes the ``inventoryItem`` state variable, and a ``Button`` that calls the ``addInventoryItem()`` method.
```suggestion
- Renders a ``TextInput`` that changes the ``inventoryItem`` state variable, and renders a ``Button`` that calls the ``addInventoryItem()`` method.
```
(same as earlier - could also remove the comma or "Renders a ``TextInput``... as well as a ``Button``...")

2023-01-17 13:56 UTC, cbullinger commented on source/sdk/react-native/realm-database/schemas/sets.txt
> +- Renders a ``TextInput`` that changes the ``inventoryItem`` state variable, and two ``Button``s that call the ``removeInventoryItem`` and ``removeAllInventory`` methods, respectively.
```suggestion
- Renders a ``TextInput`` that changes the ``inventoryItem`` state variable and two ``Button``s that call the ``removeInventoryItem`` and ``removeAllInventory`` methods, respectively. 
```
Also, you'll need to change how you refer to the plural `Buttons`. The closing backticks aren't being recognized because of the `s`, so the formatting is incorrectly applied to all of the following text: ``Button` `s that call the removeInventoryItem``

2023-01-17 13:56 UTC, cbullinger commented on source/sdk/react-native/realm-database/schemas/sets.txt
> +However, by default the order of the items in a set is not guaranteed. To
```suggestion
However, the order of the items in a set is not guaranteed by default. To
```

2023-01-17 13:56 UTC, cbullinger commented on source/sdk/react-native/realm-database/schemas/sets.txt
> +In the following example of a ``TraverseCharacterInventory`` component a
```suggestion
In the following example of a ``TraverseCharacterInventory`` component, a
```

2023-01-17 13:56 UTC, cbullinger commented on source/sdk/react-native/realm-database/schemas/sets.txt
> +- Retrieves the character by passing the ``Character`` class to the ``useQuery()`` hook and running the :js-sdk:`Collection.filtered() <Realm.Collection.html#filtered>` method on the result to filter
```suggestion
- Retrieves the character by passing the ``Character`` class to the ``useQuery()`` hook and running the :js-sdk:`Collection.filtered() <Realm.Collection.html#filtered>` method on the result to filter for characters with the name matching the ``characterName`` `prop <https://reactjs.org/docs/components-and-props.html>`__. Then we set the variable ``character`` to the first matching result.
```

2023-01-18 19:07 UTC, mongomoe commented on source/sdk/react-native/realm-database/schemas/sets.txt
> +- Renders a ``TextInput`` that changes the ``inventoryItem`` state variable, and two ``Button``s that call the ``removeInventoryItem`` and ``removeAllInventory`` methods, respectively.
Good catch, referring to them here as: ``Button`` components

2023-01-18 20:01 UTC, merged

2023-02-27 08:25 UTC, takameyer requested changes
Cool examples here.  I have some suggestions to clean things up a bit.

2023-02-27 08:25 UTC, takameyer commented on examples/react-native/__tests__/js/Models/Character.js
> +      levelsCompleted: 'int<>',
As stated in other PRs, I think it's worthwhile to show both the shorthand and object notation for defining schema properties:
```
levelsCompleted: { 
	type: "set",
	objectType: "int"
}
```

2023-02-27 08:25 UTC, takameyer commented on source/sdk/react-native/realm-database/schemas/sets.txt
> +You may want to check for information about your set, such as the set's size or
```suggestion
You may want to check for information about your ``Set``, such as the ``Set``'s size or
```
I think it would be good to keep refering to Set similarly throughout the document, so that it's clear we are talking about the `Set` data type

2023-02-27 08:25 UTC, takameyer commented on source/sdk/react-native/realm-database/schemas/sets.txt
>  To determine if a set contains a particular value, pass the value to the ``<Realm.Set>.has()`` method. The
`set.has` is refered to differently twice in this paragraph.  This should be unified.

2023-02-27 08:25 UTC, takameyer commented on source/sdk/react-native/realm-database/schemas/sets.txt
> +You may want to check for information about your set, such as the set's size or
This should be checked throughout the entire document.  It's not just here