WIP - DOCSP-26933: @realm/react-ify 'Embedded Objects'
mongodb/docs-realm pull request #2486
Opened 2023-01-11 21:34 UTC by davidhou17

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-26933

### Staged Changes

- [Embedded Objects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26933/sdk/react-native/realm-database/schemas/embedded-objects/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [ ] Create Jira ticket for corresponding docs-app-services update(s), if any
- [ ] Checked/updated Admin API
- [ ] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-01-19 15:23 UTC, mongomoe commented on source/sdk/react-native/realm-database/schemas/embedded-objects.txt
> +  ``'Submit Contact'`` button that calls ``submitContact()``.
I don't think
```suggestion
  "Submit Contact" button that calls ``submitContact()``.
```
Suggestion/not required for LGTM: get rid of the monospace around the "Submit Contact" quote. I prefer not overusing monospace, because it looks odd, so I only really use monospace for APIs, variable names, etc (for instance methods coming from the React API, or @realm/react API) etc.

Feel free to take this suggestion or leave it.

2023-01-19 15:27 UTC, mongomoe commented on source/sdk/react-native/realm-database/schemas/embedded-objects.txt
> +- Filters for contacts with the name ``"John Smith"`` by passing :js-sdk:`collection.filtered()
```suggestion
- Filters for contacts with the name "John Smith" by passing :js-sdk:`collection.filtered()
```

2023-01-19 15:32 UTC, mongomoe commented on source/sdk/react-native/realm-database/schemas/embedded-objects.txt
> +  and filters for the contact that matches the name passed into the component as a prop.
```suggestion
  and filters for the contact that matches the name passed into the component as a `prop <https://reactjs.org/docs/components-and-props.html>`__.
```
Suggestion/not required for LGTM: When it is the first use of a jargony term in a subsection, I like linking out to that term. On subsequent uses of the term, I just use monospace: ``prop``.

2023-01-19 15:36 UTC, mongomoe commented on source/sdk/react-native/realm-database/schemas/embedded-objects.txt
> +  and filters for the contact that matches the name passed into the component as a prop.
```suggestion
  and filters for the contact that matches the name passed into the component as a `prop <https://reactjs.org/docs/components-and-props.html>__`.
```

2023-01-19 15:43 UTC, mongomoe commented on source/sdk/react-native/realm-database/schemas/embedded-objects.txt
> +  the name passed into the component as a prop.
```suggestion
  the name passed into the component as a `prop <https://reactjs.org/docs/components-and-props.html>`__.
```
Suggestion/not required for LGTM:

2023-01-19 15:51 UTC, mongomoe commented on examples/react-native/__tests__/ts/realm-database/schemas/embedded-objects-test.tsx
> +        <View>
Suggestion/not required for LGTM:

Can we:

1. Perform the query for  ``contacts.filtered(`name == '${contactName}'`)[0]`` earlier (maybe on line 173), because there's no need for that query to specifically happen when the "Delete Contact" button is pressed.
2.  Add a TextInput that displays the character's name here? That way the theoretical user knows the name of the Contact that they are deleting.

Both of these changes would require a small change to the text/description in the docs under the "Delete an Embedded Object" subsection.

2023-01-19 15:58 UTC, mongomoe commented
  **LGTM**, this looks really good. 

Just left some suggestions.  Some of the suggestions are reoccurring in a few places:

1. Swapping ``”title-of-button”`` to “title-of-button” to avoid overusing monospace for something that isn’t an API specific term (such as a method or component name).

2. Adding a link for the term ‘prop’ on the first use of the term in the subsection.

2023-01-19 16:02 UTC, mongomoe commented on examples/react-native/__tests__/js/realm-database/schemas/embedded-objects-test.jsx
> +    const contactAddress = await waitFor(() => getByTestId('addressText'));
Needed fix: 
Let's add a timeout to when using the 'waitFor()' method: timeout: 5000. Line 114 includes that timeout. 

Having the timeout will prevent the error that we sometimes get without it (I think that error is something like: 'unable to find by testID')

2023-01-19 19:05 UTC, davidhou17 commented
@mongomoe Just made those changes - thanks for the feedback!

2023-01-19 19:11 UTC, merged

2023-02-27 11:10 UTC, takameyer requested changes
Mostly good, but I am concerned about the snippets being untested code.  Also have some suggestions.

2023-02-27 11:10 UTC, takameyer commented on source/examples/generated/react-native/ts/embedded-objects-test.snippet.query-embedded-object.tsx
> +    .filtered("name == 'John Smith'")[0].address.street;
This would cause a crash if 'John Smith' didn't exist, and I'm also quite sure this would show a type error.

2023-02-27 11:10 UTC, takameyer commented on source/examples/generated/react-native/ts/embedded-objects-test.snippet.query-embedded-object.tsx
> +    .filtered("name == 'John Smith'")[0].address.street;
Also want to point out, we have many untested snippets here.  Why wouldn't the source code be derived from `embedded-objects-tests`?

2023-02-27 11:10 UTC, takameyer commented on source/sdk/react-native/realm-database/schemas/embedded-objects.txt
> +You can use dot notation to filter or sort a :ref:`collection
The example below doesn't actually do this.  It just does a query on the parent property and accesses an embedded object in the results.  I think we would want to document how to actually build a filter based on embedded data.

2023-02-27 11:10 UTC, takameyer commented on source/sdk/react-native/realm-database/schemas/embedded-objects.txt
> +Example
How about deleting an embedded object without deleting the parent?