Refresh "React To Changes" page
mongodb/docs-realm pull request #2525
Opened 2023-01-26 20:30 UTC by MongoCaleb

## Pull Request Info

### Jira

https://jira.mongodb.org/browse/DOCSP-24126

### Staged Changes

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-24126/sdk/dotnet/react-to-changes/

2023-01-27 09:33 UTC, papafe commented
As we are there, we should also update the section "Register a Collection Change Listener". The notification callback contains more than 3 sets of indices, and you can see all the arguments here: https://www.mongodb.com/docs/realm-sdks/dotnet/latest/reference/Realms.ChangeSet.html

2023-01-27 14:23 UTC, papafe requested changes
In `Unregister a Change Listener` we're only showing how to unregister for a collection, and using `CollectionChanged`. We don't show how to unsubscribe for realm change listener, collection change listneers that use `SubscribeForNotifications` or object listeners. Maybe we can remove this section and add an example in the respective sections that are already there?

2023-01-27 14:23 UTC, papafe commented on source/sdk/dotnet/react-to-changes.txt
> +event and check for the type of `NotifyCollectionChangedAction
This looks strange in the rendered page

2023-01-27 14:23 UTC, papafe commented on source/sdk/dotnet/react-to-changes.txt
> +.. literalinclude:: /examples/generated/dotnet/WorkWithRealm.snippet.call-handle-collection-changed.cs
In the example for `SubscribeForNotification` we were subscribing to a query, here we do it on a property list. I think it makes sense to do it on a query here too, so it's easier to see the difference. 

Also, I think it makes sense that for both ways (Subscribe... and INotify...) we show how to do it on property collections, because I don't think it's evident. I think we can either explain it in the respective sections, or to make another small section in which we show both

2023-01-27 14:45 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> +create a notification handler for the Realm, collection, or object that you want
```suggestion
create a notification handler for the Realm, managed collection, or Realm object that you want 
```

good to specify that these are all realm db constructs, not any object or collection.

maybe worth also ref-ing word 'collection' since it might not be understood straight awy.

good t

good to specfiy

2023-01-27 14:46 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> +  any Realm object in a collection changes, including inserts, updates, and deletes.
i think this is also tru for a realm collection of primitives. good to specify here

2023-01-27 14:48 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> -Any modern app should be able to react when data changes,
death to the phrase 'modern app'

2023-01-27 14:48 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
>  --------------------------------
```suggestion
--------------------------------

```

2023-01-27 14:49 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> +----------------------------
```suggestion
----------------------------

```

2023-01-27 14:49 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> +In addition to watching for general realm changes, you can register for changes
```suggestion
You can also register for changes 
```

2023-01-27 14:54 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> +to collections. There are two ways to be notified about changes to a collection:
i rec adding just a lil bit more info abt what collections are. smthn like:

```rst
to collection types, such as ``RealmList`` and ``RealmSet``. (or whatever the relevant .NET data types are)
```

also consider ref to [collections page](https://www.mongodb.com/docs/realm/sdk/dotnet/model-data/data-types/collections/) here

2023-01-27 14:56 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> +method. ``SubscribeForNotifications`` returns a subscription token which can be
```suggestion
To subscribe to collection notifications, call 
:dotnet-sdk:`SubscribeForNotifications <reference/Realms.CollectionExtensions.html#Realms_CollectionExtensions_SubscribeForNotifications__1_System_Collections_Generic_IDictionary_System_String___0__Realms_NotificationCallbackDelegate_System_Collections_Generic_KeyValuePair_System_String___0___>`. ``SubscribeForNotifications`` returns a subscription token which can be 
```

nit for brevity

2023-01-27 14:58 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> +method. ``SubscribeForNotifications`` returns a subscription token which can be
^ not a terrible band name for a group of software engineers in there 40s who like to jam on the weekends, sometimes at weddings, mostly just for fun

2023-01-27 15:00 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> +      result in unexpected behavior.
```suggestion
      In collection notification handlers, always apply changes
      in the following order:
      
      #. Deletions
      #. Insertions
      #. Modifications
      
      Handling insertions before deletions may
      result in unexpected behavior.
```

since we're talkin about an ordered list, might as well make it an ordered list

2023-01-27 15:01 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> +<https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.inotifycollectionchanged.collectionchanged>`_
```suggestion
<https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.inotifycollectionchanged.collectionchanged>`__ 
```

2023-01-27 15:01 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> +<https://learn.microsoft.com/en-us/dotnet/api/system.collections.specialized.notifycollectionchangedaction`_.
```suggestion
<https://learn.microsoft.com/en-us/dotnet/api/system.collections.specialized.notifycollectionchangedaction`__.
```

2023-01-27 15:02 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> +   detail about the change. For finer control, use ``SubscribeForNotifications``.
> does not provide the same level of detail about the change.

same level as what? SubscribeForNotifications?

2023-01-27 15:25 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> +   demonstrates calling ``Dispose`` on the token when you no longer want to
the page only talks about `Dispose` in the example. should it be mentioned elsewhere too?

2023-01-27 15:27 UTC, mongodben reviewed
back to you with some small things throughout!

2023-01-27 18:19 UTC, MongoCaleb commented on source/sdk/dotnet/react-to-changes.txt
>  --------------------------------
huh?

2023-01-27 19:12 UTC, MongoCaleb commented on source/sdk/dotnet/react-to-changes.txt
> +----------------------------
??

2023-01-27 19:13 UTC, MongoCaleb commented on source/sdk/dotnet/react-to-changes.txt
> +to collections. There are two ways to be notified about changes to a collection:
i rec usng vwls

2023-01-27 21:20 UTC, MongoCaleb commented on source/sdk/dotnet/react-to-changes.txt
> +.. literalinclude:: /examples/generated/dotnet/WorkWithRealm.snippet.call-handle-collection-changed.cs
@papafe I don't understand the importance of showing both, sinc they are essentially the same:

` var token = realm.All<Dog>().SubscribeForNotifications((sender, changes, error) =>{});`
vs.
`dog.Owners.AsRealmCollection() .SubscribeForNotifications((sender, changes, error) =>{ });`

2023-01-27 21:34 UTC, MongoCaleb commented on source/sdk/dotnet/react-to-changes.txt
> +event and check for the type of `NotifyCollectionChangedAction
Good point about not showing how to unsubscribe a change listener. I can't figure out how to use the UnsubscribeFromNotifications and thought disposing the token was the preferred way (which we show above). If that _is_ the preferred way, then I will call that out more explicitly.

2023-01-30 10:45 UTC, papafe commented on source/sdk/dotnet/react-to-changes.txt
> +.. literalinclude:: /examples/generated/dotnet/WorkWithRealm.snippet.call-handle-collection-changed.cs
We don't need to show both necessarily, maybe just mention that one can use `SubscribeForNotifications` with both. 

By the way, in the second case you don't need `AsRealmCollection()`. You need that only if you want to access `CollectionChanged`

2023-01-30 10:51 UTC, papafe commented on source/sdk/dotnet/react-to-changes.txt
> +event and check for the type of `NotifyCollectionChangedAction
So, for `SubscribeForNotifications` unsubscribing means disposing the token, yes. 

For `CollectionChanged` the unsubscribing means unsubscribing from the event. So
```
bla.CollectionChanged += Handler;

---

bla.CollectionChanged -= Handler;
``

2023-01-30 18:14 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
>  --------------------------------
add space between header and following paragraph

2023-01-30 18:17 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> +      1. deletions
```suggestion
      in the following order:

      #. deletions
```

fix broken snooty formatting

2023-01-30 18:19 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> +Realm's notification system allows you to watch for and react to changes in your
this is still the same @MongoCaleb. curious your thoughts here.

2023-01-30 18:31 UTC, mongodben commented on source/sdk/dotnet/react-to-changes.txt
> +within a realm so that Realm notifies you when any of the object's
```suggestion
within a realm so that the SDK notifies you when any of the object's 
```

nit: read a little confusing with 'a realm so that Realm'.

2023-01-30 18:35 UTC, mongodben reviewed
nice improvements! couple more small things and few questions throughout.

2023-01-30 22:59 UTC, MongoCaleb commented on source/sdk/dotnet/react-to-changes.txt
> +  calling the ``Clear()`` method.
It's a buyilt-in method of the .NET framework and I don't think it's necessary show/explain further here.

2023-01-31 09:27 UTC, papafe commented on source/sdk/dotnet/react-to-changes.txt
> +`IList
Two points here:
- `realm.All<Person>` is neither `IList` or `ISet`, but still it can be subscribed for notifications. 
- `IDictionary` is missing
So we can say that developers can subscribe for notifications on realm collections, including collection properties (IList, ....)

2023-01-31 09:29 UTC, papafe commented on source/sdk/dotnet/react-to-changes.txt
> +- ``DeletedIndices`` is an int32[] that contains the indices of the objects that were
We can just say `int[]` instead of `int32[]`. Also it needs to be between apices, so it's treated like code.

2023-01-31 09:30 UTC, papafe commented on source/sdk/dotnet/react-to-changes.txt
> +  ModifiedIndices property, but the indices represent the new locations in the
ModifiedIndices should be between ticks

2023-01-31 09:32 UTC, papafe commented on source/sdk/dotnet/react-to-changes.txt
> +  calling the ``Clear()`` method.
I would put that as an example, as the collection could be cleared in other cases too. So something like:

``IsCleared`` is a boolean set to ``true`` when a collection has been cleared (for instance by 
  calling the ``Clear()`` method on collection properties).

2023-01-31 09:33 UTC, papafe commented on source/sdk/dotnet/react-to-changes.txt
> +cancelled at any time to stop receiving notifications on the collection.
```suggestion
disposed at any time to stop receiving notifications on the collection. 
```

2023-01-31 09:50 UTC, papafe commented on source/sdk/dotnet/react-to-changes.txt
> +When you no longer want to receive notifications on a change listener, you
Before this we have shown 3 different "things" that the developer can subscribe (realm changes, collection changes, object changes), but here we show only how to unsubscribe for collection changes.

```
//Realm listener
realm.RealmChanged += HandleRealmChanged;
realm.RealmChanged -= HandleRealmChanged;

//CollectionListener
//with SubscribeForNotifications
var token = realm.All<Item>().SubscribeForNotification(....);
var token = items.SubscribeForNotification(....);
token.Dispose();

//with CollectionChanged
realm.All<Item>().AsRealmCollection().CollectionChanged -= OnItemsChangedHandler;
items.AsRealmCollection().CollectionChanged -= OnItemsChangedHandler;

//Object listener 
artist.PropertyChanged += HandleObjectChanged;
artist.PropertyChanged -= HandleObjectChanged;


```

2023-01-31 09:55 UTC, papafe commented on source/sdk/dotnet/react-to-changes.txt
> +When you no longer want to receive notifications on a change listener, you
To be honest though, I'm pretty sure every c# developer knows how to unsubscribe from events, so the only one we probably need to show is the disposing of the tokens. For the others we could even just say in text that one can unsubscribe from the event if one wants to stop receiving notifications

2023-01-31 14:05 UTC, mongodben approved these changes
LGTM. still a couple of open minor comments from my first review that you can take or leave. 

leavin it to you and ferdinando to work out the remaining technical details. lmk if you'd like another look once all that's resolved.

2023-01-31 16:41 UTC, merged

2023-02-01 19:23 UTC, MongoCaleb commented on source/sdk/dotnet/react-to-changes.txt
> +When you no longer want to receive notifications on a change listener, you
I added the realm.RealmChanged, but I think the rest -- as you mention --isn't necessary. We show disposing the token above in the doc.