(DOCSP-27550): Kotlin Define an Object Model
mongodb/docs-realm pull request #2536
Opened 2023-01-31 16:45 UTC by cbullinger

## Pull Request Info
Blocks https://github.com/mongodb/docs-realm/pull/2514 ([DOCS-15613](https://jira.mongodb.org/browse/DOCSP-27550))

### Jira

- https://jira.mongodb.org/browse/DOCSP-27550 

### Staged Changes

- (new page) [Define an Object Model - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-27550-define-obj-model/sdk/kotlin/realm-database/define-realm-object-model/)
- (small changes) [Index a Field](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-27550-define-obj-model/sdk/kotlin/realm-database/schemas/index/)
- (small updates) [Primary Keys](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-27550-define-obj-model/sdk/kotlin/realm-database/schemas/primary-key/)
- (small updates) [Ignore a Field](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-27550-define-obj-model/sdk/kotlin/realm-database/schemas/ignore/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [ ] Create Jira ticket for corresponding docs-app-services update(s), if any
- [ ] Checked/updated Admin API
- [ ] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-01-31 21:12 UTC, dacharyc requested changes
Nice work! A handful of small tweaks and a few nits, but otherwise looking good.

2023-01-31 21:12 UTC, dacharyc commented on source/sdk/kotlin/realm-database/define-realm-object-model.txt
> +`?  <https://kotlinlang.org/docs/null-safety.html>`__.
I'm torn on whether we think there's really value in taking devs out of our docs to go check out the Kotlin docs on null safety. Do we think this is a concept that Kotlin SDK devs need to be linked to?

If we do want to keep this link here, I think it should be on more than just the `?`. That looks really odd to me, and also isn't a very large area for a link. If you want to keep the link, I might suggest moving it to the "(nullable)" or explicitly stating something like "For more information on null safety in Kotlin, refer to the Kotlin docs..."

2023-01-31 21:12 UTC, dacharyc commented on source/sdk/kotlin/realm-database/schemas/ignore.txt
> +They can't be used in queries and won't trigger Realm notifications.
Nit: The style guide suggests no future tense, but this is a teeny nit.

```suggestion
They can't be used in queries and don't trigger Realm notifications.
```

2023-01-31 21:12 UTC, dacharyc commented on source/sdk/kotlin/realm-database/schemas/primary-key.txt
> +  Realm automatically indexes primary keys, so you can efficiently read and modify objects based on their primary key.
I _think_ this is meant to be its own item? It doesn't seem to directly follow from the nullable bullet.
```suggestion
- Realm automatically indexes primary keys, so you can efficiently read and modify objects based on their primary key.
```

2023-01-31 21:26 UTC, cbullinger commented on source/sdk/kotlin/realm-database/define-realm-object-model.txt
> +:wikipedia:`ORM <Object-relational_mapping>`).
I don't feel strongly either way -- grabbed this from another sdk's version of this page and kept that ORM wiki link in. I'll remove the parens/link.

2023-01-31 21:29 UTC, cbullinger commented on source/sdk/kotlin/realm-database/define-realm-object-model.txt
> +A **realm schema** is a list of valid object schemas that a realm may contain.
I know exactly what you mean. I waffled a lot on how to organize this topic and what to include in it (and I think I'll end up revisiting it in the near future once I get some of the other outstanding kotlin content done). I'll try it as an include.

2023-01-31 21:40 UTC, cbullinger commented on source/sdk/kotlin/realm-database/define-realm-object-model.txt
> +`?  <https://kotlinlang.org/docs/null-safety.html>`__.
I copied this from the Flutter doc, but agree now that you've pointed it out. Updated to fix the link text.

2023-01-31 21:44 UTC, cbullinger commented on source/sdk/kotlin/realm-database/schemas/primary-key.txt
> +  Realm automatically indexes primary keys, so you can efficiently read and modify objects based on their primary key.
Yuuuuup. Thanks for catching

2023-01-31 21:48 UTC, cbullinger commented on source/sdk/kotlin/realm-database/define-realm-object-model.txt
> +1. Create a uniquely named Kotlin class that implements the
Technically you [don't hyphenate when the adverb ends in _-ly_](https://prowritingaid.com/grammar/1000138/How-to-use-hyphen-after-adverbs#:~:text=When%20the%20adverb%20ends%20in,%2C%20adjectives%2C%20and%20other%20adverbs.)

2023-01-31 22:58 UTC, dacharyc approved these changes
Looks great - nice work!

2023-01-31 22:58 UTC, dacharyc commented on source/sdk/kotlin/realm-database/realm-files/open-and-close-a-realm.txt
> +Realm Schema
Just a thought - I wonder if this makes more sense above the "Open" section here as a top-level section? It also applies to the in-memory realm stuff.

2023-01-31 22:58 UTC, dacharyc commented on source/sdk/kotlin/realm-database/define-realm-object-model.txt
> +1. Create a uniquely named Kotlin class that implements the
Ugh, really? I either never learned or had forgotten that rule! Thanks 😀

2023-02-01 00:51 UTC, cbullinger commented on source/sdk/kotlin/realm-database/realm-files/open-and-close-a-realm.txt
> +Realm Schema
Agreed. I moved it above that section. And, honestly, there's quite a bit missing from that Open a Realm page that I've noted as part of the kotlin docs audit, so I'll be revisiting it soon.

2023-02-01 01:20 UTC, merged