(DOCSP-26755): Kotlin Embedded Objects page
mongodb/docs-realm pull request #2556
Opened 2023-02-03 19:52 UTC by cbullinger

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-26755

### Staged Changes

- [Embedded Objects - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-26755-linking-obj/sdk/kotlin/realm-database/schemas/embedded-objects/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [ ] Create Jira ticket for corresponding docs-app-services update(s), if any
- [ ] Checked/updated Admin API
- [ ] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-02-07 15:59 UTC, rorbech requested changes
There are some errors in the usage of embedded objects. I have tried to highlight the errors.

2023-02-07 15:59 UTC, rorbech commented on source/examples/generated/kotlin/DataTypesTest.snippet.create-embedded-object.kt
> +    this.copyToRealm(
Maybe a bit confusing with the external defined objects 🤔 

Maybe better with 
```
val contact = copyToRealm(Contact())

contact.apply {
    name ...
    
    address = Address().apply { ...  }
}
```
I would think that it makes it more obvious what is actually going on, but maybe I am biased from doing the SDK 😅

2023-02-07 15:59 UTC, rorbech commented on source/examples/generated/kotlin/DataTypesTest.snippet.update-embedded-object.kt
> +// ... Fetch the object
You need to fetch the object inside the `write` block with `findLatest(object)` otherwise you would not be able to update it.

2023-02-07 15:59 UTC, rorbech commented on source/examples/generated/kotlin/DataTypesTest.snippet.overwrite-embedded-object.kt
> +realm.write {
This is not overwriting the `address` with a new object but updating the existing one. And again you need to fetch the most recent version to be able to update it. 

You should do something like

```
realm.write {
     val contact = findLatest(contactReference)?: error("Could not retrieve the latest version of parent object")
     contact.address = Address().apply { ... }
}
```

2023-02-07 15:59 UTC, rorbech commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +collection based on an embedded object property value.
This sounds like a weird paragraph to start out with. It is a general possibility for all queries that you can filter on member, so can't see why this should be mentioned specifically here.

2023-02-07 15:59 UTC, rorbech commented on source/examples/generated/kotlin/DataTypesTest.snippet.query-embedded-objects.kt
> +// Query through the parent object
I think it would make most sense to show that you can query the embedded objects directly first and then follow up with the filter on linked property afterwards. Thus, swapping this example with the below.

2023-02-07 15:59 UTC, rorbech commented on source/examples/generated/kotlin/DataTypesTest.snippet.delete-embedded-object.kt
> +//  Delete an embedded object directly from parent
Maybe a bit off with `directly from parent` as the embedded object are deleted directly without touching the parent. This a valid use case though, so just keep with an updated text. But maybe also include the use case of deleting it directly from the parent by clearing the parents property, which would delete the embedded class
```
realm.write {
    val parent = findLatest(parentRef)?: error("Cannot find parent reference")
    parent.address = null
}
```
This will delete the object so that it isn't returned from a query directly on the specific embedded class (`realm.query<Address>()`). This is fundamentally different from properties referencing normal (non-embedded) objects where clearing a reference would not delete the actual object, but only the reference to it.

2023-02-07 15:59 UTC, rorbech commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/DataTypesTest.kt
> +                        address = nicksAddress.apply {
This `apply` will update the unmanaged `nicksAddress` object and import it by creating a copy inside the realm and assign the properties of the clone according to the values of `nicksAddress`. Is that what you expect? and intend to show?

2023-02-07 15:59 UTC, rorbech commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/DataTypesTest.kt
> +                nicksAddress.street = "100 10th St N"
This doesn't update anything inside the realm. You just update the unmanaged instance. If you want to update the address of `Nick Riviera` inside the Realm then you need to fetch the reference inside the realm with a query or by looking up a previous managed instance with `findLatest(...)`

2023-02-07 15:59 UTC, rorbech commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/DataTypesTest.kt
> +                nicksAddress.apply {
Again, this it not updating anything inside the realm, but just the unmanaed `nicksAddress` instance.

2023-02-09 20:06 UTC, cbullinger commented on source/examples/generated/kotlin/DataTypesTest.snippet.delete-embedded-object.kt
> +//  Delete an embedded object directly from parent
Added/clarified use case

2023-02-09 20:07 UTC, cbullinger commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +collection based on an embedded object property value.
I copied from the other sdks' versions of the page, but agree that it's not needed here. Removed.

2023-02-09 20:08 UTC, cbullinger commented on source/examples/generated/kotlin/DataTypesTest.snippet.create-embedded-object.kt
> +    this.copyToRealm(
Updated (hopefully) for better clarity

2023-02-09 20:09 UTC, cbullinger commented on source/examples/generated/kotlin/DataTypesTest.snippet.overwrite-embedded-object.kt
> +realm.write {
Updated in this and all following instances

2023-02-09 20:48 UTC, cbush approved these changes
Looks great! I have a few minor comments I'd like to see addressed before merge

2023-02-09 20:48 UTC, cbush commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +<kotlin-relationships>`, but they provide additional constraints.
Not sure if this was inherited text from elsewhere, but anyway: I'm not sure "provide ... constraints" is the right verb? I might simply say "have additional constraints" here. Depends what we're trying to say about the quality of the constraints I guess.

2023-02-09 20:48 UTC, cbush commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +  or their parent no longer references them.
It seems this list and the paragraph above have some overlapping information. Could it be tightened up?

2023-02-09 20:48 UTC, cbush commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +`EmbeddedRealmObject <{+kotlin-local-prefix+}/io.realm.kotlin.types/-embedded-realm-object/index.html>`__:
Is the link correct? I'm getting 403

2023-02-09 20:48 UTC, cbush commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +   own definition.
Neat!

2023-02-09 20:48 UTC, cbush commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +instance in a write transaction:
This is interesting. Does this imply that simply assigning a new embedded object instance to the property (as in create an embedded object) would not work?

I would almost argue this overwrite example is an antipattern -- as the schema evolves, this code might "forget" to update some new property and therefore leave old data in the supposedly new instance.

2023-02-09 20:48 UTC, cbush commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +  - Deleting the parent object also deletes all of its embedded objects
I think the list could use a bit more context. Are these two ways to approach the problem?

2023-02-09 20:48 UTC, cbush commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +.. literalinclude:: /examples/generated/kotlin/DataTypesTest.snippet.delete-embedded-object.kt
What consequence does `delete(addressToDelete)` have on the parent object that holds it? Is the parent object's embedded property automatically nullified?

2023-02-09 20:48 UTC, cbush commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/DataTypesTest.kt
> +                // Clear the parent property (deletes the embedded class)
```suggestion
                // Clear the parent property (deletes the embedded object instance)
```

2023-02-10 13:06 UTC, cbullinger commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +`EmbeddedRealmObject <{+kotlin-local-prefix+}/io.realm.kotlin.types/-embedded-realm-object/index.html>`__:
Fixed. Thanks for catching

2023-02-10 13:07 UTC, cbullinger commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +<kotlin-relationships>`, but they provide additional constraints.
Yeah, the wording was taken from the text shared by the other sdks' pages, but I agree it's awkward. Updated to "have additional constraints"

2023-02-10 13:19 UTC, cbullinger commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +.. literalinclude:: /examples/generated/kotlin/DataTypesTest.snippet.delete-embedded-object.kt
Yes, after delete, parent's address property is null

2023-02-10 14:09 UTC, cbullinger commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +  - Deleting the parent object also deletes all of its embedded objects
Yes, insofar as they're the approaches available in kotlin sdk (other than Flutter, we only instruct on deleting the parent but IDK if that's also because you can't query the embedded objects directly in the other sdks). 
Suggestion from tech review was to include the 3rd bullet (clear through the parent property) since that's also a valid use case.

2023-02-10 14:13 UTC, cbullinger commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +  - Deleting the parent object also deletes all of its embedded objects
I've tweaked slightly

2023-02-10 14:52 UTC, cbullinger commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +instance in a write transaction:
Updated for clarification and a better code example for overwrite (deleting & creating a new object)

2023-02-10 15:30 UTC, cbullinger commented on source/sdk/kotlin/realm-database/schemas/embedded-objects.txt
> +  or their parent no longer references them.
I've tweaked slightly -- lmk if it there's still concern of overlapping/redundant info

2023-02-10 16:23 UTC, cbush approved these changes

2023-02-10 16:29 UTC, merged