(DOCSP-26120): Realm.refresh() for Flutter
mongodb/docs-realm pull request #2561
Opened 2023-02-06 21:48 UTC by mongodben

## Pull Request Info

Document `Realm.refresh()` and `Realm.refreshAsync()` for Flutter SDK. 

Note that the docs here are pretty limited b/c this method is only really needed for multi-processing, and we've decided to only talk about multi-processing in the context of syncing on multiple processes *for now*. 

In future docs changes where we talk more about working with Realm on multiple Dart/Flutter processes, there'll be further documentation of these methods.

### Jira

- https://jira.mongodb.org/browse/DOCSP-26120

### Staged Changes

- [Sync Multiple Processes (Flutter)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-26120/sdk/flutter/sync/sync-multiple-processes/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [x] Create Jira ticket for corresponding docs-app-services update(s), if any
- [x] Checked/updated Admin API
- [x] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-02-06 21:49 UTC, mongodben commented on source/sdk/flutter/sync/sync-multiple-processes.txt
> +To open a single synced realm from multiple processes, perform the following:
refactored this header/intro to make addition of later section in the PR make more sense.

2023-02-07 15:25 UTC, blagoev requested changes
added a suggestion how to fix the dos for the `refresh` methods

2023-02-07 15:25 UTC, blagoev commented on examples/dart/test/sync_multiple_processes_test.dart
> +  // Note: This test doesn't actually test what is being documented, b/c the
Do we need a test for this in the docs? Its a complex scenario to test which could be done in the SDK only.

2023-02-07 15:25 UTC, blagoev commented on examples/dart/test/sync_multiple_processes_test.dart
> +  // Note: This test doesn't actually test what is being documented, b/c the
we have a test for that in the SDK

2023-02-07 15:25 UTC, blagoev commented on source/examples/generated/flutter/sync_multiple_processes_test.snippet.refresh-secondary-process.dart
> +// You must call realm.refresh() in the secondary process
Not sure to whom this comment is but it is not a must to do it. This methos is intendent only if people find problems with the automatic refresh Realm has built-in

2023-02-07 15:25 UTC, blagoev commented on source/sdk/flutter/sync/sync-multiple-processes.txt
> +When you are working with a realm across multiple processes, the realm does not
This is incorrect. Realm has auto-refresh built-in. It works very well and is on by default. Developers don't need to do anything to sync data between processes. Still in some cases they might need to call realm.refresh() if they notice that data is not available in their  Realm instance. This should happen very rarely so the API is marked as `Typically should not be used.`

2023-02-07 15:25 UTC, blagoev commented on source/sdk/flutter/sync/sync-multiple-processes.txt
> +When you are working with a realm across multiple processes, the realm does not
So here we better write something like

> When sharing the same realm file between multiple processes, Realm has auto-refresh built-in and data written from one process is visible immediately from the other processes. Occasionally this may not happen immediately and thus Realm exposes a refresh() and refreshAsync() methods to trigger the data refresh mechanism manually.

2023-02-07 15:29 UTC, mongodben commented on examples/dart/test/sync_multiple_processes_test.dart
> +  // Note: This test doesn't actually test what is being documented, b/c the
yeah i saw your tests. i don't think it matters very much here since the actual logic in the code example is so simple.

2023-02-07 15:32 UTC, mongodben commented on source/sdk/flutter/sync/sync-multiple-processes.txt
> +When you are working with a realm across multiple processes, the realm does not
oh ok, thanks for that clarification. what are some circumstances when the refresh might not occur automatically? 

would be good to specify in the PR.

2023-02-07 15:39 UTC, blagoev commented on examples/dart/test/sync_multiple_processes_test.dart
> +  // Note: This test doesn't actually test what is being documented, b/c the
would suggest to remove this test here

2023-02-07 15:57 UTC, mongodben commented on examples/dart/test/sync_multiple_processes_test.dart
> +  // Note: This test doesn't actually test what is being documented, b/c the
going to keep b/c it's important for us to make sure that our code examples in the docs run even if they're not fully testing the behavior.

2023-02-07 15:58 UTC, blagoev commented on examples/dart/test/sync_multiple_processes_test.dart
> +  // Note: This test doesn't actually test what is being documented, b/c the
then the comments needs to be fixed I suppose.

2023-02-07 15:59 UTC, blagoev commented on examples/dart/test/sync_multiple_processes_test.dart
> +    // before the data written in the main process registers
```suggestion
```

2023-02-07 15:59 UTC, blagoev commented on examples/dart/test/sync_multiple_processes_test.dart
> +    await realm.refreshAsync();
the second call is not needed

2023-02-07 16:00 UTC, blagoev commented on examples/dart/test/sync_multiple_processes_test.dart
> +    realm.refreshAsync();
```suggestion
    realm.refreshAsync();
```
This is a bad practice. One should really use await with async calls.

2023-02-07 16:00 UTC, mongodben commented on source/sdk/flutter/sync/sync-multiple-processes.txt
> +When you are working with a realm across multiple processes, the realm does not
per slack convo, updating the text but not going into detail about what might cause the refresh to not happen.

2023-02-07 16:01 UTC, blagoev commented on source/examples/generated/flutter/sync_multiple_processes_test.snippet.refresh-secondary-process.dart
> +// You must call realm.refresh() in the secondary process
its definitely not a `must` to call this method. We should reword this comment

2023-02-07 16:12 UTC, mongodben commented on source/examples/generated/flutter/sync_multiple_processes_test.snippet.refresh-secondary-process.dart
> +// You must call realm.refresh() in the secondary process
yep, reworded

2023-02-07 16:16 UTC, blagoev commented on examples/dart/test/sync_multiple_processes_test.dart
> +    realm.refreshAsync();
when you call a method with await you release the main isolate (thread/event loop) to handle any other async events and microtasks. Then when the result is available the code continues with the next statement.

2023-02-07 16:20 UTC, mongodben commented on examples/dart/test/sync_multiple_processes_test.dart
> +    realm.refreshAsync();
thx, taking conversation to slack for additional clarification.

2023-02-07 21:08 UTC, blagoev approved these changes

2023-02-08 16:43 UTC, dacharyc approved these changes
One grammar nit we should fix, and a question about whether we can add more info, but otherwise LGTM.

2023-02-08 19:44 UTC, mongodben commented on source/sdk/flutter/sync/sync-multiple-processes.txt
> +However, occasionally the refresh may not happen immediately. In this case,
yeah i had the same question. lubo said there's no clear answer, which is why the above sentence is 

> Generally, you do not need to write additional logic
to refresh data across processes.

so this is what folks generally should do

2023-02-08 19:48 UTC, merged