(DOCSP-27005): @realm/react-ify Manage Email/Password Users page
mongodb/docs-realm pull request #2582
Opened 2023-02-13 21:48 UTC by mongodben

## Pull Request Info

@realm/react-ify Manage Email/Password Users page

### Jira

- https://jira.mongodb.org/browse/DOCSP-27005

### Staged Changes

- [Manage Email Password Users (RN)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27005/sdk/react-native/manage-users/manage-email-password-users/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [x] Create Jira ticket for corresponding docs-app-services update(s), if any
- [x] Checked/updated Admin API
- [x] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-02-15 15:54 UTC, nlarew reviewed
2 small things otherwise LGTM

2023-02-15 15:54 UTC, nlarew commented on source/sdk/react-native/manage-users/manage-email-password-users.txt
> +You must :ref:`confirm a new user's email address <react-native-confirm-user>`
```suggestion
After registration, you must :ref:`confirm a new user's email address <react-native-confirm-user>`
```

small clarification

2023-02-15 15:54 UTC, nlarew commented on source/sdk/react-native/manage-users/manage-email-password-users.txt
> +.. literalinclude:: /examples/generated/node/authenticate.snippet.confirm-email-pass-user.js
Can we remove the "Complete a User Confirmation" subheading? It's the only subsection and kind awkwardly breaks apart the content IMO.

Maybe add a sentence somewhere to replace it that mentions "the confirmation process starts when you register a user and ends when you confirm them from your client code"

2023-02-15 15:54 UTC, nlarew approved these changes

2023-02-15 15:55 UTC, nlarew reviewed
Actually one more thing - looks like there's a bunch of unused files. Can we clean that up?

2023-02-15 18:48 UTC, mongodben commented
> Actually one more thing - looks like there's a bunch of unused files. Can we clean that up?

going to deal w all of that in [DOCSP-27996](https://jira.mongodb.org/browse/DOCSP-27996)

2023-02-20 08:30 UTC, takameyer requested changes
I have a few requests

2023-02-20 08:30 UTC, takameyer commented on examples/react-native/__tests__/ts/authentication/manage-email-password-users.test.tsx
> +        <UserProvider fallback={LogIn}>
```suggestion
        <UserProvider fallback={RegisterUser}>
```
I would set `RegisterUser` as the fallback and remove `LogIn`.

2023-02-20 08:30 UTC, takameyer commented on source/sdk/react-native/manage-users/manage-email-password-users.txt
It's not really clear to me from this code sample how I would confirm a user.  If this runs in React Native, where do the tokens come from?

2023-02-23 08:12 UTC, takameyer commented on source/sdk/react-native/manage-users/manage-email-password-users.txt
Good compromise.  Thanks!

2023-02-23 08:12 UTC, takameyer approved these changes
LGTM!

2023-02-23 14:45 UTC, merged