(DOCSP-27011, DOCSP-27012, DOCSP-27013): Consolidate React Native sync session pages with @realm/react-ification
mongodb/docs-realm pull request #2587
Opened 2023-02-14 14:38 UTC by mongodben

## Pull Request Info

Consolidate React Native sync session pages with @realm/react-ification

### Jira

- https://jira.mongodb.org/browse/DOCSP-27011
- https://jira.mongodb.org/browse/DOCSP-27012
- https://jira.mongodb.org/browse/DOCSP-27013

### Staged Changes

- [Manage Sync Session (React Native)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27011/sdk/react-native/sync-data/manage-sync-session/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [x] Create Jira ticket for corresponding docs-app-services update(s), if any
- [x] Checked/updated Admin API
- [x] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-02-18 23:00 UTC, krollins-mdb reviewed
Looking good so far! I think we can do some more realm reactifying though.

2023-02-18 23:00 UTC, krollins-mdb commented on source/sdk/react-native/sync-data/manage-sync-session.txt
> +.. literalinclude:: /examples/SyncChanges/enable-session-multiplexing.js
While this example is correct, we should realm reactify it to show `useRealm()` and maybe even enabling multiplexing within a `useEffect()` hook, though I'm not certain that's the best way to do it.

2023-02-20 08:48 UTC, takameyer requested changes
I have some requests :-)

2023-02-20 08:48 UTC, takameyer commented on source/sdk/react-native/sync-data/manage-sync-session.txt
> +.. literalinclude:: /examples/generated/node/sync-changes-between-devices.snippet.sync-changes-between-devices-pause-or-resume-sync-session.js
The `Access Sync Session` already show's how to do this in the context of React Native.  This seems to be redundant and the above example is more usable.

2023-02-21 20:07 UTC, mongodben commented on source/sdk/react-native/sync-data/manage-sync-session.txt
> +.. literalinclude:: /examples/generated/react-native/ts/sync-session.test.snippet.sync-session.tsx
i get what you mean. was thinking to show an example of sync session in action. but can do a more abstract example here, and add this one to the pause/resume sync session section.

2023-02-21 20:09 UTC, mongodben commented on source/sdk/react-native/sync-data/manage-sync-session.txt
> +.. literalinclude:: /examples/SyncChanges/enable-session-multiplexing.js
> While this example is correct, we should realm reactify it to show `useRealm()` and maybe even enabling multiplexing within a `useEffect()` hook, though I'm not certain that's the best way to do it.

this method doesn't relate to teh `useRealm` hook since it's a static method on the Realm.App.Realm class

2023-02-21 20:11 UTC, mongodben commented on source/sdk/react-native/sync-data/manage-sync-session.txt
> +.. literalinclude:: /examples/SyncChanges/enable-session-multiplexing.js
> We should ensure that this needs to happen either before or after opening `realm`. 

@takameyer, do you mean that you **cannot** call `Realm.App.Sync.enableSessionMultiplexing()` while the realm is in the process of opening?

2023-02-23 21:40 UTC, mongodben commented on examples/react-native/__tests__/ts/sync/check-upload-download-progress.test.tsx
> +      'reportIndefinitely',
note to @takameyer: typescript compiler wants these to be enums but getting error documented here https://github.com/mongodb/docs-realm/pull/2587 when try use the enum value. instead have to use the string value of the enum, as seen here.

2023-02-24 11:56 UTC, takameyer commented on source/sdk/react-native/sync-data/manage-sync-session.txt
> +.. literalinclude:: /examples/SyncChanges/enable-session-multiplexing.js
I think I had been reading too much code.  The example shown is fine.  I believe I assumed you had to call it on `app`, which is not the case.

2023-02-24 12:01 UTC, takameyer commented on examples/react-native/__tests__/ts/sync/check-upload-download-progress.test.tsx
> +      'reportIndefinitely',
We just merged a fix for this.  Should be coming in the next patch release

2023-02-24 12:02 UTC, takameyer approved these changes

2023-02-24 14:00 UTC, mongodben commented on examples/react-native/__tests__/ts/sync/check-upload-download-progress.test.tsx
> +      'reportIndefinitely',
ok thanks. will merge this regardless and do a final pass on the `realm-react-guidance` epic to address before merge.

2023-02-24 16:39 UTC, krollins-mdb approved these changes
Just some minor suggestions to clarify and minimize. Nice work! That's a lot of tests. 😢

2023-02-24 16:39 UTC, krollins-mdb commented on source/sdk/react-native/sync-data/manage-sync-session.txt
> +Access the sync session with the synced realm's :js-sdk:`Realm.syncSession
I know the 'synced' here provides more specificity, but there's a lot of 'sync' in these two sentences and we already set the stage of a synced realm in the first sentence.

```suggestion
Access the sync session with the realm's :js-sdk:`Realm.syncSession
```

2023-02-24 16:39 UTC, krollins-mdb commented on source/sdk/react-native/sync-data/manage-sync-session.txt
> +open realm, pause does not affect the sync sessions for other realms.
I think we can remove this sentence, as the following sentence gets the point across.
```suggestion
You can pause and resume the realm's sync session. If you have more than one
open realm, pause does not affect the other realms' sync sessions.
```

2023-02-24 16:39 UTC, krollins-mdb commented on examples/react-native/__tests__/ts/sync/check-upload-download-progress.test.tsx
> +// TODO: create JS only version
You did this! TODO accomplished. 😄

2023-02-24 16:39 UTC, krollins-mdb commented on examples/react-native/__tests__/ts/sync/check-network-connection.test.tsx
> +// TODO: create a JS-only example b/c of type of callback :(
Turn that frown around: TODO completed! 🤣

2023-02-24 16:39 UTC, krollins-mdb commented on examples/react-native/__tests__/ts/sync/check-upload-download-progress.test.tsx
> +// TODO: create JS only version
Also, this TODO exists in the JS-only version.

2023-02-24 16:39 UTC, krollins-mdb commented on examples/react-native/__tests__/ts/sync/check-upload-download-progress.test.tsx
> +  const [uploadProgressPercent, setUploadProgressPercent] = React.useState(0);
I don't think this is critical for our phase 1, but maybe we should align on how we use React hooks. I think in most of our examples so far, we've imported `useState()` separately: `import React, {useState} from 'react';`. Then use the hook directly.

Again, not crucial right now, but we should aim to be consistent in our examples.

2023-02-24 16:39 UTC, krollins-mdb commented on examples/react-native/__tests__/ts/sync/check-upload-download-progress.test.tsx
> +  const [uploadProgressPercent, setUploadProgressPercent] = React.useState(0);
Would apply to other tests too if you opt to change in this PR.

2023-02-24 16:39 UTC, krollins-mdb commented on source/sdk/react-native/sync-data/manage-sync-session.txt
> +when connection is available.
```suggestion
when a connection is available.
```

2023-02-24 16:39 UTC, krollins-mdb commented on source/sdk/react-native/sync-data/manage-sync-session.txt
> +This method returns a boolean that is ``true`` if there is network connection and
```suggestion
This method returns a boolean that is ``true`` if there is a network connection and
```

2023-02-24 16:39 UTC, krollins-mdb commented on source/sdk/react-native/sync-data/manage-sync-session.txt
> +To listen for connection state changes, call :js-sdk:`Realm.syncSession.addConnectionNotification()
The link text for these gets quite long and kind of hard to read. Could we shorten to just the method and let users follow the link for further details?

We're inconsistent throughout the page. In the previous section, we omit the `Realm.` part. Maybe `syncSession.<method>` is a good compromise?

2023-02-24 16:42 UTC, mongodben commented on examples/react-native/__tests__/ts/sync/check-upload-download-progress.test.tsx
> +      'reportIndefinitely',
ticket to address https://jira.mongodb.org/browse/DOCSP-28258

2023-02-24 16:43 UTC, mongodben commented on examples/react-native/__tests__/ts/sync/check-upload-download-progress.test.tsx
> +// TODO: create JS only version
TODONE. will delete these 😄

2023-02-24 16:44 UTC, mongodben commented on examples/react-native/__tests__/ts/sync/check-upload-download-progress.test.tsx
> +  const [uploadProgressPercent, setUploadProgressPercent] = React.useState(0);
i'll add that to the code example cleanup ticket.

i think we can probably find an ESLint rule to enforce one of the styles. no strong personal preference on which.

2023-02-24 16:48 UTC, mongodben commented on examples/react-native/__tests__/ts/sync/check-network-connection.test.tsx
> +// TODO: create a JS-only example b/c of type of callback :(
```suggestion
```

2023-02-24 16:48 UTC, mongodben commented on examples/react-native/__tests__/ts/sync/check-upload-download-progress.test.tsx
> +// TODO: create JS only version
```suggestion
```

2023-02-24 16:49 UTC, mongodben commented on examples/react-native/__tests__/js/sync/check-upload-download-progress.test.jsx
> +// TODO: create JS only version
```suggestion
```

2023-02-24 16:55 UTC, mongodben commented on source/sdk/react-native/sync-data/manage-sync-session.txt
> +To listen for connection state changes, call :js-sdk:`Realm.syncSession.addConnectionNotification()
will shift these to be just `SyncSession.<method>()`

2023-02-24 16:57 UTC, mongodben commented on source/sdk/react-native/sync-data/manage-sync-session.txt
> +:js-sdk:`syncSession.resume() <Realm.App.Sync.Session.html#~resume>` method.
```suggestion
To pause synchronization, use the :js-sdk:`Realm.syncSession.pause()
<Realm.App.Sync.Session.html#~pause>` method. To resume synchronization, use the
:js-sdk:`Realm.syncSession.resume() <Realm.App.Sync.Session.html#~resume>` method.
```

2023-02-24 16:57 UTC, mongodben commented on source/sdk/react-native/sync-data/manage-sync-session.txt
> +The ``syncSession.addProgressNotification()`` method takes in the following three parameters:
```suggestion
notification using the :js-sdk:`Realm.syncSession.addProgressNotification() <Realm.App.Sync.Session.html#.addProgressNotification>` method.

The ``Realm.syncSession.addProgressNotification()`` method takes in the following three parameters:
```

2023-02-24 16:58 UTC, mongodben commented on source/sdk/react-native/sync-data/manage-sync-session.txt
> +  :js-sdk:`syncSession.removeProgressNotification() <Realm.App.Sync.Session.html#.removeProgressNotification>`.
```suggestion
  :js-sdk:`Realm.syncSession.removeProgressNotification() <Realm.App.Sync.Session.html#.removeProgressNotification>`.
```

2023-02-24 17:34 UTC, merged