(DOCSP-27003): @realm/react-ify Authenticate Users page
mongodb/docs-realm pull request #2590
Opened 2023-02-14 21:04 UTC by mongodben

## Pull Request Info

@realm/react-ify Authenticate Users page

### Jira

- https://jira.mongodb.org/browse/DOCSP-27003

### Staged Changes

- [Authenticate Users (RN)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-27003/sdk/react-native/manage-users/authenticate-users/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [x] Create Jira ticket for corresponding docs-app-services update(s), if any
- [x] Checked/updated Admin API
- [x] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-02-15 18:34 UTC, krollins-mdb reviewed
Looking good! I have some suggestions, but only one of them is of particular import.

2023-02-15 18:34 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +Prerequisites
Do we have a preference for when to use "Prerequisites" vs "Before You Begin"?

2023-02-15 18:34 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +Configure User Authentication in App
The "App" here could refer to several things: the App Services App, `Realm.App`, or be conflated with "in-app". Do we need the specificity? If so, would "in a Client" work?

2023-02-15 18:34 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +Configure user authentication with the ``AppProvider`` and ``UserProvider`` components
[important] We haven't mentioned `@realm/react` yet, and these things are specific to the library. Also, add angle brackets for components, as discussed in the User API Keys PR.
```suggestion
Configure user authentication with the ``@realm/react`` ``<AppProvider>`` and ``<UserProvider>`` components
```

2023-02-15 18:34 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +To set up user authentication, perform the following:
Minor style suggestion:
```suggestion
To set up user authentication:
```

2023-02-15 18:34 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +Configure user authentication with the ``AppProvider`` and ``UserProvider`` components
We should add angle brackets for other instances of the components too.

2023-02-15 18:34 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +#. Wrap all components you want to use with App Services in a ``AppProvider`` component.
```suggestion
#. Wrap all components you want to use with App Services in an ``AppProvider`` component.
```

2023-02-15 18:34 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +#. Inside of the ``AppProvider``, wrap all components that you want to have access
Because we used an indefinite article ("a") in the previous step, using a definite article here is a bit confusing. (because an indefinite article means we're not talking about a specific instance)
```suggestion
#. Inside of ``AppProvider``, wrap all components that you want to have access
```

2023-02-15 18:34 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +#. In the ``UserProvider``, include a ``fallback`` prop with another component
```suggestion
#. In ``UserProvider``, include a ``fallback`` prop with another component
```

2023-02-15 18:34 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +#. In the component passed to ``UserProvider.fallback`` prop, authenticate a user
```suggestion
#. In the component passed to the ``UserProvider.fallback`` prop, authenticate a user
```

2023-02-15 18:34 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +Components wrapped by the ``UserProvider`` only render if your app has
```suggestion
Components wrapped by ``UserProvider`` only render if your app has
```

2023-02-15 18:34 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +an authenticated user. These components can access to the authenticated user
```suggestion
an authenticated user. These components can access the authenticated user
```

2023-02-15 18:34 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
Can we remove the example directive on line 219?

2023-02-15 18:42 UTC, mongodben commented on source/sdk/react-native/manage-users/authenticate-users.txt
well i think it's suiting there b/c it's a concrete example whereas the others are more abstract.

2023-02-15 18:42 UTC, mongodben commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +Prerequisites
i think the general rule is:

- "Prerequisites" for reference/explainer content
- "Before You Begin" before procedures

2023-02-15 18:59 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
Fair enough!

2023-02-15 19:00 UTC, krollins-mdb approved these changes

2023-02-20 12:37 UTC, takameyer requested changes
I'd like the google auth example looked over.

2023-02-20 12:37 UTC, takameyer commented on source/sdk/react-native/manage-users/authenticate-users.txt
>  .. code-block:: javascript
I can't seem to find it in this review, but the "Example - Authenticate with Google in React Native" could be refactored.  It tries to call login on `realm` instead of `app`.  Could be using the hooks as well.

2023-02-21 15:24 UTC, mongodben commented on source/sdk/react-native/manage-users/authenticate-users.txt
>  .. code-block:: javascript
thanks for spotting this. the variable was misnamed. fixed in [451a1dd](https://github.com/mongodb/docs-realm/pull/2590/commits/451a1dd56444fe05401ffdfe8b8f68e4ec9a5822)

2023-02-24 11:50 UTC, takameyer approved these changes

2023-02-24 14:06 UTC, merged