DOCSP-23431 Continuous defragmentation note
mongodb/docs-realm pull request #2620
Opened 2023-02-23 16:51 UTC by lindseymoore

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-23431

### Staged Changes

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-23431/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [ ] Create Jira ticket for corresponding docs-app-services update(s), if any
- [ ] Checked/updated Admin API
- [ ] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-02-23 18:32 UTC, mongodben commented on source/sdk/dotnet/realm-files/compact-realm.txt
> +
i think it's worth reconsidering how this information is contextualized in the page. 

as i understand this feature, most apps never need to implement compaction b/c of this feature. 

the content in the 'Compaction Options' section is only relevant if you have some manual compaction needs. therefore i think it'd be good to do the following:

- rename 'Compaction Options' to 'Manual Compaction Options'
- make clear at the beginning of the section that you generally don't need to do manual compaction. 
- move the content from this note higher up on the page and make clear that this functionality means that you probably don't need to implement the Manual Compaction Options


honestly, i'm not sure what the reasons for doing manual compaction would be. might be worth talking with engineering to figure out when we should guide users t o

2023-02-23 18:34 UTC, mongodben commented on source/sdk/dotnet/realm-files/compact-realm.txt
> +
applies to all other pages as well.

2023-02-23 18:34 UTC, mongodben reviewed
good start. please see note on the .NET page for additional direction.

2023-03-01 15:24 UTC, mongodben commented on source/sdk/flutter/realm-database/realm-files/compact.txt
> +unused file space. Files are automatically compacted once free space is twice the size
> As of Flutter version 0.9.0 and up, Realm files are automatically compacted in the background by continuously reallocating data in the file and removing 
unused file space.

i recommend splitting this idea into 2 sentences. the second part "by continuously reallocating data in the file and removing unused file space" is an implementation detail that most users probably don't care about. perhaps putting this idea in a second paragraph, focusing the first paragraph on just the behavior (which is all that's relevant for most all users).

2023-03-01 15:25 UTC, mongodben commented on source/sdk/flutter/realm-database/realm-files/compact.txt
> +background by continuously reallocating data in the file and removing
> Realm files are automatically compacted in the background

please rephrase to active voice. perhaps smthn like: "the SDK automatically compacts Realm files in the background"

2023-03-01 15:26 UTC, mongodben commented on source/sdk/flutter/realm-database/realm-files/compact.txt
> +the file is not being accessed.
```suggestion
of Realm user data in the file. Automatic compaction only takes place when
the file is not being accessed. 
```

2023-03-01 15:27 UTC, mongodben commented on source/sdk/flutter/realm-database/realm-files/compact.txt
> +   if this automatic compaction threshold is not sufficient for your application.
i don't think this should be in a note. it's a pretty important idea to understanding why to use manual compaction. i suggest putting this as the first paragraph

2023-03-01 15:27 UTC, mongodben commented on source/sdk/flutter/realm-database/realm-files/compact.txt
> +   if this automatic compaction threshold is not sufficient for your application.
> Automatic compaction begins once free space in the file is twice the size of user data in the file.

i don't understand what this means. can you clarify?

2023-03-01 15:28 UTC, mongodben reviewed
back to you w some additional suggestion. looking better!

2023-03-01 22:36 UTC, lindseymoore commented on source/sdk/flutter/realm-database/realm-files/compact.txt
> +unused file space. Files are automatically compacted once free space is twice the size
Made slightly shorter with active voice, is the sentence more digestible now?

2023-03-03 18:58 UTC, mongodben commented on source/sdk/flutter/realm-database/realm-files/compact.txt
> +In most circumstances, automatic compaction will be sufficient for minimizing
```suggestion
In most circumstances, automatic compaction is sufficient for minimizing
```

2023-03-03 19:00 UTC, mongodben commented on source/sdk/flutter/realm-database/realm-files/compact.txt
> +application needs, such as if your SDK does not support automatic compaction.
```suggestion
application needs or if you're using an older version of the SDK
that does not support automatic compaction.
```

2023-03-03 19:01 UTC, mongodben reviewed
flutter page looks better. few suggestion. once changes are applied to other pages, i can review again

2023-03-15 22:01 UTC, dacharyc requested changes
I've got a few grammar comments, as well as suggestions about being more specific about when to use manual vs. automatic compacting. 

More broadly, I'm not a fan of changing the section names to "Compaction" - a feature name - because the sections are currently named more generally for what this feature does - "Reduce Realm File Size." When developers are talking about file size problems, they use the term (and search for the term) "file size." If we remove that language and instead use a feature name, that makes the information less discoverable for developers who don't know the magic feature name.

2023-03-17 16:43 UTC, dacharyc approved these changes
I think the `.. note::` directive in the `source/includes/manual-compaction-note.rst` file has some formatting issues that should be fixed before merging this PR. But overall I think this LGTM after you fix those formatting issues!

2023-03-17 16:43 UTC, dacharyc commented on source/includes/manual-compaction-note.rst
> +    Automatic compaction is sufficient for minimizing
As a convention, we typically leave a blank line between the directive tag and the directive content.

Also, the directive contents should have three spaces at the start of each line. i.e. they should line up with the first character in the directive tag. So "Automatic" and all the lines below it should align with the `n` in `.. note::`. I think it looks like 4 spaces here?

If you've seen the "Marking up" presentation, it has information about how to format directives. Let me know if you need the link!

2023-03-20 13:23 UTC, mongodben commented on source/includes/manual-compaction-note.rst
> +   for most applications. However, automatic compaction begins when the
> Automatic compaction is sufficient for minimizing the Realm file size for most applications.

this seems like important info worth having higher up on the page.

2023-03-20 13:25 UTC, mongodben commented on source/includes/manual-compaction-note.rst
> +   size of unused space in the file is more than twice the size of user
>  However, automatic compaction begins when the size of unused space in the file is more than twice the size of user data in the file.

this is just about automatic compaction. i think it should be in the automatic compaction section, not an easily missable note in manual compaction section

2023-03-20 13:27 UTC, mongodben commented on source/includes/manual-compaction-note.rst
> +   data in the file. Manual compaction can be used for applications that
> Manual compaction can be used for applications that requires stricter management of file size or that use an older version of the SDK that does not support automatic compaction.

i don't think this should be in a note. it's pretty important info to understanding why you'd want to do manual compaction. i think you could just make this 1st sentence of the 'Manual Compaction Strategies' section

2023-03-20 18:35 UTC, lindseymoore commented on source/includes/manual-compaction-note.rst
> +   size of unused space in the file is more than twice the size of user
I could move the note after the description of automatic compaction?

2023-03-20 20:36 UTC, mongodben commented on source/sdk/flutter/realm-database/realm-files/compact.txt
> +implement manual compaction to periodically reduce the realm file size.
> A production application should 
implement manual compaction to periodically reduce the realm file size.

i believe this is not true. i think it was only nec before automatic compaction was a thing.

2023-03-20 20:38 UTC, mongodben commented on source/sdk/flutter/realm-database/realm-files/compact.txt
> +----------------------------
why doesn't this section use the include `manual-compaction-note.rst`?

2023-03-20 20:39 UTC, mongodben commented on source/includes/manual-compaction-note.rst
> +Manual compaction can be used for applications that
nit: i'd rename this file to `manual-compaction.rst` b/c it doesn't include a note directive anymore.

2023-03-20 21:10 UTC, lindseymoore commented on source/sdk/flutter/realm-database/realm-files/compact.txt
> +----------------------------
The note included the portion about not using automatic compaction if you "use an older version of the SDK that does not support automatic compaction". This doesn't apply to Flutter since it implemented Automatic pre-GA, but should apply to the other SDKs.

2023-03-20 21:25 UTC, mongodben commented on source/sdk/flutter/realm-database/realm-files/compact.txt
> +if automatic compaction is not used.
active voice

```suggestion
if it does not use automatic compaction.
```

2023-03-20 21:26 UTC, mongodben approved these changes
lgtm w 1 suggestion

2023-03-21 13:51 UTC, merged