(DOCSP-26500): Add Set the Client Log Level - Kotlin SDK page
mongodb/docs-realm pull request #2676
Opened 2023-03-22 15:56 UTC by cbullinger

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-26500

### Staged Changes

- [Set the Client Log Level - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-26500-log-level/sdk/kotlin/sync/log-level/) - new page

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [x] Create Jira ticket for corresponding docs-app-services update(s), if any
- [x] Checked/updated Admin API
- [x] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-03-22 19:16 UTC, dacharyc requested changes
We should tweak the "enum" wording because it's not quite right, and I also wonder if we want to elaborate on the custom logger example, or at least add a link to the API reference.

2023-03-22 19:16 UTC, dacharyc commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
> +                .log(LogLevel.ALL, customLoggers = listOf(customLogger))
There's no example of what this `customLogger` might look like, and I didn't see a link to anything describing what this implementation should be. It looks like `customLoggers` is a list of RealmLogger objects, so I wonder if we want to link to [RealmLogger](https://www.mongodb.com/docs/realm-sdks/kotlin/latest/library-base/-realm%20-kotlin%20-s-d-k/io.realm.kotlin.log/-realm-logger/index.html) copy that goes along with this example. Additionally, I wonder if we want to provide just a basic placeholder `customLogger` to show what that might look like, similar to [the Swift example](https://github.com/mongodb/docs-realm/blob/272fe781ac6d65e21eefc7b54879b1d321faec87/examples/ios/Examples/Sync.swift#L364). (Just showing that this exposes a LogLevel and a String message, plus whatever additional stuff you want to throw in.)

2023-03-24 15:12 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
> +                .log(LogLevel.ALL, customLoggers = listOf(customLogger))
Updated to include link to RealmLogger docs and example to better match Swift (sdk engg didn't think it necessary to include more than that -- e.g. full custom logger implementation/logic)

2023-03-24 16:03 UTC, dacharyc approved these changes
Overall LGTM, just a Q about the page title and the ToC entry.

2023-03-24 16:03 UTC, dacharyc commented on source/sdk/kotlin/sync/log-level.txt
> +Set the Client Log Level - Kotlin SDK
I notice in the ToC we call this "Set the Sync Log Level" - should we update the title here to match?

2023-03-24 16:19 UTC, cbullinger commented on source/sdk/kotlin/sync/log-level.txt
> +Set the Client Log Level - Kotlin SDK
Was on purpose, but I changed TOC entry to match page title

2023-03-24 17:35 UTC, merged