(DOCSP-26752): Add new Custom User Data - Kotlin SDK page
mongodb/docs-realm pull request #2695
Opened 2023-03-28 16:34 UTC by cbullinger

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-26752

### Staged Changes

- [Custom User Data - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-26752-user-custom-data/sdk/kotlin/app-services/custom-user-data/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [x] Create Jira ticket for corresponding docs-app-services update(s), if any - see [DOCSP-28852](https://jira.mongodb.org/browse/DOCSP-28852)
- [x] Checked/updated Admin API
- [x] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-03-28 19:37 UTC, krollins-mdb approved these changes
Looks good! I do have some non-blocking style suggestions you should consider.

2023-03-28 19:37 UTC, krollins-mdb commented on source/sdk/kotlin/app-services/custom-user-data.txt
> +with Atlas App Services.
We may want to be more specific, as you can do more than store the data.

```suggestion
You can read, write, and delete :ref:`custom user data <custom-user-data>` about your users 
with Atlas App Services. 
```

2023-03-28 19:37 UTC, krollins-mdb commented on source/sdk/kotlin/app-services/custom-user-data.txt
> +Before writing and reading this data, you must enable custom user data in the backend.
I think we should specify that this is in the App Services App. "Backend" could potentially be confused for the Atlas cluster.
```suggestion
Before writing and reading this data, you must enable custom user data in your App Services App. 
```

2023-03-28 19:37 UTC, krollins-mdb commented on source/sdk/kotlin/app-services/custom-user-data.txt
> +   Currently you can only read custom user data with the Kotlin SDK.
```suggestion
   Currently, you can only read custom user data with the Kotlin SDK.
```

2023-03-28 19:37 UTC, krollins-mdb commented on source/sdk/kotlin/app-services/custom-user-data.txt
> +user custom data document immediately when underlying data changes.
```suggestion
custom user data document immediately when underlying data changes.
```

2023-03-28 19:37 UTC, krollins-mdb commented on source/sdk/kotlin/app-services/custom-user-data.txt
> +Read a User's Custom Data
The construction of headings on this page is inconsistent:
- Read a User's Custom Data
- Write Custom User Data with Atlas Functions
- Delete A User's Custom Data with Atlas Functions

I suggest shortening the first and last to:
- Read Custom User Data
- Delete Custom User Data with Atlas Functions

2023-03-28 19:37 UTC, krollins-mdb commented on source/sdk/kotlin/app-services/custom-user-data.txt
> +Custom user data is stored in a document linked to the user object.
Do we have anything that `user object` could link to? Or define more here? First use on the page, and it may not be clear to readers what we're talking about.

2023-03-28 19:37 UTC, krollins-mdb commented on source/sdk/kotlin/app-services/custom-user-data.txt
> +(e.g. to comply with :apple:`Apple's account deletion requirements <support/offering-account-deletion-in-your-app/>`).
Try to avoid Latin:
```suggestion
(For example, to comply with :apple:`Apple's account deletion requirements <support/offering-account-deletion-in-your-app/>`). 
```

2023-03-28 19:37 UTC, krollins-mdb commented on source/sdk/kotlin/app-services/custom-user-data.txt
> +:ref:`Deleting a user <kotlin-delete-users>` does *not* delete the custom user data.
I think this may warrant an `important` admonition.

2023-03-28 20:07 UTC, cbullinger commented on source/sdk/kotlin/app-services/custom-user-data.txt
> +Custom user data is stored in a document linked to the user object.
Added link

2023-03-31 22:02 UTC, clementetb requested changes
Looks good except for a minor change.

2023-03-31 22:02 UTC, clementetb commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
> +            val updatedCustomData = user.refreshCustomData()
`refreshCustomData` does not return any value, it just updates the custom data cached value that is stored internally by Realm.

The reason behind this decision is that `refreshCustomData` is a suspend function as it has to perform some network request to fetch the updated custom data and `customDataAsBsonDocument` is not, as it has direct access to the cached data.

```suggestion
            user.refreshCustomData()
            
            val userData = user.customDataAsBsonDocument()
            displayUserName(userData[USER_NAME]) 
```

2023-04-03 14:44 UTC, merged