(DOCSP-25431): Kotlin Client Reset
mongodb/docs-realm pull request #2714
Opened 2023-04-05 21:46 UTC by cbullinger

## Pull Request Info

Add new Handle Sync Errors - Kotlin SDK page to document client reset recovery

### Jira

- https://jira.mongodb.org/browse/DOCSP-25431

### Staged Changes

- [Handle Sync Errors](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-25431-kotlin-client-reset/sdk/kotlin/sync/handle-sync-errors/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [x] Create Jira ticket for corresponding docs-app-services update(s), if any - see [DOCSP-28993](https://jira.mongodb.org/browse/DOCSP-28993)
- [x] Checked/updated Admin API
- [x] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-05-01 18:31 UTC, dacharyc requested changes
Nice work! This is a tricky topic but you've got almost all the pieces in place here. I spotted a handful of typo fixes, and have a few Qs about other possible changes, but this is a great start.

2023-05-01 18:31 UTC, dacharyc commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +The following strategies support automatic client resets:
It might be nice to add something here linking to the AutomaticClientResetStrategy interface: https://www.mongodb.com/docs/realm-sdks/kotlin/latest/library-sync/-realm%20-kotlin%20-s-d-k%20-%20-sync/io.realm.kotlin.mongodb.sync/-automatic-client-reset-strategy/index.html

2023-05-01 18:31 UTC, dacharyc commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +  unsynced changes strategy, which deletes all unsynced local
I just noticed that "permanently deletes" is italicized below and think it probably should be here, too, for consistency.
```suggestion
  unsynced changes strategy, which *permanently deletes* all unsynced local 
```

2023-05-01 18:31 UTC, dacharyc commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +If your app requires specific client reset logic that can't be
If you do add a link to the AutomaticClientResetStrategy above, it probably makes sense to add a link to the ManuallyRecoverUnsyncedChangesStrategy here: https://www.mongodb.com/docs/realm-sdks/kotlin/latest/library-sync/-realm%20-kotlin%20-s-d-k%20-%20-sync/io.realm.kotlin.mongodb.sync/-manually-recover-unsynced-changes-strategy/index.html

2023-05-01 18:31 UTC, dacharyc commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +fall back to a discard local changes if the automatic recovery fails.
```suggestion
fall back to discard local changes if the automatic recovery fails. 
```

2023-05-01 18:31 UTC, dacharyc commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +Instead, it falls back to manually recover changes.
I wonder if we want to add something here like: "You might choose this client reset strategy if your app cannot lose unsynced data." I think we cover that fairly well up above, so it might be unnecessarily repetitive to say it here?

2023-05-01 18:31 UTC, dacharyc commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +  Invoked only if the automatic recovery and the discard strategy have
This one doesn't have discard - only automatic recovery.
```suggestion
  Invoked only if the automatic recovery strategy has 
```

2023-05-01 18:31 UTC, dacharyc commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +not consistency with the Device Sync :ref:`Client Recovery Rules <kotlin-client-reset-recovery-rules>`
```suggestion
not consistent with the Device Sync :ref:`Client Recovery Rules <kotlin-client-reset-recovery-rules>`
```

2023-05-01 18:31 UTC, dacharyc commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/ClientResetTest.kt
> +package com.mongodb.realm.realmkmmapp
It looks like you've handled the code examples in the `SyncTest` so should we discard this file?

2023-05-02 11:40 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
> +            // :snippet-end:
Good catch! Updated

2023-05-02 11:45 UTC, cbullinger commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +The following strategies support automatic client resets:
Added

2023-05-02 11:45 UTC, cbullinger commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +  unsynced changes strategy, which deletes all unsynced local
Updated

2023-05-02 11:47 UTC, cbullinger commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +If your app requires specific client reset logic that can't be
Added

2023-05-02 11:48 UTC, cbullinger commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +fall back to a discard local changes if the automatic recovery fails.
Good catch

2023-05-02 11:49 UTC, cbullinger commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +Instead, it falls back to manually recover changes.
I don't think it hurts to reiterate it here. Added

2023-05-02 11:50 UTC, cbullinger commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +  Invoked only if the automatic recovery and the discard strategy have
Bad copy-paste error. Great catch

2023-05-02 11:50 UTC, cbullinger commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +not consistency with the Device Sync :ref:`Client Recovery Rules <kotlin-client-reset-recovery-rules>`
Corrected

2023-05-02 11:51 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/ClientResetTest.kt
> +package com.mongodb.realm.realmkmmapp
Yes, this is no longer needed. Thanks for checking

2023-05-02 13:40 UTC, dacharyc approved these changes
One more tiny change, but it's really just a nit. Otherwise LGTM - nice work!

2023-05-02 13:40 UTC, dacharyc commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
> +        // Proceed to open a realm...
I think we would open a realm inside the `runBlocking` block, so probably should move this comment up above the bracket?

2023-05-02 13:42 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
> +        // Proceed to open a realm...
Moved up

2023-05-03 15:26 UTC, clementetb commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
> +                Log.i("Client reset: recovery unsuccessful, all unsynced changes were discarded")
Here the user might try to attempt a manual recover moving data from the before instance to the after instance.

```kotlin
override fun onAfterDiscard(before: TypedRealm, after: MutableRealm) {
    Log.i("Client reset: recovery unsuccessful, trying to manually recover any changes")

    // we can try to manually recover any unsynced data
    manuallyRecoverUnsyncedData(before, after)
}
```

2023-05-03 15:26 UTC, clementetb commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
> +                // ... Handle the reset manually here
Here we recommend making a backup of the Realm file invoking: `ClientResetRequiredException.executeClientReset`. 

```kotlin
override fun onManualResetFallback(
                session: SyncSession,
                exception: ClientResetRequiredException
) {
    Log.i("Client reset: manual reset required")

    // we must close any open Realm instance
    closeAllRealmInstances();

    // this method creates a backup
    exception.executeClientReset();
    
    // here we could send it up for analysis
    handleBackup(recoveryFilePath);

    // restore the App state reopening the Realms / or restart the app
}

```

2023-05-03 15:26 UTC, clementetb commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
> +                // ... Handle the reset manually here
Here a backup

2023-05-03 15:26 UTC, clementetb commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
> +                Log.i("Client reset: manual reset required")
Here a backup

2023-05-03 15:26 UTC, clementetb commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
> +                Log.i("Client reset: successfully recovered all unsynced changes")
Here the user might try to attempt a manual recover moving data from the before instance to the after instance.

```kotlin
override fun onAfterReset(before: TypedRealm, after: MutableRealm) {
    Log.i("Client reset: trying to manually recover any changes")

    // we can try to manually recover any unsynced data
    manuallyRecoverUnsyncedData(before, after)
}
```

2023-05-03 15:26 UTC, clementetb commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
> +                Log.i("Client reset: attempting to automatically recover unsynced changes")
```suggestion
                Log.i("Client reset: attempting to discard any unsynced changes")
```

2023-05-03 15:26 UTC, clementetb commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +If the client reset cannot complete automatically, such as when there are
It discards the local changes and allows the user to create a backup of the local Realm.

2023-05-05 11:28 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
> +                Log.i("Client reset: attempting to automatically recover unsynced changes")
Updated

2023-05-05 11:28 UTC, cbullinger commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +If the client reset cannot complete automatically, such as when there are
Added

2023-05-05 11:28 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
> +                Log.i("Client reset: successfully recovered all unsynced changes")
Added

2023-05-05 11:28 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncTest.kt
> +                // ... Handle the reset manually here
Added

2023-05-05 11:31 UTC, cbullinger commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +  Allows you to implement your own manual recovery strategy.
Added

2023-05-05 11:31 UTC, cbullinger commented on source/sdk/kotlin/sync/handle-sync-errors.txt
> +  made since the last successful sync. If recovery fails, this
Added

2023-05-05 11:49 UTC, merged