(DOCSP-28375) Add info about opening a realm with no schema
mongodb/docs-realm pull request #2753
Opened 2023-04-24 19:31 UTC by krollins-mdb

## Pull Request Info

Adds info and tests/examples about how to open a realm without passing in schema as part of the config object. Also, refactored some unnecessary includes for the Node.js page.

The Node.js test is failing in CI, but works locally. This test file needs a bunch of work, and the Node.js CI is flaky. I can look into as part of this PR if we think it's necessary, but I'd rather cut a ticket to focus on fixing all the tests in that file.

### Jira

- https://jira.mongodb.org/browse/DOCSP-28375

### Staged Changes

- React Native: [Configure a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28375/sdk/react-native/realm-files/configure-a-realm/#access-a-realm-without-providing-a-schema)
- Node.js: [Open & Close a Realm](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28375/sdk/node/realm-files/open-and-close-a-realm/#open-a-realm-without-providing-a-schema)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

### Animal Wearing a Hat

![](https://4.bp.blogspot.com/_zFfOR5W31y4/SOx65YR0_JI/AAAAAAAAAmo/JcsHhDBa7lY/w1200-h630-p-k-no-nu/krakatoaAP_450x300.jpg)

2023-04-24 22:00 UTC, dacharyc requested changes
I checked out this PR locally and was able to replicate the test's flakiness. I got it to fail once and run successfully a handful of times. Bummer about that. I think it makes sense to create a separate ticket to address the flaky tests. Just a handful of small comments and nits.

2023-04-25 15:37 UTC, krollins-mdb commented on examples/node/Examples/open-and-close-a-realm.js
> +    expect(noSchemaRealm instanceof Realm).toBe(true);
Yeah, good point. I really should have just adapted this to our test suite from the beginning.

2023-04-25 15:39 UTC, krollins-mdb commented on examples/react-native/__tests__/ts/realm-database/configure-realm-no-schema.test.tsx
> +import {Realm} from '@realm/react';
Hmm. I need to think about this some more. Definitely harder with React Native. I was trying to keep this simple, but in doing so probably lost any real utility in the example. I'll come up with a more complicated (but realistic) example.

2023-04-25 15:41 UTC, krollins-mdb commented on source/sdk/react-native/realm-files/configure-a-realm.txt
> +After a realm has been created on a device, you don't need to always pass in a
I'm trying to get some clarity on this myself. But, it can be useful for testing at the very least. Could also potentially clean up code because you don't need to import object models into all the files you want to access the realm (and in the case of Realm React, where you don't have access to RealmProvider). But, I need to do some testing to see how that all actually works.

2023-04-25 20:26 UTC, krollins-mdb commented on source/sdk/react-native/realm-files/configure-a-realm.txt
> +After a realm has been created on a device, you don't need to always pass in a
I'm temporarily punting on this aspect. I've asked internally, but haven't gotten a response yet. I can update with some more context in the future if/when I get it. At the very least, it's now clear that this is an option.

2023-04-25 21:47 UTC, krollins-mdb commented on source/sdk/node/realm-files/open-and-close-a-realm.txt
> +``Realm.defaultPath``.
I opted to keep it together. Let me know what you think.

2023-04-25 21:51 UTC, dacharyc approved these changes
LGTM - nice improvements, and nice work!

2023-04-25 21:57 UTC, dacharyc commented on source/sdk/node/realm-files/open-and-close-a-realm.txt
> +``Realm.defaultPath``.
Works for me. It's nice and clear and it didn't feel too verbose on the page.

2023-04-27 18:05 UTC, merged