Add nullability info to .NET docs
mongodb/docs-realm pull request #2756
Opened 2023-04-25 21:17 UTC by MongoCaleb

## Pull Request Info

### Jira

https://jira.mongodb.org/browse/DOCSP-27348

### Staged Changes

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/nullability/sdk/dotnet/model-data/define-object-model/#required-and-optional-properties

This PR also includes moving the Data Binding MVVM to a more appropriate location (https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/nullability/sdk/dotnet/model-data/data-binding/#data-binding-and-mvvm). There are no content changes.

2023-04-26 18:00 UTC, dacharyc approved these changes
Overall, no big blockers. There are a handful of grammar nits, though, and a few questions about things we might want to consider refining.

2023-04-26 18:00 UTC, dacharyc commented on source/sdk/dotnet/model-data/define-object-model.txt
> +`?  <https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types>`__.
Nit: having just the `?` here as the source of a link looks odd to me on the page. I wonder if, in this case, we want to just make this monospace and then add a line explicitly calling out what the link entails? Ala:

```suggestion
In C#, value types are implicitly non-nullable, but can be made optional by appending ``?``.
For more information, refer to the `Nullable Value Types C# Reference documentation. <https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types>`__
```

2023-04-26 18:00 UTC, dacharyc commented on source/sdk/dotnet/model-data/define-object-model.txt
> +The Realm .NET SDK fully supports the nullable aware context and uses nullability
```suggestion
The Realm .NET SDK fully supports the nullable-aware context and uses nullability 
```

2023-04-26 18:00 UTC, dacharyc commented on source/sdk/dotnet/model-data/define-object-model.txt
> +`nullable aware context <https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types>`__.
Nit: I see that the C# docs are missing it, but I think "nullable-aware" should be hyphenated in this case because it's a compound adjective that modifies context.

```suggestion
`nullable-aware context <https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types>`__.
```

2023-04-26 18:00 UTC, dacharyc commented on source/sdk/dotnet/model-data/define-object-model.txt
> +  (by using ``?``), Realm considers them optional.
Nit: I don't think these are strictly required, and generally writing style guides call for leaving them out when they're not needed.

```suggestion
  by using ``?``, Realm considers them optional.
```

2023-04-26 18:53 UTC, MongoCaleb commented on source/sdk/dotnet/model-data/data-binding.txt
> +Data Binding and MVVM
Good point. It definitely has a fit in both places. I'll add a link.

2023-04-26 18:58 UTC, MongoCaleb commented on source/sdk/dotnet/model-data/define-object-model.txt
> +`?  <https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types>`__.
Good point, You suggest feels a bit busy and highlights the external link more than I like. I hope this change works better!

2023-04-26 19:00 UTC, MongoCaleb commented on examples/dotnet/Examples/NullabilityTest.cs
> +        //public Dog ANonNullableDog { get; set; } // Compile-time error
great points

2023-04-27 06:52 UTC, papafe commented on source/sdk/dotnet/model-data/define-object-model.txt
> +In C#, value types are implicitly non-nullable, but can be made optional by using
```suggestion
In C#, value types (such as ``int`` or ``bool``) are implicitly non-nullable, but can be made optional by using 
```

2023-04-27 07:28 UTC, papafe requested changes

2023-04-27 07:28 UTC, papafe commented on source/sdk/dotnet/model-data/define-object-model.txt
> +  - If the collection contains a list of primatives, the primatives *can* be
I think it makes sense to move this to his own bullet point

2023-04-27 07:28 UTC, papafe commented on source/sdk/dotnet/model-data/define-object-model.txt
> +- You cannot declare dictionaries as nullable, but their values are inherently
I think we need to restructure this bullet points regarding collections/objects, because it's a little confusing the part regarding collections and objects.

An idea:

- Collections (list, sets, dictionaries, and backlinks) will never be null, and thus they cannot be declared nullable, but their parameters may be:
	- Value types (int, bool, ...) and string, byte[] can be declared as nullable or not, depending if it's a required property or not. 
	- Lists, sets, and backlinks of Realm objects cannot contain null values, and thus the type parameter must be non-nullable.
	- Dictionaries of Realm object values can contain null, and thus the value type parameter must be nullable

2023-04-27 07:28 UTC, papafe commented on source/sdk/dotnet/model-data/define-object-model.txt
> +   If your classes derive from the ``RealmObject`` base class, the rules above do
I would say something like:

"If you are using the old schema types definition (link) with classes deriving from "RealmObject", or you do not have nullability annotations enabled, then you need to use the `[Required]` attribute with `string` and `byte[]` properties to specify if they are required

2023-04-27 07:28 UTC, papafe commented on source/sdk/dotnet/model-data/define-object-model.txt
> +
We need to add a note also about this (taken from the blog post):

We realize that some developers would prefer to have more freedom in the nullability annotation of Realm object properties, and it is possible to do so by setting realm.ignore_objects_nullability = true in a global configuration file (more information about this can be found in the 
[.NET documentation](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files)
). If this option is enabled, all the Realm object properties (including collections) will be considered valid, and the nullability annotations will be ignored.

2023-04-27 07:28 UTC, papafe commented on source/examples/generated/dotnet/NullabilityTest.snippet.nullability.cs
> +    /* Collections of Primatives */
```suggestion
    /* Collections of Primitives */
```

2023-04-27 07:28 UTC, papafe commented on source/examples/generated/dotnet/NullabilityTest.snippet.nullability.cs
> +    /* Reference Types */
I would also add a small section with value types:

public int? NullableInt {get; set;}
public int NonNullableInt {get; set;}

2023-04-27 07:28 UTC, papafe commented on source/examples/generated/dotnet/NullabilityTest.snippet.nullability.cs
> +    public IList<int> RequiredIntList { get; }
I would call this IntListWithNonNullableValues, to be consistent

Also probably we should either called them all NonNullable or Required (I'd go for the first)

2023-04-27 07:28 UTC, papafe commented on source/examples/generated/dotnet/NullabilityTest.snippet.nullability.cs
> +    public IDictionary<string, Dog> MyDictionaryOfNonNullableObjects { get; }
This line is not supported

2023-04-27 07:28 UTC, papafe commented on source/examples/generated/dotnet/NullabilityTest.snippet.nullability.cs
> +    public IDictionary<string, Dog?> MyDictionaryOfNullableObjects { get; }
Let's put a space between the different collection types, and add examples for sets and backlinks

2023-04-27 07:34 UTC, papafe commented
Apart from the comments I've left, I think we need a couple things more:

- Check all the code snippets that we have and use the correct nullability annotations
- Add another note somewhere about the old schema type (this could be done in another PR too)

Regarding the second point, we need to say something like:

Prior to Realm .NET version 10.18.0, all realm objects had to be declared as derived from "RealmObject", "EmbeddedObject" and "AsymmetricObject". The classic Realm model definition is still supported, but it will not receive some of the new updates, such as the support for nullability annotations, and will be phased out in the future. For this reason we really recommend migrating to the new interface based class definitions (classes need to be declared implementing IRealmObject, IEmbeddedObject or IAsymmetricObject). 
(Here we could just copy the section about how to migrate from the blog post: https://www.mongodb.com/developer/products/realm/source-generated-classes-nullability-realm/)

2023-04-27 16:23 UTC, MongoCaleb commented on source/sdk/dotnet/model-data/define-object-model.txt
> +  - If the collection contains a list of primatives, the primatives *can* be
doh! Good catch!

2023-04-27 16:36 UTC, MongoCaleb commented on source/examples/generated/dotnet/NullabilityTest.snippet.nullability.cs
> +    public IDictionary<string, Dog> MyDictionaryOfNonNullableObjects { get; }
@papafe These all compile and run correctly. I raised this in the thread in the ask-sdks channel; I think it's an oversight/bug in the SDK.

2023-04-27 16:52 UTC, MongoCaleb commented on source/examples/generated/dotnet/NullabilityTest.snippet.nullability.cs
> +    public IDictionary<string, Dog> MyDictionaryOfNonNullableObjects { get; }
Interestingly, it doesn't compile with Set<> or Backlink, so it must just be an issue with the Dictionary implementation.

2023-04-27 17:46 UTC, MongoCaleb commented
@papafe I think I've addressed all of your comments. Note my comment about an apparent bug in the Dictionary implementation.

2023-04-28 08:01 UTC, papafe requested changes

2023-04-28 08:02 UTC, papafe commented on source/sdk/dotnet/model-data/define-object-model.txt
> +   projects. For older projects, need to manually enable it. For more information,
Or "it needs to be manually enabled"

2023-04-28 08:02 UTC, papafe commented on source/examples/generated/dotnet/NullabilityTest.snippet.nullability.cs
> +    public IDictionary<string, Dog> DictionaryOfNonNullableObjects { get; }
And yes, I will create a ticket for the bug you found.

2023-04-28 08:06 UTC, papafe requested changes

2023-04-28 08:06 UTC, papafe commented on source/includes/dotnet-implement-interface.rst
> +   In older versions of the .NET SDK, objects derive from
I would add a note that this is for versions lower than 10.18.0, so it's clear where is the cutoff.

2023-04-28 08:06 UTC, papafe commented on source/includes/dotnet-implement-interface.rst
> +   classes.
What do you think about putting a link to the blog post or just copying it here how to do the conversion? I think it would be quite useful

2023-04-28 08:06 UTC, papafe commented on source/sdk/dotnet/model-data/define-object-model.txt
> +   If you are using the older schema type definition (your classes derive from
Is it possible to add a link that goes to the new section about the old schema type you just added?

2023-04-28 08:07 UTC, papafe commented
After those small changes it looks good for me! 

Another thing that I think we need to do is to change the nullability on all the code snippets in the whole .NET docs, so that we are consistent. I understand that would be a bigger work, so I think we could have it done in a separate PR

2023-04-28 21:19 UTC, merged

2023-04-28 21:25 UTC, MongoCaleb commented on source/sdk/dotnet/model-data/define-object-model.txt
> +   projects. For older projects, need to manually enable it. For more information,
We don't use passive voice, but changed to "can" instead of "need"

2023-05-03 08:49 UTC, papafe commented on source/sdk/dotnet/model-data/define-object-model.txt
> +   If you are using the older schema type definition (your classes derive from
I was referring to the section that starts with "In older versions of the .NET SDK, objects derive from...."