(DOCSP-28928) Document asymmetric sync/stream for Node.js
mongodb/docs-realm pull request #2766
Opened 2023-04-28 02:30 UTC by krollins-mdb

## Pull Request Info

This PR adds a new page to the Node.js SDK docs. It expands on how to implement Data Ingest with asymmetric objects.

Should open another PR for the React Native SDK to update its Stream Data to Atlas page.

Note about Node.js CI test: the `authenticate.js` file is failing a test, but it's not relevant to this PR.

### Jira

- https://jira.mongodb.org/browse/DOCSP-28928

### Staged Changes

- [Stream Data to Atlas](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28798/sdk/node/sync/stream-data-to-atlas/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

### Animal Wearing a Hat

![](https://external-preview.redd.it/MZY3e25I4kI4DaLsvOQdEgDe-W6znz506Je-XLCGmVA.jpg?auto=webp&s=90cc5c706f47c2d88a4d8b1837d108e289f52ae3)

2023-04-28 15:08 UTC, dacharyc requested changes
I've left some comments throughout, and have tried using [Blocking] to indicate which ones are blocking vs. which ones should be considered but don't strictly _require_ changes. Let me know if this works for you or if there's another distinction that would be more helpful!

2023-04-28 15:08 UTC, dacharyc commented on source/includes/data-ingest-overview.rst
> +You can use :ref:`Data Ingest <optimize-data-ingest>` to stream
[Blocking] I think it makes sense to refactor this to an include as it is used in multiple places. But if we're changing it on the Swift page, we should probably also apply this change to the C++ and .NET pages.

2023-04-28 15:08 UTC, dacharyc commented on source/sdk/node/model-data/define-a-realm-object-model.txt
>  satisfy this requirement, the application developer defines an invoice
[Blocking] You've updated the examples here to show a weather sensor, but the copy in this paragraph still refers to an invoice. We should update this copy.

2023-04-28 15:08 UTC, dacharyc commented on examples/node/Examples/asymmetric-sync.js
> +    // sync WeatherSensor objects one way from your device
```suggestion
    // Sync WeatherSensor objects one way from your device
```

2023-04-28 15:08 UTC, dacharyc commented on source/sdk/node/sync/stream-data-to-atlas.txt
> +      For more information on how to define an asymmetric object, see:
I suspect this was just a copy-from-Swift situation, but have we decided to avoid "see" verbiage in our docs? I think Ben and I have been refactoring to "refer to" when we come across these instances.

```suggestion
      For more information on how to define an asymmetric object, refer to 
```

2023-04-28 15:22 UTC, krollins-mdb commented on examples/node/Examples/asymmetric-sync.js
> +    await weatherSensorCollection.deleteMany({
Good point! I should test to make sure that there aren't any weatherSensor documents remaining.

Changes to the returned collection do indeed sync back to Atlas. I confirmed it when writing the test by looking in the logs and UI.

2023-04-28 15:56 UTC, krollins-mdb commented on examples/node/Examples/asymmetric-sync.js
> +      deviceId: "WX1278UIT",
Great point! I've refactored to address this.

2023-04-28 15:58 UTC, krollins-mdb commented on examples/node/Examples/asymmetric-sync.js
> +    await weatherSensorCollection.deleteMany({
In the JS SDK, you only get a count of documents deleted, no info about them. So, we can't match _id properties. But we can count how many documents are in the collection. After deleting, it should be 0.

2023-04-28 15:59 UTC, krollins-mdb commented on examples/node/Examples/asymmetric-sync.ts
> +      deviceId: "WX1278UIT",
One of the most annoying things about writing tests for the Realm.js SDKs. We're in a limbo state where we need to duplicate a lot of things for JS and TS.

I'll make sure both are updated.

2023-04-28 17:55 UTC, krollins-mdb commented on source/sdk/node/model-data/define-a-realm-object-model.txt
>  satisfy this requirement, the application developer defines an invoice
Thanks for giving me an excuse to remove that paragraph. I don't think we need elaborate scenarios in this context.

2023-05-01 14:56 UTC, dacharyc approved these changes
Looks good - nice work! Just one Q for my curiosity but doesn't affect merging the PR.

2023-05-01 14:56 UTC, dacharyc commented on examples/node/Examples/asymmetric-sync.js
> +const weatherSensorPrimaryKey = new BSON.ObjectID();
[Non-blocking] This is purely a style question for my edification - is there a reason to define the `weatherSensorPrimaryKey` as a `const` for the entire file instead of just within the test? I have generally been in the habit of defining constants/variables in the smallest scope where they are needed so I'm wondering if that's not the typical practice in JS dev.

2023-05-01 14:56 UTC, dacharyc commented on examples/node/Examples/asymmetric-sync.js
> +    await weatherSensorCollection.deleteMany({
Reasonable approach 👍

2023-05-01 15:16 UTC, krollins-mdb commented on examples/node/Examples/asymmetric-sync.js
> +const weatherSensorPrimaryKey = new BSON.ObjectID();
That's probably better practice. I got in the habit of putting things like this at the highest level when working with multiple tests, but it doesn't need to be all the way at the top.

I'll move it lower in scope, as that does improve readability and puts it closer to its proper context.

2023-05-01 15:21 UTC, krollins-mdb commented on examples/node/Examples/asymmetric-sync.js
> +const weatherSensorPrimaryKey = new BSON.ObjectID();
We haven't really standardized the format for JS tests. Cleaning up all of the tests is on my bucket list. 😄

2023-05-01 15:24 UTC, merged