DOCSP-29577 C++ Link to C++ Filter Page from RQL Page
mongodb/docs-realm pull request #2771
Opened 2023-05-01 21:10 UTC by lindseymoore

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-29577

### Staged Changes

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [ ] Create Jira ticket for corresponding docs-app-services update(s), if any
- [ ] Checked/updated Admin API
- [ ] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-05-01 21:44 UTC, dacharyc requested changes
I think we need to make some updates here, but there's a bit of nuance and background involved. Let me know if you need more info!

2023-05-01 21:44 UTC, dacharyc commented on source/realm-query-language.txt
> +   The Swift SDK and C++ SDK do not support querying with Realm Query Language.
This isn't strictly true. Swift uses NSPredicate. C++ does not use NSPredicate, but does not yet support the full range of RQL expressions as it is currently still in development. We should probably instead just title this note something generic like:

> "Swift and C++" 

And in the note body say something like: 
> "For examples of querying Realm in the Swift SDK or C++ SDK, refer to:"

And then keep the links below.

2023-05-01 21:44 UTC, dacharyc commented on source/sdk/cpp/crud/filter-data.txt
> +  The C++ SDK has not yet implemented sort functionality. Instead, use the
I don't think we want to _recommend_ using `std::sort` necessarily. I think we just want to state that if a developer uses this to sort results, it pulls the results into memory. This is worth calling out here because it's not what they might expect when Realm implements `sort` in C++, and it negates the lazy loading stuff that Realm does. Some developers use C++ _because_ the environment is resource-constrained or performance-constrained, so they'll need to know that using `std::sort` in lieu of Realm implementing sort functionality negates some of the memory benefits of using Realm.

2023-05-02 20:32 UTC, lindseymoore commented on source/realm-query-language.txt
> +   The Swift SDK and C++ SDK do not support querying with Realm Query Language.
Decided to split into two notes, but open to combining!

2023-05-02 20:53 UTC, dacharyc commented on source/realm-query-language.txt
> +   The Swift SDK and C++ SDK do not support querying with Realm Query Language.
After seeing the two notes together on the page, it seems like not the right solution. We try to avoid stacking callouts on top of each other, although there are places where it's unavoidable. But I think we can avoid it here.

Maybe the best option is to just change these tabs starting on ln 34 into a nested bullet list? So remove the tabs entirely, and have bullets like:

```
- C++ SDK

  - :ref:`Filter Data - C++ SDK <cpp-filter-data>`

- Flutter

  - :ref:`Filter & Sort Results - Flutter SDK <flutter-filter-results>`
  
- Java SDK

  - :ref:`Query Engine - Java SDK <java-client-query-engine>`
  - :ref:`Query with Realm Query Language - Java SDK <java-filter-with-realm-query-language>` 
```

The spacing may be a little odd - I know you have to leave a blank line between the first-level indent and second-level indent or it messes up the formatting when it renders on the page. But I don't know if you need a blank line between the second level of indent and the first-level indent of the next SDK. You might have to play with this. When we provide a bullet list of SDKs, we like to keep them in alphabetical order by SDK.

I suggest bullets instead of adding a C++ SDK tab because I think we're at the max tab width here without cutting off the tab names. We've had to go to bullet lists in the App Services docs because the tab names were getting cut off. But I don't think we necessarily need to do anything more in this case than just link out to the C++ page - that page already has a note at the top about not supporting the full range of RQL expressions.

2023-05-02 20:59 UTC, dacharyc commented on source/sdk/cpp/crud/filter-data.txt
> +  performance-constrained environment.
I think the updated version of this note is better, but now we're getting into nitpick territory. I don't think we should start the sentence with "Use `std::sort`" even if we follow that with "with caution", because it sounds like we're advising people to use std::sort and we probably wouldn't recommend that. What about something like:
```suggestion
  The C++ SDK has not yet implemented sort functionality. If you use
  `std::sort <https://en.cppreference.com/w/cpp/algorithm/sort>`__ , 
  this pulls the entire results set into memory. If your data set is 
  large, this could cause problems in a resource-constrained or 
  performance-constrained environment.
```

2023-05-03 19:40 UTC, dacharyc approved these changes
I think it works as a tab, but there's a little bit of grammar weirdness there so we could rewrite it to just bypass that issue. Otherwise LGTM! Thank you for reworking this :)

2023-05-03 19:40 UTC, dacharyc commented on source/realm-query-language.txt
> +    C++ SDK. For examples querying Realm in the C++ SDK, refer to:
As written, this is awkward grammatically. It has some is/are agreement issues (and a typo). We can sidestep this by rewriting slightly:

```suggestion
    The C++ SDK Alpha implements only a subset of RQL. 
    For examples querying Realm in the C++ SDK, refer to:
```

2023-05-03 20:04 UTC, merged