11.0.0 updates
mongodb/docs-realm pull request #2783
Opened 2023-05-10 16:40 UTC by MongoCaleb

## Pull Request Info

### Jira Epic

https://jira.mongodb.org/browse/DOCSP-29725

### Staged Changes

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/foo/sdk/dotnet/model-data/define-object-model/#indexes

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/foo/sdk/dotnet/crud/filter/

2023-05-10 22:50 UTC, lindseymoore requested changes
Some small nits/questions, but overall looks good! I think the structure works for presenting the FTS info.

2023-05-11 09:42 UTC, papafe requested changes

2023-05-11 09:42 UTC, papafe commented on source/sdk/dotnet/model-data/define-object-model.txt
> +In addition to standard indexes, Realm also supports Full Text Search (FTS) on
Two things:
- most of the times it's spelled as "Full-text search" (also in other mongo documentation), so maybe we should keep it wit the dash(hypen?)
- maybe we should add the word "indexes" after (FTS), otherwise it sounds a little confusing

2023-05-11 09:42 UTC, papafe commented on source/sdk/dotnet/model-data/define-object-model.txt
> +attribute. With the ``Indexed`` attribute, you can specify the type of index
A question. This section here talks about how to add the indexes, and it makes totally sense. My only concern is that is seems like it's part of the "Full text search" region, while it's not. 
Is it possible to separate it somehow? I'm not sure exactly how, so feel free to ignore this 😁

2023-05-11 09:42 UTC, papafe commented on source/sdk/dotnet/sync/add-sync-to-app.txt
> +write it to the realm:
```suggestion
add it to the realm:
```

2023-05-11 09:42 UTC, papafe commented on source/sdk/dotnet/model-data/define-object-model.txt
> +``string`` properties. An FTS index enables searching on keywords,
I would remove the phrase "An FTS index enables searching on keywords...", because we actually don't yet support all of that

2023-05-11 09:42 UTC, papafe commented on source/sdk/dotnet/crud/filter.txt
> +=======================================
I am not sure why, but in the staging only the title has changed, but I can't see the rest of the changes.

2023-05-11 09:42 UTC, papafe commented on source/sdk/dotnet/crud/filter.txt
> +.. literalinclude:: /examples/generated/dotnet/Indexing.snippet.linq-query-fts.cs
Let's use "scientist" both in the description and in the query (lowercase s)

2023-05-11 09:42 UTC, papafe commented on source/sdk/dotnet/crud/filter.txt
> +.. literalinclude:: /examples/generated/dotnet/Indexing.snippet.rql-query-fts.cs
Same comment as up

2023-05-11 09:42 UTC, papafe commented on examples/dotnet/Examples/Indexing.cs
> +        public async Task Index()
Yes, if you don't use await inside, you can just make this a void method.

2023-05-11 09:43 UTC, papafe commented
@nirinchev do you want to give a look too in case there is some changes for v 11 that we need to add to the docs?

2023-05-11 10:03 UTC, nirinchev commented on source/sdk/dotnet/model-data/define-object-model.txt
> +``string`` properties. An FTS index enables searching on keywords,
To clarify, we only support simple term matches: https://learn.microsoft.com/en-us/sql/relational-databases/search/query-with-full-text-search?view=sql-server-ver16#Simple_Term. That means that each match must contain all the terms and we don't do any stemming/synonyms/fuzzy matches.

2023-05-11 10:05 UTC, nirinchev commented on source/sdk/dotnet/crud/filter.txt
> +You can use LINQ to query on properties that have Full Text Search (FTS) on
```suggestion
You can use LINQ to query on properties that have Full Text Search (FTS) index on 
```

2023-05-11 16:44 UTC, MongoCaleb commented on source/sdk/dotnet/crud/filter.txt
> +   You should use :ref:`.NET LINQ syntax <dotnet-linq-syntax>` for queries,
Because RQL is so much harder... ;-)

2023-05-11 16:49 UTC, MongoCaleb commented on source/sdk/dotnet/model-data/define-object-model.txt
> +indexes, Realm performs a collection scan (i.e., scan every document in a
Singular in the first case and plural in the second.

2023-05-11 16:52 UTC, MongoCaleb commented on source/sdk/dotnet/model-data/define-object-model.txt
>  To index a property, use the :dotnet-sdk:`[Indexed] <reference/Realms.IndexedAttribute.html>`
Good catch.

2023-05-11 16:56 UTC, MongoCaleb commented on examples/dotnet/Examples/Migrations.cs
> +                        var oldVersionperson = oldVersionPeople.ElementAt(i);
cool!

2023-05-11 18:06 UTC, lindseymoore commented on source/sdk/dotnet/crud/filter.txt
> +   extend beyond LINQ's current capabilities, such as using
```suggestion
   If you require features beyond LINQ's current capabilities, such as aggregation, use RQL.
```

2023-05-11 18:10 UTC, lindseymoore approved these changes
Small grammar nit. Otherwise, LGTM!

2023-05-11 20:52 UTC, dacharyc approved these changes
I've left a handful of comments, but a lot of it is just wordsmithy or personal preference stuff. But there are a couple of spots where I think it might be nice to be more explicit.

2023-05-11 20:52 UTC, dacharyc commented on source/sdk/dotnet/model-data/define-object-model.txt
> +collection) to select the documents that match the given query. However, if an
Why not just simplify?
```suggestion
indexes, Realm scans every document in a collection to select the 
documents that match the given query. However, if an 
```

2023-05-11 20:52 UTC, dacharyc commented on source/sdk/dotnet/model-data/define-object-model.txt
> +appropriate index exists for a query, Realm uses the index to limit the number of
What makes an index "appropriate" for a query? Is there something more specific we could say here, like "applicable"?

2023-05-11 20:52 UTC, dacharyc commented on source/sdk/dotnet/model-data/define-object-model.txt
> +   realm file, so adding an index to a property will increase disk space consumed
Our style guide calls for us to avoid future tense.
```suggestion
   realm file, so adding an index to a property increases disk space consumed
```

2023-05-11 20:52 UTC, dacharyc commented on source/sdk/dotnet/model-data/define-object-model.txt
> +   realm file, so adding an index to a property will increase disk space consumed
Our style guide calls for us to avoid future tense.
```suggestion
   realm file, so adding an index to a property increases disk space consumed
```

2023-05-12 17:20 UTC, MongoCaleb commented on source/sdk/dotnet/model-data/define-object-model.txt
> +on the property by using the :dotnet-sdk:`IndexType <reference/Realms.IndexType.html>`
It's the same as no index; not sure why it was added to the API, but I'm going to opt to not document it. I'll double-check with engineering, though.

2023-05-12 18:27 UTC, MongoCaleb commented on source/sdk/dotnet/model-data/define-object-model.txt
> +   Adding an index can speed up some queries at the cost of slightly slower write
I think line 101 is actually more accurate. While I can't say for sure, I think the original author was thinking "well, an index on field foo doesn't improve search times on field bar."

2023-05-12 18:45 UTC, merged

2023-05-12 18:49 UTC, nirinchev commented on source/sdk/dotnet/model-data/define-object-model.txt
> +on the property by using the :dotnet-sdk:`IndexType <reference/Realms.IndexType.html>`
`IndexType.None` is used when introspecting the schema and is not something users will ever use to pass to Realm. In fact, it's a compilation error to add an attribute like `[Indexed(IndexType.None)]`. But if you're building the schema dynamically or if you're reading it, you may come across it, though these are fairly advanced scenarios and I don't think we need to be documenting them here.

2023-05-12 18:52 UTC, nirinchev commented on source/sdk/dotnet/model-data/define-object-model.txt
> +   Adding an index can speed up some queries at the cost of slightly slower write
Actually, ln 122 sounds more accurate - even if you're querying on an indexed field, there's no guarantee the query will use the index.