(DOCSP-29580) Open and close a realm test updates
mongodb/docs-realm pull request #2799
Opened 2023-05-17 02:45 UTC by krollins-mdb

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-29580

### Staged Changes

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

### Animal Wearing a Hat

![](https://m.media-amazon.com/images/I/41JOwSsMsPS._AC_.jpg)

2023-05-17 18:40 UTC, dacharyc requested changes
Congrats on completing this large unit of work! I had a handful of blocking comments we should address, and a variety of non-blocking Qs or comments for discussion.

2023-05-17 18:40 UTC, dacharyc commented on source/sdk/node/realm-files/open-and-close-a-realm.txt
> +Configure & Open a Realm - Node.js SDK
[Non-blocking] Curious why the name change? There is no `close` in Swift because of the way Swift's memory management works - the realm is automatically deallocated when references to it go out of scope. But in SDKs where you are expected to close a realm manually to manage memory, I think it makes sense to leave "Close" in the title.

Also, for future consideration, I notice we're inconsistent about its usage across the SDKs, so it might be good to discuss this. I'll add a note to our sync document.

2023-05-17 18:40 UTC, dacharyc commented on source/sdk/node/realm-files/open-and-close-a-realm.txt
> +Open a Local Realm Without Sync
[Non-blocking] Given historical discussions across the team about "local" as analogous to "non-synced" - I wonder if we want to unify on that terminology in the docs and drop "local" since you're updating this page? It looks like in Swift I renamed this to "Open a Realm Without Sync" but we could possibly just call it "Open a Realm" in the section header and clarify that it's a non-synced realm in the text below, like you did here?

2023-05-17 18:40 UTC, dacharyc commented on source/sdk/node/realm-files/open-and-close-a-realm.txt
> +   .. example:: Convert Local Realm to Synced Realm
[Blocking] It looks like the staged version of this page is having issues with this section - presumably because this `example` is nested instead the `example` from ln 118. I _think_ this line and the newline after it can just go away?

2023-05-17 18:40 UTC, dacharyc commented on source/sdk/node/users/authenticate-users.txt
>     :language: javascript
[Potentially blocking] It looks like you're changing a JS example to a TS example, but didn't change the language.
```suggestion
.. literalinclude:: /examples/generated/node/open-and-close-a-realm.snippet.use-cached-user.ts
   :language: typescript
```

2023-05-17 18:40 UTC, dacharyc commented on source/includes/js-close-a-realm.rst
>    :language: javascript
[Potentially blocking] It looks like you're changing a JS example to a TS example, but didn't change the language.
```suggestion
.. literalinclude:: /examples/generated/node/open-and-close-a-realm.snippet.close-local-realm.ts
  :language: typescript
```

2023-05-17 18:40 UTC, dacharyc commented on source/sdk/node/realm-files/open-and-close-a-realm.txt
>     :language: javascript
[Potentially blocking] It looks like you're changing a JS example to a TS example, but didn't change the language.
```suggestion
.. literalinclude:: /examples/generated/node/open-and-close-a-realm.snippet.no-schema.ts
   :language: typescript
```

2023-05-17 18:40 UTC, dacharyc commented on source/sdk/react-native/manage-users/authenticate-users.txt
>     :language: javascript
[Potentially blocking] It looks like you're changing a JS example to a TS example, but didn't change the language.
```suggestion
.. literalinclude:: /examples/generated/node/open-and-close-a-realm.snippet.use-cached-user.ts
   :language: typescript
```

2023-05-17 18:40 UTC, dacharyc commented on source/studio/open-realm-file.txt
>           :language: javascript
[Potentially blocking] It looks like you're changing a JS example to a TS example, but didn't change the language.
```suggestion
      .. literalinclude:: /examples/generated/node/open-and-close-a-realm.snippet.find-realm-file.ts
         :language: typescript
```

2023-05-17 18:40 UTC, dacharyc commented on source/sdk/react-native/sync-data/partition-based-sync.txt
> +   .. tabs-realm-languages::
I can't leave a comment directly on the line since you didn't edit it here, but FYI there are two periods at the end of a sentence in ln 14 we should probably fix while we're in here.

2023-05-17 18:40 UTC, dacharyc commented on source/sdk/react-native/sync-data/partition-based-sync.txt
> +      .. tabs-realm-languages::
[Blocking] The tabs aren't showing up in the `example` block on the staged page. Maybe it's because they're nested too deeply?

2023-05-17 20:28 UTC, krollins-mdb commented on examples/node/Examples/open-and-close-a-realm.js
> +  const app = new Realm.App({ id: "js-flexible-oseso" });
Good point! Ben and I have talked about this. I'll introduce a global `config.js` file that has the app IDs and import from there. To keep the scope of this PR down, I won't apply it to all of the test files. I'll create another PR for that.

2023-05-17 20:39 UTC, krollins-mdb commented on examples/node/Examples/open-and-close-a-realm.js
> +      if (app.currentUser) {
Hmm. I don't know if reversing the logic simplifies it, but I refactored a bit anyway. I actually made it a little more verbose, but I think it's clearer this way.

2023-05-17 20:41 UTC, krollins-mdb commented on source/sdk/node/realm-files/open-and-close-a-realm.txt
> +Configure & Open a Realm - Node.js SDK
Ah, yeah, this will be good to discuss. Probably makes sense to keep "close" in the title for Node.js. I was thinking of bringing it closer to the React Native page, which maybe wasn't a good idea. With the realm/react library for React Native, devs don't need to manage opening and closing realms - they just configure them.

2023-05-17 20:46 UTC, krollins-mdb commented on source/sdk/node/realm-files/open-and-close-a-realm.txt
> +Open a Local Realm Without Sync
Let's discuss, for sure. I think I like just "realm" referring to non-synced and we always specifically state "synced realm" if it's not local.

2023-05-17 20:50 UTC, krollins-mdb commented on source/sdk/node/realm-files/open-and-close-a-realm.txt
> +   .. example:: Convert Local Realm to Synced Realm
Oops. Yep. That was a mistake.

2023-05-17 20:51 UTC, krollins-mdb commented on source/sdk/node/users/authenticate-users.txt
>     :language: javascript
Dang. I try to stay on top of this. It actually doesn't change anything. Our highlighting is the same for typescript and javascript. 😞

But I've tried to keep them correct anyway for semantics.

2023-05-17 20:58 UTC, krollins-mdb commented on source/studio/open-realm-file.txt
>           :language: javascript
This is an odd one. I've updated `:language:` to `typescript`, but I'm leaving the tab name as `JavaScript`. The reason is that there's actually no TypeScript in this file, but the file itself is TypeScript. I'm moving all the Node.js tests I can into TypeScript files because they're much better at pointing out issues - even when you're not using TypeScript features.

2023-05-17 21:05 UTC, dacharyc commented on source/studio/open-realm-file.txt
>           :language: javascript
Hmm. I wonder if we should leave a note on the page to that effect for future documentarians who come along and see that the file type, language, and tab name don't match? I, not being familiar with the syntax differences, might naively assume this was an error or oversight instead of an intentional decision.

I found this good info on Stack Overflow about commenting rST: https://stackoverflow.com/questions/4783814/how-to-comment-a-string-in-restructured-text

2023-05-17 22:20 UTC, dacharyc approved these changes
I've got a handful of non-blocking suggestions, but I think a few more tweaks could clarify and head off future changes. Otherwise, LGTM!

2023-05-17 22:20 UTC, dacharyc commented on source/sdk/node/sync/configure-and-open-a-synced-realm.txt
> +Configure & Access a Synced Realm - Node.js SDK
[Potentially blocking] Curious about this name change. I don't think we've talked about "accessing" a realm in any of the other docs - we have always referred to "opening" a realm. I favor "Open" for consistency with the rest of the docs & SDK method names, but am open to discuss!

2023-05-17 22:20 UTC, dacharyc commented on examples/node/Examples/open-and-close-a-realm.ts
> +        const user = await app.logIn(credentials);
[Non-blocking] Perhaps this is subjective, but I still think this example could be simplified. Assuming this works in JS/TS, we don't need to store the result of `await app.login` as a constant and then return it. We can just do:

```
if (!app.currentUser) {
  const credentials = Realm.Credentials.anonymous();
  await app.logIn(credentials);
  expect(app.currentUser).toBeTruthy(); // :remove:
}
return app.currentUser;
```

The argument for the simplified version is that it makes it clear that `app.logIn()` sets `app.currentUser` and then you can use it in the app.

2023-05-18 01:21 UTC, krollins-mdb commented on source/studio/open-realm-file.txt
>           :language: javascript
Good point. I'll add a note.

2023-05-18 01:31 UTC, krollins-mdb commented on examples/node/config.js
> +const REALM_APP_ID = "js-flexible-oseso";
That makes a lot of sense. I'll update to just "APP_ID". It's more concise anyway.

2023-05-18 01:33 UTC, krollins-mdb commented on source/sdk/node/realm-files/open-and-close-a-realm.txt
> +Configure, Open, & Close a Realm - Node.js SDK
Huh. This is one style guide thing I don't think I've ever come across before. Though pretty much everywhere I've worked has eschewed ampersands altogether. I'm inclined to keep the comma and remove the ampersand.

2023-05-18 01:35 UTC, krollins-mdb commented on source/sdk/node/sync/configure-and-open-a-synced-realm.txt
> +Configure & Access a Synced Realm - Node.js SDK
Good question. I shouldn't have introduced that here. Reverting.

2023-05-18 01:51 UTC, merged