Add Code on Watching for Collection Changes
mongodb/docs-realm pull request #2802
Opened 2023-05-17 20:47 UTC by MongoCaleb

## Pull Request Info

### Jira

https://jira.mongodb.org/browse/DOCSP-29852

### Staged Changes

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-29852/sdk/dotnet/model-data/data-types/collections/ (pruned)

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-29852/sdk/dotnet/model-data/data-types/lists/ (new)

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-29852/sdk/dotnet/model-data/data-types/dictionaries/#watching-for-changes (added section)

https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-29852/sdk/dotnet/model-data/data-types/sets/#watching-for-changes  (added section)

2023-05-18 16:30 UTC, krollins-mdb approved these changes
LGTM, assuming the refs' missing display text is added.

2023-05-18 16:30 UTC, krollins-mdb commented on source/sdk/dotnet/model-data/data-types/dictionaries.txt
> +property to an :dotnet-sdk:`<reference/Realms.IRealmCollection-1.html>` and set
I believe we're missing the display text. Is this correct?
```suggestion
property to an :dotnet-sdk:`IRealmCollection<T> <reference/Realms.IRealmCollection-1.html>` and set 
```

2023-05-18 16:30 UTC, krollins-mdb commented on source/sdk/dotnet/model-data/data-types/lists.txt
> +:dotnet-sdk:`<reference/Realms.IRealmCollection-1.html>` and set an event handler
Same a previous.
```suggestion
:dotnet-sdk:`IRealmCollection<T> <reference/Realms.IRealmCollection-1.html>` and set an event handler 
```

2023-05-18 16:30 UTC, krollins-mdb commented on source/sdk/dotnet/model-data/data-types/sets.txt
> +:dotnet-sdk:`<reference/Realms.IRealmCollection-1.html>` and set an event handler
Same a previous.
```suggestion
:dotnet-sdk:`IRealmCollection<T> <reference/Realms.IRealmCollection-1.html>` and set an event handler 
```

2023-05-18 16:30 UTC, krollins-mdb commented on source/sdk/dotnet/model-data/data-types/lists.txt
> +
Extra line
```suggestion
```

2023-05-24 09:10 UTC, papafe requested changes

2023-05-24 09:10 UTC, papafe commented on source/sdk/dotnet/model-data/data-types/lists.txt
> +One of the fundamental building blocks when working with any
This also needs to be modified following the other comments. Collection here is too much of a generic term, here we need an intro like the one for dictionaries and sets

2023-05-25 18:52 UTC, MongoCaleb commented on source/examples/generated/dotnet/ProgressNotifications.snippet.notify-set-change.cs
> +var set = container.StringSet.AsRealmCollection();
interesting catch. The IDE has no problem with it, and so I didn't notice that the HTML generator did this.

2023-05-25 19:02 UTC, MongoCaleb commented on source/sdk/dotnet/model-data/data-types/dictionaries.txt
> +``IDictionary`` implements the `INotifyPropertyChanged.PropertyChanged Event
I think in this case, it is OK to say it implements the propertychanged event, because it does. It doesn't _directly_ inherit it, but that is, as you say, an "under the hood" detail of how it gets implemented. From a user's perspective, what matters is that it is there. 
We also don't use idiomatic phrases like "under the hood" because they don't translate well.

2023-05-26 13:06 UTC, papafe commented on source/sdk/dotnet/model-data/data-types/collections.txt
>  Results are Lazily Evaluated
This is a comment for the "Collections are live" section. 

We still refer to lists in two places: 
- "Live **lists** always reflect the current state of the relationship on the realm instance." ---- I think we could keep this one, I can see that it's used also in the other SDK. I hope it's clear enough that here list means more like "collection", but using that would maybe create more confusion
- "a List property of a Realm object  that has not been added to a realm yet or that has been copied from a 
  realm." ------ For this we can change List with collection

2023-05-26 13:06 UTC, papafe commented on source/sdk/dotnet/model-data/data-types/lists.txt
> +One of the fundamental building blocks when working with any
```suggestion
```

2023-05-26 13:08 UTC, papafe requested changes

2023-05-26 19:10 UTC, MongoCaleb commented on source/examples/generated/dotnet/DataTypesSectionExamples.snippet.query-lists.cs
> +var greenPlants = realm.All<Inventory>()
I don't see a duplicate in here.

2023-05-30 16:31 UTC, merged