(DOCSP-27941) Flutter: add Decimal128 support
mongodb/docs-realm pull request #2821
Opened 2023-05-31 18:46 UTC by krollins-mdb

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-27941

### Staged Changes

- [Data Types]()

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

### Animal Wearing a Hat

<img src="https://i0.wp.com/reviewsandotherstuff.com/wp-content/uploads/2020/04/cat-on-a-hat.jpg?resize=980%2C745&ssl=1" width=400>

2023-05-31 20:45 UTC, krollins-mdb commented
@desistefanova, could you make sure that I captured this information correctly?

2023-06-02 20:34 UTC, desistefanova approved these changes
LGTM.

2023-06-05 09:36 UTC, nielsenko requested changes

2023-06-05 09:36 UTC, nielsenko commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +are true when using ``compareTo()``:
This is not odd. This is how Decimal128 should behave as defined by IEEE-754

2023-06-05 09:36 UTC, nielsenko commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +which is a 128-bit MongoDB-specific implementation of :wikipedia:`IEEE-754 <IEEE_754>`.
Not really anything MongoDB specific about it. We are basically just wrapping the intel implementation that is used in both realm-core and mongodb.

2023-06-05 09:36 UTC, nielsenko commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +are true when using ``compareTo()``:
What is a bit odd is that realm-core actually has a different total ordering .. now thats weird, but I don't think we should mention this in the dart docs.

2023-06-06 15:54 UTC, krollins-mdb commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +are true when using ``compareTo()``:
Thank you! Yeah, I shouldn't have characterized that as odd. I'll elaborate on the point a bit.

2023-06-06 15:56 UTC, krollins-mdb commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +which is a 128-bit MongoDB-specific implementation of :wikipedia:`IEEE-754 <IEEE_754>`.
Today I learned. Thanks for the info! I'll update to remove "MongoDB-specific".

2023-06-06 20:26 UTC, dacharyc approved these changes
LGTM

2023-06-06 20:35 UTC, merged