DOCSP-30001 Kotlin Full Text Search
mongodb/docs-realm pull request #2824
Opened 2023-06-01 19:15 UTC by lindseymoore

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-30001

### Staged Changes

- [Read (Filter with Full Text Search)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30001/sdk/kotlin/realm-database/crud/read/#filter-with-full-text-search)
- [Property Annotations](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30001/sdk/kotlin/realm-database/schemas/property-annotations/#full-text-search-indexes)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [ ] Create Jira ticket for corresponding docs-app-services update(s), if any
- [ ] Checked/updated Admin API
- [ ] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-06-01 20:51 UTC, dacharyc requested changes
Great start! This is most of the way there - there are just a couple of tense change we can avoid, and I think we should add a few more details in relevant spots from the API docs.

2023-06-01 20:51 UTC, dacharyc commented on source/sdk/kotlin/realm-database/schemas/property-annotations.txt
> +/-full-text/index.html>` annotation. This will enable full-text queries
Our style guide calls for us to avoid future tense.
```suggestion
/-full-text/index.html>` annotation. This enables full-text queries
```

2023-06-01 20:51 UTC, dacharyc commented on source/sdk/kotlin/realm-database/schemas/property-annotations.txt
> +on the property. In the following example, we marked the ``genre``
Probably best to avoid other tense changes, too.
```suggestion
on the property. In the following example, we mark the ``genre`` 
```

2023-06-01 20:51 UTC, dacharyc commented on source/sdk/kotlin/realm-database/schemas/property-annotations.txt
> +In addition to standard indexes, Realm also supports Full-Text Search
We should probably add a note somewhere in this section about the limitations on what characters can be in the FTS index. From the API documentation:

> Only ASCII and Latin-1 alphanumerical chars are included in the index (most western languages).

2023-06-02 20:14 UTC, dacharyc reviewed
Overall, this looks good! Just a few more refinements and then I think we'll be all set :)

2023-06-02 20:14 UTC, dacharyc commented on source/sdk/kotlin/realm-database/crud/read.txt
> +FTS Index Feature Limitations
In general, we try to avoid "Limitations" unless we're talking about things like actual limits, such as maximum counts or other caps on functionality. We don't want to give the impression that a feature is "limited." In this case, the idea is to provide more details about how our tokenizer works, so we can probably say something like:

```suggestion
Full-Text Search Tokenizer Details
```

Also, as a best practice, we should generally avoid abbreviating terms in section headings, even though you have previously established the abbreviation. Search-engine optimization (SEO) considers section headings when trying to determine what a page is about, so it's good to use relevant terms in them. And docs readers scan section headings to see if a page contains they info they want, so it's good to make the headings scannable and understandable even if a person hasn't read the text where you explained the abbreviation.

2023-06-02 20:14 UTC, dacharyc commented on source/sdk/kotlin/realm-database/crud/read.txt
> +- Exclude results for a word by placing the ``-`` character
I think we could probably remove this bullet from this list of tokenizer details and add it to the explanation above near the query that shows this in the example. Maybe something like:

> To query these properties, use the ``TEXT`` predicate in your query. 
> You can exclude results for a word by placing the ``-`` character
> in front of the word. For example, a search for ``tabby -cat`` would 
> find FTS results for ``tabby``, but exclude those that include the
> word ``cat``.
>
> The following example shows how you might query a ``Book.genre`` field:

2023-06-02 20:14 UTC, dacharyc commented on source/sdk/kotlin/realm-database/crud/read.txt
> +- Tokens can only consist of characters from ASCII and the Latin-1 supplement (western languages).
It might be helpful to add this other detail from the API docs to this bullet:
> All other characters are considered whitespace. Words split by hyphens, 
> like `full-text`, are split into two tokens.

2023-06-05 13:13 UTC, dacharyc approved these changes
Nice work, @lindseymoore - LGTM!

Before you merge, post this in the realm-kotlin Slack channel and ask for a tech review. Then we should be all set to merge!

2023-06-06 07:09 UTC, cmelchior approved these changes
Looking good 👍

2023-06-06 07:09 UTC, cmelchior commented on source/sdk/kotlin/realm-database/schemas/property-annotations.txt
> +In addition to standard indexes, Realm also supports Full-Text Search
Not sure if it is worth mentioning that you cannot combine `@Index` and `@FullText` on the same property?

2023-06-15 23:09 UTC, merged