(DOCSP 30002): Flutter FTS
mongodb/docs-realm pull request #2847
Opened 2023-06-14 20:38 UTC by lindseymoore

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-30002

### Staged Changes

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [ ] Create Jira ticket for corresponding docs-app-services update(s), if any
- [ ] Checked/updated Admin API
- [ ] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-06-24 01:20 UTC, krollins-mdb requested changes
@lindseymoore, thank you so much for putting in the work on Full-Text Search!

I have some minor text suggestions and link fixes. We need a bit more work on the unit test, but you got most of the way there.

2023-06-24 01:20 UTC, krollins-mdb commented on source/sdk/flutter/realm-database/model-data/property-annotations.txt
> +:ref:`Filter with Full Text Search <flutter-fts>`.
Couple small edits for consistency in how we refer to FTS.
```suggestion
For more information on querying FTS indexes, see 
:ref:`Filter with Full-Text Search <flutter-fts>`.
```

2023-06-24 01:20 UTC, krollins-mdb commented on source/sdk/flutter/realm-database/model-data/property-annotations.txt
> +To create a FTS index on a property, use the :flutter-sdk:`@Indexed
```suggestion
To create an FTS index on a property, use the :flutter-sdk:`@Indexed 
```

2023-06-24 01:20 UTC, krollins-mdb commented on source/sdk/flutter/realm-database/model-data/property-annotations.txt
> +<realm_common/Indexed-class.html>` annotation and specify the
TIL, `:flutter-sdk:` doesn't work for all of the Flutter SDK's docs. Looks like `realm_common`, which `Indexed` is part of, has a different root URL, so this convention results in a 404.

We'll need to use the full URL, like lines 94 and 95 in this file.

2023-06-24 01:20 UTC, krollins-mdb commented on source/sdk/flutter/realm-database/model-data/property-annotations.txt
> +:flutter-sdk:`IndexType <realm_common/RealmIndexType.html>` as ``fullText``.
Same as above. Right now, this 404s.

2023-06-24 01:20 UTC, krollins-mdb commented on source/sdk/flutter/realm-database/model-data/property-annotations.txt
> +following example, we mark the genre property with the FTS annotation:
```suggestion
following example, we mark the pattern and material properties with the FTS annotation:
```

2023-06-24 01:20 UTC, krollins-mdb commented on source/sdk/flutter/realm-database/read-and-write-data.txt
> +:ref:`Full-Text Search Indexes <flutter-fts-annotation>` (FTS) on them.
```suggestion
You can use Realm Query Language (RQL) to query on properties that use
:ref:`Full-Text Search Index <flutter-fts-annotation>` annotations. 
```

2023-06-24 02:07 UTC, krollins-mdb commented
Also, Autobuilder is [mad about inconsistent title levels](https://github.com/mongodb/docs-realm/actions/runs/5350295998/jobs/9702710675?pr=2847), but I couldn't find anything wrong. *shrug* Maybe take a look and see if you can find something I missed.

2023-06-26 20:37 UTC, lindseymoore commented on examples/dart/test/full_text_search_test.dart
Thank you, this was very helpful!

2023-06-27 17:56 UTC, merged