(DOCSP-30841) Add binary data type to Flutter docs
mongodb/docs-realm pull request #2859
Opened 2023-06-22 20:48 UTC by krollins-mdb

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-30841

### Staged Changes

- [Data Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30841/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-06-22 21:06 UTC, krollins-mdb commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +.. API docs don't seem to have the Binary class: https://pub.dev/documentation/realm/latest/realm/realm-library.html
Note for technical reviewer: I didn't see `Uint8List` or `Binary` or anything in the generated API docs. I assume this is because it's part of `dart:typed_data`?

Should this actually go under "[Dart Types](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30841/sdk/flutter/realm-database/model-data/data-types/#dart-types)"?

2023-06-22 21:09 UTC, krollins-mdb commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +To add ``Uint8List`` to a Realm object, call ``Uint8List.fromList(List<int>
Note for technical reviewer: I pulled ``Uint8List.fromList(List<int> elements)`` from the Dart docs. Would it be appropriate to use `RealmList` instead of `List` as an argument for `.fromList()`? I'm not 100% clear on how this would typically be used.

2023-06-23 09:29 UTC, blagoev requested changes
Added some suggestions

2023-06-23 09:29 UTC, blagoev commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +To add ``Uint8List`` to a Realm object, call ``Uint8List.fromList(List<int>
`Uint8List.fromList` takes any List regardless of the actual class implementing it.

2023-06-23 09:29 UTC, blagoev commented on examples/dart/pubspec.yaml
> +  # graphql has version mismatches with realm_dart v1.3.0
what are the versions mismatches. Can you update the `graphql` version ?

2023-06-23 09:29 UTC, blagoev commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +.. API docs don't seem to have the Binary class: https://pub.dev/documentation/realm/latest/realm/realm-library.html
I am not sure whom this text is written for. 
```suggestion
.. API docs don't seem to have the Binary class: https://pub.dev/documentation/realm/latest/realm/realm-library.html
```
This should be removed if it is part of the web site Docs text

2023-06-26 19:07 UTC, krollins-mdb commented on examples/dart/pubspec.yaml
> +  # graphql has version mismatches with realm_dart v1.3.0
This is what I get after running `dart pub get` with the latest `graphql` version (5.1.3) specified in `package.yaml`:
```
Resolving dependencies... 
The current Dart SDK version is 3.0.5.

Because graphql >=5.2.0-beta.2 <5.2.0-beta.3 requires SDK version >=2.15.0 <=3.0.0 and graphql >=5.2.0-beta.3
  depends on http ^0.13.0, graphql >=5.2.0-beta.2 requires http ^0.13.0.
And because graphql >=5.0.0-beta.1 <5.2.0-beta.2 depends on http ^0.13.0, graphql >=5.0.0-beta.1 requires
  http ^0.13.0.
Because no versions of realm_dart match >1.3.0 <2.0.0 and realm_dart 1.3.0 depends on http ^1.0.0, realm_dart
  ^1.3.0 requires http ^1.0.0.
Thus, realm_dart ^1.3.0 is incompatible with graphql >=5.0.0-beta.1.
So, because myapp depends on both realm_dart ^1.3.0 and graphql ^5.1.3, version solving failed.
```

Looks like `graphql` hasn't updated to v1.0.0 of `http`, which `realm_dart` v1.3.0 requires.

2023-06-27 18:13 UTC, merged