(DOCSP-30677): Kotlin Asymmetric Sync
mongodb/docs-realm pull request #2871
Opened 2023-06-28 15:28 UTC by cbullinger

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-30677

### Staged Changes

- [Stream Data to Atlas - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30677-kotlin-asymmetric-sync/sdk/kotlin/sync/stream-data-to-atlas/)
- [Create Realm Objects - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30677-kotlin-asymmetric-sync/sdk/kotlin/realm-database/crud/create/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [x] Create Jira ticket for corresponding docs-app-services update(s), if any (see [DOCSP-30986](https://jira.mongodb.org/browse/DOCSP-30986)
- [x] Checked/updated Admin API
- [x] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-06-29 20:20 UTC, cbullinger commented on source/sdk/kotlin/realm-database/crud/create.txt
> +You can only create an `AsymmetricRealmObject <{+kotlin-sync-prefix+}io.realm.kotlin.types/-asymmetric-realm-object/index.html>`__
@clementetb when will the 1.10.0 API ref docs be available/generated? These links are broken until the `latest` URL is updated (currently only accessible through [v1.10.0 URL](https://www.mongodb.com/docs/realm-sdks/kotlin/1.10.0/library-sync/io.realm.kotlin.types/-asymmetric-realm-object/index.html))

2023-06-29 21:56 UTC, dacharyc requested changes
Great start! I've got a smattering of questions and comments. Let's chat if you have questions about any of them!

2023-06-29 21:56 UTC, dacharyc commented on source/sdk/kotlin/sync/stream-data-to-atlas.txt
> +   .. step:: Define an AsymmetricObject
We say **Asymmetric Object** above, and here we run the words together like a proper object type, but the code example & API docs show this is `AsymmetricRealmObject`. So we should probably either separate the words with a space here to show we're talking generally about the thing we referred to as an "**Asymmetric Object**" above, or use the proper Kotlin interface name `AsymmetricRealmObject`.

2023-06-29 21:56 UTC, dacharyc commented on source/sdk/kotlin/sync/stream-data-to-atlas.txt
> +      Define an asymmetric object by deriving from the ``AsymmetricRealmObject`` class:
I don't think we'd say "deriving from the ``AsymmetricRealmObject`` class" in Kotlin. In the Kotlin SDK, this is an [interface](https://kotlinlang.org/docs/interfaces.html). We should probably say instead something like "To define an asymmetric object, your class must implement the `AsymmetricRealmObject` interface."

2023-06-29 21:56 UTC, dacharyc commented on source/sdk/kotlin/sync/stream-data-to-atlas.txt
> +      Services backend and the linked Atlas database.
After watching Mark Brown's presentation, I'm thinking we should add something here along the lines of:

> "After syncing to Atlas, Realm deletes asymmetric objects from the device. This keeps the realm file size small even with a heavy insert workload."

We don't really call out this benefit currently, but maybe we should!

2023-06-29 21:56 UTC, dacharyc commented on source/sdk/kotlin/realm-database/crud/create.txt
> +extension method.
I am pondering whether we should add something like:

```suggestion
extension method inside a write transaction.
```

That gets a little wordier and maybe it's not necessary since the code example shows that. What do you think?

2023-06-29 21:56 UTC, dacharyc commented on source/sdk/kotlin/realm-database/crud/create.txt
> +Create an Asymmetric Object
Hmm, so I noticed this when I added the "Dictionary" section but I am not loving the "Dictionary" and "Asymmetric" sections in the OTP with nothing there about just creating an object. Should we add a header above at like ln 23 for "Create a Realm Object" or something like that for just the general "Create" case? Or maybe remove the OTP from this page altogether?

2023-06-29 21:56 UTC, dacharyc commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AsymmetricSyncTest.kt
> +        assertEquals(1, deletedCount)
Nice!

2023-06-29 21:56 UTC, dacharyc commented on source/sdk/kotlin/sync/stream-data-to-atlas.txt
> +      .. literalinclude:: /examples/generated/kotlin/AsymmetricSyncTest.snippet.asymmetric-model.kt
In the other SDKs, we have a section in "Model Data" about how to define an asymmetric object: https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30677-kotlin-asymmetric-sync/sdk/swift/model-data/object-models/#define-an-asymmetric-object

I'm wondering if you decided not to do that intentionally, or just missed it? If the former, we should chat and consider applying those changes to the other SDKs for consistency.

2023-06-29 21:56 UTC, dacharyc commented on source/sdk/kotlin/sync/stream-data-to-atlas.txt
> +- The Kotlin objects that you sync with Atlas must derive from the
Similar to my comment below, here and in ln 37 I don't think we'd say in Kotlin "derives from ``AsymmetricRealmObject``" - we should probably talk about it implementing the `AsymmetricRealmObject` interface.

2023-06-29 21:56 UTC, dacharyc commented on source/sdk/kotlin/sync/stream-data-to-atlas.txt
> +**Asymmetric Object**. The Kotlin SDK allows you to work with asymmetric objects
It surprised me to read in Kotlin that you can work with asymmetric objects and standard Realm objects within the same realm. That's definitely _not_ the case in Swift, and I'm not sure if that's the case in C++. I saw that this was in the Kotlin API doc for `AsymmetricRealmObject` so I'm guessing that's where you got the information.

Curious if you tried testing this? I checked the engineering PR and didn't see a test for this, but maybe I missed it - there were a lot of files changed. I am presuming this means you would add all the types to the schema as usual, and add a Flexible Sync subscription query for the non-asymmetric objects but explicitly leave out the asymmetric types from the sync query. It would probably be good to add a section to the page for how to work with both asymmetric and non-asymmetric object types in the same realm just to provide more information and/or an example.

Also, I don't think we use the term "standard Realm objects" anywhere else, so we might want to clarify what is "standard" - is it just any object type other than asymmetric? i.e. Realm object and embedded object?

2023-06-29 22:28 UTC, cbullinger commented on source/sdk/kotlin/sync/stream-data-to-atlas.txt
> +   .. step:: Define an AsymmetricObject
That was a miss from copy-pasting from the Swift... derp.

2023-06-29 22:30 UTC, cbullinger commented on source/sdk/kotlin/sync/stream-data-to-atlas.txt
> +      Define an asymmetric object by deriving from the ``AsymmetricRealmObject`` class:
Updated

2023-06-29 22:32 UTC, cbullinger commented on source/sdk/kotlin/sync/stream-data-to-atlas.txt
> +      Services backend and the linked Atlas database.
Good call! Added

2023-06-29 22:33 UTC, cbullinger commented on source/sdk/kotlin/realm-database/crud/create.txt
> +extension method.
I think it's helpful. Added.

2023-06-29 22:35 UTC, cbullinger commented on source/sdk/kotlin/realm-database/crud/create.txt
> +Create an Asymmetric Object
I'd rather have the extra heading, I think. Good catch, though. It does look off as-is.

2023-06-29 22:38 UTC, cbullinger commented on source/sdk/kotlin/sync/stream-data-to-atlas.txt
> +**Asymmetric Object**. The Kotlin SDK allows you to work with asymmetric objects
@clementetb can you confirm whether you can work with asymmetric objects and non-asymmetric objects within in the same realm? .NET allows it, but Swift and possibly C++ do not.

2023-06-29 22:38 UTC, cbullinger commented on source/sdk/kotlin/sync/stream-data-to-atlas.txt
> +- The Kotlin objects that you sync with Atlas must derive from the
Updated

2023-06-29 22:43 UTC, cbullinger commented on source/sdk/kotlin/sync/stream-data-to-atlas.txt
> +      .. literalinclude:: /examples/generated/kotlin/AsymmetricSyncTest.snippet.asymmetric-model.kt
I did intentionally omit it since the Define an Object Model page in Kotlin is kind of a mess right now, and I wasn't sure where it should live now (versus in the future after that page is redone). Let's sync on this.

2023-06-30 13:04 UTC, cbullinger commented on source/sdk/kotlin/sync/stream-data-to-atlas.txt
> +**Asymmetric Object**. The Kotlin SDK allows you to work with asymmetric objects
I was able to successfully, so I assume that means you can. I've revised the "standard Realm objects" wording

2023-06-30 13:43 UTC, cbullinger commented on source/sdk/kotlin/realm-database/crud/create.txt
> +You can only create an `AsymmetricRealmObject <{+kotlin-sync-prefix+}io.realm.kotlin.types/-asymmetric-realm-object/index.html>`__
Nevermind. Looks like this is a caching issue on my end.

2023-06-30 14:04 UTC, dacharyc approved these changes
There are a couple of things I think we should tweak in the new "Define an Asymmetric Object" section, but after that, LGTM!

2023-06-30 14:04 UTC, dacharyc commented on source/sdk/kotlin/sync/stream-data-to-atlas.txt
> +**Asymmetric Object**. The Kotlin SDK allows you to work with asymmetric objects
Thank you for checking on this, and for the wording tweaks!

2023-06-30 14:04 UTC, dacharyc commented on source/sdk/kotlin/realm-database/crud/create.txt
> +Create an Asymmetric Object
Thanks for adding the extra heading - I think that makes it clearer what's on the page!

2023-06-30 14:06 UTC, cbullinger commented on source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
> +`AsymmetricRealmObject <{+kotlin-sync-prefix+}io.realm.kotlin.types/-asymmetric-realm-object/index.html>`__ class:
Updated

2023-06-30 14:06 UTC, cbullinger commented on source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
> +You can only :ref:`create an asymmetric object <kotlin-create-asymmetric-object>`,
Ooh good point. Was a lazy copy-paste, I think. Updated for better explanation/context

2023-06-30 21:42 UTC, clementetb reviewed
Looks good. We are naming the realms as `asymmetricRealm` and might be misleading as the Realm is not asymmetric but the objects. I would name it `realm` because a Realm can contain symmetric and asymmetric objects.

2023-06-30 22:03 UTC, merged