(DOCSP-30336 & DOCSP-29597): Kotlin Write Data to Synced Realm page
mongodb/docs-realm pull request #2881
Opened 2023-07-10 17:53 UTC by cbullinger

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-30336 (Add Write Data to Synced Realm page)
- https://jira.mongodb.org/browse/DOCSP-29597 (Include section on compensatingWriteError)

### Staged Changes

- [Write Data to a Synced Realm - Kotlin SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-30336-kotlin-write-data/sdk/kotlin/sync/write-to-synced-realm/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [ ] Create Jira ticket for corresponding docs-app-services update(s), if any
- [x] Checked/updated Admin API
- [x] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-07-14 10:06 UTC, clementetb commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncedRealmCRUD.kt
> +                    val writeInfo = error.writes[0]
There could be more than one compensating write, we should iterate through them:

```
error.writes.forEach { writeInfo ->
    val errorMessage = """
        A write was rejected with a compensating write error
        The write to object type: ${writeInfo.objectType}
        With primary key of: ${writeInfo.primaryKey}
        Was rejected because: ${writeInfo.reason}
        """.trimIndent()
    Log.e(errorMessage)
}
```

2023-07-14 14:01 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SyncedRealmCRUD.kt
> +                    val writeInfo = error.writes[0]
Updated

2023-07-14 14:02 UTC, cbullinger commented on source/sdk/kotlin/sync/write-to-synced-realm.txt
> +Device Sync is configured with the following queryable fields:
Updated

2023-07-14 16:44 UTC, lindseymoore requested changes
A few suggestions for clarity.

2023-07-14 16:44 UTC, lindseymoore commented on source/sdk/kotlin/sync/write-to-synced-realm.txt
> +and the corresponding compensating write will be lost.
Suggestion: Move this sentence to the beginning of line 156. I was confused by the mention of an illegal write, but after reading the bulleted list, I understood.

2023-07-14 16:44 UTC, lindseymoore commented on source/sdk/kotlin/sync/write-to-synced-realm.txt
> +  permissions to perform the write. Realm reverts the illegal write.
```suggestion
  permissions to perform the write. Realm reverts the illegal write with a compensating write.
```
To explain how it reverts, or maybe remove compensating to not include the term within the defintion.

2023-07-17 14:18 UTC, cbullinger commented on source/sdk/kotlin/sync/write-to-synced-realm.txt
> +- ``complexity``
It's based on the example object model described in the next section. Maybe that needs to go first?

2023-07-17 14:25 UTC, cbullinger commented on source/sdk/kotlin/sync/write-to-synced-realm.txt
> +and the corresponding compensating write will be lost.
Moved

2023-07-17 16:46 UTC, lindseymoore approved these changes
LGTM w/ one small suggestion!

2023-07-17 16:46 UTC, lindseymoore commented on source/sdk/kotlin/sync/write-to-synced-realm.txt
> +Based on the above :ref:`object model <kotlin-sync-example-object-model>`,
```suggestion
Based on the above example :ref:`object model <kotlin-sync-example-object-model>`, 
```
Just to make it clear that it's an example!

2023-07-17 16:46 UTC, lindseymoore commented on source/sdk/kotlin/sync/write-to-synced-realm.txt
> +- ``complexity``
Yes, makes more sense with it appearing first!

2023-07-17 17:50 UTC, merged