(DOCSP-27757) Update docs to reflect latest `@realm/react` version
mongodb/docs-realm pull request #2900
Opened 2023-07-21 13:04 UTC by krollins-mdb

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-27757

### Staged Changes

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

### Animal Wearing a Hat

<img src="https://en.bcdn.biz/Images/2019/1/22/6482ed68-a95f-44bc-ae2a-3330aba9ad05.jpg" width=400>

2023-07-27 16:50 UTC, dacharyc approved these changes
Overall, LGTM. There are just a few highlighting things I think we need to fix, and I had a couple of Qs about some inconsistencies in empty lines between the TS and JS examples that are non-blocking - just wondering if there's a difference in convention there, or difference in linting, or if they're just inconsistent.

2023-07-27 16:50 UTC, dacharyc commented on source/sdk/react-native/crud/read.txt
> +      .. literalinclude:: /examples/generated/react-native/js/read.test.snippet.crud-read-filter-data.jsx
Similar to a comment down below, the TS example has an empty line on ln 12 before the return, but the JS one does not. It's not at all a big deal - just flagging it in case you want to make them consistent.

2023-07-27 16:50 UTC, dacharyc commented on source/sdk/react-native/crud/delete.txt
> +      .. literalinclude:: /examples/generated/react-native/js/delete.test.snippet.crud-delete-object.jsx
Similar to comments below - the TS example has an empty line on ln 10 before the return, the JS does not. Just flagging in case you want to make them consistent.

2023-07-27 16:50 UTC, dacharyc commented on source/sdk/react-native/crud/delete.txt
> +      .. literalinclude:: /examples/generated/react-native/js/delete.test.snippet.crud-delete-multiple-objects.jsx
Same as commented elsewhere - TS has an empty line before the return, JS does not. Just flagging in case.

2023-07-27 16:50 UTC, dacharyc commented on source/sdk/react-native/crud.txt
> +.. literalinclude:: /examples/generated/react-native/ts/create.test.snippet.crud-create-object.tsx
I think the highlighting here needs to be updated. I'm not sure which part you're trying to emphasize, so not sure what line numbers to suggest as a fix.

2023-08-01 07:02 UTC, takameyer requested changes
Thanks for getting these updated.  I would say a good amount of my comments are out of scope for the work requested here, but may be good to follow up on and discuss.
I do have a few suggestions and clarifications that should be worked on before publshing.

2023-08-01 07:02 UTC, takameyer requested changes
Thanks for getting these updated.  I would say a good amount of my comments are out of scope for the work requested here, but may be good to follow up on and discuss.
I do have a few suggestions and clarifications that should be worked on before publishing.

2023-08-02 18:43 UTC, krollins-mdb commented on examples/react-native/__tests__/js/CRUD/create-test.jsx
Good question! I'm slowly porting all code over to TypeScript files. We can write plain 'ol JavaScript in TypeScript if needed. And sometimes a sample is valid for both. In those cases, I'm removing the JavaScript version.

This will hopefully be a moot point in the future. I'm looking into generating JavaScript samples from TypeScript.

2023-08-02 19:29 UTC, krollins-mdb commented on source/sdk/react-native/crud.txt
> +.. literalinclude:: /examples/generated/react-native/ts/create.test.snippet.crud-create-object.tsx
Thank you! Just needed to include line 33 as well.

2023-08-02 19:33 UTC, krollins-mdb commented on source/sdk/react-native/crud/delete.txt
> +      .. literalinclude:: /examples/generated/react-native/js/delete.test.snippet.crud-delete-object.jsx
Ah, thanks for noticing these. More clean up from tests I didn't write. 😢 

I'll make sure that they're all consistent.

2023-08-02 19:52 UTC, krollins-mdb commented on source/sdk/react-native/crud/update.txt
> +      .. literalinclude:: /examples/generated/react-native/js/update.test.snippet.crud-bulk-update.jsx
Thanks for noticing! I've been cleaning these up in the JS SDKs. For some reason, previous writers would use tabs when there's no difference between the TypeScript and JavaScript. I'll consolidate this down to one sample.

2023-08-02 20:03 UTC, krollins-mdb commented on source/sdk/react-native/realm-files/configure-a-realm.txt
>  To learn how to open a realm using Device Sync, refer to
Good point! I don't think this one is necessary.

2023-08-02 20:11 UTC, krollins-mdb commented on source/sdk/react-native/realm-files/configure-a-realm.txt
> +Realm Configuration With @realm/react
Good points! I've restructured the page a bit - it definitely needed some work.

I added the no-schema section somewhat recently. We've had customers ask about it and Kenneth created a docs ticket. Probably mostly useful for testing and debugging? We could move this section over to testing when I finally have time to write that up.

2023-08-03 15:03 UTC, krollins-mdb commented on source/sdk/react-native/crud/create.txt
>  object conforms to the schema, then Realm stores the object.
I've created a ticket to make sure this work is tracked: https://jira.mongodb.org/browse/DOCSP-31867

2023-08-03 16:09 UTC, takameyer commented on source/sdk/react-native/realm-files/configure-a-realm.txt
> +Realm Configuration With @realm/react
Well, I think including it is fine, but maybe have a lower placement on the page.

2023-08-04 20:34 UTC, krollins-mdb commented on source/sdk/react-native/realm-files/configure-a-realm.txt
>  Key Concept: Realm Files
Yeah, this is a legacy section that I just haven't gotten around to clearing out yet. I like the idea of adding a reference of sorts to this page and reducing the number of specific examples. I'll look at re-working the page in another piece of work.

2023-08-07 21:23 UTC, krollins-mdb commented on source/sdk/react-native/realm-files/configure-a-realm.txt
>  Key Concept: Realm Files
a

2023-08-08 22:38 UTC, dacharyc reviewed
You have put a ton of work into this PR, and it shows! I've got a selection of small comments, typo fixes, broken links, and little things to fix but it's all very minor. Great work!

2023-08-08 22:38 UTC, dacharyc commented on source/sdk/react-native/realm-files/configure-a-realm.txt
> +of a :js-sdk:`Configuration object <Realm.html#~Configuration>`. You can also
This was a little odd - so far the API reference links on this page are to `@realm/react`, but here we're linking to the JS config API documentation. 

Should we make it clearer that this is the JS SDK Configuration API reference? My initial thought was that this was an incorrect link so I wonder if folks will think there is an error here. (I guess this applies to ln 44 above, too.)

```suggestion
of a :js-sdk:`Node.js SDK Configuration object <Realm.html#~Configuration>`. You can also
```

2023-08-08 22:38 UTC, dacharyc commented on source/sdk/react-native/realm-files/configure-a-realm.txt
> +  :realm-react-sdk:`createRealmContext() </functions/createRealmContext.html>`.
This link is returning a 403 for me.

2023-08-08 22:38 UTC, dacharyc commented on source/sdk/react-native/realm-files/configure-a-realm.txt
> +objects using :realm-react-sdk:`createRealmContext() </functions/createRealmContext.html>`.
Same as above - the link is returning a 403.

2023-08-08 22:38 UTC, dacharyc commented on source/sdk/react-native/sync-data/configure-a-synced-realm.txt
> +You configre a a synced realm using the providers from ``@realm/react``.
```suggestion
Configure a synced realm using the providers from ``@realm/react``.
```

2023-08-08 22:38 UTC, dacharyc commented on source/sdk/react-native/sync-data/configure-a-synced-realm.txt
> +Configure user authentication with ``AppProvider`` and ``UserProvider``. Then
```suggestion
Configure user authentication with ``AppProvider`` and ``UserProvider``. Then,
```

2023-08-08 22:38 UTC, dacharyc commented on source/sdk/react-native/sync-data/configure-a-synced-realm.txt
> +   :emphasize-lines: 9-19
I think the highlighting here is off. If you're trying to highlight `RealmProvider`, we're missing the opening line.
```suggestion
   :emphasize-lines: 8-19
```

2023-08-10 18:15 UTC, krollins-mdb commented on examples/react-native/__tests__/js/realm-database/configure-realm-multiple.test.jsx
> +  // :remove-start:
Yep! Thank you for catching these.

2023-08-10 18:40 UTC, krollins-mdb commented on source/sdk/react-native/realm-files/configure-a-realm.txt
> +of a :js-sdk:`Configuration object <Realm.html#~Configuration>`. You can also
Great point! The `realm/react` docs also include content for the regular JS SDK stuff. I hadn't considered it before, but I think we should just link out to the `@realm/react` docs exclusively. I'll do that as part of another PR, but I can at least update all the links on these pages.

That way, we're consistently sending readers to the same place.

A potential downside is that we end up in a weird place where the `@realm/react` docs haven't yet picked up the latest changes from Realm.js. @takameyer, does the automated docs process run the `@realm/react` TypeDoc generation when there's an update to the Realm.js TypeDoc?

2023-08-10 19:36 UTC, krollins-mdb commented on source/sdk/react-native/sync-data/configure-a-synced-realm.txt
> +You configre a a synced realm using the providers from ``@realm/react``.
I love to `configre` things. Sounds fancier than just configure. 😆 
Thank you for catching this mess.

2023-08-10 19:47 UTC, krollins-mdb commented on examples/react-native/__tests__/js/CRUD/delete.test.jsx
>      expect(getAllByTestId('deleteDog').length).toBe(3); // we can't use the value of deleteDogButtons because the variable doesn't update when a deleteDog testID is removed from the UI, so we need to
I've been trying to clean up these comments. It's a style that was used in the SDK before and it's very hard to read. Thanks for pointing it out here.

2023-08-10 19:50 UTC, krollins-mdb commented on examples/react-native/__tests__/js/Models/Invoice.js
> -// :snippet-start: js-invoice-schema
I'm not sure if we ever generated that snippet or if I already removed it. Either way, it doesn't exist in the JS generated snippets directory.

2023-08-10 19:50 UTC, krollins-mdb commented on examples/react-native/__tests__/ts/CRUD/create.test.tsx
> +class Dog extends Realm.Object {
Yep! Thank you.

2023-08-10 19:51 UTC, krollins-mdb commented on examples/react-native/__tests__/ts/Models/Invoice.ts
> -// :snippet-start: ts-invoice-schema
The TS snippet also doesn't exist. Either I deleted it in a previous PR or we never actually generated this snippet.

2023-08-10 21:11 UTC, merged