(DOCSP-31531): NET SDK Migrate PBS to FS updates
mongodb/docs-realm pull request #2916
Opened 2023-07-26 20:52 UTC by dacharyc

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-31531

### Staged Changes

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [ ] Create Jira ticket for corresponding docs-app-services update(s), if any
- [ ] Checked/updated Admin API
- [ ] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-07-26 22:22 UTC, MongoCaleb approved these changes
Approving with some open questions. Overall looks great!

2023-07-26 22:22 UTC, MongoCaleb commented on source/sdk/dotnet/sync.txt
> +   We recommend new apps use Flexible Sync.
perhaps: "We recommend **all** apps..." or just "We recommend using Flexible Sync." ?

2023-07-26 22:22 UTC, MongoCaleb commented on source/sdk/dotnet/sync/configure-and-open-a-synced-realm.txt
> +<ADD-FS-CODE-EXAMPLE-HERE>
Would you like me to create this?

2023-07-26 22:22 UTC, MongoCaleb commented on source/sdk/dotnet/sync/configure-and-open-a-synced-realm.txt
> +Open a Synced Realm While Offline
I'm still seeing the See Also in the staging build. ??

2023-07-26 22:22 UTC, MongoCaleb commented on source/sdk/dotnet/sync/partition-based-sync.txt
> +Partition-Based Sync is currently the only Sync Mode that supports upload
Is this still true? I don't think so...but my brain is tired. I'll check tomorrow, unless you already know.

2023-07-27 18:34 UTC, dacharyc commented on source/sdk/dotnet/sync.txt
> +   We recommend new apps use Flexible Sync.
Hmm. Gonna go with "We recommend using Flexible Sync." This was going to have to be removed soon anyway when you can only create new apps using FS. The more generic phrasing also covers the migration case so it won't necessarily need to be pulled.

2023-07-27 18:38 UTC, dacharyc commented on source/sdk/dotnet/sync/partition-based-sync.txt
> +Partition-Based Sync is currently the only Sync Mode that supports upload
Oh, I thought it was. I seem to recall someone saying there is work coming in the next Q either in Core or Sync to make this work properly for FS - I can't recall what exactly the limitation was.

Technically there is nothing stopping you from using it with FS - it doesn't crash or throw an error - but my understanding is that it doesn't show progress properly.

2023-07-27 18:40 UTC, dacharyc commented on source/sdk/dotnet/sync/configure-and-open-a-synced-realm.txt
> +Open a Synced Realm While Offline
Huh, weird, I am not. That's strange!

2023-07-27 18:54 UTC, dacharyc commented on source/sdk/dotnet/sync/partition-based-sync.txt
> +Partition-Based Sync is currently the only Sync Mode that supports upload
Blerg, just checked and it seems upload progress works properly, but download progress doesn't. Seems odd to separate them, so maybe I'll move this back and just add a note about upload progress only working accurately for PBS.

2023-07-28 18:41 UTC, dacharyc commented on examples/dotnet/Examples/ClientResetExamples.cs
> +            user = await app.LogInAsync(Credentials.Anonymous(false));
This kept hanging when I was running the tests locally until I added the `false` here.

2023-07-31 07:58 UTC, papafe approved these changes
Left some small comments

2023-07-31 07:58 UTC, papafe commented on examples/dotnet/Examples/ClientResetExamples.cs
> +            user = await app.LogInAsync(Credentials.Anonymous(false));
Mmh, not sure why this one was hanging, it shouldn't be a problem to reuse the User. If it's still happening I'll take a look

2023-07-31 07:58 UTC, papafe commented on source/sdk/dotnet/sync/partition-based-sync.txt
> +You pass in the partition value when you open a synced realm.
Maybe this sentence can go together with the previous one? I don't have a strong opinion, it's just that both sentences feel lonely 😁

2023-07-31 07:58 UTC, papafe commented on source/sdk/dotnet/sync/partition-based-sync.txt
> +   object that includes the :ref:`partition name <partition-value>` and
In the staged change this says "partition name" instead of "partition value"

2023-07-31 07:58 UTC, papafe commented on source/sdk/dotnet/sync/partition-based-sync.txt
> +   the :dotnet-sdk:`User <reference/Realms.Sync.User.html>` object.
I don't think that the snippet is included in this PR, but in the snippet it catches the `RealmFileAccessErrorException`. It should catch a generic `Exception`, since there are multiple errors that can be raised at this point

2023-07-31 07:58 UTC, papafe commented on source/examples/generated/dotnet-flexible-sync/FlexibleSyncExamples.snippet.open-fs-realm.cs
> +var realm = Realm.GetInstance(config);
```suggestion
var realm = await Realm.GetInstanceAsync(config);
```
In the text preceding this we say we're going to use `GetInstanceAsync` so that's what we should use. 
Also, in the following snippet, that I think is not included, we are using `GetInstance`, while we say the opposite. We should fix that snippet too
(in the "Configure & Open a Synced Realm" page)

2023-07-31 07:58 UTC, papafe commented on source/examples/generated/dotnet-flexible-sync/FlexibleSyncExamples.snippet.open-fs-realm-offline.cs
> +
Not sure why in the `if` section we have an empty line between each command, while in the `else` section it's all together. We should just decide for one way, personally the `else` way looks fine.

2023-07-31 07:59 UTC, papafe requested changes
Left some small comments here and there

2023-07-31 17:58 UTC, dacharyc commented on source/sdk/dotnet/sync/partition-based-sync.txt
> +   the :dotnet-sdk:`User <reference/Realms.Sync.User.html>` object.
Got it - updated this example. Thank you!

2023-07-31 18:00 UTC, dacharyc commented on examples/dotnet/Examples/ClientResetExamples.cs
> +            user = await app.LogInAsync(Credentials.Anonymous(false));
I tried removing this when I updated the code examples, and it started hanging again - but passed when I put it back. I can leave a ticket for Caleb to investigate this when he's back from vacation, if you don't think this should be an issue.

2023-08-01 14:06 UTC, papafe commented on examples/dotnet/Examples/ClientResetExamples.cs
> +            user = await app.LogInAsync(Credentials.Anonymous(false));
Yes, I think it's not a problem

2023-08-01 14:08 UTC, papafe commented
Looks good!

2023-08-01 14:09 UTC, papafe commented on examples/dotnet/Examples/FlexibleSyncExamples.cs
> +            var realm = Realm.GetInstanceAsync(config);
If this one is using the async version, then it needs `await` too

2023-08-01 20:37 UTC, merged