(DOCSP-29317) Document new subscribe API for Node.js
mongodb/docs-realm pull request #2918
Opened 2023-07-27 03:03 UTC by krollins-mdb

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-29317

### Staged Changes

- [Manage Flexible Sync Subscriptions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

### Animal Wearing a Hat

![](https://imgur.com/YOQZXx8)

2023-08-16 20:09 UTC, nlarew requested changes
Good work so far! Left a bunch of smaller suggestions and comments.

2023-08-16 20:09 UTC, nlarew commented on source/sdk/node/sync/flexible-sync.txt
> +`````````````````````````
```suggestion
~~~~~~~~~~~~~~~~~~~~~~~~~
```

Let's flatten this section out. I don't think this needs to be a subsection of Add a Subscription even though the APIs are similar.

2023-08-16 20:09 UTC, nlarew commented on source/sdk/node/sync/flexible-sync.txt
> +called an initial subscription.
When/why would I want to use an initial subscription vs just adding them in my code normally?

2023-08-16 20:09 UTC, nlarew commented on source/sdk/node/sync/flexible-sync.txt
> +your realm is opened.
This implies the default behavior is something else. Can we call out the default behavior + why you'd want to configure this?

2023-08-16 20:09 UTC, nlarew commented on source/sdk/node/sync/flexible-sync.txt
> +
Can't comment directly, but there's a typo in the note below: `s/throw/throws`. Also nitpick but no need for the comma before throws.

2023-08-16 20:09 UTC, nlarew commented on source/sdk/node/sync/flexible-sync.txt
> +:ref:`node-sync-subscribe-to-queryable-fields` section.
```suggestion
For better performance when making multiple subscription changes, use the
``subscriptions`` API to update all the subscriptions in a single transaction. To learn how, see
:ref:`node-sync-subscribe-to-queryable-fields`.
```

2023-08-21 11:57 UTC, takameyer approved these changes
Just a few minor things.  Looks great!

2023-08-21 11:57 UTC, takameyer commented on source/sdk/node/sync/flexible-sync.txt
> +   :language: javascript
The code example shows "throwOnUpdate" but doesn't go into detail what that will do.  If this option is explained in another section, then it should be excluded here so that users will not inadvertantly copy said code.

2023-08-22 08:49 UTC, elle-j approved these changes
Great work!

2023-08-22 08:49 UTC, elle-j commented on source/sdk/node/sync/flexible-sync.txt
> +- ``Never``: Never wait to download matching objects. The app needs an internet
Small correction: `FirstTime` is the default behavior.

2023-08-22 08:49 UTC, elle-j commented on source/sdk/node/sync/flexible-sync.txt
> +realm. There is no API to wait for ``.unsubscribe()`` to sync with the server.
Adding to the above comment. Syncing does not stop in this case, it just syncs in the background. If the subscription was named, it will be removed by name, otherwise, it will be removed by query.

2023-08-22 17:28 UTC, krollins-mdb commented on source/sdk/node/sync/flexible-sync.txt
> +#. :ref:`Open the synced Realm with a Flexible Sync configuration <node-flexible-sync-open-realm>`
Good point! As part of the Node.js docs upgrade epic, I have plans to strengthen the relationship between opening a synced realm and adding subscriptions. This is a good indicator that the relationship isn't clear enough on the Open a Synced Realm page.

2023-08-22 17:29 UTC, krollins-mdb commented on source/sdk/node/sync/flexible-sync.txt
> +This creates an unnamed subscription and adds it to ``MutableSubscriptionSet``,
Nice catch. I'll rephrase.

2023-08-22 17:40 UTC, krollins-mdb commented on source/sdk/node/sync/flexible-sync.txt
> +subscription with the same name as an existing subscription throws an error.
Hmm. Yeah, I'll look at restructuring a bit to prioritize the subscription name approach.

2023-08-22 18:06 UTC, krollins-mdb commented on source/sdk/node/sync/flexible-sync.txt
> +persists both subscriptions to the subscription set.
Looking at it now, I'm not even sure this is worth covering here. The majority of the time, this isn't something people need to know about.

2023-08-22 18:09 UTC, krollins-mdb commented on source/sdk/node/sync/flexible-sync.txt
> +specify that a subscription should ``waitForSync``:
Yeah, I think "results" on its own is good enough.

2023-08-22 18:13 UTC, krollins-mdb commented on source/sdk/node/sync/flexible-sync.txt
> +- ``Never``: Never wait to download matching objects. The app needs an internet
Thank you!

2023-08-22 19:31 UTC, krollins-mdb commented on source/sdk/node/sync/flexible-sync.txt
> +   :language: javascript
Ah, yeah. It's an older sample. I have no idea why that's in there.

2023-08-23 15:04 UTC, krollins-mdb commented
Thanks for the reviews, everyone! This page was a challenge, as I had to reconcile the new API with the old API's content - which wasn't in the best of shape. This page is looking better with your help!

2023-08-29 18:33 UTC, nlarew commented on examples/node/v12/__tests__/manage-subscriptions.test.ts
> +    };
Did you have a particular reason for keeping the options object up here as a separate variable instead of defining it inline in `.subscribe()`? IMO it's a bit nicer to see the config as close to where it's used as possible + the inline approach could infer the type of `SubscriptionOptions` instead of needing to import & declare it.

2023-08-29 18:34 UTC, nlarew commented on source/sdk/node/sync/flexible-sync.txt
> +When you call .unsubscribe(), the associated subscription is removed.
```suggestion
When you call ``unsubscribe()``, the associated subscription is removed. 
```

2023-08-29 18:40 UTC, nlarew commented on source/sdk/node/sync/flexible-sync.txt
> +realm. Syncing will continue in the background, based on existing subscriptions.
```suggestion
The ``unsubscribe()`` method returns before objects matching the dropped subscription are removed from the realm. Sync continues in the background based on the new set of subscriptions.
```

Tweaked wording to frame things in terms of the function return + use present tense + avoid gerunds

2023-08-29 19:06 UTC, nlarew approved these changes
Awesome job on these updates! Left a few more comments & suggestions but overall I think the page is in a good spot. I'll leave those fixes up to your judgement - LGTM!

2023-08-30 17:37 UTC, krollins-mdb commented on examples/node/v12/__tests__/manage-subscriptions.test.ts
> +    };
Good point! I think I was using it in more than one place at some point and forgot to clean it up.

2023-08-30 17:52 UTC, merged