(DOCSP-29646) Fix CRUD - Create page example and add examples for diff relationships
mongodb/docs-realm pull request #2939
Opened 2023-08-08 15:26 UTC by amalhotra-mdb

## Pull Request Info

The current page has a schema that defines:

name!: string;
owner?: Realm.List<Person>;
age?: number;

But the practical example does not build the relationship - it omits an owner. And, really, it should be `owners` plural. The practical sample should show how to build this relationship.

We should add more examples for other relationships. We cover defining relationships in schemas well, but don't have good examples of them. This is a common implementation pain point.

### Jira

- https://jira.mongodb.org/browse/DOCSP-29646

### Staged Changes

- [CRUD - Create - React Native SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-29646/sdk/react-native/crud/create/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-08-09 14:36 UTC, krollins-mdb requested changes
Great work so far, @amalhotra-mdb!

I misled you on some of the testing - totally on me. We can walk through it on Zoom. Other than that, I have some suggestions for the first half or so of the page. I'll finish reviewing the rest after we've adjusted the tests.

2023-08-10 18:11 UTC, amalhotra-mdb commented on source/sdk/react-native/crud/create.txt
> +#. Capture our newly created Pet object in a ``newPet`` variable using the :ref:`@realm/react useObject() hook <react-native-use-object-hook>`.
thank you kyle! this makes a lot more sense to me. i used the same logic with company & employee, but wasn't really positive about the example making total sense in this context, since i changed it to only displaying creating a new company and linking the already existing employees to it. 

do you think i should change the whole schema to make this example make more sense? maybe some example where it makes sense to already have many objects of the same kind, and then have to create a new object to connect that collection of objects to? (if that makes sense.)

2023-08-10 18:12 UTC, amalhotra-mdb commented on source/sdk/react-native/crud/create.txt
> +#. Create a new Pet object within a :ref:`write transaction <react-native-write-transactions>` by calling the ``create()`` method on our realm instance.
thank you kyle! this makes a lot more sense to me. i used the same logic with company & employee, but wasn't really positive about the example making total sense in this context, since i changed it to only displaying creating a new company and linking the already existing employees to it. 

do you think i should change the whole schema to make this example make more sense? maybe some example where it makes sense to already have many objects of the same kind, and then have to create a new object to connect that collection of objects to? (if that makes sense.)

2023-08-11 01:16 UTC, krollins-mdb approved these changes
Nice work, @amalhotra-mdb! Creating React Native tests is not easy and you tackled some of the harder stuff (object relationships). This page has turned out great.

I do have some suggestions that would be good to look at before merging, but none of them should block you.

2023-08-11 01:16 UTC, krollins-mdb commented on source/sdk/react-native/crud/create.txt
> +In the following example of a ``CreatePersonInput`` component, we:
Each section of this page has a block of this type of content. They're often referred to as "procedures" or "tasks". Because they're all of the same type, they should all follow the same patterns. This is a form of [parallelism](https://openoregon.pressbooks.pub/lbcctechwriting/chapter/8-7-parallel-construction/) (or parallel structure) that happens at the page level, rather than the sentence level. 

On this page, not all of these procedures share exactly the same structure and conventions. For example, on this line, we talk about the component example itself to introduce the procedure. However, on line 70, we introduce the next procedure with:
> To create an object with a to-one relationship to another object:

In this case, our typical overall style is the second approach: state the task that we expect readers to accomplish.

It would be good to give each of the procedures on this page parallel structure.

2023-08-11 01:16 UTC, krollins-mdb commented on source/sdk/react-native/crud/create.txt
> +In the following example of a ``CreatePersonInput`` component, we:
I know you were working from existing content that set a precedent, but our [style guide recommends](https://www.mongodb.com/docs/meta/style-guide/writing/write-to-the-user/#write-to-the-user) mostly avoiding "we". Second person and imperative is usually better.

I'm cleaning up the content in the JS SDKs that was written in this style and forgot to mention that to you.

2023-08-11 12:43 UTC, krollins-mdb commented
@amalhotra-mdb, also, I merged a PR yesterday that introduced a couple merge conflicts for this PR. Sorry! We can walk through handling the merge conflicts together if you'd like.

2023-08-11 16:43 UTC, amalhotra-mdb commented on examples/react-native/__tests__/js/CRUD/create-test.test.jsx
> +
ah, those little spaces looked a little off to me too. will change!

2023-08-11 16:54 UTC, merged