DOCSP-32150: Update Kotlin Delete Users page
mongodb/docs-realm pull request #2949
Opened 2023-08-11 15:35 UTC by cbullinger

## Pull Request Info

Update existing [Delete Users](https://www.mongodb.com/docs/realm/sdk/kotlin/users/delete-users/) page: 

- Fix links pointing to Swift docs
- Add Create Users and Remove Users sections
- Retitle page to Create & Delete Users to align with other SDKs

### Jira

- https://jira.mongodb.org/browse/DOCSP-NNNNN

### Staged Changes

- [Create and Delete Users](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-32150-delete-users/sdk/kotlin/users/delete-users/) - updated page

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [x] Create Jira ticket for corresponding docs-app-services update(s), if any
- [x] Checked/updated Admin API
- [x] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-08-14 16:46 UTC, dacharyc requested changes
We should fix the instances where we say "App Services App" but we mean "client app" or "device." Otherwise, a handful of nitpicks you can feel free to incorporate or ignore.

2023-08-14 16:46 UTC, dacharyc commented on source/sdk/kotlin/users/delete-users.txt
> +- Deletes locally stored data associated with the user from the device.
I wonder if we want to be more specific here and say "synced realms?" I think this could be ambiguous otherwise.
```suggestion
- Deletes synced realms associated with the user from the device.
```

2023-08-14 16:46 UTC, dacharyc commented on source/sdk/kotlin/users/delete-users.txt
> +Because removing a user deletes any local realms owned by the user, you
Local realms don't really have a concept of being owned by a user.
```suggestion
Because removing a user deletes any synced realms owned by the user, you 
```

2023-08-14 16:46 UTC, dacharyc commented on source/sdk/kotlin/users/delete-users.txt
> +from your Atlas App Services App *and* the App Services server.
I think these things are both saying the same thing. We need to get the client app in, and I think "App Services server" isn't a term we generally use in the docs.
```suggestion
from your client app *and* the Atlas App Services App.
```

2023-08-14 16:46 UTC, dacharyc commented on source/sdk/kotlin/users/delete-users.txt
> +- Deletes locally stored data associated with the user from the device.
If you take my suggestion above about changing this to synced realms, we should do the same here.
```suggestion
- Deletes synced realms associated with the user from the device.
```

2023-08-14 16:46 UTC, dacharyc commented on source/sdk/kotlin/users/delete-users.txt
> +Because this method deletes any local realms owned by the user, you
```suggestion
Because this method deletes any synced realms owned by the user, you 
```

2023-08-14 16:46 UTC, dacharyc commented on source/sdk/kotlin/users/delete-users.txt
> +.. important:: Deleting a User Doesn't Delete User Metadata
Same Q as above - can we make this an `include` and add it to all the SDKs except Swift?

2023-08-14 16:46 UTC, dacharyc commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
> +        app.close()
A) Nice!
B) Should we add something to the Connect to Atlas App Services page about `.close()`?

2023-08-14 16:46 UTC, dacharyc commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
> +            // and the Atlas App Services server
Nit: we generally refer to "Atlas App Services App" - not server. We might want to clarify the wording here.
```suggestion
            // Delete the logged-in user from the device
            // and the Atlas App Services App
```

2023-08-14 16:46 UTC, dacharyc commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
> +            // Remove the user from the app
We might want to clarify this - if you've got a multiplatform app, like say I have an iOS and macOS app, I believe remove() just removes the user from the device. If the user is logged in somewhere else, I don't believe remove() removes them from there. So clarifying device might be more accurate here.
```suggestion
            // Remove the user from the device
```

2023-08-14 16:46 UTC, dacharyc commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
> +            // DOES NOT delete user from the server
To be consistent with our messaging, we should probably change this.
```suggestion
            // DOES NOT delete user from the App Services App
```

2023-08-14 16:46 UTC, dacharyc commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
> +            assertEquals(User.State.REMOVED, user.state)
This is one of those cases where we have to use our judgment about how difficult it is to test this properly vs. making sure we test what we assert in the docs. If we _really_ wanted to test this, we should check the App Services App to confirm the user object no longer exists in App Services. Otherwise, this is functionally the same as the `remove` example.

We could potentially do this by calling an Atlas Function. The Bushicorp `example-testers` app has a `deleteAUser` Function that we could modify to create a `getAUser` function using a `get` request. This would return a user object matching the `user.id` if the user still exists, and we would consider it a test fail here if it successfully returns a user.

If you _want_ to do that, feel free to ping me about how we might set that up. But I think it would also be reasonable to say this is more work than we want to do to test this, when really we could just rely on the SDK to have tested this properly. I'll leave that up to you.

2023-08-14 16:46 UTC, dacharyc commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
> +
I think showing this in the snippet doesn't quite make sense without adding some comment to represent some intermediary state, something like:

```
// Work with the user... then later:
```

2023-08-14 18:31 UTC, cbullinger commented on source/sdk/kotlin/users/delete-users.txt
> +The Kotlin SDK provides methods to create and delete users in your Atlas App
Updated

2023-08-14 18:32 UTC, cbullinger commented on source/sdk/kotlin/users/delete-users.txt
> +method on a user to remove the ``User`` object from your Atlas App Services App. This method *does not* delete the ``User`` object from the Atlas App Services server.
updated

2023-08-14 18:33 UTC, cbullinger commented on source/sdk/kotlin/users/delete-users.txt
> +Because removing a user deletes any local realms owned by the user, you
updated

2023-08-14 18:33 UTC, cbullinger commented on source/sdk/kotlin/users/delete-users.txt
> +- Deletes locally stored data associated with the user from the device.
updated

2023-08-14 18:34 UTC, cbullinger commented on source/sdk/kotlin/users/delete-users.txt
> +from your Atlas App Services App *and* the App Services server.
updated

2023-08-14 18:34 UTC, cbullinger commented on source/sdk/kotlin/users/delete-users.txt
> +- Deletes locally stored data associated with the user from the device.
updated

2023-08-14 18:34 UTC, cbullinger commented on source/sdk/kotlin/users/delete-users.txt
> +Because this method deletes any local realms owned by the user, you
updated

2023-08-14 18:38 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
> +        app.close()
I cut a ticket to add it (and some additional config info that's missing from that page as well)

2023-08-14 18:40 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
> +            // and the Atlas App Services server
updated

2023-08-14 18:40 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
> +            // Remove the user from the app
thanks! updated

2023-08-14 18:40 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
> +            // DOES NOT delete user from the server
updated

2023-08-14 18:41 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
> +
updated

2023-08-14 18:52 UTC, cbullinger commented on source/sdk/kotlin/users/delete-users.txt
> +.. important:: Deleting a User Doesn't Delete User Metadata
we can if we don't mind the links being updates to more generic app services links (vs. sdk-specific procedures for metadata and custom user data)

2023-08-15 11:30 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
> +            assertEquals(User.State.REMOVED, user.state)
It's kind of extra, but I did add the function call to get the user

2023-08-15 11:30 UTC, cbullinger commented on source/sdk/kotlin/users/delete-users.txt
> +.. tip:: Google and Apple Account Deletion Requirements
Added

2023-08-15 13:44 UTC, dacharyc approved these changes
LGTM - nice work!

2023-08-15 13:44 UTC, dacharyc commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
> +            assertEquals(User.State.REMOVED, user.state)
Nice job! This was definitely a nice-to-have and not required, but it's a bonus to have it properly tested and it also gives us practice working with App Services & SDK features.

2023-08-16 10:45 UTC, merged