Docsp 30003
mongodb/docs-realm pull request #2979
Opened 2023-08-29 18:38 UTC by lindseymoore

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-30003

### Staged Changes

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [ ] Create Jira ticket for corresponding docs-app-services update(s), if any
- [ ] Checked/updated Admin API
- [ ] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-09-05 22:26 UTC, lindseymoore commented on source/sdk/react-native/crud/query-data.txt
> +Full-Text Search Tokenizer Details
The details for the tokenizer are non-existent in the JS API ref. Should I reach out to an engineer to confirm that the behavior works the same for the other SDKs or leave out this section completely?

2023-09-06 13:33 UTC, krollins-mdb commented on source/sdk/react-native/crud/query-data.txt
> +Full-Text Search Tokenizer Details
It would definitely be good to get an engineer from the JS team to confirm. This is useful info, but we need to make sure it's correct.

2023-09-07 08:57 UTC, elle-j reviewed
Nice work! 🚀 Only got some small suggestions for now. If @papafe has a few minutes to look through the draft he'd be a great pair of eyes 👍

2023-09-07 08:57 UTC, elle-j commented on examples/react-native/v12/TestApp/src/components/FtsQuery.tsx
> +      realm.create('Book', {
It's definitely fine to pass the string `'Book'` here. Just to mention some alternatives:
* Since you passed the `Book` class in the `schema`, you can also pass it here (instead of the string). This way, TypeScript can infer the returned type.
* If you pass the schema name instead (the string), but don't want to hard code the string `'Book'`, you can always use `Book.schema.name`.

2023-09-07 08:57 UTC, elle-j commented on source/sdk/react-native/model-data/define-a-realm-object-model.txt
> +following example, we set the indexed type for the ``name`` property to ``full-text``:
Unsure if the docs usually include the single/double quotes when showing string literals in the text. If so, make sure to use that for `'full-text'`.
```suggestion
type to ``'full-text'``. This enables full-text queries on the property. In the 
following example, we set the indexed type for the ``name`` property to ``'full-text'``:
```

2023-09-08 18:24 UTC, lindseymoore commented on examples/react-native/v12/TestApp/src/components/FtsQuery.tsx
> +          writeBooks(bookName, Number(bookPrice));
Keeping the 0 to a string, so I can use TextInput more easily!

2023-09-08 18:53 UTC, lindseymoore commented on source/sdk/react-native/crud/query-data.txt
> +Full-Text Search Tokenizer Details
@elle-j Would you be able to confirm the tokenizer details here?

2023-09-08 18:57 UTC, lindseymoore commented on source/sdk/react-native/crud/query-data.txt
@krollins-mdb Can you please provide feedback on this when you review?

2023-09-11 11:36 UTC, elle-j commented on source/sdk/react-native/crud/query-data.txt
> +Full-Text Search Tokenizer Details
Yes those are correct. As in the Flutter description, it could be helpful to include inline examples to better understand each bullet point 🙂

Perhaps bullet point 3 and 4 can be combined since 4 refers to 3 when saying "All other characters..".

2023-09-13 09:26 UTC, papafe commented on source/examples/generated/react-native/v12/FtsQuery.snippet.react-native-fts-query.tsx
> +const booksWithHunger = books.filtered("name TEXT \$0", ["hunger"]);
I'm not sure why in the examples here we are using the backslash and the arrays. Couldn't we just write:
```ts
const booksWithHunger = books.filtered("name TEXT $0", "hunger");
```

2023-09-13 09:43 UTC, elle-j commented on source/examples/generated/react-native/v12/FtsQuery.snippet.react-native-fts-query.tsx
> +const booksWithHunger = books.filtered("name TEXT \$0", ["hunger"]);
I believe she has updated this, but may not be reflected in the `generated` files yet 👍

2023-09-13 13:54 UTC, krollins-mdb requested changes
Excellent work so far, @lindseymoore! I think we need to refactor the test a bit more, but it's very close. 😄

2023-09-13 13:54 UTC, krollins-mdb commented on source/examples/generated/react-native/v12/FtsQuery.snippet.react-native-fts-query.tsx
> +const booksWithHunger = books.filtered("name TEXT \$0", ["hunger"]);
Yep. @lindseymoore, don't forget to run Bluehawk again. 🐦

2023-09-13 13:54 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/src/components/FtsQuery.tsx
> +  // :snippet-start: react-native-fts-query
It's a bit awkward in instances like this, but we should show where `useQuery` comes from. We can use [Bluehawk's `uncomment` tag](https://mongodb-university.github.io/Bluehawk/reference/tags#uncomment) to include it without moving the actual imports around.

So, after line 48, we can put something like this:
``` js
// :uncomment-start:
// import {useQuery} from "@realm/react";
// :uncomment-end:
```

2023-09-13 13:54 UTC, krollins-mdb commented on source/sdk/react-native/crud/query-data.txt
@elle-j, is there anything specific you'd like to see here for TypeScript? If used in a TS file, like this code is, `useQuery(Book)` gives us type safety and information. It's also valid JavaScript on its own.

We're shifting to TS-only examples for the React Native docs, but when there are cases when the TS examples are also valid JS examples.

2023-09-13 13:54 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/src/components/FtsQuery.tsx
> +      <Text>  </Text>
We have an empty <Text> component here. Did you need this for something?

2023-09-13 13:54 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/src/components/FtsQuery.tsx
> +};
Add empty line at the end of the file.

```suggestion
};

```

2023-09-13 13:54 UTC, krollins-mdb commented on source/sdk/react-native/crud/query-data.txt
> +In the following example, we query on the ``Book.name`` field:
I'm still figuring out the best way to show readers the object models we use for examples. For now, what do you think of including the `rn-fts-annotation` sample here too? Then readers won't be confused about what the `Book` class is.

2023-09-13 13:54 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/__tests__/crud/full-text-search.test.tsx
> +    // check the screen fro results of query
Tiny typo. 😄 
```suggestion
    // check the screen for results of query
```

2023-09-13 13:54 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/__tests__/crud/full-text-search.test.tsx
> +    // NOW I NEED TO TEST
I assume this is an old comment you left for yourself? 😆

2023-09-13 13:54 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/__tests__/crud/full-text-search.test.tsx
> +// also where is the api for filtered? under results
Is this one also an old comment for yourself?

2023-09-13 13:54 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/src/components/FtsQuery.tsx
> +  const booksWithHunger = books.filtered("name TEXT $0", "hunger");
This variable name makes me laugh. 😆 
I'm enjoying the thought of books being hungry.

2023-09-13 13:54 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/__tests__/crud/full-text-search.test.tsx
> +    });
Does this work? The rendered <Text> nodes are "Books with 'swan'" and "Books with 'hunger'", aren't they?
Which <Text> node are you trying to get here?

2023-09-13 13:54 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/__tests__/crud/full-text-search.test.tsx
> +    expect(checkTheBooks.children[1]).toBe('2');
We're not creating any books as part of the test. That means the test is relying on the fact that you open the simulator and create books with specific titles. That info then lives in the realm at the default location, so this test would pass.

But if you don't do that in the simulator and create books with specific information, this test will fail.

We should mimic a user selecting a "Create books" button that creates the books we need. You can see how to mimic a user in [my latest PR](https://github.com/mongodb/docs-realm/pull/3010/files#diff-d8ea36f6d914d5ef1a6514b6a86682c3647d2393fcd318dbfd96ca56fe15c249R65-R89).

I'm happy to hop on a call to discuss. This stuff isn't easy to reason about and I haven't done the best job of writing all these things down yet.

2023-09-13 19:48 UTC, lindseymoore commented on examples/react-native/v12/TestApp/src/components/FtsQuery.tsx
> +      <Text>  </Text>
It's supposed to create a new line😅 Is there a better way to do so?

2023-09-15 13:41 UTC, elle-j commented on source/sdk/react-native/crud/query-data.txt
Ah okay sounds good! 🙂 The only thing then would be to type annotate the `TaskSchema` and `ProjectSchema` (with `: ObjectSchema`) in the section [Examples on This Page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-30003/sdk/react-native/crud/query-data/#examples-on-this-page).

P.S. I don't think that was a part of this PR explicitly, but saw it on the staging page 👍

2023-09-15 18:42 UTC, krollins-mdb commented on source/sdk/react-native/crud/query-data.txt
Ah, yes. Thanks for catching that! I have a Jira ticket to update all the TS object models for the React Native and Node.js SDKs. 😄 https://jira.mongodb.org/browse/DOCSP-32626 

That should be done next week, hopefully.

2023-09-15 18:48 UTC, krollins-mdb approved these changes
This looks great, @lindseymoore! Thanks for sticking with it. I know working with the React Native SDK and writing the tests can be a lot.

There are still some merge conflicts to resolve, though.

2023-09-18 19:22 UTC, merged