(DOCSP-29611): Node.js: Add cancelWaitsOnNonFatalError
mongodb/docs-realm pull request #2980
Opened 2023-08-30 16:44 UTC by dacharyc

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-29611

### Staged Changes

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [ ] Create Jira ticket for corresponding docs-app-services update(s), if any
- [ ] Checked/updated Admin API
- [ ] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-08-30 19:32 UTC, krollins-mdb requested changes
@dacharyc, thank you for putting this together! There are a couple of changes I think should be implemented before merging. They have to do with the differences between older SDK versions and v12.

I also have a number of less important suggestions and questions.

2023-08-30 19:32 UTC, krollins-mdb commented on examples/node/v12/__tests__/configure-and-open-synced-realm.test.ts
> +      realm.delete(realm.objects("Doggie"));
Is there a reason to repeat `realm.objects("Doggie")` here? You could pass `dogsAfterWrite` to achieve the same thing, no?

2023-08-30 19:32 UTC, krollins-mdb commented on source/sdk/node/app-services/connect-to-app-services-backend.txt
> +wait for uploads and downloads cancel. For an example, refer to
> When the timeout interval elapses, wait for uploads and downloads cancel.

This is a bit confusing. Does this mean that after the timeout elapses, sync will continue in the background if it hasn't finished or errored out?

2023-08-30 19:32 UTC, krollins-mdb commented on source/sdk/node/sync/configure-and-open-a-synced-realm.txt
> +When ``true``, the Realm JS SDK cancels asynchronous operations, such as
```suggestion
When ``true``, the Node.js SDK cancels asynchronous operations, such as 
```

2023-08-30 19:32 UTC, krollins-mdb commented on source/sdk/node/sync/configure-and-open-a-synced-realm.txt
> +:js-sdk:`SyncConfiguration <Realm.App.Sync.html#~SyncConfiguration>` object.
[Blocking] This has changed a bit in v12.
```suggestion
:js-sdk:`BaseSyncConfiguration <types/BaseSyncConfiguration.html>` object.
```

2023-08-30 19:32 UTC, krollins-mdb commented on source/sdk/node/sync/manage-sync-session.txt
> +realm, call ``uploadAllLocalChanges()``. This method returns true when
I know it's kind of implied because of the page we're on, but it may still be a good idea to mention that this method exists on the realm instance's SyncSession. Or link to the new docs: https://www.mongodb.com/docs/realm-sdks/js/latest/classes/SyncSession.html#uploadAllLocalChanges

2023-08-30 19:32 UTC, krollins-mdb commented on source/sdk/node/sync/manage-sync-session.txt
> +realm, call ``uploadAllLocalChanges()``. This method returns true when
Similar consideration for `downloadAllServerChanges()` below.

2023-08-30 19:32 UTC, krollins-mdb commented on source/sdk/node/sync/manage-sync-session.txt
> +You can specify a request timeout on the App configuration. With a timeout
Should we link to the API ref docs for `AppConfiguration` again on this page?

2023-08-30 19:32 UTC, krollins-mdb commented on source/sdk/node/sync/manage-sync-session.txt
> +configuration. With this bool set to ``true``, upload and download requests
And maybe link to `baseSyncConfiguration` here? Could help disambiguate between App and Sync configs.

2023-08-30 19:32 UTC, krollins-mdb commented on source/sdk/node/sync/manage-sync-session.txt
> +configuration. With this bool set to ``true``, upload and download requests
```suggestion
specified, you can set ``cancelWaitsOnNonFatalErrors`` on your Sync 
configuration. With this boolean set to ``true``, upload and download requests 
```

2023-08-30 19:32 UTC, krollins-mdb commented on examples/node/v12/__tests__/configure-and-open-synced-realm.test.ts
> +    // :snippet-end:
Should include the subscription part to highlight _why_ we're waiting for server changes?

2023-08-30 19:32 UTC, krollins-mdb commented on source/sdk/node/sync/manage-sync-session.txt
> +        :language: typescript
Including the single-line download example here feels odd to me. Could we split them out and move the examples under the paragraphs that reference their methods?

2023-08-31 19:18 UTC, dacharyc commented on examples/node/v12/__tests__/configure-and-open-synced-realm.test.ts
> +    const appId = "js-flexible-oseso";
Cool! But FWIW, I got an error when I tried to import this into the TS file:

> An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled. 

I did a little digging and didn't find an obvious place to enable that setting. A helpful SO post let me know I could just omit the `.ts` from the import statement and it would work - and it did!

2023-08-31 19:22 UTC, dacharyc commented on examples/node/v12/__tests__/configure-and-open-synced-realm.test.ts
> +      realm.delete(realm.objects("Doggie"));
Nope, not a good reason. I've been fighting some concurrency stuff in one of my personal project apps with Swift and one of the fixes for that is to re-query the objects you need on the appropriate thread. I may be a little too casual about just re-querying things now 😁

2023-08-31 19:28 UTC, dacharyc commented on source/sdk/node/sync/manage-sync-session.txt
> +realm, call ``uploadAllLocalChanges()``. This method returns true when
Thank you for the link! I drafted this before the new docs were available and couldn't find this in the v12.0.0 version. Updating both. 👍

2023-08-31 21:07 UTC, dacharyc commented on examples/node/v12/__tests__/configure-and-open-synced-realm.test.ts
> +    // :snippet-end:
I don't want to imply that downloading changes is tied in some way to the query subscription. You might want to download changes based on business logic in your app - like maybe if you're checking if a user is a paid user before presenting some feature. (Although maybe that's a bad example because you could do that in other ways.) I just don't want to couple these two things in the minds of the devs reading this code.

2023-08-31 21:10 UTC, dacharyc commented on source/sdk/node/sync/manage-sync-session.txt
> +configuration. With this bool set to ``true``, upload and download requests
Rewording this a little so this suggestion will be outdated.

2023-09-01 15:47 UTC, krollins-mdb commented on examples/node/v12/__tests__/configure-and-open-synced-realm.test.ts
> +    const appId = "js-flexible-oseso";
Oh. That's interesting. Hmm. Could be a Babel thing, but I've never encountered that before! I'll add it to the list of things to investigate if I ever have the time. 🙃

2023-09-01 16:18 UTC, krollins-mdb approved these changes
Looks great, @dacharyc. I a couple tiny suggestions and a bigger one I should have noticed in my first review. None of them are blocking. 😄

2023-09-01 18:59 UTC, merged