realm web landing page sync copy fixes
mongodb/docs-realm pull request #2986
Opened 2023-08-31 21:06 UTC by mongodben

## Pull Request Info

landing page incorrectly said web sdk doesn't support sync

### Jira

- n/a

### Staged Changes

- [Web SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/web_sync_homepage/web)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [ ] Create Jira ticket for corresponding docs-app-services update(s), if any
- [ ] Checked/updated Admin API
- [ ] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-08-31 21:37 UTC, nlarew approved these changes

2023-08-31 21:38 UTC, dacharyc requested changes
One minor point that doesn't seem quite accurate.

2023-08-31 21:38 UTC, dacharyc commented on source/web.txt
> +a local Realm database.
I don't think this is actually true anymore. The "Get Started with Device Sync" page says you _can_ create a "local" Realm: https://www.mongodb.com/docs/realm/web/sync/#open-a-non-synced-realm

But it's an in-memory Realm, it doesn't persist to disk. We should probably tweak this wording.

2023-09-01 14:52 UTC, mongodben commented on source/web.txt
> +a local Realm database.
good call out. adjusting phrasing to: 

```
Unlike the other Realm SDKs, Web SDK only support creating
a in-memory Realm database, not one persisted to disk.
```

2023-09-01 15:02 UTC, dacharyc approved these changes
Teeny nit, but otherwise LGTM. Thanks for tweaking this!

2023-09-01 15:02 UTC, dacharyc commented on source/web.txt
> +a in-memory Realm database, not one persisted to disk.
```suggestion
an in-memory Realm database, not one persisted to disk.
```

2023-09-05 16:09 UTC, merged