(DOCSP-32576) Document new subscribe API for React Native
mongodb/docs-realm pull request #3010
Opened 2023-09-12 20:53 UTC by krollins-mdb

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-32576

### Staged Changes

- [Manage Sync Subscriptions](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

### Animal Wearing a Hat

<img src="https://i.chzbgr.com/full/9197265920/h0EE55220/bearded-dragon-with-top-hat-reptile" width=400>

2023-09-18 21:46 UTC, lindseymoore requested changes
Some comments on including API references for methods and a question about a comment in three of the code snippets. Let me know if you have any questions, thanks!

2023-09-18 21:46 UTC, lindseymoore commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +The other supported ``WaitForSync`` options are:
Suggestion: Might also be nice to point to the API reference here once for WaitForSync.

2023-09-18 21:46 UTC, lindseymoore commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +The ``useRealm()`` hook gives you access to the currently-opened realm.
Suggestion: Include useRealm API reference

2023-09-18 21:46 UTC, lindseymoore commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +``SubscriptionSet``.
Suggestion: Could use API reference for SubscriptionSet here.

2023-09-18 21:46 UTC, lindseymoore commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +subscription that you want to update to the ``MutableSubscriptionSet.add()``
Suggestion: API reference for .add()

2023-09-18 21:46 UTC, lindseymoore commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +transaction by calling ``subscriptions.update()``.
Suggestion: API reference for .update()

2023-09-18 21:46 UTC, lindseymoore commented on source/sdk/react-native/sync-data/flexible-sync.txt
>  You can remove subscriptions in several ways:
```suggestion
You can remove subscriptions in the following ways:
```
Word change: Are these the only ways to remove the subscription? 'Several' to me makes it seem like there could be others.

2023-09-18 21:46 UTC, lindseymoore commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +calling ``.removeUnnamed()`` on ``mutableSubs``. ``.removeUnnamed()`` returns
API ref for .removeUnnamed()?

2023-09-18 21:46 UTC, lindseymoore commented on source/examples/generated/react-native/v12/BasicSubscription.snippet.subscribe-query.tsx.rst
> +     // ...work with the subscribed results list or modify the subscription.
This comment seems a bit unintentional and unnecessary for the section. Consider deleting or adding more details in the text following the code snippet. Or the reword below makes more sense to me. 

```suggestion
     // Continue work with the subscribed results list or modify the subscription ...
```

2023-09-18 21:46 UTC, lindseymoore commented on source/examples/generated/react-native/v12/WaitFirstTime.snippet.subscribe-query.tsx.rst
> +     // ...work with the subscribed results list or modify the subscription.
Same as above comment, consider rewording or deleting.

2023-09-18 21:46 UTC, lindseymoore commented on source/examples/generated/react-native/v12/WaitFirstTime.snippet.wait-firsttime.tsx.rst
> +     // ...work with the subscribed results list or modify the subscription.
Same as above comment on the BasicSubscription snippet, consider rewording or deleting.

2023-09-19 15:02 UTC, krollins-mdb commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +#. Query for the objects that you want to read and write.
The MongoDB style guide suggests not including links in procedure sections, as they distract from what the user is trying to do. https://www.mongodb.com/docs/meta/style-guide/style/links-and-cross-references/#avoid-inline-references-in-tutorials

I'll think about how to include these links somewhere though. I do think they'd be useful.

2023-09-19 20:14 UTC, krollins-mdb commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +#. Query for the objects that you want to read and write.
I've added an "API Reference" sections to the end of procedure topics where needed. The idea is to collect links to the API docs there so that they don't distract readers while they're trying to do something.

2023-09-19 20:38 UTC, lindseymoore requested changes
Like the API reference section! A few links are giving 403 errors and another small code snippet fix.

2023-09-19 20:38 UTC, lindseymoore commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +- :js-sdk:`MutableSubscriptionSet.add() </classes/MutableSubscriptionSet.html#removeUnnamed>`
Is this .add() reference necessary here in the remove section?

2023-09-19 20:38 UTC, lindseymoore commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +**API Reference**
Links need to be fixed, these API reference links are leading to pages with 403 errors.

2023-09-19 20:38 UTC, lindseymoore commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +- :js-sdk:`SubscriptionSet </classes/SubscriptionSet.html>`
403 Error

2023-09-19 20:38 UTC, lindseymoore commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +- :js-sdk:`unsubscribe() </classes/Results.html#unsubscribe>`
403 error

2023-09-19 20:38 UTC, lindseymoore commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +- :js-sdk:`waitForSync </enums/WaitForSync.html>`
403 error

2023-09-19 20:38 UTC, lindseymoore commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +**API Reference**
Top two links lead to 403 errors.

2023-09-19 20:38 UTC, lindseymoore commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +#. Query for the objects that you want to read and write.
Great idea!

2023-09-19 20:38 UTC, lindseymoore commented on source/examples/generated/react-native/v12/WaitFirstTime.snippet.wait-firsttime.tsx.rst
> +       <></>
```suggestion
 
```
Are the angle brackets necessary?

2023-09-19 21:02 UTC, krollins-mdb commented on source/examples/generated/react-native/v12/WaitFirstTime.snippet.wait-firsttime.tsx.rst
> +       <></>
This is a fragment - totally valid React: https://react.dev/reference/react/Fragment

It's useful for showing the nature of a full React Native component, but not including anything if it's not relevant to the code sample.

2023-09-19 21:05 UTC, krollins-mdb commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +- :js-sdk:`MutableSubscriptionSet.add() </classes/MutableSubscriptionSet.html#removeUnnamed>`
Oops. Thank you for catching that! The URL is correct, but I forgot to change the display text. Definitely running low on energy this afternoon!

2023-09-19 21:09 UTC, krollins-mdb commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +**API Reference**
Thanks for catching this too! Did platform change how the role links behave. I'm pretty sure I needed a preceding `/` before, but now those break the URLs...

2023-09-19 21:23 UTC, lindseymoore commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +**API Reference**
I'm honestly not sure! I just looked at the [:js-sdk: defintion](https://github.com/mongodb/snooty-parser/blob/095c4d2ad8fba25ba79406f643de0304e82abc42/snooty/rstspec.toml#L1458), and there is no ending ``/``, so perhaps :(

2023-09-19 21:27 UTC, lindseymoore approved these changes
LGTM, great work on a large page update!

2023-09-20 10:31 UTC, takameyer approved these changes
Just a few suggestions.  Otherwise looks great!

2023-09-20 10:31 UTC, takameyer commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +until synced data is downloaded. When you do need to wait for syned objects to
```suggestion
until synced data is downloaded. When you do need to wait for synced objects to
```

2023-09-20 10:31 UTC, takameyer commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +finish downloading, use ``waitForSync``. You can specify different behavior for
```suggestion
finish downloading, configure the ``waitForSync`` option. You can specify different behavior for
```

2023-09-20 10:31 UTC, takameyer commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +your subscriptions and how they handle witing for downloads.
```suggestion
your subscriptions and how they handle waiting for downloads.
```

2023-09-20 10:31 UTC, takameyer commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +Wait for a Query Subscription to Sync
Been giving this thought, I don't think theres much to change, but I'm trying to think of a situation in React Native where I actually would want to wait for this.  I guess one would want to set some state in this case and block the UI from rendering.  Definitely increases the need of a new hook from `@realm/react`, where the status of the subscription is sent back as a result.

2023-09-20 10:31 UTC, takameyer commented on examples/react-native/v12/TestApp/src/components/subscribeApi/WaitFirstTime.tsx
> +  const seenBirds = useQuery(Bird).filtered('haveSeen == true'); // :emphasize:
```suggestion
  const seenBirds = useQuery(Bird, col => col.filtered('haveSeen == true')); // :emphasize:
```
Let's make this syntax standard.  Otherwise on every re-render the collection reference will be updated.

2023-09-20 10:31 UTC, takameyer commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +Unsubscribe from a Query
Could be worth noting, subscriptions that have been added will persist upon the app opening again, unless the subscription has been removed.

2023-09-20 13:20 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/jest.config.ts
> +  roots: ['<rootDir>/src/__tests__'],
Yeah, that's probably a better way to do it. Easier to keep track of.

2023-09-20 13:21 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/src/__tests__/sync/SubscribeApi.test.tsx
> +    console.debug('after subnamenode found');
Oops! Thank you for noticing those! I do not want those anymore. 😆

2023-09-20 13:23 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/src/components/subscribeApi/WaitFirstTime.tsx
> +  const seenBirds = useQuery(Bird).filtered('haveSeen == true'); // :emphasize:
Agh, right. Thanks for reminding me. I need to break the old habit.

2023-09-20 15:16 UTC, krollins-mdb commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +Wait for a Query Subscription to Sync
Yeah, I don't think it would be a particularly common case. Ideally, people use initial subs and then pass filtered data to components as needed. But I can imagine some people having questions and thought it might be good to have this. Especially as the Node.js SDK and other SDKs use this syntax (or close to it).

2023-09-20 15:17 UTC, krollins-mdb commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +your subscriptions and how they handle witing for downloads.
Thanks for catching a couple of little typos!

2023-09-20 15:19 UTC, krollins-mdb commented on source/sdk/react-native/sync-data/flexible-sync.txt
> +subscription with the same name as an existing subscription throws an error.
Oh, good to know. Not sure why I missed that. Thank you!

2023-09-20 15:32 UTC, merged