DOCSP-32753: Update Kotlin's Define Object Model page
mongodb/docs-realm pull request #3019
Opened 2023-09-19 13:27 UTC by cbullinger

## Pull Request Info

- Convert existing [Data Model](https://www.mongodb.com/docs/realm/sdk/kotlin/realm-database/schemas/) landing page to a container
- Move relevant content to [Define an Object Model](https://www.mongodb.com/docs/realm/sdk/kotlin/realm-database/schemas/define-realm-object-model/) page
- Update Define an Object Model page with any missing content, examples
- Clean up existing examples in kotlin test suite

### Jira

- https://jira.mongodb.org/browse/DOCSP-32753

### Staged Changes

- [Define an Object Model - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-32753-define-object-model-page/sdk/kotlin/realm-database/schemas/define-realm-object-model/) - updated page
- [Model Data - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-32753-define-object-model-page/sdk/kotlin/realm-database/schemas/) - updated; now a container

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [x] Create Jira ticket for corresponding docs-app-services update(s), if any
- [x] Checked/updated Admin API
- [x] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-09-19 14:56 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AsymmetricSyncTest.kt
> -    // :snippet-start: asymmetric-model
moved relevant object model definitions to new Schema.kt file

2023-09-19 14:57 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/DataTypes.kt
> +// :snippet-start: timestamp-workaround
moved here to be with the other examples used on Supported Types page

2023-09-19 14:58 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SchemaTest.kt
> -// :snippet-start: example-schema
deleted - not used anymore

2023-09-19 14:58 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/SchemaTest.kt
> -            // :snippet-start: open-with-class
deleted snippet - not used anymore

2023-09-20 21:42 UTC, lindseymoore requested changes
A few minor copy changes.

2023-09-20 21:42 UTC, lindseymoore commented on source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
> +**Realm objects** are uniquely named Kotlin classes that you can work with
```suggestion
**Realm objects** are uniquely named instances of Kotlin classes that you can work with 
```
Think its more precise to say objects are instances of  a class. Or could say 'Realm object models' instead and get rid of the 'instances' part I suggested.

2023-09-20 21:42 UTC, lindseymoore commented on source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
> +  - Realm-specific types, which you can use for unique
Is there a page to link to for the Realm-specific types since you linked for the others?

2023-09-20 21:42 UTC, lindseymoore commented on source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
> +To define a Realm object, create a Kotlin class that implements the `RealmObject
```suggestion
To define a Realm object model, create a Kotlin class that implements the `RealmObject 
```
Are you referring to creating an object instance or model here?

2023-09-20 21:42 UTC, lindseymoore commented on source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
> +   relationship, refer to :ref:`<kotlin-relationships>`.
```suggestion
   relationships, refer to :ref:`<kotlin-relationships>`.
```
Grammar fix

2023-09-20 21:42 UTC, lindseymoore commented on source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
> +To define an embedded object, create a Kotlin class that implements the
```suggestion
To define an embedded object type, create a Kotlin class that implements the 
```
if you're talking about creating a new object model.

2023-09-20 21:42 UTC, lindseymoore commented on source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
> +To define an :ref:`asymmetric object<kotlin-asymmetric-objects>`, create a
```suggestion
To define an :ref:`asymmetric object type<kotlin-asymmetric-objects>`, create a 
```
Could use 'type' or 'model' here, but perhaps be consistent about it throughout the page.

2023-09-20 21:42 UTC, lindseymoore commented on source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
> +To define a :ref:`RealmDictionary <kotlin-realm-dictionary>`, specify its
```suggestion
To define a property as a :ref:`RealmDictionary <kotlin-realm-dictionary>`, specify its 
```
For consistency with other sections.

2023-09-21 12:09 UTC, cbullinger commented on source/sdk/kotlin/realm-database/schemas/define-realm-object-model.txt
> +  - Realm-specific types, which you can use for unique
it's technically the Supported Types pages linked in the intro statement for this list, but I can add a link to that specific section here.

2023-09-21 17:38 UTC, lindseymoore approved these changes
LGTM!

2023-09-21 18:19 UTC, merged