DOCSP-30347: Convert Manage Users landing page
mongodb/docs-realm pull request #3021
Opened 2023-09-20 20:22 UTC by cbullinger

## Pull Request Info

- Convert existing [Manage Users](https://www.mongodb.com/docs/realm/sdk/kotlin/users/) landing page to a container page
- Move all relevant information to any child pages 
- Update and rename existing [Authenticate Users](https://www.mongodb.com/docs/realm/sdk/kotlin/users/authenticate-users/) page to Create and Authenticate Users
- Split existing [Create and Delete Users](https://www.mongodb.com/docs/realm/sdk/kotlin/users/delete-users/) page to only Delete Users 
- Clean up any example in test suite

### Jira

- https://jira.mongodb.org/browse/DOCSP-30347

### Staged Changes

- [Create & Authenticate Users - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/30347-manage-users-page/sdk/kotlin/users/authenticate-users/) - updated 
- [Delete Users - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/30347-manage-users-page/sdk/kotlin/users/delete-users/) - updated and moved in TOC
- [Manage Custom User Data - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/30347-manage-users-page/sdk/kotlin/users/custom-user-data/) - updated title to verb
- [Manage User Metadata - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/30347-manage-users-page/sdk/kotlin/users/user-metadata/) - updated title to verb
- [Manage Users - Kotlin SDK](https://preview-mongodbcbullinger.gatsbyjs.io/realm/30347-manage-users-page/sdk/kotlin/users/) - updated; now a container

### Reminder Checklist

If your PR modifies the docs, you might need to also update some corresponding
pages. Check if completed or N/A.

- [x] Create Jira ticket for corresponding docs-app-services update(s), if any
- [x] Checked/updated Admin API
- [x] Checked/updated CLI reference

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-09-20 21:06 UTC, cbullinger commented on examples/kotlin/shared/src/commonTest/kotlin/com/mongodb/realm/realmkmmapp/AuthenticationTest.kt
> +    ** Tests for Create and Authenticate Users page **
rearranged tests in file based on page they're used on

2023-09-21 19:35 UTC, lindseymoore requested changes
Some copy review comments, overall looks good so far with a few small changes needed.

2023-09-21 19:35 UTC, lindseymoore commented on source/sdk/kotlin/users/custom-user-data.txt
> +To use custom user data, you must have an you must have an
```suggestion
To use custom user data, you must have an 
```

2023-09-21 19:35 UTC, lindseymoore commented on source/sdk/kotlin/users/custom-user-data.txt
> +#. :ref:`Connect to Atlas App Services <kotlin-connect-to-backend>`
```suggestion
#. :ref:`Connect your app to Atlas App Services <kotlin-connect-to-backend>`
``` 
To make it a clearer procedural prerequisite step.

2023-09-21 19:35 UTC, lindseymoore commented on source/sdk/kotlin/users/delete-users.txt
> +your Atlas App Services App. Learn how to :ref:`<kotlin-authenticate-users>`.
```suggestion
your Atlas App Services App. For more information on how to create and authenticate users, see :ref:`<kotlin-authenticate-users>`.
```
Did you mean to do something like this to introduce further reading?

2023-09-21 19:35 UTC, lindseymoore commented on source/sdk/kotlin/users/delete-users.txt
>  The ``user.remove()`` method:
```suggestion
The ``user.remove()`` method acts as follows: 
```
Style Guide [Lists section](https://www.mongodb.com/docs/meta/style-guide/style/lists/) says lists should start with capital letter. Reformatting to help.

2023-09-21 19:35 UTC, lindseymoore commented on source/sdk/kotlin/users/delete-users.txt
> +- *does not* delete the ``User`` object from the Atlas App Services App
```suggestion
- *Does not* delete the ``User`` object from the Atlas App Services App.
```

2023-09-21 19:35 UTC, lindseymoore commented on source/sdk/kotlin/users/delete-users.txt
> +- deletes synced realms associated with the user from the device
```suggestion
- Deletes synced realms associated with the user from the device.
```

2023-09-21 19:35 UTC, lindseymoore commented on source/sdk/kotlin/users/delete-users.txt
> +- sets the
```suggestion
- Sets the
```

2023-09-21 19:35 UTC, lindseymoore commented on source/sdk/kotlin/users/delete-users.txt
> +- :ref:`logs the user <kotlin-logout>` out if they are logged in
```suggestion
- :ref:`Logs the user <kotlin-logout>` out if they are logged in.
```

2023-09-21 19:35 UTC, lindseymoore commented on source/sdk/kotlin/users/delete-users.txt
>  The ``user.delete()`` method:
```suggestion
The ``user.delete()`` method performs the following:
```
Same as above comment, lists should start with capital. I believe should end in period.

2023-09-22 11:38 UTC, cbullinger commented on source/sdk/kotlin/users.txt
> +
Added

2023-09-22 11:45 UTC, cbullinger commented on source/examples/generated/kotlin/AuthenticationTest.snippet.access-token-refresh.kt
> -// Gets the current refresh token for the user
Re-added

2023-09-22 11:48 UTC, cbullinger commented on source/sdk/kotlin/users/authenticate-users.txt
> +<docs/reference/android/current/class/LoginResult>`.
Moved to same line

2023-09-22 20:26 UTC, lindseymoore approved these changes
Small copy things, otherwise LGTM! Thanks for work on this :)

2023-09-22 20:26 UTC, lindseymoore commented on source/sdk/kotlin/users/authenticate-users.txt
> +Use this to login offline or :ref:`call an Atlas Function
```suggestion
Use this to log in offline or :ref:`call an Atlas Function 
```
verb typo!

2023-09-22 20:26 UTC, lindseymoore commented on source/sdk/kotlin/users/delete-users.txt
> +  to ``REMOVED``
```suggestion
  to ``REMOVED``.
```

2023-09-22 20:26 UTC, lindseymoore commented on source/sdk/kotlin/users/delete-users.txt
> +- deletes synced realms associated with the user from the device
```suggestion
- Deletes synced realms associated with the user from the device.
```
Same as in above section, capitalize first word of each item in list and add period.

2023-09-25 12:38 UTC, merged