(DOCSP-32579) Add compensating write handler example for React Native
mongodb/docs-realm pull request #3024
Opened 2023-09-22 15:19 UTC by krollins-mdb

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-32579

### Staged Changes

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

### Animal Wearing a Hat

<img src="https://i.pinimg.com/originals/61/8d/77/618d779ab1a34a3ff01cfed774d365a8.jpg" width=400>

2023-09-26 21:00 UTC, lindseymoore requested changes
Copy looks good! Request for more comments on code snippets.

2023-09-26 21:00 UTC, lindseymoore commented on source/examples/generated/react-native/v12/CompensatingWriteWrapper.snippet.handle-compensating-write-error.tsx.rst
More comments would be helpful in this snippet. Lining up the steps with the snippet was a bit confusing.

2023-09-27 13:29 UTC, krollins-mdb commented on source/examples/generated/react-native/v12/CompensatingWriteWrapper.snippet.handle-compensating-write-error.tsx.rst
> +   :emphasize-lines: 30
True. But it's relatively easy to miss this one line among all the provider stuff. I would highlight for the other steps, too, but there's no good way to do that - most of the sample would be highlighted. 😆

2023-09-27 13:34 UTC, krollins-mdb commented on source/sdk/react-native/sync-data/handle-sync-errors.txt
> +error handler will detect and respond to failed sync-related API calls to your
Hmm. After thinking it over, I've removed the last chunk of the sentence. It wasn't particularly helpful. And it's potentially confusing.

2023-09-27 13:43 UTC, krollins-mdb commented on source/examples/generated/react-native/v12/CompensatingWriteWrapper.snippet.handle-compensating-write-error.tsx.rst
Oof. I added comments for the sync config object, but the syntax highlighting doesn't recognize them as comments. As it currently is, I think the comments are distracting and not worth the value they add. What do you think? https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-32579/sdk/react-native/sync-data/handle-sync-errors/#handle-compensating-write-errors

2023-09-27 17:31 UTC, lindseymoore commented on source/examples/generated/react-native/v12/CompensatingWriteWrapper.snippet.handle-compensating-write-error.tsx.rst
I would put a comment above the start of the `CompensatingWriteErrorHandling` function. Something like:
// Create a callback that handles sync errors using CompensatingWriterError
I'd say it's good practice to put a comment to introduce a function. The other comments could be distracting, so I agree they can be deleted!

2023-09-27 17:32 UTC, lindseymoore commented on source/examples/generated/react-native/v12/CompensatingWriteWrapper.snippet.handle-compensating-write-error.tsx.rst
> +   :emphasize-lines: 30
Since the comments aren't registering properly in your above example, they can be deleted! In place of the comments, the highlighting does work well here since the line is easy to miss.

2023-09-27 17:37 UTC, lindseymoore approved these changes
LGTM! Let me know if you'd like me to take a look at the final commenting on the snippet :)

2023-09-27 17:54 UTC, merged