(DOCSP-32577) RN: Update inverse relationship examples
mongodb/docs-realm pull request #3031
Opened 2023-09-28 15:06 UTC by krollins-mdb

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-32577

### Staged Changes

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

### Animal Wearing a Hat

![](https://img.freepik.com/premium-photo/there-is-fish-wearing-hat-glasses-with-scarf-generative-ai_902338-33198.jpg?w=360)

2023-09-29 23:18 UTC, lindseymoore requested changes
I was confused my the code example I commented on. I think a bit more description could be included on how to define the object being linked to. Let me know if you want to hop on a call to discuss!

2023-09-29 23:18 UTC, lindseymoore commented on source/examples/generated/react-native/v12/models.snippet.define-one-to-many.ts.rst
> +     manufacturer!: Realm.List<ToManyManufacturer>;
I'm a bit confused by the syntax here. Does this point to a single manufacturer but is a list because you need to define the type, objectType, and property? Upon first reading the example, it seems like this is pointing to a list of manufacturers. Perhaps this could be described briefly in the text.

2023-10-02 14:18 UTC, krollins-mdb commented on source/sdk/react-native/model-data/relationships-and-embedded-objects.txt
> +   can expect that manufacturer to be named Nissan.
I agree that the IO output is nice. However, in this case, we're expecting a simple one-word string. I'm not sure the maintenance burden of adding the IO directive is worth it here. I'll add a comment to the code snippet though.

2023-10-02 20:32 UTC, lindseymoore requested changes
One more question and a few suggestions.

2023-10-02 20:32 UTC, lindseymoore commented on source/examples/generated/react-native/v12/models.snippet.define-one-to-many.ts.rst
> +         manufacturer: {
Would you also need to remove this manufacturer property from the schema if you remove it from the model parameters?

2023-10-02 20:32 UTC, lindseymoore commented on source/examples/generated/react-native/v12/models.snippet.define-inverse.ts.rst
> +         // A manufacturer that may have many CarInverse objects
```suggestion
         // A manufacturer's related CarInverse objects
```
Suggestion: simplify the comment, would do for the other snippets as well

2023-10-02 20:32 UTC, lindseymoore commented on source/examples/generated/react-native/v12/models.snippet.define-inverse.ts.rst
> +         manufacturer: {
I'd put a comment here as well: `\\ A car's related ManufacturerInverse objects`

2023-10-02 20:48 UTC, krollins-mdb commented on source/examples/generated/react-native/v12/models.snippet.define-one-to-many.ts.rst
> +         manufacturer: {
Nope. We still need this in the schema to be able to use `linkingObjects()`.

2023-10-02 21:13 UTC, lindseymoore approved these changes
Great work, LGTM!

2023-10-02 21:25 UTC, merged