(DOCSP-27838) Add authentication hooks to React Native docs
mongodb/docs-realm pull request #3037
Opened 2023-10-02 18:48 UTC by krollins-mdb

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-27838

### Staged Changes

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

### Animal Wearing a Hat

<img src="https://www.pocketpetpouch.store/cdn/shop/products/hedgehogsailorhat.jpg?v=1667878886" width=400>

2023-10-16 07:24 UTC, takameyer requested changes
Great work here, but I have some requests that should be addressed before this goes live.

2023-10-16 07:24 UTC, takameyer commented on source/sdk/react-native/manage-users/manage-email-password-users.txt
> +.. include:: /examples/generated/react-native/v12/LoginWithEmail.snippet.email-password-register.tsx.rst
Should we also get the `result` in this example?

2023-10-16 07:24 UTC, takameyer commented on source/sdk/react-native/manage-users/manage-email-password-users.txt
> +.. include:: /examples/generated/react-native/v12/LoginWithEmail.snippet.email-password-register.tsx.rst
Since `register` is not yet "awaitable", perhaps showing this flow would be helpful:
https://github.com/realm/realm-js/blob/main/examples/rn-todo-list/frontend/app/screens/LoginScreen.tsx#L50-L54

2023-10-16 07:24 UTC, takameyer commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +useAuth Hook
I do, however, think we should have an explanation about the "operation enum".  Since nothing is awaitable, it's necessary to use the operation to determine which auth method is currently being processed.  
Also it may be good to show the possible `string` values for `operation`, just in case someone has the gall to use plain JS instead of TypeScript.

2023-10-16 07:24 UTC, takameyer commented on source/sdk/react-native/manage-users/manage-email-password-users.txt
> +useEmailPasswordAuth Hook
`result` should also be added here.

2023-10-16 07:24 UTC, takameyer commented on source/sdk/react-native/manage-users/link-user-identities.txt
> +         with the app's current user. Initially, only the anonymou user
```suggestion
         with the app's current user. Initially, only the anonymous user
```

2023-10-16 07:24 UTC, takameyer commented on source/sdk/react-native/manage-users/link-user-identities.txt
> +         .. include:: /examples/generated/react-native/v12/LinkIdentities.snippet.user-identities.tsx.rst
Upon reading this example, it occurred to me that we should probably have a `linkCredentials` method returned from `useAuth`.

2023-10-16 19:35 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
>  .. _react-native-login-api-key:
I will! But this PR kept growing, so I wanted to break things up a bit. I created a small Jira epic to track the rest of the work: https://jira.mongodb.org/browse/DOCSP-27838

2023-10-16 19:35 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +useAuth Hook
Great points about the enum. I'll update!

2023-10-16 20:16 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
>  .. _react-native-login-api-key:
Part of why this is so much work is that we're currently pulling examples from the Node.js test suite. And those examples are old and weren't well put together to begin with. So, gotta write new components.

2023-10-17 13:38 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/manage-email-password-users.txt
> +.. include:: /examples/generated/react-native/v12/LoginWithEmail.snippet.email-password-register.tsx.rst
Yep. Good catch!

2023-10-17 13:42 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/link-user-identities.txt
> +         .. include:: /examples/generated/react-native/v12/LinkIdentities.snippet.user-identities.tsx.rst
That would be helpful, for sure!

2023-10-17 16:09 UTC, cbullinger approved these changes
overall LGTM -- a few typos and non-blocking suggestions

2023-10-17 17:36 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +#. Destructure ``logIn`` and ``result`` from the ``useEmailPasswordAuth`` hook.
I've been trying to avoid links in procedure steps. Probably makes sense to include a mention of `useEmailPasswordAuth` in the intro and link to it. What do you think?

2023-10-17 17:37 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
>  User Sessions
I'll experiment! I was wondering the same thing at some point, but didn't get around to it.

2023-10-17 17:39 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +``useUser()`` hook. These components only render if your app has an
Probably should be. I've been consciously trying to keep the linking down, as I tend to over link things. Might have gone too far and not linked enough.

2023-10-17 17:40 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/link-user-identities.txt
> +You can link identities with the :realm-react-sdk:`useUser hook
Good catch! There wasn't one before because the page was too small for it. With the new procedure, it probably makes sense.

2023-10-17 17:40 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/manage-email-password-users.txt
>  To learn more about configuring email/password authentication,
Because I forgot to add it here. 😆 Good spot for it, for sure!

2023-10-17 17:42 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/src/components/authentication/login/Login.tsx
> +  // // Log in an anyonmouse user on component render.
Wow. I really messed that one up. 🐁

2023-10-17 17:42 UTC, krollins-mdb commented on source/sdk/react-native/manage-users/manage-email-password-users.txt
> +You can send password reset emails to confirm users' identity. You must
Ooh, nice catch. Thank you!

2023-10-17 18:33 UTC, cbullinger commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +#. Destructure ``logIn`` and ``result`` from the ``useEmailPasswordAuth`` hook.
Yep, that makes sense! 👍

2023-10-17 18:36 UTC, cbullinger commented on source/sdk/react-native/manage-users/authenticate-users.txt
> +``useUser()`` hook. These components only render if your app has an
I think it was more that it didn't seem consistent with the API refs. But I'm also not as familiar with the SDK, so I might be assuming the need for links where there isn't any

2023-10-18 08:19 UTC, takameyer approved these changes
LGTM :shipit:

2023-10-18 08:19 UTC, takameyer commented on examples/react-native/v12/TestApp/src/components/authentication/login/LoginWithAnonymous.tsx
> +      }}
```suggestion
      onPress={logInWithAnonymous}
```

This could be simplified.

2023-10-18 14:49 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/src/components/authentication/login/LoginWithAnonymous.tsx
> +      }}
Yeah, I've been omitting the UI bits of of components for the auth stuff. Bluehawk removes everything between `:remove-start:` and `:remove-end:` so that we get samples like what's on the page: https://preview-mongodbkrollinsmdb.gatsbyjs.io/realm/DOCSP-27838/sdk/react-native/manage-users/authenticate-users/#anonymous-user

In this case, we could probably include the UI, as there's not much. But in other cases, the UI can be a lot and isn't really what we're focusing on. I think I'll keep this one as-is so it's consistent with the other examples.

I'd be happy to hear your thoughts on the balance between concise examples and "complete" examples though!

2023-10-18 14:52 UTC, takameyer commented on examples/react-native/v12/TestApp/src/components/authentication/login/LoginWithAnonymous.tsx
> +      }}
I guess this urge to comment spawned on this block:
```
  const performAnonymousLogin = () => {
    logInWithAnonymous();
  };
```

One could simply provide `logInWithAnonymous` without wrapping it in a function.

2023-10-18 14:55 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/src/components/authentication/login/LoginWithAnonymous.tsx
> +      }}
Oh. Yeah, that's a great point. ha! Thank you. I'll update other spots in the code that follow this pattern. Not sure why I got so wrapper happy.

2023-10-18 14:56 UTC, krollins-mdb commented on examples/react-native/v12/TestApp/src/components/authentication/login/LoginWithAnonymous.tsx
> +      }}
I think I initially misunderstood what you meant. Thank you for clarifying!

2023-10-19 20:42 UTC, merged