(DOCSP-28276) Add argument to `useQuery` to allow result to be filtered and sorted
mongodb/docs-realm pull request #3063
Opened 2023-10-30 19:33 UTC by krollins-mdb

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-28276

### Staged Changes

- [Code samples throughout the React Native SDK docs](https://preview-mongodbkrollinsmdb.gatsbyjs.io/realm/DOCSP-28276/sdk/react-native/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

### Animal Wearing a Hat

<img src="https://images.unsplash.com/photo-1575425187336-d5ec5d0a1451?auto=format&fit=crop&q=80&w=1000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8ZG9nJTIwaGF0fGVufDB8fDB8fHww" width=400>

2023-10-30 19:56 UTC, krollins-mdb commented
I'm not sure what the test error is. I'm going to spend time this week fixing tests and the test suite.

2023-10-31 17:30 UTC, lindseymoore requested changes
1 question!

2023-10-31 17:30 UTC, lindseymoore commented on source/examples/generated/react-native/js/dictionary-test.snippet.query-objects-with-dictionary.jsx
> +    return homeOwner.filtered('home["address"] = "Summerhill St."');
```suggestion
    return homeOwners.filtered('home["address"] = "Summerhill St."');
```
Is this supposed to be ``homeOwners``?

2023-10-31 21:29 UTC, lindseymoore approved these changes
Going to go ahead and approve since I'll be OOO. Please review previous question!

2023-11-01 14:57 UTC, krollins-mdb commented on source/examples/generated/react-native/js/dictionary-test.snippet.query-objects-with-dictionary.jsx
> +    return homeOwner.filtered('home["address"] = "Summerhill St."');
Yep! Thanks for catching that.

2023-11-01 15:12 UTC, merged