(DOCSP-34624): Device SDK Landing Page and Intro updates
mongodb/docs-realm pull request #3092
Opened 2023-11-28 20:03 UTC by dacharyc

## Pull Request Info

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34624
Staged changes:

- [Swift SDK Landing Page](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34624/sdk/swift/)
- [Why Realm?](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-34624/sdk/swift/realm-database/)

### Reminder Checklist

Before merging your PR, make sure to check a few things.

- [ ] Describe your PR's changes in the Release Notes section
- [ ] Create a Jira ticket for corresponding docs-realm docs-app-services, if any

### Release Notes

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-11-29 14:08 UTC, cbullinger commented on source/index.txt
> +Welcome to the Device SDK Docs
should this be "Atlas Device SDK Docs"?

2023-11-29 14:08 UTC, cbullinger commented on source/index.txt
> +   :description: Device SDK is an offline-first, cloud-syncable database for mobile, web, desktop, and IoT apps.
IDK if we're following it exactly, but per that renaming doc:
[after the first formal reference] feel free to refer to them as “the SDKs” or “the SDK” 
```suggestion
   :description: The SDKs are an offline-first, cloud-syncable database for mobile, web, desktop, and IoT apps.
```

2023-11-29 20:58 UTC, krollins-mdb commented on source/index.txt
> +Welcome to the Device SDK Docs
Not having "Atlas Device SDK" in top-level titles and headings feels odd. If that's the product name and what people will see in Atlas, they could get confused by seeing the more generic "Device SDK".

2023-11-29 21:00 UTC, krollins-mdb commented on source/index.txt
> +   :description: Device SDK is an offline-first, cloud-syncable database for mobile, web, desktop, and IoT apps.
I think the "full name, then 'SDK' or 'SDKs'" construction could work well. The repetition of "Device SDK" everywhere feels odd. (though at least it improves the realm/Realm thing a bit. Maybe.)

Shortening subsequent references to just "SDK" would be wonderful.

2023-11-29 21:46 UTC, krollins-mdb reviewed
I don't know why I started a review. Habit, I suppose. 😆 

My comments are merely suggestions and explorations. I didn't want to go too far down this road until we've had a chance to discuss more.

Thank you for working on this difficult refactor! It's hard to reconcile all the concerns and naming conventions.

2023-11-29 21:46 UTC, krollins-mdb commented on source/index.txt
> +   Use Device SDK to build mobile, web, desktop, and IoT apps.
This first sentence is doing a lot of work. Can we simplify?

```suggestion
   Device SDK is a suite of app development tools with a core
   mobile-first database. Use Device SDK to build modern
   and data-driven mobile, web, desktop, and IoT apps.
```

2023-11-29 21:46 UTC, krollins-mdb commented on source/index.txt
> +   Use Device SDK to build mobile, web, desktop, and IoT apps.
Alternatively, viewing this from an Atlas-first perspective, maybe something like this is better? Also, you can't really build an app with the SDK. Rather, you integrate it with an app so that you can work with data that lives in Atlas, right?

```suggestion
   Device SDK is a suite of app development tools that
   translate Atlas data to an on-device, mobile-first database. 
   Use Device SDK to integrate Atlas data with, web, desktop,
   and IoT apps.
```

2023-11-29 21:46 UTC, krollins-mdb commented on source/index.txt
> +database that lets you build real-time, always-on applications.
An Atlas-first suggestion:

```suggestion
Device SDK provides tools to access and persist Atlas data on many kinds
of devices. The device persistence layer is called Realm, an embedded,
object-oriented database for real-time always-on applications. Realm works
with Device Sync to keep all devices updated.

You can also access your Atlas data from a device in other ways, like 
using the MongoDB GraphQL API or Atlas Functions.
```

2023-11-30 15:16 UTC, cbullinger commented on source/index.txt
> +   :description: Device SDK is an offline-first, cloud-syncable database for mobile, web, desktop, and IoT apps.
might be just me, but the singular "Device SDK is ... " without a definite article also feels odd

2023-11-30 20:22 UTC, lindseymoore commented on source/index.txt
> +   :description: Device SDK is an offline-first, cloud-syncable database for mobile, web, desktop, and IoT apps.
Probably best to include the full name (Atlas Device SDK) for the meta description.

2023-12-01 16:49 UTC, dacharyc commented on source/index.txt
> +   :description: Device SDK is an offline-first, cloud-syncable database for mobile, web, desktop, and IoT apps.
I'm adjusting the naming per our discussion yesterday. But FWIW, the meta:description should always include the full name, because that's what shows up in Google search results. We shouldn't use the short version there. It doesn't actually show up on the page.

We can use the SDK short name after the first "visible" full product name on the page (after the title). I'll share the formalized doc from our convo yesterday after I apply the changes to this PR and make sure I'm clear on everything.

2023-12-01 17:38 UTC, dacharyc commented on source/index.txt
> +   Use Device SDK to build mobile, web, desktop, and IoT apps.
Went with a compromise between these two things and something slightly different based on our convo yesterday. Curious for your thoughts!

2023-12-01 17:39 UTC, dacharyc commented on source/index.txt
> +database that lets you build real-time, always-on applications.
I tweaked this a little based on our convo yesterday, and more thinking about it this AM. What do you think of the changes I made?

2023-12-04 19:56 UTC, lindseymoore commented on source/sdk/swift/install.txt
> +Atlas Device SDK for Swift SDK enables you to build iOS, macOS, tvOS,
```suggestion
Atlas Device SDK for Swift enables you to build iOS, macOS, tvOS,
```

2023-12-04 19:59 UTC, lindseymoore approved these changes
LGTM to show! This is more a question for marketing perhaps, but I think using ' the SDK' is so generic. When we say 'the SDK', there is nothing specific to MongoDB. What if instead, we used 'Atlas Device' as the shortened product name?

2023-12-04 19:59 UTC, lindseymoore commented on source/sdk/swift/install.txt
> +Atlas Device SDK for Swift SDK enables you to build iOS, macOS, tvOS,
```suggestion
Atlas Device SDK for Swift enables you to build iOS, macOS, tvOS,
```

2023-12-04 21:50 UTC, krollins-mdb requested changes
@dacharyc, thank you for putting our naming conventions into practice! I think you've done a great job navigating the complex pieces.

I have a number of small suggestions and I identified some spots where I don't think we're consistent with the naming.

But overall, this is really great.

2023-12-04 21:50 UTC, krollins-mdb commented on source/introduction.txt
This page is _so_ much better now. Excellent work, @dacharyc. 🎉

2023-12-04 21:50 UTC, krollins-mdb commented on source/introduction.txt
> +Mobile and edge developers face a number of unique challenges. You must:
[minor] I think we could drop "You must:", which assumes the person reading this is a mobile or edge developer. Probably true, but possibly not.
```suggestion
Mobile and edge developers face a number of unique challenges.
```

2023-12-04 21:50 UTC, krollins-mdb commented on source/introduction.txt
> +  the latest data stored in the database. You can
Are we concerned about "object store" vs "database"? I can't remember if we decided anything about that.

2023-12-04 21:50 UTC, krollins-mdb commented on source/sdk/swift.txt
> +Get Started with Device SDK for Swift
I think we should go with the short name here:
```suggestion
Get Started with the Swift SDK
```

2023-12-04 21:50 UTC, krollins-mdb commented on source/sdk/swift/install.txt
> +.. tip:: Device SDK and Realm
```suggestion
.. tip:: Atlas Device SDK and Realm
```

2023-12-04 21:50 UTC, krollins-mdb commented on source/sdk/swift/install.txt
> +.. tip:: Device SDK and Realm
```suggestion
.. tip:: Atlas Device SDK and Realm
```

2023-12-04 21:50 UTC, krollins-mdb commented on source/sdk/swift/react-to-changes.txt
> +Device SDK for Swift offers SwiftUI property wrappers to make it easy to
```suggestion
Atlas Device SDK for Swift offers SwiftUI property wrappers to make it easy to
```

2023-12-04 21:50 UTC, krollins-mdb commented on source/sdk/swift.txt
> +         :alt: Device SDK Mobile Illustration
```suggestion
         :alt: Atlas Device SDK Mobile Illustration
```

2023-12-04 21:50 UTC, krollins-mdb commented on source/sdk/swift.txt
> +         :alt: Device SDK Mobile Illustration
```suggestion
         :alt: Atlas Device SDK Mobile Illustration
```

2023-12-04 22:51 UTC, dacharyc reviewed
I've got a few Qs for you, @krollins-mdb , about some things that may need additional clarification!

2023-12-04 22:51 UTC, dacharyc commented on source/index.txt
> +   build data-driven mobile, edge, web, desktop, and IoT apps.
Optimizing for devices (mobile, specifically) was the driving force behind the Realm product development. A lot of the criteria that went into developing Realm was specific to mobile development - i.e. fast, lightweight, embedded, object-based, supports low power consumption, etc. Persistence is the purpose that it serves, but the optimization was for device.

Do you think I need to be more verbose here to clarify that detail?

2023-12-04 22:51 UTC, dacharyc commented on source/index.txt
> +The SDKs provide tools to read and write Atlas data from device. Your app
I am happy to incorporate these suggestions, but I wonder if we need to align as a team around the use of singular/plural device/devices and whether we need an article before "device." My choices here weren't overlooked grammar issues - they were intentional. I think these changes could get pretty inconsistent if we're not all on the same page as we incorporate the new naming.

2023-12-04 22:51 UTC, dacharyc commented on source/index.txt
> +The SDKs support most popular languages, frameworks, and platforms. Each
I see what you're going for, but I don't love the passive "There are..."

What do you think about:

> The SDK provides packages for most popular...

Or even just:

> We provide SDKs for most popular...

2023-12-04 22:51 UTC, dacharyc commented on source/sdk/swift.txt
> +         :alt: Device SDK Mobile Illustration
Should we add something to our naming doc about using the full name in alt text?

2023-12-04 22:51 UTC, dacharyc commented on source/sdk/swift/install.txt
> +Atlas Device SDK for Swift SDK enables you to build iOS, macOS, tvOS,
Ack, I thought I caught all these but of course I missed one. Thank you for catching this!

2023-12-04 22:51 UTC, dacharyc commented on source/sdk/swift/install.txt
> +.. tip:: Device SDK and Realm
Curious for your reasoning to use the full name in the tip text here. It's got the full name in ln 16 above, so I treated this as a "subsequent mention" where we could omit the "Atlas." Is there some additional nuance we should clarify in our naming doc for here and in the other tip down below?

2023-12-12 14:32 UTC, krollins-mdb approved these changes
Thank you for all the hard work on this, Dachary!

2023-12-12 22:00 UTC, lindseymoore commented on source/web/api-reference.txt
> +.. tip:: Atlas Device SDK and Realm
Will we remove a tip like this eventually? Seems like information the reader doesn't always need a call out for. Fine for now since the change is new though.

2023-12-12 22:44 UTC, dacharyc commented on source/sdk/flutter/install.txt
> +   The Flutter SDK and Dart Standalone SDK are not compatible with
I'm not sure, either! But it looks like all of the other references to it in our docs use lowercase "standalone", so I'll change this instance.

2023-12-12 22:50 UTC, dacharyc commented on source/sdk/flutter/realm-database/realm-files.txt
> +  actively in use. This prevents realm from reclaiming storage space
It looks like this comment and many others are on sections that I'm just moving from the deleted intro pages, and am intentionally not editing. I think those edits are out of scope of this PR's changes. 

In this PR, I'm only trying to update the naming and references on the landing pages and install pages. 

This piece of content, and many of the other moved pieces of content, are just a side effect of removing the deleted pages and needing somewhere relevant to put the content. I think we should address updating the moved content as part of whatever effort we make to address naming/concepts on the pages where the content has moved. (i.e. if I were trying to address naming/concepts on _all_ of the pages where I moved content, that would be full edits of ~60ish pages in one PR and that would be way too massive. So I think we should make separate efforts to address the naming/concepts on these other pages as a broader part of the renaming project.)

2023-12-12 22:52 UTC, dacharyc commented on source/sdk/swift.txt
> +-------------------------------------
I think it's from when I was using "Device" in the name - looks like I forgot to update the underlines when I removed the "Device". Good catch - thanks!

2023-12-12 22:52 UTC, dacharyc commented on source/sdk/swift.txt
> +         For example View code that demonstrates common SwiftUI
This is specifically about example View code in SwiftUI, so it's correct as written.

2023-12-12 22:58 UTC, dacharyc commented on source/web/api-reference.txt
> +.. tip:: Atlas Device SDK and Realm
At the moment, I think it's called for because we're trying to make clear why we're still using "Realm" in a lot of places even though there's a banner at the top of the docs that says "Realm is now Atlas Device SDK." I think eventually, when we separate the packages, all of these references in particular will no longer be in a Realm namespace and we can safely remove this tip. There is a plan to put a lot of the App Services APIs in a separate package which will have a different name, so people can use them without having to use Realm, and then we can probably remove a lot of these tips.

2023-12-12 23:05 UTC, merged