DOCSP-35056 Dart upgrade dependencies
mongodb/docs-realm pull request #3114
Opened 2023-12-15 21:47 UTC by lindseymoore

## Pull Request Info

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35056

### Release Notes

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2023-12-15 22:03 UTC, lindseymoore commented on examples/dart/test_sdk_example/pubspec.lock
Should I add back this deleted file?

2023-12-15 23:03 UTC, dacharyc requested changes
It looks like there are a couple of things added here that we should remove - a few generated files, but more importantly, the `flutter` git submodule. After those changes, this should be good to go!

2023-12-15 23:03 UTC, dacharyc commented on examples/dart/test_sdk_example/pubspec.lock
Generally speaking, I would expect changes to this file if we do the load dependency command _inside_ this directory. But I know we had some challenges while we were on the call dealing with multiple pubspec.yaml files. It's probably not super important for this PR. We can always regenerate it in the future when we're working in this directory.

2023-12-18 13:59 UTC, dacharyc approved these changes
LGTM! Thanks for taking care of this, Lindsey!

2023-12-18 14:53 UTC, merged