DOCSP-33414 Add section on FTS to RQL reference
mongodb/docs-realm pull request #3188
Opened 2024-02-28 20:50 UTC by lindseymoore

## Pull Request Info

Jira ticket: https://jira.mongodb.org/browse/DOCSP-33414

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/): description of changes

### Reminder Checklist

Before merging your PR, make sure to check a few things.

- [ ] Did you tag pages appropriately?
  - genre
  - meta.keywords
  - meta.description
- [ ] Describe your PR's changes in the Release Notes section
- [ ] Create a Jira ticket for related docs-app-services work, if any

### Release Notes

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2024-02-29 01:24 UTC, cbullinger requested changes
Some corrections needed

2024-02-29 01:24 UTC, cbullinger commented on examples/node/v12/__tests__/realm-query-language.test.js
> +    expect(itemsWithWrite.length).toBeGreaterThan(0);
do we want to make these actual values more specific to ensure the search syntax is working?

2024-02-29 01:24 UTC, cbullinger commented on examples/dart/test/task_project_models_test.dart
> +  @Indexed(RealmIndexType.fullText)
doesn't this model need to be re-generated with the change?

2024-03-01 03:02 UTC, lindseymoore commented on source/realm-query-language.txt
> +3. Query using the ``geoWithin`` RQL operator.
According to this design doc, seems to be camel case? https://docs.google.com/document/d/1Z7CK79CqebEtVllVHTNEq8neKhoMWeFCDjKBrn_pq1Y/edit#heading=h.2s9zdv6a57gn
I'll update

2024-03-01 03:16 UTC, lindseymoore commented on source/realm-query-language.txt
> +- :ref:`Flutter SDK <flutter-fts-annotation>`
Not sure it's necessary, this page doesn't include any information that those pages won't have. Is it more to promote this page?

2024-03-01 16:35 UTC, cbullinger approved these changes
a few suggestions, but lgtm! Also, should we plan to eventually get all of the RQL examples in the new v12 file(s)?

2024-03-01 16:35 UTC, cbullinger commented on source/realm-query-language.txt
>  - :ref:`Kotlin SDK <kotlin-geospatial>`
I updated the Read page with info on querying geo data. it's probably a more appropriate link here ... but I'm realizing that I didn't add a ref anchor to the section so nm 🤷

2024-03-01 18:17 UTC, lindseymoore commented on source/realm-query-language.txt
> +- Tokens can only consist of characters from ASCII and the Latin-1 supplement (western languages).
Missed this one, thanks!

2024-03-01 18:56 UTC, lindseymoore commented on source/realm-query-language.txt
> +3. Query using the ``geoWithin`` RQL operator.
Created!: https://jira.mongodb.org/browse/DOCSP-37318

2024-03-01 22:36 UTC, merged