DOCSP-35364: Flutter SDK - Nested Collections of Mixed Data
mongodb/docs-realm pull request #3201
Opened 2024-03-15 14:57 UTC by cbullinger

## Pull Request Info

> **NOTE:** This PR is temporarily using an alpha snapshot - unit tests will fail. Upgrading to v2.0.0 release, once it's available, may impact some of the code examples.

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35364

- [Define an Object Schema](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-35364-dart-collections-mixed/sdk/flutter/realm-database/model-data/define-realm-object-schema/#model-unstructured-data): Added new "Modeled Unstructured Data" section with example
- [Data Types](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-35364-dart-collections-mixed/sdk/flutter/realm-database/model-data/data-types/#realmvalue): Updated ``RealmValue`` mixed data type section with new info and examples for collections in mixed; added note re. breaking change (**links to migration page from a separate PR**)
- [Read](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-35364-dart-collections-mixed/sdk/flutter/crud/read/#query-nested-collections-of-mixed-data): Add new Query Nested Collections of Mixed Data (**needs query examples added as part of RQL ticket**)

### Reminder Checklist

Before merging your PR, make sure to check a few things.

- [ ] Did you tag pages appropriately?
  - genre
  - meta.keywords
  - meta.description
- [ ] Describe your PR's changes in the Release Notes section
- [ ] Create a Jira ticket for related docs-app-services work, if any

### Release Notes

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2024-03-15 20:58 UTC, nirinchev reviewed
I haven't gone through the whole thing yet since it's quite late, but I'll get to it on Monday! I think the structure is sound, but we could come up with better examples. There are a few inaccuracies as well that I've highlighted.

2024-03-15 20:58 UTC, nirinchev commented on source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
> +:ref:`RealmMap <flutter-realm-map>` of ``RealmValue`` type:
I know what this means, but to a new user reading this, it may seem they need to somehow clarify that the RealmValue property contains a map or list.

2024-03-15 20:58 UTC, nirinchev commented on source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
> +- ``RealmValue<RealmMap<String, RealmValue>>``
This is not valid dart. The field type is a `RealmValue` with no generic arguments - it can implicitly contain a primitive or a collection with no extra definition required.

2024-03-15 20:58 UTC, nirinchev commented on source/examples/generated/flutter/define_realm_model_test.snippet.create-unstructured-data-example.dart
> +      EventLog(ObjectId(), 'purchase', DateTime.now(), 'user123', details: {
I think we need to show the schema of the `EventLog` somewhere.

Also, if `details` is a RealmValue, you can probably move the `RealmValue.from` to the top level rather than have it in multiple places in the structure:

```dart
details: RealmValue.from({
  'ipAddress': '192.168.1.1',
  items: [ ... ]
}),
```

2024-03-15 20:58 UTC, nirinchev commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +   - ``RealmValue.type`` is now an enum of ``RealmValueType`` instead of ``Type``, and ``RealmValue.value.runtimeType`` is added.
`RealmValue.value.runtimeType` is not technically added. `Object.runtimeType` comes from the framework (i.e. it's built in for all dart objects). It's just that previously `type` was just a shorthand for `value.runtimeType` and now users can just access it themselves.

2024-03-15 20:58 UTC, nirinchev commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +   These changes require a migration for existing apps.
I think this may be a little extraneous information and also has the possibility to throw people off. Migration is typically associated with data migrations and might imply that you'd be forced to execute some migration on your database, when in reality, one needs to just update some code. We should also qualify the statement with "may" since there are probably many apps that don't use `RealmValue` at all and even the ones that do may not have used the `.type` property.

2024-03-15 20:58 UTC, nirinchev commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +data type. In Flutter SDK v2.0.0 and later, ``RealmValue`` can represent a List or Map collection (but *not* a Set) of mixed type.
```suggestion
data type. In Flutter SDK v2.0.0 and later, ``RealmValue`` can represent a ``List<RealmValue>`` or ``Map<String, RealmValue>``. 
```

2024-03-15 20:58 UTC, nirinchev commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +data type is a mixed data type that can represent any other valid Realm
It cannot represent embedded objects.

2024-03-15 20:58 UTC, nirinchev commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +``RealmValue.type``.
I think this paragraph is confusing. I would suggest rewording it to something along the lines of:

> To obtain the data stored in a `RealmValue`, you can use `RealmValue.value` which returns an `Object?` or `RealmValue.as<T>` to fetch the data and cast it to a desired type. You can check the type of the data stored in a `RealmValue` by accessing the `type` property. Starting with Realm Flutter v2.0.0, that will return a `RealmValueType` enum value, while in earlier versions it would return `RealmValue.value.runtimeType`.

2024-03-15 20:58 UTC, nirinchev commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +.. _flutter-nested-collections-realm-value:
I don't think we should show this - it's generally a bad practice and we only added it in the past to have something. Accessing the runtimeType has always been available, but instead of doing that, you'd probably want to use an expression:

```dart
final value = mixedValue.value;
if (value is int) {
  sum = sum + value;
} else if (value is String) {
  final subValue = value.substring(5, 8);
}
```

2024-03-15 20:58 UTC, nirinchev commented on source/examples/generated/flutter/data_types_test.snippet.realm-value-type-value.dart
> +      break;
This is not super helpful as `obj.singleAnyValue.value` is of type `Object?` and unless you're stringifying it, you can't use it for anything meaningful without casting. We could instead showcase the `.as<T>` helper method and show some use case that is using the actual type - e.g.:

```dart
final anyValue = obj.singleAnyValue;
switch (anyValue.type) {
  case RealmValueType.int:
    // we stored birth year
    approximateAge = DateTime.now().year - anyValue.as<int>();
    break;
  case RealmValueType.date:
    // We stored the birthday
    approximateAge = (DateTime.now().difference(anyValue.as<DateTime>()).inDays / 365).floor();
    break;
  case RealmValueType.string:
    // We stored the birthday as a string
    final birthday = DateTime.parse(anyValue.as<String>());
    approximateAge = (DateTime.now().difference(birthday).inDays / 365).floor();
    break;
}
```

2024-03-15 20:58 UTC, nirinchev commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +- ``RealmValue<RealmMap<String, RealmValue>>``
These declarations are incorrect - it's just a `RealmValue`.

2024-03-15 20:58 UTC, nirinchev commented on source/examples/generated/flutter/data_types_test.snippet.realm-value-nested-collections.dart
> +final listOfAnyValue = RealmValue.from([singleAnyValue]);
I think it's a little unclear what `singleAnyValue` is here and below.

2024-03-15 20:58 UTC, nirinchev commented on source/examples/generated/flutter/data_types_test.snippet.realm-value-nested-collections.dart
> +  var collectionsOfMixed = realm.add(RealmValueExample(
Do we need the assignment here?

2024-03-15 20:58 UTC, nirinchev commented on source/examples/generated/flutter/data_types_test.snippet.realm-value-nested-collections.dart
> +      mapOfMixedAnyValues: {'key': singleAnyValue}));
I think these are kind of confusing - `singleAnyValue` or `listOfMixedAnyValues` are somewhat convoluted names and not really relatable to a real-world example.

2024-03-15 20:58 UTC, nirinchev commented on source/examples/generated/flutter/data_types_test.snippet.realm-value-nested-collections.dart
> +          ]),
I think it'd be nicer if we could show a complex data structure inline rather than referring objects we defined above. Seeing a json-like data structure is a lot easier than to reason about what's going on where, especially with all the `RealmValue.from`-s being scattered around.

2024-03-18 10:37 UTC, cbullinger commented on source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
> +:ref:`RealmMap <flutter-realm-map>` of ``RealmValue`` type:
Updated for clarity

2024-03-18 10:37 UTC, cbullinger commented on source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
> +- ``RealmValue<RealmMap<String, RealmValue>>``
Updated here and in the Data Types page

2024-03-18 11:53 UTC, cbullinger commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +.. _flutter-nested-collections-realm-value:
Replaced this with example of accessing the type with an expression

2024-03-18 11:54 UTC, cbullinger commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +``RealmValue.type``.
Updated this and the example to demonstrate both methods of accessing data

2024-03-18 11:55 UTC, cbullinger commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +- ``RealmValue<RealmMap<String, RealmValue>>``
Updated here and in Define Schema page

2024-03-18 12:01 UTC, cbullinger commented on source/examples/generated/flutter/data_types_test.snippet.realm-value-nested-collections.dart
> +final listOfAnyValue = RealmValue.from([singleAnyValue]);
let's sync up on a better example to address this and the following comments

2024-03-18 12:08 UTC, cbullinger commented on source/examples/generated/flutter/data_types_test.snippet.realm-value-type-value.dart
> +      break;
Updated

2024-03-19 21:29 UTC, lindseymoore requested changes
Overall, content looks good! A few smaller suggestions and fixes. 
For code snippets, I would like to see introduction comments to explain what the code is doing. Sometimes you explain what the code is doing in the text, sometimes not. I think an introduction comment is helpful whether the code is explained in text or not, given the code is copyable.

2024-03-19 21:29 UTC, lindseymoore commented on source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
> +performant than using a structured schema or serializing JSON blobs
```suggestion
in the nested data and to update specific elements. However in some cases, it is less 
performant than using a structured schema or serializing JSON blobs.
```
Why it is less performant? Maybe give some reasons or cases where it would be less performant.

2024-03-19 21:29 UTC, lindseymoore commented on source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
> +
```suggestion
    :copyable: true
```
Did a quick search, adding this should make the code snippet copyable!

2024-03-20 20:01 UTC, cbullinger commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +   version to v2.0.0 or later, refer to :ref:`flutter-upgrade-v2`.
not yet, the page is part of another PR. i've commented these last lines out for now, and will re-add it once the page is available

2024-03-20 20:04 UTC, cbullinger commented on source/sdk/flutter/crud/read.txt
> +same way you would a normal collection. You can also use bracket notation to query a specific element in the collection (for example, ``[FIRST]``, ``[1]``, ``[LAST]``, or ``[*]``).
Was going to rely on the RQL docs to provide the bulk of this, but I will update these with more information since the RQL content isn't ready yet

2024-03-20 20:05 UTC, cbullinger commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +.. versionchanged:: 2.0.0
i think it's just how the description portion of the versionchanged direction is formatted, unfortunately...

2024-03-20 20:09 UTC, cbullinger commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +.. literalinclude:: /examples/generated/flutter/data_types_test.snippet.realm-value-type.dart
Updated snippet and highlighting

2024-03-20 21:20 UTC, cbullinger commented on source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
> +performant than using a structured schema or serializing JSON blobs
I've noted this for a fast follow addition. I'll need to get more info from engineering for the additional details

2024-03-20 21:56 UTC, lindseymoore approved these changes
Some typos and more stuff about comments, add at your discretion. Otherwise, LGTM!

2024-03-20 21:56 UTC, lindseymoore commented on source/sdk/flutter/crud/read.txt
> +- Bracket notation, which provides additional collection query support:
Not sure why it's bolded in the staging link, but remove bolding if possible.

2024-03-20 21:56 UTC, lindseymoore commented on source/sdk/flutter/crud/read.txt
> +- The ``@type`` operator, which has the following possible values:
Remove bolding here too.

2024-03-20 21:56 UTC, lindseymoore commented on source/sdk/flutter/crud/read.txt
> +    - ``[FIRST]`` and [``LAST``] - match the first or last elements within the collection
```suggestion
    - ``[FIRST]`` and [``LAST``] : match the first or last elements within the collection
```
Nit: The hyphens for the few following lines should be colons according to the style guide: https://www.mongodb.com/docs/meta/style-guide/style/punctuation/#colons

2024-03-20 21:56 UTC, lindseymoore commented on source/sdk/flutter/crud/read.txt
> +  - ``[FIRST]`` and [``LAST``] - match the first or last elements within the collection
```suggestion
  - ``[FIRST]`` and [``LAST``]: match the first or last elements within the collection
```
Nit: This should be a colon according to style guide: https://www.mongodb.com/docs/meta/style-guide/style/punctuation/#colons

2024-03-20 21:56 UTC, lindseymoore commented on source/sdk/flutter/crud/read.txt
> +.. literalinclude:: /examples/generated/flutter/read_write_data_test.snippet.filter-nested-collections.dart
Would be nice to add a comment introducing the object models since the relevant information to the section starts so far down.

2024-03-20 21:56 UTC, lindseymoore commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +To define a property as ``RealmValue``, set its type in your object model.
```suggestion
To define a ``RealmValue`` property , set its type in your object model. 
```

2024-03-20 21:56 UTC, lindseymoore commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +.. literalinclude:: /examples/generated/flutter/data_types_test.snippet.realm-value-from.dart
Suggestion: I think for readability, comments above each of the examples would be more helpful than having to read the camel case name to know what the example is for. A simple format like``// To add a single value`` would be helpful

2024-03-20 21:56 UTC, lindseymoore commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +``RealmValue.value.runtimeType``.
```suggestion
``RealmValue.value.runtimeType``. The following example uses RealmValueType to run calculations based on the data type.
```
Could intro example with something like that^

2024-03-20 21:56 UTC, lindseymoore commented on source/sdk/flutter/realm-database/model-data/define-realm-object-schema.txt
> +.. literalinclude:: /examples/generated/flutter/define_realm_model_test.snippet.unstructured-data-model.dart
Could add comment at the top.

2024-03-20 22:54 UTC, cbullinger commented on source/sdk/flutter/crud/read.txt
> +    - ``[FIRST]`` and [``LAST``] - match the first or last elements within the collection
good catch. thanks!

2024-03-21 11:54 UTC, cbullinger commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +Then, you can create the list or map collections using ``RealmValue.from()``.
Added link

2024-03-21 11:58 UTC, cbullinger commented on source/sdk/flutter/crud/read.txt
> +- Bracket notation, which provides additional collection query support:
It's a snooty thing based on the indentation and spacing. I can never remember the formatting for a regular sub-list 😒 but it's fixed now. Thanks for catching.

2024-03-21 11:58 UTC, cbullinger commented on source/sdk/flutter/crud/read.txt
> +- The ``@type`` operator, which has the following possible values:
fixed

2024-03-21 12:04 UTC, cbullinger commented on source/sdk/flutter/crud/read.txt
> +.. literalinclude:: /examples/generated/flutter/read_write_data_test.snippet.filter-nested-collections.dart
Added. Good call.

2024-03-21 12:04 UTC, cbullinger commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +To define a property as ``RealmValue``, set its type in your object model.
😅 thanks for catching

2024-03-21 12:48 UTC, cbullinger commented on source/sdk/flutter/realm-database/model-data/data-types.txt
> +``RealmValue.value.runtimeType``.
added

2024-03-21 15:09 UTC, merged