DOCSP-29928 Serialization for Dart
mongodb/docs-realm pull request #3235
Opened 2024-04-26 23:44 UTC by lindseymoore

## Pull Request Info

Jira ticket: https://jira.mongodb.org/browse/DOCSP-NNNNN

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/): description of changes

### Reminder Checklist

Before merging your PR, make sure to check a few things.

- [ ] Did you tag pages appropriately?
  - genre
  - meta.keywords
  - meta.description
- [ ] Describe your PR's changes in the Release Notes section
- [ ] Create a Jira ticket for related docs-app-services work, if any

### Release Notes

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2024-05-21 15:22 UTC, nielsenko reviewed
I have added a few comments.

I also noticed that the syntax highlighting is missing a few places.

My biggest question is; if we want to show how to serialize non-realm objects? I guess we can wait with that until later, perhaps when the _new_ mongo db client (or what it ends up being named lands).

2024-05-21 15:22 UTC, nielsenko commented on examples/dart/test/serialization_test.dart
> +    Pet deserializeFromEjson = fromEJson<Pet>(serializeByParam);
```suggestion
    final deserializeFromEjson = fromEJson<Pet>(serializeByParam);
```
or
```suggestion
    Pet deserializeFromEjson = fromEJson(serializeByParam);
```
The last is shorter, but perhaps a little less obvious. The point is that the type can be inferred.

BTW; something is off with the syntax highlighting.

2024-05-21 15:22 UTC, nielsenko commented on source/sdk/flutter/realm-database/serialization.txt
> +
Should we mention the types we don't support? (yet?), like `Code`, `CodeWScope`, `DBPointer`, `DBRef`, `Regular Expression`, and `Timestamp`(which is nothing like you would expect).

Not sure myself. What does other SDKs do?

2024-05-21 15:22 UTC, nielsenko commented on source/sdk/flutter/realm-database/serialization.txt
> +    }
```suggestion
    {
      type: Jumping Spider, 
      numberOfLegs: {$numberInt: 8}, 
      birthDate: {$date: {$numberLong: 1712707200000}}, 
      price: null
    }
```
Should we indent a bit?

2024-05-21 21:21 UTC, lindseymoore commented on examples/dart/test/serialization_test.dart
> +    Pet deserializeFromEjson = fromEJson<Pet>(serializeByParam);
I went with the second for simpliity if there is no preference.

2024-05-21 21:26 UTC, lindseymoore commented on source/sdk/flutter/realm-database/serialization.txt
> +
I think it would be helpful to include!

2024-05-21 21:32 UTC, lindseymoore commented
Thanks @nielsenko! Let me know if there is anything else. Will look into why the syntax highlighting is off. 

For serializing non-realm objects, I linked to this page on [BSON Data Types and Representation](https://www.mongodb.com/docs/manual/reference/mongodb-extended-json/#bson-data-types-and-associated-representations) in the "Supported Data Types" section of the page.

2024-05-22 13:11 UTC, cbullinger requested changes
Back to you with some questions and comments. And let's clean up and refactor the tests for idempotency

2024-05-23 22:37 UTC, lindseymoore commented on examples/dart/test/serialization_test.dart
> +}
Put the Pet model it in a different file for the snippet. I only want to show the part declaration and the import for realm dart. I get an error when I try to include the ``part 'pet.realm.dart';`` declaration in this file. Any guidance on making the object model snippet friendly in the file if I shouldn't define the model twice?

2024-05-24 22:51 UTC, lindseymoore commented on examples/dart/test/serialization_test.dart
> +
Any suggestions on using the clean up function?

2024-05-24 22:58 UTC, lindseymoore commented on examples/dart/test/serialization_test.dart
> +  print(serializeWithCall);
Think it's helpful to see the output when the test is run! But did remove the unnecessary ones.

2024-05-28 22:24 UTC, lindseymoore commented on source/sdk/flutter/realm-database/serialization.txt
> +The following data types can be serialized and deserialized:
Undefined is a created class that serializes to `{'\$undefined': 1}`. Perhaps I can include the serialization as a note?
RealmValue is supported. Added to the list.

2024-05-30 05:20 UTC, lindseymoore commented on examples/dart/test/serialization_test.dart
> +
Called at the end of main since I dont change the realm in the individual tests.

2024-05-30 17:15 UTC, lindseymoore commented on source/sdk/flutter/realm-database/serialization.txt
> +The Atlas Device SDK for Flutter supports serialization and deserialization of
Added information about the @ejson annotation and mention of the API ref for register based on input from Kasper.

2024-06-04 00:48 UTC, cbullinger approved these changes
Some suggestions but overall I think this looks good

2024-06-04 00:48 UTC, cbullinger commented on source/sdk/flutter/realm-database/serialization.txt
> +- Decimal128
```suggestion
- Document
- Decimal128
```
Document is listed as a supported enum value

2024-06-04 00:48 UTC, cbullinger commented on source/sdk/flutter/realm-database/serialization.txt
> +- :ref:`RealmValue <flutter-realm-value>`
```suggestion
```
I know I was the one to ask about this (and I might be confusing myself at this point), but I think we're only listing the BSON types here, not the Realm-specific types

2024-06-04 00:48 UTC, cbullinger commented on source/sdk/flutter/realm-database/serialization.txt
> +can be serialized and deserialized:
```suggestion
The Flutter SDK supports serializing the following data types:
```
(sorry again; I know I'm the one to mention the enum values link, but I'm not sure how helpful it actually is 🙈 )

2024-06-04 00:48 UTC, cbullinger commented on examples/dart/test/serialization_test.dart
> +main() {
we should tweak these for idempotency (i.e. so the tests can run independently). can we have the setup run before each test, and the teardown after each?

2024-06-06 09:03 UTC, nielsenko reviewed
LGTM. I have a few suggestions, but feel free to disregard them if you don't agree.

2024-06-06 09:03 UTC, nielsenko commented on examples/dart/test/serialization_test.dart
> +    Pet deserializeFromEjson = fromEJson(serializeByParam);
```suggestion
    final deserializeFromEjsonWithExplicitType = fromEJson<Pet>(serializeByParam);
    // or the shorter from where type is inferred ..
    Pet deserializeFromEjson = fromEJson(serializeByParam);
```
I know I suggested and prefer the latter form, but perhaps it is good to draw attention to the fact that `fromEjson<T>` is a generic function 🤔

2024-06-06 11:57 UTC, cbullinger commented on source/sdk/flutter/realm-database/serialization.txt
> +- Undefined
Agreed. Can we make this a table, @lindseymoore? Alternately, we could make it a table of:  
`Dart/Realm type | Serialized type | Example output`

2024-06-26 13:25 UTC, cbullinger requested changes
Formatting and content suggestions. We also need to make sure the other affected Flutter pages are updated with this new method (e.g. [Call an Atlas Function](https://www.mongodb.com/docs/atlas/device-sdks/sdk/flutter/app-services/call-function/#call-a-function:~:text=To%20include%20objects,native%20Dart%20object.))

2024-06-26 13:25 UTC, cbullinger commented on source/sdk/flutter/realm-database/serialization.txt
> +   * - Realm Data Type
these aren't technically all Realm Data Types; they're Dart + Realm-specific types. It might make sense to only include the realm-specific ones since the Dart types serialize to their ejson counterparts (bool > bool, string > string)

2024-06-26 13:25 UTC, cbullinger commented on source/sdk/flutter/realm-database/serialization.txt
> +Serialization allows for easier integration with MongoDB APIs.
```suggestion
The Flutter SDK can use this full-document EJSON encoding to communicate 
directly with MongoDB Atlas, such as through the following APIs:

- App Services :ref:`Function calls <flutter-call-function>`
- Credentials with :ref:`custom function authentication <flutter-login-custom-function>`
- User profile and :ref:`custom user data <flutter-custom-user-data>`
```
You'll also need to check these linked pages and make sure there aren't any doc impacts (e.g. the Call a Function page [instructions](https://www.mongodb.com/docs/atlas/device-sdks/sdk/flutter/app-services/call-function/#call-a-function:~:text=To%20include%20objects,native%20Dart%20object.) need to be updated with this new ESJON method)

fyi - this list will eventually include the [enhanced Query MongoDB functionality](https://jira.mongodb.org/browse/DOCSP-37312), which hasn't been released yet

2024-07-02 22:08 UTC, lindseymoore commented on source/sdk/flutter/realm-database/serialization.txt
> +---------------
Keeping as a regular heading, but let me know.

2024-07-09 03:23 UTC, lindseymoore commented on source/sdk/flutter/realm-database/serialization.txt
> +Serialization allows for easier integration with MongoDB APIs.
Ticket for this work: https://jira.mongodb.org/browse/DOCSP-41296

2024-07-09 20:39 UTC, cbullinger requested changes

2024-07-09 20:39 UTC, cbullinger commented on source/sdk/flutter/realm-database/serialization.txt
> +   * - Embedded Object
I think we should be okay with just Object here. To show that any Object <-> Document

2024-07-09 20:39 UTC, cbullinger commented on examples/dart/test/person.dart
> +class Person {
[random nit] is there a reason the class is defined the way it is (e.g. what the heck is a `cprNumber`)?

2024-07-09 20:39 UTC, cbullinger commented on examples/dart/test/serialization_test.dart
> +  // RealmValue supported??? Engineer said so but doesn't seem to be so
1. Can we update these comments to be more descriptive of the issue (to help anyone else reading them who might not have the context)?
2. Do we have a ticket or something to track this work, so we can update once engineering get the bug fixes in? @krollins-mdb do we have a standard for handling feature docs with known bugs? i.e. do we need to note anything in the docs?

2024-07-09 20:39 UTC, cbullinger commented on examples/dart/test/serialization_test.dart
> +  // Symbol sym = #hhh;
?

2024-07-09 20:39 UTC, cbullinger commented on examples/dart/test/serialization_test.dart
> +import 'package:test/test.dart';
can we clean up the old comments and print statements?

2024-07-09 20:39 UTC, cbullinger commented on source/sdk/flutter/realm-database/serialization.txt
> +Serialization allows for easier integration with MongoDB APIs.
I think the suggested edits here are still valid, even if the linked pages will be updated in separate tickets (let's make sure we have tickets tracking the custom function auth updates too. doesn't look like custom user data has any impacts)

2024-07-09 20:39 UTC, cbullinger commented on source/sdk/flutter/realm-database/serialization.txt
> +    :language: dart
```suggestion
    :language: dart
    :emphasize-lines: 9
```
to highlight the @ejson annotation line

2024-07-18 19:33 UTC, lindseymoore commented on examples/dart/test/person.dart
> +class Person {
It's apparently a Danish id number?? I took from another example in the docs, I'll just change to age haha

2024-07-18 20:03 UTC, lindseymoore commented on examples/dart/test/serialization_test.dart
> +  // RealmValue supported??? Engineer said so but doesn't seem to be so
Added the engineering ticket to a comment (RDART-1063). I can make a DOCSP ticket to update this section with RealmValue and Decimal128 once engineering ticket is resolved. Doesn't seem to be high priority for engineering, so I'm comfortable listing RealmValue and Decimal128 as unsupported for now. Will let engineering know if that sounds good!

2024-07-18 20:07 UTC, lindseymoore commented on examples/dart/test/serialization_test.dart
> +  // Symbol sym = #hhh;
Removed, as users should only be using these types with endpoints.

2024-07-18 21:04 UTC, cbullinger commented on examples/dart/test/person.dart
> +class Person {
😂 that makes sense lol

2024-07-18 21:36 UTC, lindseymoore commented on source/sdk/flutter/realm-database/serialization.txt
> +Serialization allows for easier integration with MongoDB APIs.
I see the function on this page converts to json rather than ejson. Is converting to ejson the more updated way; will it no longer work with json?
I'll add the function auth update to the previous ticket!

2024-07-18 22:02 UTC, cbullinger commented on source/sdk/flutter/realm-database/serialization.txt
> +Serialization allows for easier integration with MongoDB APIs.
ooh, good catch! 🕵️ looks like that call uses `jsonEncode()` and `jsonDecode()` internally, so we should probably still point users to serialize object args that way. Although now I'm a little confused by the last sentence... ("The Function returns a dynamic value containing MongoDB Extended JSON (EJSON) deserialized to a native Dart object.") 

Either way, I think we're good to leave this as-is. Thanks for digging into this and confirming!

2024-07-18 22:14 UTC, cbullinger approved these changes
🚀 You did it! Page looks great, @lindseymoore! ❤️

2024-07-18 22:14 UTC, cbullinger commented on source/sdk/flutter/realm-database/serialization.txt
> +The Flutter SDK supports serialization of all :ref:`supported data types <flutter-data-types>`.
```suggestion
The Flutter SDK currently supports serialization of the following :ref:`supported data types <flutter-data-types>`: 

- All Dart-language data types
- All Realm-specific data types _except_ Decimal128 and RealmValue
```
this lets us move these 2 realm-specific types from the list of unsupported BSON types below

2024-07-18 22:14 UTC, cbullinger commented on source/sdk/flutter/realm-database/serialization.txt
> +CodeWScope, DBPointer, DBRef, Regular Expression, and Timestamp.
```suggestion
Flutter SDK serialization does not currently support the following BSON types: Code, 
CodeWScope, DBPointer, DBRef, Regular Expression, and Timestamp. 
```

2024-07-19 19:09 UTC, merged