DOCSP-39509 Reduce Database File Size
mongodb/docs-realm pull request #3271
Opened 2024-05-22 19:05 UTC by lindseymoore

## Pull Request Info - SDK Docs Consolidation

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39509

*Staged Page*

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

*Page Source*

Add links to every SDK's pages where you got the SDK-specific information:

- [PAGE_NAME](https://www.mongodb.com/docs/atlas/device-sdks/LIVE-DOCS-LINK)

### PR Author Checklist

Before requesting a review for your PR, please check these items:

- [ ] Open the PR against the `feature-consolidated-sdk-docs` branch instead of `master`
- [ ] Tag the consolidated page for:
  - genre
  - meta.keywords
  - meta.description

#### Naming
- [ ] Update Realm naming and the language around persistence layer/local/device per [this document](https://docs.google.com/document/d/126OczVxBWAwZ4P5ZsSM29WI3REvONEr1ald-mAwPtyQ/edit?usp=sharing)
- [ ] Include `.rst` files comply with [the naming guidelines](https://docs.google.com/document/d/1h8cr66zoEVeXytVfvDxlCSsUS5IZwvUQvfSCEXNMpek/edit#heading=h.ulh8b5f2hu9)

#### Links and Refs
- [ ] Create new consolidated SDK ref targets starting with "_sdks-" for relevant sections
- [ ] Remove or update any SDK-specific refs to use the new consolidated SDK ref targets
- [ ] [Update any Kotlin API links](https://jira.mongodb.org/browse/DOCSP-32519) to use the new Kotlin SDK roles

#### Content
- [ ] Shared code boxes have snippets or placeholders for all 9 languages
- [ ] API description sections have API details or a generic placeholder for all 9 languages
- [ ] Check related pages for relevant content to include
- [ ] Create a ticket for missing examples in each relevant SDK: Consolidation Gaps epic

### Reviewer Checklist

As a reviewer, please check these items:

- [ ] Shared code example boxes contain language-specific snippets or placeholders for every language
- [ ] API reference details contain working API reference links or generic content
- [ ] Realm naming/language has been updated
- [ ] All relevant content from individual SDK pages is present on the consolidated page

2024-06-05 14:59 UTC, dacharyc requested changes
Great first pass! I know this was a lot of work. I've got a mix of heading and content suggestions, some spots where we do actually have the API that we say is missing, and a reminder to clean up the "realm" naming as part of this PR. Let me know if you have any questions about any of these suggestions!

2024-06-05 14:59 UTC, dacharyc commented on source/sdk/files/reduce-file-size.txt
> +      The Swift SDK for Objective C does not currently support this API.
```suggestion
      The Swift SDK for Objective-C does not currently support this API.
```

2024-06-13 18:53 UTC, lindseymoore commented on source/sdk/files/reduce-file-size.txt
> +Manual Compaction Strategies
I think this suggestions works, thanks!

2024-06-13 19:12 UTC, lindseymoore commented on source/sdk/files/reduce-file-size.txt
> +compact a file without first obtaining a realm instance.
Thank you!

2024-06-13 19:26 UTC, lindseymoore commented on source/sdk/files/reduce-file-size.txt
> +Make a Compacted Copy
"Make a Reduced File Size Copy of the Original File", what do you think? Want to include reduce file size in the title somewhere.

2024-06-13 19:34 UTC, lindseymoore commented on source/sdk/files/reduce-file-size.txt
> +
Edited, what do you think?

2024-06-13 20:19 UTC, lindseymoore commented on source/sdk/files/reduce-file-size.txt
> +.. include:: /includes/compaction-tips.rst
Removed the information from the include! Considering keeping this information here, as it could also apply to the compact on demand section if a user wants to compact on close or some other time instead of open. What do you think?

2024-06-13 20:20 UTC, lindseymoore commented on source/sdk/files/reduce-file-size.txt
> +.. code-block:: javascript
That's fair, I was hoping the example would be helpful pseudocode for a user to potentially copy and paste (I could make the example more pseudocode-y?). What do you think?

2024-06-13 20:35 UTC, lindseymoore commented on source/sdk/files/reduce-file-size.txt
> +      The Java SDK does not currently support this API.
Thank you!

2024-06-13 20:53 UTC, lindseymoore commented on source/sdk/files/reduce-file-size.txt
> +.. for this one, might want to delete code block all together, since we didn't have examples for any of them. Or do
Ticket for adding TS examples: https://jira.mongodb.org/browse/DOCSP-40178

2024-06-17 20:40 UTC, dacharyc requested changes
Nice work on the updates! We should undo changing the code examples, as we'll do that as a separate unit of work. I've got a handful of other suggestions, but it's getting close!

2024-06-17 20:40 UTC, dacharyc commented on source/sdk/files/reduce-file-size.txt
> +.. code-block:: javascript
I think as it is it's not the greatest representation. It's using a lot of variables that are not initialized in the example block. You can _guess_ what the values represent based on the variable names, but it's not actually spelled out. And I also think this code block should not be copyable since it doesn't have everything it needs to actually work.

Looking at it again, I honestly think we should move the text from this section up into the "Conditionally Reduce File Size on Database Open" section as a new subsection. It only applies to that method. Then I think we could remove this code example entirely, since it's so close to the language-specific code example where we're already showing this logic.

2024-06-17 20:40 UTC, dacharyc commented on source/sdk/files/reduce-file-size.txt
> +Because compacting can be computationally expensive, you may want to avoid
I think we should probably put this information above the API description, since it describes when you might want to use this method versus the conditional compact method.

2024-06-17 20:40 UTC, dacharyc commented on source/sdk/files/reduce-file-size.txt
> +      The C++ SDK does not currently support this API.
Since the code example is using the placeholder that says the API is unsupported, we can omit the text here. You can just leave the C++ tab empty.

2024-06-17 20:40 UTC, dacharyc commented on source/sdk/files/reduce-file-size.txt
> +      The C++ SDK does not currently support this API.
Same here - you can just leave this tab empty since we're using the "unsupported API" code example snippet.

2024-06-17 20:40 UTC, dacharyc commented on source/sdk/files/reduce-file-size.txt
> +The size of a database file is always larger than the total
The use of `.realm` below without explaining that it's the database file format read a little weird to me. I think we should probably mention it here where we're first referring to a db on the page. Maybe:
```suggestion
The size of a database file (``.realm``) is always larger than the total 
```

Or:

```suggestion
The size of a ``.realm`` database file is always larger than the total 
```

2024-06-17 20:40 UTC, dacharyc commented on source/sdk/files/reduce-file-size.txt
> +require stricter management of file size or that use an older version
Because we mention "an older version of the SDK that does not support automatic compaction," I as a user immediately wonder what version of the SDK that is, and whether my version supports it or not.

So I think we should probably add a list of SDK versions to the section above so people know what versions support automatic compaction. You should be able to get the information from the "New in version" directives in the various SDKs. I saw that there is no version listed for Java or C++, so you may need to do some spelunking in Jira to figure out whether it is tied to a Core version update or an SDK release. If it's a Core version, you can list whichever version of C++ got that Core version, and Java may or may not have a release that has it. If it's something that required work in the SDK, C++ and Java may not have it, I guess? It should be a bullet list similar to:

> The minimum SDK version requirements for automatic compaction are:
> - C++ SDK vFoo
> - Flutter SDK v0.9.0
> - Kotlin SDK v1.6.0

Where the SDKs are in alphabetical order and list the minimum required version, etc.

2024-08-16 19:15 UTC, closed without merging