Docsp 39541
mongodb/docs-realm pull request #3273
Opened 2024-05-23 16:09 UTC by krollins-mdb

## Pull Request Info - SDK Docs Consolidation

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39541

*Staged Page*

- [Logging](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-39541/)

*Page Source*

Add links to every SDK's pages where you got the SDK-specific information:

- [Logging - C++ SDK](https://www.mongodb.com/docs/atlas/device-sdks/sdk/cpp/logging/)
- [Logging - Flutter SDK](https://www.mongodb.com/docs/atlas/device-sdks/sdk/flutter/logging/)
- [Log Realm Events - Java SDK](https://www.mongodb.com/docs/atlas/device-sdks/sdk/java/test-and-debug/log-realm-events/)
- [Logging - Kotlin SDK](https://www.mongodb.com/docs/atlas/device-sdks/sdk/kotlin/logging/)
- [Logging - .NET SDK](https://www.mongodb.com/docs/atlas/device-sdks/sdk/dotnet/logging/)
- [Logging - Node.js SDK](https://www.mongodb.com/docs/atlas/device-sdks/sdk/node/logging/)
- [Logging - Swift SDK](https://www.mongodb.com/docs/atlas/device-sdks/sdk/swift/logging/)

### PR Author Checklist

Before requesting a review for your PR, please check these items:

- [ ] Open the PR against the `feature-consolidated-sdk-docs` branch instead of `master`
- [ ] Tag the consolidated page for:
  - genre
  - meta.keywords
  - meta.description

#### Naming
- [ ] Update Realm naming and the language around persistence layer/local/device per [this document](https://docs.google.com/document/d/126OczVxBWAwZ4P5ZsSM29WI3REvONEr1ald-mAwPtyQ/edit?usp=sharing)
- [ ] Include `.rst` files comply with [the naming guidelines](https://docs.google.com/document/d/1h8cr66zoEVeXytVfvDxlCSsUS5IZwvUQvfSCEXNMpek/edit#heading=h.ulh8b5f2hu9)

#### Links and Refs
- [ ] Create new consolidated SDK ref targets starting with "_sdks-" for relevant sections
- [ ] Remove or update any SDK-specific refs to use the new consolidated SDK ref targets
- [ ] [Update any Kotlin API links](https://jira.mongodb.org/browse/DOCSP-32519) to use the new Kotlin SDK roles

#### Content
- [ ] Shared code boxes have snippets or placeholders for all 9 languages
- [ ] API description sections have API details or a generic placeholder for all 9 languages
- [ ] Check related pages for relevant content to include
- [ ] Create a ticket for missing examples in each relevant SDK: Consolidation Gaps epic

### Reviewer Checklist

As a reviewer, please check these items:

- [ ] Shared code example boxes contain language-specific snippets or placeholders for every language
- [ ] API reference details contain working API reference links or generic content
- [ ] Realm naming/language has been updated
- [ ] All relevant content from individual SDK pages is present on the consolidated page

2024-06-06 17:19 UTC, krollins-mdb commented on examples/dart/test/logger.dart
> +    await delay(200);
This is a bit of a hack to wait for the stream to and listeners to do their thing.

I would love to make this code a more realistic use case and incorporate it into a Flutter app, but there's no time for that - especially as part of the consolidation project.

2024-06-06 19:52 UTC, dacharyc requested changes
This is a great start! There are some things that come across kind of weird on on the consolidated page that I think we can improve, and there are some updates we should make to the metadata.

2024-06-06 19:52 UTC, dacharyc commented on source/sdk/test-and-debug/log.txt
> +   :keywords: Realm, C++ SDK, Flutter SDK, Kotlin SDK, Java SDK, Node.js SDK, Swift SDK, code example
Sorry, we're missing .NET here in the copyable template. I've added it on one of my PRs that is pending review, but it's still pending review.

```suggestion
   :keywords: Realm, C++ SDK, Flutter SDK, Kotlin SDK, Java SDK, .NET SDK, Node.js SDK, Swift SDK, code example
```

2024-06-06 19:52 UTC, dacharyc commented on source/sdk/test-and-debug/log.txt
> +   :values: cpp, csharp, dart, java, javascript/typescript, kotlin, objective-c, swift
I don't see Objective-C examples here, so I think we should omit it.

```suggestion
   :values: cpp, csharp, dart, java, javascript/typescript, kotlin, swift
```

2024-06-06 19:52 UTC, dacharyc commented on source/sdk/test-and-debug/log.txt
> +Java SDK: Deprecated Sync Logger
I think, instead of having two separate "Deprecated Sync Logger" sections for different SDKs, I'd probably rename this generically to:

"Deprecated Sync Logger"

And then use a tab group here to display the C++ and Java info.

For the tabs that aren't C++ or Java, I'd probably add a quick note saying something like:

> The <Foo> SDK deprecated the Sync logger in favor of the Realm logger in version <version number>. For versions <version number immediately before this was deprecated> and earlier, refer to the <link to SyncManager API reference> for details about the deprecated APIs.

2024-06-06 19:52 UTC, dacharyc commented on source/sdk/test-and-debug/log.txt
> +The Java SDK's only logger is a deprecated sync logger that behaves differently
I'm not sure this is technically true? The RealmLogger in Java doesn't say anything about being restricted to a Sync logger - it's not in the Sync package, and the API reference docs say:

> Global logger used by all Realm components. Custom loggers can be added by registering classes implementing [RealmLogger](https://www.mongodb.com/docs/realm-sdks/java/latest/io/realm/log/RealmLogger.html).

So - I think this can be used similar to the other loggers, and it just doesn't have any examples other than setting the log level.

2024-06-06 19:52 UTC, dacharyc commented on source/sdk/test-and-debug/log.txt
> +Set the Sync Client Log Level
We probably don't need a separate subheader here. It's taking more real estate/attention than I think it needs in the OtP. And if we make this a generic "Deprecated Sync Logger" header with tab groups for SDK-specific info, then I think we wouldn't want this header to show on the page anyway since it would only be in the C++ tab.

2024-06-06 19:52 UTC, dacharyc commented on source/sdk/test-and-debug/log.txt
> +      .. include:: /includes/api-details/cpp/logger/logging-customize-logger-description-2.rst
So - you don't actually have to include empty files for each tab. You can omit content within a tab if there is no SDK-specific content we need to call out, as long as you still include the tab itself. So I'd probably remove these empty includes.

2024-06-06 19:52 UTC, dacharyc commented on source/sdk/test-and-debug/log.txt
> +After setting a custom logger, you may need to initialize the logger.
This reads a bit weird to me on languages where there is no example of initializing the logger. For example, on C#, there's a "missing example" placeholder below this copy. I wasn't sure if that's because the example is _actually_ missing, or if you don't have to do a separate step of initializing the logger, since the copy here says "you may need to."

I think I would probably move this content for SDKs that require it up into the tab group above, and just omit it from here.

Then, I would include the "last" code example as the code example in the `/includes/sdk-examples/logger/logging-set-custom-logger-example.rst` file.

For example, for C++ - I see there's an example of initializing the logger below. I would make _that_ the example in the `/includes/sdk-examples/logger/logging-set-custom-logger-example.rst` file, and then move the C++ example of actually defining the custom logger into the `/includes/api-details/cpp/logger/logging-customize-logger-description.rst` file.

Let me know if this makes sense or if you have Qs!

2024-06-06 19:52 UTC, dacharyc commented on temp/swift/app-services/connect-to-app-services-backend.txt
> -.. _ios-init-appclient:
We should probably omit this file from the PR so we're not getting into merge conflicts in the `temp` directory.

2024-06-06 19:52 UTC, dacharyc commented on source/sdk/atlas/connect.txt
> +.. _ios-init-appclient:
One of the units of work for this project is to remove SDK-specific ref targets, so we shouldn't add this here. We should just use the generic `sdks-connect-to-atlas` ref target if we need to link to this page.

2024-06-06 19:52 UTC, dacharyc commented on source/includes/api-details/swift/logger/logging-set-change-level-description.rst
> +  When you initialize an :ref:`App client <ios-init-appclient>`, the Swift SDK
One of the units of work for this project is to replace the language and SDK-specific ref targets with generic ones. So we can just use `sdks-connect-to-atlas` here, instead, since that's the one on the page.
```suggestion
  When you initialize an :ref:`App client <sdks-connect-to-atlas>`, the Swift SDK
```

2024-06-06 19:52 UTC, dacharyc commented on source/includes/api-details/kotlin/logger/logging-set-change-level-description.rst
> +.. include:: /includes/tip-sync-log-levels.rst
One of the benefits of consolidating the docs pages is that we generally shouldn't need generic includes, because we don't need to split content across a bunch of pages. Instead of nesting this includes here, I'd try taking the content out of the include and putting it directly on the main page wherever it needs to be.

2024-06-06 19:57 UTC, dacharyc reviewed
Just to avoid blocking this, changing my review status from "request changes" to "comment."

2024-06-06 19:58 UTC, dacharyc reviewed
Trying again to change the review state to "comment" just so I don't block this while I'm out next week.

2024-06-10 16:03 UTC, krollins-mdb commented on source/includes/api-details/kotlin/logger/logging-set-change-level-description.rst
> +.. include:: /includes/tip-sync-log-levels.rst
Thanks for catching that. I do have this on the main page already. 😄

2024-06-10 16:07 UTC, krollins-mdb commented on source/sdk/atlas/connect.txt
> +.. _ios-init-appclient:
Hmm. Yeah, I can't remember why I added it here. It's not used anywhere in the consolidated content. 🤷 

Thanks for catching this!

2024-06-10 16:09 UTC, krollins-mdb commented on temp/swift/app-services/connect-to-app-services-backend.txt
> -.. _ios-init-appclient:
Ah, right. I think I had a build error about ambiguous refs, so deleted this one. Before I realized the right way is to use the consolidated refs.

2024-06-10 16:15 UTC, krollins-mdb commented on source/sdk/test-and-debug/log.txt
> +      .. include:: /includes/api-details/cpp/logger/logging-customize-logger-description-2.rst
Got it! Thanks. 😄

2024-06-10 17:57 UTC, krollins-mdb commented on source/sdk/test-and-debug/log.txt
> +The Java SDK's only logger is a deprecated sync logger that behaves differently
I renamed the section to "Other Loggers" and have just two tabs: C++ and Java. I did this because, as you say, the Java logger isn't really the same thing as the deprecated Sync Logger. But the C++ SDK currently needs that Sync Logger. So, they're both different from the rest of the examples on the page.

2024-06-10 18:00 UTC, krollins-mdb commented on source/sdk/test-and-debug/log.txt
> +Java SDK: Deprecated Sync Logger
I renamed the section to "Other Loggers" and have just two tabs: C++ and Java. I did this because, as you say, the Java logger isn't really the same thing as the deprecated Sync Logger. But the C++ SDK currently needs that Sync Logger. So, they're both different from the rest of the examples on the page.

2024-06-10 20:47 UTC, krollins-mdb commented on source/sdk/test-and-debug/log.txt
> +After setting a custom logger, you may need to initialize the logger.
Hmm, yeah. I went back and forth trying to figure out how much structure to impose. Including initialization as an include in the SDK description hides the expected structure a bit (set -> initialize). But doing the way I currently am definitely makes it awkward for a couple of the SDKs.

2024-06-17 21:23 UTC, dacharyc requested changes
Looking good! Just a couple of things with tab IDs, and I think we need to add some generic placeholder content to the "Other Loggers" section for languages _other_ than C++ or Java or else it looks like the page is missing text for that section.

2024-06-17 21:23 UTC, dacharyc commented on source/sdk/test-and-debug/log.txt
> +Other Loggers
lol, I didn't think about this, but for languages _other_ than C++ or C#, this section header now shows with no content. (i.e. Kotlin has an "Other Loggers" heading with no content.) I guess in this case, we should add something to the tabs. Maybe this would be a place to mention the deprecated Sync logger? i.e.

> In SDK versions {FOO} and earlier, you could configure a Sync logger using `methodName`. That method has been deprecated in favor of the global logger.

One for each SDK with the version number in which the Sync logger was deprecated, and the Sync logger method name. I'd say we should avoid linking to the deprecated Sync logger API reference, because at some point those links will break. But it may be useful for folks using the older methods, if nothing else than to have the method name show up if they do a search in the docs so they can see it has been deprecated.

2024-06-17 21:23 UTC, dacharyc commented on source/sdk/test-and-debug/log.txt
> +      :tabid: cpp
The new Realm-specific C++ ID has been added, so we should update all of these `cpp` tab references to use our ID. (This one will display "C++" in the language drop down _without_ the "11" that the Driver version uses.)
```suggestion
      :tabid: cpp-sdk
```

2024-06-17 21:23 UTC, dacharyc commented on source/sdk/test-and-debug/log.txt
> +      :tabid: cpp
```suggestion
      :tabid: cpp-sdk
```

2024-06-17 21:23 UTC, dacharyc commented on source/sdk/test-and-debug/log.txt
> +      :tabid: cpp
```suggestion
      :tabid: cpp-sdk
```

2024-06-17 21:23 UTC, dacharyc commented on source/includes/sdk-examples/logger/logging-set-change-level-example-2.rst
> +     - id: cpp
```suggestion
     - id: cpp-sdk
```

2024-06-17 21:23 UTC, dacharyc commented on source/includes/sdk-examples/logger/logging-set-change-level-example.rst
> +     - id: cpp
```suggestion
     - id: cpp-sdk
```

2024-06-17 21:23 UTC, dacharyc commented on source/includes/sdk-examples/logger/logging-set-custom-logger-example.rst
> +     - id: cpp
```suggestion
     - id: cpp-sdk
```

2024-06-17 21:23 UTC, dacharyc commented on source/includes/sdk-examples/logger/logging-turn-off-example.rst
> +     - id: cpp
```suggestion
     - id: cpp-sdk
```

2024-06-17 21:23 UTC, dacharyc commented on source/sdk/test-and-debug/log.txt
> +      The Java SDK uses an older Logger that may not behave like the other SDKs.
This content is in a `csharp` tab (maybe it was copied from above?), but it pertains to the Java SDK. We'll need to update this ID to `java` for this info, which means we'll have to add it to _all_ of the tab sets on the page _and_ the ones in the `includes/sdk-examples/logger` or we'll get Snooty errors about a missing tab. But since we don't have Java content that is relevant for those other sections, you'll have to use your judgement about what to put there. Maybe the missing API snippet for the code blocks, and I don't know if it's relevant to add text copy for each Java tab saying that the Java SDK uses a separate logger described below, or if we can just let the missing API snippet serve in those sections.

2024-06-25 00:39 UTC, krollins-mdb commented on source/sdk/test-and-debug/log.txt
> +Other Loggers
It seems like a lot of effort for two minor, relatively unsupported, things. I think I'm going to go back to dedicated sections, but have them be under "Other Loggers".

2024-06-25 13:26 UTC, dacharyc approved these changes
Nice work! I know this has been a big rethink about how the docs work versus the old way. I've got just a few more minor comments, but those are more subjective and not blockers. Thanks for all your effort on this!

2024-06-25 13:26 UTC, dacharyc commented on source/sdk/test-and-debug/log.txt
> +.. warning:: Java SDK Logging Support
I don't love this bright red warning tab at the beginning of the page for an SDK we don't particularly want people to use. I think we should remove this warning block. It's not relevant if I'm here for any of the languages that we _do_ support. There's a ToC entry in the OTP about Java SDK, so if I'm confused about why Java isn't in the language selector, I can just jump right to that section.

2024-06-25 13:26 UTC, dacharyc commented on source/sdk/test-and-debug/log.txt
> +The Java SDK uses an older Logger that may not behave like the other SDKs.
Just a general Q - should we be more specific about how this logger differs from the other SDKs?

2024-06-25 13:26 UTC, dacharyc commented on source/sdk/test-and-debug/log.txt
> +To access newer logging features, use the Kotlin SDK.
And again, if we want to drive people to the Kotlin SDK, should we be more specific about what new features they'll get access to if they use the Kotlin SDK?

2024-06-25 18:44 UTC, krollins-mdb commented on source/sdk/test-and-debug/log.txt
> +.. warning:: Java SDK Logging Support
Makes sense to me! Should be a better experience without that warning.

2024-06-25 18:54 UTC, krollins-mdb commented on source/sdk/test-and-debug/log.txt
> +The Java SDK uses an older Logger that may not behave like the other SDKs.
Maybe. But I don't think it's worth spending more time on. I think I added this sentence to make it clear that the Java SDK wasn't using the same logger type as the other SDKs. But that's accomplished by putting it in the new "Other Loggers" section. I've removed this sentence as it doesn't add anything now and only invites questions. 😄

2024-06-25 19:02 UTC, merged