(DOCSP-39503): Consolidate Relationships page
mongodb/docs-realm pull request #3287
Opened 2024-06-06 17:31 UTC by dacharyc

## Pull Request Info - SDK Docs Consolidation

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39503

*Staged Page*

- [Relationships](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-39503/sdk/model-data/relationships/)

*Page Source*

Add links to every SDK's pages where you got the SDK-specific information:

- [PAGE_NAME](https://www.mongodb.com/docs/atlas/device-sdks/LIVE-DOCS-LINK)

### PR Author Checklist

Before requesting a review for your PR, please check these items:

- [ ] Open the PR against the `feature-consolidated-sdk-docs` branch instead of `master`
- [ ] Tag the consolidated page for:
  - genre
  - meta.keywords
  - meta.description

#### Naming
- [ ] Update Realm naming and the language around persistence layer/local/device per [this document](https://docs.google.com/document/d/126OczVxBWAwZ4P5ZsSM29WI3REvONEr1ald-mAwPtyQ/edit?usp=sharing)
- [ ] Include `.rst` files comply with [the naming guidelines](https://docs.google.com/document/d/1h8cr66zoEVeXytVfvDxlCSsUS5IZwvUQvfSCEXNMpek/edit#heading=h.ulh8b5f2hu9)

#### Links and Refs
- [ ] Create new consolidated SDK ref targets starting with "_sdks-" for relevant sections
- [ ] Remove or update any SDK-specific refs to use the new consolidated SDK ref targets
- [ ] [Update any Kotlin API links](https://jira.mongodb.org/browse/DOCSP-32519) to use the new Kotlin SDK roles

#### Content
- [ ] Shared code boxes have snippets or placeholders for all 9 languages
- [ ] API description sections have API details or a generic placeholder for all 9 languages
- [ ] Check related pages for relevant content to include
- [ ] Create a ticket for missing examples in each relevant SDK: Consolidation Gaps epic

### Reviewer Checklist

As a reviewer, please check these items:

- [ ] Shared code example boxes contain language-specific snippets or placeholders for every language
- [ ] API reference details contain working API reference links or generic content
- [ ] Realm naming/language has been updated
- [ ] All relevant content from individual SDK pages is present on the consolidated page

2024-06-18 22:06 UTC, lindseymoore requested changes
Overall, very good! A couple comments to aid in clarity.

2024-06-18 22:06 UTC, lindseymoore commented on source/sdk/model-data/relationships.txt
> +Relationship definitions in Realm are unidirectional. An
```suggestion
Relationship definitions for Atlas Device SDK are unidirectional. An 
```
realm naming

2024-06-21 21:04 UTC, dacharyc commented on source/sdk/model-data/relationships.txt
> +:ref:`an embedded object <sdks-embedded-objects>`.
Embedded objects are a weird grey area. We don't explicitly define them as a relationship, because they're a different object type and they can't have a lifecycle outside of the parent object. They're not related - they're nested. So we don't say it's a related object - we say it's an embedded object. But we do say right above this:

> The only way to restrict a relationship to "one to one/one to many" instead of "many to one/many to many" is to use an embedded object, which is a nested object with exactly one parent.

So - it felt important to call out here that embedded objects _do_ get deleted, in case anyone takes that comment above as an implication that embedded objects behave like related objects.

2024-06-21 21:04 UTC, dacharyc commented on source/sdk/model-data/relationships.txt
> +object model.
In relational databases, it may be reasonable to infer that these collection types are transient and come from a query. It's important to distinguish for Realm/Device SDK, these aren't transient collections created by querying, but are defined properties on the model. This is also conceptual information that should be familiar to people who are coming from relational databases, so I don't think it warrants additional explanation here.

2024-07-12 20:27 UTC, lindseymoore approved these changes
LGTM! Only lingering question is that the Kotlin page includes how to make the different types of relationship for embedded objects. Is this specific to Kotlin and will this information be included in the embedded object section for Kotlin? @dacharyc 
Link to Kotlin page: https://www.mongodb.com/docs/atlas/device-sdks/sdk/kotlin/realm-database/schemas/relationships/#define-an-embedded-object

2024-07-12 20:59 UTC, dacharyc commented
> LGTM! Only lingering question is that the Kotlin page includes how to make the different types of relationship for embedded objects. Is this specific to Kotlin and will this information be included in the embedded object section for Kotlin? @dacharyc Link to Kotlin page: https://www.mongodb.com/docs/atlas/device-sdks/sdk/kotlin/realm-database/schemas/relationships/#define-an-embedded-object

Totally reasonable question, @lindseymoore ! In the consolidated docs set, the Embedded Object info is on the "Define an Object Model" page - you can see the details in this PR: https://github.com/mongodb/docs-realm/pull/3314

Here's the section about Embedded Objects: https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-39502/sdk/model-data/object-models/#define-an-embedded-object

I removed the info from here because embedded objects _aren't_ related objects in the same way as the other relationships here. They can't exist independent of their parent object. The relationships described here are about linking two object types that each have independent lifecycles. The concept info here does mention embedded objects and link out to the other page, but obviously the page content isn't populated here - it's in the PR for the consolidated "Define an Object Model" page.

2024-07-12 21:16 UTC, merged