DOCSP-16785 the the typo
mongodb/docs-realm pull request #3297
Opened 2024-06-12 21:49 UTC by osharaf-mdb

## Pull Request Info

Jira ticket: https://jira.mongodb.org/browse/DOCSP-16785

- [Many Pages Across docs-realm](https://preview-mongodbosharafmdb.gatsbyjs.io/realm/DOCSP-16785-the-the-typo/): changed "the the" typo and added metadata

### Reminder Checklist

Before merging your PR, make sure to check a few things.

- [ ] Did you tag pages appropriately?
  - genre
  - programming_language
  - meta.keywords
  - meta.description
- [ ] Describe your PR's changes in the Release Notes section
- [ ] Create a Jira ticket for related docs-realm work, if any

### Release Notes

- **Across many docs-realm pages**
  - fixed "the the" typo and added meta data

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-app-services/blob/master/REVIEWING.md)

2024-06-12 22:57 UTC, lindseymoore requested changes
All the the's look good, thanks! 

For the meta descriptions, you'll want to replace Atlas App Services with "Atlas Device SDK". App Services is actually a separate product from the SDKs which are documented here (we'll do a talk on App Services the week after next)! When using the term "realm", I would use the full term "realm database" to specify as well. 

For more context, "Realm" is now the name of just the database as we changed the name of the SDKs from Realm SDKs to "Atlas Device SDKs". Here is a link to how we refer to SDKs of different languages after the name change. The cheatsheet at the bottom is especially helpful!: https://docs.google.com/document/d/126OczVxBWAwZ4P5ZsSM29WI3REvONEr1ald-mAwPtyQ/edit#heading=h.lwkbqtp71sr5

You can used the meta descriptions I fixed as examples or templates. Try to fix the remaining ones, and I'll take another look, thanks!

2024-06-12 22:57 UTC, lindseymoore commented on temp/dotnet/app-services/call-a-function.txt
> +   deserialize after calling the function or by using the  generic
```suggestion
   deserialize after calling the function or by using the generic 
```

2024-06-12 22:57 UTC, lindseymoore commented on temp/cpp/users/custom-user-data.txt
> +  :description: Learn how to create custom data for a user using Atlas App Services in C++
```suggestion
  :description: Learn how to create custom user data using Atlas Device SDK for C++.
```

2024-06-12 22:57 UTC, lindseymoore commented on temp/dotnet/app-services/call-a-function.txt
> +  :description: Learn how to call a function from the .NET SDK
```suggestion
  :description: Learn how to call a function using the Atlas Device SDK for .NET.
```

2024-06-12 22:57 UTC, lindseymoore commented on temp/dotnet/manage-users/custom-user-data.txt
> +  :description: Learn how to create custom user data using Atlas App Services in .NET
```suggestion
  :description: Learn how to create custom user data using the Atlas Device SDK for .NET. 
```

2024-06-12 22:57 UTC, lindseymoore commented on temp/flutter/sync/write-to-synced-realm.txt
> +  :description: Learn how to write data to a synced realm in Flutter
```suggestion
  :description: Learn how to write data to a synced realm database using the Atlas Device SDK for Flutter.
```

2024-06-13 02:21 UTC, cbullinger commented on temp/swift/sync/write-to-synced-realm.txt
> +  :description: Learn how ot write to a synced realm using flexible sync
- if you're not already using one, I recommend installing a VSCode linter or [spell checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) to catch basic typos
- the naming guideline for the SDKs is `Atlas Device SDK for <SDK language>`

```suggestion
  :description: Learn how to write to a synced database using Atlas Device SDK for Swift.
```

2024-06-13 02:25 UTC, cbullinger commented on temp/node/users/authenticate-users.txt
> +  :description: Authenticate users into an app using API in node.js
- `Node.js` should always be capitalized 
- This page is specific to the SDK, so we'd refer it as an SDK, not an API (e.g. an _SDK_ method)
```suggestion
  :description: Authenticate users in an Atlas App Services App using Atlas Device SDK for Node.js.
```

2024-06-13 02:30 UTC, cbullinger commented on temp/swift/swiftui/swiftui-previews.txt
> +  :description: Use and debug SwiftUI previews while developing with Atlas App Services
This is a page specific to SDK functionality, not App Services functionality 
```suggestion
  :description: Use and debug SwiftUI Previews while developing with Atlas Device SDK with Swift.
```

2024-06-13 02:32 UTC, cbullinger commented on temp/flutter/users/custom-user-data.txt
> +  :description: Learn how to create custom user data using Atlas App Services in Flutter
There's a note at the top of this page indicating that Flutter SDK currently only supports **reading** custom user data.
```suggestion
  :description: Learn how to read custom user data using Atlas Device SDK for Flutter.
```

2024-06-13 02:33 UTC, cbullinger commented on temp/java/quick-starts/livedata.txt
> +  :description: Learn how to quickly integrate realm into an Android application with LiveData
```suggestion
  :description: Learn how to quickly integrate the Atlas Device SDK for Java into an Android application using LiveData.
```

2024-06-13 02:35 UTC, cbullinger commented on temp/kotlin/users/custom-user-data.txt
> +  :description: Learn about custom user data and how to manage it in App Services in Kotlin
same as Flutter, there's a note at the top of the page indicating that you can only currently read custom user data in Kotlin 
```suggestion
  :description: Learn how to read custom user data in an App Services App using Atlas Device SDK for Kotlin.
```

2024-06-13 02:42 UTC, cbullinger commented on temp/swift/users/custom-user-data.txt
> +  :description: Learn how to create custom user data using Atlas App Services in Swift.
in general we should always strive for consistency, e.g. the descriptions for similar pages across the SDKS (it's not critical for this PR since it will be resolved as part of the consolidation, but definitely something to keep in mind)
```suggestion
  :description: Learn how to work with custom user data using Atlas Device SDK for Swift.
```

2024-06-17 18:25 UTC, lindseymoore approved these changes
LGTM, thanks! Added 'the' in front of Atlas Device SDK to standardize the copy, as that seems to be how we use it when indicating a specific language.

2024-06-17 18:25 UTC, lindseymoore commented on temp/cpp/users/custom-user-data.txt
> +  :description: Learn how to create custom user data using Atlas Device SDK for C++.
```suggestion
  :description: Learn how to create custom user data using the Atlas Device SDK for C++.
```
nit

2024-06-17 18:25 UTC, lindseymoore commented on temp/flutter/users/custom-user-data.txt
> +  :description: Learn how to read custom user data using Atlas Device SDK for Flutter.
```suggestion
  :description: Learn how to read custom user data using the Atlas Device SDK for Flutter.
```
nit

2024-06-17 18:25 UTC, lindseymoore commented on temp/kotlin/users/custom-user-data.txt
> +  :description: Learn how to read custom user data in an App Services App using Atlas Device SDK for Kotlin.
```suggestion
  :description: Learn how to read custom user data in an App Services App using the Atlas Device SDK for Kotlin.
```

2024-06-17 18:25 UTC, lindseymoore commented on temp/node/users/authenticate-users.txt
> +  :description: Authenticate users in an Atlas App Services App using Atlas Device SDK for Node.js.
```suggestion
  :description: Authenticate users in an Atlas App Services App using the Atlas Device SDK for Node.js.
```

2024-06-17 18:25 UTC, lindseymoore commented on temp/swift/swiftui/swiftui-previews.txt
> +  :description: Use and debug SwiftUI Previews while developing with Atlas Device SDK for Swift.
```suggestion
  :description: Use and debug SwiftUI Previews while developing with the Atlas Device SDK for Swift.
```

2024-06-17 18:25 UTC, lindseymoore commented on temp/swift/sync/write-to-synced-realm.txt
> +  :description: Learn how to write to a synced database using Atlas Device SDK for Swift.
```suggestion
  :description: Learn how to write to a synced database using the Atlas Device SDK for Swift.
```

2024-06-17 18:25 UTC, lindseymoore commented on temp/swift/users/custom-user-data.txt
> +  :description: Learn how to work with custom user data using Atlas Device SDK for Swift.
```suggestion
  :description: Learn how to work with custom user data using the Atlas Device SDK for Swift.
```

2024-06-25 15:42 UTC, merged