Docsp 40401 Node.js counter page
mongodb/docs-realm pull request #3313
Opened 2024-06-24 23:49 UTC by osharaf-mdb

## Pull Request Info

Jira ticket: https://jira.mongodb.org/browse/DOCSP-40401

- [Counters - Node.js SDK](https://preview-mongodbosharafmdb.gatsbyjs.io/realm/DOCSP-40401-js-counter/): Added counters page to the Node.js SDK 

### Note to Reviewer

Still fixing formatting, and currently only have code examples in typescript (javascript soon to come)
Creating a new JIRA ticket for pages that require an update as a result of this addition

### Reminder Checklist

Before merging your PR, make sure to check a few things.

- [ ] Did you tag pages appropriately?
  - genre
  - programming_language
  - meta.keywords
  - meta.description
- [ ] Describe your PR's changes in the Release Notes section
- [ ] Create a Jira ticket for related docs-realm work, if any

### Release Notes

- **Counters - Node.js SDK**
  - Node.js SDK > Model Data > Data Types > Counters: The Counters page was created to document the addition of the Counter class and data type to the Node.js SDK and updated the Table of Contents to reflect the addition.

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-app-services/blob/master/REVIEWING.md)

2024-06-25 13:46 UTC, cbullinger requested changes
Fantastic work on this so far! Let's review the feedback together

2024-06-25 13:46 UTC, cbullinger commented on source/sdk/node/model-data/data-types/counters.txt
> +while ''UpdateMode.Modified'' updates only modified properties.
```suggestion
To update a nullable counter (either _to_ or _from_ a ``null`` value), you must 
use ``realm.create()`` with an 
:js-sdk:`UpdateMode <enums/Realm.UpdateMode.html#Modified>` specified. 
Rather than updating the underlying counter value, you are creating a new counter 
value from ``null`` (or reassigning ``null`` to a nullable counter). 

``UpdateMode`` updates any existing Counter object with a matching primary key:

- ``UpdateMode.All`` updates all properties provided.
- ``UpdateMode.Modified`` updates only modified properties.
```
[suggestion] This is a pretty dense paragraph, making it difficult to parse. Let's break it up so it's easier to read, and make sure we're clearly communicating what's important 
[suggestion] include links out to API ref docs
[style] Use active voice

2024-06-25 13:46 UTC, cbullinger commented on source/sdk/node/model-data/data-types/counters.txt
> +querying, you must use ''counter.value'' as seen below.
```suggestion
You can query counter properties like other property types. However, to query by the 
underlying counter value, you must use ``counter.value`` as a placeholder value:
```
[suggestion] revise for conciseness and clarity

2024-06-25 13:46 UTC, cbullinger commented on source/sdk/node/model-data/data-types/counters.txt
> +  :language: typescript
```suggestion
  :language: typescript

For more information on querying with the SDK, refer to :ref:`realm-query-language`. 

```
[suggestion] include link to the RQL ref page
[formatting] include a newline at the end of each source file (you can also automate this with VSCode extensions)

2024-06-25 13:46 UTC, cbullinger commented on source/sdk/node/model-data/data-types/counters.txt
> +Migration will also be necessary for existing counters that are not ''int'' types.
```suggestion
The SDK's :sdk-js:`counter <classes/Realm.Types.Counter.html>` is a presentation 
data type, with an underlying type of ``int``. 
Due to current TypeScript limitations, the SDK does not support using ``valueOf()`` to implicitly convert a counter to a number.
This means that migration is required when changing an ``int`` type to a ``counter``.
```
[suggestion] use active voice 
[suggestion] revise slightly for conciseness  
[suggestion] include link to API ref docs

2024-06-25 13:46 UTC, cbullinger commented on examples/node/v12/__tests__/data-types.test.ts
> +            return realm.create( WithCounterSchema, { _id: new BSON.ObjectId(), counter: 0 } ); // initializing counter to 0
these are both redundant with your assigned defaults

2024-06-25 13:46 UTC, cbullinger commented on examples/node/v12/__tests__/data-types.test.ts
> +describe("Counter Updates", () => {
High-level suggestions for the code: 
- Combine any `without asserts` tests with their corresponding tests containing asserts (or if they do warrant being separate tests, we need to include assertions). If it's a matter of getting the correct content in the snippet, we can walk through the available Bluehawk tags that let you manipulate what's included/excluded. 
- Keep names helpful. For example, it might be easier to refer to a `myCounter` property than a generic `counter` property that you have to then distinguish between the actual data type itself
- We can move some of this to the top of the test file (e.g. defining our objects) to reduce redundancy

2024-06-25 13:46 UTC, cbullinger commented on examples/node/v12/__tests__/data-types.test.ts
> +        // :snippet-start:filtering-with-counter
might be helpful to include a comment about what you're trying to filter for here. Or add it as an intro sentence in the page before this code example is used, e.g.:
> In the following example, we want to find all objects with a counter value greater than or equal to a specific counter's value.

2024-06-25 20:07 UTC, elle-j reviewed
Very nice updates Omar! Great seeing your contributions already. Left you some feedback and suggestions 👍

2024-06-25 20:07 UTC, elle-j commented on source/sdk/node/model-data/data-types/counters.txt
> +- ''"counter”''
Note the `”` (vs `"`)

2024-06-26 17:58 UTC, osharaf-mdb commented on examples/node/v12/__tests__/data-types.test.ts
> +                    nullableCounter: "counter?",
I've updated the examples and removed default. I think it may make more sense, as you've brought up, to mention the "default" parameter outside of the code example

2024-06-26 18:51 UTC, osharaf-mdb commented on examples/node/v12/__tests__/data-types.test.ts
> +            return realm.create( WithNullableCounterSchema, {_id: new BSON.ObjectId(), nullableCounter: 0 } ); // initializing counter to 0
I have changed it so that, rather than having the different counter and nullable counter, there is now just the single class definition that includes both. Hopefully this fixes this issue.

2024-06-26 18:57 UTC, osharaf-mdb commented on examples/node/v12/__tests__/data-types.test.ts
> +        });
I removed them. For the first, I am going to work it into the preceding text in the documentation

2024-07-15 20:20 UTC, osharaf-mdb commented on source/sdk/node/model-data/data-types/counters.txt
> +be ''null''. The ''Counter'' field is declared by using either:
I think I want to keep the nullability out of the properties above but I'm not entirely sure how I would want to go about doing that. I'll set up time to talk to you about that in more detail

2024-07-15 20:26 UTC, osharaf-mdb commented on source/sdk/node/model-data/data-types/counters.txt
> +- ''{ type: "int", presentation: "counter" }''
I tried combining `this comment <https://github.com/mongodb/docs-realm/pull/3313/files#r1653363239>__` here but I'm not sure if it's better or not

2024-07-16 14:21 UTC, osharaf-mdb commented on source/sdk/node/model-data/data-types/counters.txt
> +while ''UpdateMode.Modified'' updates only modified properties.
During an initial review you had mentioned wanting to call out an error. I added some of the verbiage about triggering an error to address this, should I remove it completely or find another place to communicate that?

2024-07-18 03:45 UTC, cbullinger approved these changes
This is really close! Great job on the updates. A few things to address, and some suggestions to take or leave, and we should be good to go! 🚀

2024-07-18 03:45 UTC, cbullinger commented on source/sdk/node/model-data/data-types/counters.txt
> +To update a nullable counter (either *to* or *from* a ``null`` value), you must use
[style] [avoid parentheses in running text](https://www.mongodb.com/docs/meta/style-guide/style/punctuation/#std-label-punctuation:~:text=Avoid%20parentheses%20in%20running%20text.) 
Alternatively, you could set it off with a comma
```suggestion
To update a nullable counter, either *to* or *from* a ``null`` value, you must use
```

2024-07-18 03:45 UTC, cbullinger commented on source/sdk/node/model-data/data-types/counters.txt
> +specified. Rather than updating the underlying counter value, this sets the counter
[style] "rather" typically implies a preference, whereas "instead" implies a choice
```suggestion
specified. Instead of updating the underlying counter value, this sets the counter
```

2024-07-18 03:45 UTC, cbullinger commented on source/sdk/node/model-data/data-types/counters.txt
> +          :language: javascript
[suggestion] might be helpful to highlight the lines where we're calling 
`realm.create()` with the `UpdateMode` (you can use the `emphasize-lines` option, then specify the line numbers)
 ```suggestion
    .. tab::
      :tabid: typescript
      :emphasize-lines: 8, 12
    
      .. literalinclude:: /examples/generated/node/data-types.test.snippet.null-updating.ts 
          :language: typescript
    
    .. tab::
      :tabid: javascript
      :emphasize-lines: 8, 12

      .. literalinclude::  /examples/generated/node/data-types.test.snippet.null-updating.js
          :language: javascript
```

2024-07-18 03:45 UTC, cbullinger commented on source/sdk/node/model-data/data-types/counters.txt
> +query<rql-parameterized-queries>` using ``counter.value`` as an interpolated variable. In the
I know it's what's on the current RQL page, but it's not the most clear language (as an aside, I have a PR for the [overhauled RQL page](https://preview-mongodbcbullinger.gatsbyjs.io/realm/docsp-36298-rql/sdk/crud/query-engines/realm-query-language/) as part of the consolidation project, which hopefully uses more straightforward verbiage)
```suggestion
underlying counter value, you must pass the ``counter.value`` in a :ref:`parameterized
query<rql-parameterized-queries>`. In the
```

2024-07-18 03:45 UTC, cbullinger commented on source/sdk/node/model-data/data-types/field-types.txt
> +- ``counter`` functions as a logical counter when working with synchronized realms. The ``counter`` data type and its associated class is available in the :github:`realm-js@12.10.0 release <realm/rea
```suggestion
- ``counter`` functions as a logical counter when working with synchronized databases. The ``counter`` data type and its associated class are available in the :github:`realm-js@12.10.0 release <realm/realm-js/releases/tag/v12.10.0>`.
```

2024-07-18 03:45 UTC, cbullinger commented on source/sdk/node/model-data/define-a-realm-object-model.txt
> +Define a Realm Object Model - Node.js SDK
nice!

2024-07-18 03:45 UTC, cbullinger commented on source/sdk/node/model-data/data-types/counters.txt
> +``UpdateMode`` updates any existing Counter object with a matching primary key.
```suggestion
``UpdateMode`` updates any existing Counter object with a matching primary key, according to the specified mode:
```

2024-07-18 03:45 UTC, cbullinger commented on source/sdk/node/model-data/data-types/counters.txt
> +desired :ref:`Realm Object Schema <node-define-a-realm-object-schema>` and initial counter
is it "the desired schema"? or the schema that contains the counter property?

2024-07-18 15:07 UTC, osharaf-mdb commented on source/sdk/node/model-data/data-types/counters.txt
> +desired :ref:`Realm Object Schema <node-define-a-realm-object-schema>` and initial counter
Heard -- I ended up just dropping the word "desired" from that sentence.

2024-07-18 15:13 UTC, osharaf-mdb commented on source/sdk/node/model-data/data-types/counters.txt
> +The ``Counter`` class makes it possible to sync these updates so the ``counter`` converges to
I changed this instance from ``counter`` to "value" to remove the monospace formatting and changed line 59ish to read "The property is initialized by using either:" instead of "The ``counter`` field is initialized by using either:"

2024-07-18 18:30 UTC, merged