(DOCSP-39502): Consolidate Define an Object Model page
mongodb/docs-realm pull request #3314
Opened 2024-06-27 18:53 UTC by dacharyc

## Pull Request Info - SDK Docs Consolidation

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39502

*Staged Page*

- [Define an SDK Object Model](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

*Page Source*

Add links to every SDK's pages where you got the SDK-specific information:

- [PAGE_NAME](https://www.mongodb.com/docs/atlas/device-sdks/LIVE-DOCS-LINK)

### PR Author Checklist

Before requesting a review for your PR, please check these items:

- [ ] Open the PR against the `feature-consolidated-sdk-docs` branch instead of `master`
- [ ] Tag the consolidated page for:
  - genre
  - meta.keywords
  - meta.description

#### Naming
- [ ] Update Realm naming and the language around persistence layer/local/device per [this document](https://docs.google.com/document/d/126OczVxBWAwZ4P5ZsSM29WI3REvONEr1ald-mAwPtyQ/edit?usp=sharing)
- [ ] Include `.rst` files comply with [the naming guidelines](https://docs.google.com/document/d/1h8cr66zoEVeXytVfvDxlCSsUS5IZwvUQvfSCEXNMpek/edit#heading=h.ulh8b5f2hu9)

#### Links and Refs
- [ ] Create new consolidated SDK ref targets starting with "_sdks-" for relevant sections
- [ ] Remove or update any SDK-specific refs to use the new consolidated SDK ref targets
- [ ] [Update any Kotlin API links](https://jira.mongodb.org/browse/DOCSP-32519) to use the new Kotlin SDK roles

#### Content
- [ ] Shared code boxes have snippets or placeholders for all 9 languages
- [ ] API description sections have API details or a generic placeholder for all 9 languages
- [ ] Check related pages for relevant content to include
- [ ] Create a ticket for missing examples in each relevant SDK: Consolidation Gaps epic

### Reviewer Checklist

As a reviewer, please check these items:

- [ ] Shared code example boxes contain language-specific snippets or placeholders for every language
- [ ] API reference details contain working API reference links or generic content
- [ ] Realm naming/language has been updated
- [ ] All relevant content from individual SDK pages is present on the consolidated page

2024-07-08 20:26 UTC, krollins-mdb commented on source/includes/api-details/javascript/model-data/object-models-define-embedded-object-js-ts-description.rst
> +In the Node.js SDK, to define an embedded object, set ``embedded``
> In the Node.js SDK

Can we remove this specific reference? In the consolidated docs, there's not really a "Node.js" SDK anymore. And the conceptual info here applies to all the JS SDKs.

2024-07-08 20:31 UTC, krollins-mdb commented on source/includes/api-details/javascript/model-data/object-models-object-model-description.rst
> +JavaScript objects.
After talking with the JS SDK team, it makes sense to simplify the approach to only using classes. With the caveat that we never use `new` to construct a new instance. Instead, we define a model with a class, then create objects use an object literal. Like this:
```
class Book extends Realm.Object {
  // Don't forget to declare these.
  title!: string;
  price!: number;

  static schema: ObjectSchema = {
    name: "Book",
    properties: {
      title: "string",
      price: "double",
    },
  };
}

const book = realm.write(() => {
  return realm.create(Book, { title: "My Title", price: 20.25 });
});

// TS knows about these fields from the declarations in the model.
book.title;
book.price;
```

Passing the class into `realm.create`, followed by an object literal, gives us a better dev experience in TypeScript. It doesn't provide any benefits in JavaScript, but we should use the same approach in both for consistency.

2024-07-08 20:34 UTC, krollins-mdb commented on source/includes/api-details/javascript/model-data/object-models-object-model-description.rst
> +.. TODO: Provide more info about why you would choose one of these approaches over the other
Based on my comment above, we don't recommend this and should probably avoid talking about it.

2024-07-08 20:34 UTC, krollins-mdb commented on source/includes/api-details/javascript/model-data/object-models-object-schema-js-ts-description.rst
> +.. TODO: Verify that this is accurate
Let's leave this approach out of the docs.

2024-07-08 20:40 UTC, krollins-mdb commented on source/includes/api-details/javascript/model-data/object-models-object-model-description.rst
> +JavaScript objects.
We should note that you shouldn't use `new` with class-based models for a few reasons:

- It calls `realm.create()`, so must always be used in a write transaction
- It doesn't play well with embedded objects

It really comes down to when objects are just objects and when they are managed objects. Calling `new` automatically creates a managed object.

Not calling `new` lets you create unmanaged objects, then pass them and the class model to `realm.create()` when it makes sense to do so.

2024-07-10 16:01 UTC, dacharyc commented on source/includes/api-details/javascript/model-data/object-models-object-model-description.rst
> +JavaScript objects.
Got it! Thanks for clarifying these details with the JS team.

I've updated the wording here and in the TS description. Can you take a look and make sure this accurately communicates the important points?

I do worry that we're now saying something in the docs that is not consistent with all of our code examples. But I guess that's a problem to address in the consolidation gaps epic.

2024-07-10 17:30 UTC, krollins-mdb commented on source/includes/api-details/javascript/model-data/object-models-object-model-description.rst
> +JavaScript objects.
We seem to mostly adhere to the guidance - at least on this page. The Node.js examples definitely need work. They haven't been modernized/standardized in a long time (since before I started at MongoDB).

2024-07-17 19:48 UTC, krollins-mdb requested changes
Requesting changes mainly for some remaining "realm" stuff. I had a question in particular about "Realm object" that will affect a good number of my suggestions.

@dacharyc, thank you for doing this difficult and delicate work! Having everything together like this makes it much easier to understand how to work with objects. My brain is spaghetti after reading it. It must have been such a bear to put together.

A higher-level question: do we want to introduce a generic managed vs not managed objects section that talks about the different between language objects and realm objects?

2024-07-17 19:48 UTC, krollins-mdb commented on source/includes/api-details/kotlin/model-data/object-models-define-geospatial-object-description.rst
> +     property in the realm schema containing a latitude/longitude
```suggestion
     property in the database schema containing a latitude/longitude 
```

2024-07-17 19:48 UTC, krollins-mdb commented on source/includes/api-details/kotlin/model-data/object-models-define-realm-object-description.rst
> +In the Kotlin SDK, to define a Realm object type, create a Kotlin class that
```suggestion
In the Kotlin SDK, to define an SDK object type, create a Kotlin class that
```

2024-07-17 19:48 UTC, krollins-mdb commented on source/includes/api-details/kotlin/model-data/object-models-map-model-or-property-to-different-name-description.rst
> +persisted name to used to store objects in a realm:
```suggestion
persisted name to used to store objects in the on-device database:
```

2024-07-17 19:48 UTC, krollins-mdb commented on source/includes/api-details/objectivec/model-data/object-models-define-realm-object-description.rst
> +In Objective-C, to define a Realm object, create a class that inherits from
```suggestion
In Objective-C, to define an SDK object, create a class that inherits from
```

2024-07-17 19:48 UTC, krollins-mdb commented on source/includes/api-details/swift/model-data/object-models-define-realm-object-description.rst
> +In Swift, to define a Realm object, create a class that inherits from
```suggestion
In Swift, to define an SDK object, create a class that inherits from
```

2024-07-17 19:48 UTC, krollins-mdb commented on source/includes/api-details/typescript/model-data/object-models-define-geospatial-object-description.rst
> +     property in the realm schema.
```suggestion
     property in the database schema. 
```

2024-07-17 19:48 UTC, krollins-mdb commented on source/sdk/model-data/object-models.txt
> +- **Realm object**: the base object type used by the SDK.
Are we sticking with Realm for this use case? Could we use "managed object" instead? The decision here would impact my suggestions in other places to replace "realm object".

2024-07-17 19:48 UTC, krollins-mdb commented on source/sdk/model-data/object-models.txt
> +Define Special Property Behaviors
I know it's from the old content, but are these really "special"? I think "Define Property Behaviors" would work better.

2024-07-17 19:48 UTC, krollins-mdb commented on source/includes/api-details/kotlin/model-data/object-models-define-asymmetric-object-description.rst
> +<io.realm.kotlin.types/-asymmetric-realm-object/index.html>` interface:
I'm getting a 403 on this link. However, I can navigate to the right page and copy-pasting from there works. It's the exact same URL, so this could absolutely be a me thing.

Resolved URL that works for me: https://www.mongodb.com/docs/realm-sdks/kotlin/latest/library-sync/io.realm.kotlin.types/-asymmetric-realm-object/index.html

2024-07-17 22:15 UTC, dacharyc commented on source/includes/api-details/csharp/model-data/object-models-define-realm-object-description.rst
> +In C#, to define a Realm object, inherit from the the
I think in this case, we are specifically talking about Realm object versus the other object types (Asymmetric, Embedded) so this is an appropriate Realm usage.

2024-07-17 22:15 UTC, dacharyc commented on source/includes/api-details/dart/model-data/object-models-define-embedded-object-description.rst
> +The following example shows how to model an embedded object in a Realm schema.
Hmm. This one is tricky - I'm going to go with "Realm object schema" because we're specifically talking about the schema for a Realm object.

2024-07-17 22:15 UTC, dacharyc commented on source/includes/api-details/dart/model-data/object-models-define-realm-object-description.rst
> +In Dart, to define a Realm object, create a class model and add the
I feel pretty strongly that we should keep the Realm name for the Realm object type, so I'll skip applying any of these name change suggestions that are specific to Realm objects.

2024-07-17 22:15 UTC, dacharyc commented on source/includes/api-details/java/model-data/object-models-define-sdk-object-model-java-description.rst
> +The following code block shows a Realm object that
I'm keeping most of these where they refer specifically to the Realm object type, but there are a couple I can genericize to "database" instead - so I'll try to do that.

2024-07-17 22:15 UTC, dacharyc commented on source/includes/api-details/java/model-data/object-models-define-sdk-object-model-kotlin-description.rst
> +      All Realm objects must use the ``open``
I think this is specifically referring to the Realm object implementation, so I'm keeping this one as "Realm."

2024-07-17 22:15 UTC, dacharyc commented on source/includes/api-details/javascript/model-data/object-models-define-geospatial-object-description.rst
> +     property in the realm schema.
I think this one is actually "object schema."

The renaming project does not sit well on this page!

2024-07-17 22:15 UTC, dacharyc commented on source/includes/api-details/kotlin/model-data/object-models-define-asymmetric-object-description.rst
> +<io.realm.kotlin.types/-asymmetric-realm-object/index.html>` interface:
Good catch! This was my error - this link should use the `:kotlin-sync-sdk:` role, not the `:kotlin-sdk:` role. Updating!

2024-07-18 15:48 UTC, krollins-mdb approved these changes
Excellent work, @dacharyc! Thank you for putting so much thought and effort into this.

2024-07-19 15:57 UTC, merged