(DOCSP-39535): Consolidate Manage Sync Subscriptions page
mongodb/docs-realm pull request #3320
Opened 2024-07-11 15:23 UTC by dacharyc

## Pull Request Info - SDK Docs Consolidation

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39535

*Staged Page*

- [Manage Sync Subscriptions](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-39535/sdk/sync/manage-sync-subscriptions/)

*Page Source*

Add links to every SDK's pages where you got the SDK-specific information:

- [C++: Manage Sync Subscriptions](https://www.mongodb.com/docs/atlas/device-sdks/sdk/cpp/sync/sync-subscriptions/)
- [Flutter: Manage Sync Subscriptions](https://www.mongodb.com/docs/atlas/device-sdks/sdk/flutter/sync/manage-sync-subscriptions/)
- [Java: Manage Sync Subscriptions](https://www.mongodb.com/docs/atlas/device-sdks/sdk/java/sync/flexible-sync/)
- [Kotlin: Manage Sync Subscriptions](https://www.mongodb.com/docs/atlas/device-sdks/sdk/kotlin/sync/subscribe/)
- [.NET: Manage Flexible Sync Subscriptions](https://www.mongodb.com/docs/atlas/device-sdks/sdk/dotnet/sync/flexible-sync/)
- [Node.js: Manage Flexible Sync Subscriptions](https://www.mongodb.com/docs/atlas/device-sdks/sdk/node/sync/flexible-sync/)
- [Swift: Manage Flexible Sync Subscriptions](https://www.mongodb.com/docs/atlas/device-sdks/sdk/swift/sync/flexible-sync/)

### PR Author Checklist

Before requesting a review for your PR, please check these items:

- [ ] Open the PR against the `feature-consolidated-sdk-docs` branch instead of `master`
- [ ] Tag the consolidated page for:
  - genre
  - meta.keywords
  - meta.description

#### Naming
- [ ] Update Realm naming and the language around persistence layer/local/device per [this document](https://docs.google.com/document/d/126OczVxBWAwZ4P5ZsSM29WI3REvONEr1ald-mAwPtyQ/edit?usp=sharing)
- [ ] Include `.rst` files comply with [the naming guidelines](https://docs.google.com/document/d/1h8cr66zoEVeXytVfvDxlCSsUS5IZwvUQvfSCEXNMpek/edit#heading=h.ulh8b5f2hu9)

#### Links and Refs
- [ ] Create new consolidated SDK ref targets starting with "_sdks-" for relevant sections
- [ ] Remove or update any SDK-specific refs to use the new consolidated SDK ref targets
- [ ] [Update any Kotlin API links](https://jira.mongodb.org/browse/DOCSP-32519) to use the new Kotlin SDK roles

#### Content
- [ ] Shared code boxes have snippets or placeholders for all 9 languages
- [ ] API description sections have API details or a generic placeholder for all 9 languages
- [ ] Check related pages for relevant content to include
- [ ] Create a ticket for missing examples in each relevant SDK: Consolidation Gaps epic

### Reviewer Checklist

As a reviewer, please check these items:

- [ ] Shared code example boxes contain language-specific snippets or placeholders for every language
- [ ] API reference details contain working API reference links or generic content
- [ ] Realm naming/language has been updated
- [ ] All relevant content from individual SDK pages is present on the consolidated page

2024-07-31 16:29 UTC, krollins-mdb requested changes
Thank you for all of the hard work on this page, @dacharyc!

I requested changes for some API ref links, adding back in a Dart code example, and looking into a couple potential platform bugs.

2024-07-31 16:29 UTC, krollins-mdb commented on source/includes/sdk-examples/sync/manage-sync-subscriptions-subscribe-to-query.rst
> +            :copyable: false
We do have an example for Dart.
```suggestion
         .. literalinclude:: /examples/generated/flutter/manage_sync_subscription_test.snippet.add-subscription-subscribe-api.dart
            :language: dart 
```

2024-07-31 16:29 UTC, krollins-mdb commented on source/includes/api-details/javascript/sync/manage-sync-subscriptions-find-subscription-js-ts-description.rst
> +:java-sdk:`findByQuery()
```suggestion
:js-sdk:`findByQuery()
```

2024-07-31 16:29 UTC, krollins-mdb commented on source/includes/api-details/kotlin/sync/manage-sync-subscriptions-add-subscription-description.rst
> +   :ref:`Realm Query Language query <rql>` to query only a subset of the objects.
```suggestion
   :ref:`Realm Query Language <rql>` to query only a subset of the objects.
```

2024-07-31 16:29 UTC, krollins-mdb commented on source/includes/api-details/kotlin/sync/manage-sync-subscriptions-remove-all-subscriptions-to-object-type-description.rst
> +<io.realm.kotlin.mongodb.sync/-mutable-subscription-set/remove.html>`
```suggestion
<io.realm.kotlin.mongodb.sync/-mutable-subscription-set/remove-all.html>`
```

2024-07-31 16:29 UTC, krollins-mdb commented on source/includes/api-details/swift/sync/manage-sync-subscriptions-find-subscription-description.rst
> +the variants of :kotlin-sync-sdk:`subscriptions.first(ofType: where:)
```suggestion
the variants of :swift-sdk:`subscriptions.first(ofType: where:)
```

2024-08-01 15:17 UTC, dacharyc commented on source/includes/sdk-examples/sync/manage-sync-subscriptions-remove-all-subscriptions-to-object-type.rst
> +         .. include:: /includes/api-details/cpp/sync/manage-sync-subscriptions-refresh-realm-description.rst
Nope, this was a missed copy-paste when I duplicated it from another file. Thanks for catching this!

2024-08-01 15:24 UTC, dacharyc commented on source/sdk/sync/manage-sync-subscriptions.txt
> +.. include:: /includes/sdk-examples/sync/manage-sync-subscriptions-add-subscription.rst
Well, that's unfortunate ☹️ 

It seems to be specific to this page. If I switch to another page with placeholders, this isn't happening (i.e. Create). So I don't know if I've done something disallowed with tabs here, or if it's the _quantity_ of tabs here, or what. I'll play around with this and see if I can figure out what's happening.

2024-08-01 15:42 UTC, dacharyc commented on source/sdk/sync/manage-sync-subscriptions.txt
> +.. include:: /includes/sdk-examples/sync/manage-sync-subscriptions-add-subscription.rst
Ahh, figured it out. I used the wrong `id` in the code example include - I used `cpp` (which IS a valid Driver language, but isn't the one we're using for the SDK) instead of `cpp-sdk`.

This is now fixed here. I noticed it's also wrong in some other code example tab sets, so I'll make a separate PR to update it everywhere else it's wrong as that is outside the scope of this PR.

2024-08-01 15:48 UTC, krollins-mdb commented on source/sdk/sync/manage-sync-subscriptions.txt
> +.. include:: /includes/sdk-examples/sync/manage-sync-subscriptions-add-subscription.rst
Oooooh, interesting. I'm glad you figured it out. I was totally stumped. ha

2024-08-01 15:52 UTC, krollins-mdb approved these changes
Thanks for figuring out and fixing the weird tab set behavior! LGTM!

2024-08-01 16:06 UTC, merged