(DOCSP-39523): Consolidate Call a Function page
mongodb/docs-realm pull request #3322
Opened 2024-07-16 19:18 UTC by dacharyc

## Pull Request Info - SDK Docs Consolidation

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39523

*Staged Page*

- [Call an Atlas Function](https://preview-mongodbdacharyc.gatsbyjs.io/realm/DOCSP-39523/sdk/atlas/call-function/)

*Page Source*

Add links to every SDK's pages where you got the SDK-specific information:

- [C++: Call a Function](https://www.mongodb.com/docs/atlas/device-sdks/sdk/cpp/app-services/call-a-function/)
- [Flutter: Call a Function](https://www.mongodb.com/docs/atlas/device-sdks/sdk/flutter/app-services/call-function/)
- [Java: Call a Function](https://www.mongodb.com/docs/atlas/device-sdks/sdk/java/app-services/call-a-function/)
- [Kotlin: Call a Function](https://www.mongodb.com/docs/atlas/device-sdks/sdk/kotlin/app-services/call-function/)
- [.NET: Call a Function](https://www.mongodb.com/docs/atlas/device-sdks/sdk/dotnet/app-services/call-a-function/)
- [Node.js: Call a Function](https://www.mongodb.com/docs/atlas/device-sdks/sdk/node/app-services/connect-to-app-services-backend/)
- [Swift: Call a Function](https://www.mongodb.com/docs/atlas/device-sdks/sdk/swift/app-services/call-a-function/)

### PR Author Checklist

Before requesting a review for your PR, please check these items:

- [ ] Open the PR against the `feature-consolidated-sdk-docs` branch instead of `master`
- [ ] Tag the consolidated page for:
  - genre
  - meta.keywords
  - meta.description

#### Naming
- [ ] Update Realm naming and the language around persistence layer/local/device per [this document](https://docs.google.com/document/d/126OczVxBWAwZ4P5ZsSM29WI3REvONEr1ald-mAwPtyQ/edit?usp=sharing)
- [ ] Include `.rst` files comply with [the naming guidelines](https://docs.google.com/document/d/1h8cr66zoEVeXytVfvDxlCSsUS5IZwvUQvfSCEXNMpek/edit#heading=h.ulh8b5f2hu9)

#### Links and Refs
- [ ] Create new consolidated SDK ref targets starting with "_sdks-" for relevant sections
- [ ] Remove or update any SDK-specific refs to use the new consolidated SDK ref targets
- [ ] [Update any Kotlin API links](https://jira.mongodb.org/browse/DOCSP-32519) to use the new Kotlin SDK roles

#### Content
- [ ] Shared code boxes have snippets or placeholders for all 9 languages
- [ ] API description sections have API details or a generic placeholder for all 9 languages
- [ ] Check related pages for relevant content to include
- [ ] Create a ticket for missing examples in each relevant SDK: Consolidation Gaps epic

### Reviewer Checklist

As a reviewer, please check these items:

- [ ] Shared code example boxes contain language-specific snippets or placeholders for every language
- [ ] API reference details contain working API reference links or generic content
- [ ] Realm naming/language has been updated
- [ ] All relevant content from individual SDK pages is present on the consolidated page

2024-07-22 21:27 UTC, krollins-mdb requested changes
Thanks again, @dacharyc! Mostly looks good, but I'm requesting changes for a few reasons:

- Some Java API doc links weren't working as expected
- Swift API details have headings that don't appear in other language's details content
- A suggestion for potentially removing the Atlas Function example

2024-07-22 21:27 UTC, krollins-mdb commented on source/sdk/atlas/call-function.txt
> +them, and returns the result:
This paragraph is confusing. Here are a few thoughts:

- ~~In the following code block, we're not showing calling the Function from the SDK - we're showing the Atlas Function itself. The current set up is a bit misleading. I think "The example on this page" may not mean the closest code example, but that's how most people will read it.~~
- ~~Why would it matter what the Atlas Function is named? We don't show that in the following code block.~~
- ~~While it's true that the code example could sum or concatenate in JavaScript, this wouldn't work in other languages. I think it would make sense to simplify to just sum or concatenate and not worry about JavaScript's weirdness~~

EDIT: I see what you were going for. See next comment for more well-informed thoughts. 😆

2024-07-22 21:27 UTC, krollins-mdb commented on source/sdk/atlas/call-function.txt
> +them, and returns the result:
- I think the distance between stating what the Atlas Function is and the example(s) where the Function is invoked is too much for readers to easily associate the two.
- Did you consider putting the Atlas Function example in the "Call a Function" section - maybe it's own subsection - where it's more clearly highlighted that this is the Function that the following code examples will invoke?
- I'm tempted to remove the Atlas Function example entirely. In the context of the consolidated examples, it's more confusing than helpful, I think. It would be nice to have, but I think there are some fundamental things we'd need to fix that are beyond the scope of this PR. (like the fact that the Function example explicitly states it's concatenating strings in a comment)

2024-07-22 21:27 UTC, krollins-mdb commented on source/includes/api-details/swift/atlas/call-atlas-function-call-function-description.rst
> +Async/Await
The Async/Await and Completion Handler headings are included in the on-this-page TOC for every language. But they only work for Swift because it's the only language with API details that include these headings.

Is the only way around this to remove the headers?

2024-07-22 21:27 UTC, krollins-mdb commented on source/includes/api-details/java/atlas/call-atlas-function-call-function-description.rst
> +:java-sdk:`getFunctions() <io/realm/mongodb/App.html#getFunctions-io.realm.mongodb.User->`
This link currently just goes to App and not the specific function.
```suggestion
:java-sdk:`getFunctions() <io/realm/mongodb/App.html#getFunctions(io.realm.mongodb.User)>`
```

2024-07-22 21:27 UTC, krollins-mdb commented on source/includes/api-details/java/atlas/call-atlas-function-call-function-description.rst
> +:java-sdk:`callFunction() <io/realm/mongodb/functions/Functions.html#callFunction-java.lang.String-java.util.List-->`
```suggestion
:java-sdk:`callFunction() <io/realm/mongodb/functions/Functions.html#callFunction(java.lang.String,java.util.List,java.lang.Class)>`
```

2024-07-22 21:27 UTC, krollins-mdb commented on source/includes/api-details/java/atlas/call-atlas-function-call-function-description.rst
> +or :java-sdk:`callFunctionAsync() <io/realm/mongodb/functions/Functions.html#callFunctionAsync-java.lang.String-java.util.List--io.realm.mongodb.App.Callback->`:
```suggestion
or :java-sdk:`callFunctionAsync() <io/realm/mongodb/functions/Functions.html#callFunctionAsync(java.lang.String,java.util.List,java.lang.Class,io.realm.mongodb.App.Callback)>`:
```

2024-07-22 21:27 UTC, krollins-mdb commented on source/includes/api-details/swift/atlas/call-atlas-function-call-function-description.rst
> +To execute a function in Swift, use the ``functions`` object on the currently
I noticed that the Swift content doesn't link to the Swift API ref docs. Worth adding links?

2024-07-22 21:27 UTC, krollins-mdb commented on source/includes/sdk-examples/atlas/call-atlas-function-call-function.rst
> +         .. literalinclude::  /examples/MissingPlaceholders/example.ts
I think we can share the JS example with TS here, as there wouldn't be any difference between the two.

2024-07-22 21:55 UTC, dacharyc commented on source/includes/api-details/swift/atlas/call-atlas-function-call-function-description.rst
> +Async/Await
Ugh, yes, I meant to make this page depth 1. Good catch, thank you!

2024-07-22 21:56 UTC, dacharyc commented on source/sdk/atlas/call-function.txt
> +them, and returns the result:
I did experiment with a few different placements for it, but landed on this. But I understand it's not ideal.

I've removed the example and have reworded the description of the Function we're calling to be generic enough to apply to all the examples, I think.

We can revisit adding some other example in the future if this page becomes a high enough priority to warrant a bigger time investment.

2024-07-23 14:33 UTC, krollins-mdb approved these changes
LGTM. Thanks again, Dachary!

2024-07-23 15:44 UTC, merged