testing providers and hooks
mongodb/docs-realm pull request #3339
Opened 2024-07-25 19:47 UTC by osharaf-mdb

## Pull Request Info - SDK Docs Consolidation

Jira ticket: https://jira.mongodb.org/browse/DOCSP-NNNNN

*Staged Page*

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

*Page Source*

Add links to every SDK's pages where you got the SDK-specific information:

- [PAGE_NAME](https://www.mongodb.com/docs/atlas/device-sdks/LIVE-DOCS-LINK)

### PR Author Checklist

Before requesting a review for your PR, please check these items:

- [ ] Open the PR against the `feature-consolidated-sdk-docs` branch instead of `master`
- [ ] Tag the consolidated page for:
  - genre
  - meta.keywords
  - meta.description

#### Naming
- [ ] Update Realm naming and the language around persistence layer/local/device per [this document](https://docs.google.com/document/d/126OczVxBWAwZ4P5ZsSM29WI3REvONEr1ald-mAwPtyQ/edit?usp=sharing)
- [ ] Include `.rst` files comply with [the naming guidelines](https://docs.google.com/document/d/1h8cr66zoEVeXytVfvDxlCSsUS5IZwvUQvfSCEXNMpek/edit#heading=h.ulh8b5f2hu9)

#### Links and Refs
- [ ] Create new consolidated SDK ref targets starting with "_sdks-" for relevant sections
- [ ] Remove or update any SDK-specific refs to use the new consolidated SDK ref targets
- [ ] [Update any Kotlin API links](https://jira.mongodb.org/browse/DOCSP-32519) to use the new Kotlin SDK roles

#### Content
- [ ] Shared code boxes have snippets or placeholders for all 9 languages
- [ ] API description sections have API details or a generic placeholder for all 9 languages
- [ ] Check related pages for relevant content to include
- [ ] Create a ticket for missing examples in each relevant SDK: Consolidation Gaps epic

### Reviewer Checklist

As a reviewer, please check these items:

- [ ] Shared code example boxes contain language-specific snippets or placeholders for every language
- [ ] API reference details contain working API reference links or generic content
- [ ] Realm naming/language has been updated
- [ ] All relevant content from individual SDK pages is present on the consolidated page

2024-07-26 16:12 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +To make your Providers context available to your entire app, you can create an App Wrapper by
I think we could build this content out more, and then it might be easier to make more logical sense of how the elements fit together on the page and what the headers should be.

It would probably be good to show a hierarchy diagram for various tasks - i.e.

*Use a Synced Database*
- AppProvider
  - UserProvider
    - RealmProvider

*Use a Non-Synced Database*
- RealmProvider

*Authenticate a User*
- AppProvider
  - UserProvider

*Call a Function*
- AppProvider
  - UserProvider

*Access MongoDB Atlas* (this is the "[Query MongoDB page](https://www.mongodb.com/docs/atlas/device-sdks/sdk/react-native/app-services/query-mongodb/)" that uses the MongoClient API)
- AppProvider
  - UserProvider

When you see a bunch of the tasks listed out, it becomes more obvious how the providers fit together and which ones you need to use to perform common tasks. And then I think the requirement to nest components within the wrapper makes more sense. There are a lot of different ways you might choose to represent this information, visually and within the context of the page IA (and as it relates to the larger section IA).

2024-07-26 16:12 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +To use a state in a component you’re creating, call the related hook at the top of your
Maybe this would be a good place for a procedure?

2024-07-26 16:16 UTC, dacharyc commented on source/frameworks/react/api-reference/app-provider.txt
> +Components nested within ``AppProvider`` can access your App Services App
We should probably provide more information in the introduction to each of these pages about what tasks a user might want to do when they are using the Provider - i.e. in this case, accessing an App Services App. The act of accessing an App Services App isn't the developer's goal - it's an incidental implementation detail. It's something they have to do in order to accomplish a task they're trying to do. Documentation usually makes a lot more sense to users when we can frame it in terms of how the developer can use it to do the task they're trying to do instead of mentioning the implementation without that task-based framing.

2024-07-29 21:05 UTC, gagik reviewed
Cool! Some comments that may be worth considering.

2024-07-29 21:24 UTC, gagik commented on source/frameworks/react/api-reference/realm-provider.txt
> +than one realm, you need to destructure a new realm Provider and its associated
not sure what destructure means but what you're creating is a `RealmContext` which includes a `Provider` and hooks.  So with multiple Realms, you will need multiple Realm Contexts and then use their associated providers and hooks depending on the one you need.

As with React docs, you can think of a Provider as a component that "specifies the value of the (Realm) context for all components inside it", so when you have multiple Realms, what you do is create multiple Realm _contexts_ and then use _providers_ to specify what parts of your applications should get what context (in some cases they could be the same).

And in the sense, the hooks are accessing the realm/app/user from the context, not the provider.

It's quite challenging / confusing to word this even for me now but hope this helps 😄

2024-07-29 21:24 UTC, gagik commented on source/frameworks/react/api-reference/realm-provider.txt
> +  Returns a realm instance. This is the realm created by the hook's parent,
similar to the reasoning above, I'd frame this more as the realm from the appropriate realm context.

2024-07-29 21:24 UTC, gagik commented on source/frameworks/react/api-reference/realm-provider.txt
> +than one realm, you need to destructure a new realm Provider and its associated
Redux framing for provider and hooks, may be a helpful reference with subtle wording things:
https://react-redux.js.org/api/provider
https://react-redux.js.org/api/hooks

2024-07-29 21:24 UTC, gagik commented on source/frameworks/react/api-reference/realm-provider.txt
> +RealmProvider Hooks
I understand the reasoning for wording it this way to separate different types of hooks and their needed providers but this may make more sense as `Realm Hooks`, the provider is an implementation detail. https://react-redux.js.org/api/hooks (our case is more complex since we have multiple providers but may be helpful...)

2024-08-01 14:29 UTC, dacharyc reviewed
Nice work, Omar! I really like how this page is shaping up. I've got a handful of suggestions, a couple of technical implementation fixes we need to address, and a Q about possibly adding a little info at a higher conceptual level. But I think you've done a great job and this is really close!

2024-08-01 14:29 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +where child components can access the context created by its parent component.
I really like how you link out to the relevant config objects for configuring props. But after reading this section, I feel like I'm missing a higher-level concept explanation: I want something on this page to make the connection between the Providers and _using_ their analogous JS objects.

We have the section down below where we break down the hooks. But I kind of feel like I want something somewhere that makes the direct mapping - i.e.:

- RealmProvider gives you access to [Realm](https://www.mongodb.com/docs/realm-sdks/react/latest/classes/Realm-1.html)
- AppProvider gives you access to [App](https://www.mongodb.com/docs/realm-sdks/react/latest/classes/Realm.App-1.html)
- UserProvider gives you access to [User](https://www.mongodb.com/docs/realm-sdks/react/latest/classes/Realm.User.html)

Maybe that belongs somewhere in the intro, and then we can say there are two ways to use these Providers - either by using the provided hooks to abstract away some of the boilerplate for common functionality, or create a context if you need direct access to these underlying objects for more granular configuration or usage?

(And I am also not a React dev so I'm not 100% sure I've got this understanding right - which is why I'd love something that gives me a concept explanation at this level of abstraction.)

2024-08-01 14:29 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +      .. include:: /includes/note-rn-multiple-app-clients-and-app-config-cache.rst
Since this is a net new page that is intended for developers who are new to `@realm/react`, I believe we can omit this note. This is only an important detail for folks who are using earlier versions of the SDK, and I believe those folks will not be looking at this page.

2024-08-01 14:29 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +      #. Pass your object models to the ``schema`` prop. (link out)
Looks like we missed adding a link here?

2024-08-01 14:29 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +
Couple of issues with this attempt to link out:

- `:react.dev:` isn't a valid Snooty role. The links we can use in this way are defined in the Snooty [rstspec.toml file](https://github.com/mongodb/snooty-parser/blob/main/snooty/rstspec.toml). For example, here's the [Apple](https://github.com/mongodb/snooty-parser/blob/9610fffa9aa6b004fa89793fd8c088cf23ba0e61/snooty/rstspec.toml#L1459) one. If we wanted to do something like this to link out to the react.dev docs, we would need to make a PR to define a new role in this file and get DOP to merge it before we could use it this way.
- I'm not sure what page we're trying to link out to here. react.dev/docs/hooks-intro.html gives me a 404. I assume a React dev will be familiar with Hooks so we may not need to link out to this at all. (But noting a style element - the React docs use capital "H" for "Hooks", so we may want to update "hook" to "Hook" on this page.)

```suggestion
To use the Provider's context in your app's components, you can use Hooks.
```

2024-08-01 14:29 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +      gives you access to realm methods and properties. For example, you can call
This might be a good place to link out to the [Realm](https://www.mongodb.com/docs/realm-sdks/react/latest/classes/Realm-1.html) class reference, so people can see what methods and properties are available.

2024-08-01 14:29 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +      The ``useObject()`` hook returns a Realm object for a given
This might be a good place to link out to the [Realm.Object](https://www.mongodb.com/docs/realm-sdks/react/latest/classes/Realm.Object.html) class reference, so people can see what methods and properties are available.

2024-08-01 14:29 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +      The ``useQuery()`` hook returns a collection of realm objects of a given type.
Looks like useQuery returns a results set, so this might be a good place to link out to the [Realm.Results](https://www.mongodb.com/docs/realm-sdks/react/latest/classes/Realm.Results.html) class reference so people can see what properties and methods are available.

2024-08-01 14:29 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +      ``useAuth`` returns ``result`` and an authentication method you specify, as shown below. There is an authentication
Might be good to link out to [AuthResult](https://www.mongodb.com/docs/realm-sdks/react/latest/types/AuthResult.html) and/or [OperationResult](https://www.mongodb.com/docs/realm-sdks/react/latest/types/OperationResult.html) here so folks can easily see what they're working with.

2024-08-01 14:29 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +      The ``useUser()`` hook provides access to the logged-in user. For example,
Might be good to link out to [User](https://www.mongodb.com/docs/realm-sdks/react/latest/classes/Realm.User.html) here so people can see what properties and methods are available.

2024-08-02 13:46 UTC, krollins-mdb requested changes
Overall, excellent work @osharaf-mdb! Thank you for working hard on this new page! 🥳 

I requested changes for a couple of reasons:

- There are some higher-level concepts that should be tweaked a bit
- Some leftovers from the original content should be generalized so that they're not specific to React Native. This is one of the not fun parts of moving content around. 😄

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +        The fallback component to render while the Realm is opening.
Or when the realm fails to open.

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +        Configures a synced realm.
A bit more detail might be helpful here. For example, this is where you set initial subscriptions. Something along these lines, perhaps?
```suggestion
        Defines Device Sync behavior for this realm, including initial subscriptions.
```

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +        Default is ``true``. If set to ``false``, realm will not close when the
```suggestion
        Default is ``true``. If set to ``false``, the open realm will not close when the
```

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +        Specifies the App ID.
We try to be specific about this because it's easy to get it confused with the app that devs are working on while reading the docs. We generally use capital A App to indicate this, but we haven't introduced the concept of an App Services App yet on this page, so that distinction is easily lost.

```suggestion
        Specifies the App Services App ID.
```

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +      If you are developing an app using sync, you will need to use all three Providers.
```suggestion
      If you are developing an app using Device Sync, you will need to use all three Providers. 
```

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +      <react-native-open-synced-realm-offline>`.
We should add a placeholder page to link to.

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +         a. Pass your App ID string to the ``id`` prop of the ``AppProvider``.
```suggestion
         a. Pass your App Services App ID string to the ``id`` prop of the ``AppProvider``. 
```

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +         a. Pass a component that logs a user in into the ``fallback`` prop. The app renders this component if there is no authenticated user.
The "in into" construction could be read like it's a mistake/typo. This might be easier to read:
```suggestion
         a. Pass a component that logs in a user to the ``fallback`` prop. The app renders this component if there is no authenticated user.
```

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +      4. Configure ``RealmProvider`` for sync and nest it within ``UserProvider``.
```suggestion
      4. Configure ``RealmProvider`` for Device Sync and nest it within ``UserProvider``.
```

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +         c. Add other Configuration object properties as props to ``RealmProvider``.
"Configuration": Either lowercase c or in monospace to indicate it's a code object.

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +         d. You must set up a sync subscription. The example below uses an initial subscription,
A minor clarification. Devs could build an app with Device Sync without any subscriptions. It would compile and run. But it wouldn't sync any data.
```suggestion
         d. You must set up a sync subscription to sync data. The example below uses an initial subscription,
```

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +      ``RealmProvider``. The rendering of each component is dependent on the successful
Minor clarification. You only have to nest the components that need access to the realm in `RealmProvider`. That's what the context is for. So, you could have a component outside `RealmProvider` but within `UserProvider` that can access info about the current user, but doesn't have access to the realm. And go up another level to have a component outside both `RealmProvider` and `UserProvider` but still has access to the App client.

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +
Ha! I hadn't noticed that the React docs use a capital H for Hooks. It can be weird what they decide are proper nouns.

@osharaf-mdb, generally, it's a good idea to follow the primary author's conventions - even if they're inconsistent - because that's what people who use the tech will be familiar with. So, on this page, we should have lowercase providers and uppercase Hooks. They're the same class of thing, but the React folks decided one needs to a proper noun the not the other. 😆

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +use in any wrapped component.
```suggestion
use in any wrapped component in the right context.
```

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +   :depth: 2
Yep. I love the thought, @osharaf-mdb and I've wanted to do this many times. Unfortunately, our docs tool chain can't handle it. 😢

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +         :emphasize-lines: 3-5, 8-14
Looks like the line emphasis is off. It's off in the original too. Probably my fault. 😞

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +      .. _react-native-use-realm-hook:
We don't want to use a React Native-specific ref here. This page should be generic. You'll need to update anything that points to this ref.

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +      <react-native-write-transactions>`.
We should add a placeholder page to link to.

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +      or the class name as a string and the primary key.
We should add a placeholder page to link to.

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +      refer to the :ref:`CRUD - Read <react-native-read-objects>` docs.
We should add a placeholder page to link to.

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +<react-native-expose-multiple-realms>`.
We should add a placeholder page to link to.

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +<react-native-expose-multiple-realms>`.
We should add a placeholder page to link to.

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +      .. _react-native-use-object-hook:
We don't want to use a React Native-specific ref here. This page should be generic. You'll need to update anything that points to this ref.

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +      .. _react-native-use-query-hook:
We don't want to use a React Native-specific ref here. This page should be generic. You'll need to update anything that points to this ref.

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +      .. _react-native-realm-context:
We don't want to use a React Native-specific ref here. This page should be generic. You'll need to update anything that points to this ref.

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +      .. _react-native-use-auth:
We don't want to use a React Native-specific ref here. This page should be generic. You'll need to update anything that points to this ref.

2024-08-02 13:46 UTC, krollins-mdb commented on source/frameworks/react/providers-hooks.txt
> +      .. _react-native-use-user-hook:
We don't want to use a React Native-specific ref here. This page should be generic. You'll need to update anything that points to this ref.

2024-08-07 16:31 UTC, closed without merging