DOCSP-41778 query size limit
mongodb/docs-realm pull request #3355
Opened 2024-08-02 15:10 UTC by osharaf-mdb

## Pull Request Info

Jira ticket: https://jira.mongodb.org/browse/DOCSP-41778

- [C++/Sync Data/Manage Sync Subscriptions](https://preview-mongodbosharafmdb.gatsbyjs.io/realm/DOCSP-41778-query-size-limit/sdk/cpp/sync/sync-subscriptions/#manage-your-subscriptions)
- [Flutter/Sync Device Data/Manage Subscriptions](https://preview-mongodbosharafmdb.gatsbyjs.io/realm/DOCSP-41778-query-size-limit/sdk/flutter/sync/manage-sync-subscriptions/#query-size-limit)
- [Java/Sync Data/Mange Flexible Sync Subscriptions](https://preview-mongodbosharafmdb.gatsbyjs.io/realm/DOCSP-41778-query-size-limit/sdk/java/sync/flexible-sync/#query-size-limit)
- [Kotlin/Sync Device Data/Manage Subscriptions](https://preview-mongodbosharafmdb.gatsbyjs.io/realm/DOCSP-41778-query-size-limit/sdk/kotlin/sync/subscribe/#query-size-limit)
- [.NET/Sync Data/Manage Flexible Sync Subscriptions](https://preview-mongodbosharafmdb.gatsbyjs.io/realm/DOCSP-41778-query-size-limit/sdk/dotnet/sync/flexible-sync/#query-size-limit)
- [Node.js//Sync Data/Manage Flexible Sync Subscriptions](https://preview-mongodbosharafmdb.gatsbyjs.io/realm/DOCSP-41778-query-size-limit/sdk/node/sync/flexible-sync/#query-size-limit)
- [Swift//Sync Data/Manage Flexible Sync Subscriptions](https://preview-mongodbosharafmdb.gatsbyjs.io/realm/DOCSP-41778-query-size-limit/sdk/node/sync/flexible-sync/#query-size-limit)

### Reminder Checklist

Before merging your PR, make sure to check a few things.

- [ ] Did you tag pages appropriately?
  - genre
  - programming_language
  - meta.keywords
  - meta.description
- [x] Describe your PR's changes in the Release Notes section
- [ ] Create a Jira ticket for related docs-realm work, if any

### Release Notes

- C++ SDK
  - Sync Data/Manage Sync Subscriptions: Add a warning about the query size limit when using Device Sync.

- Throughout the SDK Docs: Update the "Flexible Sync RQL Requirements and Limitations" section to include the query size limit when using Device Sync.

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-app-services/blob/master/REVIEWING.md)

2024-08-02 15:11 UTC, osharaf-mdb commented on source/sdk/cpp/sync.txt
> +client application.
```suggestion
client application. 
```

2024-08-02 16:41 UTC, dacharyc requested changes
Nice work on adding this to the right page for each SDK! But I think we need to refine where we put it on the pages, and also maybe verify some additional details with engineering so we can communicate the limit effectively in the SDK client context.

2024-08-02 16:41 UTC, dacharyc commented on source/includes/warning-device-sync-query-size-limit.rst
> +    **256 kB**. Exceeding this limit in a query will result in a :ref:`LimitsExceeded Error<flexible-sync-errors>`.
Same minor nitpick: our style guide calls for us to avoid future tense.
```suggestion
    **256 kB**. Exceeding this limit in a query results in in a :ref:`LimitsExceeded Error<flexible-sync-errors>`.
```

2024-08-02 16:41 UTC, dacharyc commented on source/sdk/cpp/sync/sync-subscriptions.txt
> +.. include:: /includes/warning-device-sync-query-size-limit.rst
I believe this include should come after the next paragraph - around line ~84. The `mutable_sync_subscription_set` is the structure that actually enables developers to add or change subscriptions, so that information is primary and this note about query size would be secondary to that information.

2024-08-02 16:41 UTC, dacharyc commented on source/sdk/dotnet/sync/flexible-sync.txt
> +.. include:: /includes/warning-device-sync-query-size-limit.rst
I think this is a reasonable place to put this! But I also wanted to flag an alternative: most of these pages have a "Flexible Sync RQL Requirements and Limitations" section, where we could add a new subsection for "Query Size Limit" and provide this information. It would make sense to keep the limitations together in an include we're using across most of these Manage Sync Subscriptions pages.

This isn't such a big deal here, but some of the other pages have multiple query APIs, so finding the right place to provide this callout on those other pages is more difficult. Moving this to the "Limitations" section would keep it consistent.

2024-08-02 16:41 UTC, dacharyc commented on source/sdk/flutter/sync/manage-sync-subscriptions.txt
> +.. include:: /includes/warning-device-sync-query-size-limit.rst
I don't think this is the right place for this callout on the Flutter page. The "Subscribe to Queries" and "Manually Manage Queries" sections on this page actually represent two different APIs and two different ways to add queries. If we add this callout here, we should _also_ add it to the "Manually Manage Subscriptions/Add a Query" section, as it applies to both APIs. 

Moving this to the "Flexible Sync RQL Limitations" as a section there would sidestep this issue, and would be an alternative to listing it in both places on the page.

2024-08-02 16:41 UTC, dacharyc commented on source/sdk/java/sync/flexible-sync.txt
> +.. include:: /includes/warning-device-sync-query-size-limit.rst
I would put this after the code example, even though it means stacking callouts. The code example is part of the primary information in the section, and this warning is secondary. Alternately, if we moved this info to the "Flexible Sync RQL Limitations" section, we could remove it from here entirely.

2024-08-02 16:41 UTC, dacharyc commented on source/sdk/kotlin/sync/subscribe.txt
> +.. include:: /includes/warning-device-sync-query-size-limit.rst
Same issue here as in the Flutter page - the "Subscribe to Queries" and "Manually Manage Subscriptions" sections represent two different APIs, so we would either need to include this warning in _both_ places or move it to the "Flexible Sync RQL Requirements and Limitations" section.

Same thing applies to the remaining pages here - Node, React Native, and Swift.

2024-08-02 16:41 UTC, dacharyc commented on source/includes/warning-device-sync-query-size-limit.rst
> +    **256 kB**. Exceeding this limit in a query will result in a :ref:`LimitsExceeded Error<flexible-sync-errors>`.
I have a question about this info that we may need to verify with engineering. The message here is "size limit for queries." From the SDK side, the subscription set may contain multiple queries. i.e. I might have a query for `Dog` objects and a query for `Person` objects. So do we mean that each subscription in the subscription set must be under 256KB, or does the server treat the subscription set as a combined "query" for the size limit purposes, and so the entire subscription set must be under 256 KB? We should clarify the details with engineering and then refine the wording here.

2024-08-06 17:23 UTC, osharaf-mdb commented on source/includes/warning-device-sync-query-size-limit.rst
> +    **256 kB**. Exceeding this limit in a query will result in a :ref:`LimitsExceeded Error<flexible-sync-errors>`.
I checked with Engineering and they confirmed that the size limit is for each individual subscription. I updated the wording to be:

The **size limit** for a subscription to a query from your client application is **256 kB** when using Device Sync.

2024-08-06 17:51 UTC, osharaf-mdb commented on source/sdk/dotnet/sync/flexible-sync.txt
> +.. include:: /includes/warning-device-sync-query-size-limit.rst
This was a great idea! I added the warning to the Limitations include and will be removing the warning from pages that display the limitations

2024-08-06 19:08 UTC, dacharyc requested changes
Thanks for clarifying that detail with engineering! I think we could do a little more tweaking of the wording to remove some unnecessary wordiness and be clearer about the distinction of an individual query size vs. the size of the subscription set.

2024-08-06 19:08 UTC, dacharyc commented on source/includes/flex-sync-limitations.rst
> +when using Device Sync. Exceeding this limit results in a
This still reads a little confusing to me. If I have correctly understood that the size limit is *per query in the subscription set*, not the total subscription set, we might want to reword a little just for clarity:

We don't need to say "when using Device Sync" because we're on the subscription query page where it's understood (hopefully!) that we're talking about Sync subscriptions. And we don't need to say "from your client application" because we're in the SDK client docs.

We should also update the wording on the C++ page once we're happy with this one.

```suggestion
The **size limit** for any given query in your subscription set is
**256 kB**. Exceeding this limit results in a
```

2024-08-06 20:20 UTC, dacharyc approved these changes
LGTM! ✅

2024-08-06 21:20 UTC, merged