Consolidation Providers and Hooks
mongodb/docs-realm pull request #3356
Opened 2024-08-05 09:35 UTC by osharaf-mdb

**##** Pull Request Info - SDK Docs Consolidation

Jira ticket: https://jira.mongodb.org/browse/DOCSP-NNNNN

*Staged Page*

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

*Page Source*

Add links to every SDK's pages where you got the SDK-specific information:

- [PAGE_NAME](https://www.mongodb.com/docs/atlas/device-sdks/LIVE-DOCS-LINK)

### PR Author Checklist

Before requesting a review for your PR, please check these items:

- [ ] Open the PR against the `feature-consolidated-sdk-docs` branch instead of `master`
- [ ] Tag the consolidated page for:
  - genre
  - meta.keywords
  - meta.description

#### Naming
- [ ] Update Realm naming and the language around persistence layer/local/device per [this document](https://docs.google.com/document/d/126OczVxBWAwZ4P5ZsSM29WI3REvONEr1ald-mAwPtyQ/edit?usp=sharing)
- [ ] Include `.rst` files comply with [the naming guidelines](https://docs.google.com/document/d/1h8cr66zoEVeXytVfvDxlCSsUS5IZwvUQvfSCEXNMpek/edit#heading=h.ulh8b5f2hu9)

#### Links and Refs
- [ ] Create new consolidated SDK ref targets starting with "_sdks-" for relevant sections
- [ ] Remove or update any SDK-specific refs to use the new consolidated SDK ref targets
- [ ] [Update any Kotlin API links](https://jira.mongodb.org/browse/DOCSP-32519) to use the new Kotlin SDK roles

#### Content
- [ ] Shared code boxes have snippets or placeholders for all 9 languages
- [ ] API description sections have API details or a generic placeholder for all 9 languages
- [ ] Check related pages for relevant content to include
- [ ] Create a ticket for missing examples in each relevant SDK: Consolidation Gaps epic

### Reviewer Checklist

As a reviewer, please check these items:

- [ ] Shared code example boxes contain language-specific snippets or placeholders for every language
- [ ] API reference details contain working API reference links or generic content
- [ ] Realm naming/language has been updated
- [ ] All relevant content from individual SDK pages is present on the consolidated page

2024-08-06 15:01 UTC, krollins-mdb approved these changes
Nice job, @osharaf-mdb! Thanks for all of the hard work you put into this page! LGTM. 🎊 

There are some build errors you should look at though. See the Netlify logs here: https://app.netlify.com/sites/device-sdk/deploys/66b1acaec55e1b00087de096#L405-L423

2024-08-07 07:54 UTC, gagik approved these changes
Great job, great improvements! Some minor comments you could consider:

2024-08-07 07:54 UTC, gagik commented on source/frameworks/react/providers-hooks.txt
> +``RealmProvider`` context is the database it connects to, so all components nested in the
"Realm instance" or "Realm database" would be more descriptive.

2024-08-07 07:54 UTC, gagik commented on source/frameworks/react/providers-hooks.txt
> +      - ``children: React.ReactNode``
would you like to also describe the possibility to pass `realm` `app` as props? 
This is currently undocumented as it is new but people have usecases for this:
https://github.com/realm/realm-js/issues/6283
https://github.com/realm/realm-js/issues/6785

It may complicate the docs, so kind of up to where you'd want this information to be.

2024-08-07 07:54 UTC, gagik commented on source/frameworks/react/providers-hooks.txt
> +      sync properties are formatted like a JSON dictionary.
sync properties are defined by an object of type `SyncConfiguration`; if you can't link it to the type, I'd describe it something like "sync properties are defined by an object with different configuration fields".

JSON was inspired by the object structure in JavaScript so calling an object formatted like JSON sounds a bit weird to me.

2024-08-07 07:54 UTC, gagik commented on source/frameworks/react/providers-hooks.txt
> +   ``RealmProvider`` to ensure they have access to all three providers' contexts.
but you may also need to make sure this RealmProvider is also nested under User/App for sync right? might be worth mentioning

2024-08-07 07:54 UTC, gagik commented on source/frameworks/react/providers-hooks.txt
> +execution of its parent components' functionality. For example, if ``AppProvider`` cannot
RealmProvider has a fallback component which gets rendered instead which may be worth mentioning here.

Not released yet but we're also working on adding progress information to this fallback: https://github.com/realm/realm-js/pull/6801

2024-08-07 11:24 UTC, kneth approved these changes
Nice work!

2024-08-07 11:24 UTC, kneth commented on source/frameworks/react/providers-hooks.txt
> +        Default is ``true``. If set to ``false``, the open datahase will not close when the
Do we want to mention the scenarios where `false` is a good value?

2024-08-07 11:24 UTC, kneth commented on source/frameworks/react/providers-hooks.txt
> +The ``useRealm()`` Hook returns an opened :js-sdk:`database instance<classes/Realm-1.html>`. The database instance
Neat that you write "Hook" and not "hook" as in the official React documentation 👍🏻

2024-08-07 11:24 UTC, kneth commented on source/frameworks/react/providers-hooks.txt
> +     - ``credentials``: An Atlas credential supplied by any supported Atlas authentication.
```suggestion
     - ``credentials``: An Atlas credential supplied by any supported Atlas App Services authentication provider.
```

2024-08-07 11:24 UTC, kneth commented on source/frameworks/react/providers-hooks.txt
> +     - Logs in a user with any authentication mechanism supported by Atlas. If called when a
```suggestion
     - Logs in a user with any authentication mechanism supported by Atlas App Services. If called when a
```

2024-08-07 15:37 UTC, dacharyc requested changes
Nice work, Omar! I love it.

I'm requesting changes for a couple of typos I've called out here - we should definitely fix those before merging. I've also left feedback about some more subjective changes, but feel free to take or leave those suggestions - if it's not a typo, it's not blocking.

2024-08-07 15:37 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +- :realm-react-sdk:`AppProvider (@realm/react) <functions/AppProvider.html>`
On the prior version of this page, we had a short description of what each provider was used for. That was helpful for folks who don't know our functionality well and don't necessarily understand from the provider name what something like "App" and "Realm" might be referring to. (App in particular is a really generic term, and I wouldn't automatically assume that an AppProvider was used to manage a connection to Atlas.)

I'm curious why we removed the descriptions here.

Also, as a note, we probably _don't_ want to add a lot of links at the top of the page that take the users _off_ the page without making it clear that's what we're doing. In coming to this page, I would have assumed these links take me to somewhere on the page where I can learn more about the specific provider, since there is no description provided here. I would suggest we handle this in one of a few ways:

- Instead of linking off the page, link to somewhere on the page where we describe what each provider is for and how you use it. You could link out to the API reference from there for people who want more info.
- Keep the links as-is, and add "API Reference" to the link text to make it clearer you're going off to a different page - i.e. `AppProvider API Reference (@realm/react) <link>`
- Remove the links entirely, and just add a short description of what each provider is for. Let users go to the relevant section - props or hooks - and get linked out to the API reference from there where it is contextually relevant.

2024-08-07 15:37 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +.. note:: Exposing more than one database using createRealmContext()
I would probably move this note to _below_ the example. We're already asking the reader to go through a lot of text before they get to see example code. This seems like information that is secondary to showing the example - i.e. conceptually - now you've seen how to do this in general, if you need to use more than one database, go to this other part of the page.

2024-08-07 15:37 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +      - ``sync?: SyncConfiguration``
SyncConfiguration is a pretty complex object, and since we _want_ people to use Sync as a default, we might consider linking out to it here.

2024-08-07 15:37 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +Your app's needs determine what providers you use, as all three providers are not always
This seems like good information to also include at the top of the page, where we list the three providers.

2024-08-07 15:37 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +   Once your providers have been configured, nest your app components within the
If you want this to be a description under the number heading, instead of just a part of the number heading (which I think would be easier to read and it looks like that's what you're going for!) then you'll need to add an empty line here.

Also, small typo - "Nest you" should be "Nest your".
```suggestion
5. Nest your app components in the providers.

   Once your providers have been configured, nest your app components within the
```

2024-08-07 15:37 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +   * - logInWithApiKey
I'm generally ok with the wrapping, but this method where we're wrapping one character just looks really odd to me. I notice a few places below we're wrapping 1, 2, or 3 characters. 

I notice some of the code blocks in the table require scrolling even at the current table width. It seems like the `// user defined function` text is what's requiring most of the code blocks to scroll. I wonder if we can remove that comment - maybe move the comment to the line above or below, or mention above the table that the `getAPIKey` or `getToken` functions are user-defined. IF we can remove this `user-defined function` text, I think we can make the third column a little narrower and give this first column a little more space so we're not wrapping single characters.

2024-08-07 15:37 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +         const key = getApiKey(); // user defined function
This is just a Q - I don't know React so I don't know the indentation conventions here. But since we're inside a closure, should the const in this stanza be indented? i.e.:

```typescript
const performLogin = () => {
     const key = getApiKey(); // user defined function
     logInWithApiKey(key);
};
```

(Same question applies in each example below where we're defining a `const` in closures to get the relevant tokens.)

2024-08-07 15:37 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +Most of the time, you will only use ``createRealmContext()`` if you need to
Our style guide calls for us to avoid future tense, so I'd say we should remove the "will" here. But we can also trim this to be much more concise:
```suggestion
Use ``createRealmContext()`` to
```

2024-08-07 15:37 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +configure more than one database. Otherwise, you should import ``RealmProvider``
We can simplify here by removing the "you should."
```suggestion
configure more than one database. Otherwise, import ``RealmProvider``
```

2024-08-07 15:37 UTC, dacharyc commented on source/frameworks/react/providers-hooks.txt
> +imported from the ``@realm/react`` library. You should namespace providers
The use of "you should" weakens the writing. Just make the recommendation - it's more authoritative.
```suggestion
imported from the ``@realm/react`` library. Namespace your providers
```

2024-08-09 13:27 UTC, dacharyc approved these changes
LGTM - awesome work, @osharaf-mdb ! 🎉 🚀 :shipit:

2024-08-09 21:30 UTC, merged