(DOCSP-11835): Clarify Partition Key handling on Client-side vs. Server-side
mongodb/docs-realm pull request #445
Opened 2020-09-09 19:46 UTC by llazala000

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-11835

### Docs staging link (requires sign-in on MongoDB Corp SSO):
Still waiting on MANA requests to be approved

2020-09-09 20:00 UTC, ccho-mongodb approved these changes
LGTM, a couple nitpicks.

2020-09-09 20:00 UTC, ccho-mongodb commented on source/sync/partitioning.txt
> +  will be sent to the null partition by default.
Nitpick: when qualifying with "by default", I might expect to also see a case in which the behavior could be overridden. Is that the case here? Otherwise, you might consider omitting "by default".

2020-09-11 01:49 UTC, nlarew requested changes
A few nitpicks on the partitioning page + let's mirror this to the other versions of the Define Sync Rule procedure

2020-09-11 01:49 UTC, nlarew commented on source/sync/partitioning.txt
> +  sent to the null partition.
A few nitpicks here:

- > Partition key fields should be made required...

  In general our style prefers [active voice](https://docs.mongodb.com/meta/style-guide/writing/use-active-voice/), so let's rephrase a bit to answer "made required _by whom?_"

  ```rst
  You can configure your app to treat partition keys as either optional or required.
  ```

- We should also describe what happens to documents that exclude or have a null partition key when partition keys are required

- A reader might ask "what is the null partition?" Can we either clear that up here or add a glossary entry (in `source/get-started/glossary.txt`) and reference it here (`` :term:`null partition` ``). e.g. it's the default realm on the client device

2020-09-11 01:49 UTC, nlarew commented on source/includes/steps-define-sync-rules-ui.yaml
> +  partition keys and how to choose one, see
Can we make it a bit clearer that "should" here is just our default/general suggestion? Maybe we could move this out of the paragraph and into a `.. note::` right below the paragraph.

2020-09-11 14:09 UTC, llazala000 commented on source/includes/steps-define-sync-rules-ui.yaml
> +  partition keys and how to choose one, see
Should I move just the general suggestion out to a note? Or should I move the description of the partition key handling out too?

2020-09-11 17:02 UTC, nlarew commented on source/includes/steps-define-sync-rules-ui.yaml
> +  partition keys and how to choose one, see
Not totally sure what you mean by "partition key handling" but I was referring just to the new text, i.e.

"Partition key fields should be made required through the {+Realm+} UI. If the partition key field is optional, then all documents that either exclude the partition key or have a null value for the partition key will be sent to the null partition."

2020-09-11 17:28 UTC, llazala000 commented on source/includes/steps-define-sync-rules-ui.yaml
> +  partition keys and how to choose one, see
Gotcha

2020-09-14 17:47 UTC, nlarew commented on source/includes/steps-define-sync-rules-ui.yaml
> +    Partition key fields should be made required. If the partition key field is
This is passive voice - partition key fields should be made required _by whom?_ Let's make it a bit more active! 

Also, I think we can (1) more explicitly call out that this is our recommendation (2) give a bit more context on why we recommend this (3) move the recommendation to the end of the note so that readers have some context. Thoughts?

"The partition key field can either be required or optional. [If optional... If required...] We recommend a required partition key unless your application specifically needs access to unpartitioned documents."

2020-09-14 17:47 UTC, nlarew commented on source/sync/partitioning.txt
> +  required,
Looks like we're missing the end of the sentence here

2020-09-15 22:12 UTC, nlarew approved these changes
LGTM % one last update to include

Let's get a review from Ian on this too

2020-09-15 22:12 UTC, nlarew commented on source/includes/steps-define-sync-rules-ui.yaml
> +    application specifically needs access to unpartitioned documents.
Can we add this note to the step files for the other interfaces (i.e. CLI & API)?

- source/includes/steps-define-sync-rules-cli.yaml
- source/includes/steps-define-sync-rules-api.yaml

2020-09-15 23:33 UTC, ianpward commented on source/includes/steps-define-sync-rules-ui.yaml
> +    application specifically needs access to unpartitioned documents.
> We recommend a required partition key unless your 
    application specifically needs access to unpartitioned documents. 

I'm not sure I would use this phrasing - since any documents will be partitioned just in the nil partition. The use case for nil partitions is more for the case where a user has pre-existing data in their MongoDB and wants to sync data on documents that may not have that field in it or may not have a valid value in it. Asking them to refactor and change their data might be a big ask

2020-09-16 18:18 UTC, nathan-contino-mongo approved these changes
LGTM with one caveat: I think we should use the term "MongoDB documents" instead of "documents" because (particularly in the "partitioning" page) this will make it clearer that this refers to data originating in Atlas, rather than client-side applications.

2020-09-16 18:18 UTC, nathan-contino-mongo commented on source/get-started/glossary.txt
> +      A null partition is the default :term:`{+service-short+}` on the client
```suggestion
      A null partition is the default :term:`{+realm+}` on the client 
```

We actually use the substitution realm for the word realm just in case they change the name in the future :)

2020-09-16 18:18 UTC, nathan-contino-mongo commented on source/get-started/glossary.txt
> +      A null partition is the default :term:`{+service-short+}` on the client
service-short gives you capital R realm, which is the service itself. Far too many things are named Realm here!

2020-09-16 18:18 UTC, nathan-contino-mongo commented on source/includes/steps-define-sync-rules-ui.yaml
> +    the partition key. We recommend a required partition key unless your
I think we need to clarify that this refers to documents in MongoDB, since some users might not recognize that Realm uses objects and MongoDB uses documents (even I did a short double-take here to make sure I understood). Suggestion: use the term "MongoDB documents" throughout this note?

2020-09-16 18:18 UTC, nathan-contino-mongo commented on source/sync/partitioning.txt
> +  required, {+sync+} will ignore any documents that lack a valid value for
```suggestion
  required, {+sync+} ignores any MongoDB documents that lack a valid value for 
```
Both here and in the above usage of "document" I think it would help users to use the term "MongoDB documents" so they don't confuse this with client-side behavior. Also, prefer active voice when possible (which I know can be a huge pain when we're writing about theoretical scenarios like "if x is y, z..")

2020-09-16 18:18 UTC, nathan-contino-mongo commented on source/sync/partitioning.txt
> +  required. If the partition key field is designated as optional, all documents
documents -> MongoDB documents

2020-09-16 18:18 UTC, nathan-contino-mongo commented on source/includes/steps-define-sync-rules-ui.yaml
> +    field is optional, then all documents that either exclude the partition
documents -> MongoDB documents

2020-09-16 19:23 UTC, merged