(DOCSP-11287, 10812): Document Sync Protocol + Clarify Billing
mongodb/docs-realm pull request #486
Opened 2020-09-24 23:56 UTC by nlarew

## Pull Request Info

### Issue JIRA link:

- (DOCSP-11287): Document Sync Protocol Details
- (DOCSP-10812): Add more detail on billing for Realm Requests for Sync Operations

### Docs staging link (requires sign-in on MongoDB Corp SSO):

- [Realm Sync Protocol](https://docs-mongodbcom-staging.corp.mongodb.com/realm/nlarew/sync-protocol/sync/protocol.html)

2020-09-25 04:03 UTC, ianpward commented on source/includes/steps-sync-protocol.yaml
> +  To begin a sync session, a Realm SDK sends a :sync-client-message:`BIND`
so I know this is for the sync-protocol but the first thing a client must do is authenticate and get a valid token which can then be used open a websocket sync connection with a BIND message - should we call that out here or would that be better in another doc?

2020-09-25 04:06 UTC, ianpward commented on source/includes/steps-sync-protocol.yaml
> +  specific local Realm file to sync and includes a WebSocket connection key that
should we spell out how the the websocket is actually established? something like this - https://docs.realm.io/server/-Lrk2at2AQQPwaKdjheq/configure/learn-realm-sync-and-integrate-with-a-proxy

2020-09-25 04:08 UTC, ianpward commented on source/sync/protocol.txt
> +other clients. The {+service-short+} sync server accepts changesets from any
including mongodb driver mutations

2020-09-25 04:11 UTC, ianpward commented on source/sync/protocol.txt
> +   previously uploaded changesets.
I don't understand why we are mentioning this as important for the user to understand? do you mean the history version here? I think this is sync just making sure that changesets are only applied once, idempotent, across the wire

2020-09-25 19:16 UTC, nlarew commented on source/includes/steps-sync-protocol.yaml
> +  To begin a sync session, a Realm SDK sends a :sync-client-message:`BIND`
We should definitely call out that a sync session requires an authenticated user's valid access token, I'll find a spot on this page that feels good

2020-09-25 19:19 UTC, nlarew commented on source/includes/steps-sync-protocol.yaml
> +  To begin a sync session, a Realm SDK sends a :sync-client-message:`BIND`
To be clear - does the sync protocol use the same auth process/access tokens as e.g. `app.logIn()` or is it a separate system? The [Proxy Integration](https://docs.realm.io/server/-Lrk2at2AQQPwaKdjheq/configure/learn-realm-sync-and-integrate-with-a-proxy) page you linked makes it seem like they're separate systems.

2020-09-25 19:24 UTC, nlarew commented on source/includes/steps-sync-protocol.yaml
> +  specific local Realm file to sync and includes a WebSocket connection key that
Ah yeah I think I initially missed the HTTP Request and HTTP Response since they have very generic names. I can add that the WS connection is established over HTTP before any of the other protocol messages can be sent

2020-09-25 19:25 UTC, nlarew commented on source/sync/protocol.txt
> +   previously uploaded changesets.
Probably better to summarize as "idempotent", I'll update

2020-09-25 19:26 UTC, nlarew commented on source/includes/steps-sync-protocol.yaml
> +  specific local Realm file to sync and includes a WebSocket connection key that
Separately we may want to have another page on proxied requests, if it's still relevant

2020-09-28 21:31 UTC, ianpward commented on source/includes/steps-sync-protocol.yaml
> +  To begin a sync session, a Realm SDK sends a :sync-client-message:`BIND`
it uses the same system as app.LogIn() - which I believe is covered here:
https://docs.mongodb.com/realm/reference/authenticate-http-client-requests/index.html#get-a-client-api-access-token

2020-09-28 21:33 UTC, ianpward commented on source/includes/steps-sync-protocol.yaml
> +  specific local Realm file to sync and includes a WebSocket connection key that
I actually don't think we can integrate with a proxy in the new Realm Sync - id have to check with the server team

2020-09-29 00:52 UTC, ccho-mongodb requested changes
Overall looks pretty good. I have a number of questions on the content as it wasn't completely clear after reading through it. Also, there are a few typos. You can use a tool like aspell or one of its variants to catch these.

2020-09-29 00:52 UTC, ccho-mongodb commented on source/includes/steps-sync-protocol.yaml
> +  message that contains the client file identifier. If the identifier is valid,
Nitpick: it could be useful to expand on what conditions qualify it to be valid. Is a Realm name supplied in the request and does that have to match?

2020-09-29 00:52 UTC, ccho-mongodb commented on source/includes/steps-sync-protocol.yaml
> +  Once a sync session is established, the SDK can send and recieve
recieve -> receive

2020-09-29 00:52 UTC, ccho-mongodb commented on source/includes/steps-sync-protocol.yaml
> +  server's history and the SDK applies the changesets in the same order.
Nitpick: I think a "," before the "and" could help break up this sentence. Alternatively, you could rewrite this as two sentences.

2020-09-29 00:52 UTC, ccho-mongodb commented on source/sync/protocol.txt
> +.. _changeset:
I think this may apply if you're prepping for nextgen (anchors shouldn't be named the same as titles):
https://jira.mongodb.org/browse/DOP-1532?focusedCommentId=3414748&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3414748

2020-09-29 00:52 UTC, ccho-mongodb commented on source/sync/protocol.txt
> +operation and the server sends each client changesets for operations executed by
Question: does this server changeset sent to the client include anything other than write operations? If not, then maybe it would be more clear to refer to them as write operations instead.

2020-09-29 00:52 UTC, ccho-mongodb commented on source/sync/protocol.txt
> +time and uses an operational transformation algorithm to serialize changes and
Question: Is this "serialize" conversion of the data to another format or ordering of the data? I think it could be important to specify which one.

2020-09-29 00:52 UTC, ccho-mongodb commented on source/sync/protocol.txt
> +   An operational transformation on {+service-short+} changesets is analagous to
analagous -> analogous

2020-09-29 00:52 UTC, ccho-mongodb commented on source/sync/protocol.txt
> +{+service-short+} file. Each identifier is a  64-bit, non-zero, positive signed
There's an extra space here before "64-bit"

2020-09-29 00:52 UTC, ccho-mongodb commented on source/sync/protocol.txt
> +To initiate, execute, and terminate a {+service-short+} Database sync session, a
Question: Is Realm Database a product name or should Database be lowercase?

2020-09-29 00:52 UTC, ccho-mongodb commented on source/sync/protocol.txt
> +       |  <-------- 3. IDENT* ----------  |
Question: did you intend to explain why the Server's IDENT request has a "*"?

2020-09-29 00:52 UTC, ccho-mongodb commented on source/sync/protocol.txt
> +       client {+realm+}'s current version.
Question 1: Is this true for the "IDENT*" request from the server as well?

Question 2: Is this the client's SDK version or the changeset version? I think it's the latter, but had to read further down to figure that out.

Question 3: Is there a description about the changeset versions somewhere? Is it monotonically increasing? could be good info in the Changeset section. Comment applies to both Client and Server message descriptions.

2020-09-29 00:52 UTC, ccho-mongodb commented on source/sync/protocol.txt
> +   Realm SDK                      Realm App Server
Nice diagram!

2020-09-29 00:52 UTC, ccho-mongodb commented on source/sync/protocol.txt
> +       commonly used to execute a client reset.
Question: is a client reset when it requests the first changeset version?

2020-09-29 00:52 UTC, ccho-mongodb commented on source/sync/protocol.txt
> +       end the session.
Question: does this happen regardless of any other type of request being sent by the client during the 10 minutes? Could you mention which one is the case here?

2020-09-29 00:52 UTC, ccho-mongodb commented on source/sync/protocol.txt
> +     - Acknowledges a :sync-client-message:`PING`.
Question: Does a client ever timeout its connection with a server if it doesn't receive the PONG?

2020-09-29 00:52 UTC, ccho-mongodb commented on source/includes/steps-sync-protocol.yaml
> +  The server sends an :mdn`HTTP 101 Switching Protocols <Web/HTTP/Status/101>`
`:mdn` -> `:mdn:`

2020-09-29 00:52 UTC, ccho-mongodb commented on source/includes/steps-sync-protocol.yaml
> +  then the server establishes the session and begins to send and receieve sync
receieve -> receive

2020-09-29 00:52 UTC, ccho-mongodb commented on source/sync/protocol.txt
> +changesets to the {+service-short+} server whenever they perfrom a write
perfrom -> perform

2020-09-29 00:52 UTC, ccho-mongodb commented on source/sync/protocol.txt
> +{+service-short+} file to eachother via :sync-client-message:`UPLOAD` and
eachother -> each other

2020-09-29 00:52 UTC, ccho-mongodb commented on source/sync/protocol.txt
> +       occured on the client. The changesets are listed by client version in
occured -> occurred
(multiple instances)

2020-09-29 16:35 UTC, nlarew commented on source/sync/protocol.txt
> +To initiate, execute, and terminate a {+service-short+} Database sync session, a
It's a product name afaik

2020-09-29 17:01 UTC, nlarew commented on source/sync/protocol.txt
> +       client {+realm+}'s current version.
Lol I deleted some content to this effect in response to one of Ian's comments. Maybe I can re-introduce with a slightly different angle.

2020-09-29 17:35 UTC, ccho-mongodb approved these changes
LGTM!

2020-09-30 16:05 UTC, merged