WIP- (DOCSP-11147): Initted Realm Electron Quickstart Doc
mongodb/docs-realm pull request #494
Opened 2020-09-29 18:49 UTC by mongomoe

Work in Progress - **Do Not Merge**

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-11147

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-11147-Realm-Electron-QuickStart/node/electron.html

2020-10-02 21:13 UTC, cbush requested changes
Good work! I think the layout of the doc is pretty good. Research seems thorough and I think people will get good use out of it.

I went ahead and added a ton of suggestions to save you some time on some punctuation fixes. Please ask if you have any questions about my suggestions.

What needs to change:
- Please accept suggestions.
- Please move the code snippets into literalincludes. This is going to happen soon anyway so let's save ourselves the tech debt.
- Please move the setup headers into a subsection specifically for setup. I'm concerned the "Working Realm Using Renderer and Main Processes" section is getting lost otherwise.
- Please add a note or paragraph or sentence near the top that helps people decide which of the setup sections to read. You could also have a sentence in each setup section that lets people know whether they should read that section or if they can skip it. It's not clear from the section titles alone right now.
- Please write a summary section.

Thanks!

2020-10-02 21:13 UTC, cbush commented on source/node/electron.txt
> +On line 27, a non-synced realm is opened in this rendere r process. All
```suggestion
On line 27, a non-synced realm is opened in this renderer process. All
```

2020-10-02 21:13 UTC, cbush commented on source/node/electron.txt
> +
This page could use a summary.

2020-10-02 21:13 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  To allow your application to work properly with electron you have to
```suggestion
  To allow your application to work properly with Electron, you have to
```

2020-10-02 21:13 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  to the end user. Using CRACO you can override these default
Link to CRACO?

2020-10-02 21:13 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  to the end user. Using CRACO you can override these default
>to the end user.

You could explain that unfortunately, this is not compatible with Realm and needs to be overridden.

2020-10-02 21:13 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  and the electron-devtools and included in the bundle. In order to make
```suggestion
  and the electron-devtools are included in the bundle. In order to make
```

2020-10-02 21:13 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  Install electron as a devDependency in order to run your application
```suggestion
  Install Electron as a devDependency in order to run your application
```

2020-10-02 21:13 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  from a chromium desktop window using Electron. Run the following
This is a bit awkward. Surely people know what they're installing Electron for. Why not just say:

>To add Electron to your project, run the following command:

2020-10-02 21:13 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  The electron ``main process`` file can be thought of as the entry
```suggestion
  The Electron ``main process`` file can be thought of as the entry
```

2020-10-02 21:13 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +     Each electron application can only have one ``main process``. The
```suggestion
     Each electron application can only have one **main process**. The
```

2020-10-02 21:13 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +     main process can create web pages, and each web page runs in it's
```suggestion
     main process can create web pages. Each web page runs in its
```

2020-10-02 21:13 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +     own process, known as the ``renderer process``. To learn more about
```suggestion
     own process, known as a **renderer process**. To learn more about
```

2020-10-02 21:13 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +     this read the official `Electron Application
```suggestion
     this, read the official `Electron Application
```

2020-10-02 21:13 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  .. code-block:: javascript
Can you move this to a literalinclude?

2020-10-02 21:13 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  Use realm in the main process by adding the following to the top of the ``public/electron.js`` file (you will also need to require it in whichever file you write code using Realm in):
I would remove that parenthetical:
```suggestion
  Use Realm in the main process by adding the following to the top of the ``public/electron.js`` file:
```

2020-10-02 21:13 UTC, cbush commented on source/node/electron.txt
> +write transactions on this local realm, will not be synced by default. In order to sync these writes, the `ipcRenderer <https://www.electronjs.org/docs/api/ipc-renderer>` Electron API is used to emit
Broken link:
```suggestion
write transactions on this local realm, will not be synced by default. In order to sync these writes, the `ipcRenderer <https://www.electronjs.org/docs/api/ipc-renderer>`__ Electron API is used to emit an "asynchronous-message" with the arguement "sync" on line 40. This tells our ``main process`` to upload all local changes to the synced realm. 
```

2020-10-05 17:22 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  .. code-block:: javascript
done 👍

2020-10-05 17:22 UTC, mongomoe commented on source/node/electron.txt
> +write transactions on this local realm, will not be synced by default. In order to sync these writes, the `ipcRenderer <https://www.electronjs.org/docs/api/ipc-renderer>` Electron API is used to emit
Thanks for pointing this out - fixed

2020-10-05 17:59 UTC, mongomoe commented
@cbush per your top level comment ("Please accept suggestions.
Please move the code snippets into literalincludes. This is going to happen soon anyway so let's save ourselves the tech debt.
Please move the setup headers into a subsection specifically for setup. I'm concerned the "Working Realm Using Renderer and Main Processes" section is getting lost otherwise.
Please add a note or paragraph or sentence near the top that helps people decide which of the setup sections to read. You could also have a sentence in each setup section that lets people know whether they should read that section or if they can skip it. It's not clear from the section titles alone right now.
Please write a summary section."):

* Moved code snippets into literalincludes: ✅  (only moved the codesnippets that were full js files) 
* Moved the setup headers into subsections: ✅ 
* Added a paragraph at the top that helps people decide which setup to read & added a sentence in each set up subsection: ✅ 
* Added a summary:  ✅

2020-10-05 19:47 UTC, mongomoe commented on source/node/electron.txt
> +- Since a non-synced realm is opened on the renderer process, the main process must be notified when a write transaction happens during the renderer process.
Hmm, I prefer this current approach of:

- <challenge>, <solution> 

Where we present two challenges (2 diff processes can't access a synced realm, and a non-synced realm is opened on a renderer process). I think separating the two lists might dilute the fact that a synced realm can be opened on a renderer process (but is not recommended, due to the first bullet). What do. you think?

2020-10-05 19:47 UTC, mongomoe commented on source/node/electron.txt
> +Working Realm Using Renderer and Main Processes
Fixed

2020-10-05 19:48 UTC, mongomoe commented on source/node/electron.txt
> +.. include:: /includes/steps/realm-with-electron.rst
Added an intro sentence to these subsections

2020-10-05 19:48 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  from a chromium desktop window using Electron. Run the following
that does sound better, fixed 👍

2020-10-05 19:48 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  to the end user. Using CRACO you can override these default
yup that makes sense, done 👍

2020-10-05 19:48 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  to the end user. Using CRACO you can override these default
added 👍

2020-10-05 19:51 UTC, mongomoe commented on source/node/electron.txt
> +will be uploaded to the synced realm.
Good catch - fixed now

2020-10-05 20:09 UTC, cbush commented on source/node/electron.txt
> +- Since a non-synced realm is opened on the renderer process, the main process must be notified when a write transaction happens during the renderer process.
This section is not clear as is. Please rework it.

2020-10-06 13:46 UTC, cbush approved these changes
Looks good. Please accept suggestions before merging. Thanks!

2020-10-06 13:46 UTC, cbush commented on source/includes/steps-realm-with-electron.yaml
> +  electron API. Copy the following code into your ``main.js`` file:
```suggestion
  Electron API. Copy the following code into your ``main.js`` file:
```

2020-10-06 13:46 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  In order to run your application, specify a homepage and a main entry point for electron by adding the following to your ``package.json`` file:
```suggestion
  In order to run your application, specify a homepage and a main entry point for Electron by adding the following to your ``package.json`` file: 
```

2020-10-06 13:46 UTC, cbush commented on source/node/electron.txt
> +- Two different processes cannot access a synced realm. Due to this, the recommended course of action is to open a non-synced realm on renderer processes and open a synced realm on the main process.
This is still not as clear as it could be. At the very least:
```suggestion
- Two different processes cannot access a synced realm. Due to this, the recommended course of action is to only open non-synced realms on renderer processes and only one synced realm on the main process.
```

2020-10-06 13:46 UTC, cbush commented on source/node/electron.txt
> +Notice that on line 38, the main process opens a synced realm. On line
Exactly what I warned about has happened: line 38 is blank:

![image](https://user-images.githubusercontent.com/20050130/95209220-202b0800-07b8-11eb-9ab0-7ad35e1f9014.png)

```suggestion
Notice that on line 39, the main process opens a synced realm. On line
```

2020-10-06 13:46 UTC, cbush commented on source/node/electron.txt
> +Consider the adjacent ``renderer process`` code:
Why this word?
```suggestion
Consider the ``renderer process`` code:
```

2020-10-06 13:46 UTC, cbush commented on source/node/electron.txt
> +42, the `ipcMain <https://www.electronjs.org/docs/api/ipc-main>`_
```suggestion
45, the `ipcMain <https://www.electronjs.org/docs/api/ipc-main>`_
```

2020-10-06 13:46 UTC, cbush commented on source/node/electron.txt
> +On line 27, the renderer process opens a non-synced realm. All write
```suggestion
On line 28, the renderer process opens a non-synced realm. All write
```

2020-10-06 13:46 UTC, cbush commented on source/node/electron.txt
> +transactions on this local Realm, will not be synced by default. In
```suggestion
transactions on this local realm will not be synced by default. In
```

2020-10-06 13:46 UTC, cbush commented on source/node/electron.txt
> +an "asynchronous-message" with the argument "sync" on line 40. This
```suggestion
an "asynchronous-message" with the argument "sync" on line 42. This
```

2020-10-06 13:46 UTC, cbush commented on source/node/electron.txt
> +- You can create React Application with Realm using Electron by utilizing `craco <https://www.npmjs.com/package/@craco/craco>`_, Electron, and Realm.
```suggestion
- You can create a React application that uses Realm and Electron with `craco <https://www.npmjs.com/package/@craco/craco>`_.
```

2020-10-06 13:46 UTC, cbush commented on source/node/electron.txt
> +- Notify the main process that a write transaction has occurred on the renderer process by utilizing the `ipcMain <https://www.electronjs.org/docs/api/ipc-main>`_ and the `ipcRenderer <https://www.el
Avoid overwriting:
```suggestion
- Notify the main process that a write transaction has occurred on the renderer process with the `ipcMain <https://www.electronjs.org/docs/api/ipc-main>`_ and the `ipcRenderer <https://www.electronjs.org/docs/api/ipc-renderer>`_ APIs.
```

2020-10-06 18:08 UTC, mongomoe commented on source/node/electron.txt
> +Working Realm Using Renderer and Main Processes
```suggestion
Working with Realm Using Renderer and Main Processes
```

2020-10-06 20:37 UTC, merged