(DOCSP-12109): Android Code Example project; RC-1
mongodb/docs-realm pull request #559
Opened 2020-10-16 22:53 UTC by nathan-contino-mongo

Creating an example app for Android

2020-10-23 14:19 UTC, cbush requested changes
Tested locally. Looks nice. A few comments on the README and various tests. I think the .idea configuration needs to be tweaked. Also, why not add the output of the Android bluehawk examples to match the others?

Let me know when you've addressed the .idea issue and I can take another look. Worst case, we just don't include the configurations and instruct how to run the tests.

2020-10-23 14:19 UTC, cbush commented on examples/android/README.md
> +**instrumented tests**. Thanks to some workarounds and brilliance on the part of Chris Bush,
😊

2020-10-23 14:19 UTC, cbush commented on examples/android/README.md
> +directory containing this README file. Because the project contains the `.idea` directory created
This doesn't work unfortunately. First, when clicking the run button I am asked to edit the configuration:
![image](https://user-images.githubusercontent.com/20050130/97013349-f3e0ec80-1516-11eb-8ce2-38308cadebab.png)

When I click Run on the popup, I get "Configuration is still incorrect":
![image](https://user-images.githubusercontent.com/20050130/97013406-0824e980-1517-11eb-8b46-9331fcd04fdf.png)

Ignoring this leads to "no Android facet found".

2020-10-23 14:19 UTC, cbush commented on examples/android/README.md
> +directory containing this README file. Because the project contains the `.idea` directory created
I think you may want to share only .idea/runConfigurations/All_Tests.xml or see here: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839

2020-10-23 14:19 UTC, cbush commented on examples/android/README.md
> +- add the `@RunWith(AndroidJUnit4.class)` annotation before the class definition
Is this actually needed? We don't combine JUnits, so why the disambiguation?

2020-10-23 14:19 UTC, cbush commented on examples/android/README.md
> +  Now all you have to do is add a `public void` method with the `@Test` annotation
For Java. What about Kotlin?

2020-10-23 14:19 UTC, cbush commented on examples/android/README.md
> +Add a test method to it, which can be named anything starting with `test...`. For example,
This is not applicable here.

2020-10-23 14:19 UTC, cbush commented on examples/android/README.md
> +`model` directory of the example application code itself.
I think you need to rewrite or delete this entire section. None of this really applies to Java (since everything has to be in a class file), but maybe to Kotlin.

2020-10-23 14:19 UTC, cbush commented on examples/android/README.md
> +        // realm will probably yell at you if you do things here
😂😰

2020-10-23 14:19 UTC, cbush commented on examples/android/README.md
> +alias bluehawk="node /path/to/bluehawk/index.js"
Actually these need to be updated. Let's remove the bluehawk installation/alias instructions here and I'll update on the iOS side.

2020-10-23 14:19 UTC, cbush commented on examples/android/README.md
> +to output the example blocks to the `source/includes/android-example-snippets/` directory. Run this on all of the files in `Examples/`.
Instead of Examples/ shouldn't it be "com/mongo/blahblahbl/..."

2020-10-23 14:19 UTC, cbush commented on examples/android/README.md
> +Bluehawk currently generates a lot of files, but we care about those in `/source/includes/android-example-snippets/generated/code/start/`:
Why not send them to `/examples/generated/` like all the others?

2020-10-23 14:19 UTC, cbush commented on examples/android/README.md
> +Now you can update `source/ios/manage-email-password-users.txt` to use these code examples:
```suggestion
Now you can update `source/android/manage-email-password-users.txt` to use these code examples:
```

2020-10-23 14:19 UTC, cbush commented on examples/android/.gitignore
> +!/.idea
Why not just not add /.idea above? -- Though I think this needs to be more specific about what to include/exclude from that directory.

2020-10-23 15:14 UTC, nathan-contino-mongo commented on examples/android/app/src/androidTest/java/com/mongodb/realm/examples/RealmTest.kt
> +@RunWith(AndroidJUnit4::class)
Earlier I tried removing it and ended up with some rather spooky errors, but I'll give it a shot again and remove it. I think the description in the Google Android documentation isn't quite right (big surprise there)

2020-10-23 15:14 UTC, nathan-contino-mongo commented on examples/android/README.md
> +directory containing this README file. Because the project contains the `.idea` directory created
Looking into this! Thank you.

2020-10-23 15:15 UTC, nathan-contino-mongo commented on examples/android/README.md
> +Add a test method to it, which can be named anything starting with `test...`. For example,
well for consistency's sake all of the tests do currently start with "test...". It is not required, but the reader doesn't have to know that if it encourages consistency :)

2020-10-23 15:17 UTC, nathan-contino-mongo commented on examples/android/README.md
> +Bluehawk currently generates a lot of files, but we care about those in `/source/includes/android-example-snippets/generated/code/start/`:
I would like to separate them into distinct subdirectories in `generated`, at least, since I think things will get out of hand quickly if we just throw all of the generated files in one directory. Wanted to check in about that before I moved all of my examples to point at a new destination for the generated files.

2020-10-23 15:17 UTC, nathan-contino-mongo commented on examples/android/.gitignore
> +!/.idea
Ah, I did this at the behest of Android Studio, which claimed that a single click of a button could allow me to share my configuration. Little did I know just how bad their solution could be.

2020-10-23 16:18 UTC, cbush commented on examples/android/README.md
> +Add a test method to it, which can be named anything starting with `test...`. For example,
Then this is not accurately phrased. It _can_  be named anything as long as you have the @Test annotation.

2020-10-23 16:19 UTC, cbush commented on examples/android/README.md
> +Bluehawk currently generates a lot of files, but we care about those in `/source/includes/android-example-snippets/generated/code/start/`:
I'm okay with putting them in /examples/generated/android/.

2020-10-23 16:19 UTC, cbush commented on examples/android/.gitignore
> +!/.idea
Typical.

2020-10-23 18:20 UTC, nathan-contino-mongo commented on examples/android/README.md
> +Add a test method to it, which can be named anything starting with `test...`. For example,
I mean if we're being pedantic here, I don't say that it *can't* be named anything else 😉 
But I have reworded it to clear up this confusion.

2020-10-23 18:24 UTC, nathan-contino-mongo commented on examples/android/app/src/androidTest/java/com/mongodb/realm/examples/RealmTest.kt
> +open abstract class RealmTest {
TIL!

2020-10-23 18:29 UTC, nathan-contino-mongo commented on examples/android/app/src/androidTest/java/com/mongodb/realm/examples/RealmTest.kt
> +@RunWith(AndroidJUnit4::class)
Turns out you can remove it!

2020-10-23 22:48 UTC, nathan-contino-mongo commented
@cbush Updated with fixes for your comments, take a look when you get the chance!

2020-10-26 17:54 UTC, cbush approved these changes
Nice work!

2020-10-26 17:56 UTC, merged