(DOCSP-13017): JS SDK Open a Realm Synchronously
mongodb/docs-realm pull request #609
Opened 2020-11-16 14:58 UTC by mongomoe

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-13018

### Docs staging link (requires sign-in on MongoDB Corp SSO):
Node: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-13017-JS-SDK-Open-Realm-Synchronously/node/open-a-realm.html
React Native: https://docs-mongodbcom-staging.corp.mongodb.com/realm/mohammad.hunan/DOCSP-13017-JS-SDK-Open-Realm-Synchronously/react-native/open-a-realm.html

2020-11-16 15:49 UTC, nlarew requested changes

2020-11-16 15:49 UTC, nlarew commented on source/node/open-a-realm.txt
> +a ``Configuration object`` to a new instance of the :js-sdk:`Realm.App
* What is a `Configuration object`? It's a Realm [Configuration](https://docs.mongodb.com/realm-sdks/js/latest/Realm.html#~Configuration) - let's link to the API docs for it here.
* This is about `Realm` not `Realm.App`

2020-11-16 15:49 UTC, nlarew commented on source/node/open-a-realm.txt
> +<Realm.App.html>` object, which is necessary if the device is offline.
Why is it necessary if the device is offline? From the ticket - `Realm.open` **downloads all the server data that is currently available** but requires an internet connection.

2020-11-16 15:49 UTC, nlarew commented on source/node/open-a-realm.txt
> +   an offline state.
Based on the ticket, it's not about the first time a particular user logs in but rather about whether or not a user is logged in at the time that you open the realm.

I think the motivation is that if a user is already logged in, we want to load the UI as fast as possible. `Realm.open()` doesn't resolve until all pending changes are fully synced so rather than making the user wait for all of that sync to happen we use the `new Realm()` constructor to open the Realm locally. Then it downloads changes in the background and we can update the UI to match the state of the on-device Realm as synced changes come in.

2020-11-16 15:49 UTC, nlarew commented on source/node/open-a-realm.txt
> +<Realm.App.html>`.
nits:
* When opening -> To open
* You can pass -> pass

When should I include the path property? If we're going to mention details of the config file let's give a bit more guidance.

2020-11-16 15:49 UTC, nlarew commented on source/node/open-a-realm.txt
> +   const realm = new Realm.App(config);
```suggestion
   const realm = new Realm(config);
```

2020-11-17 04:22 UTC, mongomoe commented on source/node/open-a-realm.txt
> +a ``Configuration object`` to a new instance of the :js-sdk:`Realm.App
To address your points:
* It is a Realm Configuration! It's linked just a bit above this (line 18) and later linked below in a different section. I didn't want to include two external links to the same thing in the same section.
* Whoops sorry about that, fixed it now!

2020-11-17 04:23 UTC, mongomoe commented on source/node/open-a-realm.txt
> +<Realm.App.html>` object, which is necessary if the device is offline.
```suggestion
<Realm.html>` object, which is necessary if the device is offline.
```

2020-11-17 04:23 UTC, mongomoe commented on source/node/open-a-realm.txt
> +a ``Configuration object`` to a new instance of the :js-sdk:`Realm.App
```suggestion
a ``Configuration object`` to a new instance of the :js-sdk:`Realm
```

2020-11-17 04:24 UTC, mongomoe commented on source/node/open-a-realm.txt
> +either :js-sdk:`Realm.open() <Realm.html#.open>` or :js-sdk:`new Realm.App()
```suggestion
either :js-sdk:`Realm.open() <Realm.html#.open>` or :js-sdk:`new Realm()
```

2020-11-17 04:24 UTC, mongomoe commented on source/node/open-a-realm.txt
> +<Realm.App.html>`.
```suggestion
<Realm.html>`. 
```

2020-11-17 04:44 UTC, mongomoe commented on source/node/open-a-realm.txt
> +   an offline state.
The ticket specifies to open a realm synchronously (via new Realm) if the app user is already logged in. This is not to load the UI as possible, but rather to open a realm even if the phone is offline (it's about internet connectivity not speed). This note is taken from the published [DOTNET page](https://docs.mongodb.com/realm/dotnet/open-a-realm/) about opening a realm, and it functions the same way. 

Let me know if this makes sense or if you still have any questions/concerns about this.

2020-11-17 04:46 UTC, mongomoe commented on source/node/open-a-realm.txt
> +<Realm.App.html>` object, which is necessary if the device is offline.
Sorry - it should be "This works even if the device is offline." not that it is necessary. Updated it now.

2020-11-17 04:46 UTC, mongomoe commented on source/node/open-a-realm.txt
> +<Realm.html>` object, which is necessary if the device is offline.
```suggestion
<Realm.html>` object. This works even if the device is offline. 
```

2020-11-17 05:14 UTC, mongomoe commented on source/node/open-a-realm.txt
> +<Realm.App.html>`.
* When opening -> To open [Fixed]
* You can pass -> pass [Fixed]

Sure, I've altered the sentence to be more like the .net and ios adjacent sentences: "To open a local (non-synced) realm, pass a Configuration() object to either Realm.open() or new Realm(). The following example creates a Configuration object with a path property that defines the local file path to store data." 

Let me know if that works, or if you have any specific alternatives.

2020-11-19 20:21 UTC, nlarew approved these changes

2020-11-20 20:03 UTC, merged