13105
mongodb/docs-realm pull request #630
Opened 2020-11-30 22:03 UTC by MongoCaleb

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-13105

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/13105/dotnet/async-console

2020-11-30 22:34 UTC, cbush approved these changes
LGTM with minor comments

2020-11-30 22:34 UTC, cbush commented on source/dotnet/async-console.txt
> +do not support background threads. So if you are building a .NET
Arguably the "so" doesn't need to be stated here:
```suggestion
do not support background threads. If you are building a .NET 
```

2020-11-30 22:34 UTC, cbush commented on examples/dotnet/ConsoleTests/Program.cs
> +    class Foo : RealmObject
Why not include the Foo class definition in the example for the sake of completeness?

2020-12-01 21:28 UTC, nirinchev requested changes
I have a minor code comment and a suggestion for a rewrite of the opening section.

2020-12-01 21:28 UTC, nirinchev commented on source/dotnet/async-console.txt
> +provides support for asynchronous tasks.
I would reword this paragraph to something along the lines of:

> Realm instances and objects are SynchronizationContext-confined (*link to the threading page*). This means that they can only be accessed on the thread they were created on. .NET's [Task Asynchronous Programming model](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/) allows developers to seamlessly write asynchronous code as a sequence of statements preceded by the `await` keyword. On platforms with a UI thread the framework installs a synchronization context on the main thread, so the continuation after an `await` is dispatched to original context, allowing you to intersperse reads and writes to the database with asynchronous calls. On server/console apps, however, there is no UI thread/SynchronizationContext, which means that `await`-ing a Task will dispatch the continuation on a random thread from the thread pool, preventing you from accessing previously opened Realm instances. To be able to efficiently use Realm in between asynchronous calls, we recommend installing a SynchronizationContext - either one you implemented yourself or one provided by a 3rd party library.

That may be a bit heavy, so feel free to reword it however you want, but I hope it clarifies the problem - it's not about the lack of background threads, but instead, because there's no UI thread, a developer would be forced to reopen Realm after every `await`, otherwise they'd get invalid thread exception.

Also, you can weave in a reference to Stephen Cleary's (the author of Nito.AsyncEx) writeup about synchronization contexts - it's excellent, but also very technical: https://docs.microsoft.com/en-us/archive/msdn-magazine/2011/february/msdn-magazine-parallel-computing-it-s-all-about-the-synchronizationcontext

2020-12-01 21:28 UTC, nirinchev commented on examples/dotnet/ConsoleTests/Program.cs
> +            AsyncContext.Run(async () =>
MainAsync is already invoked with `AsyncContext.Run`, which installs the synchronization context - there's no need to do it again here.

2020-12-03 16:35 UTC, MongoCaleb commented on examples/dotnet/ConsoleTests/Program.cs
> +    class Foo : RealmObject
It's not relevant to this discussion, I think, and is covered in several other places. ¯\_(ツ)_/¯

2020-12-07 17:02 UTC, nirinchev approved these changes

2020-12-07 18:20 UTC, merged