(DOCSP-13318): Define a Realm Object Schema (Java/Kotlin)
mongodb/docs-realm pull request #646
Opened 2020-12-05 00:20 UTC by nathan-contino-mongo

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-13318

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodborg-staging.corp.mongodb.com/NNNNNNN/java/docsworker-xlarge/NNNNNNNNNNN/

2020-12-05 04:04 UTC, ccho-mongodb approved these changes
LGTM, a few nitpicks.

2020-12-05 04:04 UTC, ccho-mongodb commented on source/examples/Schemas/ManyToMany.java
> +            this.rivals = new RealmList();
Question: don't you need the diamond operator `RealmList<>()` for type safety (and prevent the warning) since you declared a type for the field?

2020-12-05 04:28 UTC, nathan-contino-mongo commented on source/sync/configure-your-data-model.txt
> +   * - Type
Really good point -- we're basically talking about JSON schema here, defined in the Realm UI. I'll see if I can pull in an example snippet.

2020-12-05 04:35 UTC, nathan-contino-mongo commented on source/sync/configure-your-data-model.txt
> +     - Optional properties may contain a null value or be entirely
Added types to all fields

2020-12-05 04:38 UTC, nathan-contino-mongo commented on source/examples/Schemas/ClassFieldNamingPolicy.java
> +  public String name;
I *think* this is the only one I missed. Let me know if I missed any others!

2020-12-05 04:38 UTC, nathan-contino-mongo commented on source/examples/Schemas/DefaultValues.java
> +        if (name != null) {
I thought about that, but I think the if logic is easier to follow. However, if you think this is so verbose that a ternary would actually be better, I'm open to the idea! Just let me know.

2020-12-05 04:41 UTC, nathan-contino-mongo commented on source/sync/configure-your-data-model.txt
> +       Objects that are missing a required field without a defined
Woah, big improvement. Thanks for the suggestion!

2020-12-05 04:43 UTC, nathan-contino-mongo commented on source/sync/configure-your-data-model.txt
> +You can configure the following constraints for a given property:
I've added a smaller example earlier on the page because I think the other example (nested in steps) is a little hard for the average user to find. Let me know if you think it's too much!

2020-12-05 04:44 UTC, nathan-contino-mongo commented on source/examples/Schemas/ManyToMany.java
> +            this.rivals = new RealmList();
Good point. Adding this because we'd like the examples to be copy-pasteable.

2020-12-07 19:08 UTC, clementetb requested changes
Looks good 🧙🏻‍♂️! I added some minor change requests.

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/Embedded.kt
> +    var age: int = 0
```suggestion
    var age: Int = 0
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/Embedded.kt
> +class Dog: RealmObject {
```suggestion
open class Dog: RealmObject() {
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/Ignore.kt
> +class Dog: RealmObject {
```suggestion
open class Dog: RealmObject() {
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/Ignore.kt
> +    var age: int = 0
```suggestion
    var age: Int = 0
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/Index.kt
> +class Dog: RealmObject {
```suggestion
open class Dog: RealmObject() {
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/Index.kt
> +    var age: int = 0
```suggestion
    var age: Int = 0
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/ManyToMany.kt
> +class Cat: RealmObject {
```suggestion
open class Cat: RealmObject() {
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/ManyToOne.kt
> +class Cat: RealmObject {
```suggestion
open class Cat: RealmObject() {
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/PrimaryKey.kt
> +class Dog: RealmObject {
```suggestion
open class Dog: RealmObject() {
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/PrimaryKey.kt
> +    var age: int = 0
```suggestion
    var age: Int = 0
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/RenameClass.kt
> +class Dog: RealmObject {
```suggestion
open class Dog: RealmObject() {
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/RenameClass.kt
> +    var age: int = 0
```suggestion
    var age: Int = 0
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/RenameField.kt
> +class Dog: RealmObject {
```suggestion
open class Dog: RealmObject() {
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/RenameField.kt
> +    var age: int = 0
```suggestion
    var age: Int = 0
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/Required.kt
> +class Dog: RealmObject {
```suggestion
open class Dog: RealmObject() {
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/Required.kt
> +    var age: int = 0
```suggestion
    var age: Int = 0
```

2020-12-07 19:08 UTC, clementetb commented on source/examples/Schemas/SameTypeRelationships.kt
> +class Cat: RealmObject {
```suggestion
open class Cat: RealmObject() {
```

2020-12-07 19:39 UTC, nlarew commented on source/android/objects.txt
> +:java-sdk:`RealmPrimaryKeyConstraintException <io/realm/exceptions/RealmPrimaryKeyConstraintException.html`.
```suggestion
:java-sdk:`RealmPrimaryKeyConstraintException <io/realm/exceptions/RealmPrimaryKeyConstraintException.html>`.
```

2020-12-07 19:40 UTC, nlarew commented on source/android/objects.txt
> +      - ``Date``
Why aren't the other types nullable in Kotlin?

2020-12-07 19:43 UTC, nathan-contino-mongo commented on source/android/objects.txt
> +      - ``Date``
The Kotlin Int/Long/Double/etc. types all map to the lowercase primitive versions of those types in Java. Those types aren't nullable because they 1) aren't objects and 2) have a default value (0, typically) instead of null.

2020-12-07 19:59 UTC, nlarew commented on source/android/objects.txt
> +annotation.
Do we have a code snippet for the `@Required` annotation?

2020-12-07 19:59 UTC, nlarew commented on source/android/objects.txt
> +~~~~~~~~~~~~~
This seems to overlap with the [Relationships](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13318b/android/relationships) page. Given that this page is about objects not sure that we need to include relationships here, though I see why you included them here with other schema concepts.

2020-12-07 19:59 UTC, nlarew commented on source/android/objects.txt
> +========
Similar overlap with the [embedded objects](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13318b/android/embedded-objects) page

2020-12-07 19:59 UTC, nlarew commented on source/android/objects.txt
> +=====================
Also overlaps with the [Relationships](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13318b/android/relationships#inverse-relationship) page

2020-12-07 19:59 UTC, nlarew commented on source/android/objects.txt
> +all of the classes that you would like to include in your schema:
nit: feels a bit weird to talk about modules before the section that introduces them

2020-12-07 19:59 UTC, nlarew commented on source/android/objects.txt
> +You cannot explicitly omit classes from your schema. However, you can
Can we rephrase this in a way that's less bait and switch? e.g.

- by default the schema automatically includes all classes that extend RealmObject
- if you only want to include a specific subset of schemas, you can open the realm with a module

Also given this framing it feels like it'd be more appropriate on the Realms page or Open a Realm examples. Thoughts?

2020-12-07 19:59 UTC, nlarew commented on source/android/objects.txt
> +-------------
Should this go on the [Realms](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13318b/android/realms) page instead? Seems like it has to do with multiple objects/realm schemas, which is beyond the scope of this page that focuses specifically on Realm Objects.

2020-12-07 20:00 UTC, nlarew commented on source/android/objects.txt
> +      - ``Date``
Might be worth a note to explain this context/difference

2020-12-07 20:13 UTC, nathan-contino-mongo commented on source/android/objects.txt
> +annotation.
yeah, it should be on this page

2020-12-07 20:13 UTC, nathan-contino-mongo commented on source/android/objects.txt
> +~~~~~~~~~~~~~
I think i'll add a seealso link to relationships for further reading

2020-12-07 20:13 UTC, nathan-contino-mongo commented on source/android/objects.txt
> +========
Will add a seealso link to embedded objects

2020-12-07 21:28 UTC, nathan-contino-mongo commented on source/android/objects.txt
> +You cannot explicitly omit classes from your schema. However, you can
I think I'm just going to move the Modules section to the Realms page for now -- this section is a little more task oriented (specifically instructing users how to omit classes from their schema). But definitely agreed that the modules info fits better on the realms page.

2020-12-07 21:28 UTC, nathan-contino-mongo commented on source/android/objects.txt
> +all of the classes that you would like to include in your schema:
Fixed by moving modules to another page ;)

2020-12-07 21:47 UTC, merged