(DOCSP-13594): stitch deprecation doc - web
mongodb/docs-realm pull request #665
Opened 2020-12-14 14:00 UTC by mongomoe

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-13594

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/docsp-13594-stitchtorealm-web/web/migrate

2020-12-14 14:24 UTC, ccho-mongodb commented on source/web/migrate.txt
> +    - Replace all ``mongoClient`` instatiations with ``Realm.User.mongoClient``.
```suggestion
    - Replace all ``mongoClient`` instantiations with ``Realm.User.mongoClient``.
```

2020-12-14 15:02 UTC, ccho-mongodb requested changes
Looks pretty good, added suggestions that may make it easier to read and understand.

2020-12-14 15:02 UTC, ccho-mongodb commented on source/web/migrate.txt
> +   SDK to the Realm Web SDK. If you are looking to use the Realm JS SDK to build
Suggestion: add a line break after the first sentence. Seems like it would be easier to read at a glance. E.g.
"This page shows how to migrate from the MongoDB Stitch Browser SDK to the Realm Web SDK.

If you are looking for ... see this link instead.
"

2020-12-14 16:09 UTC, nlarew commented on source/web/migrate.txt
> +   <node-migrating-from-stitch-to-realm>` doc. If you are looking to develop
+1 in general we use "page" or omit the noun entirely, e.g. "check out Upgrade from Stitch to Realm (Node)"

2020-12-14 16:12 UTC, nlarew commented on source/web/migrate.txt
> +- The  {+service-short+} SDKs do not provide hooks for calling Services (like the
nit: IMO these aren't really hooks. I associate that term with lifecycle/plugin methods, e.g. `componentDidMount` in React or `onPageCreate` in Gatsby.

In general we've referred to service methods as **actions** that you access as methods on a **service client**

2020-12-14 16:19 UTC, nlarew commented on source/web/migrate.txt
> +information hasn't changed, there are a few changes to how it connects to the
```suggestion
information hasn't changed, there are a few changes to how the SDK connects to the
```

2020-12-14 16:19 UTC, nlarew commented on source/web/migrate.txt
> +   * - The Stitch SDK required developers to import authentication credentials from the "mongodb-stitch-server-sdk". The Realm SDK has a class, :js-sdk:`Realm.Credentials <Realm.Credentials.html>`, t
```suggestion
   * - The Stitch SDK required developers to import authentication credentials from the ``mongodb-stitch-browser-sdk``. The Realm SDK has a class, :js-sdk:`Realm.Credentials <Realm.Credentials.html>`, that creates credentials for each authentication provider.
```

2020-12-14 16:19 UTC, nlarew commented on source/web/migrate.txt
> +   * - Instead of calling {+backend+} functions using the app client directly via the method `stitchAppClient.callFunction() <http://stitch-sdks.s3-website-us-east-1.amazonaws.com/stitch-sdks/js/4/in
You shouldn't really need `callFunction()` for most use cases. It's more ergonomic to use the Proxy form, i.e.

`await app.currentUser.callFunction("myFunction", [1,2,3])`
vs
`await app.currentUser.functions.myFunction(1,2,3)`

2020-12-14 16:19 UTC, nlarew commented on source/web/migrate.txt
> +   * - Instead of calling {+backend+} functions using the app client directly via the method `stitchAppClient.callFunction() <http://stitch-sdks.s3-website-us-east-1.amazonaws.com/stitch-sdks/js/4/in
"server MongoDB Realm functions" is weird phrasing, let's just call them "Realm functions" or "functions"

2020-12-14 19:34 UTC, mongomoe commented on source/web/migrate.txt
> +  * - The interface to the MongoDB Data Access API, containing objects like :js-sdk:`MongoDatabase <Realm-MongoDBDatabase.html>`, and :js-sdk:`MongoCollection <Realm.MongoDBCollection>`, has changed.
I think there was a spacing issue originally. I pushed a change w/ the fixed spacing. Can you try refreshing your page and seeing if it renders properly now?

2020-12-14 19:36 UTC, mongomoe commented on source/web/migrate.txt
> +  * - The interface to the MongoDB Data Access API, containing objects like :js-sdk:`MongoDatabase <Realm-MongoDBDatabase.html>`, and :js-sdk:`MongoCollection <Realm.MongoDBCollection>`, has changed.
Fixed in latest commit

2020-12-14 19:48 UTC, mongomoe commented on source/web/migrate.txt
> +Deprecated Features
You can still use these services if you use the Stitch SDK. 

I found this [doc](https://docs.moodle.org/dev/Deprecation) describing deprecation as: "Deprecation, in its programming sense, is the process of taking older code and marking it as no longer being useful within the codebase, usually because it has been superseded by newer code. The deprecated code is not immediately removed from the codebase because doing so may cause regression errors." 

Do you still recommend replacing this w/ Incompatible features? Especially considering users can still use these services with the Stitch SDK.

2020-12-14 20:20 UTC, mongomoe commented on source/web/migrate.txt
> +   * - Instead of calling {+backend+} functions using the app client directly via the method `stitchAppClient.callFunction() <http://stitch-sdks.s3-website-us-east-1.amazonaws.com/stitch-sdks/js/4/in
Good ideas. I've updated the row accordingly to both of your suggestions.

2020-12-14 20:23 UTC, mongomoe commented on source/web/migrate.txt
> +     - Replace imports of authentication credentials with method calls for each respective authentication provider through the ``Realm.Credentials`` class.
Thanks for the suggestion. I've added a link to StitchCredentials which is implemented by all the auth credential classes. There you can see specific examples for each respective type of credential.

2020-12-14 20:28 UTC, mongomoe commented on source/web/migrate.txt
> +     - Migrate all occurrences of ``StitchAppClient`` to ``Realm.App``.
It was something you can do with the StitchAppClient. I've removed that sentence ("The Realm.App is not an interface to access MongoDB Realm functions" entirely. There is another row (second to last one) that discusses this in length.

2020-12-14 20:32 UTC, ccho-mongodb commented on source/web/migrate.txt
> +Deprecated Features
I think "Incompatible Features" makes sense.

My initial suggestion was based on my misconception that you were only referring to the Stitch SDK and that the support had been removed.

Given the info that you're talking about Stitch SDK and Realm SDK, "deprecated" does not fit because they are two different SDKs and codebases. It sounds like there are plans to remove the Stitch SDK but not to change the Stitch SDK to remove the lifecycle methods.

I think this may be a candidate for the table that lists the changes and what the solutions are rather than placed in a separate section.

2020-12-14 20:39 UTC, mongomoe commented on source/web/migrate.txt
> +- The  {+service-short+} SDKs do not provide hooks for calling Services (like the
Decided to go with the word "interfaces" here. Took everything from chris's suggestion, except the first sentence (the interface/hook into services still works w/ stitch sdk, and never worked w/ the realm sdk). 

The full paragraph reads: 

"The Realm SDKs do not provide an interface for calling Services
(like the Twilio and AWS services). If you were using these in your Stitch app, convert them to Realm functions in your Realm application using the AWS and/or Twilio npm packages. For more information, see Upload External Dependencies."

2020-12-14 20:40 UTC, mongomoe commented on source/web/migrate.txt
> +   <node-migrating-from-stitch-to-realm>` doc. If you are looking to develop
👍  fixed to "page"

2020-12-14 20:47 UTC, mongomoe commented on source/web/migrate.txt
> +{+realm+} backend.
We don't have an exact timeline for Stitch apps becoming not compatible. This paragraph is taken from the adjacent pages of the other SDK. Once we have a solid timeline we can add a mention to the timeline.

2020-12-14 20:47 UTC, mongomoe commented on source/web/migrate.txt
> +   SDK to the Realm Web SDK. If you are looking to use the Realm JS SDK to build
👍

2020-12-14 21:04 UTC, mongomoe commented on source/web/migrate.txt
> +Deprecated Features
👍  That's a really good idea and is far more accurate. I've removed the "deprecated features" subsection and moved this into a row of the "changes table"

2020-12-14 21:21 UTC, ccho-mongodb approved these changes
Looks good to me. Just a few optional nitpicks.

2020-12-14 21:21 UTC, ccho-mongodb commented on source/web/migrate.txt
> +information hasn't changed, there are a few changes to how the SDK connects to the
Nitpick: might seem obvious, but since you mention two SDKs in the prior sentence, it could be good to identify which one here:
```suggestion
information hasn't changed, there are a few changes to how the new SDK connects to the
```

2020-12-14 21:21 UTC, ccho-mongodb commented on source/web/migrate.txt
> +   The following page presents how to migrate from the MongoDB Stitch Browser
Nitpick: here's how I'd refer to it. If "the following page" is something you use through Realm docs, feel free to ignore.

```suggestion
   This page presents how to migrate from the MongoDB Stitch Browser
```

2020-12-14 21:21 UTC, ccho-mongodb commented on source/web/migrate.txt
> +.. note::
Nitpick: Sorry for missing this initially -- I wonder if the note is required or whether this could just be normal paragraph-formatted text.

2020-12-14 21:21 UTC, ccho-mongodb commented on source/web/migrate.txt
> +   Node applications, check out the :ref:`Upgrade from Stitch to Realm Node
Nitpick: Node.js

2020-12-14 21:21 UTC, ccho-mongodb commented on source/web/migrate.txt
> +     - Migrate all occurrences of ``StitchAppClient`` to ``Realm.App``.
Ok, I just want to make sure -- are there corresponding functions in Realm.App for all functions called on StitchAppClient? Otherwise, would it make sense to mention that they should check that the function exists or the equivalent one here?

2020-12-14 21:21 UTC, ccho-mongodb commented on source/web/migrate.txt
> +     -  Convert uses of Third Party Services in your Stitch Application to Realm functions in your Realm application using the AWS and/or Twilio npm packages. For more information, see :doc:`Upload E
Just thought the sentence was a little indirect. Could even omit the parenthetical containing AWS and Twilio since it's mentioned in the "What's Changed" column.

```suggestion
     -  Convert references to Third Party Services (AWS or Twilio) in your Stitch Application to Realm functions in your Realm application using the corresponding npm packages. For more information, see :doc:`Upload External Dependencies </functions/upload-external-dependencies>`.
```

2020-12-15 16:52 UTC, mongomoe commented on source/web/migrate.txt
> +     - Migrate all occurrences of ``StitchAppClient`` to ``Realm.App``.
They exist and are accessible on the logged-in user object.
 ```So user.functions.<MyMongoDBRealmFunction>(param1,param2)```

2020-12-15 16:54 UTC, mongomoe commented on source/web/migrate.txt
> +   Node applications, check out the :ref:`Upgrade from Stitch to Realm Node
👍

2020-12-15 16:55 UTC, mongomoe commented on source/web/migrate.txt
> +.. note::
I prefer it as a note personally since it doesn't directly impact the information itself on the doc, but is rather an aside to the reader.

2020-12-15 16:56 UTC, merged