WIP - (DOCSP-13196) Stitch Deprecation doc - IOS
mongodb/docs-realm pull request #668
Opened 2020-12-14 21:27 UTC by mongomoe

WIP - DONOTMERGE/DONOTREVIEW YET
## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-13196

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodborg-staging.corp.mongodb.com/NNNNNNN/java/docsworker-xlarge/NNNNNNNNNNN/

2020-12-15 20:58 UTC, cbush requested changes
Content looks good, but we can't publish "IOS". Please update to iOS.

2020-12-15 20:58 UTC, cbush commented on source/ios/migrate.txt
> +- The {+service-short+} IOS SDK supports IOS applications written in Objective C.
It is iOS, not IOS.

2020-12-15 20:58 UTC, cbush commented on source/ios/migrate.txt
> +- The {+service-short+} IOS SDK supports IOS applications written in Objective C.
```suggestion
- The {+service-short+} IOS SDK supports IOS applications written in Objective-C.
```

2020-12-15 20:58 UTC, cbush commented on source/ios/migrate.txt
> +- The {+service-short+} IOS SDK supports IOS applications written in Objective C.
And Swift.

2020-12-15 20:58 UTC, cbush commented on source/ios/migrate.txt
> +   * - The API to call a {+service-short+} function has changed from `stitchAppClient.callFunction() <http://stitch-sdks.s3-website-us-east-1.amazonaws.com/stitch-sdks/swift/6/Protocols/StitchAppClie
It might help to explicitly call out something like "where `{myFunction}` is the name of the function".

2020-12-16 16:59 UTC, mongomoe commented on source/ios/migrate.txt
> +- The {+service-short+} IOS SDK supports IOS applications written in Objective C.
Fixed, in all areas where it was written "IOS"

2020-12-16 17:03 UTC, mongomoe commented on source/ios/migrate.txt
> +- The {+service-short+} IOS SDK supports IOS applications written in Objective C.
The previous Stitch SDK was written in Swift as well. This is a new features section @cbush. It's also meant to parody the [Android version of this page](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/whatschanged/android/migrate#new-features)

2020-12-16 17:14 UTC, mongomoe commented on source/ios/migrate.txt
> +- The {+service-short+} IOS SDK supports IOS applications written in Objective C.
Fixed the typo with "Objective C" -> "Objective-C" though

2020-12-16 17:14 UTC, mongomoe commented on source/ios/migrate.txt
> +   * - The API to call a {+service-short+} function has changed from `stitchAppClient.callFunction() <http://stitch-sdks.s3-website-us-east-1.amazonaws.com/stitch-sdks/swift/6/Protocols/StitchAppClie
👍

2020-12-16 17:49 UTC, cbush approved these changes

2020-12-16 18:25 UTC, merged