DOCSP-13320: Define a Realm Object Schema (.NET)
mongodb/docs-realm pull request #669
Opened 2020-12-15 16:59 UTC by ksadoff

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-13320

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13320/dotnet/objects

2020-12-15 17:07 UTC, MongoCaleb approved these changes
LTGM except: please add a newline to the end of each file.

2020-12-15 19:03 UTC, nlarew requested changes
Nice work! Just a few small tweaks and then I think this is good to go.

2020-12-15 19:03 UTC, nlarew commented on source/dotnet/objects.txt
> +      - ``Decimal128``
nit: let's totally de-indent this list

2020-12-15 19:03 UTC, nlarew commented on source/dotnet/objects.txt
> +         :language: csharp
Let's de-indent the literalinclude (and other similar ones on this page)

2020-12-16 20:57 UTC, nlarew commented on source/dotnet/objects.txt
> +- ``IList<T>`` where T is any of the previous data types
```suggestion
- ``IList<T>`` where T is any of the previous data types (see :ref:`Lists <dotnet-field-lists>`)
```

2020-12-16 21:01 UTC, nlarew commented on source/dotnet/objects.txt
> +- ``Date``
nits:
* These are in a different order from the previous section which makes it tougher to compare them
* Do lists also support `Decimal128` and `ObjectId`? AFAIK they do, i.e. they should support lists of any primitive type.

Maybe it'd be easier to just remove the list and say you can have lists of any of the primitive data types? i.e. you can have a list of anything except for RealmObject (which uses Relationships instead) or another List.

2020-12-16 21:03 UTC, nlarew commented on source/dotnet/objects.txt
> +   or ``MongoDB.Bson.ObjectId``.
This is redundant with the other list at the start of the section + doesn't really fit with the rest of the note. Can we remove it?

2020-12-16 21:04 UTC, nlarew commented on source/dotnet/objects.txt
> +- ``Date``
Maybe it'd be easier to say what you **can't** make required? Then we avoid redundancy with the list of primitive data types

2020-12-16 21:06 UTC, nlarew commented on source/dotnet/objects.txt
> +~~~~~~~~~~~~~~~
Optional fields are more or less the inverse of Required fields + have a lot of overlap in terms of content. Do you think we could combine these into one section, e.g. **Required & Optional Fields**?

2020-12-16 21:06 UTC, nlarew commented on source/dotnet/objects.txt
> +Adding an index to a field makes writing slightly slower, but makes
```suggestion
Adding an index to a field makes write operations slightly slower, but makes
```

2020-12-16 21:07 UTC, nlarew commented on source/dotnet/objects.txt
> +===========
```suggestion
======
```

The header underline should have the same number of characters as the text

2020-12-16 21:07 UTC, nlarew commented on source/dotnet/objects.txt
> +============
```suggestion
=======
```

The header underline should have the same number of characters as the text

2020-12-16 21:10 UTC, nlarew commented on source/dotnet/objects.txt
> +================
I think we should make sure Relationships and Embedded Objects are distinct. They're both relational constructs but embedded objects are more like a complex field type and have different behavior/considerations from other relationships.

To wit, can we pull **Embedded Objects** up one level to be a peer of Relationships rather than a child?

2020-12-16 22:38 UTC, nirinchev commented on source/dotnet/objects.txt
> +- ``Date``
I think it would be confusing to say you can have a list of anything except RealmObject considering a relationship is defined precisely as a list of RealmObject 😅

2020-12-16 22:40 UTC, nlarew commented on source/dotnet/objects.txt
> +- ``Date``
Ah fair enough! That simplifies it to "a List of anything except for another List"

2020-12-16 23:49 UTC, nlarew approved these changes
LGTM!

2020-12-17 14:31 UTC, merged

2020-12-17 15:26 UTC, nirinchev reviewed
I'm leaving the comments here because it's easier to explain what needs to be fixed than if I created a Jira ticket.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +{+client-database+} supports the following field data types:
It should also mention that the nullable versions of these types are supported.

2020-12-17 15:26 UTC, nirinchev commented on source/examples/Schemas/Embedded.cs
> +    public string City { get; set; }
These `MapTo` attributes don't provide value in the context of embedded object docs. I'm guessing they're reusing examples from the embedded objects page, but there we have the JSON Schema doc which uses camelCase properties and it's clearer to the reader why we have them.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +- ``String``
This should be lowercase

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +- ``Short`` or ``short``
The capitalized versions of these types should be removed.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +- ``Byte`` or ``byte[]``
`byte[]` cannot be a primary key. `byte` can, but it has to be lowercase.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +A **primary key** is a field that uniquely identifies an object. You can
This list is missing `char` as well as the nullable versions of ObjectId and the numeric types.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +   object of that type to a {+realm+}.
`object of that type` is redundant - once an object is added, it's primary key cannot be changed - the fact that it is of that type is not important.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +- ``Decimal128``
This list is incorrect. It should only contain `string` and `byte[]`.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +C# `? operator <https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types>`__ except
`?` is not an operator.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +Any value type in C# can be made nullable with the ``?``, although by
"the `?`" reads very awkwardly.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +If a field is normally nullable, you can make it required to disallow ``null`` values
Here and in the rest of the document field should be property - the .NET SDK doesn't work with fields.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +nullable and cannot be required.
"cannot be *made* required".

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +You can use the ``[Required]`` annotation as seen in the following example:
`[Required]` is an attribute, not annotation.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +annotation.
This repeats the information in the first sentence of this section - do we really need it?

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +In .NET, you can assign a default value in the field declaration.
Here .NET should be C# - I know that in many places we use them interchangeably, but here we can't.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +*collection scan*, i.e. scan every document in a collection, to select
In the Realm database, "collection" is called "table" and "document" is "object". While this terminology might be more understandable for MongoDB developers, it will be confusing for people coming from Realm background.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +- ``String``
`string`

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +- ``Short`` or ``short``
Remove uppercase versions

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +- ``Byte`` or ``byte[]``
`byte`

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +- ``Boolean`` or ``bool``
Remove uppercase versions

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +- ``Date``
`DateTimeOffset`

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +- ``String``
This list is missing `char`.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +To set up a many-to-one or one-to-one relationship, create a field
field -> property

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +with whose type is a ``RealmObject`` in your application:
The type is not `RealmObject`, but rather a type that inherits from `RealmObject` or `EmbeddedObject`.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +{+service-short+} object in your application:
T can be RealmObject or EmbeddedObject inheritor.

2020-12-17 15:26 UTC, nirinchev commented on source/examples/Schemas/Inverse.cs
> +    // One to many relationship with Person.Dogs
This comment is incorrect.

2020-12-17 15:26 UTC, nirinchev commented on source/examples/Schemas/Inverse.cs
> +    // Many to many relationship with Hobby.PeopleWithThatHobby
This comment is incorrect - this is a One-to-many relationship to Hobbies.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +If you don't want to save a field in your model to a {+realm+}, you can
Should mention that properties that are not autoimplemented or don't have a setter are ignored by default.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +classes that extend ``RealmObject``. If you only want to include a
extend `RealmObject` -> inherit from `RealmObject` or `EmbeddedObject`.

2020-12-17 15:26 UTC, nirinchev commented on source/dotnet/objects.txt
> +subset of classes that extend ``RealmObject`` in your {+service-short+}
repetition of `extend RealmObject` - can be replaced with `a subset of these classes`.

2020-12-17 17:36 UTC, ksadoff commented on source/dotnet/objects.txt
> +*collection scan*, i.e. scan every document in a collection, to select
Is this something you'd liked to see changed in the .NET SDK documentation in general? It's used on other pages beside this one.

2020-12-17 17:46 UTC, nirinchev commented on source/dotnet/objects.txt
> +*collection scan*, i.e. scan every document in a collection, to select
Gotcha - let's create a separate ticket for that then - we should probably make sure it's aligned across all SDKs.