Work In Progress: Initial Setup for Electron with vanilla js
mongodb/docs-realm pull request #679
Opened 2020-12-18 19:47 UTC by mongomoe

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-NNNN

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/QuickStart-Electron-with-vanilla-js/node/electron

2021-01-07 11:00 UTC, blagoev reviewed
The quickstart shows only how to open a Realm from the renderer. Should we have another quick start that shows how to use a single Realm from main and renderer processes simultaneously using vanilla html/js code. 
Also are we planning on having these quickstarts on github somewhere. I think having the manual steps defined how to create the whole application from scratch is nice but also having these somewhere easily cloneable will be even nicer since most devs will already know Electron app structure but would like to just quickly clone a project and hack on with Realm already setup for them.  
Also this might help if we in the future have a CLI that has scaffolding functionality similar to create-react-app
I think having all examples in common repo will be a great addition to the docs. 

Otherwise I think the PR is good

2021-01-07 17:47 UTC, terakilobyte requested changes
The content appears to be good but I think the copy can be cleaned up. I've made several suggestions.

2021-01-07 17:47 UTC, terakilobyte commented on source/includes/steps-realm-with-electron.yaml
> +  The main.js file is the entry point into your application and
```suggestion
  The ``main.js`` file is the entry point into your application and
```

2021-01-07 17:47 UTC, terakilobyte commented on source/includes/steps-realm-with-electron.yaml
> +  following to your ``index.html`` file:
```suggestion
  Add the following to your ``index.html`` file:
```

2021-01-07 17:47 UTC, terakilobyte commented on source/includes/steps-realm-with-electron.yaml
> +  you require in this HTML file will execute on the renderer process. Add the
```suggestion
  you require in this HTML file will execute on the renderer process.
```

2021-01-07 17:47 UTC, terakilobyte commented on source/includes/steps-realm-with-electron.yaml
> +  Create a ``renderer.js`` file in the root directory of your
Is there any reason they can't create this file when they create the other files above?

2021-01-07 17:47 UTC, terakilobyte commented on source/includes/steps-realm-with-electron.yaml
> +  application. Add the following code to this file:
Why is this in the renderer?

2021-01-07 17:47 UTC, terakilobyte commented on source/includes/steps-realm-with-electron.yaml
> +
```suggestion
  Install the necessary dependencies to begin developing your Electron application using Realm. 

  .. code-block:: shell

     npm install electron --save-dev
     npm install realm --save

```

2021-01-07 17:47 UTC, terakilobyte commented on source/includes/steps-realm-with-electron.yaml
> +  Running the command ``npm start`` will now start your Electron app.
```suggestion
  Add a script to your ``package.json`` file in order to start your application with the ``npm start`` command.

  .. code-block:: json

     "scripts": {
      "start": "electron ."
     }

```

2021-01-07 17:47 UTC, terakilobyte commented on source/includes/steps-realm-with-electron.yaml
> +  In order to display HTML to the users, your application needs a
```suggestion
  In order to display HTML to users, your application needs a
```

2021-01-07 17:47 UTC, terakilobyte commented on source/includes/steps-realm-with-electron.yaml
> +  accessible in this main process file.
```suggestion
  ``require("realm")`` on line 2 makes Realm accessible in the main process.
```

2021-01-07 17:47 UTC, terakilobyte commented on source/includes/steps-realm-with-electron.yaml
> +
issue: This feels distinct from the above information and should be moved into its own step

2021-01-07 17:47 UTC, terakilobyte commented on source/includes/steps-realm-with-electron.yaml
> +  on the ``renderer process``.
```suggestion
  ``main.js`` executes on the ``main`` process. ``renderer.js`` and
  any other files required by it, or by ``index.html``, execute
  on the ``renderer`` process.
```

2021-01-07 17:47 UTC, terakilobyte commented on source/includes/steps-realm-with-electron.yaml
> +  In order to run your application, enter the following into your terminal:
```suggestion
  Start your application from the terminal:
```

2021-01-07 17:47 UTC, terakilobyte commented on source/node/electron.txt
> +This page contains information to get {+service+} integrated into your
```suggestion
This page contains information to integrate {+service+} into your
```

2021-01-07 17:47 UTC, terakilobyte commented on source/node/electron.txt
> +Set up
```suggestion
Setup
```

2021-01-07 17:47 UTC, terakilobyte commented on source/node/electron.txt
> +To set up an Electron application using {+service+} use the following instructions:
nitpick: Does this sentence provide value?

2021-01-07 17:47 UTC, terakilobyte commented on source/node/electron.txt
> +Have a user authenticated, define your schema, and have :ref:`sync enabled
nitpick: This mixes passive with active voice and tense. Additionally, it strikes me as awkward to begin the sentence with "Have".

2021-01-11 15:51 UTC, mongomoe commented on source/node/electron.txt
> +Have a user authenticated, define your schema, and have :ref:`sync enabled
Fixed to: "Authenticate a user, define a schema, and enable Realm Sync, then call Realm.open in your renderer.js file:"

2021-01-11 15:51 UTC, mongomoe commented on source/node/electron.txt
> +           _id: 'objectId',
Sounds good, changed to an int

2021-01-11 15:52 UTC, mongomoe commented on source/node/electron.txt
> +To set up an Electron application using {+service+} use the following instructions:
I guess not, removed now 👍

2021-01-11 18:23 UTC, terakilobyte requested changes
The content looks good overall, but please ensure you're formatting consistently.

2021-01-11 18:23 UTC, terakilobyte commented on source/includes/steps-realm-with-electron.yaml
> +  Your application file structure should now look something like the following:
nitpick: s/now look something like/resemble

2021-01-11 18:23 UTC, terakilobyte commented on source/includes/steps-realm-with-electron.yaml
> +  on the ``renderer`` process.
```suggestion
  on a ``renderer`` process.
```

2021-01-11 18:23 UTC, terakilobyte commented on source/node/electron.txt
> +renderer.js file:
issue: please ensure you are formatting [file names](https://docs.mongodb.com/meta/style-guide/style/text-formatting/) in accordance with the style guide.

2021-01-11 18:35 UTC, mongomoe commented on source/includes/steps-realm-with-electron.yaml
> +  Add the following to your ``index.html`` file:
fixed

2021-01-11 18:36 UTC, mongomoe commented on source/includes/steps-realm-with-electron.yaml
> +     Each Electron application can only have one **main process**. The
Fixed to emphasize the name using code formatting with backticks similar to renderer process

2021-01-11 18:37 UTC, mongomoe commented on source/includes/steps-realm-with-electron.yaml
> +  Your application file structure should now look something like the following:
sounds good 👍

2021-01-11 18:37 UTC, mongomoe commented on source/includes/steps-realm-with-electron.yaml
> +  on the ``renderer`` process.
There can potentially be multiple renderer processes, so it needs to be "a renderer" rather than "the renderer"

2021-01-11 18:38 UTC, mongomoe commented on source/node/electron.txt
> +renderer.js file:
👍

2021-01-11 20:27 UTC, terakilobyte commented on source/includes/steps-realm-with-electron.yaml
> +  on the ``renderer`` process.
Correct. My suggestion changes it from 'the' top 'a'

2021-01-11 20:33 UTC, mongomoe commented on source/includes/steps-realm-with-electron.yaml
> +  you require in this HTML file will execute on the renderer process.
```suggestion
  you require in this HTML file will execute on a renderer process.
```

2021-01-11 20:33 UTC, mongomoe commented on source/includes/steps-realm-with-electron.yaml
> +     |-- renderer.js // runs on the renderer process
```suggestion
     |-- renderer.js // runs on a renderer process
```

2021-01-11 20:34 UTC, mongomoe commented on source/includes/steps-realm-with-electron.yaml
> +  executes on the ``renderer`` process.
```suggestion
  executes on a ``renderer`` process.
```

2021-01-11 20:42 UTC, mongomoe commented on source/includes/steps-realm-with-electron.yaml
> +  on the ``renderer`` process.
fixed!

2021-01-11 20:42 UTC, terakilobyte approved these changes
lgtm

2021-01-11 20:48 UTC, mongomoe commented
Merging @blagoev has given lgtm through slack

2021-01-12 15:07 UTC, merged