DOCSP-13325: Read & Write Data (.NET)
mongodb/docs-realm pull request #680
Opened 2020-12-22 19:47 UTC by ksadoff

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-13325

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13325/

2020-12-22 20:28 UTC, ccho-mongodb requested changes
I have a number of questions and couple nitpicks. I'd recommend asking for a reviewer that  knows .NET well since it sounds like we're both uncertain about the code based on your code comments.

Also, could you update the staging url to this page if you get the chance?
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-13325/dotnet/relationships

2020-12-22 20:28 UTC, ccho-mongodb commented on examples/dotnet/Examples/Relationships.cs
> +            // Not sure if this accurately shows a one-to-many query
Question: is this something that you'll update before publishing, or is there a ticket for it?

2020-12-22 20:28 UTC, ccho-mongodb commented on source/examples/generated/code/start/Relationships.codeblock.one-to-many-query.cs
> +// Not sure if this accurately shows a one-to-many query
Question: is this something that you'll update before publishing, or is there a ticket for it?

2020-12-22 20:28 UTC, ccho-mongodb commented on source/examples/Query/FindByPrimaryKey.cs
> +var myTask = new Task
Question: what's this Task instance used for? Is this being stored in Realm as MyObject type and then is supposed to be retrieved in line 7? If so, could you explain that? I wasn't able to make the connection from the description or code snippet.

2020-12-22 20:28 UTC, ccho-mongodb commented on examples/dotnet/Examples/Relationships.cs
> +                person.Dogs.Add(dog1);
Question: this is more for my own edification, but are the Dog documents just subdocuments of Person, or should they also exist as Documents themselves? I was trying to understand using the Java documentation on relationship object schemas, so it wasn't apparent whether Dog should be saved Realm objects as well:
https://docs.mongodb.com/realm/android/relationships

If the dogs are not stored separately, would the query on line 132 work?

2020-12-22 20:28 UTC, ccho-mongodb commented on examples/dotnet/Examples/Relationships.cs
> +            var youngDogs = realm.All<Dog>().Where(d => d.Age == 1);
```suggestion
            var puppies = realm.All<Dog>().Where(d => d.Age == 1);
```

2020-12-22 20:28 UTC, ccho-mongodb commented on examples/dotnet/Examples/Relationships.cs
> +            var younglist = new List<Dog>();
Nitpick: use camelcase to separate the words similar to the prior variable (e.g. youngList or youngDogsList).

Question:  should this be an `IList`? It looks like that's the type referenced in the documentation earlier on this page.

2020-12-22 20:28 UTC, ccho-mongodb commented on source/examples/generated/code/start/Relationships.codeblock.one-to-one-query.cs
> +// Not sure if this accurately shows a one-to-one query
Question: is this something that you'll update before publishing, or is there a ticket for it?

2020-12-22 20:35 UTC, ksadoff commented on examples/dotnet/Examples/Relationships.cs
> +            // Not sure if this accurately shows a one-to-one query
https://github.com/mongodb/docs-realm/pull/677 looks like it's been merged already.

2020-12-22 20:35 UTC, ksadoff commented on source/dotnet/relationships.txt
> +(Inverse queries handled in Caleb's PR)
https://github.com/mongodb/docs-realm/pull/677 looks like it's been merged already

2020-12-22 20:41 UTC, ksadoff commented on examples/dotnet/Examples/Relationships.cs
> +            // Not sure if this accurately shows a one-to-one query
This is something I want to update, I was hoping to get some insight on what might work as a good example if this one (and the one below) doesn't.

2020-12-22 20:41 UTC, ksadoff commented on examples/dotnet/Examples/Relationships.cs
> +            // Not sure if this accurately shows a one-to-many query
See above comment

2020-12-22 20:53 UTC, ksadoff commented on source/examples/Query/FindByPrimaryKey.cs
> +var myTask = new Task
Yes, that was my intention. I can clarify that in the description/code.

2020-12-22 21:06 UTC, ksadoff commented on examples/dotnet/Examples/Relationships.cs
> +            var younglist = new List<Dog>();
`IList` is an interface in C#; `List` is one of the classes that implements it, so I used that.

2020-12-22 23:35 UTC, ccho-mongodb commented on examples/dotnet/Examples/Relationships.cs
> +            var younglist = new List<Dog>();
Ah, makes sense. 👍

2021-01-04 17:56 UTC, MongoCaleb approved these changes
LGTM with a couple of suggested changes.

2021-01-04 17:56 UTC, MongoCaleb commented on examples/dotnet/Examples/Relationships.cs
> +            var fidosPerson = realm.All<Person>().Where(p => p.Dog == dog);
Try 
`var fidosPerson = realm.All<Person>().FirstOrDefault(p => p.Dog == dog);`
or
`var fidosPerson = realm.All<Person>().Where(p => p.Dog == dog).FirstOrDefault();`

2021-01-04 17:56 UTC, MongoCaleb commented on examples/dotnet/Examples/Relationships.cs
> +            Assert.AreEqual(fidosPerson.First(), person);
And then you don't need the First() here. BTW, "FirstOrDefault()" is better because it won't thrown an exception if no record is found.

2021-01-04 17:56 UTC, MongoCaleb commented on examples/dotnet/Examples/Relationships.cs
> +                person.Dogs.Add(dog1);
The dogs are stored in their own collection.

2021-01-04 17:56 UTC, MongoCaleb commented on examples/dotnet/Examples/Relationships.cs
> +            var youngDogs = realm.All<Dog>().Where(d => d.Age == 1);
Again, use the `FirstOrDefault()` here in place of `Where()`

2021-01-05 00:36 UTC, nirinchev reviewed
Looks good - only nits from me.

2021-01-05 00:36 UTC, nirinchev commented on examples/dotnet/Examples/Relationships.cs
> +            var fidosPerson = realm.All<Person>().Where(p => p.Dog == dog).FirstOrDefault();
[nit] `Where(...).FirstOrDefault()` is equivalent to `FirstOrDefault(...)`, so you can simplify the example a little.

2021-01-05 00:36 UTC, nirinchev commented on examples/dotnet/Examples/Relationships.cs
> +            return;
[extreme nit] No need to add a return at the end of a void method

2021-01-05 14:45 UTC, ccho-mongodb commented on source/dotnet/relationships.txt
> +(Inverse queries handled in Caleb's PR)
Is this text rendered on the page? If so, it probably won't make sense to the reader.

2021-01-06 01:27 UTC, nirinchev approved these changes

2021-01-06 14:23 UTC, merged