WIP - Electron CRA QuickStart
mongodb/docs-realm pull request #686
Opened 2021-01-07 03:02 UTC by mongomoe

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-NNNN

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodborg-staging.corp.mongodb.com/NNNNNNN/java/docsworker-xlarge/NNNNNNNNNNN/

2021-01-14 17:30 UTC, cbush requested changes
Good start. A few comments.

2021-01-14 17:30 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  The Electron ``main process`` file can be thought of as the entry
Should this be...?
```suggestion
  The Electron **main process** file can be thought of as the entry
```

2021-01-14 17:30 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +     Each electron application can only have one **main process**. The
```suggestion
     Each Electron application can only have one **main process**. The
```

2021-01-14 17:30 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  All JS Files within the ``src`` directory executes on the ``renderer`` process. The electron.js and any files required by it execute on the ``main process``.
```suggestion
  All JS files within the ``src`` directory executes on the ``renderer`` process. The electron.js and any files required by it execute on the main process.
```

2021-01-14 17:30 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  start`` in another tab. You should see the following:
Why specifically across two tabs?

2021-01-14 17:30 UTC, cbush commented on source/node/electron-cra.txt
> +     await app.logIn(new Realm.Credentials.anonymous());
Is `new` actually used with anonymous()?

2021-01-14 17:30 UTC, cbush commented on source/node/electron-cra.txt
> +   });
Can this snippet be bluehawked?

2021-01-14 20:44 UTC, mongomoe commented on source/node/electron-cra.txt
> +     await app.logIn(new Realm.Credentials.anonymous());
👍

2021-01-14 20:46 UTC, mongomoe commented on source/node/electron-cra.txt
> +   });
It could, it doesn't need to be. It's a standalone single snippet that doesn't need any parsing or for any bits of the code to be stripped out for instructional purposes.

2021-01-14 20:47 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  <https://www.npmjs.com/package/@craco/craco>`_ you can override these
👍

2021-01-14 20:56 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  following. This representation abstracts some files, such as CSS,
It means that the file structure below does not include some of the files that the user would have in their application. The file structure below does not have files, such as CSS files, because it's not relevant to the QuickStart.


How about:

"Your application should include the following files. Some additional files in your project, such as CSS, service worker, and test files aren't included below."


Open to alternatives, I'm not in love with the above sentence either.

2021-01-14 20:56 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  <https://www.npmjs.com/package/@craco/craco>`_ you can override these
👍

2021-01-15 22:20 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  following. This representation abstracts some files, such as CSS,
Your suggestion sounds good!

2021-01-15 22:43 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  following. This representation abstracts some files, such as CSS,
👍

2021-01-15 22:44 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  default configurated values. Install CRACO with the following command:
👍

2021-01-15 22:46 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  start`` in another tab. You should see the following:
Yeah I guess this doesn't need to be two tabs. Fixed it now 👍

2021-01-15 22:48 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  in this case electron's dev tools and webpack. In order to make use of
Fixed, not sure why this keeps being hidden (or if its only hidden to me).

2021-01-15 22:48 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  The Electron ``main process`` file can be thought of as the entry
This is fixed too, not sure again why its hidden

2021-01-15 22:49 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +     Each electron application can only have one **main process**. The
This is fixed too, not sure again why its hidden

2021-01-15 22:49 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  All JS Files within the ``src`` directory executes on the ``renderer`` process. The electron.js and any files required by it execute on the ``main process``.
fixed 👍

2021-01-20 14:49 UTC, cbush approved these changes
Looks good. Just a couple more suggestions.

2021-01-20 14:49 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  Any JS files within the ``src`` directory executes on a ``renderer process``.
```suggestion
  Any JS file within the ``src`` directory executes on a ``renderer process``.
```

2021-01-20 14:49 UTC, cbush commented on source/node/electron-cra.txt
> +Set up
"Setup" is the noun. "Set up" is the verb phrase. (So, if you wanted to leave this as a verb, you would need an object like "Set up the Electron app", but just "Setup" is fine)
```suggestion
Setup
```

2021-01-20 14:49 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +   own process, known as a ``renderer process``. To learn more about
```suggestion
   own process, known as **renderer process**. To learn more about
```

2021-01-20 14:50 UTC, cbush commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +   own process, known as a ``renderer process``. To learn more about
This is to be consistent with the other one in this paragraph. Generally I use bold for new terms and monospace for code things.

2021-01-20 21:59 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +   own process, known as a ``renderer process``. To learn more about
👍

2021-01-20 22:06 UTC, mongomoe commented on source/node/electron-cra.txt
> +Set up
👍

2021-01-20 22:06 UTC, mongomoe commented on source/includes/steps-realm-with-electron-using-create-react-app.yaml
> +  Any JS files within the ``src`` directory executes on a ``renderer process``.
👍

2021-01-20 22:08 UTC, merged