wip-(DOCSP-13339): Sync Changes between devices - node
mongodb/docs-realm pull request #731
Opened 2021-01-28 20:09 UTC by mongomoe

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-NNNN

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodborg-staging.corp.mongodb.com/NNNNNNN/java/docsworker-xlarge/NNNNNNNNNNN/

2021-02-01 19:53 UTC, nathan-contino-mongo approved these changes
LGTM with one issue and a question about the intent of an example.

2021-02-01 19:53 UTC, nathan-contino-mongo commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +   </node/examples/define-a-realm-object-model>` value of a predefined
schema link is broken

2021-02-01 19:53 UTC, nathan-contino-mongo commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +      const realm = await Realm.open(config); // open a Realm
Should we add these snippets to the test apps?
Also, this isn't quite the way I interpreted this example -- I assumed that this section was supposed to be an example of how to handle a client reset in a custom way when the backend tells you that you need to client reset. If I'm misinterpreting the example, let me know and I can update the Android example to align more with this snippet.

2021-02-01 20:10 UTC, nlarew requested changes
Need to update the client reset example + a few nits

2021-02-01 20:10 UTC, nlarew commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +      const realm = await Realm.open(config); // open a Realm
+1 this should describe how to handle client reset errors, specifically show a sync error callback that call [Realm.App.Sync.initiateClientReset()](https://docs.mongodb.com/realm-sdks/js/latest/Realm.App.Sync.html#initiateClientReset).

The process is somewhat vague/manual right now so we don't have to go too in-depth I think. There's a decent code snippet on realm.io docs (https://docs.realm.io/sync/using-synced-realms/errors#client-reset) that can be the base for this.

See this Slack thread for some more info - https://mongodb.slack.com/archives/CL9JSLTGE/p1611689853022500

2021-02-01 20:10 UTC, nlarew commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +with your :js-sdk:`Realm.App <Realm.App.html>`.
nit: might be helpful to include a list of valid log levels since we don't have a resource that describes those that we can link out to.

2021-02-01 20:12 UTC, mongomoe commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +      const realm = await Realm.open(config); // open a Realm
* These snippets should be added to the test apps, I have another ticket for that (https://jira.mongodb.org/browse/DOCSP-13431)
* I see, looks like you're right (Nick clarified below: https://github.com/mongodb/docs-realm/pull/731#discussion_r568102395). Will update this example shortly.

2021-02-01 21:14 UTC, mongomoe commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +   </node/examples/define-a-realm-object-model>` value of a predefined
fixed 👍

2021-02-01 21:19 UTC, mongomoe commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +with your :js-sdk:`Realm.App <Realm.App.html>`.
👍

2021-02-01 22:22 UTC, nlarew reviewed
Left some comments on the updated client reset example. It looks like it's partially copied from the TypeDoc, so these comments apply there too. We should make sure to communicate any changes with the SDK engineers so that the typedoc gets updated.

2021-02-01 22:22 UTC, nlarew commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +            let path = realm.path; // realm.path will no be accessible after realm.close()
```suggestion
            let path = realm.path; // realm.path will not be accessible after realm.close()
```

What does it mean if `realm.path` is not accessible? Does that mean I can't open the realm or something else?

2021-02-01 22:22 UTC, nlarew commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +         error: (_session, error) => {
Why the underscore in `_session`?

Also we should find out what this object actually represents and what its purpose is. It's currently unused in this snippet which is a bit mysterious.

2021-02-01 22:22 UTC, nlarew commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +         }
- Indentation is off here

- Can we add more descriptive code comments? This is a fairly complex snippet so additional context is helpful.

  - What is `realm.path`? (A: The path of the `.realm` file that needs to be reset)
  - Why do we close the realm? (A: You must close a realm before you can reset it)
  - What happens when I call `initiateClientReset()`? (A: The SDK moves the local `.realm` file to a backup directory - located at `error.config.path` - and then creates a new replacemennt `.realm` file that downloads the latest realm state from the server.)

2021-02-01 22:22 UTC, nlarew commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +            Realm.App.Sync.initiateClientReset(app, path);
Can we also include code or comments that describe how to recover unsynced objects from the realm? The typedoc example comments give a decent overview.

2021-02-01 22:22 UTC, nlarew commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +            let path = realm.path; // realm.path will no be accessible after realm.close()
Also where does this `realm` instance come from? We're defining this callback in the config that we use to open the realm, so we don't have access to our realm instance inside the callback.

2021-02-03 16:45 UTC, mongomoe commented
Fyi to all viewers, awaiting comments in slack channel #realm-js-team on further instructions on how to go forward with initiate client reset

2021-02-03 17:00 UTC, mongomoe commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +         error: (_session, error) => {
We discussed this via zoom, but just going to address it here incase any other viewer of this PR is interested:

- The underscore in a parameter is a coding standard that indicates an unused parameter 
- Took some digging but the ```session``` refers to [The session from which the error originates](https://github.com/realm/realm-js/issues/1467)

2021-02-03 21:44 UTC, mongomoe commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +         }
Resolving this as we temporarily removed this "client reset" example from this page, since it's not fully fledged in the JS SDK

2021-02-03 21:44 UTC, mongomoe commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +            Realm.App.Sync.initiateClientReset(app, path);
Resolving this as we temporarily removed this "client reset" example from this page, since it's not fully fledged in the JS SDK

2021-02-03 21:44 UTC, mongomoe commented on source/sdk/node/examples/sync-changes-between-devices.txt
> +         error: (_session, error) => {
Resolving this as we temporarily removed this "client reset" example from this page, since it's not fully fledged in the JS SDK

2021-02-04 00:50 UTC, nlarew commented
LGTM - let's make sure we follow up with additional network/sync progress examples once those are unblocked.

2021-02-04 00:50 UTC, nlarew approved these changes

2021-02-04 18:48 UTC, merged

2021-02-04 18:59 UTC, mongomoe commented
Yup @nlarew created a follow on ticket to create the sync progress example once unblocked. The network examples do not apply to Node itself, but RN only and I created a ticket for it: https://jira.mongodb.org/browse/DOCSP-14354

The client reset examples apply to both RN/Node and here's the follow up ticket for it: https://jira.mongodb.org/browse/DOCSP-14353