Docsp 13336
mongodb/docs-realm pull request #737
Opened 2021-02-01 18:26 UTC by nathan-contino-mongo

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-13336

### Docs staging link (requires sign-in on MongoDB Corp SSO):

2021-02-01 18:55 UTC, cbush approved these changes
LGTM

2021-02-01 18:55 UTC, cbush commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/SyncDataTest.kt
> +            RealmLog.setLevel(LogLevel.ALL)
Just wondering if this has a generated Kotlin setter: `RealmLog.level = LogLevel.ALL`

2021-02-01 19:10 UTC, nathan-contino-mongo commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/SyncDataTest.kt
> +            RealmLog.setLevel(LogLevel.ALL)
It seems that this isn't a standard mutator method tied to a property/auto generated by Kotlin so apparently not! Good catch though, when I ported my java examples over to Kotlin I forgot to check this.

2021-02-02 08:23 UTC, cmelchior requested changes
I added some comments. Generally, it looks good, but I think there are some misconceptions about ConnectionState vs. SessionState that requires a cleanup?

2021-02-02 08:23 UTC, cmelchior commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/SyncDataTest.java
> +                            Assert.assertEquals(ConnectionState.CONNECTING, app.getSync().getSession(config).getConnectionState());
This is a race condition. It could already be CONNECTED here.

2021-02-02 08:23 UTC, cmelchior commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/SyncDataTest.java
> +                            app.getSync().getSession(config).stop();
Minor, but I would extract `val session = app.getSync().getSession(config)` in all of these code snippets. Would make it more readable.

2021-02-02 08:23 UTC, cmelchior commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/SyncDataTest.java
> +                            //Assert.assertEquals(ConnectionState.CONNECTING, app.getSync().getSession(config).getConnectionState());
Not sure why this is commented out?

2021-02-02 08:23 UTC, cmelchior commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/SyncDataTest.java
> +                            Assert.assertEquals(ConnectionState.DISCONNECTED, app.getSync().getSession(config).getConnectionState());
This is actually testing the wrong thing. We have two kinds of state. `SyncSession.getConnectionState()` and `SyncSession.getState()`. Connection state is about the underlying network connection and not wether the session is working or not. In this case you probably wanted to check for `SyncSession.getState() == SyncSession.State.INACTIVE`

2021-02-02 08:23 UTC, cmelchior commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/SyncDataTest.java
> +                            Log.v("EXAMPLE", "Sync state: " + app.getSync().getSession(config).getConnectionState());
Did you want `SyncSession.getState()` here?

2021-02-02 08:23 UTC, cmelchior commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/SyncDataTest.kt
> +                            val tasks = realm.where(Task::class.java).findAll()
We have `realm.where<Task>().findAll()` as a Kotlin extension function to make this more kotlin-friendly.

2021-02-02 08:23 UTC, cmelchior commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/SyncDataTest.kt
> +                                realm.where(
The formatting here looks different than elsewhere?

2021-02-02 08:23 UTC, cmelchior commented on source/examples/generated/android/code/start/SyncDataTest.codeblock.sync-data.kt
> +        val tasks = realm.where(Task::class.java).findAll()
```suggestion
        val tasks = realm.where<Task>().findAll()
```

2021-02-02 08:23 UTC, cmelchior commented on source/sdk/android/examples/sync-changes-between-devices.txt
> +To check the current network connection, call :java-sdk:`getConnectionState() <io/realm/mongodb/sync/SyncSession.html#getConnectionState-->` on your :java-sdk:`SyncSession <io/realm/mongodb/sync/Sync
We should probably describe the difference between the connection and the session states? I.e. multiple users will share the same network connection, but the sync session state is unique and controllable for each session.

This means that you can e.g. have `ConnectionState.CONNECTED && SyncSession.State.INACTIVE` which means that the network is available, but no data is transferred, or `ConnectionState.DISCONNECTED && SyncSession.State.ACTIVE` which means that the session is active, but cannot transfer data because the network is temporarily down (and we will auto-recover it)

2021-02-02 14:29 UTC, nathan-contino-mongo commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/SyncDataTest.java
> +                            //Assert.assertEquals(ConnectionState.CONNECTING, app.getSync().getSession(config).getConnectionState());
Another race condition, unfortunately -- it turns out that because the connection occurs in the background at the leisure of the sync client, the connectionstate can be any of connected/connecting/disconnected here, even after a synchronous  transaction block.

2021-02-02 14:31 UTC, nathan-contino-mongo commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/SyncDataTest.java
> +                            Assert.assertEquals(ConnectionState.DISCONNECTED, app.getSync().getSession(config).getConnectionState());
Thanks, I definitely missed this.

2021-02-02 14:51 UTC, nathan-contino-mongo commented on source/sdk/android/examples/sync-changes-between-devices.txt
> +To check the current network connection, call :java-sdk:`getConnectionState() <io/realm/mongodb/sync/SyncSession.html#getConnectionState-->` on your :java-sdk:`SyncSession <io/realm/mongodb/sync/Sync
Added a warning here.

2021-02-02 15:09 UTC, merged