Define a Realm Object Schema
mongodb/docs-realm pull request #738
Opened 2021-02-01 22:52 UTC by nathan-contino-mongo

## Pull Request Info

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodborg-staging.corp.mongodb.com/NNNNNNN/java/docsworker-xlarge/NNNNNNNNNNN/

2021-02-01 23:34 UTC, terakilobyte requested changes
Solid content, a few issues to address and some nits to think about.

2021-02-01 23:34 UTC, terakilobyte commented on source/sdk/android/examples/define-a-realm-object-model.txt
> +   :ref:`Relationships <android-client-relationships>`
issue: This appears duplicated

2021-02-01 23:34 UTC, terakilobyte commented on source/sdk/android/examples/define-a-realm-object-model.txt
> +   :ref:`Relationships <android-client-relationships>`
issue: This appears duplicated

2021-02-01 23:34 UTC, terakilobyte commented on source/sdk/android/examples/define-a-realm-object-model.txt
> +with whose type is a {+service-short+} object in your application:
```suggestion
whose type is a {+service-short+} object in your application:
```

2021-02-01 23:34 UTC, terakilobyte commented on source/sdk/android/examples/define-a-realm-object-model.txt
> +  follow a :manual:`denormalized data model </manual/core/data-modeling-introduction/>`.
issue: this link doesn't work

2021-02-01 23:34 UTC, terakilobyte commented on source/sdk/android/examples/define-a-realm-object-model.txt
> +  follow a :manual:`denormalized data model </manual/core/data-modeling-introduction/>`.
```suggestion
  follow a :manual:`denormalized data model </core/data-modeling-introduction/>`.
```

2021-02-01 23:34 UTC, terakilobyte commented on source/sdk/android/examples/define-a-realm-object-model.txt
> +      - ``Decimal128``
question: this appears to either contradict or supplement the previous warning about Kotlin types and nullability. Can they be clarified and combined?

2021-02-01 23:34 UTC, terakilobyte commented on source/sdk/android/examples/define-a-realm-object-model.txt
> +Primitive types like ``int`` and the ``RealmList`` type are non-nullable
nitpick: hard to quickly parse.

When I first read this I read it as `RealmList` is a primitive, which surprised me. I looked into it more and there don't appear to be any "primitive" types in Kotlin, do you mean ["basic" types](https://kotlinlang.org/docs/reference/basic-types.html)

 Maybe something like:

All basic types (``Numbers``, ``Strings``, etc...), and the ``RealmList`` type, are non-nullable...

2021-02-01 23:34 UTC, terakilobyte commented on source/sdk/android/examples/define-a-realm-object-model.txt
> +default values.
nitpick: required reading.

It seems this paragraph could be decomposed to its core components and then distributed into the language tabs. That way someone who has been following along with Kotlin doesn't even see the mention of how to do it in Java

2021-02-02 14:22 UTC, nathan-contino-mongo reviewed
@terakilobyte thanks for the review, implemented updates to address your feedback. Please take a look when you get the chance!

2021-02-02 14:51 UTC, terakilobyte approved these changes
lgtm

2021-02-02 14:51 UTC, merged