Fundies
mongodb/docs-realm pull request #786
Opened 2021-02-17 22:53 UTC by MongoCaleb

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-14580

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/fundies/sdk/dotnet/fundamentals/mongodb-realm-cloud/

2021-02-18 03:22 UTC, cbush reviewed
Great first pass! I think this covers all of the intended information. Leaving some comments for now and I'd like to hear your thoughts.

2021-02-18 03:22 UTC, cbush commented on source/sdk/dotnet/fundamentals.txt
> +   MongoDB Realm </sdk/dotnet/fundamentals/mongodb-realm-cloud>
Be sure to put this at the bottom of the list. Top is for local-only (Realm Database, non-Sync, free, etc.) use case.

2021-02-18 03:22 UTC, cbush commented on source/sdk/dotnet/fundamentals/mongodb-realm-cloud.txt
> +:ref:`find your Realm app ID <find-your-app-id>` in the Realm UI.
```suggestion
:ref:`find in the Realm UI <find-your-app-id>`.
```

2021-02-18 03:22 UTC, cbush commented on source/sdk/dotnet/fundamentals/mongodb-realm-cloud.txt
> +The fundamental building block in the SDK is the ``App`` object. It is from this
This is only true for the MongoDB Realm stuff, but not for the database. That is, you don't need to log in or do anything with the app if you aren't using Sync, Functions, Remote MongoDB, or auth. So I would reword this to be less about "the SDK" as a whole and "all functionality" and more about interacting with MongoDB Realm and MongoDB Realm functionality.

2021-02-18 03:22 UTC, cbush commented on source/sdk/dotnet/fundamentals/mongodb-realm-cloud.txt
> +- Multiple concurrent users
Can we clarify this? When we say concurrent, do we mean multiple users logged in at the same time or do we mean allowing you to have different logins/accounts saved on a device?

2021-02-18 03:22 UTC, cbush commented on source/sdk/dotnet/fundamentals/mongodb-realm-cloud.txt
> +Using the {+service-short+} SDKs, you can :ref:`create server-side functions <create-a-function>`,
I don't think you meant _create_ here. But we can call them which is pretty cool too.

2021-02-18 03:22 UTC, cbush commented on source/sdk/dotnet/fundamentals/mongodb-realm-cloud.txt
> +without have to reproduce the logic. Calling functions from your client code is
Typo
```suggestion
without having to reproduce the logic. Calling functions from your client code is 
```

2021-02-18 03:22 UTC, cbush commented on source/sdk/dotnet/fundamentals/mongodb-realm-cloud.txt
> +without have to reproduce the logic. Calling functions from your client code is
This is a good point. What about calling into the "backend as a service" functionality that you have defined? In particular, you can use functions to have server-controlled permissions management.

2021-02-18 03:22 UTC, cbush commented on source/sdk/dotnet/fundamentals/mongodb-realm-cloud.txt
> +{+service-short+}, the Realm SDKs include the APIs for accessing a MongoDB
I'm not sure I get the intention here when you say "most apps don't require...". Is it to appease the sense of feature overload? I'm reading this as a bit of a downplay on the MongoDB Remote Access feature.

2021-02-18 22:54 UTC, cbush commented on source/sdk/dotnet/fundamentals/mongodb-realm-cloud.txt
> +The fundamental building block in the SDK is the ``App`` object. It is from this
Still looking for an update or something here.

2021-02-18 22:55 UTC, cbush reviewed
Looks great. Still wondering about the "fundamental building block" part.

2021-02-18 22:55 UTC, cbush commented on source/sdk/dotnet/fundamentals/mongodb-realm-cloud.txt
> +For more information, see :ref:`Authenticate Users <dotnet-authenticate>`.
It might be nice to actually link out to the individual usage examples/advanced guides pages about each of the above.

2021-02-19 02:01 UTC, nlarew requested changes
A few changes to contextualize to .NET + some broader thoughts

2021-02-19 02:01 UTC, nlarew commented on source/sdk/dotnet/fundamentals/mongodb-realm-cloud.txt
> +The App Client
```suggestion
The Realm App Client
```
nit: For consistency and clarity I think it's a good idea to always specify that it's a _Realm_ app client. This is particularly true given its code type is usually some variant e.g. `RealmApp` or `Realm.App`

2021-02-19 02:32 UTC, nlarew commented
Also looks like some extra commits snuck in here. Let's rebase on top of `new-ia`

2021-02-19 03:52 UTC, MongoCaleb commented on source/sdk/dotnet/fundamentals/mongodb-realm-cloud.txt
> +For more information, see :ref:`Authenticate Users <dotnet-authenticate>`.
Removed the "fundamental building block" stuff (sorry I missed that!).

As for the links, the problem is that the first 2 items in the list really depend on which provider. I can link to the main page, which I do below the list already. I've checked in the list now with the others linked. LMK your thoughts.

2021-02-19 03:55 UTC, MongoCaleb commented on source/sdk/dotnet/fundamentals/mongodb-realm-cloud.txt
> +=======================================
Other than esthetic, it's not a problem to have them longer than the text. But fixed.

2021-02-19 04:04 UTC, MongoCaleb commented on source/sdk/dotnet/fundamentals/mongodb-realm-cloud.txt
> +   you are working with and look under **Usage Examples**.
I was intentionally writing it to be generic enough that we could copy-paste without too much replacement, but I see now that's kinda silly....

2021-02-19 04:06 UTC, MongoCaleb commented on source/sdk/dotnet/fundamentals/mongodb-realm-cloud.txt
> +For more information, see :ref:`Authenticate Users <dotnet-authenticate>`.
@nlarew @cbush now that I'm seeing the staging, I really don't like having some items linked and others not.

2021-02-19 04:21 UTC, MongoCaleb commented on source/sdk/dotnet/fundamentals/mongodb-realm-cloud.txt
> +collection.
@nlarew LMK what you think of the change.

2021-02-19 21:49 UTC, cbush reviewed
Page looks great, but something doesn't look right with this git history. I would reset to upstream/new-ia and cherry-pick all of the relevant commits, then force push back up.

2021-02-19 22:41 UTC, closed without merging