(DOCSP-14676) iOS Local-Only Quickstart
mongodb/docs-realm pull request #829
Opened 2021-02-25 22:17 UTC by dacharyc

## Pull Request Info

Draft PR: currently just a code example.

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-14676

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodborg-staging.corp.mongodb.com/realm/docsworker-xlarge/ios-local-quickstart/

### Docs staging build link:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60381edc75e817aef7136ea0

### Review Guidelines
[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-02-25 22:37 UTC, cbush reviewed
One formatting issue. Otherwise, code looks great.

2021-02-25 22:37 UTC, cbush commented on examples/ios/Examples/LocalOnlyCompleteQuickStart.swift
> +        // Get all tasks in the realm
This line and everything below it to the end of the function must be dedented by 1.

2021-02-25 22:37 UTC, cbush commented on examples/ios/Examples/LocalOnlyCompleteQuickStart.swift
> +        gExpectation!.fulfill()
It seems we should be able to get rid of gExpectation completely.

2021-02-26 19:13 UTC, cbush requested changes
Great first start! Let's get all of those code blocks into Bluehawk. Thanks!

2021-02-26 19:13 UTC, cbush commented on source/sdk/ios.txt
> +   Quick Start Local </sdk/ios/quick-start-local>
From the user's perspective, "local" should be default and they won't know what we mean by local-only. Sync is the add-on, so we need not say local. (If possible, please update the file name too)
```suggestion
   Quick Start </sdk/ios/quick-start-local>
```

2021-02-26 19:13 UTC, cbush commented on source/sdk/ios/quick-start-local.txt
> +Quick Start (Local-only) - iOS SDK
I would also remove "Local-only" here.

2021-02-26 19:13 UTC, cbush commented on source/sdk/ios/quick-start-local.txt
> +This page contains information to quickly get started with a local-only
I know this is inherited, but maybe we should replace this "Overview" with a "Prerequisites" section that jumps straight into the bullet list. The preamble here feels redundant.

2021-02-26 19:13 UTC, cbush commented on source/sdk/ios/quick-start-local.txt
> +   a local-only {+client-database+}. For a quickstart featuring communicating
I would remove this first line. I feel we're really looking at this as if people are assuming Realm Sync is the default, but they won't be.

2021-02-26 19:13 UTC, cbush commented on source/sdk/ios/quick-start-local.txt
> +.. code-block:: swift
The Sync quick start was written well before Bluehawk 0.1 which supports nested code snippets. So you can now go through and add code-block tags around each of these things you want to include.

2021-02-26 21:48 UTC, dacharyc commented on source/sdk/ios/quick-start-local.txt
> +.. _ios-client-quick-start-local:
So question, @cbush - does removing the "local-only" references you identified in your comments preclude us from using "local" in the :ref: label here? The existing quick start, which is now "Quick Start with Sync" uses the plain quick start label: `.. _ios-client-quick-start:`. 

Should I: 
A) Change that to `.. _ios-client-quick-start-with-sync:` (and update associated :ref: links to it) and then use `.. _ios-client-quick-start:` here, or;
B) Leave this `local` in the :ref: label since that's really just for internal use?

2021-02-26 21:55 UTC, cbush commented on source/sdk/ios/quick-start-local.txt
> +.. _ios-client-quick-start-local:
I would do A, because refs do show up as anchor links (# in URL). That said, it's not a big deal to have -local in there too.

2021-02-26 22:00 UTC, dacharyc commented on source/sdk/ios.txt
> +   Quick Start Local </sdk/ios/quick-start-local>
I'll make these changes, but I'm wondering if leaving the "local" would be helpful for users who are aware there is both a local-only Realm and a Realm w/Sync option. Having "local" in the title and key places in the doc might make it easier for folks who are specifically looking for local-only documentation to identify this as the right page for them. Thoughts?

2021-02-26 22:16 UTC, dacharyc commented on source/sdk/ios/quick-start-local.txt
> +.. _ios-client-quick-start-local:
So in updating the associated :ref: links, I see there's a link in the "Check Out the Quick Start" note admonition on the Swift Task Tracker tutorial (ios-swift.txt): 

>If you prefer to explore on your own rather than follow a guided tutorial,
   check out the :ref:`iOS Quick Start <ios-client-quick-start>`. It includes
   copyable code examples and the essential information that you need to set up
   a MongoDB Realm application.

Since the tutorial features sync, I assume this should point to the "with Sync" quick start?

2021-03-01 16:11 UTC, cbush commented on source/sdk/ios/quick-start-local.txt
> +.. _ios-client-quick-start-local:
Yes, I would link to the "with Sync" version there.

2021-03-01 16:12 UTC, cbush approved these changes
Looks good! Could you ask the Realm Swift team to take a look?

2021-03-05 19:20 UTC, merged