WIP- (DOCSP-14303): Terminating and Reenabling Sync
mongodb/docs-realm pull request #831
Opened 2021-02-26 03:45 UTC by mongomoe

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-NNNN

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodborg-staging.corp.mongodb.com/NNNNNNN/java/docsworker-xlarge/NNNNNNNNNNN/

### Docs staging build link:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=NNNNNNNNNNNNNNNNNNNNNN

### Review Guidelines
[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-02-26 23:37 UTC, nathan-contino-mongo requested changes
Looking good (nice screenshots!), I think we can clean up some of the wording on the "Terminate Realm Sync" page to clarify concepts to users. Also gerunds.

2021-02-26 23:37 UTC, nathan-contino-mongo commented on source/includes/steps-upgrade-shared-cluster.yaml
> +  <terminating-realm-sync>` instructions.
Nit: I'm not sure why this reads so wrong to me, but I feel like this would read better as:
```
To terminate {+sync+}, follow the instructions for :ref:`Terminating Realm Sync
  <terminating-realm-sync>`.
```

2021-02-26 23:37 UTC, nathan-contino-mongo commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +- When upgrading from a Shared Tier {+atlas-short+} Cluster (either to a Shared or Dedicated instance)
Suggestion: keep bullet point wording consistent with the intro you established above "for one of the following reasons":
```suggestion
- An upgrade from a Shared Tier {+atlas-short+} Cluster to a Shared or Dedicated instance
```

2021-02-26 23:37 UTC, nathan-contino-mongo commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +- When moving an {+atlas-short+} cluster across regions/cloud providers
Similarly,
```suggestion
- A move to an {+atlas-short+} cluster that is distributed across regions/cloud providers
```
Note: is there a proper name for this? I couldn't find one with a short search, but maybe the Atlas team knows.

2021-02-26 23:37 UTC, nathan-contino-mongo commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +- When upgrading NVMe Atlas clusters
```suggestion
- Any upgrade to NVMe Atlas clusters
```

2021-02-26 23:37 UTC, nathan-contino-mongo commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +- If the Oplog rolls over due to a Bug or misconfiguration
```suggestion
- An :manual:`oplog </core/replica-set-oplog/>` rollover
```

2021-02-26 23:37 UTC, nathan-contino-mongo commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +- If {+sync+} becomes paused on a shared tier cluster with in-frequent usage
```suggestion
- A paused {+sync+} session on a shared tier cluster due to in-frequent usage 
```

2021-02-26 23:37 UTC, nathan-contino-mongo commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +- For certain troubleshooting steps (at the request of MongoDB Support)
```suggestion
- troubleshooting, at the request of MongoDB Support
```

2021-02-26 23:37 UTC, nathan-contino-mongo commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +Terminate {+sync+} in your {+backend+} application to stop syncing data across
Suggestion: You can actually use the {+app+} source constant here ("Realm App") to refer to an individual instance of the MongoDB Realm backend
```suggestion
Terminate {+sync+} in your {+app+} to stop syncing data across
```

2021-02-26 23:37 UTC, nathan-contino-mongo commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +.. warning::
We should probably create a title for this warning -- maybe "Terminating Sync may Lose Unsynced Client Changes"

2021-02-26 23:37 UTC, nathan-contino-mongo commented on source/reference/terminating-and-reenabling-realm-sync.txt
> + synced yet from syncing. If you plan on terminating Sync in production and wish
two occurrences of "sync" in the last four words of a sentence feels repetitive to me. I would suggest something like:

```
Terminating and re-enabling {+sync+} prevents unsynchronized
client changes from automatically syncing. To recover any
unsychronized changes, implement a manual client reset
that handles this case in your client applications:
```

2021-02-26 23:37 UTC, nathan-contino-mongo commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +Terminating/Reenabling Realm Sync
```suggestion
Terminate Realm Sync
```
I figure that @nlarew will come after you with some kind of weapon if you add a _double_ gerund page to his toctree 😉

2021-03-01 19:49 UTC, mongomoe commented on source/includes/steps-upgrade-shared-cluster.yaml
> +  <terminating-realm-sync>` instructions.
👍

2021-03-01 19:53 UTC, mongomoe commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +- When moving an {+atlas-short+} cluster across regions/cloud providers
There is no proper name to describe moving a cluster to a different region - https://docs.atlas.mongodb.com/tutorial/move-cluster/

2021-03-01 19:54 UTC, mongomoe commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +- When upgrading NVMe Atlas clusters
Did you mean: `An upgrade to NVMe Atlas clusters`?

2021-03-01 19:56 UTC, mongomoe commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +- If the Oplog rolls over due to a Bug or misconfiguration
👍

2021-03-01 19:56 UTC, mongomoe commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +- If {+sync+} becomes paused on a shared tier cluster with in-frequent usage
👍

2021-03-01 19:57 UTC, mongomoe commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +- For certain troubleshooting steps (at the request of MongoDB Support)
👍

2021-03-01 19:57 UTC, mongomoe commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +Terminate {+sync+} in your {+backend+} application to stop syncing data across
👍

2021-03-01 20:00 UTC, mongomoe commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +.. warning::
Adding a title sounds good, but I don't think that suggestion captures everything in the note. How about: "Preventing loss of unsynced changes when terminating Realm Sync"?

2021-03-01 20:03 UTC, mongomoe commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +.. warning::
or more simply "Preventing loss of unsynchronized changes"

2021-03-01 20:07 UTC, mongomoe commented on source/reference/terminating-and-reenabling-realm-sync.txt
> + synced yet from syncing. If you plan on terminating Sync in production and wish
👍

2021-03-01 20:09 UTC, mongomoe commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +Terminating/Reenabling Realm Sync
The page title was actually a request from Drew. Given that this is nested within "Reference", I think forgoing the single gerund is fine in this case.

2021-03-01 21:49 UTC, nathan-contino-mongo commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +- When upgrading NVMe Atlas clusters
I actually did mean "any" in my suggestion but that works too, probably better tbh.

2021-03-01 21:49 UTC, nathan-contino-mongo commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +.. warning::
How about "Recovering Unsynchronized Changes after Terminating Sync"?

2021-03-01 21:50 UTC, nathan-contino-mongo commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +Terminating/Reenabling Realm Sync
I personally feel like a slash and double gerund is pretty awkward for a page title -- after all, this page only discusses terminating sync, and just points you elsewhere to re-enable it -- but how about this:

"Terminating & Re-enabling Realm Sync"

2021-03-02 18:00 UTC, mongomoe commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +- When upgrading NVMe Atlas clusters
done 👍

2021-03-02 18:00 UTC, mongomoe commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +.. warning::
That works for me! 👍

2021-03-02 18:01 UTC, mongomoe commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +Terminating/Reenabling Realm Sync
👍

2021-03-02 18:10 UTC, nathan-contino-mongo approved these changes
LGTM mod two nitpicks!

2021-03-02 18:10 UTC, nathan-contino-mongo commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +- A paused {+sync+} session on a shared tier cluster due to in-frequent usage
```suggestion
- A paused {+sync+} session on a shared tier cluster due to infrequent usage 
```
infrequent should not be hyphenated, it's just a normal word

2021-03-02 18:10 UTC, nathan-contino-mongo commented on source/reference/terminating-and-reenabling-realm-sync.txt
> +- troubleshooting, at the request of MongoDB Support
```suggestion
- Troubleshooting, at the request of MongoDB Support
```
Capitalize for parity with other bullet points

2021-03-02 18:16 UTC, merged