Add Dictionaries and Sets, and update to Collections
mongodb/docs-realm pull request #835
Opened 2021-03-01 18:25 UTC by MongoCaleb

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-14562
https://jira.mongodb.org/browse/DOCSP-14570

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/dicts_and_sets/sdk/dotnet/data-types/dictionaries/
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/dicts_and_sets/sdk/dotnet/data-types/sets/
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/dicts_and_sets/sdk/dotnet/data-types/collections/

### Docs staging build link:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=603d307c75e817aef7f40cc4

### Review Guidelines
[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-03-01 18:46 UTC, nirinchev reviewed
A few quick corrections about dictionaries. Will review the rest later today.

2021-03-01 18:46 UTC, nirinchev commented on source/sdk/dotnet/data-types/dictionaries.txt
> +:ref:`{+service-short+} type <dotnet-objects>` except :ref:`dotnet-client-collections`.
The `dotnet-client-collections` ref renders as "values of any Realm type except Collections - .NET SDK." which reads pretty weird.

2021-03-01 18:46 UTC, nirinchev commented on source/sdk/dotnet/data-types/dictionaries.txt
> +in which it existed. Therefore, a dictionary of objects will never contain null objects.
This is not true - it will set the value to `null`, but the key will remain.

2021-03-01 18:46 UTC, nirinchev commented on source/sdk/dotnet/data-types/dictionaries.txt
> +the dictionary declaration (for example, use ``IDictionary<double>`` instead of
These definitions need to be `IDictionary<string, double>`, etc.

2021-03-01 18:46 UTC, nirinchev commented on examples/dotnet/Examples/DataTypes.cs
> +            // objects that inherit from RealmObject
or EmbeddedObject

2021-03-01 18:46 UTC, nirinchev commented on source/sdk/dotnet/data-types/dictionaries.txt
> +   You cannot query against a {+service-short+} Dictionary.
This is true for LINQ, but not for string queries. String queries are fully supported and have the following syntax (which is common for all SDKs, so probably a good idea to extract it to a shared page):

```csharp
// Find all Inventory items that have "Petunia" as a key in their PlantDict.
var matches = realm.All<Inventory>().Filter("PlantDict.@keys == 'Petunia'");

// Find all Inventory items that have at least one value in their IntDict that is larger than 5
var matches = realm.All<Inventory>().Filter("IntDict.@values > 5");

// Find all Inventory items where StringDict has the key "Foo" and its value
// contains the phrase "bar" regardless of what the case is
var matches = realm.All<Inventory>().Filter("StringDict['Foo'] CONTAINS[c] 'bar'");
```

2021-03-01 19:19 UTC, MongoCaleb commented on source/sdk/dotnet/data-types/dictionaries.txt
> +   You cannot query against a {+service-short+} Dictionary.
@nirinchev on the last example, since keys are unique, finding a key of "Foo" will always result in 0 or 1 results, right? So the rest of that query (the contains) isn't necessary. Yes?

2021-03-01 19:32 UTC, nirinchev commented on source/sdk/dotnet/data-types/dictionaries.txt
> +   You cannot query against a {+service-short+} Dictionary.
This is filtering for inventory objects, each of which contains a dictionary. It may or may not contain the Foo key and many dictionaries can contain it. The [c] part is the query syntax for case insensitive.

2021-03-01 19:45 UTC, MongoCaleb commented on source/sdk/dotnet/data-types/dictionaries.txt
> +   You cannot query against a {+service-short+} Dictionary.
Also, I'll need examples for Sets, too, as I can't get them working correctly.

2021-03-02 17:21 UTC, cbush requested changes
Looks great. Blocking until available.

2021-05-04 17:43 UTC, merged