Update "Define a Function" and "External Dependencies"
mongodb/docs-realm pull request #869
Opened 2021-03-09 18:50 UTC by MongoCaleb

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-14954
https://jira.mongodb.org/browse/DOCSP-14955

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli/functions/define-a-function/
and
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/cli/functions/upload-external-dependencies/

### Review Guidelines
[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-03-09 19:53 UTC, mongomoe commented on source/includes/steps-define-a-function-import-export.yaml
>    To create new function with :doc:`realm-cli
```suggestion
  To create a new function with :doc:`realm-cli
```

I realize this isn't part of your PR, but this should prob be fixed.

2021-03-09 20:16 UTC, mongomoe approved these changes
lgtm

2021-03-09 20:23 UTC, nlarew requested changes
Overall looks good, just a few small changes & comments. Also they're not in the diff, but let's update the CLI Version note at the start of each Realm CLI procedure tab to indicate the procedure is updated for v2 (e.g. https://github.com/mongodb/docs-realm/blob/cli/source/mongodb/enforce-a-document-schema.txt#L44)

2021-03-09 20:23 UTC, nlarew commented on source/includes/steps-define-a-function-import-export.yaml
> +   .. code-block:: json
nit: indentation is off for this code block

2021-03-09 20:23 UTC, nlarew commented on source/includes/steps-define-a-function-import-export.yaml
> +  - **System**
Love the bullets vs the old table!

2021-03-09 20:23 UTC, nlarew commented on source/includes/steps-define-a-function-import-export.yaml
> +  Set User Authentication
Thoughts on bumping these headings up as individual steps? I could see arguments both ways.

2021-03-09 20:23 UTC, nlarew commented on source/includes/steps-define-a-function-import-export.yaml
> +  function.
`<function name>/source.js` is the old format - now it's `functions/**/<function name>.js`

2021-03-09 20:23 UTC, nlarew commented on source/includes/steps-define-a-function-import-export.yaml
> +  A. Ensure that your changes to ``config.json`` and ``source.js`` are saved.
- Need to update `source.js` -> `<function name>.js` here too
- Thoughts on framing this around "deploy the function" + removing the nested list? [example](https://github.com/mongodb/docs-realm/blob/cli/source/includes/steps-enforce-a-document-schema-import-export.yaml#L110-L115)

2021-03-09 22:22 UTC, MongoCaleb commented on source/includes/steps-define-a-function-import-export.yaml
> +  You can :doc:`pull </deploy/export-realm-app>` your application from the
![image](https://user-images.githubusercontent.com/32645888/110546047-d76ad880-80e2-11eb-8585-8074ec96d1c4.png)

2021-03-09 22:23 UTC, MongoCaleb commented on source/includes/steps-define-a-function-import-export.yaml
> +  Set User Authentication
They were, and I didn't like the way it scanned.

2021-03-09 22:33 UTC, MongoCaleb commented on source/includes/steps-define-a-function-import-export.yaml
> +  A. Ensure that your changes to ``config.json`` and ``source.js`` are saved.
![image](https://user-images.githubusercontent.com/32645888/110547141-5f051700-80e4-11eb-96de-eb67ff3f230a.png)

2021-03-10 20:14 UTC, nlarew commented on source/includes/steps-define-a-function-import-export.yaml
> +  You can :doc:`pull </deploy/export-realm-app>` your application from the
nit: let's change **Import/Export App** to just **Export App** to match the UI when this goes live

2021-03-10 20:16 UTC, nlarew commented on source/includes/steps-define-a-function-import-export.yaml
> +  function.
nit: a couple tweaks on this, basically to match the app structure page

* adds config.json
* fixes pipe character styling

```
app/
└── functions/
    ├── config.json
    ├── <function name>.js
    └── <directory>/
        └── <function name>.js


```

2021-03-10 20:17 UTC, nlarew approved these changes
LGTM % two more nits

2021-03-10 23:14 UTC, merged