(DOCSP-14627) Getting Help Doc
mongodb/docs-realm pull request #884
Opened 2021-03-15 18:40 UTC by mongomoe

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-14627

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodborg-staging.corp.mongodb.com/NNNNNNN/java/docsworker-xlarge/NNNNNNNNNNN/

### Job:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=604fa9be75e817aef75c4b61

### Review Guidelines
[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-03-15 19:10 UTC, nathan-contino-mongo requested changes

2021-03-15 19:10 UTC, nathan-contino-mongo commented on source/get-started/getting-help.txt
> +      :github:`Request a feature <https://github.com/realm/realm-java/issues/new?template=feature_request.md>`, :github:`report a bug <https://github.com/realm/realm-java/issues/new?template=bug_repo
All of these links are broken because you've included the "github.com" suffix in `:github:` extlinks.

2021-03-15 19:10 UTC, nathan-contino-mongo commented on source/get-started/getting-help.txt
> +      :github:`Request a feature <https://github.com/realm/realm-java/issues/new?template=feature_request.md>`, :github:`report a bug <https://github.com/realm/realm-java/issues/new?template=bug_repo
The changelogs are already linked in each SDK's toctree, so I think we should just remove the changelog link here.

2021-03-15 19:10 UTC, nathan-contino-mongo commented on source/get-started/getting-help.txt
> +      :github:`Request a feature <https://github.com/realm/realm-java/issues/new?template=feature_request.md>`, :github:`report a bug <https://github.com/realm/realm-java/issues/new?template=bug_repo
Is github the preferred way to request a feature or report a bug these days, since Mongo uses JIRA for that stuff? Should we reach out to each SDK and ask them their preferred method, since I know many of the SDK teams still use github issues for some of those things?

2021-03-15 19:10 UTC, nathan-contino-mongo commented on source/get-started/getting-help.txt
> +We offer professional support for {+service+} apps. Paid support includes help
A lot of "we"s on this page. Since our docs tend to use "we" sparingly, should we reword this?

2021-03-15 19:10 UTC, nathan-contino-mongo commented on source/get-started/getting-help.txt
> +realm-related question <https://stackoverflow.com/questions/ask?tags=realm>`_ or
Realm the product should be capitalized, and should use the `{+service-short+}` source constant when possible.

2021-03-16 18:43 UTC, mongomoe commented on source/get-started/getting-help.txt
> +      :github:`Request a feature <https://github.com/realm/realm-java/issues/new?template=feature_request.md>`, :github:`report a bug <https://github.com/realm/realm-java/issues/new?template=bug_repo
* Fixed the broken github links
* The changelogs aren't in the TOC tree for each SDK (except android, but that might be bug because the link says 'release notes' but links to the [changelog](https://github.com/realm/realm-java/blob/releases/CHANGELOG.md) instead of the [release notes](https://github.com/realm/realm-java/releases). But to be fair, the release notes on Android look pretty barren compared to the JS ones) . The release notes are on the TOC, but the release notes != changelog (https://stackoverflow.com/questions/51621400/what-is-difference-between-release-notes-and-changelog). 
* Double checked with Ian and the preferred way is to use the [feedback engine  ](https://feedback.mongodb.com/forums/923521-realm/filters/top) for feature requests and github issues for bug reporting. I think JIRA might just be internally how we would report a bug/issue (depending on the SDK), but might not be how we want to tell users to do it publicly.

2021-03-16 18:43 UTC, mongomoe commented on source/get-started/getting-help.txt
> +      :github:`Request a feature <https://github.com/realm/realm-java/issues/new?template=feature_request.md>`, :github:`report a bug <https://github.com/realm/realm-java/issues/new?template=bug_repo
Fixed the links for the feature request as well ^

2021-03-16 18:45 UTC, mongomoe commented on source/get-started/getting-help.txt
> +realm-related question <https://stackoverflow.com/questions/ask?tags=realm>`_ or
Fixed, thanks!

2021-03-16 18:46 UTC, mongomoe commented on source/get-started/getting-help.txt
> +We offer professional support for {+service+} apps. Paid support includes help
Fixed - replaced the "we" statements with "MongoDB"

2021-03-16 18:55 UTC, nathan-contino-mongo commented on source/get-started/getting-help.txt
> +      :github:`Request a feature <https://github.com/realm/realm-java/issues/new?template=feature_request.md>`, :github:`report a bug <https://github.com/realm/realm-java/issues/new?template=bug_repo
Glad to hear we cleared up the links and figured out better links for the issue reporting/feature requests. Personally I'm glad that github issues still has its place in the new workflow, since JIRA has a tendency to become a place where feature requests go to die.

The only one I'll (agree to) disagree on is the changelog/release notes split: while I would agree that for an application those two are very distinct concepts, for an SDK, particularly an open-source SDK, I would argue that the distinction is blurred so heavily that it's essentially meaningless (anything that's important enough to show up in Release Notes is likely technical with an SDK; any detail that's meaningless to end users probably doesn't even belong in the changelog). But I think it's fair to link the changelogs here since you're right -- they really are distinct for some of the SDKs!

2021-03-16 19:05 UTC, nathan-contino-mongo reviewed
Looking good, last round of nits

2021-03-16 19:05 UTC, nathan-contino-mongo commented on source/get-started/getting-help.txt
> +      :github:`Report a bug <realm/realm-js/issues/new>`,  or :github:`view the changelog <realm/realm-js/blob/master/CHANGELOG.md>` for the Node.js, React Native, or Web SDK.
```suggestion
      For the Node.js, React Native, or Web SDKs:
      - :github:`Report a bug <realm/realm-js/issues/new>`
      - :github:`View the changelog <realm/realm-js/blob/master/CHANGELOG.md>`
```

2021-03-16 19:05 UTC, nathan-contino-mongo commented on source/get-started/getting-help.txt
> +----------------
Most of docs-realm includes a space for ease of reading between section headers and section text. Could we add one here? I also noticed that this page uses double newlines between some sections (such as just before the "Feature Requests" header and the "Professional Support" header) and single newlines between others -- for consistency, it would be nice if we could consolidate all of those at single newlines.

2021-03-16 19:21 UTC, mongomoe commented on source/get-started/getting-help.txt
> +----------------
fixed

2021-03-16 19:33 UTC, mongomoe commented on source/get-started/getting-help.txt
> +{+service-short+} related question <https://stackoverflow.com/questions/ask?tags=realm>`_ or
Yup - fixed, should lead you to the realm tagged questions now

2021-03-16 19:34 UTC, mongomoe commented on source/get-started/getting-help.txt
> +{+service-short+} related question <https://stackoverflow.com/questions/ask?tags=realm>`_ or
It was just originally just the wrong link rather than an issue w/ not being logged in

2021-03-16 19:41 UTC, nathan-contino-mongo approved these changes
LGTM!

2021-03-16 20:31 UTC, merged