(DOCSP-14644) Add Property Cheatsheet for both Swift and Objective-C
mongodb/docs-realm pull request #888
Opened 2021-03-16 01:40 UTC by dacharyc

## Pull Request Info

Couple of notes:
- The property cheat sheet from the Realm legacy doc site lists Float, which is not on our current page listing supported property types, but there are tests for it in the realm-cocoa repo.
- The property cheat sheet page from the Realm legacy docs does _not_ list Decimal128, which _is_ on our current page listing supported property types, so I've attempted to add appropriate declarations, but would love confirmation that I've done it correctly.

The Jira ticket doesn't request the Objective-C property cheatsheet, but since both tabs exist in our current documentation set, I've ported over the Objective-C properties, too.

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-14644

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14644/sdk/ios/data-types/supported-property-types/

### Review Guidelines
[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-03-16 15:20 UTC, nathan-contino-mongo approved these changes
LGTM with some small nitpicks. Looks great!

2021-03-16 15:20 UTC, nathan-contino-mongo commented on source/sdk/ios/data-types/supported-property-types.txt
>        - User-defined :swift-sdk:`Object <Extensions/Object.html>`- and
For consistency, I would stick to either including or excluding "user defined Object" in both tables, since it's mentioned below each of them.

2021-03-16 15:25 UTC, nathan-contino-mongo commented on source/sdk/ios/data-types/supported-property-types.txt
>        - User-defined :objc-sdk:`RLMObject<Classes/RLMObject.html>`- and
Boy, could we use monospace-formatted links...

2021-03-16 16:45 UTC, cbush commented on source/sdk/ios/data-types/supported-property-types.txt
> +           - ``@property NSNumber<RLMBool> *value;``
NSNumber is not a supported type in Swift, I guess because it can't be specialized for a specific numeric type like in Obj-C (i.e. `NSNumber<RLMInt>`).

Realm property types must be representable in Obj-C (hence the `@objc dynamic ...` annotation). Realm depends on this to be able to dynamically see which properties a class has so it can be represented in the database. `Int?` (i.e. optional Int) cannot be represented in Obj-C, so you need another way to represent a number as an Objective-C class instance.

2021-03-16 17:59 UTC, dacharyc commented on source/sdk/ios/data-types/supported-property-types.txt
>        - User-defined :objc-sdk:`RLMObject<Classes/RLMObject.html>`- and
YES!

2021-03-18 14:43 UTC, cbush requested changes
See suggestions.

2021-03-18 14:43 UTC, cbush commented on source/sdk/ios/data-types/supported-property-types.txt
> +           - ``@property RLMArray<MyArray *><MyArray> *arrayItems;``
Not MyArray - MyClass
```suggestion
           - ``@property RLMArray<MyClass *><MyClass> *arrayItems;``
```

2021-03-18 14:43 UTC, cbush commented on source/sdk/ios/data-types/supported-property-types.txt
> +           - ``@property RLMArray<MyArray *><MyArray> *arrayItems;``
```suggestion
           - ``@property RLMArray<MyClass *><MyClass> *items;``
```

2021-03-18 14:43 UTC, cbush commented on source/sdk/ios/data-types/supported-property-types.txt
> +           - ``@property RLMArray<MyArray *><MyArray> *arrayItems;``
I think it would be more conventional to drop "array" (even for example):
```suggestion
           - ``@property RLMArray<MyArray *><MyArray> *items;``
```

2021-03-18 14:43 UTC, cbush commented on source/sdk/ios/data-types/supported-property-types.txt
> +           - ``@interface MyClass : RLMObject``
```suggestion
           - ``@property MyClass *value;``
```

2021-03-18 15:18 UTC, cbush approved these changes
Few more minor comments. Looks good!

2021-03-18 15:18 UTC, cbush commented on source/sdk/ios/data-types/supported-property-types.txt
> +         * - Bool
This "type" column actually seems redundant on the Obj-C side. Swift used type inference so it's useful to have the type explicitly listed, but the type is always after "@property" in Obj-C. In any case, these are generally using the Swift type names so we might want to use the proper Obj-C name (i.e. `BOOL`, `int`, etc.) or a more generic name (boolean, integer, etc.).

2021-03-18 15:18 UTC, cbush commented on source/sdk/ios/data-types/supported-property-types.txt
> +           - ``@objc dynamic var decimalOpt: Decimal128?``
Minor: I would avoid baking the optionality into the name.
```suggestion
           - ``@objc dynamic var decimal: Decimal128?``
```

2021-03-18 15:18 UTC, cbush commented on source/sdk/ios/data-types/supported-property-types.txt
> +           - ``@objc dynamic var objectIdOpt: ObjectId?``
```suggestion
           - ``@objc dynamic var objectId: ObjectId?``
```

2021-03-18 15:18 UTC, cbush commented on source/sdk/ios/data-types/supported-property-types.txt
> +           - ``@objc dynamic var objectId = ObjectId()``
Perhaps:
```suggestion
           - ``@objc dynamic var objectId = ObjectId.generate()``
```

2021-03-18 16:45 UTC, dacharyc commented on source/sdk/ios/data-types/supported-property-types.txt
> +         * - Bool
One nice thing about the "type" column in the Obj-C table is that it gives me a place to link out to the SDK docs for things like `RLMObjectId`, `RLMArray`, and `User-defined RLMObject`. I think I'd prefer to keep it, but your point is valid re: the Swift type names. I'll swap Bool and Int to more generic names.

2021-03-18 19:11 UTC, merged