(DOCSP-14982): New Swift SDK landing page
mongodb/docs-realm pull request #913
Opened 2021-03-23 16:08 UTC by dacharyc

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-14982

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14982/sdk/ios/

### Review Guidelines
[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-03-23 18:52 UTC, cbush approved these changes
Looks good! Just a few comments for your consideration.

2021-03-23 18:52 UTC, cbush commented on examples/ios/Examples/LandingPageCodeExamples.swift
> +    func landingPageExamples_objectNotificationExample() {
It's not really required to namespace this function ("landingPageExamples_...") since it's already [scoped](https://docs.swift.org/swift-book/ReferenceManual/Declarations.html) by the class. We only use the prefix to prevent global namespace pollution as in the case of Realm object classes, which much be declared at the module (top) level and therefore can be seen by any Swift file in this module.

2021-03-23 18:52 UTC, cbush commented on examples/ios/Examples/LandingPageCodeExamples.swift
> +        try! realm.write {
Why not include this in the snippet? Makes it a bit longer, but then someone can easily copy and paste. Or add it to a "write" example earlier on.

2021-03-23 18:52 UTC, cbush commented on examples/ios/Examples/LandingPageCodeExamples.swift
> +        expectation.fulfill()
I don't think you need to use expectations here at all, since all of the code in this function is synchronous, and you're not waiting for anything.

2021-03-23 18:52 UTC, cbush commented on source/sdk/ios.txt
> +stored in local {+realms+} and interact with {+backend+} services like
It might be worth finding some way to emphasize that all MongoDB Realm/Atlas/App Services stuff is optional.
```suggestion
stored in local {+realms+} and optionally interact with {+backend+} services like
```

2021-03-23 18:52 UTC, cbush commented on source/sdk/ios.txt
> +Query Realm Database
This page seems to be missing the important "write an object".

2021-03-23 18:52 UTC, cbush commented on examples/ios/Examples/LandingPageCodeExamples.swift
> +
Deleting this (blank) line prevents double blank lines in the bluehawked output. (Unless you keep the above snippet).
```suggestion
```

2021-03-23 18:52 UTC, cbush commented on examples/ios/Examples/LandingPageCodeExamples.swift
> +        print("Well-rated drinks: \(wellRatedDrinks.count)")
Perhaps "Highly rated"?

2021-03-23 19:15 UTC, dacharyc commented on examples/ios/Examples/LandingPageCodeExamples.swift
> +    func landingPageExamples_objectNotificationExample() {
That's helpful - thank you!

2021-03-23 19:59 UTC, dacharyc commented on source/sdk/ios.txt
> +Query Realm Database
Huh, good point! Added it - thanks!

2021-03-23 19:59 UTC, dacharyc commented on source/sdk/ios.txt
> +stored in local {+realms+} and interact with {+backend+} services like
I rewrote this intro section a little bit to emphasize that. Thanks!

2021-03-23 20:03 UTC, dacharyc commented on examples/ios/Examples/LandingPageCodeExamples.swift
> +        try! realm.write {
I wanted to keep the snippets short and easily scannable for folks who just wanted a quick overview. But I did add this as a write example earlier on, and refactored the tests a little bit. Would you please take another look and make sure everything looks good, @cbush ?

2021-03-23 23:51 UTC, cbush approved these changes
Looks great!

2021-03-23 23:53 UTC, cbush requested changes

2021-03-23 23:53 UTC, cbush commented on examples/ios/Examples/LandingPageCodeExamples.swift
> +        setUp()
Wait, this changed.

setUp() is automatically run before each test. So you shouldn't be calling it twice. Also, I think this might be stretching the Bluehawk replace functionality since this inserts a big chunk of code rather than renaming something.

2021-03-23 23:54 UTC, cbush commented on examples/ios/Examples/LandingPageCodeExamples.swift
> +    let realm = try! Realm()
I would just put this in every test case where you want to use it. It's ok to open it again and again in the examples. (It will automatically close when it goes out of scope, i.e. at the end of each test function.)

2021-03-25 14:37 UTC, dacharyc commented on examples/ios/Examples/LandingPageCodeExamples.swift
> +        setUp()
Alrighty, thanks! I've removed the manual call to setUp() and have removed the Bluehawk replace for that.

2021-03-25 14:38 UTC, dacharyc commented on examples/ios/Examples/LandingPageCodeExamples.swift
> +    let realm = try! Realm()
Got it, thanks! Added it where I'd like to illustrate that, and it didn't appear to cause any issues - tests are still passing - so I think these should be all set now.

2021-03-25 17:44 UTC, cbush approved these changes

2021-03-29 21:24 UTC, merged