(DOCSP-12904): Link to Supplementary Examples - iOS SDK
mongodb/docs-realm pull request #941
Opened 2021-03-29 15:25 UTC by mongomoe

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-12904

### Staged Changes (Requires MongoDB Corp SSO)

- [Additional Examples - iOS SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-12904-Link-to-supplementary-examples/sdk/ios/additional-examples/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-03-29 15:51 UTC, nathan-contino-mongo requested changes
Couple of nits, looking good though. I need to create one of these for Android!

2021-03-29 15:51 UTC, nathan-contino-mongo commented on source/sdk/ios/additional-examples.txt
> +There are many examples of applications that the {+realm+} community has
```suggestion
There are many examples of applications that the {+service-short+} community has
```
The "realm" substitution is just for the database/data structure, not the product or community.

2021-03-29 15:51 UTC, nathan-contino-mongo commented on source/sdk/ios/additional-examples.txt
> +of {+realm+} with UITableViewControllers, and more.
```suggestion
of {+realm+} with ``UITableViewController``, and more. 
```
Should this be monospaced?

2021-03-29 15:51 UTC, nathan-contino-mongo commented on source/sdk/ios/additional-examples.txt
> +There are many examples of applications that the {+realm+} community has
The introductory sentence reads a bit awkwardly to me. I wonder if we could rephrase it to something like "Every day, the MongoDB community creates additional applications that demonstrate {+service-short+}." Or maybe that is too marketing-y?

2021-03-30 19:58 UTC, nathan-contino-mongo requested changes
Some source constant and consistency issues still.

2021-03-30 19:58 UTC, nathan-contino-mongo commented on source/sdk/ios/additional-examples.txt
> +of {+realm+} with ``UITableViewController``, and more.
Since "use of realm with UITableViewController" isn't a "Realm feature" as you introduce this list, maybe you could rewrite this into two sentences? Also, be sure to use the {+service-short+} source constant for all mentions of Realm in paragraph text.

```
The :github:`realm-cocoa example applications
<realm/realm-cocoa/tree/master/examples>` provide examples for both iOS and macOS that
demonstrate how to use {+service-short+} features such as migrations, encryption,
and {+sync+}. The examples also demonstrate how to combine {+service-short+} with
common iOS concepts like ``UITableViewController``. 
```

2021-03-30 19:58 UTC, nathan-contino-mongo commented on source/sdk/ios/additional-examples.txt
> +The Realm community has created many applications that demonstrate the usage of the Realm iOS SDK. This page contains some of these applications, and the MongoDB documentation team will update this p
Always use the source constants for the product name.
```suggestion
The {+service-short+} community has created many applications that demonstrate the usage of the Realm iOS SDK. This page contains some of these applications, and the MongoDB documentation team will update this page with additional examples over time.
```

2021-03-30 19:58 UTC, nathan-contino-mongo commented on source/sdk/ios/additional-examples.txt
> +The Realm community has created many applications that demonstrate the usage of the Realm iOS SDK. This page contains some of these applications, and the MongoDB documentation team will update this p
In the note below, you mention the "MongoDB Documentation team", but in this sentence, you write it as "MongoDB documentation team" (no capital 'D' on "documentation"). We should keep this identifier consistent.

2021-03-30 19:58 UTC, nathan-contino-mongo commented on source/sdk/ios/additional-examples.txt
> +The Realm community has created many applications that demonstrate the usage of the Realm iOS SDK. This page contains some of these applications, and the MongoDB documentation team will update this p
Can we cut off this line at 80 characters? It's super long.

2021-04-01 17:37 UTC, mongomoe commented on source/sdk/ios/additional-examples.txt
> +The Realm community has created many applications that demonstrate the usage of the Realm iOS SDK. This page contains some of these applications, and the MongoDB documentation team will update this p
Fixed

2021-04-01 17:38 UTC, mongomoe commented on source/sdk/ios/additional-examples.txt
> +The Realm community has created many applications that demonstrate the usage of the Realm iOS SDK. This page contains some of these applications, and the MongoDB documentation team will update this p
fixed 👍

2021-04-01 17:42 UTC, mongomoe commented on source/sdk/ios/additional-examples.txt
> +of {+realm+} with ``UITableViewController``, and more.
Yup that sounds good, copied almost verbatim except I changed "... features such as migrations, encryption,
and {+sync+}" to remove Realm Sync, since the iOS examples in that project do not contain Realm Sync examples.

2021-04-01 18:12 UTC, nathan-contino-mongo approved these changes
LGTM with one nit

2021-04-01 18:12 UTC, nathan-contino-mongo commented on source/sdk/ios/additional-examples.txt
> +macOS that demonstrate how to use {+service-short+} features such as migrations,
unneeded comma
```suggestion
macOS that demonstrate how to use {+service-short+} features such as migrations
```

2021-04-01 20:09 UTC, merged