WIP - (DOCSP-11955): Add Sync Error Handling Docs
mongodb/docs-realm pull request #953
Opened 2021-03-31 04:09 UTC by mongomoe

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-11955

### Staged Changes (Requires MongoDB Corp SSO)

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-03-31 21:26 UTC, cbush reviewed
I see the new test files for Swift/Obj-C but I don't see the change to the pbxproj so they don't show up in the project when I check out this PR. Is there something missing from the PR?

2021-03-31 21:26 UTC, cbush commented on examples/ios/Examples/HandleErrorsObjc.m
> +    [app loginWithCredential:[RLMCredentials anonymousCredentials] completion:^(RLMUser *user, NSError *error) {
I don't think you really need to log in for this example. It would be nice if you could include the instantiation of the app in the code snippet so people know what `app` refers to.

2021-03-31 21:26 UTC, cbush commented on examples/ios/Examples/HandleErrors.swift
> +        let app = App(id: YOUR_REALM_APP_ID)
It would be nice to could include the instantiation of the app in the code snippet so people know what `app` refers to.

2021-03-31 21:26 UTC, cbush commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +      object representing the session the error occurred on.
This and the corresponding Obj-C version could be tidied up a bit. Rather than:

>with an object representing the error and a SyncSession object representing the session the error occurred on. 

Maybe:

>with the error object and the SyncSession that the error occurred on.

2021-03-31 21:27 UTC, nathan-contino-mongo requested changes
Looking solid so far despite what appears to be an accidental codeblock reference change and some minor flaws in the codeblocks.

2021-03-31 21:27 UTC, nathan-contino-mongo commented on source/sdk/android/examples/sync-changes-between-devices.txt
> +         To register a default global error handler that will apply to all :java-sdk:`SyncConfigurations <io/realm/mongodb/sync/SyncConfiguration.html>`, call :java-sdk:`SyncManager.setDefaultSession
The second link here doesn't work for me. Also, please try to keep lines within the 80 characters that the rest of the docs (aside from links where unavoidable) generally adhere to.

2021-03-31 21:27 UTC, nathan-contino-mongo commented on source/sdk/android/examples/sync-changes-between-devices.txt
> +         To register a default global error handler that will apply to all :java-sdk:`SyncConfigurations <io/realm/mongodb/sync/SyncConfiguration.html>`, call :java-sdk:`SyncManager.setDefaultSession
Same as above.

2021-03-31 21:27 UTC, nathan-contino-mongo commented on source/sdk/android/examples/sync-changes-between-devices.txt
> +       .. literalinclude:: /examples/generated/android/sync/ErrorHandlerTest.codeblock.error-handler.kt
Why did we change this? Client resets are entirely separate from error handling in a general sense, and the client reset example here contains a lot of information for folks who need to handle them in a custom way.

2021-03-31 21:27 UTC, nathan-contino-mongo commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/ErrorHandlerTest.java
> +            String partition = getRandomPartition();
No need for this partition variable.

2021-03-31 21:27 UTC, nathan-contino-mongo commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/ErrorHandlerTest.kt
> +                    )
Please fix the awkward newlines here and use kotlin string interpolation instead of appending to the string. For instance, I would probably write this as:
```
Log.e( "EXAMPLE", "Failed login: ${it.error.errorMessage}")
```

2021-03-31 21:27 UTC, nathan-contino-mongo commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/ErrorHandlerTest.kt
> +            val partition = getRandomPartition()
No need for this partition variable.

2021-03-31 21:30 UTC, nathan-contino-mongo commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/ErrorHandlerTest.java
> +import com.mongodb.realm.examples.RealmTest;
Your tests are failing because you don't import the Expectation class.
```suggestion
import com.mongodb.realm.examples.RealmTest;
import com.mongodb.realm.examples.Expectation
```

2021-03-31 21:30 UTC, nathan-contino-mongo commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/ErrorHandlerTest.kt
> +import com.mongodb.realm.examples.RealmTest
Your tests are failing because you never import the expectation class.
```suggestion
import com.mongodb.realm.examples.RealmTest
import com.mongodb.realm.examples.Expectation
```

2021-03-31 22:54 UTC, nlarew commented on source/sync/errors.txt
> +------------
Let's delete the colons from this and other headings

2021-04-01 17:52 UTC, mongomoe commented on examples/dotnet/Examples/ErrorHandler.cs
> +using System;
@MongoCaleb

2021-04-01 17:58 UTC, MongoCaleb approved these changes
One typo, one suggestion.

2021-04-01 17:58 UTC, MongoCaleb commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +{+sync+} represents errors via :dotnet-sdk:`SessionExceptions <api/reference/Realms.Sync.Exceptions.SessionException.html>` . In
Extra space after the SessionExceptions link.

2021-04-01 17:58 UTC, MongoCaleb commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +Set :dotnet-sdk:`LogLevel <reference/Realms.Sync.LogLevel.html>` to specify which messages will be logged by the sync client logger.
I think it's useful to say where this is set (even though the code snippet makes it obvious). Like, maybe:

> To control which messages are logged by the sync client logger, set the LogLevel property of the SyncConfiguration object:

2021-04-01 18:17 UTC, nlarew reviewed
A few comments and suggestions

2021-04-01 18:17 UTC, nlarew commented on source/sdk/android/examples/sync-changes-between-devices.txt
> +While developing an application that uses {+sync+}, you should set an error
nit: Only while developing? Should I remove my error handler in production?

maybe we could be more direct, e.g.

- You can configure an error handler to detect and respond to any errors that occur in the Realm sync process.
- You define the error handler callback function in the `error` field of Realm.Configuration.

2021-04-01 18:17 UTC, nlarew commented on source/sync/errors.txt
> +section details some common errors.
nit: Only while developing? I think we could frame this a bit more in the context of the sync protocol (and even link to that page).

- The sync protocol may raise an error if either the client or server do not conform to the protocol while using it.
- This page describes the errors you may encounter and includes advice on how to troubleshoot error (future ticket?)

2021-04-01 18:18 UTC, nlarew commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +Set :dotnet-sdk:`LogLevel <reference/Realms.Sync.LogLevel.html>` to specify which messages will be logged by the sync client logger.
+1 - this is in line with a couple of my comments:

- On the client side: https://github.com/mongodb/docs-realm/pull/953#discussion_r605852816
- On the server side: https://github.com/mongodb/docs-realm/pull/953#discussion_r605272509

2021-04-01 18:25 UTC, nlarew commented on source/sync/errors.txt
> +:github:`error code list on the Realm Core github repository. <realm/realm-core/blob/master/doc/protocol/protocol_1.md#error-codes>`.
This would also be a good spot to include the "advice on how to troubleshoot errors" I mention in another comment. e.g.

| Error | Description / Troubleshooting |
| ----- | ------------------------------ |
| `208 Bad client file identifier (IDENT)` | The server configuration doesn't match the client realm file. To troubleshoot, turn sync off and then back on again |

2021-04-01 18:44 UTC, nlarew commented on source/sync/errors.txt
> +``trace`` to diagnose errors while developing your application. When running in a
Also should we add a link to the [Sync logs](https://docs.mongodb.com/realm/logs/sync/) page for server-side logs

2021-04-02 20:04 UTC, mongomoe commented on examples/ios/Examples/HandleErrors.swift
> +        let app = App(id: YOUR_REALM_APP_ID)
Good idea, fixed

2021-04-02 20:07 UTC, mongomoe commented on examples/ios/Examples/HandleErrorsObjc.m
> +    [app loginWithCredential:[RLMCredentials anonymousCredentials] completion:^(RLMUser *user, NSError *error) {
Good ideas, fixed now

2021-04-02 20:29 UTC, mongomoe commented on source/sdk/ios/examples/sync-changes-between-devices.txt
> +      object representing the session the error occurred on.
Thanks for the suggestion, updated the text to your suggestion for both swift and objc now 👍

2021-04-02 20:36 UTC, cbush approved these changes
Green stamp for iOS.

2021-04-02 20:52 UTC, mongomoe commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/ErrorHandlerTest.java
> +import com.mongodb.realm.examples.RealmTest;
Fixed + for kotlin

2021-04-02 21:01 UTC, mongomoe commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/ErrorHandlerTest.kt
> +import com.mongodb.realm.examples.RealmTest
Fixed

2021-04-02 21:03 UTC, mongomoe commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/ErrorHandlerTest.kt
> +            val partition = getRandomPartition()
I think it is needed. That partition variable is used in line 30 of the same file `SyncConfiguration.Builder(user, partition)` . I took this idea from SyncDataTest.kt

2021-04-02 21:04 UTC, mongomoe commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/ErrorHandlerTest.kt
> +                    )
Fixed

2021-04-02 21:05 UTC, nathan-contino-mongo commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/ErrorHandlerTest.kt
> +            val partition = getRandomPartition()
Gotcha, I missed that before since we don't actually use the realm at all. Keep it then.

2021-04-02 21:05 UTC, nathan-contino-mongo commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/ErrorHandlerTest.java
> +            String partition = getRandomPartition();
Never mind this as we discussed below

2021-04-02 21:06 UTC, mongomoe commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/java/ErrorHandlerTest.java
> +            String partition = getRandomPartition();
I think it is required (same reason as the kotlin comment I made below - https://github.com/mongodb/docs-realm/pull/953/files#r606419114). That partition variable is used in line 32 of the same file new SyncConfiguration.Builder(user, partition). I took this idea from SyncDataTest.java

2021-04-02 21:15 UTC, mongomoe commented on source/sdk/android/examples/sync-changes-between-devices.txt
> +         To register a default global error handler that will apply to all :java-sdk:`SyncConfigurations <io/realm/mongodb/sync/SyncConfiguration.html>`, call :java-sdk:`SyncManager.setDefaultSession
Removed this whole note, looks like this method is not a thing version 10 of the SDK

2021-04-02 21:15 UTC, mongomoe commented on source/sdk/android/examples/sync-changes-between-devices.txt
> +         To register a default global error handler that will apply to all :java-sdk:`SyncConfigurations <io/realm/mongodb/sync/SyncConfiguration.html>`, call :java-sdk:`SyncManager.setDefaultSession
Removed this whole note, looks like this method is not a thing version 10 of the SDK

2021-04-02 21:18 UTC, mongomoe commented on source/sdk/android/examples/sync-changes-between-devices.txt
> +       .. literalinclude:: /examples/generated/android/sync/ErrorHandlerTest.codeblock.error-handler.kt
Sorry about that! Not sure why that link was changed, wasn't a purposeful choice - probably was a copy and paste issue. Fixed it back to the original client reset example now

2021-04-02 21:21 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +{+sync+} represents errors via :dotnet-sdk:`SessionExceptions <api/reference/Realms.Sync.Exceptions.SessionException.html>` . In
```suggestion
{+sync+} represents errors via :dotnet-sdk:`SessionExceptions <api/reference/Realms.Sync.Exceptions.SessionException.html>`. In
```

2021-04-02 21:26 UTC, nathan-contino-mongo requested changes
Looking good with a wording change + a couple of links to the relevant Java SDK methods.

2021-04-02 21:26 UTC, nathan-contino-mongo commented on source/sdk/android/examples/sync-changes-between-devices.txt
> +While developing an application that uses {+sync+}, you should set an error
Agreed with nick's comment above. I'd probably word it like this:
```
You can configure an error handler to detect and respond to any errors that
occur in the {+sync+} process. To define an error handler, pass an
:java-sdk:`ErrorHandler <io/realm/mongodb/sync/SyncSession.ErrorHandler.html>`
to the :java-sdk:`SyncConfiguration.Builder.errorHandler()
<io/realm/mongodb/sync/SyncConfiguration.Builder.html#errorHandler-io.realm.mongodb.sync.SyncSession.ErrorHandler->`
builder method.
```

2021-04-02 21:48 UTC, nathan-contino-mongo approved these changes
LGTM for Android now. Rubber green stamped.

2021-04-05 14:31 UTC, nathan-contino-mongo approved these changes
LGTM with one nit

2021-04-05 14:31 UTC, nathan-contino-mongo commented on source/sdk/android/examples/sync-changes-between-devices.txt
> +builder method.
```suggestion
builder method:
```

Colon makes sense for consistency with the other examples on this page and because it's introducing the snippet. Sorry that I forgot to suggest this earlier!

2021-04-05 15:38 UTC, mongomoe commented on examples/android/sync/app/src/androidTest/java/com/mongodb/realm/examples/kotlin/ErrorHandlerTest.kt
> +            val partition = getRandomPartition()
👍

2021-04-05 15:58 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +Set :dotnet-sdk:`LogLevel <reference/Realms.Sync.LogLevel.html>` to specify which messages will be logged by the sync client logger.
Altered to be "To control which messages are logged by the sync client logger, set the LogLevel property of the SyncConfiguration object:" (LogLevel is set on AppConfiguration rather than SyncConfiguration for the v10 sdk, see: https://mongodb.slack.com/archives/C017MBM0A30/p1617399475011000)

2021-04-05 22:50 UTC, nirinchev commented on source/examples/generated/dotnet/ErrorHandler.codeblock.set-log-level.cs
> +    LogLevel = LogLevel.Debug,
Would be nice to also mention that users can configure a custom log function in case they want to write log messages to a file or send them somewhere: https://docs.mongodb.com/realm-sdks/dotnet/10.0.0-beta.1/reference/Realms.Sync.AppConfiguration.html#Realms_Sync_AppConfiguration_CustomLogger.

2021-04-06 03:41 UTC, mongomoe commented on source/sync/errors.txt
> +------------
👍

2021-04-06 12:45 UTC, mongomoe commented on source/sync/errors.txt
> +performance.
Hey Nick, that's a good idea - I've captured that idea in a follow-up ticket (https://jira.mongodb.org/browse/DOCSP-15481) and will work on that in the future, going to merge this as is now, in order to get this to our users (since it has no blocking comments and has been sitting in review for a bit). Hoping to update these pages when I work on DOCSP-15481.

2021-04-06 12:45 UTC, mongomoe commented on source/sync/errors.txt
> +``trace`` to diagnose errors while developing your application. When running in a
Hey Nick, those are both good ideas - I've captured them in a follow-up ticket (https://jira.mongodb.org/browse/DOCSP-15481) and will work on that in the future, going to merge this as is now, in order to get this to our users (since it has no blocking comments and has been sitting in review for a bit). Hoping to update these pages when I work on DOCSP-15481.

2021-04-06 12:48 UTC, mongomoe commented on source/sync/errors.txt
> +:github:`error code list on the Realm Core github repository. <realm/realm-core/blob/master/doc/protocol/protocol_1.md#error-codes>`.
Unfortunately, those error codes are somewhat out of date (some of them are still very relevant, but at least half are legacy), so I hesitate to mirror them as is right now. Meeting with Drew at some point soon to go through the error codes that are still up to date, and will update this page with them then (likely in the table style you suggested above).

In the meantime, I've captured this idea in a follow-up ticket (https://jira.mongodb.org/browse/DOCSP-15481)

2021-04-06 12:48 UTC, mongomoe commented on source/sync/errors.txt
> +section details some common errors.
That's a good idea - I've captured that idea in a follow-up ticket (https://jira.mongodb.org/browse/DOCSP-15481) and will work on that in the future, going to merge this as is now, in order to get this to our users (since it has no blocking comments and has been sitting in review for a bit). Hoping to update these pages when I work on DOCSP-15481.

2021-04-06 12:50 UTC, mongomoe commented on source/examples/generated/dotnet/ErrorHandler.codeblock.set-log-level.cs
> +    LogLevel = LogLevel.Debug,
Hey @nirinchev, thanks for the suggestion, I'm merging this PR as is right now in order to get this content out to users. But I've added your suggestion to a follow-up ticket https://jira.mongodb.org/browse/DOCSP-15481 (along with some suggestions from other team members).

2021-04-06 18:29 UTC, merged