(DOCSP-14643): Port Swift FAQ info from Realm.io
mongodb/docs-realm pull request #978
Opened 2021-04-06 22:36 UTC by dacharyc

## Pull Request Info

From the legacy doc [Swift: FAQ](https://docs.mongodb.com/realm-legacy/docs/swift/latest/index.html#faq)

I did not port content for:
- Is Realm open source?
- I see a network call to Mixpanel when I run my app

The first question seemed more like a top-level Realm docs question than a Realm Swift question, and I'm not sure it warrants a FAQ. 

The second bullet also seems to apply to more than just the Swift SDK, and I was uncertain how/where we'd want to comment on this, if at all. The example linked to in the ["source code" link](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMAnalytics.mm) is the Realm Cocoa implementation of analytics, but I found stuff in several of the SDK repos related to this, so I think it applies more broadly.

And finally, I added info on finding the Realm file path to the Realm Studio page for Swift and Objective-C, but if we want to keep this there, we should probably make a ticket to add corresponding info for the other SDKs/frameworks.

### Jira

- https://jira.mongodb.org/browse/DOCSP-14643

### Staged Changes (Requires MongoDB Corp SSO)

- [Fundamentals -> Object Models & Schemas -> Realm Does Not Support Swift Structs](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14643/sdk/ios/fundamentals/object-models-and-schemas/#realm-does-not-support-swift-structs)
- [Fundamentals -> Realms -> App Download File Size](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14643/sdk/ios/fundamentals/realms/#app-download-file-size)
- [Realm Studio -> Find the Realm File(s)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14643/sdk/ios/fundamentals/realms/#app-download-file-size)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-04-07 13:20 UTC, cbush requested changes
I like the general direction but I think the first section needs work.

2021-04-07 13:20 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +variety of reasons. Foremost, {+service-short+}'s design focuses on
Word choice:
```suggestion
variety of reasons. {+service-short+}'s design focuses on 
```

2021-04-07 13:20 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +By design, {+service-short+} provides features which are incompatible with
```suggestion
By design, {+service-short+} provides features that are incompatible with 
```

2021-04-07 13:20 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +- Live data
Link to live objects page?

2021-04-07 13:20 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +- Reactive APIs
Link to react to changes page?

2021-04-07 13:20 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +- Lazy and cheap access to partial data
Live queries link?

2021-04-07 13:20 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +- Keeping potentially complex object graphs synchronized
Link to Sync?

2021-04-07 13:20 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +- Lack of data serialization/deserialization
Link to Object Models & Schemas?

2021-04-07 13:20 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +objects to behave like :apple:`Apple's NSObject <documentation/objectivec/nsobject>`.
"Implemented standalone/detached ... to behave" reads a bit weird. How about:

>We've made unmanaged objects behave like ..."

2021-04-07 13:20 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +We support making “in-memory copies” of {+service-short+} objects. Use an initializer
Watch out for smart quotes:
```suggestion
We support making "in-memory copies" of {+service-short+} objects. Use an initializer 
```

2021-04-07 13:20 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +To make this easier, we’ve implemented standalone/detached {+service-short+}
```suggestion
To make this easier, we've implemented standalone/detached {+service-short+} 
```

2021-04-07 13:20 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +  create "in-memory copies" of {+service-short+} objects.
Does this make it sound more complicated than it is? I feel like the point here is that you can use "unmanaged" objects like normal objects. (Standalone, in-memory, detached are all new words for "unmanaged")

2021-04-07 13:20 UTC, cbush commented on source/sdk/ios/fundamentals/realms.txt
> +App Download File Size
This section is labeled `ios-default-realm` above. Must move above the label.

2021-04-07 13:53 UTC, dacharyc commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +- Lack of data serialization/deserialization
This content is on the Object Models & Schemas page. Is there another part of the page where you think this should link, @cbush ?

2021-04-07 13:58 UTC, dacharyc commented on source/sdk/ios/fundamentals/realms.txt
> +App Download File Size
Thank you for spotting that! I moved this on the page a couple of times and eventually just missed it when this became the final resting place for that content.

2021-04-07 14:15 UTC, cbush approved these changes
Much improved!

2021-04-07 14:15 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +initializer to create an unmanaged object by key-value coding copying a
Can we simplify this?

>Create an unmanaged copy by passing the managed instance to the object's initializer.

2021-04-07 14:15 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +- Lack of data serialization/deserialization
Oh right. I was thinking about the intro paragraph. But there's not a specific place where we talk about the fact that you don't need an ORM, etc. for Realm. Oh well.

2021-04-07 14:15 UTC, cbush commented on source/sdk/ios/fundamentals/realms.txt
>  App Download File Size
Should we add a section label?

.. _ios-app-download-file-size:

2021-04-07 15:32 UTC, dacharyc commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +Realm Does Not Support Swift Structs
It does. And I don't like a negative header in general. I've shortened it to just "Structs." What do you think?

2021-04-07 15:34 UTC, dacharyc commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +initializer to create an unmanaged object by key-value coding copying a
I've [rewritten this paragraph](https://github.com/mongodb/docs-realm/pull/978/commits/e5008ff2a529e0be704fc0c1ed6a9b5d8d60dd33#diff-ea0e01aa4cd7351e0e98d04b778142d1e208bf07da90437e9cd585ce922afed7R136) a bit. What do you think, @cbush ?

2021-04-07 18:10 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +initializer to create an unmanaged object by key-value coding copying a
Perfect.

2021-04-07 18:39 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +Realm Does Not Support Swift Structs
I can't currently check the staged build due to https://jira.mongodb.org/browse/MARKETING-21151, but I think the name is fine.

2021-04-07 18:42 UTC, cbush commented on source/sdk/ios/fundamentals/object-models-and-schemas.txt
> +Realm Does Not Support Swift Structs
You might want to specify "Swift Structs". Obj-C objects can't go in (plain C) structs in Obj-C, so it's kind of implied.

2021-04-09 14:13 UTC, ericjordanmossman approved these changes
> The example linked to in the "source code" link is the Realm Cocoa implementation of analytics, but I found stuff in several of the SDK repos related to this, so I think it applies more broadly.

Just a note:
While it's true other sdks are also collecting similar build analytics, the way the analytics is disabled might be different (and have different comments, methods for gathering, etc.). So the broader section on analytics may still benefit from linking to each SDKs analytics source file.

2021-04-09 14:14 UTC, ericjordanmossman commented
Hmm.. just looked at some other sdks, they also just check for an env "REALM_DISABLE_ANALYTICS". Just FYI.

2021-04-19 15:48 UTC, merged