(DOCSP-14572): [iOS] Add MutableSet to Collections
mongodb/docs-realm pull request #982
Opened 2021-04-07 22:50 UTC by dacharyc

## Pull Request Info

Everywhere that I linked to the Jazzy docs with `:swift-sdk: MutableSet <Classes/MutableSet.html>` is currently a broken link, but I believe that link should be correct once the updated docs are auto-generated.

### Jira

- https://jira.mongodb.org/browse/DOCSP-14572

### Staged Changes (Requires MongoDB Corp SSO)

- [Collections -> Mutable Set](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14572/sdk/ios/data-types/collections/#mutableset)
- [Supported Property Types (add MutableSet)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-14572/sdk/ios/data-types/supported-property-types/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-04-08 00:25 UTC, cbush requested changes
I think this is the correct amount of information, but the example could be refined.

Also, please retarget the PR to the upstream `new-data-types` branch I created.

2021-04-08 00:25 UTC, cbush commented on examples/ios/Examples/MutableSetExample.swift
> +class MutableSetExamples_Person: Object {
We're making new models but they aren't shown to the user in the docs. They also don't really use the set. Maybe we should make a new example model just for the set usage and show it in the docs.

2021-04-08 00:25 UTC, cbush commented on examples/ios/Examples/MutableSetExample.swift
> +        let specificPersonsDogBreeds = MutableSet<String>()
The above is a lot before we finally get to the meat of the example. Do we need the setup in the snippet?

Also, we're using the set, but this example isn't really showing me why I would use the Realm set over the standard library set. It might be worth making this an example with a whole new class that has a set as a property.

2021-04-08 00:25 UTC, cbush commented on source/sdk/ios/data-types/collections.txt
> +{+service-short+} mutable sets are reference types. They are only immutable
This last sentence feels like a non sequitur. It might answer the question "can a _Mutable_ Set be immutable?"

2021-04-08 00:25 UTC, cbush commented on source/sdk/ios/data-types/collections.txt
> +You can filter and sort a ``MutableSet`` with the same predicates as
```suggestion
You can filter and sort a ``MutableSet`` with the :ref:`same predicates <ios-filter-data>` as 
```

2021-04-08 00:26 UTC, cbush commented on examples/ios/Examples/MutableSetExample.swift
> +        }
Missing `:code-block-end:`?

2021-04-08 00:28 UTC, cbush commented
Do they support notification listeners?

2021-04-08 14:28 UTC, cbush reviewed
Shaping up! Few more comments.

2021-04-08 14:28 UTC, cbush commented on examples/ios/Examples/MutableSetExample.swift
> +        // Later, retreive the dog
```suggestion
        // Later, retrieve the dog
```

2021-04-08 14:28 UTC, cbush commented on examples/ios/Examples/MutableSetExample.swift
> +// :hide-end:
This will not deindent properly. The best option is to make two snippets, one for the model and one for the usage example.

2021-04-08 14:28 UTC, cbush commented on examples/ios/Examples/MutableSetExample.swift
> +// }
Are these still needed?

2021-04-08 14:28 UTC, cbush commented on examples/ios/Examples/MutableSetExample.swift
> +    let citiesVisited = MutableSet<String>()
I like it!

2021-04-08 14:28 UTC, cbush commented on examples/ios/Examples/MutableSetExample.swift
> +        let specificDog = dogs.filter("name == 'Maui'").first!
I still feel this example is kind of long. Do we need to refetch the dog? What if we just said `// Later...` and show the Set update?

2021-04-08 14:28 UTC, cbush commented on examples/ios/Examples/MutableSetExample.swift
> +//        }
Is this still needed?

2021-04-08 14:28 UTC, cbush commented on source/sdk/ios/data-types/collections.txt
> +{+service-short+} mutable sets are reference types.
Maybe?
```suggestion
{+service-short+} mutable sets are reference types as opposed to value types (structs). 
```

2021-04-08 16:31 UTC, cbush approved these changes
Looks good! One last question: is it possible to observe the Set for changes?

2021-04-08 16:48 UTC, cbush approved these changes

2021-04-08 16:49 UTC, dacharyc commented
> One last question: is it possible to observe the Set for changes?

Sorry, @cbush , I saw you ask that before but then lost it when I was doing updates. Yes, it looks like `MutableSet` can be observed in the the same way as other Realm collections, so I just added a link to the section of the docs where we cover that.

2021-04-09 15:54 UTC, cbush approved these changes
New content looks great.

2021-04-09 15:54 UTC, cbush commented on examples/ios/Examples/MutableSetExample.swift
> +        // :code-block-start: set-methods-example
Nitpick: `example` is implied by being a snippet. IDs have conventionally been without "-example" (so far...)

2021-04-09 15:54 UTC, cbush commented on examples/ios/Examples/MutableSetExample.swift
> +        let dog2Cities: [String] = ["Boston", "New York", "Toronto", "Montreal", "Boston"]
Not sure that explicit type (`: [ String ]`) is required. Usually best to prefer type inference.

2021-04-09 15:54 UTC, cbush commented on examples/ios/Examples/MutableSetExample.swift
> +        let isInBothCitiesVisited: Bool = (dog.citiesVisited.intersects(dog2.citiesVisited))
Remove `: Bool`

2021-04-09 15:54 UTC, cbush commented on source/sdk/ios/data-types/collections.txt
> +MutableSet Methods
Perhaps a more specific title like "Set Intersection Methods" etc.?

2021-04-09 17:05 UTC, merged

2021-04-09 18:05 UTC, cbush commented
Note that autobuilder failure is not related to this PR and fixed in https://github.com/mongodb/docs-realm/pull/984