DOCSP-12545 Add Realm progress notification documentation to .NET docs
mongodb/docs-realm pull request #989
Opened 2021-04-09 20:06 UTC by jenniferpeshansky

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-12545

### Staged Changes (Requires MongoDB Corp SSO)

- [Sync Changes Between Devices - .NET SDK](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCS-12545-carb/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-04-09 21:01 UTC, mongomoe commented on examples/dotnet/Examples/ProgressNotifications.cs
> +            ulong progressPercentage = Convert.ToUInt32(-1);
Why set this initially to `Convert.ToUInt32(-1);` if it just needs to be set to another value later? Alternatively, could you just do:
`ulong progressPercentage;` 

Maybe even declare it as a class member after line 13?

2021-04-09 21:04 UTC, mongomoe commented on examples/dotnet/Examples/ProgressNotifications.cs
> +            ulong progressPercentage = Convert.ToUInt32(-1);
I think this is also causing the test to fail, here is the message from the CI:
```
  Failed TestUploadDownloadProgressNotification [2 s]
  Error Message:
   System.OverflowException : Value was either too large or too small for a UInt32.
  ```

2021-04-09 21:08 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +Check Upload & Download Progress for a Sync Session
Should we mention the System.Reactive requirement in the docs itself so that users don't get an error when trying to create that anonymous function like we did?

2021-04-09 21:11 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
>  .. _dotnet-check-sync-progress:
The snooty autobuilder should have given you a link for the job. Something like:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=<job_id> 

Can you do a command+find in that link to search for the key word error (and then later warning). There may be some indent warnings on files you touched - such as the sync changes file

2021-04-09 21:14 UTC, mongomoe commented
404 on staging

2021-04-09 21:15 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +   them to calculate the progress percentage of the upload.
Something going on with the indentation or spacing here, I think you possibly need a new line in between the last line of the `..example::` and the literal include

2021-04-09 21:15 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +   .. literalinclude:: /examples/generated/dotnet/ProgressNotifications.codeblock.upload-download-progress-notification.cs
```suggestion

   .. literalinclude:: /examples/generated/dotnet/ProgressNotifications.codeblock.upload-download-progress-notification.cs
```

2021-04-09 21:17 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +      :language: dotnet
```suggestion
      :language: csharp
```

C# is the language, .NET is the framework + runtime

2021-04-09 21:17 UTC, mongomoe commented
Nice job on this @jenniferpeshansky !

2021-04-09 21:19 UTC, mongomoe requested changes
Nice job on this @jenniferpeshansky!!

Just a few comments on my end. The major required thing is the unit test needs to pass, I believe the "ulong progressPercentage = Convert.ToUInt32(-1);" line is breaking it right now.

Also, make sure to merge this https://github.com/jenniferpeshansky/docs-realm/pull/2 to your fork:branch, pull changes locally, and push to get the changes visible here.

2021-04-09 23:38 UTC, nirinchev requested changes
Looks good, barring some clarifications. Also, might be a good idea - either as part of this PR or a follow-up - to explain that this approach is what a user would need after they've opened the Realm database. If they want to use `GetInstanceAsync` and be notified of the progress during the initial download of the Realm file, they can use [`config.OnProgress`](https://docs.mongodb.com/realm-sdks/dotnet/10.0.0/reference/Realms.Sync.SyncConfiguration.html#Realms_Sync_SyncConfiguration_OnProgress).

2021-04-09 23:38 UTC, nirinchev commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +- A ``ProgressMode`` parameter that can be set to ``ProgressMode.ReportIndefinitely`` for the notifications to continue until the callback is unregistered using the :js-sdk:`syncSession.removeProgres
Seems like there are some leftovers from the JS docs. To unregister an observer in the .NET SDK, the user needs to dispose the token they receive when they call `.Subscribe(..)`

2021-04-09 23:38 UTC, nirinchev commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +- A ``ProgressMode`` parameter that can be set to ``ProgressMode.ReportIndefinitely`` for the notifications to continue until the callback is unregistered using the :js-sdk:`syncSession.removeProgres
Also, why is `for the notifications to continue ...` in parentheses?

2021-04-09 23:38 UTC, nirinchev commented on examples/dotnet/Examples/ProgressNotifications.cs
> +                       progressPercentage = progress.TransferredBytes / progress.TransferableBytes;
This is dividing integers, so will probably not result in a meaningful value.

2021-04-21 15:46 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +- A ``ProgressMode`` parameter that can be set to ``ProgressMode.ReportIndefinitely`` for the notifications to continue until the callback is unregistered using the :js-sdk:`syncSession.removeProgres
Thanks, I've removed the leftover JS doc stuff now and taken the 'for the notifications to continue' out of parenthesis.

I'm closing this PR since it's on Jenny's branch but you can see the changes here: https://github.com/mongodb/docs-realm/pull/998

2021-04-21 15:47 UTC, mongomoe commented on examples/dotnet/Examples/ProgressNotifications.cs
> +                       progressPercentage = progress.TransferredBytes / progress.TransferableBytes;
Removed that line. You can see the changes here: https://github.com/mongodb/docs-realm/pull/998

2021-04-22 14:19 UTC, mongomoe commented
Closing this PR, please refer to https://github.com/mongodb/docs-realm/pull/998

2021-04-22 14:19 UTC, closed without merging