(DOCSP-15010): Reacting to Changes from React Native Components
mongodb/docs-realm pull request #996
Opened 2021-04-20 17:15 UTC by mongomoe

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-NNNNN

### Staged Changes (Requires MongoDB Corp SSO)

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-04-22 17:44 UTC, nathan-contino-mongo requested changes
Looking good, lots of minor nitpicks and questions since I'm not super familiar with React.

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +You can copy our {+realm+} objects to our component's :reactjs:`state
our -> your?

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +<docs/state-and-lifecycle.html>`.  However, since {+realm+} objects are live and
Typically we use "{+service-short+} objects".

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +{+realm+} objects in state. You can do this by registering a change listener in
Same as above

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +{+realm+} objects in state. You can do this by registering a change listener in
"in state" sounds confusing to me as a non-React developer -- I feel like we should use an article, or "your", something like that to introduce state. Or maybe "state variable" like you've used below? Unless "state" is a well-known object/container in React, which it might be.

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +your component and updating the state variable when that listener fires.
I do like the way that this introduction jumps right into the meat and potatoes of the page, but I wonder if we can draw on some of the language in the JIRA ticket description to make it seem *slightly* less abrupt. Specifically I think the concept of "live object deletions cause issues" is an important one to bring up since it's relatively easy for a developer to understand how an invalid object reference tied to a widget could cause null pointers or invalid access issues.

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +   Failing to update copies of {+realm+} objects leads to your UI being out of date.
If you copy information out of live objects into plain old objects, it seems obvious enough that you'll have to manually update those plain old objects that I'm not sure we need a warning here to point that out. Perhaps this is a better place to point out that live objects in state can lead to invalid accesses as collections change and objects are deleted?

Also, {+realm+} should be {+service-short+} here according to our conventions elsewhere in the docs.

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +value of your objects and then declare a change listener on the {+realm+} objects.
{+realm+} should be {+service-short+} here according to our conventions elsewhere in the docs.

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +:reactjs:`useEffect() <docs/hooks-effect.html>` hook, set state to the initial
"state" -> "the state variable"?

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +Declare a state variable for your {+realm+} objects using the
Starting this sentence with "declare" seems a little too strong a command for my liking in the docs. I think I'd prefer an introduction before we get to the prescribed solution, something like "To always keep your UI up-to-date with changes to underlying {+service-short+} objects, ..."?

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +the component unmounts.
Similarly to above, I think we're missing the *why* of this paragraph. I understand that we need to clean up the listener when we're done displaying the object on the UI and no longer need the listener... but that might not be obvious to a reader who's just learning about realm. Also, should "Reactjs" be "ReactJS" or "React.js" or even just "React"?

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +Adding Change Listeners to Functional Components
As someone who doesn't know the difference between "functional components" and "class components" (or non-functional components? Are those the same thing?) it might be useful to explain what a functional or class component is in an introductory sentence. Unless we're assuming that all readers already know those definitions -- but even then, it could be useful to at least link to some external reading?

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +In your component's constructor, create a :reactjs:`ref
Similar thoughts as above -- I think we should introduce the concept of class components and what we're trying to accomplish before we dive straight into a prescribed solution to a problem.

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +of your objects and then declare a change listener on the {+realm+} objects.
{+realm+} -> {+service-short+}

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +of your objects and then declare a change listener on the {+realm+} objects.
Should we explain what to do in the change listener?

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +the value of the {+realm+} changes, the component will not re-render, as it would
Maybe we should change "realm" to "underlying data" here, since we're probably not subscribing to changes to all data in the realm but just a subset?

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +with a state variable. Declare a state variable to store your {+realm+} objects.
I found this sentence confusing. The previous sentence talks about how we should use a ref instead of a state variable, and how that means our component won't re-render on data changes.  But then this sentence instructs us to declare a state variable for the objects?

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/react-to-changes.txt
> +the :ref:`using change listeners in react components <react-native-use-listeners-in-components>` documentation.
This link still uses the old page title.
```suggestion
the documentation on how to
:ref:`use change listeners in React components <react-native-use-listeners-in-components>`.
```

2021-04-22 17:44 UTC, nathan-contino-mongo commented on source/examples/generated/rn/using-change-listeners-class-component.codeblock.using-change-listeners-class-component.js
> +    }
Should we handle the case where the realm is invalid somehow during `componentWillUnmount()`? Maybe an error log?

2021-04-27 15:23 UTC, mongomoe commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +You can copy our {+realm+} objects to our component's :reactjs:`state
👍

2021-04-27 15:25 UTC, mongomoe commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +<docs/state-and-lifecycle.html>`.  However, since {+realm+} objects are live and
👍

2021-04-27 15:25 UTC, mongomoe commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +{+realm+} objects in state. You can do this by registering a change listener in
👍

2021-04-27 15:32 UTC, mongomoe commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +{+realm+} objects in state. You can do this by registering a change listener in
State is a fundamental term in react, but I did change the phrasing to be more understandable:

"... since realm objects are live and automatically update in response to changes, **you must update the copies
of them** to prevent your UI from being out of date. You can do this by registering a change listener in your component and updating the state variable when that listener fires. "

2021-04-27 15:41 UTC, mongomoe commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +your component and updating the state variable when that listener fires.
Added a sentence in the intro that I think captures this:

"However, since Realm objects are live and automatically update in response to changes, you must update the copies of them to prevent your UI from being out of date."

2021-04-27 16:29 UTC, mongomoe commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +value of your objects and then declare a change listener on the {+realm+} objects.
👍

2021-04-27 16:34 UTC, mongomoe commented on source/examples/generated/rn/using-change-listeners-class-component.codeblock.using-change-listeners-class-component.js
> +    }
Deleted this file for the following reasons:
* The class example was a bit redundant since we already have a functional component example and we're documenting using React with Realm not React itself. 
* A React developer looking to use Realm will know how to take the info presented for the functional component and convert it to a class component if they need. 
* Functional components are shorter and easier to understand and becoming increasingly popular, making them suitable for our docs.

2021-04-27 17:10 UTC, mongomoe commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +with a state variable. Declare a state variable to store your {+realm+} objects.
Removed this bit on class components (see reasoning in [this comment](https://github.com/mongodb/docs-realm/pull/996#discussion_r621395094)). 

But just FYI, what I meant here was that the Realm Instance itself does not need to trigger a UI refresh/rerender. However, changes to the Realm Objects do need to trigger a UI refresh/rerender and thus are stored in state.

2021-04-27 17:10 UTC, mongomoe commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +the value of the {+realm+} changes, the component will not re-render, as it would
Removed this bit on class components (see the reasoning in [this comment](https://github.com/mongodb/docs-realm/pull/996#discussion_r621395094)).

2021-04-27 17:11 UTC, mongomoe commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +of your objects and then declare a change listener on the {+realm+} objects.
Removed this bit on class components (see the reasoning in [this comment](https://github.com/mongodb/docs-realm/pull/996#discussion_r621395094)).

2021-04-27 17:11 UTC, mongomoe commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +In your component's constructor, create a :reactjs:`ref
Removed this bit on class components (see the reasoning in [this comment](https://github.com/mongodb/docs-realm/pull/996#discussion_r621395094)).

2021-04-27 17:13 UTC, mongomoe commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +Adding Change Listeners to Functional Components
Removed this bit on class components (see the reasoning in [this comment](https://github.com/mongodb/docs-realm/pull/996#discussion_r621395094)). 

But just fyi, here's an article illustrating the difference between the two types of components if you're interested: https://www.twilio.com/blog/react-choose-functional-components#:~:text=Just%20like%20in%20their%20names,which%20has%20a%20render%20method.&text=The%20JSX%20to%20render%20will%20be%20returned%20inside%20the%20render%20method.

2021-04-27 17:56 UTC, mongomoe commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +   Failing to update copies of {+realm+} objects leads to your UI being out of date.
* updated {+realm+} to be {+service-short+}
* changed the sentence to "Failing to update copies of {+realm+} objects leads to your UI being out of date as objects are deleted or changed" (I think this captures both the 'what happens if we don't update copies' and the 'when do state copies become invalid').

2021-04-27 17:57 UTC, mongomoe commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +:reactjs:`useEffect() <docs/hooks-effect.html>` hook, set state to the initial
👍

2021-04-27 18:00 UTC, mongomoe commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +Declare a state variable for your {+realm+} objects using the
👍

2021-04-27 18:04 UTC, mongomoe commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +the component unmounts.
* Good catch, altered Reactjs to be 'React.js' (proper term is either 'React.js' or 'ReactJS' 👍 
* Also, remember that this is a usage example. Like the other usage examples, this presents a procedure without delving into the why. To learn the why, a user should have read/can read: [React Native SDK > Fundamentals > Change Notifications](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-15010-mutable-objects-react-native/sdk/react-native/fundamentals/live-queries/#change-notifications)

2021-04-29 14:17 UTC, nathan-contino-mongo approved these changes
LGTM with a couple of wording nits and a suggestion for code sample maintenance!

2021-04-29 14:17 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +   In the following example, a developer is creating an application to manage
passive voice
```suggestion
   In the following example, a developer creates an application to manage
```

2021-04-29 14:17 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +      :emphasize-lines: 4, 13-17, 29-35
pro tip: you can use bluehawk with the `:emphasize:` bluehawk command and the `-format rst` command-line option to tag these lines directly in the code sample and generate an entire code-block directive that you can literalinclude here. That way we won't have to worry about emphasizing the right lines when we update this example in the future.

2021-04-29 14:17 UTC, nathan-contino-mongo commented on source/sdk/react-native/examples/use-change-listeners-in-components.txt
> +   Failing to update copies of {+service-short+} objects leads to your UI being out of date as objects are deleted or changed.
Similar (but different, for spicyness) reword of "being out of date" phrase:
```suggestion
   Failing to update copies of {+service-short+} objects leads to out-of-date data displayed
   in your UI as objects are deleted or changed.
```

2021-04-29 15:56 UTC, merged