WIP - (DOCSP-12545) .NET progress notifications
mongodb/docs-realm pull request #998
Opened 2021-04-21 15:17 UTC by mongomoe

## Pull Request Info

### Jira

- https://jira.mongodb.org/browse/DOCSP-12545

### Staged Changes (Requires MongoDB Corp SSO)

- [PAGE_NAME](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/BRANCH_NAME/)

### Review Guidelines

[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)

2021-04-21 17:15 UTC, nirinchev requested changes
I think as part of this section, we should definitely mention [`session.WaitForUploadAsync`](https://docs.mongodb.com/realm-sdks/dotnet/10.0.0/reference/Realms.Sync.Session.html#Realms_Sync_Session_WaitForUploadAsync) and [`session.WaitForDownloadAsync`](https://docs.mongodb.com/realm-sdks/dotnet/10.0.0/reference/Realms.Sync.Session.html#Realms_Sync_Session_WaitForDownloadAsync) since those are much easier to use if people just want to make sure that the current changes are uploaded or downloaded and don't care too much about progress.

Additionally, we should add one of those big warnings for the progress API and explain that:
1) Those bytes are estimates and represent the uncompressed data. Since the actual changesets will be gzip-ed before transmitting over the network, the actual transmitted sizes will be much smaller for both transferable and transferred bytes.
2) The callback will not be invoked continuously. I'll explain the technical aspects of it below, but it's up to you to decide how much of that information to convey to users.

For ^: the way sync works is by uploading and downloading changesets. You can roughly think of them as transactions - everything that happens in a `realm.Write(...)` call will be a single changeset. This is the minimum amount of data that can be transferred between callback invocations. So if they insert a billion objects in a single transaction, the changeset may be tens of megabytes large, so it's possible that they get one invocation saying `{ transferred: 0, transferable: 100 MB }` and then a second one saying `{ transferred: 100 MB, transferable: 100 MB }` with no invocations in between. Additionally, the sync server will try to bulk changesets together up to 16 MB in a single message. So if they have 100 small changesets, that are 100 KB each, they'll again get only two callbacks - `transferred: 0` and `transferred: 10 MB`.

For the reasons above, we generally recommend that people use the `WaitForUploadAsync` and `WaitForDownloadAsync` API unless they really want to show some vague progress bar.

2021-04-21 17:15 UTC, nirinchev commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +notification using the `session.GetProgressObservable() <https://docs.mongodb.com/realm-sdks/dotnet/latest/reference/Realms.Sync.Session.html#Realms_Sync_Session_GetProgressObservable_Realms_Sync_Pro
While the example covers it, I think we should mention how a user can obtain a session here as well. This is the first time we're mentioning sessions on this page, so it's very likely that a user is not aware that they exist. Additionally, `GetSession` is an extension method from the `Realms.Sync` namespace. So we should definitely mention that developers need to add `using Realms.Sync` to be able to even access it.

2021-04-21 17:15 UTC, nirinchev commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +- A ``ProgressMode`` parameter that can be set to ``ProgressMode.ReportIndefinitely`` for the notifications to continue until the callback is unregistered, or ``"ProgressMode.ForCurrentlyOutstandingW
Why is `"ProgressMode.ForCurrentlyOutstandingWork"` in quotes while `ProgressMode.ReportIndefinitely` isn't?

2021-04-21 17:54 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +notification using the `session.GetProgressObservable() <https://docs.mongodb.com/realm-sdks/dotnet/latest/reference/Realms.Sync.Session.html#Realms_Sync_Session_GetProgressObservable_Realms_Sync_Pro
Sounds like a good idea, I've altered the first sentence to:

"To check upload and download progress first get the sync session by calling `Realms.Sync.getSession() <link>`_. Then, add a progress notification ..."

2021-04-21 17:54 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +- A ``ProgressMode`` parameter that can be set to ``ProgressMode.ReportIndefinitely`` for the notifications to continue until the callback is unregistered, or ``"ProgressMode.ForCurrentlyOutstandingW
Good catched, fixed now

2021-04-21 17:54 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +Once the notification token is no longer needed, unregister it using ``token.Dispose()``.
👍

2021-05-03 09:31 UTC, nirinchev commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +   Changesets under 16mb only trigger when they are 0% completed or 100% completed. Each consecutive 16mb will trigger a notification. So changesets that are 160mb, will trigger 10 notifications.
These are very rough numbers and may vary in the real world. I think a better wording would be something like "Realm will try to optimize download speeds by combining multiple changesets into a single download message up to 16 MB. Since the progress callback is only invoked once before and after a download message is processed, this means that you'll likely see `transferredBytes` change in increments of roughly 16 MB rather than continuously as the message is being downloaded."

2021-06-03 15:58 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +   .. literalinclude:: /examples/generated/dotnet/ProgressNotifications.codeblock.upload-download-progress-notification.cs
I've included a note telling readers to install https://www.nuget.org/packages/System.Reactive/ now 👍

2021-06-03 15:58 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +You can use progress notifications to display a progress bar. First get the sync session by calling `Realms.Sync.getSession() <https://docs.mongodb.com/realm-sdks/dotnet/latest/reference/Realms.Sync.
Whoops sorry about that, fixed the casing on it now 👍

2021-06-03 15:58 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +
Sounds like a good idea, I've included a slightly altered version of that snippet 👍 :

```
var realm = Realm.GetInstance(config);
await realm.GetSession().WaitForDownloadAsync();
```

2021-06-03 15:58 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +First, get the sync session by calling `Realms.Sync.getSession()
Fixed 👍

2021-06-03 15:58 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +To asynchronously wait for your changes to be completed, create an awaitable `Task <https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task?view=net-5.0>`_ that completes when all pen
I see, sorry for the mixup. I've removed that bit now and hopefully it's a bit more clear 👍

2021-06-03 18:19 UTC, MongoCaleb approved these changes
LGTM except for the code build issues.

2021-06-04 11:50 UTC, nirinchev commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +
I would still recommend including the `using Realms.Sync` either as text around the snippet or in the snippet itself. Since `GetSession` is declared as an extension method in the `Realms.Sync` namespace without the `using`, they'll get an error that is not always obvious how to resolve. We've received a couple of reports already from MongoDB employees that they've been confused by missing usings - https://jira.mongodb.org/browse/DOCSP-15672.

2021-06-04 11:52 UTC, nirinchev approved these changes
LGTM except for this comment: https://github.com/mongodb/docs-realm/pull/998#discussion_r645509941

2021-06-06 23:38 UTC, mongomoe commented on source/sdk/dotnet/examples/sync-changes-between-devices.txt
> +
Added 'using Realms.Sync' now

2021-06-06 23:56 UTC, merged